### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by JensBaumgarten** [clarat-org/clarat#100]
Hier sollte ein Screenshot zu sehen sein...

![screenshot-developer clarat org 2015-01-20 13-01-44](https://cloud.githubusercontent.com/assets/10612933/5816813/15274f2a-a0a5-11e4-872a-706b6d41e5d4.png)

Gruß
Jens

**Comment by Twiek** [comment]
Ist das nicht das gleiche Issue wie #99 ;-)
