### ISSUE TITLE
Backend 2.0 Logik in Operations umziehen

### ISSUE THREAD

**Issue by KonstantinKo** [clarat-org/clarat#1000]

**Comment by KonstantinKo** [comment]
Aktuell: Translation & Assignment Logik

**Comment by NilsVollmer** [comment]
Update: vorhandene Logik transferiert, Tests aktualisiert & ein wenig manuell getestet (fehlende Integration-Tests für React Redux).

TODO:
- [ ] Erweiterung: Assignment braucht ein 'created_by_system' (Naming TBD) - Boolean um automatisch generierte Zuweisungen erkenntlich zu machen & sauber von Nutzer-Zuweisungen zu trennen. Dieses Feld soll komplett automatisch vom Backend auf true gesetzt werden (default: false) und natürlich nicht editierbar sein. Hintergrund ist der, dass das Backend z.T. Zuweisungen erstellt, die weder von noch für den System-Nutzer sind und diese dadurch nicht mehr von manuell erstellen Zuweisungen zu unterscheiden sind.

**Comment by NilsVollmer** [comment]
TODO:
- [ ] Zuweisungslogik minimal aktualisieren: wenn eine neue Zuweisung erstellt werden sollte aber noch eine offene Zuweisung vorhanden ist, soll deren updated_at-Timestamp aktualisiert werden (aktuell passiert nichts: es wird keine neue Zuweisung erstellt und die alte Zuweisung wird nicht angefasst). Analog soll dann in den AssignmentIndexTables anstatt (oder zusätzlich?) zu created_at auch/auf updated_at angezeigt/umgestellt werden.
