### ISSUE TITLE
Zwischenweltangebote abschaffen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1004]
Künftig soll es keine Zwischenweltangebote mehr geben. Dafür soll folgendes umgesetzt werden:

- [ ] Die bisherigen Zwischenweltangebote 'splitten'. Dabei bleibt alles identisch bis auf
* die Welt (hello Captain Obvious -  more like: thank you captain obvious!)
* die Target Audience (gemäß der Identifier verteilen)
* gegebenenfalls das Alter (beim Family Angebot auf max. 17 setzen) 

Nach diesem Schritt bitte die IDs aller betroffenen Angebote hier als Kommentar posten.

- [ ] Validierung, dass man nicht 2 Welten auswählen kann (eventuell ne has_one Beziehung draus machen?)

**Comment by mokus80** [comment]
TO DO BEFORE DEPLOY!!

# Duplicate offers that live in both worlds
# 
# Inside loop
# 1. Duplicate offer: partial_dup method
# New record
# 2. update new record's attributes except id
# 3. set age_to: 17 
# 4. delete section filter and target audience filters that belong to refugee world (section_filter_id: 77)
# 5. save new record (validate: false) to skip validation on slug
# 6. Index in Algolia
# Old record
# 7. delete section filter and target audience filters that belong to family world
# 8. save
# 9. save new record (validate: false) to skip validation on slug
# 10. Reindex in Algolia

common = []
Offer.all.each { |offer| common << offer if offer.section_filters.count > 1 }

common.each do |offer|
  new_offer = offer.partial_dup
  new_offer.assign_attributes(offer.attributes.except('id'))
  new_offer.age_to = 17
  new_offer.section_filters.delete(SectionFilter.find(77))
  new_offer.target_audience_filters.delete(TargetAudienceFilter.where(section_filter_id: 77))
  new_offer.save(validate: false)
  new_offer.update_columns(slug: offer.slug)
  new_offer.index!

  offer.section_filters.delete(SectionFilter.find(76))
  offer.target_audience_filters.delete(TargetAudienceFilter.where(section_filter_id: 76))
  offer.save(validate: false)
  offer.index!

  puts "#{new_offer.id} - #{new_offer.slug}" unless offer.attributes.except('id') == new_offer.attributes.except('id')

end

**Comment by mokus80** [comment]
https://github.com/clarat-org/clarat_base/pull/97
https://github.com/clarat-org/clarat/pull/1113
https://github.com/clarat-org/claradmin/pull/119

**Comment by mokus80** [comment]
Folgende Angebote haben zwei Welten: [8451, 8455, 7036, 7038, 9742, 10365, 7071, 7077, 8555, 8556, 3107, 10700, 7072, 8386, 8385, 8741, 2885, 9041, 9047, 9054, 9071, 9073, 9092, 9087, 9098, 9099, 9105, 9104, 9103, 9107, 9108, 9121, 9120, 3617, 7216, 10778, 9095, 6406, 16081, 9787, 10355, 10356, 10362, 7828, 9089, 10227, 10233, 9060, 3975, 9066, 10779, 9068, 10520, 10522, 10121, 11123, 9070, 9091, 8259, 10707, 9102, 9076, 9086, 9090, 9078, 9083, 9044, 9048, 10523, 9053, 9055, 9057, 9064, 9072, 9074, 9077, 9093, 9094, 9045, 9046, 15218, 9051, 9052, 9056, 9084, 10772, 10660, 997, 13324, 8593, 8456, 8797, 3105, 3106, 13971, 13950, 7829, 3616, 7093, 7040, 7063, 7169, 7173, 7076, 7078, 7166, 7172, 7062, 7060, 7044, 7068, 7088, 7091, 7082, 7061, 7084, 7085, 7073, 7064, 7069, 7075, 7982, 7168, 7170, 7167, 7171, 7174, 9038, 9049, 9069, 9079, 9080, 8008, 7217, 6643, 17353, 1806, 1805, 2886, 5320]

**Comment by mokus80** [comment]
Abfolge Deploy:

1. Task zur Duplizierung der Angebote in der Konsole ausführen (siehe oben)
2. Deploay
3. rake db:migrate
4. Check!

**Comment by mokus80** [comment]
Duplizierte Angebote auf Staging, zB hier:

https://staging.clarat.org/family/angebote/e-mail-beratung-fuer-opfer-von-gewalt
https://staging.clarat.org/refugees/angebote/e-mail-beratung-fuer-opfer-von-gewalt

Backend müsste noch getestet werden.

**Comment by MichiBecker** [comment]
- Reihenfolge trait filter ist unterschiedlich im Frontend

**Comment by mokus80** [comment]
@MichiBecker 
Könntest du bitte im Backend testen, ob alles ok ist, zB:

- Angebot anlegen
- Angebot duplizieren in gleicher Welt und jeweils anderer Welt duplizieren
- kompletter Approval-Prozess, werden die Angebote im Frontend angezeigt? Ist die URL von Angebote, die in jeweils anderer Welt dupliziert werden - bis auf die Welt - identisch?

**Comment by MichiBecker** [comment]
- Notes mit kopieren in beide Welten

**Comment by MichiBecker** [comment]
Duplizieren und "durch-staten" bis approved (ohne etwas zu ändern) funktioniert in beiden Welten. 

Wenn ich etwas ändere im duplizierten Angebot:

bei family an Titel "test" drangehangen: Anzeige in App produziert 404 Fehler

bei refugees geht alles

**Comment by mokus80** [comment]
@MichiBecker 
Folgende Zwischenweltangebote haben keine Target Audience Filter:

[3616, 3617, 3975, 9120, 9121, 9742, 9787, 10121, 10227, 10233, 10355, 10356, 10362, 10365, 10700, 10707, 10778, 10779]
