### ISSUE TITLE
Crawler ignorieren Häkchen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1006]
Manchmal markiert der Crawler Webseiten als 'kaputt' die es aus menschlicher Sicht nicht sind (für Ottonormaluser sieht alles schick aus, aber der Crawler sieht nur 404 etc.). In solchen Fällen muss es dem Researcher möglich sein die Webseite künftig vom Crawler-Check auszunehmen.

Dies sollte im Backend im Rahmen der Webseite umgesetzt werden (per Häkchen ;-).

**Comment by Twiek** [comment]
Bereits in #994.

**Comment by NilsVollmer** [comment]
Vorschlag: direkt auch mit Validierung auf Angebots- und Orgaebene, dass alle zugeordneten Websites Reachable oder ignored_by_crawler sein müssen.

**Comment by Twiek** [comment]
Abwarten wie der neue Crawler performt (immer noch zu sensibel?) und dann eventuell das explizite Häkchen einführen (und Zuweisungen statt Asana-Task, Crawler schon bei jedem Website-Save laufen lassen und dann das Häkchen zwingend setzen... ).

**Comment by Twiek** [comment]
@Twiek Überlegen ob Task für Comms erstellt wird.
