### ISSUE TITLE
Alle externe Links gehen in neuem Tab auf

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#101]
Bitte Vorschlag machen wie das am besten umgesetzt werden kann (also z.B. jeden Ort an dem ein externer Link gesetzt werden kann individuell anfassen etc.).

**Comment by KonstantinKo** [comment]
Option (`target:"_blank"`) muss direkt beim Link gesetzt werden. In Links die von Researchern gesetzt werden, muss das auch von ihnen beachtet werden.

Man beachte, dass diese Option kein valides HTML5 ist, in der Praxis aber von Browsern verstanden wird.

Falls eine automatisiertere Lösung gewünscht wird, könnte ich dafür JS schreiben.

**Comment by Twiek** [comment]
Wird erstmal nur händisch von den Researchern umgesetzt.
