### ISSUE TITLE
clarat Startseite in englischer Sprache kaputt

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1017]
Der Text für family wird nicht komplett angzeigt. Bitte versuchen das so hinzubekommen, dass die Textfelder von Family und Refugees nicht out of sync aussehen, also vermutlich die gleiche Höhe bekommen.

![bildschirmfoto 2017-02-22 um 14 27 54](https://cloud.githubusercontent.com/assets/432388/23213515/823550ec-f90b-11e6-8faf-511020c60b45.png)

**Comment by marcus-herrmann** [comment]
Fix liegt bereit auf https://github.com/clarat-org/clarat/tree/fix/1017-frontpage-english-text

**Comment by Twiek** [comment]
![bildschirmfoto 2017-02-23 um 13 44 32](https://cloud.githubusercontent.com/assets/432388/23259614/4036de54-f9ce-11e6-93ba-ffc2c9e8b0c7.png)

Könnte man den kürzeren Text bei Refugees eventuell noch vertikal zentrieren (gerne dann allgemein, also auch bei den Sprachen bei denen es dort nur eine Zeile Text gibt (Türkisch, Polnisch... ), oder gibt es dann Problemen mit der 'Pfeilspitze'?

**Comment by marcus-herrmann** [comment]
Branch aktualisiert

**Comment by Twiek** [comment]
Looks good!
