### ISSUE TITLE
Falsche Pfeilrichtung arabische Startseite

### ISSUE THREAD

**Issue by OmarAlsabbagh** [clarat-org/clarat#1019]
- clarat arabisches Homepage
- Google Chrome Version 56.0.2924.8
- Man erwartet RTL-Pfeilrichtung auf den Buttons zu sehen.
![13](https://cloud.githubusercontent.com/assets/20440875/23262363/ae3c7c40-f9da-11e6-9dd4-e3d4f1c19784.jpg)

**Comment by marcus-herrmann** [comment]
Fixed. PR hier: https://github.com/clarat-org/clarat/pull/1085

**Comment by Twiek** [comment]
@marcus-herrmann Leider sind die Pfeile noch immer auf der falschen Seite. Die Orientierung ist zwar richtig, aber die Pfeile müssen jeweils rechts neben dem Wort sein, nicht am linken Rand.

![bildschirmfoto 2017-04-07 um 18 27 24](https://cloud.githubusercontent.com/assets/432388/24809461/e23faa24-1bbf-11e7-9141-a84d38825bd7.png)

**Comment by marcus-herrmann** [comment]
Branch mit dem Fix aktualisiert

**Comment by Twiek** [comment]
Sieht in Arabisch und Farsi jetzt gut aus, aber dafür nicht mehr im Deutschen:

![bildschirmfoto 2017-04-13 um 10 24 44](https://cloud.githubusercontent.com/assets/432388/24996525/7bb027b6-2033-11e7-84de-4dae08123dec.png)

**Comment by marcus-herrmann** [comment]
Verdammt, statt Zeile kopieren habe ich die Zeile ausgeschnitten. Korrigiert

**Comment by KonstantinKo** [comment]
siehe PR

**Comment by marcus-herrmann** [comment]
PR conflict gelöst
