### ISSUE TITLE
Graue Karte bei den Suchergebnissen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#102]
Bei einigen Suchen wird die Karte nicht richtig angezeigt. Beispiel: http://developer.clarat.org/angebote?utf8=%E2%9C%93&search_form%5Bquery%5D=esst%C3%B6rung&search_form%5Bsearch_location%5D=Berlin&search_form%5Bgenerated_geolocation%5D=52.520007%2C13.404954&search_form%5Btags%5D= (Suche nach 'esstorung' in Berlin).

Screenshot:
![bildschirmfoto 2015-01-21 um 14 18 57](https://cloud.githubusercontent.com/assets/432388/5836665/7dc1729e-a178-11e4-8c3f-9ecfe5521856.png)

**Comment by KonstantinKo** [comment]
Problem war, dass einige alte Locations (17) keine Geokoordinaten hatten. Als ich sie jetzt alle noch einmal angetriggert habe, haben sie sofort die Daten bekommen. Ich hab's auch hoffentlich etwas Fehlerresistenter gemacht, kann den Ernstfall aber nicht wirklich simulieren, da ich keine Ahnung hab, warum die keine Koordinaten bekommen haben. Wir sollten das im Auge behalten.
