### ISSUE TITLE
Backend 2.0: Redirect on session expiration

### ISSUE THREAD

**Issue by KonstantinKo** [clarat-org/clarat#1022]
Wenn man zu lange im neuen backend nichts gemacht hat, versagt einfach die Seite bei jedem Klick weil die ajax requests im Hintergrund nicht mehr beantwortet werden.

Vermutlich muss man eine middleware schreiben, die Authorization-Fehler abfängt und einen auf die Login-Seite weiterleitet.

**Comment by KonstantinKo** [comment]
Ich hatte gerade das alert Fenster 2 mal direkt nacheinander bevor ich zur Login-Seite weitergeleitet wurde. Falls es einen Unterschied macht, es ist auf der organizations/new Seite passiert.

**Comment by allthegoldt** [comment]
Habe es bei mir lokal (mit timeout = 1.min) mehrfach getestet und konnte es nicht reproduzieren. Ich vermute mal, dass es eine Ausnahme war.
