### ISSUE TITLE
Reorganisation der States

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1026]
Aktuelles Schaubild: https://docs.google.com/drawings/d/1l2DUm1T0jVVbFIk9icGwOoimoax6yk7-LHpxMn-TguA/edit

Es werden einige states verschwinden, andere kommen hinzu und eine Transition funktioniert künftig anders:

- [x] Refactoring: State-Machine Logik von clarat_base in claradmin umziehen.
- [x] Die states 'doze' und 'under_construction_pre' fallen weg. Alle Angebote die dort bisher sind werden in den state 'internal_feedback' versetzt. Vor deploy eine Liste mit den IDs dieser Angebote erstellen und mir per E-Mail schicken + in den Notizen "Ehemaliger State: 'doze' " bzw. 'Ehemaliger State: 'under_construction_pre'" ergänzen.
- [x] Wechsel von 'completed' zu 'initialized' unmöglich mache (one way street).
- [x] Neuen state 're_edit' erstellen. In diesem kann das Angebot bearbeitet werden. Man kann von 'completed' und 'disapproved' hinwechseln. Von 're_edit' kann man ausschließlich zu 'completed' wechseln. Das Wording des Buttons lautet: 'Erneut bearbeiten'.
- [x] Neuen state 'disapproved' erstellen. Zu diesem kommt man ausschließlich vom state 'approval_process'. In diesem kann das Angebot nicht bearbeitet werden. Von diesem kann man ausschließlich in den state 're_edit' wechseln. Er dient dazu die Wartezeit zu messen, also wie lange es dauert bis sich ein Researcher einem Angebote wieder annimmt welches es nicht durch den Approval-Process geschafft hat. Das Wording des Buttons lautet 'Disapprove'.

**Comment by NilsVollmer** [comment]
Deploy TODO: 

```ruby
Offer.where(aasm_state: 'dozing').update_all(aasm_state: 'TODO')
Offer.where(aasm_state: 'under_construction_pre').update_all(aasm_state: 'TODO')
Offer.where(aasm_state: 'under_construction_post').update_all(aasm_state: 'under_construction')
```

**Comment by NilsVollmer** [comment]
@Twiek Frage nach Erweiterung: da wir ab und zu invalide (weil abgelaufene) Angebote haben, die dann in einem non-edit state festhängen und wir ja mittlerweile auch abgelaufene Angebote im Frontend lassen, können wir die Validierung vllt. nochmal überdenken. Komplett rausnehmen würde ich sie aber nicht.. man könnte sie z.B. nur im state 'approved' durchführen.
