### ISSUE TITLE
Anzeigen der Punkte auf individueller Ebene

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1028]
Alles hier aufgeführten Anzeigen sind erstmal ausschließlich für den jeweiligen User sichtbar, d.h. in Version 1 sieht jeder ausschließlich seine eigenen Zahlen.

Must have:

- [x] Es werden auf individueller Ebene 'Completed-Punkte' für den Wechsel von 'initialized' oder 'checkup_process' zu 'completed' vergeben. Für den Wechsel von 're-edit' zu 'completed' werden keine Punkte vergeben.
- [x] Es werden auf individueller Ebene 'Approved-Punkte' für den Wechsel von 'approval_process' oder 'checkup_process' zu 'approved' oder 'seasonal_pending' vergeben.

In beiden Fällen werden die Punkte unabhängig davon gezählt, in welchem Team der Backenduser gerade unterwegs ist. Es ist nur die Gesamtzahl relevant.

- [x] Jeder Backenduser sieht in seinem Dashboard (oder einer speziellen Seite) seine absoluten Zahlen für das aktuelle Jahr. Also z.B. 'Approved: 87, Completed: 113'). Diese Zahlen sind andere eingeloggte User auch dann nicht sichtbar, wenn man über einen direkten Link verfügt. Möglichkeiten sich per Console etc. 'reinzuhacken' sind hinnehmbar, müssen aber im Rahmen des Issues außerhalb von Github dokumentiert werden.

Nice to have:

- [x] Jeder Backenduser sieht in seinem Dashboard (oder einer speziellen Seite) zusätzlich seine Zahlen pro Woche (Tabellenansicht) 
- [x]  Jeder Backenduser sieht in seinem Dashboard (oder einer speziellen Seite) einen (oder zwei) Diagrammen in dem der realen Fortschritt (auf Wochenbasis) für die 'Approved-Punkte' und 'Completed-Punkte' angezeigt wird.

**Comment by KonstantinKo** [comment]
Übersetze das mal für mich in aktuelle Statistik-Logik:

- Ziele müssen mehrere Statewechsel zusammenrechnen können.
- Ziele müssen für einzelne Nutzer anlegbar sein, nicht nur für Teams
- Es muss ein "Completion" Ziel für jeden Nutzer geben, nach dem X Offer-Statewechsel von initialized->completed + checkup_process->completed geschafft werden müssen.
- Es muss ein "Approve" Ziel für jeden Nutzer geben, nach dem X Offer-Statewechsel von checkup_process->approved + approval_process->approved geschafft + checkup_process-> seasonal_pending + approval_process-> seasonal_pending geschafft werden müssen.
- Obige Ziele müssen jährlich für das aktuelle Jahr erstellt werden (evtl. automatisiert per Dateneingabe von Anne) - oder implizit existieren
- Später: Eine Ziel-Anzeige soll nach Möglichkeit mehrere Linien übereinander anzeigen können (Complete & Approve gleichzeitig)
- Zusätzlich: Wie oben beschrieben, Ausgabe der einzelnen wöchentlichen Zahlen zusätzlich als Tabelle

**Comment by Twiek** [comment]
In dem Rahmen gerne die Soll/Ist Stundenübersicht im Dashboard ersatzlos streichen (nicht mehr anzeigen).

![bildschirmfoto 2017-03-08 um 14 05 12](https://cloud.githubusercontent.com/assets/432388/23705121/7acf1d9e-0408-11e7-9946-b1690400ed27.png)

**Comment by KonstantinKo** [comment]
DEPLOY TODO: Alle bestehenden Productivity Goals löschen.

**Comment by KonstantinKo** [comment]
Ausstehende Verbesserungen: 

- Nicht alle Statistiken auf einmal laden (können sehr viele werden) sondern Schrittweise
- Automatisierte Ziel-Eingabe
- Dateien-Verteilung der Komponenten für BurnUpChart sollte verbessert werden
- "Meine Ziele" ein- und ausklappbar machen. Standardmäßig eingeklappt. (Sicherheit vor "Über-Schulter-Blicken")
- MouseOver in Chart sollte Daten an gewählter Stelle zeigen
- Mehrere Linien in einem Chart

**Comment by NilsVollmer** [comment]
Bitte noch zu erledigende Sachen in neue Issue ziehen.

**Comment by KonstantinKo** [comment]
Bin mit dem Auslagern soweit fertig

**Comment by NilsVollmer** [comment]
@Twiek Dann ist das Issue hier vermutlich fertig.
