### ISSUE TITLE
Paginate the Pagination

### ISSUE THREAD

**Issue by KonstantinKo** [clarat-org/clarat#1030]
<img width="1197" alt="screen shot 2017-03-02 at 12 04 16" src="https://cloud.githubusercontent.com/assets/779660/23504613/a200d032-ff40-11e6-8456-fd78c87ed32f.png">
Wenn es viele Seiten gibt, werden zu viele Seiten-Links ausgerendert.

Zum Einarbeiten in React, Redux, und unsere JSONAPI-Schnittstelle.

**Comment by NilsVollmer** [comment]
Könnt ihr als Übung ja vllt. als Pair-Programming angehen, da React/Redux für euch beide wahrscheinlich Neuland ist.

**Comment by allthegoldt** [comment]
We still have to implement it for inlinePagination
