### ISSUE TITLE
Residency Status - Update

### ISSUE THREAD

**Issue by MichiBecker** [clarat-org/clarat#1034]
Hallo,

hier kommt ein Issue, was sich vielleicht für ein Mini Feature qualifizieren könnte für den nächsten (oder übernächsten) Sprint? Korrigiere mich wenn ich falsch liege.

Residency Status "before the assylum procedure" und "During the asylum procedure" gibt es nicht mehr.

Beide Stati bekommen rückwirkend den neuen Status "before the asylum decision"?

Caption füs Frontend: "Vor der Asylentscheidung"

Das war's

**Comment by NilsVollmer** [comment]
Was (mindestes) zu tun ist - kein Anspruch auf Vollständigkeit: 
- [ ] nicht mehr benötigte Einträge aus dem Enum-Array entfernen
- [ ] Stamp-Logik überprüft und ggf. nicht benötigten Code entfernen
- [ ] nicht mehr benötigte Einträge in localeapp löschen (Projekt: clarat_base)
- [ ] falls das Wording 'Vor der Asylentscheidung' neu ist, brauchen wir auch neue Übersetzungen dafür in localeapp
- [ ] nach dem Deploy per Konsole alle Angebote, die einen der beiden zu löschenden Residency_status haben, rauspicken, in einem Array speichern. Dann mit dem noch vorhandenem residency_state überschreiben und für diese Angebote (deshalb wegspeichern) den Algolia-Index neu generieren.

**Comment by MichiBecker** [comment]
Update: iPM hat anscheinend noch kein offizielles GO von Anne.

Bitte noch nichts anfangen. Ich geb nochmal bescheid, wenn das geklärt ist.

In welche Pipeline kommt das in diesem Falle? Icebox?

**Comment by MichiBecker** [comment]
@Twiek es gibt jetzt ein GO.

Kannst du das einplanen für den Deploy am 27. März?
(da das Team noch Zeit braucht, die Wissensquellen etc vorzubereiten etc)

Merci

**Comment by Twiek** [comment]
@MichiBecker Sprich mich dazu bitte kurz an.

**Comment by mokus80** [comment]
Für die Änderungen in clarat_base gibt es einen Pull Request. 

Noch zu tun:

1. Bundle update auf Claradmin 

2. Deploy-To-Do: Zu löschende residency_status ' s in einem Array speichern, neuen residency status zuweisen und bei Algolia indizieren.

3. Alte Translations in Localeapp löschen

**Comment by NilsVollmer** [comment]
@mokus80 bitte in PRs immer das Issue (in diesem Fall clarat-org/clarat#1034 ) referenzieren damit man den PR nicht suchen muss.

**Comment by NilsVollmer** [comment]
clarat_base PR ist merged.

Wichtig: Deploy TODO in das Issue schreiben, damit jeder es deployen kann!

**Comment by Twiek** [comment]
@mokus80 Ist hier noch was zutun, oder ist das ready to go? Wenn letzteres, dann bitte in die entsprechende Pipeline ziehen.

**Comment by mokus80** [comment]
Deploy To Do:

list = Offer.where(residency_status: 'before_the_asylum_application') + Offer.where(residency_status: 'during_the_asylum_procedure')

list.each do |o|
  o.residency_status = 'before_the_asylum_decision'
  o.save
  puts "#{o.residency_status} saved for offer #{o.id}"
end

Auf Staging getestet. Residency_status wird geändert, Änderungen in Algolia indiziert. 13 Angebote konnten nicht mit dem neuen Status upgedatet werden, da ihr Ablaufdatum in der Vergangenheit liegt (Validierung). Das können wir laut Michi ignorieren.

Nach Ausführung des Task können die alten Übersetzungen in Localeapp gelöscht werden.

**Comment by MichiBecker** [comment]
@Twiek es gab ja eine Anfrage von Sabine wegen doppelter Angebote.

Wurde wohl bei Auftrag nicht bedacht, dass es dann dadurch:
"Beide Stati bekommen rückwirkend den neuen Status "before the asylum decision"?"

doppelte identische Angebote gibt.

Frage: Kann man in der Konsole herausfinden welche Angebote identisch sind? und eins davon löschen?

ahhhh hab ne idee: wenn ich nen export bekomme von allen Angeboten mit "before the asylum decision" +offer id +  titel kann ich die in sheets sortieren und euch dann die IDs zurück geben, die gelöscht werden können
