### ISSUE TITLE
Kontrast der Filter im neuen Backend anpassen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1036]
Hier brauchen wir deutlich mehr Kontrast:

![bildschirmfoto 2017-03-08 um 13 42 28](https://cloud.githubusercontent.com/assets/432388/23704420/286ccd6a-0405-11e7-910e-0a603d3dbf2c.png)

In dem Rahmen gerne Vorschlag für die Farbgebung im Backend machen (die aktuellen Farben sind weitgehend willkürlich vergeben bzw. kommen vom Theme). Hier aber nicht zu viel Zeit investieren.

**Comment by marcus-herrmann** [comment]
![bildschirmfoto 2017-03-08 um 16 02 02](https://cloud.githubusercontent.com/assets/505181/23709109/a4cc142a-0418-11e7-9fe5-853029adb116.png)

Zum besseren Contrast: Die Komponente hatte einen Invers-Mode, der aktiv war. So sieht er deaktiviert aus

**Comment by marcus-herrmann** [comment]
Vorschlag: 

![bildschirmfoto 2017-03-08 um 18 11 51](https://cloud.githubusercontent.com/assets/505181/23714884/1d409310-042b-11e7-972c-bdef7ec5a0e5.png)

**Comment by Twiek** [comment]
Yup, schaut gut aus. Bitte so umsetzen.

**Comment by marcus-herrmann** [comment]
Liegt auf Commit 83c94e4cb8b52eebdfa293f00bbec7352095d729 bereit

**Comment by marcus-herrmann** [comment]
@Twiek PR ist nicht gestellt, da #944/claradmin, also nicht mein eigener Branch

**Comment by Twiek** [comment]
Noch auf #1051 warten.

**Comment by marcus-herrmann** [comment]
PR auf @KonstantinKo 's Bitte hin gestellt
