### ISSUE TITLE
Filtering: Range-Filter

### ISSUE THREAD

**Issue by NilsVollmer** [clarat-org/clarat#1041]
Im Moment kann jedes filterbare Modell mit genau einem Operator und einem Wert gefiltert werden (z.B. 'name' genau gleich 'einWert' oder 'created_at' kleiner als '1.1.2017'). Gerade für Datums-Felder  wäre eine Range Filter (vor 'wert1' und nach 'wert2'). Eine mögliche Umsetzung ist eine Range-Formatierung wie Ruby es macht (z.B. '1.1.2017...1.7.2017') oder einer Version mit zwei Eingabefeldern, bei der das zweite nur angezeigt wird, wenn man als Operator 'zwischen' ausgewählt hat.

**Comment by mokus80** [comment]
Pull Request: https://github.com/clarat-org/claradmin/pull/130

Hinweis: Da sie refactored werden müsste, habe ich die Suche im Dashboard deaktiviert. Die Dateien sind noch vorhanden.

**Comment by mokus80** [comment]
Ist auf Staging zum Testen.

**Comment by NilsVollmer** [comment]
TODO für mich: kurz prüfen, wie hoch der refactoring-Aufwand ist und dann mit Nicole sprechen.

**Comment by NilsVollmer** [comment]
@mokus80 aktueller Develop ist gemerged, tests entsprechend angepasst & hinzugefügt und die coverage ist bei 100%. Bitte noch die größer/kleiner Abfrage rausnehmen, sodass man den RangeFilter auch bei größeren Zahlen benutzen kann.

**Comment by NilsVollmer** [comment]
@mokus80 Ich habe noch einen TODO-Kommentar gefunden. Schau da bitte nochmal drüber, ob das erledigt ist oder noch fehlt. Ansonsten gerne auch mal meine Commits von heute auf dem Branch angucken - Refactoring & Code Styling ;)

Davon abgesehen passt der PR.. not the prettiest Code but it gets the job done.
