### ISSUE TITLE
Editieransicht-Bugs im neuen Backend

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1049]
Wenn ich hier http://claradmin.herokuapp.com/offer_translations oder hier http://claradmin.herokuapp.com/organization_translations auf den Editierbutton klicke, dann sollte sich die Seite nicht 'totladen'

![bildschirmfoto 2017-03-15 um 17 22 58](https://cloud.githubusercontent.com/assets/432388/23958967/138dc6c0-09a4-11e7-8993-2a7da332d8f2.png),

sondern die Möglichkeit gegeben werden, dass ich mir das selber zuweisen kann (mit Textfeld, aber ansonsten ähnlich wie hier):

![bildschirmfoto 2017-03-15 um 17 22 08](https://cloud.githubusercontent.com/assets/432388/23959269/07d0e096-09a5-11e7-9bf6-dd80e4852fee.png)

Davon möglicherweise unabhängig taucht das 'totladen' Problem auch dann auf, wenn ich in meinem Dashboar auf den Editierbutton einer Zuweisung klicke, aber versuche das in einem neuen Tab aufzumachen.

**Comment by NilsVollmer** [comment]
Als hotfix direkt auf master umgesetzt & deployed.
