### ISSUE TITLE
Possibly outdated Translations auch ohne Änderung speichern können.

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1050]
Manchmal gibt es keinen Grund an der Übersetzung was zu ändern. In diesem Fall will ich das speichern können, ohne dass ich eine Pseudoänderung vornehmen muss.

Bug, da es eigentlich schon mal ging.

**Comment by NilsVollmer** [comment]
? Wurde das als Bug von den Übersetzern reportet? Eigentlich funktioniert es so, dass man es sich zuweist und die Zuweisung direkt wieder schließt. Dadurch wird es dann als source=translator gespeichert.

Funktioniert das im Moment nicht?
