### ISSUE TITLE
Designsprache für das neue Backend

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1051]
Bitte für das neue Backend einen Vorschlag für eine ganz lose an das Frontend angelehnte Designsprache entwickeln (also Standardfarben etc.). Falls es sich anbietet gerne auch den Code anpassen (aber im Hinterkopf behalten, dass wir Bootstrap vielleicht mal updaten, also große Änderungen nur nach Absprache).

Als Basis gerne die Zuweisungstabelle und die W&A-Statistiken nehmen.

**Comment by marcus-herrmann** [comment]
Hier eine erste Skizze. Disclaimer: Ich habe nicht wirklich seriös gecheckt, ob ich das alles mit dem bestehenden HTML umsetzen kann und ob es nicht ein riesiger Berg Arbeit ist. Aber: grob diese Richtung würde ich vorschlagen: Ein wenig Farbcodierung (Tabellen grün, Sektionen beige, Tabreiter blau, Hauptnavigation gelb etc).

![claradmin_designfindung_1](https://cloud.githubusercontent.com/assets/505181/23997374/6adca092-0a51-11e7-8771-b5df70ae70b9.png)

**Comment by Twiek** [comment]
I like it. Bitte hier noch mal die Filter aus #1036 ergänzen (sind hier im Screenshot ja ausgespart) und dann checken was davon wie leicht umgesetzt werden kann. Hier gerne in der ersten Runde sehr pragmatisch vorgehen, also keine Zeit mit Minidetails verbringen + es reicht, wenn das in Chrome funktioniert (die Researcher benutzen ohnehin fast alle Chromebooks).

**Comment by marcus-herrmann** [comment]
Filter ergänzt:

![artboard](https://cloud.githubusercontent.com/assets/505181/24247279/56d67ba2-0fcb-11e7-949e-bd2f03ddcf3c.png)

**Comment by marcus-herrmann** [comment]
> und dann checken was davon wie leicht umgesetzt werden kann

Erkenntnis: Wenn ich das Bootstrap-Theme flat-ui ausbaue (und nicht umständlich versuche zu überschreiben, sollte ich in einem Personentag viel erreichen können. Ich kann aber nicht ausschließen, dass ich einige Interfaceelemente mangels Zugang noch gar nicht gesehen habe und ich deswegen die Schätzung korrigieren muss
