### ISSUE TITLE
Statistiken: W&A-Ziele per Standard verstecken

### ISSUE THREAD

**Issue by KonstantinKo** [clarat-org/clarat#1052]
Ich als Backend-Nutzer möchte nicht, dass jemand über meine Schulter schauend meine W&A Zielerreichungen sieht, wenn ich auf meinem Dashboard bin.

Schlage vor, den Reiter mit einer Akkordeon-Ein-und-Ausklapp-Funktion zu versehen. Diesen dann gleich allgemein für Tab-Reiter verfügbar machen. Willkommensreiter standardmäßig ausgeklappt lassen.

**Comment by NilsVollmer** [comment]
@marcus-herrmann Im neuen Backend (Dashboard) gibt es jetzt zwei CollapsiblePanels, die (wie der Name sagt ^^) collapsible sind. Da die Funktionalität für den Nutzer gerade nicht sehr intuitiv ist, wollen wir den Link je nach state anpassen. Vermutlich kann man da mit aria-expanded arbeiten?! Sprich mich bei Gelegenheit einfach mal darauf an - dann können wir bestimmt schnell eine Lösung finden.

**Comment by KonstantinKo** [comment]
@NilsVollmer bitte noch auf react/redux refactoren

https://react-bootstrap.github.io/components.html#panels-collapsible

**Comment by NilsVollmer** [comment]
Update: eine vorläufige Version ist jetzt bereits deployed weil es für die Team-Statistiken wichtig war/ist. Dieses Issues ist somit jetzt ein Refactoring-Issue (siehe Kommentar von @KonstantinKo )

**Comment by NilsVollmer** [comment]
TODO: 
- [ ] CursorPointer bei Rollover über Header
- [ ] Loading Indicator für große Datensätze
- [ ] optional: hover state auf komplettem Header & HeadText fett/größer
