### ISSUE TITLE
Statistiken: Schrittweise nachladen

### ISSUE THREAD

**Issue by KonstantinKo** [clarat-org/clarat#1056]
Von Statistiken werden aktuell 9999 in einem ajax request geladen. Gibt es mehr relevante (unwahrscheinlich aber theoretisch möglich), werden diese nicht mit einbezogen. Gibt es viele, wird dies ein sehr langsamer request.

Stattdessen sollten weniger auf einmal geladen werden und while(nächste Seite exisitert) { Statistiken von nächster Seite laden und zu den aktuell in Betracht gezogenen hinzufügen }

**Comment by NilsVollmer** [comment]
Wird im Zusammenhang mit #1064 umgesetzt.

**Comment by NilsVollmer** [comment]
TODO:
- [x] Nachladen in kleinen Chunks
- [ ] Fix: User-Selection funktioniert noch nicht (kein redraw)
- [ ] Fix if possible: spinner wird nach jedem Chunk neu geladen (springt in der Animation zurück.. zum debuggen sogar ganz praktisch)

**Comment by NilsVollmer** [comment]
Aktuell auf staging deployed um es mit tatsächlichen Daten zu testen
