### ISSUE TITLE
Locationvorschläge bei Angebotserstellung im Adminbereich neu strukturieren

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#106]
![bildschirmfoto 2015-01-22 um 11 12 31](https://cloud.githubusercontent.com/assets/432388/5853854/d4eca9ee-a227-11e4-9ce7-6591296fe7e3.png)

Wenn man ein Angebot erstellt und eine Location hinzufügen will werden aktuell folgende Informationen in den Vorschlägen angezeigt:
'Name der Location (Straße PLZ Ort)'
Künftig soll es wie folgt erscheinen:
'Name der Organisation der Location, Name der Location (Straße PLZ Ort)'
Es ist bekannt, dass die aktuelle Datenlage dazu führen wird, dass der Name der Organisation dann vorerst oft doppelt erscheint und die Vorschläge insgesamt sehr lang sein können.

**Comment by KonstantinKo** [comment]
Rückmeldung von Researchern: Organisationsname kann nicht durchsucht werden

**Comment by KonstantinKo** [comment]
Nun geht es endlich. Getestet mit "Arbeit und Bildung" / "Check Up"
