### ISSUE TITLE
Wochen statt Tagesansicht in den W&A Statistiken

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1060]
Die Tabelle sollte nicht einzelne Tage, sondern Kalenderwochen anzeigen (Wording: 'KW 1', 'KW 2'... ). Auch Wochen in denen kein completed/approved erzielt wurde sollen angezeigt werden (dann mit der Zahl 0).

**Comment by NilsVollmer** [comment]
Duplicate auf #1061
