### ISSUE TITLE
Statistiken: Tabelle verkleinern

### ISSUE THREAD

**Issue by KonstantinKo** [clarat-org/clarat#1061]
Als Backend-Nutzer möchte ich auch bei vielen vorhandenen Datenpunkten die Übersicht behalten, wann ich wie viele "Punkte" bekommen habe. Die aktuelle Tabelle kann sehr lang werden.

Entweder die Punkte zu Wochen zusammenfassen oder - meiner Meinung nach noch besser - die Tabelle paginieren (z.B. nach Monaten).

**Comment by NilsVollmer** [comment]
Bastis Text aus duplicated Issue:

Die Tabelle sollte nicht einzelne Tage, sondern Kalenderwochen anzeigen (Wording: 'KW 1', 'KW 2'... ). Auch Wochen in denen kein completed/approved erzielt wurde sollen angezeigt werden (dann mit der Zahl 0).

**Comment by NilsVollmer** [comment]
@Twiek Sollen dann wirklich bis zu 56 Einträge (am Ende des Jahres) erscheinen und keiner interessiert sich mehr für die täglichen Zahlen? Ich höre da nur direkt den nächsten Feature-Request in die Richtung 'kann man das nicht so machen, dass beim anklicken die Tagesansicht aufklappt' heraus.

Warum nicht z.B. die Daten (nach Monaten) paginieren? Und sollen die 0er Werte wirklich redundant mit angezeigt werden? Das wären dann auch alle Wochenenden und ausschliessen können wir die wahrscheinlich auch nicht, weil manche Researcher (Franzi fällt mir da ein) tatsächlich am Wochenende was machen..

Lass uns dazu am besten nochmal sprechen.

**Comment by Twiek** [comment]
Also in meinem Kopf wären es max. 53 Einträge (solange das Jahr bei 365 Tagen bleibt... ;-).

Anyway. 0er Werte bitte auf jeden Fall mit anzeigen. In einer Woche nichts gemacht zu haben ist ja auch eine Information, macht dann allerdings auf Wochenbasis mehr Sinn als für einzelne Tage. Denke auch insgesamt, dass hier eine aggregierte Ansicht nützlicher ist, so dass ich mir vorstellen kann, dass ein erneuter Featurewunsch eher in die Richtung geht Monate statt Wochen anzuzeigen, aber who knows. Kurzfristig erschien mir der Wunsch Wochen statt Tagen anzuzeigen ziemlich klar, insofern würde ich erstmal dabei bleiben. Weitere Änderungen gibt es dann erst, wenn wir wirklich relevante Praxiserfahrungen haben, also sicher nicht vor Q3 und dann in Kombination mit weiteren Anpassungen.

**Comment by Twiek** [comment]
Ok, dann lass uns wie besprochen folgendes anpeilen:

![bildschirmfoto 2017-03-17 um 11 58 36](https://cloud.githubusercontent.com/assets/432388/24040338/1e15f2be-0b09-11e7-9854-47e8b0f400a7.png)


Also Jahresziel und Jahres-Ist einmalig überhalb der Tabelle anzeigen. Dann die Monate als Spalten (jeweils die Summe der pro Monat erzielten Punkte neben/unter den Monat) und dann darunter die einzelnen Tage (dort dann auch 0er Ergebnisse anzeigen). Nice-to have wäre wenn die nicht existenten Tage (30. Februar) statt '0' ein '-' bekommen.
