### ISSUE TITLE
Farsi online stellen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1062]
Bitte um Rückmeldung, sobald wir das auf Staging testen können.

**Comment by NilsVollmer** [comment]
TODOs, die mir jetzt direkt aufgefallen sind:

- [ ] in localeapp fehlen noch einige Einträge (nicht vergessen: die Sprache Farsi für die NavBar oben muss in allen Sprachen hinzugefügt werden)
- [ ] sehr viele CSS-Fixes für arabisch fehlen für Farsi noch (.ar oder ar. in css files) und deshalb sieht alles noch sehr kaputt aus

**Comment by NilsVollmer** [comment]
@Twiek auf staging aufgespielt

**Comment by Twiek** [comment]
@marcus-herrmann Ist aktuell auch auf Staging. Das Design ist momentan noch ziemlich zerschossen.

**Comment by marcus-herrmann** [comment]
Besteht die Möglichkeit, dass das Farsi-Locale-Kürzel anders als `.fa` lautet? `.far` oder so? Das beißt sich mit Font-Awesome (ebenfalls .fa) und sorgt für die gröbsten Fehldarstellungen. Ansonsten refaktore ich gerade RTL, sodass die RTL-Optimierungen nicht mehr nur mit .ar zu tun haben, sondern alle RTL-Sprachen (eben auch farsi)

**Comment by marcus-herrmann** [comment]
Nevermind, [ich konnte es unelegant lösen](https://github.com/clarat-org/clarat/commit/ce7b566c14c7e7d0471fdbad63000361d75d106d#diff-1ccd3e5828c7330cdc2450c78847cd35R2). Ready for review
