### ISSUE TITLE
Ausnahmeregelung in den Mailings für große Orgas aufheben

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1063]
Also die 'big_player?' Methode und alles was daran hängt löschen (auch eventuelle Tests etc.).

**Comment by mokus80** [comment]
Es gibt nur eine Handvoll 'big_player', die "mailings: 'big_player'" gesetzt haben. Die können nach dem Deploy händisch auf 'enabled' gesetzt werden.

**Comment by NilsVollmer** [comment]
@mokus80 Also
