### ISSUE TITLE
Team-Ziele

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1064]
Researcher sollten im Backend künftig nur noch einem einzigen Team zugeordnet sein (ihrem Experten-Team). Da das für andere User nicht gilt und auch Ausnahmen nicht auszuschließen sind soll dies technisch nicht validiert werden, ist nur für den Hinterkopf.

Im Dashboard des neuen Backend soll es neben dem Bereich 'Meine W&A Statistiken' künftig noch den Bereich 'Meine Team W&A Statistiken' geben. Hier kann dann ein Team ausgewählt werden (auch wenn i.d.R. unnötig). Darunter erscheinen dann die Statistiken für das jeweilige Team. Diese werden analog zu den eigenen Zielen dargestellt, also mit Graphen, Jahresziel, Ist-Gesamt und Monatstabelle (Vgl. #1061 ). Die Zahlen beziehen sich aber immer auf das gesamte Team. Diese Zahlen berechnen sich ganz einfach durch Summierung der Ziele und der tatsächlich erreichten Ist-Zahlen der aktuellen Team-Mitglieder. Sollte mal jemand zu dem Team hinzustoßen oder aus dem Team ausscheiden werden die Ziele ab diesem Zeitpunkt neu berechnet und zwar so, als sei diese Person schon immer dabei bzw. nie dabei gewesen.

Beispiel: Team A hat 3 Team-Mitglieder die jeweils ein Ziel von 1.000 haben und die bisher jeweils 500 erzielt haben. Das Team-Ziel ist 3.000 und das Ist-Gesamt 1.500. Auch Team B hat 3 Mitglieder die jeweils ein Ziel von 800 haben und bisher jeweils 400 erreicht haben. Nun wechselt Susi von Team B zu Team A. Dadurch erhöht sich das Ziel von Team A auf 3.800 und das Ist-Gesamt auf 1.900. Das Ziel von Team sinkt auf 1.600 und das Ist-Gesamt auf 800. Im Graphen ist der Wechsel nicht ersichtlich. Er wird neu berechnet und tut so, als wäre Susi schon immer Mitglied von Team A und niemals von Team B gewesen.

Die Team-Ziele sind für alle Team-Mitglieder einsehbar, aber nur für diese.

**Comment by NilsVollmer** [comment]
technische Formulierung:

- [ ] Jeder Nutzer bekommt einen weiteren Bereich 'Team W&A Ziele' unter den bereits vorhandenen Bereichen (Panels)
- [ ] In diesem neuen Bereich wir die identische Ansicht wie bei den eigenen Zielen angezeigt - der einzige Unterschied besteht in den geladenen Daten: es werden die Daten aller Mitglieder des current_teams aufsummiert und angezeigt anstatt nur die eigenen Daten
- [ ] Es gibt (analog zu den Zuweisungen) die Möglichkeit, das aktuelle Team zu wechseln. In den allermeisten Fällen wird da aber nur genau ein Team zu Auswahl stehen. Optional könnte man dieses Element nur ausrendern, wenn der Nutzer mehr als einem Team zugeordnet ist.

An der User <-> Team-Verknüpfung ändert sich nichts (technisch sind mehrere Teams pro Nutzer möglich).
