### ISSUE TITLE
Ziele/Zielerreichung (wer kann was sehen)

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1065]
Grundsätzlich gibt es folgende Hierarchien:

- Geschäftsführung
- Bereichsleiter (Wording tbd)
- Leads
- Team-Mitglieder

Team-Mitglieder können ihre eigenen Ziele/Zielerreichung und die Ziele/Zielerreichung ihres Teams sehen, sonst nichts.

Leads können ihre eigenen Ziele/Zielerreichung, die Ziele/Zielerreichung ihres Teams und die Ziele/Zielerreichung der einzelnen Mitglieder dieser Team sehen (tendenziell als weitere Bereiche im Dashboard.

Bereichsleiter können ihre eigenen Ziele/Zielerreichung (i.d.R. 0) und die Ziele/Zielerreichung der Teams sehen die ihrem Bereich zugeordnet sind. Die Ziele/Zielerreichung der Leads dieser Teams sieht er nicht. Die Ziele/Zielerreichung der anderen Team-Mitglieder können sie ebenfalls nicht sehen.

Die Geschäftsführung kann die Ziele/Zielerreichung der einzelnen Bereiche sehen, aber nicht die der Mitarbeiter dieser Bereiche (egal ob Bereichsleiter, Lead oder Team-Mitglied). Auch die Ziele/Zielerreichung der einzelnen Team kann die Geschäftsführung nicht sehen.

Die Berechnung der Ziele/Zielerreichung der Bereiche erfolgt analog zu der Berechnung der Team-Ziele (Vgl #1064). 

In einem ersten Schritt reicht es, wenn nur per Konsole eingegeben kann wer Bereichsleiter von welchem Team ist, wer Geschäftsführung ist etc.

**Comment by NilsVollmer** [comment]
Lass uns darüber nochmal sprechen ;)

**Comment by NilsVollmer** [comment]
Okay ist ja im direkten Gespräch alles klar geworden.

**Comment by NilsVollmer** [comment]
Deploy TODO nach db:migrate (!)

``` ruby
UserTeam.find_each do |team|
    Statistic::WeeklyStatisticAggregator.new(team.id, 2017).record!
end
```
