### ISSUE TITLE
Anzahl der Suchergebnisse in der mobilen Ansicht anders anzeigen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#107]
Die Anzahl der Ergebnisse in der gleichen Zeile wie 'Zum Schlagwortfilter' anzeigen. 

'34 Angebote' ganz link und statt 'Zum Schlagwortfilter' nur 'Schlagwortfilter', gerne ergänzt um ein Symbol und das ganz rechts anzeigen.

![clarat](https://cloud.githubusercontent.com/assets/432388/5854664/7fbb4bf2-a230-11e4-90c8-e4fd8ac98aff.png)

**Comment by Twiek** [comment]
Bitte noch einmal probieren mit einem durchgehenden grauen Balken und dem 'X Angebote' in weißer Schrift dadrüber.

**Comment by marcus-herrmann** [comment]
Variante in c5122cf7dad701a3dd2936531d64b8a5812d5fa2

**Comment by marcus-herrmann** [comment]
Missverständnis geklärt.

**Comment by marcus-herrmann** [comment]
Besprochene Variante in d40dd9756a09e631361004924e442b0ef50801fd
