### ISSUE TITLE
Teams können nicht bearbeitet werden

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1074]
Wenn ich versuche einen Übersetzerteam im Backend einen neuen Nutzer hinzuzufügen passiert folgendes:

![bildschirmfoto 2017-03-27 um 09 57 25](https://cloud.githubusercontent.com/assets/432388/24346264/d09c5bd6-12d3-11e7-9f32-c80c4ef6fa50.png)

Obwohl das Team schon mehrere Nutzer hat tauchen diese hier nicht auf. Gebe ich einen Namen ein und wähle einen User aus erstelle ich defakto ein neues Team.

**Comment by NilsVollmer** [comment]
Duplicate auf #1089
