### ISSUE TITLE
Category Active State

### ISSUE THREAD

**Issue by KonstantinKo** [clarat-org/clarat#1076]
Durch die leicht geänderte Logik vom Issue enhanced_geolocation ist es nun so, dass wenn eine Kategorie auf der Homepage der Sections geklickt wird, diese "aktiv" wird, also in einem hidden field diese Kategorie gespeichert wird und ab dann in dem Formular gilt. Wenn also der submit abgebrochen wird (momentan nur durch fehlende location) und danach per Klick auf den Suchbutton noch einmal gesucht wird, ist trotzdem diese Kategorie weiterhin ausgewählt.

Das sollte man auch im UI kenntlich machen. Also die geklickte Kategorie irgendwie als "aktiv"/gedrückt/ausgewählt anzeigen.

**Comment by marcus-herrmann** [comment]
@KonstantinKo Welche Prio hat das Ticket?

**Comment by KonstantinKo** [comment]
@marcus-herrmann Tickets die so von mir ohne Prio gestellt werden sind erstmal low prio "Lückenfüller" solange sie nicht von Basti promotet werden
