### ISSUE TITLE
Organisationsnamen zusätzlich in die Suche aufnehmen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#108]
Bitte Vorschlag machen wie künftig auch Organisationsnamen in den Suchergebnissen angezeigt werden können (zusätzlich zum Angebotsnamen und der Adresse). Von der Wichtigkeit sollte der Organisationsname irgendwo zwischen Angebotsname (höchste Priorität) und Adresse (niedrigste Priorität) liegen.

Herausforderung ist es nicht an Übersichtlichkeit oder Informationsdichte zu verlieren. (insbesondere in der mobilen Ansicht). Hier z.B. mit deutlich geringeren Abständen zwischen den einzelnen Angeboten experimentieren.

Als Beispiel bitte lange Namen für Angebot und Organisation nehmen (jeweils 80 Zeichen) und auch ein längere Adresse (z.B. Ludwig-Siebert-Straße 21,
91541 Rothenburg ob der Tauber) und ein weiteres Beispiel für den seltenen Fall, dass ein Angebote mehrere Organisationen hat.

**Comment by Twiek** [comment]
Kleine Inspiration von anderen Seiten:

![bildschirmfoto 2015-01-22 um 12 17 52](https://cloud.githubusercontent.com/assets/432388/5860333/fb50913e-a260-11e4-9b11-5d179deeada0.png)

**Comment by marcus-herrmann** [comment]
Bin hier gerade im Grafikprogramm zu Gange, und da kam mir die ketzerische Frage in den Sinn:

Kann bzw. soll die Applikation Suchergebnisse nach Orten gruppieren?

* Überall wo du bist
    * Ergebnis
    * ...
* Berlin
    * Ergebnis, Beispielstraße 1
    * Ergebnis, Musterallee 47
    * ...
* Potsdam
    * Ergebnis, Beispielstraße 7
    * Ergebnis, Musterallee 122
    * ...

Dann könnte man Ortsangabe und ggf. PLZ aus der direkten Suchergebnispräsentation nehmen, nur noch Angebotstitel + Orga + Straße & Hausnummer.

**Comment by Twiek** [comment]
Eine Unterteilung nach 'Überall wo du bist' bzw. virtuellen Angeboten (Telefonseelsorge etc.) und örtlich gebundenen Angeboten könnte Sinn machen.

Darüber hinaus wäre ich unsicher, gerade bei Berlin. Ohne PLZ weiß man ja nicht ob es in Spandau oder Köpenick ist und das macht definitiv einen Unterschied.

**Comment by marcus-herrmann** [comment]
Mal ein erster Ansatz ohne Gruppierung, mit Orga und Adresse in der Unterzeile. Hier müssten Abstände zwischen den einzenlen Einträgen allerdings gleich bleiben, um eine Trennung zu gewährleisten. (Dummydaten natürlich sachlich Quatsch, ging mir um Bezeichnerlängen). Weiteres dann Dienstag persönlich.
![bildschirmfoto 2015-01-26 um 14 45 51](https://cloud.githubusercontent.com/assets/505181/5900522/58147924-a56a-11e4-898e-643a00357be5.png)
![bildschirmfoto 2015-01-26 um 14 45 26](https://cloud.githubusercontent.com/assets/505181/5900523/582b239a-a56a-11e4-9600-1937fccba4e1.png)

**Comment by Twiek** [comment]
Nicht uninteressant, aber da der Organisationsname wichtiger sein soll als die Adresse (s.o.) bitten diesen fett machen und nicht die Adresse.

Ansonsten gerade bei der mobilen Ansicht schon mal eine Version entwerfen mit kleineren Abstand zwischen den Ergebnissen und im Idealfall auch schon #107 berücksichtigen.

**Comment by marcus-herrmann** [comment]
Update: Header aus #107 ist drin, Abstände der Listitems jetzt einheitlich 15px, Fettungen getauscht. Bei Interesse kann ich in einem gesonderten Branch das ganze im CSS am lebenden Objekt bauen.

![folge-desktop](https://cloud.githubusercontent.com/assets/505181/5937971/7bd6db94-a6f6-11e4-93ab-ecb28382ad8b.png)
![folge-mobil](https://cloud.githubusercontent.com/assets/505181/5937972/7bdc55d8-a6f6-11e4-9200-8d4863b05001.png)

**Comment by Twiek** [comment]
Sieht gut aus, bitte umsetzen. Einzig den geringeren Abstand zwischen den Suchergebnissen wenn möglich auf die mobile Ansicht beschränken.

**Comment by marcus-herrmann** [comment]
Styling ist drin, es ist aber deshalb nicht im Master, da ich mir nicht sicher bin, was die Slim-Syntax/-Logik in Bezug auf `app/views/offers/index.html.slim` angeht, auch in Bezug auf #84 (mehrere Namen, ich überprüfe noch nicht wirklich die Größe der Collection `offer.organizations`). Bitte um Refactoring oder Hinweis.

**Comment by Twiek** [comment]
@KonstantinKo: Lass uns das morgen (Dienstag) klären und dann gegebenenfalls deployen.
