### ISSUE TITLE
Falscher Bullet?

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1082]
WAs ist hier los?

![bildschirmfoto 2017-03-28 um 17 37 15](https://cloud.githubusercontent.com/assets/432388/24413954/43c81672-13dd-11e7-866e-9b57f7b052da.png)

https://www.clarat.org/refugees/preview/angebote/hilfe-beim-lesen-und-schreiben-von-briefen

**Comment by marcus-herrmann** [comment]
Kein CSS-Fehler: an dieser Stelle ist redaktionell einfach ein `<br>` gesetzt:

```
<li>
  <br>Telefon:  <a href="tel:03061621703">030  61 62 17 03...
```

**Comment by NilsVollmer** [comment]
Das Problem liegt schon bei uns im Code:

        li
          = "#{contact_name contact}"
          br

Wenn aus dem neuem contact_name helper ein nil zurückkommt (contact hat weder last_, first_ noch operational_name), wir da eine leere Zeile durch das br in der View erzeugt.

**Comment by NilsVollmer** [comment]
@Twiek ist das jetzt schon auf master oder develop? es gibt noch einen offenen PR für dieses Issue.. Not sure if 'ready for deploy' is correct..

**Comment by mokus80** [comment]
Deployed auf Production.
