### ISSUE TITLE
Bug: Nutzer & NutzerTeam im Backend 2.0 funktioniert nicht

### ISSUE THREAD

**Issue by NilsVollmer** [clarat-org/clarat#1089]
Daten werden beim editieren nicht korrekt geladen bzw. nicht korrekt angezeigt? Beim speichern wird dann anscheinend sogar ein neues Modell erstellt, was auch ein grobes Fehlverhalten ist.

Bitte einarbeiten (dürfte die GenericForm sein) und auf Fehlersuche gehen.

Ist an sich ein sehr kritischer Bug, der aber im Moment wenige User betrifft - nichtsdestotrotz muss er natürlich behoben werden.

**Comment by NilsVollmer** [comment]
siehe auch #1074

**Comment by allthegoldt** [comment]
Hast Du das ggf. schon gefixt?

**Comment by NilsVollmer** [comment]
Da Konstantin leider krank ist => please investigate
