### ISSUE TITLE
Algolia Operations in control

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1094]
Aktuell verbrauchen wir sehr viele Operations (z.B. dadurch, dass wir jeden Freitag diverse workers für die definitions über alle Angebote laufen lassen). Hier mal alle solche Fälle dokumentieren und Vorschläge machen wie wir hier deutlich ressourcenschonender arbeiten können. Im Idealfall rein technisch (worker arbeitet gezielter), zur Not aber auch indem wir die defintions bzw. Angebote seltener updaten.

**Comment by Twiek** [comment]
Direkt im neuen Backend machen (Worker muss manuell getriggered werden wenn eine neue Definition angelegt wird). Bis dahin tendenziell den Worker im alten backend ausschalten.

**Comment by allthegoldt** [comment]
hotfix: der worker wurde erstmal ausgeschaltet. Soll vor Donnerstag deployed werden.

**Comment by allthegoldt** [comment]
Bei Sprache angefragt, wie häufig es zu Änderungen/neuen Definitions kommt.

**Comment by allthegoldt** [comment]
Before deploy: worker has to be set manually once to get all new definitions since the day it ran the last time. After that it should be left to work once a week.
