### ISSUE TITLE
Backend 2.0: DataLoading of Tabs überarbeiten

### ISSUE THREAD

**Issue by NilsVollmer** [clarat-org/clarat#1098]
Daten sollen immer nur wenn nötig geladen werden. (AssignmentContainer & StatisticContainer) Zusätzlich: current_team_id und alles was damit zusammenhängt entfernen (bei den Zuweisungen dann auch einfachen select für das Team - wie bei den Statistiken) 

- [x] improved TabView
- [x] Controlled SelectView mit active-element im state
- [x] added lockedParams to Index-Views (nur für Filter). Diese werden beim Filtern genutzt, sind aber nicht vom Nutzer änderbar (locked)
- [x] remove current_team_id everywhere and adjust code based on it

**Comment by NilsVollmer** [comment]
@marcus-herrmann Auf diesem Branch gerne noch bei den neuen Tab- und SelectViews (?) das Styling korrigieren.

**Comment by marcus-herrmann** [comment]
@NilsVollmer @KonstantinKo 
Done. Kann jetzt insgesamt reviewed werden
