### ISSUE TITLE
Move simple validations to claradmin

### ISSUE THREAD

**Issue by allthegoldt** [clarat-org/clarat#1102]
Move: website, area, city, definition, federal_state, filter, logic_version, next_step, note, opening, solution_category from clarat_base to claradmin

**Comment by NilsVollmer** [comment]
@KonstantinKo Da du mit de Review ja schon begonnen hast, weise ich dir das Issue mal zu.

**Comment by KonstantinKo** [comment]
Bitte noch model validations auf contract validations übertragen
