### ISSUE TITLE
Best guess completed Angebote bis Anfang März

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1105]
Für clarat insgesamt, nicht für einzelne Mitarbeiter.

**Comment by mokus80** [comment]
Hier meine Schätzung für den Zeitraum vom 1.1. bis 15.3.2017:

5920 completed Angebote insgesamt (80 täglich; 86 % der 6885 completed Angebote)

Details hier: https://gist.github.com/mokus80/055881a860e7ff14eb5a4c8b23fc1b5d
