### ISSUE TITLE
Platzhalter sollten aussehen wie Platzhalter

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1106]
![bildschirmfoto 2017-04-12 um 18 39 51](https://cloud.githubusercontent.com/assets/432388/24968988/7b89ead0-1faf-11e7-88ae-4bda8b44ee33.png)

Hier ist 'Berlin' nur Platzhalter, sieht aber nicht so aus. Bitte durch 'Adresse, Stadteil, Stadt oder PLZ' ersetzen.

**Comment by marcus-herrmann** [comment]
Geändert (und vereinheitlicht) in Localeapp

**Comment by Twiek** [comment]
@marcus-herrmann Passt textlich, aber optisch macht es noch immer keinen Unterschied (oder ich sehe ihn nicht). Fällt Dir hier noch etwas ein (die Schrift z.B. heller zu machen wie bei Yelp bringt vermutlich nichts).

**Comment by marcus-herrmann** [comment]
Ah Ticket missverstanden. Grafischer Vorschlag folgt.

**Comment by marcus-herrmann** [comment]
Vorschlag: Placeholder Text ist kursiv, eingegebener Text nicht. Damit kommen wir nicht in Farb-/Kontrastschwierigkeiten:

<img width="1209" alt="bildschirmfoto 2017-04-26 um 17 06 44" src="https://cloud.githubusercontent.com/assets/505181/25441555/da0c0ec8-2aa2-11e7-97f5-d718fde6b46f.png">

**Comment by Twiek** [comment]
Ja, bitte so umsetzen.

**Comment by marcus-herrmann** [comment]
PR gestellt.
