### ISSUE TITLE
Where ist the map?

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1107]
![bildschirmfoto 2017-04-12 um 18 49 46](https://cloud.githubusercontent.com/assets/432388/24969365/dc3f5724-1fb0-11e7-8f06-a35d1955d368.png)

https://www.clarat.org/refugees/angebote?utf8=%E2%9C%93&search_form%5Bquery%5D=&search_form%5Bsearch_location%5D=Berlin%2C+Deutschland&search_form%5Bgenerated_geolocation%5D=52.520007%2C13.404954&search_form%5Bcategory%5D=&search_form%5Bexact_location%5D=false&search_form%5Bcontact_type%5D=remote&search_form%5Bencounters%5D=hotline%2Cemail%2Cchat%2Cforum%2Conline-course%2Cportal%2Cfax%2Cletter&search_form%5Bage%5D=&search_form%5Btarget_audience%5D=&search_form%5Bexclusive_gender%5D=&search_form%5Blanguage%5D=&search_form%5Bsort_order%5D=nearby&search_form%5Bsection%5D=family

**Comment by marcus-herrmann** [comment]
Auf Staging ist sie da. Production hat allerdings folgende Meldung in der Konsole:

> 2017-04-12 18:56:54.419 angebote?utf8=✓&search_form[query]=&search_form[search_location]=Berlin%2C+Deutschland&search_form[…:1 Redirect from 'https://www.google-analytics.com/r/collect?v=1&_v=j50&aip=1&a=610525050&t=t…id=304474896&cid=1542217049.1433492811&tid=UA-59626864-1&_r=1&z=1533009278' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'https://www.clarat.org' is therefore not allowed access.

Staging nicht und die Karte ist da. Auch wenn es in der Meldung um Analytics geht, kann es das sein? Welcher Branch ist gerade auf Staging deployed (bzw. könnte man da schnell master deployen um meine Theorie mit der Fehlermeldung zu testen)?

**Comment by marcus-herrmann** [comment]
Production: Consolenmeldung ist weg, Karte wieder da, wahrscheinlich lags daran.

**Comment by Twiek** [comment]
Das Problem ist, dass die Karte bei Remote-Angeboten zwar nicht angezeigt wird, das 'drumherum' aber nur entfernt wird, wenn man 'manuell' switched, nicht wenn man direkt über den Link kommt oder die Seite neu lädt.

**Comment by marcus-herrmann** [comment]
Korrigiert (als Commit auf extra fix-branch): https://github.com/clarat-org/clarat/tree/fix/1107-map

**Comment by NilsVollmer** [comment]
Passt
