### ISSUE TITLE
Farsi | Fehler in den Kategorien

### ISSUE THREAD

**Issue by OmarAlsabbagh** [clarat-org/clarat#1110]
In der Farsi-Version sind noch ein paar Fehler in den Kategorien.

a) Kategorie "Lernen und Arbeiten" zeigt 0 Angebote an
b) Kategorie "Freizeit" ist unübersetzt

**Comment by NilsVollmer** [comment]
Update: b habe ich schon gelöst: es fehlte tatsächlich im Backend die Farsi-Übersetzung für die Kategorie.

**Comment by NilsVollmer** [comment]
Update 2: Kategorie umbenennen (war ein Leertaste drin), re-index der betroffenen Angebote und rake cache:clear im Frontend hat das Problem gelöst.

**Comment by NilsVollmer** [comment]
Es gibt also keinen Fehler im Code, es muss also nichts deployed werden. Von mir aus kann das Issue direkt zu. Was meinst du @Twiek ?

**Comment by allthegoldt** [comment]
kann geschlossen werden.
