### ISSUE TITLE
location name vs orga name auf Suchergebnis-Seite

### ISSUE THREAD

**Issue by MichiBecker** [clarat-org/clarat#1115]
Hallo,

laut iPM sollte auf der Suchergebnis-Seite analog zur Angebots-Seite bei der Adresse nicht der Orga-Name ausgegeben werden sondern der Name der Location. Das ist aktuell nicht so.
Ich hab das auch nochmal kurz "auf Sinn" geprüft und der Name der Location hilft dem Nutzer mehr als der Organame, siehe Beispiel

**Output Angebotsseite:**
Jugendclub SKANDAL
Gryphiusstraße 29
10245 Berlin

**Output Suchergebnis-Seite**
Bezirksamt Friedrichshain-Kreuzberg von Berlin
Gryphiusstraße 29, 10245 Berlin

**Angebotslink Backend:** http://claradmin.herokuapp.com/admin/offer/2652/edit
**Standort Backend:** http://claradmin.herokuapp.com/admin/location/1335

**Angebotslink Frontend:** https://www.clarat.org/refugees/preview/angebote/jugendzentrum-10245

**Suchergebnis-Seite (1. Angebot):** https://www.clarat.org/family/angebote?utf8=%E2%9C%93&search_form%5Bquery%5D=jugendzentrum&search_form%5Bsearch_location%5D=gryphiusstr.+Berlin&search_form%5Bgenerated_geolocation%5D=52.520007%2C13.404954&search_form%5Bcategory%5D=&search_form%5Bexact_location%5D=false&search_form%5Bcontact_type%5D=personal&search_form%5Bencounters%5D=hotline%2Cemail%2Cchat%2Cforum%2Conline-course%2Cportal%2Cfax%2Cletter&search_form%5Bage%5D=&search_form%5Btarget_audience%5D=&search_form%5Bexclusive_gender%5D=&search_form%5Blanguage%5D=&search_form%5Bsort_order%5D=nearby&search_form%5Bsection%5D=family

**Comment by Twiek** [comment]
#729 kümmert sich schon drum. Jetzt machen wir es wirklich... ;-)
