### ISSUE TITLE
Neues Backendesign nachbessern

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1116]
Auf Seiten wie diesen:

![bildschirmfoto 2017-04-25 um 18 22 31](https://cloud.githubusercontent.com/assets/432388/25396240/2ef55a4e-29e4-11e7-9931-3f1025faac89.png)

Die Abstände, insbesondere im oberen Bereich etwas großzügiger gestalten, den 'Zuweisung schließen!' Button sogar deutlich anders platzieren und auch farblich anders gestalten (eher einen warnenden Farbton). Außerdem tendenziell alle Buttons mit einem sichtbaren Mouseover-Effekt ausstatten. Der 'Neu zuweisen' Button soll ebenfalls eine andere, hellere Farbe bekommen. Eventuell insgesamt noch mal checken, ob es eine Alternative zum dunklen Braun als actionable color gibt und dabei nicht davor zurückschrecken neue Farben einzuführen (das helle Blau welches den oberen Kasten umrandet gibt es so ja im 'Frontend' auch nicht). 

Den 'Gespeichert!' Button wenn er nicht klickbar ist noch stärker ausgrauen. Wenn er klickbar ist dies farblich deutlicher hervorheben.

Das Rot von 'GoogleTranslate' aufhellen bzw. für einen stärkeren Kontrast mit der Schrift daneben sorgen. Gleiches gilt für das Grün von 'Menschenhand' (siehe Screenshot unten). Das 'Original (Preview)' klarer als 2 (unterschiedliche) Links markieren.

![bildschirmfoto 2017-04-25 um 18 28 30](https://cloud.githubusercontent.com/assets/432388/25396494/0dd74038-29e5-11e7-8ca7-25a571307aca.png)

**Comment by marcus-herrmann** [comment]
Neu zuweisen = Farbvorschlag für Standardfarbe Buttons. Weniger "hart" als der aktuelle Braunton
Zuweisung schließen! = Farbvorschlag für "Achtung!"-Buttons
Gespeichert = Farbvorschlag für disabled buttons

Das Blau des Panels war kein Farbvorschlag, sondern eine Panel-Variante, die mir bisher noch nicht über den Weg lief. Ist vereinheitlicht.

![bildschirmfoto 2017-04-27 um 10 53 26](https://cloud.githubusercontent.com/assets/505181/25475685/dc00c5c6-2b37-11e7-82b4-200bac42bff7.png)

**Comment by Twiek** [comment]
Die Übersetzer sind sehr angetan. Bitte so umsetzen.

**Comment by marcus-herrmann** [comment]
Featurebranch mit dem Stand aus dem Screenshot: https://github.com/clarat-org/claradmin/tree/fix/1116-style-fixes

**Comment by NilsVollmer** [comment]
@Twiek Für das Issue gab es noch gar keinen PR, insofern war/ist es auch noch nicht ready for deploy. Bitte kurz drüber schauen und PR stellen, wenn es passt. Dann können wir diese Kleinigkeit ja noch nachträglich deployen.

**Comment by NilsVollmer** [comment]
Never mind - ich muss eh noch einen worker-fix nach-deployen und kümmere mich dann auch gleich um dieses Issue.
