### ISSUE TITLE
Pop-Up für wiederkehrende User

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1118]
Ziel ist mit echten 'Powerusers' von clarat in Kontakt zu kommen.

- Daher soll Menschen die in den vergangenen 28 Tagen an 3 verschiedenen Tagen auf clarat waren ein Pop-Up präsentiert wird in dem sie gebeten werden, sich mit uns in Verbindung zu setzen (200 Zeichen Lore Ipsum + Kontaktformular --> E-Mail als Pflichtfeld und Freitext).
- Nachdem dieses Popup einmal gesehen haben wird es den Nutzern nicht wieder angezeigt.
- Wir tracken in Google-Analytics wie oft es angezeigt wurde (Google-Analytics auch um internen Traffic besser rauszufiltern).

**Comment by Twiek** [comment]
Auch klären, ob das Datenschutzrelevant ist

**Comment by Twiek** [comment]
Bitte diesen Text / Logik verwenden.

![bildschirmfoto 2017-05-19 um 15 06 49](https://cloud.githubusercontent.com/assets/432388/26249079/38b29c1c-3ca5-11e7-9331-1fd6592a1ee8.png)

**Comment by Twiek** [comment]
@mokus80 Siehst Du eine Möglichkeit wie wir verhindern können, dass die clarat Mitarbeiter das angezeigt bekommen (z.B. wer das Google-Analytics-Deaktivierungs-Plugin nutzt kriegt das nicht angezeigt oder über die IP)? Bzw. w

**Comment by mokus80** [comment]
![screen shot 2017-05-23 at 15 48 36](https://cloud.githubusercontent.com/assets/3678996/26357432/83abf6a0-3fcf-11e7-9bd1-fdf83cbb99d2.png)

**Comment by mokus80** [comment]
Pull Request: https://github.com/clarat-org/clarat/pull/1174

**Comment by Twiek** [comment]
Könntest Du bitte mobil noch mal reingehen und mit den Textgrößen spielen. Finde aktuell mobil die Überschrift und das was nach dem '*' kommt eher zu groß und den 'Haupttext' eher zu klein.

Im Screenshot hat die Überschrift jetzt 1em (statt 2), der Haupttext 0,7em und das was nach dem '*' 0,5em. Nicht zwangsweise der Weisheit letzter Schluss, finde es aber dennoch etwas besser fürs Handy.

![bildschirmfoto 2017-05-24 um 15 49 40](https://cloud.githubusercontent.com/assets/432388/26406602/0782465e-4099-11e7-8f25-3da9de6a37f8.png)

**Comment by Twiek** [comment]
Noch mal eine kleine Textänderung ;-):

"20 Euro für deine Meinung

Sag uns, was wir verbessern können. Oder was dir gut gefällt. Gern würden wir dazu mit dir telefonieren. Dürfen wir dir eine E-Mail mit den Details schicken?

Ja, bitte. 

Dein Name und deine E-Mail-Adresse werden ausschließlich zur Kontaktaufnahme verarbeitet. Du abonnierst keinen Newsletter und deine E-Mail-Adresse wird nicht an Dritte weitergegeben."

**Comment by Twiek** [comment]
Deploy Todos:
- [ ] Mit Eleonore absprechen, dass sie ein Auge drauf hat.
- [ ] Bei Katja Übersetzungen anfordern.
