### ISSUE TITLE
Problemkategorien um Keywords ergänzen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1119]
Problemkategorien sollen die Möglichkeit erhalten um Keywords ergänzt zu werden. Die Keywords haben ausschließlich das Ziel die Suche zu verbessern, d.h. sie müssen auch an Algolia übermittelt werden (in der Wichtigkeit direkt unter den Kategorien selber angeordnet). Keywords sollen sowohl Synonyme abbilden z.B. ist 'Marihuana' ein Synonym der Kategorie 'Cannabis' und zusätzliche verwandte Begriffe wie z.B. 'kiffen'. Die Keywords sollen auch perspektivisch nicht im Frontende erscheinen.

Wichtig ist, dass die Keywords wie auch der Name der Kategorie in verschiedenen Sprachen angelegt werden können, im Gegensatz zu diesen aber nicht von Gengo übersetzt werden. Die Keywords bleiben einfach leer, solange hier nicht manuell Daten eingepflegt werden. Nice to have feature in diesem Rahmen: Es wird überhaupt nur für die Sprachen 'Deutsch', 'Arabisch', 'Englisch' und 'Farsi' die Möglichkeit angezeigt Keywords einzutragen.

**Comment by NilsVollmer** [comment]
Nach Rücksprache mit @Twiek : Die Keywords sollen gemäß der Baumstruktur der Kategorien für den AlgoliaIndex nach unten 'vererbt' werden. 

Oberkategorie 'Gesundheit' hat Keyword 'Medizin'
Unterkategorie (von Gesundheit) 'Drogen' hat Keyword 'Rausch, High'
Unterkategorie (von Drogen) 'Cannabis' hat Keyword 'Kiffen'

Angebot1 in Kategorie Gesundheit liefert 'Medizin' für Algolia
Angebot2 in Kategorie Drogen liefert 'Medizin Rausch High' für Algolia
Angebot3 in Kategorie Cannabis liefert 'Medizin Rausch High Kiffen' für Algolia

Des Weiteren sollen die aktuell nicht benötigten Sprachen (ru, tr, pl, fr) nicht als Datenfeld angelegt werden. Der auslesende Code muss dafür minimal angepasst werden, sodass er keinen Fehler schmeisst, wenn auf ein nicht existierendes Feld zugegriffen wird (try-Methode)
