### ISSUE TITLE
Verknüpfung: AP mit Telefon/Mailadresse (Feature)

### ISSUE THREAD

**Issue by JensBaumgarten** [clarat-org/clarat#112]
Angeboten können 0 - X 'Ansprechpartner' zugeordnet werden.

Zu einem Ansprechpartner können folgende Informationen hinzugefügt werden (alls Felder sind optional, es muss aber mind. 1 ausgefüllt werden.

- Name (Freitext, d.h. hier ist sowohl 'Hans Dampf', 'Herr Hans Dampf', also auch 'Andrea' oder einfach nichts, z.B. für die allgemeine Durchwahl bzw. falls es keine konkreten Ansprechpartner gibt möglich. Zusätze wie 'Mädchen rufen bitte Gabi Müller an' gehören allerdings in die Beschreibung).
- Telefonnummer 1
- Telefonnummer 2
- E-Mail

Bisherige Angebotsangaben wie 'telephone', 'second telephone' und 'contact name' werden dann zu einem neuen Ansprechpartner-Objekt zusammengefasst und dann gelöscht. Das Feld 'fax' bleibt weiterhin direkt dem Angebot zugeordnet.

**Comment by KonstantinKo** [comment]
- Ansprechpartner können auch mehreren Angeboten zugeordnet sein
- Ansprechpartner haben eine Organisation (Pflicht)
- Display name sollte ID, Namen und Organisationsnamen beinhalten

**Comment by KonstantinKo** [comment]
Braucht dann noch Frontend-Styling.

**Comment by Twiek** [comment]
In Verbindung mit #178.

**Comment by marcus-herrmann** [comment]
#178 heute geschlossen, kann dieses Issue auch zu?
