### ISSUE TITLE
Keywords umbenennen und erweitern

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1120]
Das bisherige Keyword Modell soll in 'Tags' umgenannt werden und das Feld Synonyms soll in Keywords umbenannt werden. Keywords sollen sowohl Synonyme abbilden z.B. ist 'Marihuana' ein Synonym des Tags 'Cannabis' und zusätzliche verwandte Begriffe wie z.B. 'kiffen'. Die Keywords sollen auch perspektivisch nicht im Frontende erscheinen.

Wichtig ist, dass die Keywords wie auch der Name des Tags in verschiedenen Sprachen angelegt werden können (Vgl. Problem-Kategorien). Der Name des Tags soll dabei von Gengo übersetzt werden, die Keywords nicht, sie bleiben einfach leer, solange hier nicht manuell Daten eingepflegt werden. Nice to have feature in diesem Rahmen: Es wird überhaupt nur für die Sprachen 'Deutsch', 'Arabisch', 'Englisch' und 'Farsi' die Möglichkeit angezeigt Keywords einzutragen.

**Comment by Twiek** [comment]
Präferenz Synonyme und Searchhelper zusammezulegen (technisch identisch).

**Comment by allthegoldt** [comment]
https://github.com/clarat-org/claradmin/pull/123

**Comment by NilsVollmer** [comment]
Error beim staging-test-deploy: rake db:migrate =>

```console
== 20170502132754 RenameKeywordsToTagsExpandAndReindex: migrating =============
-- rename_table(:keywords, :tags)
   (5.4ms)  ALTER TABLE "keywords" RENAME TO "tags"
   (2.3ms)  ALTER TABLE "public"."keywords_id_seq" RENAME TO "tags_id_seq"
   (5.6ms)  ALTER INDEX "keywords_pkey" RENAME TO "tags_pkey"
   (0.9ms)  ROLLBACK
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateTable: ERROR:  relation "tags_pkey" already exists
: ALTER INDEX "keywords_pkey" RENAME TO "tags_pkey"
(...)
```

**Comment by NilsVollmer** [comment]
Update: Problem lokalisiert. An der Categories-Table (die früher ja Tags hieß) wurde der primary-key index nicht umbenannt und deshalb existiert der natürlich schon
```console
dff0f9csufifh=> \d categories
                                     Table "public.categories"
   Column   |            Type             |                        Modifiers                        
------------+-----------------------------+---------------------------------------------------------
 id         | integer                     | not null default nextval('categories_id_seq'::regclass)
 name_de    | character varying(255)      | not null
 created_at | timestamp without time zone | 
 updated_at | timestamp without time zone | 
 icon       | character varying(12)       | 
 parent_id  | integer                     | 
 sort_order | integer                     | 
 visible    | boolean                     | default true
 name_en    | character varying           | 
 name_ar    | character varying           | 
 name_fr    | character varying           | 
 name_pl    | character varying           | 
 name_tr    | character varying           | 
 name_ru    | character varying           | 
 name_fa    | character varying           | 
Indexes:
    "tags_pkey" PRIMARY KEY, btree (id)
    "index_categories_on_name_de" btree (name_de)
```

Mögliche Lösungen: den pkey von categories in 'categories_pkey' umbenennen oder für die neue Tags-Tabelle einen eigenen pkey-index-namen angeben. Ersteres wäre mein Favorit aber mal schauen, ob das mit live-Daten möglich ist..
