### ISSUE TITLE
Checkbox und Select Inputs nicht als solche erkennbar

### ISSUE THREAD

**Issue by KonstantinKo** [clarat-org/clarat#1123]
Durch die Inklusion von `-webkit-appearance: none` im CSS des neuen Backends sehen (mindestens) checkbox und select input Felder nicht mehr wie solche aus sondern wie standard text inputs.

**Comment by marcus-herrmann** [comment]
Hast du zufällig Beispiellinks zur Hand?

**Comment by KonstantinKo** [comment]
Ja, bei Organisationen->Erstellen (http://claradmin-staging.herokuapp.com/organizations/new)

- priority ist eine checkbox
- unter website_ids auf "neues Objekt" klicken -> host ist ein select

**Comment by marcus-herrmann** [comment]
Danke Dir. Ist als fix auf develop.

Bei der Gelegenheit habe ich gesehen, dass ich als aktueller Nutzer gar nicht auf alle Screens/Formulare zugreifen kann (ich vermute, nur Admins können auf die /new und /edit routes der Models zugreifen bzw. bekommen sie verlinkt). Also Zeit für Konsolenaction. User mit ID1 und Maximalrechten bist vermutlich du? ;)

**Comment by KonstantinKo** [comment]
Ahja, das wird in Zukunft sogar noch schwieriger, da dann nur noch Nutzer die auch wirklich laut ihren Arbeitsaufgaben mit bestimmten Modellen zu tun haben, diese auch bearbeiten können. Aber im Zweifelsfall werde ich meinem Account (ja, ID1) schon die notwendigen Rechte verschaffen ;)

Das gesamte Orga-Formular ist übrigens noch WIP. Dir wird ja wahrscheinlich aufgefallen, dass da einiges andere noch styling braucht. Das weise ich dir dann aber erst zu, wenn die Funktionalität soweit fertig ist.
