### ISSUE TITLE
Fehler beim Preview

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1127]
http://claradmin.herokuapp.com/admin/offer/22310 (dupliziert)
http://claradmin.herokuapp.com/admin/offer/20946 
http://claradmin.herokuapp.com/admin/offer/20947 
http://claradmin.herokuapp.com/admin/offer/22308 (dupliziert)
http://claradmin.herokuapp.com/admin/offer/20942
http://claradmin.herokuapp.com/admin/offer/20943

Laut Aussage der Researcher sind das keine Zwischenweltangebote, sondern reine Refugees Angebote.

Siehe auch: https://app.asana.com/0/48434740552087/332820318682782/f

**Comment by NilsVollmer** [comment]
Als Hotfix direkt auf master umgesetzt & deployed
