### ISSUE TITLE
Weltenwechsel tracken

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1129]
Überlegen den Header noch mal umzubauen. In dem Rahmen soll getracked werden ob bzw. wie oft die Links in die andere Welt ('zu clarat Family', 'zu clarat Refugees') geklickt werden. Hier muss der notwendige Analytics code eingebaut werden.

**Comment by allthegoldt** [comment]
Eleonore macht eine historische Auswertung aus Google Analytics
