### ISSUE TITLE
Doppelte Ausgabe von Hand erstellter 'dependent tags'  

### ISSUE THREAD

**Issue by JensBaumgarten** [clarat-org/clarat#113]
Wenn man ein neues Angebot eingibt und beide Tags (Tag + dependent Tag) von Hand eingibt, kommt nach dem Speichern der dependent tag doppelt. 

Hier ein Beispiel zum Tag "Spielsucht": http://developer.clarat.org/admin/offer/916
"Suchtberatung" wurde manuell eingegeben und nach dem speichern, kommt es zweimal vor.

![dependent_tags](https://cloud.githubusercontent.com/assets/10612933/5897834/dc858bf2-a548-11e4-8e11-02bf89be148e.png)

Könntet ihr diese Funktion vielleicht rausnehmen?

Researcher: Sophie

**Comment by KonstantinKo** [comment]
¿Ganz sicher, dass das noch passiert?
Der Fehler existierte mal nach dem ersten deploy und die Angebote, die damals doppelt Tags bekommen haben, werden die auch vielleicht immer noch haben. Aber bei neuen sollte das eigentlich nicht mehr passieren.

**Comment by KonstantinKo** [comment]
Ist eh hinfällig, dadurch, dass es keine dependent tags mehr gibt
