### ISSUE TITLE
Warning fixes (+Aufräumen) in claradmin react

### ISSUE THREAD

**Issue by KonstantinKo** [clarat-org/clarat#1133]
In der `client/app/Backend/components/TopNav.jsx` gibt es ein paar li, die so wohl von react-bootstrap nicht vorgesehen sind und uns dadurch unknown props warnings erzeugen. Siehe Issue 2199 von bootstrap-react

Wenn man schon in dieser Datei umbaut, könnte man auch gleich mal die Übersichtlichkeits- und Platzraubende SVG weiter oben in eine eigene Komponente auslagern. Gehört eigentlich nicht zum Bugfix, aber das ist denk ich mal zu klein für ein eigenes Issue.

**Comment by allthegoldt** [comment]
done in 944-945
