### ISSUE TITLE
React GenericForm Success Flash Message

### ISSUE THREAD

**Issue by KonstantinKo** [clarat-org/clarat#1136]
Sollte auf Basis von `feature/944-945-orga-division-2` behandelt werden.

Bei erfolgreichem Abschicken eines GenericForm wird momentan einfach das Formular cleared. Schön wäre eine Erfolgsmeldung und eine Auswahlmöglichkeit, was der Researcher als nächstes machen möchte: Zurück zum Index, ein neues Formular, zum Dashboard, etc.

**Comment by NilsVollmer** [comment]
In #944 #945 aufgegangen. Dieses Issue kann also geschlossen werden.
