### ISSUE TITLE
GenericForms für Location und ContactPerson (benötigt für Orgas 2.0)

### ISSUE THREAD

**Issue by KonstantinKo** [clarat-org/clarat#1137]
Sollte auf Basis von `feature/944-945-orga-division-2` behandelt werden.

Ein Formular für Location und für ContactPerson wird noch benötigt. Dieses wird nested im Orga#create angefordert.

Braucht auch umgezogene Validierungen (siehe #953) für diese Objekte. Achtung, auf diese habe ich vorhin auch schon Damjan angesprochen, nicht dass ihr euch da überschneidet.

**Comment by NilsVollmer** [comment]
Ist in #944 #945 gemerged und wird dort weiter bearbeitet. Dieses Issue kann zu.
