### ISSUE TITLE
Bug: Map wird bei Einschränkung der Suche nicht aktualisiert

### ISSUE THREAD

**Issue by NilsVollmer** [clarat-org/clarat#1139]
Ich suche nach Angeboten und lande auf der Suchergebnis-Seite. Da mir dort zu viele Ergebnisse angezeigt werden, schränke ich meine Suche weiter ein (Suchwort oder durch Kategorien-Klick) und finde dadurch weniger Angebote. Leider aktualisieren die Marker auf der Karte sich nicht. Das betrifft z.B: auch die Änderung der Sortierung (von default 'In der Nähe' auf 'Beste Treffer'). Oder: ich starte meine Suche mit einem Suchwort, dass ich danach entferne (mehr Ergebnisse). Die Karte wird auch in diesem Fall nicht aktualisiert. Bei der adv. Search dürfte es ähnlich sein.

Anscheinend wird die Map nur beim reload initialisiert und danach (JS-Updates) nicht mehr aktualisiert.

@Twiek bitte priorisieren und zuweisen (Nicole hat in letzter Zeit einiges mit der Karte gemacht ;) )

**Comment by mokus80** [comment]
https://github.com/clarat-org/clarat/pull/1186

**Comment by NilsVollmer** [comment]
Merged & wird dann (mit @Twiek abgesprochen) am Dienstag deployed.
