### ISSUE TITLE
Sitemap erstellen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#114]
Mit dem Ziel bei Google schnell vollständig indexiert zu werden (siehehttps://support.google.com/webmasters/answer/156184?hl=de).

Bitte kurze Einschätzung (Sinnhaftigkeit + Aufwand wenn diese Seite automatisiert aktualisiert werden soll).

**Comment by KonstantinKo** [comment]
Vorarbeit ist geleistet. Rest muss gemacht werden, wenn live version online ist und wir die sitemap auch benutzen wollen. Bis dahin pack ich's ins Backlog.

**Comment by Twiek** [comment]
Bitte mit eigenem Pull-Request.

**Comment by KonstantinKo** [comment]
PR ist gestellt.

**Comment by KonstantinKo** [comment]
Nach Deploy:
im heroku scheduler einen Task anlegen, der regelmäßig
`rake sitemap:generate`
ausführt um Sitemaps aktuell zu halten.

**Comment by Twiek** [comment]
@KonstantinKo Bitte noch einmal kurz checken ob aktuellere gems perspektivisch irgendwelche nennenswerten Vorteile bieten (z.B. https://github.com/kjvarga/sitemap_generator). Wenn nicht, dann gerne mergen.

**Comment by KonstantinKo** [comment]
@Twiek Es hat einen nennenswerten Vorteil, nämlich gzip. Aber es hat ein wichtiges Feature nicht, was es für uns unbrauchbar macht: speichern und holen der sitemap aus der & in die Datenbank.
Wir können uns überlegen ob wir uns nen Amazon S3 o.ä. holen. Dafür gibts wohl auch Adapter und das müsste bei uns funktionieren.
