### ISSUE TITLE
Kategorien auf Offer Show ausgeben

### ISSUE THREAD

**Issue by marcus-herrmann** [clarat-org/clarat#1144]

**Comment by marcus-herrmann** [comment]
![offerindex - family - desktop](https://cloud.githubusercontent.com/assets/505181/25949754/ec196964-3658-11e7-9e8a-89098eb19b55.png)
![offerindex - family - desktop copy](https://cloud.githubusercontent.com/assets/505181/25949753/ec15ce1c-3658-11e7-968a-c32563e60850.png)

**Comment by Twiek** [comment]
Thanks. Sieht schon nicht schlecht aus. Bitte dennoch noch mal eine Version bei dem der Hintergrund gleich bleibt (also nicht Dunkelbesche auf Hellbesche) und einmal als wirklich gesondertes Kästchen.

**Comment by marcus-herrmann** [comment]
> Bitte dennoch noch mal eine Version bei dem der Hintergrund gleich bleibt 

![offerindex - family - desktop copy 2](https://cloud.githubusercontent.com/assets/505181/25957217/13f6d236-366e-11e7-938b-533b5021b644.png)
![offerindex - family - desktop copy 3](https://cloud.githubusercontent.com/assets/505181/25957218/13f7db2c-366e-11e7-8cee-9c5cbdf77f90.png)

> und einmal als wirklich gesondertes Kästchen.

![offerindex - family - desktop copy 4](https://cloud.githubusercontent.com/assets/505181/25957232/1c4532b6-366e-11e7-97f3-57a4bb76cdc6.png)
![offerindex - family - desktop copy 5](https://cloud.githubusercontent.com/assets/505181/25957231/1c413468-366e-11e7-9f8e-b9ba07362e7c.png)

**Comment by Twiek** [comment]
@MichiBecker What do you think?

**Comment by MichiBecker** [comment]
hm, vom Platzverbrauch und auch ein bisschen vom themantischen Zusammenhalt her finde ich die Variante mit den Kategorien im Description Kästchen besser.

**Comment by Twiek** [comment]
@marcus-herrmann bitte gemäß https://cloud.githubusercontent.com/assets/505181/25957217/13f6d236-366e-11e7-938b-533b5021b644.png umsetzen. Angezeigt werden sollen Kategorien und Tags (ohne das diese optisch unterschieden werden).

**Comment by marcus-herrmann** [comment]
Offers und Categories haben ja eine hasMany Relationship in beide Richtungen und sind kein Feld auf dem Offer Model. Deswegen kann ich ja vermutlich nicht mit so etwas wie `- @offer.categories.each do |category|` arbeiten - oder?

Wie auch immer - ich fake die Ausgabe fürs Styling und würde das dann im Anschluss @NilsVollmer oder @KonstantinKo zuweisen

**Comment by marcus-herrmann** [comment]
Styling bereit: https://github.com/clarat-org/clarat/tree/feature/1144-categories-on-offer-show

**Comment by Twiek** [comment]
Problema es: Wenn ich einem Angebot 'nur' eine Kategorie unterer Ebene zuweise, dann finde ich es in der Suche trotzdem in den übergeordneten Kategorien, auch wenn diese dem Angebot nicht explizit zugewiesen wurden. Diese werden auf dem aktuellen Stand jedoch nicht angezeigt.

**Comment by allthegoldt** [comment]
try it now

**Comment by Twiek** [comment]
Bitte Develop reinziehen (Achtung: Merge-Konflikte) und dann auf Ready for Deploy schieben (falls alles im grünen Bereich).
