### ISSUE TITLE
Welchen Status hatten die 'internal_feedback' Angebote vorher

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1148]
Wunsch: Liste aller IDs + vorherigem Zustand der Angebote die sich jetzt im Zustand 'internal_feedback' befinden.

**Comment by allthegoldt** [comment]
https://docs.google.com/a/clarat.org/spreadsheets/d/1qOfpTovoJMGw_H8oUZRT8phz_FS7CJKYn7BQdJXfmgk/edit?usp=sharing

Waren fast alle approved, bis auf ein Angebot, dass "Under_construction" hatte und 2 deren vorheriges state ich nicht herausfinden konnte (ggf. keins?).
