### ISSUE TITLE
Google Analytics Glossar Tracking

### ISSUE THREAD

**Issue by MichiBecker** [clarat-org/clarat#1150]
Bitte an die Tooltips ein Event dranhängen, dass man in GA die Nutzung messen kann.

Output GA: Wie oft wird über einen Glossarbegriff "ge mouse overed" oder anders wie gut kommt der Glossar an oder bzw wird er überhaupt bemerkt?

Sicherstellen, dass das event NACH Pageload gesendet wird. Siehe #1149

Nice to have: Nur zählen wenn > 1 Sekunde (um zu verhindern das versehentliche mouse overs mitgezählt werden).

**Comment by Twiek** [comment]
@MichiBecker Passt das jetzt so? Wenn ja, bitte schließen.
