### ISSUE TITLE
Infos für Telefonaktion herausfinden

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1151]
Verschiedene Wünsche (Priorität entspricht der Reihenfolge):

- [x] Alle Kontaktpersonen (Backendlink) herausfinden die mit einer E-Mail verknüpft sind die den aasm-state 'subscribed' haben und mir per E-Mail schicken.

- [x] Prüfen in welchem aasm-state die E-Mails sind die mit den hier aufgeführten Kontaktpersonen verknüpft sind: https://docs.google.com/spreadsheets/d/1t-4B0pakrBX5W7QSR3MpYyD25txruNh4gddc0AKbopA/edit#gid=0. Falls nur mit sehr großem Aufwand möglich Andrea noch mal anhauen, ob sie die E-Mail liefern kann.

- [x] Prüfen was wir über die aasm-states hinaus zu den verschickten E-Mail sagen können (tracken wir irgendwas in Sendgrid oder Analytics).

- [x] Ist es möglich, dass wir mit Hilfe von Sendgrid und/oder Analytics künftig tracken können welche über das System verschickten E-Mails aufgemacht wurden?

**Comment by allthegoldt** [comment]
https://app.sendgrid.com/email_activity? zeigt meiner Meinung nach ob jede verschickte E-Mail aufgemacht oder gar angeklickt wurde. Ist das was wir in letzten 2 Punkten brauchen?
