### ISSUE TITLE
Zielgruppen/Stamp in eigenes Objekt auslagern

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1156]
Es soll im Rahmen von Split In Control (SIC) nicht mehr nach Zielgruppen gesplittet werden. Dadurch  muss es möglich sein einem Angebot mehrere Zielgruppen zuzuordnen. Daher müssen die entsprechenden Informationen in ein eigenes Objekt (TargetAudience) ausgelagert werden. Einem Angebot können dann mehrere TargetAudiences zugewiesen werden. Konkret geht es um die folgenden Felder die aus dem Angebot entfernt und in ein eigenes Objekt gepackt werden sollen:

- Target audience filters
- Residency Status
- Gender first part of stamp
- Gender second part of stamp
- Age from
- Age to
- Age visible

Zusätzlich soll es ein neues Feld 'Addition' geben (auf 80 Zeichen begrenzter String). Dieses soll in der Stamp-Generierung immer am Ende des Stamps erscheinen. Wenn z.B. der Stamp ohne Addition  lautet 'für werdende Eltern' und in der Addition steht '(aus Charlottenburg)', dann lautet der im Frontend angezeigte Stamp 'für werdende Eltern (aus Charlottenburg)'. Es ist auch möglich, dass der Stamp nur aus der Addition besteht.

Im Frontend sollen kurzfristig auf den Suchergebnisseiten nur maximal 1 Stamp angezeigt werden (im Zweifelsfall der älteste). In der Angebotseinzelansicht alle (kommagetrennt). Das wir sich aber mit an Sicherheit grenzender Wahrscheinlichkeit noch einmal ändern.

Der Deploy muss vermutlich in 2 Schritten erfolgen. Erst wird das neue Objekt angelegt, dann werden die bestehenden Daten umgezogen und dann werden die Felder im Angebot gelöscht.

@NilsVollmer Sprich mich bitte mal drauf an.

**Comment by NilsVollmer** [comment]
Wie besprochen: die Felder wandern in das Verknüpfungsmodell (FiltersOffer) und wir prügeln es RailsAdmin irgendwie ein, damit zurechtzukommen. Usability wird nicht awesome sein.

@Twiek Offene Fragen: 
- [ ] was ist mit der Addition (Freitext) im Bezug auf Übersetzungen?
- [ ] 'Es ist auch möglich, dass der Stamp nur aus der Addition besteht.' => Also die Zielgruppe ist das Mindeste aus dem ein Stamp generiert wird, weil die immer da ist. Es gibt ja auch keine Möglichkeit, zu entscheiden, wann die Zielgruppe angezeigt werden soll und wann nicht. Oh I know.. ein zusätzliches 'ignore_target_audience_for_stamp'-Feld? 👎  Also ne, bitte nicht.

**Comment by NilsVollmer** [comment]
Deploy TODO nach rake db:migrate:

```ruby
# retrieve models that must be moved
array = FiltersOffer.joins(:filter).where('filters.type = ?', 'TargetAudienceFilter').all.to_a
# create new connector models for every valid connection
array.map do |f_o|
if Offer.where(id: f_o.offer_id).any? && Filter.where(id: f_o.filter_id).any?
TargetAudienceFiltersOffer.create!(offer_id: f_o.offer_id, target_audience_filter_id: f_o.filter_id)
end
end
# delete old connection model entries
array.map(&:destroy)
```
