### ISSUE TITLE
Zuweisungen von Übersetzern per default an Creator, nicht an Approver (+ boolean für ehemalige Mitarbeiter) 

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1158]
Issue hat mehrere Teile:

- [x] User-Model um boolean 'active' mit dem default 'true' zuweisen. Geht darum aktive von ehemaligen Mitarbeitern zu unterscheiden. Wechsel des booleans ist nur über die Konsole möglich.

- [x] User bei denen der boolean 'active' = 'false' ist können keine Zuweisungen erhalten und tauchen nicht mehr im Zuweisungsdropdown im Backend auf:

![bildschirmfoto 2017-06-01 um 16 13 23](https://cloud.githubusercontent.com/assets/432388/26683807/5bd4e250-46e5-11e7-8b70-44c798ac5c2c.png)

- [ ] Zuweisungen für die Übersetzen welche nach approve eines Angebotes automatisch erstellt werden, kommen nicht mehr wie jetzt vom Approver (siehe 'von:' im Screenshot), sondern vom creator des Angebots. Ausnahme ist, wenn das 'active' boolean des creator 'false' ist. In diesem Fall wird doch der Approver genommen. Ist auch dieser nicht mehr active wird der Systemuser angezeigt.

![bildschirmfoto 2017-06-01 um 16 14 55](https://cloud.githubusercontent.com/assets/432388/26683952/e298e368-46e5-11e7-8f08-0113ced7b9fb.png)

**Comment by NilsVollmer** [comment]
Deploy-TODO nach db:migrate:
``ruby
User.where(id: [4, 5, 6, 8, 15, 23, 25, 30, 34, 35, 36, 46, 49, 54, 60, 66, 67, 69, 73]).update_all active: false
```
