### ISSUE TITLE
Automatisiert Orgas und Divisions aus Google-Sheet erstellen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1160]
#Erst nach #944 und #945 umsetzen.

Aus https://docs.google.com/spreadsheets/d/1dRcBu-PanhRHDVkAWaCCM9PhjDY9YpI4uDy5KnXL3c0/edit#gid=651475560 sollen automatisiert Organisationen und Divisions angelegt werden und zwar nach folgenden Regeln:

Update: grüne Liste: https://docs.google.com/spreadsheets/d/1vqxv1psEnd_Ut81NsI8oK1P0RBHz3yg4wbmmFPYpt38/edit#gid=0

Orga:
- Name aus Spalte B (Organisation) übernehmen 
- Kommentar aus Spalte K (Kommentar) und Spalte L (Kommentar (Research)) erstellen. Wenn in beiden Spalten Inhalte sind diese mit ' | '  (Leerzeichen, Pipe, Leerzeichen) trennen.
Verknüpfte Objekte:
Website:
 - URL aus Spalte G (URL) übernehmen und host = own setzen.
Divisions:
- Wenn in Spalte N (clarat-Welt) 'family' steht, dann für die Orga eine Division erstellen.
--> Welt = family
--> Name = 'Divison' + 'family' + 'Name der Orga' (jeweils durch ' | ' getrennt)
--> Wichtige Ausnahme: Wenn die Stadt (Spalte O) NICHT Berlin ist, dann wird dafür keine family Division erstellt.
- Wenn in Spalte N (clarat-Welt) 'refugees' steht, dann für die Orga eine Division erstellen.
--> Welt = refugees
--> Name = 'Divison' + 'refugees' + 'Name der Orga' (jeweils durch ' | ' getrennt)
- Wenn in Spalte N (clarat-Welt) 'beides' steht, dann für die Orga zwei Divisions mit jeweils einer Welt erstellen (analog oben).
--> Wichtige Ausnahme: Wenn die Stadt (Spalte O) NICHT Berlin ist, dann wird dafür keine family Division erstellt.
- Wenn in Spalte N (clarat-Welt) 'Ausland' steht, dann für die Orga keine Division erstellen.

Unabhängig von den Welten sollten bei den Divisions gegebenenfalls noch Webseiten angelegt werden:
--> Der Inhalt der Spalte O  ('Stadt') wird genutzt um eine entsprechende Verknüpfung mit dem City-Modell zu erstellen.
--> Weitere Webseiten werden erstellt, wenn in den Spalten H, I oder J (URL2, URL3, URL4) Inhalte vorhanden sind. Für jeden Inhalt wird eine Webseite mit host = own erstellt (url = Inhalt).  

Unsaubere Daten werden an Screening zurückgespielt

Alle so erstellen Divisions werden dem Screening-Team zugewiesen.

**Comment by NilsVollmer** [comment]
Anmerkungen:
- beim Import der Divisions für welt = 'beides' => eine Division hat genau eine Welt also müssen in diesem Fall zwei Divisions für die Orga erstellt werden
- es ist von dem Feld 'Stadt' die Rede.. in meinem Kopf sollte das kein Textfeld sondern eine Zuordnung zum City-Modell sein. Dann müsste man die Texte der Spalte O nach Komma splitten, nach jeder City im Backend suchen oder diese anlegen
- die so erstellten Divisions sollen Screening zugewiesen werden - was ist mit den Orga's? Auch an Screening?

**Comment by NilsVollmer** [comment]
Update: da dieses Issue für den Deploy auch schon ready sein muss, nehme ich mich der Sache ab jetzt mal an.

**Comment by NilsVollmer** [comment]
Pending: warte auf das GO von Screening.

**Comment by NilsVollmer** [comment]
Update: ist durchgelaufen und somit 'deployed'.
