### ISSUE TITLE
Zuweisungsbug

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1164]
Bericht der Übersetzer: 'die zurückgewiesenen Aufgaben landen oft nicht im Ordner “meine Aufgaben” sondern im Ordner “bereits abgeschlossene Aufgaben”. Übersetzer finden die Zuweisung nicht mehr. Bug? '

Feature, Bug, oder haben die Übersetzer hier potentiell etwas durcheinander gebracht?

**Comment by Twiek** [comment]
@NilsVollmer Checken ob das schon (indirekt) gefixed wurde.

**Comment by NilsVollmer** [comment]
Meine erste Intuition war korrekt: das Problem sollte sich seit dem Deploy am Montag mit #1024 erledigt haben. Solange sich die Übersetzer nicht wieder melden besteht hier IMHO kein Handlungsbedarf mehr.
