### ISSUE TITLE
formerly Zwischenweltangebote family outside Berlin

### ISSUE THREAD

**Issue by MichiBecker** [clarat-org/clarat#1168]
Hallo zusammen,

nach dem Wegfall der Zwischenweltangebote gibt es ca. 70 family Angebote, die außerhalb Berlins sind (Düsseldorf, Köln etc).

Die sollen auf keinen Fall im Frontend auftauchen. Können wir aber für später, wenn clarat family außerhalb Berlins tätig wird, behalten.

Task:
1. Identifizieren der OUTSIDE BERLIN EX ZWISCHENWELT Angebote
2. alle auf INTERNALLY DEACTIVATED setzen

wegen 1. Kann sein, wenn das nicht über Konsole geht, dass das jemand (Researcher) von Hand machen muss.

Prio kläre ich im nächsten Product Meeting (24. mai)

**Comment by Twiek** [comment]
Gibt aktuell 81 Family Angebote die eine andere Stadt als Berlin haben (3102, 6456, 6479, 6480, 6481, 6482, 6483, 6484, 6485, 6486, 6487, 22001, 22016, 22018, 22020, 22021, 22022, 22023, 22025, 22026, 22027, 22028, 22029, 22030, 22031, 22032, 22033, 22034, 22035, 22036, 22037, 22043, 22044, 22048, 22049, 22050, 22053, 22054, 22103, 22105, 22106, 22107, 22108, 22110, 22111, 22112, 22113, 22114, 22115, 22116, 22117, 22118, 22119, 22120, 22121, 22122, 22123, 22124, 22125, 22126, 22127, 22128, 22129, 22130, 22131, 22132, 22133, 22134, 22136, 22137, 22138, 22139, 22140, 22141, 22142, 22183, 22184, 22185, 22186, 22187, 24285). Bis auf eines sind auch alle im Frontend sichtbar.
