### ISSUE TITLE
Seedfile mit Offer-Orga-Dummydaten erstellen

### ISSUE THREAD

**Issue by marcus-herrmann** [clarat-org/clarat#117]
Zwecks testen der z.B. Typeahead- und Listingausgaben.

**Comment by Twiek** [comment]
Wie nutze ich das Seedfile? Mit 'rake db:seed' klappt es zumindest bei mir nicht.

**Comment by KonstantinKo** [comment]
`rake db:fake`(steht auch als Kommentar im neuen seedfile)

Kann wiederholt angewendet werden. Sollte nach einmaliger Ausführung von `rake db:seed` benutzt werden. Ums richtig zu testen, müsste man aber seine bestehende lokale Datenbank wegwerfen und beides auf einer frischen DB ausführen.
