### ISSUE TITLE
Neue Version erstellen 

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1170]
Wir brauchen eine neue Version für Angebote.

Name: 'Split in Control'
Zusätzliche Validierungen:
- Solution Category wird zum Pflichtfeld.
- SplitBase wird zum Pflichtfeld.

--> Anzeige in RailsAdmin anpassen (nicht 'optional' anzeigen wenn es aufgrund einer custom validation nicht optional ist).

**Comment by Twiek** [comment]
- Kann/soll noch nicht am 29. deployed werden. 
- Weitere Validierung ergänzt (SplitBase wird zum Pflichtfeld).

**Comment by Twiek** [comment]
Muss am 13.6. zur Verfügung stehen/gelten.

**Comment by NilsVollmer** [comment]
Deploy TODO:
Offer.where(id: [23753, 23753, 23798, 23838]).map(&:index!)
