### ISSUE TITLE
Angebote ohne solution_category_id eine solche hinzufügen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1171]
Angebote die visible_in_frontend sind und einer SplitBase zugeordnet sind und keine solution_category_id haben sollen die solution_category_id der SplitBase übernehmen.

**Comment by mokus80** [comment]
Betrifft Angebote mit folgenden IDS (alle aus dem Jahr 2015):

[22193, 4251, 23793, 6332, 2456, 10468, 6145, 2395, 2453, 3984, 1686, 1805, 1806, 1812, 2349, 2574, 2575, 2588, 4750, 5306, 6139, 6289, 6327, 8631, 10488, 15686, 16742, 16745, 19365, 19366, 19367, 19368, 19369, 19370, 19372, 19373, 19374, 19377, 20030, 20032, 20035, 21394, 22192]

**Comment by mokus80** [comment]
Offer mit ID 4251 kann keine solution_category zugewiesen werden:

Fehlermeldung:
ActiveRecord::RecordInvalid: Gültigkeitsprüfung ist fehlgeschlagen: Categories <span class="translation_missing localeapp" title="translation missing: de.offer.validations.category_for_section_needed">Category For Section Needed</span>, Categories <span class="translation_missing localeapp" title="translation missing: de.offer.validations.section_for_category_needed">Section For Category Needed</span>

**Comment by mokus80** [comment]
Task auf Production ausgeführt
