### ISSUE TITLE
Angebote übernehmen automatisch die Solution Category ihrer SplitBase

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1173]
D.h. diese Information muss nicht mehr vom Researcher eingetragen werden.

Nach #1170 deployen.

**Comment by Twiek** [comment]
Im neuen Backend.

**Comment by mokus80** [comment]
Wären im alten Backend zu viele Änderungen (Callbacks, Validierungen), die im neuen Backend wieder rückgängig gemacht werden müssten...
