### ISSUE TITLE
Suchfelder Placeholder etc. optimieren

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#118]
In das erste Feld ganz links, fett und konstant (also kein Placeholder) das Wort 'Finde' anbringen. Dahinter, tendenziell leicht grau folgenden Placeholer: 'schwänzen, drogen, gewalt'. Im zweiten Feld statt 'Finde' einfach 'Wo' einsetzen und als Placeholder 'Adresse, Stadtteil, Stadt oder PLZ' verwenden.

In dem Rahmen bitte ein wenig mit verschiedenen Monitorgrößen und auch der mobilen Ansicht spielen und eventuell auch eine etwas kleinere Schriftgröße testen.

**Comment by marcus-herrmann** [comment]
Grundsätzlich eingebaut mit https://github.com/clarat-org/clarat/commit/fecb9a223b5155c9f586423b1a2d8e79ef635c29 (in eigenem Feature Branch), es wäre aber noch Refactoring nötig, sofern dies in den master soll.

**Comment by marcus-herrmann** [comment]
+ Fehldarstellung in FF korrigieren.

**Comment by Twiek** [comment]
Sieht gut aus. Gerne refactoren, FF fixen und einbauen.

**Comment by marcus-herrmann** [comment]
Nun im master (6a4a112ee525864f81239576dfdf14c1704808d0)
