### ISSUE TITLE
Highlight Telefon& Online Tab outside Berlin

### ISSUE THREAD

**Issue by MichiBecker** [clarat-org/clarat#1181]
Nach Anzeige des Overlays "...in deiner deiner Stadt gibt es nur....blabla" nicht auf leerem VOR ORT tab landen sondern gleich auf  Telefon&Online Tab

**Comment by KonstantinKo** [comment]
Hat evtl viel mit search js/coffee zu tun, was schnell komplex werden kann. Wenn du hilfe brauchst sag bescheid, Markus.

**Comment by marcus-herrmann** [comment]
Siehe 93c9b2a - das war allerdings das Gegenteil von komplex, insofern habe ich leise Zweifel, das Ticket missverstanden zu haben.

**Comment by MichiBecker** [comment]
Hi Marcus :)

Sieht gut aus und nicht komplex ;)

kannst du bitte einen pull request draus machen?

Danke

**Comment by marcus-herrmann** [comment]
Freilich: #1191
