### ISSUE TITLE
Internetexplorer Bug fixen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1182]
Es ist im IE noch möglich, dass Suchen ohne Standort getriggered werden was erwartungsgemäß zu einer Fehlermeldung führt. Mehr hier: @marcus-herrmann: Bitte hier den Link eintragen, Dich dann wieder rauslöschen und Nils zuweisen.

**Comment by marcus-herrmann** [comment]
Polyfill includes: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/includes?v=control

**Comment by NilsVollmer** [comment]
Als Hotfix direkt aus master umgesetzt & deployed.
