### ISSUE TITLE
Addition-Feld aus den Zielgruppen entfernen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1184]
#Wird nicht mehr benötigt. Bitte vor dem finalen Löschen noch mal eine Liste erstellen mit den IDs der betroffenen Angebote (die eine Addition haben) + den Text der jeweiligen Addition. Danach endgültig löschen. Liste kann sofort erstellt werden (das Feld darf offiziell ohnehin nicht mehr genutzt werden).

**Comment by NilsVollmer** [comment]
Wichtig: StampLogik anpassen

**Comment by allthegoldt** [comment]
["mit Arbeitserlaubnis", 18824, 23753], ["mit Arbeitserlaubnis", 18928, 23753], ["in Schöneberg", 18940, 23798], ["mit Zulassung zum Integrationskurs", 18944, 23838] (TargetAudienceFiltersOffer.where.not(addition: nil || '').pluck(:addition, :id, :offer_id))

**Comment by NilsVollmer** [comment]
Deploy TODO:
```ruby
Offer.where(id: [23753, 23753, 23798, 23838]).map(&:index!)
```
