### ISSUE TITLE
Kategorien und Tags um eine Explanation-Feld ergänzen (analog Definition)

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1188]
#Kategorien und Tags sollen ein Explanation Feld erhalten und zwar jeweils für Deutsch, Englisch, Arabisch und Farsi (alle Text-Felder optional).

Liegt eine Explanation in der jeweiligen Sprache vor wird sie per Mouseover der jeweiligen Kategorie/Tag in der Angebotseinzelansicht im Frontend angezeigt (analog Definitions). Offensichtlich erst nach #1144. 

Soll perspektivisch die Definitions ersetzen.

**Comment by Twiek** [comment]
Ein Teil der bisherigen Definitions soll direkt in Kategorien oder Tags umgezogen werden. Teilweise soll dabei auch der Text ausgetauscht werden. Details siehe hier: https://docs.google.com/spreadsheets/d/1McdFI5MpL3HnsvCsJcToQTwQ3gxo6eTekABkdgqiF2E/edit#gid=0. Nach Übertrag soll die entsprechende Definition gelöscht werden. Es sind vorerst noch nicht alle Definitions betroffen.

**Comment by NilsVollmer** [comment]
Deploy ist durch - das mit der Spreadsheet muss noch gemacht werden.

**Comment by Twiek** [comment]
@mokus80 Sprich mich bitte mal drauf an.

**Comment by mokus80** [comment]
Müssen Tags und Kategorien noch umgezogen, also zu den entsprechenden Angeboten hinzugefügt werden?

Mir ist aufgefallen, dass die Definitionen nicht unbedingt zu den gleichen Angeboten gehören wie in den Tags und Kategorien. 

Hier ein Beispiel:

Angebote für Definition mit ID 148 (32):
[3534, 3612, 5966, 6679, 8496, 8500, 8508, 8536, 8541, 9182, 9340, 9867, 9873, 14701, 17671, 17899, 19244, 20118, 20119, 20344, 20351, 20392, 20394, 20403, 20434, 20437, 20479, 20866, 20888, 21179, 21180, 21182]

Angebote für Kategorie mit ID 634 (39):
[3534, 3612, 5966, 6679, 7732, 9340, 10702, 10703, 10704, 13095, 14701, 15984, 17671, 17899, 19244, 19608, 20118, 20119, 20344, 20351, 20392, 20394, 20403, 20434, 20437, 20479, 20888, 21179, 21180, 21182, 21184, 21334, 23303, 23304, 23305, 23325, 23847, 23854, 23871]

**Comment by mokus80** [comment]
DONE:
- In allen Kategorien und Tags, die die explanation der Definition übernehmen, wurde diese entsprechend gespeichert
- Angebote, die zwar Definitions haben aber noch nicht die zugehörigen Kategorien und Tags, wurden diese hinzugefügt

TO DO:
- Explanations, die beim Umzug geändert werden sollen, müssen in den Tags und Kategorien noch manuell angepasst werden (im Backend - Basti/Tine?)
- Anschließend werden die Definitions per Konsolentask gelöscht
