### ISSUE TITLE
target audience stamp Generierung im Frontend refugees

### ISSUE THREAD

**Issue by MichiBecker** [clarat-org/clarat#1195]
WENN
unbegleitete minderjährige Flüchtlinge AGE TO > 17
DANN
Stamp im Frontend: unbegleitete Flüchtlinge

Hier die detaillierte Auflistung:
https://docs.google.com/document/d/1H6lQJNbLtisRp4gRtZJ66uZPnu84F2YXc5cL4j-Ly9w/edit#

Im Backend stehen dann nach anlegen der erweiterten Zielgruppe auch die gleichen Stamps wie im Frontend, richtig? WYSIWYG und so

Fragen?

**Comment by NilsVollmer** [comment]
TODO: 
- [ ] Stamp-Generierung anpassen
- [ ] In localeapp (clarat_base) den neuen Fall anlegen (müsste durch Entfernen aus den vorhandenen Übersetzungen für alle Sprache machbar sein)
- [ ] Test anpassen bzw. einen neuen Test für den Fall schreiben
- [ ] nach dem Deploy: in der Konsole alle betroffenen TargetAudienceFiltersOffers herausfinden, bei denen die stamps neu generieren lassen und dann alle betroffenen Angebote für Algolia neu indizieren

**Comment by MichiBecker** [comment]
@NilsVollmer weißt du, wie weit Damian gekommen ist? Das Issue ist in keiner Pipeline.

**Comment by Twiek** [comment]
@MichiBecker Doch, ist in der 'To do' Pipeline. Scheinbar ist aktuell niemand zuständig.

**Comment by Twiek** [comment]
Nach Deploy Reindex der betroffenen Angebote (sollten ca. 223 sein).

**Comment by mokus80** [comment]
Benötigen wir den singular_stamp in Algolia noch? Scheint identisch mit dem stamps_string zu sein und nicht von der Volltextsuche erfasst zu werden...

**Comment by NilsVollmer** [comment]
Wird definitiv benötigt: in singular_stamp steht immer nur der erste Stamp drin (wird bei den Suchergebnissen angezeigt) und in stamps_string stehen alle stamp_strings (wird auf Offer.show angezeigt).

**Comment by NilsVollmer** [comment]
Deploy TODO:
```ruby
ta = TargetAudienceFilter.find_by(identifier: 'refugees_umf')
ta.update_columns(identifier: 'refugees_uf', name: 'unbegleitete Flüchtlinge')

TargetAudienceFiltersOffers.where(target_audience_filter_id: ta.id).map do |tafo|
tafo.generate_stamps!
tafo.offer.index!
puts 'Done with Tafo#' + tafo.id.to_s
end
```
