### ISSUE TITLE
Verschiebung von Angeboten zu anderen Lösungskategorien

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1197]
Es sollen alle Angebote die bisher mit bestimmten Lösungskategorien verknüpft sind mit anderen Lösungskategorien verknüpft werden. Im Anschluss soll die alte Verknüpfung gelöscht werden.

Konkret (IDs beziehen sich auf die Lösungskategorien):

- ID 190 to ID 18
- ID 185 to ID 129
- ID 184 to ID 125
- ID 186 to ID 123
- ID 183 to ID 169

**Comment by allthegoldt** [comment]
done
