### ISSUE TITLE
Max. Zeichenanzahl im Datenfeld 'Synonyms' erhöhen 

### ISSUE THREAD

**Issue by JensBaumgarten** [clarat-org/clarat#120]
Die max. 255 Zeichen im Datenfeld 'Synonyms' reichen bei einigen Begriffen nicht aus. Wenn möglich die max. Zeichenzahl auf 'unlimited' setzen.

![synonyme](https://cloud.githubusercontent.com/assets/10612933/5920015/86bda316-a639-11e4-877c-b785ba8eac7b.png)

Researcher: Andrea

**Comment by Twiek** [comment]
Siehe #126
