### ISSUE TITLE
Neue Sprachen | Ewe, Djerma & Mina

### ISSUE THREAD

**Issue by OmarAlsabbagh** [clarat-org/clarat#1207]
Name der Sprache auf Deutsch: Ewe
Name der Sprache in der Sprache selbst: Eʋegbe
ISO 639-2 Code der Sprache: ewe

Name der Sprache auf Deutsch:  Zarma
Name der Sprache in der Sprache selbst:  Djerma
ISO 639-3 Code der Sprache:  dje

Name der Sprache auf Deutsch:  Gen
Name der Sprache in der Sprache selbst:  Mina
ISO 639-3 Code der Sprache:  gej

**Comment by OmarAlsabbagh** [comment]
A new language will be added to this group:

Kirundi 
ISO 639-2: run

**Comment by OmarAlsabbagh** [comment]
b4c4d8b143c7d7edd094af49a2ebad62dfb09d0a

**Comment by OmarAlsabbagh** [comment]
@b4c4d8b

**Comment by OmarAlsabbagh** [comment]
https://github.com/clarat-org/clarat_base/commit/b4c4d8b143c7d7edd094af49a2ebad62dfb09d0a

**Comment by NilsVollmer** [comment]
Identifier in _base sind gemerged. Es fehlen jetzt noch die entsprechenden Änderungen auf clarat & claradmin.

**Comment by OmarAlsabbagh** [comment]
@NilsVollmer Was für @fc905d4 und @0688a74
--

**Comment by NilsVollmer** [comment]
Achso die hatte ich nicht gefunden, weil sie hier noch nicht verlinkt waren. Alles klar, dann gucke ich mir die an, sobald ich Zeit habe.

**Comment by OmarAlsabbagh** [comment]
Doch alles wurde hier im Verfahren dieses Issues erwähnet. Allerdings Du hast recht, habe keine PRs gemacht.
Perfekt, dass Du jetzt die commits gefunden hast :-)

**Comment by allthegoldt** [comment]
Deploy TODO: 
LanguageFilter.create! identifier: 'ewe', name: 'Ewe'
LanguageFilter.create! identifier: 'gej', name: 'Gen'
LanguageFilter.create! identifier: 'dje', name: 'Zarma'
LanguageFilter.create! identifier: 'run', name: 'Kirundi'

**Comment by allthegoldt** [comment]
Claudia sagt es funktioniert
