### ISSUE TITLE
Beim Duplizieren Öffnungszeiten übernehmen 

### ISSUE THREAD

**Issue by JensBaumgarten** [clarat-org/clarat#121]
Die Eingabe der Öffnungszeiten ist teilweise recht zeitaufwändig.

Wenn ein Angebot dupliziert wird, wäre es daher gut, wenn auch die Eingaben im Datenfeld 'Openings' direkt übernommen würden.

**Comment by Twiek** [comment]
Bitte kurze Einschätzung ob Aufwand > 2 Stunden.

**Comment by KonstantinKo** [comment]
Aufwand < 5 Minuten (und erledigt)
Wir haben die Duplizierung damals auf researcher Anfrage extra abgeschaltet, das musste ich nur rückgängig machen.
