### ISSUE TITLE
Statistikzählung | all done Orgas

### ISSUE THREAD

**Issue by OmarAlsabbagh** [clarat-org/clarat#1210]
Geht um folgendes: In der Statistikzählung im Bereich Organizationsübersicht werden bisher unter all done nur solche Orgas gezählt, deren HQ in der jeweiligen Stadt sind. Das heißt Organisationen, die in mehreren Städten Angebote haben, werden nur für die HQ-Location all done gezählt. Und Orgas, deren HQ nicht in clarat-Städten liegen, aber Angebote in clarat-Städten haben, werden damit auch nicht gezählt.
Wäre super, wenn ihr das hinbekommt, dass die all done Zählung für alle Städte, in denen es approvte Angebote gibt, gilt.

- Beispiel:

Orga XYZ hat in Berlin, Hamburg und München Angebote. Der HQ der Orga ist in Berlin.
Das heißt, die Orga wird für alle drei Städte als Orga gezählt. 
Wenn nun die Orga all done geklickt wird, wird die Orga nur für den HQ Berlin gezählt. Das heißt Hamburg und München wird nicht als all done gezählt, obwohl die Orga in den jeweiligen Städten in die Orgazählung aufgenommen wurde.
Verzerrt also die Übersicht, wie viele Orgas all done sind. Deswegen wäre es super, wenn man es so einstellen könnte, dass die all done Zählung nicht nur bei Berlin zählt, sondern auch bei München und Hamburg. 

Nachtrag: Diese Zählweise soll dann auch für alle anderen states gelten, d.h. sobald man unter /statistics/organization_overview eine Einschränkung bezüglich der Stadt vornimmt.

**Comment by Twiek** [comment]
@allthegoldt Es sollte aber AUCH der Sitz der Orga gezählt werden, d.h. wenn

**Comment by NilsVollmer** [comment]
Bug: Wenn man auf einer overview Page war und dann zu einer anderen geht, gibt es aktuell einen Fehler.
