### ISSUE TITLE
Explanation von Tags und Kategorien an Algolia senden

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1214]
Und entsprechend in der Suche berücksichtigen.

**Comment by NilsVollmer** [comment]
Deploy TODO: alle Angebote aller Kategorien mit Explanation müssen neu indiziert werden!

@Twiek Obacht: wenn sich die Explanation eine Kategorie ändert, werden die davon betroffenen Angebote noch nicht re-indiziert. Das sollte dann wohl ein eigenes Issue werden.
