### ISSUE TITLE
Angebotsumzug

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1216]
Alle Angebote der Kategorie "Todesfall" (ID 473) solle in die Kategorie "Probleme in der Familie" (ID 378) umziehen (die Verknüpfung mit "Todesfall" --> ID 473 würde also entfernt). Zusätzlich sollen diese Angebote den neuen tag "Todesfall" bekommen.

**Comment by mokus80** [comment]
Task auf Produktion erfolgreich durchgelaufen...
