### ISSUE TITLE
Facebooklink in den Footer einbauen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1217]
Einfache Verlinkung, kein Social-PLugin, aber gerne mit Symbol/Grafik (Vgl. z.B. betterplace.org).

Wichtig: Getrennte Links für Family und Refugees: 
https://www.facebook.com/clarat-family-1067489519960102/
https://www.facebook.com/claratrefugees/

**Comment by marcus-herrmann** [comment]
![localhost-3000- kopie](https://user-images.githubusercontent.com/505181/27902489-35acebce-6236-11e7-9a31-66dc3c17bdf0.png)
![localhost-3000-](https://user-images.githubusercontent.com/505181/27902490-35b15308-6236-11e7-8a29-2d47e343e2c8.png)

**Comment by marcus-herrmann** [comment]
![localhost-3000- kopie2](https://user-images.githubusercontent.com/505181/27902705-eb423b6a-6236-11e7-865d-43055ee48bae.jpg)
![localhost-3000- kopie3](https://user-images.githubusercontent.com/505181/27902754-16123f52-6237-11e7-8b20-904104d89230.jpg)

**Comment by Twiek** [comment]
![bildschirmfoto 2017-07-06 um 16 24 42](https://user-images.githubusercontent.com/432388/27915863-bfc2af2a-6267-11e7-851e-8c6bf4253417.png)

Auf der Startseite (wo man sich für eine Welt entscheiden muss) erscheint nur der Link zu clarat Refugees. Hier sollten aber beide auftauchen.

**Comment by marcus-herrmann** [comment]
PR aktualisiert

**Comment by Twiek** [comment]
@allthegoldt Bitte noch einmal codeseitig drüberschauen und dann in develop mergen.
