### ISSUE TITLE
Rahmen für neues Wording minimal anpassen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1219]
Neue Übersetzungen liegen in Localeapp ('Unterstützungsangebote' wurde an einigen Stellen durch 'Hilfe' ersetzt). Teilweise könnte man schauen, ob man die 'Kästchen' drumherum anpasst oder z.B. den Zeilenumbruch neu definiert (don't get fancy).

![bildschirmfoto 2017-07-07 um 10 43 55](https://user-images.githubusercontent.com/432388/27951279-a5f774ac-6304-11e7-94a2-5ef148428c7d.png)

![bildschirmfoto 2017-07-07 um 10 44 05](https://user-images.githubusercontent.com/432388/27951283-ab5055a4-6304-11e7-831a-d887828f600b.png)

![bildschirmfoto 2017-07-07 um 10 44 17](https://user-images.githubusercontent.com/432388/27951286-af5b7a52-6304-11e7-9776-583020f62dee.png)

**Comment by marcus-herrmann** [comment]
PR ist gestellt: #1226
