### ISSUE TITLE
Angebote: Sortierung nach 'Creator'

### ISSUE THREAD

**Issue by JensBaumgarten** [clarat-org/clarat#122]
Es wäre hilfreich, wenn sich die Angebote im Backend auch nach den Namen der Researcher sortieren ließen. 

![filter](https://cloud.githubusercontent.com/assets/10612933/5920898/60d5ffd4-a640-11e4-8100-2398901bbfd7.png)

**Comment by Twiek** [comment]
Wofür genau wird das gebraucht?

**Comment by Twiek** [comment]
Bitte checken wie man das lösen kann. Falls Dir auch keine straight-forward Lösung einfällt eventuell die E-Mail nehmen (und wenn Du fancy sein willst versuchen daraus den Nachnamen zu parsen und groß zu schreiben).

**Comment by KonstantinKo** [comment]
Aktueller Vorschlag ist deployed: absolut nicht fancy, dafür nur 2 Minuten Arbeit. Man filtert einfach nach dem Feld "created_by". Dafür muss man zwar die Nummer des entsprechenden Menschen kennen und kann nicht nach Namen gehen, aber die Nummer kann man ja im "Nutzer" Reiter nachsehen.

**Comment by KonstantinKo** [comment]
Kurze Erklärung:
![clarat1](https://cloud.githubusercontent.com/assets/779660/6019250/cc90ef28-ab9e-11e4-9e8a-70660ef59cc8.png)
![clarat2](https://cloud.githubusercontent.com/assets/779660/6019254/d13e2658-ab9e-11e4-86ce-038cd74e1101.png)
