### ISSUE TITLE
Angebote löschen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1220]
Out of Scope Angebote sollen gelöscht werden. Konkret geht es um die folgenden IDs:
[107, 131, 867, 1131, 1133, 1147, 1151, 1184, 1334, 1335, 1535, 1554, 1555, 1556, 1557, 1745, 1761, 1895, 1900, 2169, 2306, 2322, 2383, 2432, 2434, 2479, 2636, 2637, 2648, 2664, 2666, 2667, 2695, 2696, 2734, 2736, 2738, 2745, 2755, 2757, 2810, 2826, 2829, 2848, 2856, 2876, 2944, 2997, 3014, 3039, 3056, 3383, 3964, 3981, 4547, 4675, 4679, 4726, 5350, 6045, 6355, 6844, 7145, 9317, 9716, 10150, 10894, 10912, 10975, 11024, 11044, 11068, 11624, 11792, 12047, 12051, 12210, 12353, 12862, 13107, 13120, 13163, 13220, 13222, 13223, 15279, 15546, 15625, 15648, 15657, 15743, 17598, 17896, 18198, 18205, 18209, 18264, 18468, 18515, 18903, 20147, 20456, 21029, 21048, 21263, 21308, 548, 2170, 2667, 2694, 2744, 2916, 2945, 2998, 3111, 3721, 3722, 4724, 6046, 6870, 10001, 10152, 10913, 10914, 10915, 12211, 12212, 13121, 13196, 13202, 13207, 15628, 15653, 16807, 18243, 18245, 18247, 18248, 18249, 18250, 18251, 18252, 18253, 18254, 18256, 18259, 18260, 18261, 18262, 19630, 19632, 19636, 19639, 19641, 20149, 1929, 1957, 1958, 1959, 2649, 2765, 2784, 2988, 3015, 3034, 3057, 3110, 3195, 3333, 3968, 4050, 4059, 4211, 4244, 4263, 4269, 4575, 4576, 4677, 4680, 5393, 6326, 6564, 7288, 10798, 10903, 11046, 11143, 11148, 11635, 12005, 12354, 13272, 13290, 13436, 15433, 15636, 20467, 21078, 21311, 2700, 3058, 4047, 4247, 4682, 5356, 10911, 11152, 11807, 15434, 1372, 1465, 1511, 1512, 1513, 1514, 2172, 2531, 2654, 2655, 2656, 2657, 2710, 2713, 2714, 2728, 2729, 2730, 2772, 3566, 3572, 5131, 5160, 5458, 5460, 5461, 6749, 6774, 6776, 12146, 12148, 12161, 15685, 17837, 17809, 17260, 17246, 17241, 17238, 5693, 5648, 3865, 3862, 3860, 3850, 3849, 1946, 525, 14784, 14262, 12863, 8399, 5141, 5134, 5133, 5131, 3760, 3759, 3464, 3397, 2732, 2443, 2438]

**Comment by allthegoldt** [comment]
Sind gelöscht. Man könnte noch ggf. folgende E-Mails löschen, die weder Offers, noch Organizations noch ContactPeople haben: [521, 523, 533, 534, 1820, 80, 31, 2186, 70, 77, 1288, 92, 93, 94, 95, 98, 99, 100, 114, 160, 162, 164, 165, 167, 168, 238, 225, 234, 260, 541, 271, 2187, 288, 343, 346, 618, 1310, 1311, 395, 611, 393, 357, 445, 460, 476, 1328, 478, 488, 494, 23, 25, 78, 86, 87, 89, 157, 166, 176, 177, 2043, 205, 228, 338, 339, 350, 605, 606, 608, 616, 630, 1467, 2, 97, 371, 388, 391, 392, 364, 680, 1473, 705, 708, 714, 725, 727, 728, 729, 731, 732, 733, 427, 429, 433, 760, 1351, 1364, 803, 2207, 1851, 833, 1499, 837, 852, 765, 784, 864, 867, 890, 1391, 1394, 898, 899, 900, 901, 902, 908, 919, 920, 2208, 946, 2212, 2803, 1507, 1599, 1601, 2094, 1354, 1437, 1438, 1439, 1595, 1875, 2215, 1660, 1662, 1674, 959, 1029, 1459, 1461, 984, 990, 1485, 1876, 1877, 1007, 1028, 981, 1062, 1065, 1614, 1641, 1047, 2361, 718, 722, 1883, 836, 868, 891, 994, 996, 1036, 1038, 1106, 1445, 1120, 1122, 1892, 1893, 1112, 1170, 1176, 1178, 2231, 1183, 1134, 1258, 1271, 1233, 1549, 1559, 1278, 1294, 1986, 1987, 1997, 2010, 1331, 1302, 1339, 470, 831, 1097, 1098, 1119, 1201, 1928, 2095, 2348, 2374, 2378, 2379, 2288, 2386, 1944, 1663, 1640, 2148, 1680, 1685, 440, 617, 1703, 1735, 2330, 1756, 1777, 2714, 1807, 1809, 1810, 2387, 2443, 2451, 2438, 2488, 2524, 2540, 2543, 2553, 2555, 2560, 2571, 2597, 2602, 2611, 2572, 2649, 2659, 2663, 2688, 2702, 2665, 2712, 2717, 2719, 2723, 2725, 2732, 2716, 2755, 2763, 2785, 2934, 2953, 3001, 2977, 3007, 3009, 3010, 3011, 3086, 3087, 3114, 3072, 3140, 3143, 3145, 3147, 3168, 3170, 2853, 3222, 3236, 3251, 3252, 3285, 3267, 3314, 3316, 3330, 3331, 3345, 3401, 3403, 3417, 3440, 3495, 3540, 3551, 3579, 3580, 3582, 3594, 3602, 3608, 3609, 3611, 3623, 3674, 3701, 3711, 3733, 3627, 3789, 3827, 3841, 3842, 3849, 3876, 3886, 3949, 3836, 3970, 3910, 4043, 4140, 4167, 4182, 3982, 4220, 4235, 4286, 4342]

**Comment by allthegoldt** [comment]
Ebenso haben folgende Webseiten weder Orgas noch Offers: [3448, 5, 28, 27, 26, 25, 24, 8, 10, 9, 11, 12, 34, 14, 3454, 3455, 17, 16, 18, 23, 22, 21, 20, 19, 39, 40, 41, 42, 43, 44, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 59, 62, 65, 68, 70, 3699, 356, 3700, 73, 74, 76, 84, 85, 86, 87, 3451, 92, 93, 98, 100, 111, 115, 3462, 119, 120, 122, 124, 125, 127, 132, 3463, 139, 140, 141, 142, 143, 145, 146, 335, 357, 157, 159, 3459, 3466, 168, 169, 5279, 178, 179, 180, 181, 182, 183, 184, 185, 3706, 188, 190, 3711, 3721, 202, 276, 203, 204, 210, 211, 212, 213, 214, 215, 216, 217, 218, 221, 224, 229, 231, 3465, 241, 243, 244, 251, 253, 255, 256, 257, 258, 259, 260, 262, 265, 266, 4045, 267, 268, 269, 270, 271, 272, 6937, 286, 287, 303, 310, 311, 312, 315, 322, 327, 5835, 281, 279, 280, 283, 275, 329, 330, 331, 336, 338, 342, 343, 345, 274, 347, 348, 350, 351, 361, 369, 3474, 380, 381, 382, 383, 384, 385, 392, 394, 395, 396, 397, 400, 401, 405, 410, 411, 412, 413, 415, 417, 418, 419, 420, 421, 424, 425, 426, 427, 428, 429, 441, 443, 448, 458, 460, 462, 472, 478, 481, 696, 482, 483, 492, 494, 497, 499, 501, 503, 507, 508, 512, 518, 519, 520, 521, 523, 524, 525, 526, 528, 529, 530, 531, 533, 536, 543, 544, 546, 551, 553, 547, 556, 557, 559, 573, 579, 3492, 582, 3493, 584, 585, 586, 587, 589, 590, 591, 592, 596, 3495, 600, 3490, 3494, 3496, 568, 566, 576, 645, 646, 649, 651, 654, 655, 656, 657, 658, 666, 677, 678, 680, 684, 686, 692, 693, 698, 699, 700, 703, 705, 706, 708, 711, 712, 715, 718, 719, 720, 721, 723, 726, 6953, 737, 740, 743, 744, 746, 749, 750, 752, 753, 756, 761, 762, 767, 769, 772, 773, 776, 778, 783, 786, 787, 788, 789, 792, 793, 796, 798, 799, 800, 801, 803, 804, 806, 807, 808, 809, 3498, 812, 813, 814, 815, 5292, 817, 819, 820, 5293, 824, 827, 829, 830, 831, 832, 838, 3500, 845, 847, 849, 850, 852, 853, 856, 857, 862, 865, 868, 870, 873, 875, 881, 890, 895, 896, 899, 3529, 906, 908, 3530, 912, 915, 917, 918, 3501, 922, 923, 924, 3511, 934, 935, 936, 3534, 950, 956, 3536, 958, 963, 968, 970, 975, 981, 983, 985, 986, 991, 993, 994, 997, 957, 1001, 1018, 1023, 1026, 1028, 3515, 3517, 1036, 1038, 1039, 3538, 1043, 1046, 1049, 1050, 1051, 1054, 1055, 1057, 1058, 1059, 1061, 1063, 3543, 1066, 1068, 1069, 1072, 1073, 1074, 1082, 1085, 1089, 1091, 1097, 1101, 1104, 1105, 1106, 1107, 1108, 1110, 1111, 1112, 1117, 1118, 1119, 1121, 3742, 1128, 4053, 1130, 1133, 1134, 3514, 1142, 1147, 1149, 1150, 1152, 1154, 3519, 3521, 161, 1170, 1172, 1173, 1174, 1175, 1178, 1184, 1191, 1192, 1194, 3548, 1198, 1203, 1204, 1207, 1214, 1223, 1224, 1225, 1227, 1228, 1231, 1234, 1239, 1252, 1255, 1263, 1265, 1267, 1276, 1277, 1279, 1281, 1282, 1285, 1286, 1288, 1289, 1296, 1299, 1303, 1305, 1312, 1313, 1329, 1330, 1331, 1333, 1335, 1336, 1327, 1340, 1344, 1347, 1348, 1357, 1358, 1359, 1361, 1362, 1367, 1376, 1388, 1392, 1395, 1397, 3551, 1411, 1419, 1422, 1430, 1432, 1434, 1447, 3750, 1451, 1456, 1459, 1461, 1462, 1463, 1464, 1466, 1467, 1468, 4056, 6428, 1472, 1474, 1479, 1486, 1487, 1488, 1489, 1490, 3576, 1503, 3578, 1512, 1515, 1520, 1526, 1528, 1530, 1531, 1533, 1534, 1535, 3561, 1538, 1540, 1541, 1546, 1548, 1551, 1553, 1554, 1560, 1566, 1568, 1570, 1572, 1574, 1576, 1578, 1580, 1582, 1583, 2045, 2405, 2406, 2407, 1594, 1603, 1606, 1607, 1612, 1613, 1615, 1619, 1620, 1629, 1635, 1637, 1641, 1643, 1644, 2325, 1659, 1657, 1681, 1685, 1687, 1691, 1706, 1712, 1713, 1719, 1723, 1725, 1732, 1733, 1734, 1735, 1736, 3569, 1745, 1746, 1755, 1760, 1761, 1765, 1767, 1769, 3590, 3593, 1785, 1786, 1796, 1800, 1801, 1804, 1805, 1806, 1750, 1822, 1825, 1826, 1827, 1830, 1833, 1835, 1837, 1842, 7628, 1871, 1872, 1874, 1875, 1838, 1868, 1810, 1873, 1882, 1889, 1890, 1896, 1898, 1899, 3602, 1902, 1901, 1903, 1910, 1909, 1913, 1914, 1922, 1930, 3618, 1935, 1938, 1811, 1939, 63, 94, 137, 3599, 3616, 3782, 3783, 3789, 3798, 208, 247, 248, 436, 668, 977, 1045, 1480, 1481, 1494, 1498, 1504, 1505, 1507, 1536, 3626, 1683, 1694, 1696, 1700, 1709, 1768, 1772, 1776, 1782, 1789, 1809, 1812, 1828, 1829, 1831, 1832, 1834, 1891, 1904, 1926, 2127, 1950, 1954, 1955, 1958, 1963, 1964, 527, 1968, 1974, 7030, 2009, 2012, 2014, 2018, 4062, 2026, 2033, 2034, 2035, 2038, 2043, 2044, 2046, 2057, 2058, 2062, 2074, 2075, 2080, 2082, 2083, 2086, 2087, 2094, 2101, 2104, 2107, 2111, 2113, 2115, 2126, 2129, 2130, 2133, 2140, 2143, 2173, 2181, 2186, 2187, 2202, 2204, 2205, 2206, 2195, 2216, 2218, 2219, 2220, 2224, 2231, 2232, 2240, 2242, 2048, 2256, 2257, 2260, 2265, 7047, 2269, 2270, 2271, 2274, 2275, 2277, 2278, 2279, 2282, 2284, 2285, 2287, 2289, 2290, 2291, 2293, 2294, 2300, 2301, 2302, 2303, 2304, 2305, 2306, 2319, 7644, 3647, 3648, 3657, 3660, 3661, 3816, 5669, 3833, 2336, 2337, 2338, 2340, 2342, 2344, 2345, 2346, 2347, 2352, 2354, 2357, 2358, 2360, 2362, 2364, 2365, 2368, 2369, 2376, 2377, 2381, 3652, 3658, 2394, 2396, 2397, 2402, 2412, 2413, 2414, 2417, 2422, 2424, 2436, 2437, 2438, 2446, 2453, 2473, 2475, 2476, 2477, 2479, 3663, 2504, 2510, 2523, 2529, 2530, 3679, 2546, 2549, 2562, 2565, 2566, 2567, 2569, 2574, 2575, 2576, 2522, 2585, 2588, 3673, 2598, 2599, 5310, 2618, 3669, 6635, 2654, 2660, 3891, 6073, 2648, 2665, 2666, 2667, 2669, 2694, 2699, 2701, 2703, 2707, 2709, 2710, 2711, 2722, 2724, 5316, 2685, 3688, 3694, 2738, 2739, 2755, 2756, 5679, 2770, 2771, 2776, 2778, 2779, 2780, 2782, 2783, 2784, 2785, 3813, 3814, 3936, 5334, 2799, 2800, 5335, 5336, 2827, 2832, 2841, 2863, 2871, 3920, 3925, 3937, 3972, 3973, 3974, 3981, 3989, 3994, 2883, 2889, 2890, 2898, 2907, 2926, 2933, 2929, 2928, 2932, 2891, 2946, 2954, 2956, 3956, 3967, 4020, 4032, 2999, 6077, 6083, 3008, 4034, 3014, 3016, 3017, 3025, 3026, 3038, 3050, 3059, 3063, 3064, 3065, 3067, 3068, 3072, 3089, 3090, 3093, 3094, 3095, 3098, 3099, 3109, 3120, 3121, 3142, 3145, 3186, 3187, 3188, 3346, 3206, 4035, 3201, 3205, 3230, 3239, 3241, 3243, 3246, 3247, 3248, 3249, 3211, 3279, 3280, 3281, 3284, 7090, 3291, 3292, 3299, 3235, 3302, 3303, 3304, 3311, 3313, 3314, 3294, 3333, 3336, 3343, 3349, 3352, 3357, 3365, 3367, 3368, 3387, 4042, 3398, 3399, 3400, 3401, 3405, 3411, 3414, 3418, 7102, 3426, 3437, 3438, 3440, 7104, 7108, 4118, 4122, 4125, 4134, 4139, 4147, 4148, 4154, 4162, 4116, 4157, 4167, 4172, 4175, 2563, 2233, 2564, 2235, 2712, 6016, 839, 3028, 2744, 6199, 7123, 5695, 5696, 5697, 5698, 5704, 6115, 6019, 6025, 3566, 6051, 6127, 6135, 5347, 5350, 5351, 5373, 4201, 4206, 4209, 4211, 4220, 5404, 5416, 5424, 5447, 5451, 6069, 5456, 5465, 5467, 5464, 5487, 5500, 5503, 5508, 5511, 5525, 5526, 5531, 5524, 2079, 4249, 4264, 4284, 4285, 2777, 3435, 6095, 6096, 4994, 6057, 4676, 5879, 5902, 5909, 5901, 3600, 4300, 4305, 4312, 4325, 4297, 4328, 4346, 4347, 4361, 4372, 4379, 4387, 4452, 4453, 4391, 4395, 4399, 4448, 4405, 4408, 4412, 4413, 4414, 4417, 4419, 4420, 4427, 4431, 4434, 4436, 4451, 4459, 4474, 4479, 4480, 4484, 4491, 4493, 4497, 4498, 4500, 4502, 4515, 7166, 4540, 4541, 4542, 4543, 4552, 4555, 4562, 4570, 4576, 5878, 5913, 5915, 5954, 4589, 4585, 4586, 4587, 4591, 4596, 4614, 5575, 5582, 5583, 5585, 5586, 6065, 6066, 7193, 5919, 6061, 4642, 4650, 4660, 4662, 4665, 4666, 5597, 5599, 5601, 7219, 7220, 4711, 4698, 5622, 5631, 5707, 4795, 5745, 5754, 4821, 4823, 4825, 889, 4804, 4837, 4840, 4843, 6241, 4862, 4864, 4880, 4858, 4903, 5750, 5801, 5806, 5808, 5773, 5774, 5775, 5779, 5784, 5792, 5793, 5794, 1124, 5819, 4921, 4922, 4928, 4943, 5007, 5016, 5019, 5020, 5026, 5036, 5038, 6327, 6328, 5040, 5065, 5066, 5067, 5068, 5070, 5071, 5072, 5075, 5076, 5077, 5078, 5079, 6386, 5083, 5084, 5803, 5090, 6161, 6162, 6176, 5111, 5119, 5145, 5157, 5825, 5175, 5178, 5186, 5183, 5192, 5195, 5196, 5200, 5201, 5979, 5170, 5980, 5982, 5169, 5224, 5238, 5241, 5243, 5244, 5246, 5250, 5252, 5254, 5262, 5263, 7238, 7243, 7251, 7323, 7324, 7263, 7276, 6212, 6248, 7338, 7339, 7340, 7359, 7371, 6322, 4924, 4939, 2061, 7287, 7289, 7290, 4831, 4488, 7429, 6416, 4702, 4950, 5227, 7305, 7306, 7496, 7498, 7501, 6439, 6447, 6468, 4697, 4945, 6494, 6495, 6496, 6519, 6543, 6567, 6568, 6589, 6599, 7524, 6642, 6650, 7537, 7538, 6673, 6688, 7561, 7563, 6718, 6723, 6724, 6711, 6735, 6738, 6739, 6740, 6741, 6742, 6743, 6744, 6745, 6747, 6757, 1200, 6717, 6779, 6780, 6791, 6827, 6828, 6845, 6849, 6856, 7601, 6902, 7603, 4926, 7716, 167, 278, 282, 636, 672, 863, 861, 999, 1056, 1197, 2600, 2702, 2814, 2815, 2872, 3213, 3272, 3433, 3541, 3589, 3743, 3774, 3848, 3879, 3883, 3887, 4223, 4526, 5298, 1928, 1960, 2155, 2312, 2619, 2668, 2758, 3087, 3177, 3212, 3429, 3479, 3558, 3740, 3773, 3878, 3882, 3893, 3900, 3902, 3907, 4245, 4254, 4336, 1961, 2244, 2568, 2587, 2662, 2725, 2804, 2868, 2870, 2922, 3045, 3203, 3298, 3379, 3391, 3464, 3542, 3881, 3888, 3892, 3894, 3898, 3901, 3904, 3908, 2073, 2131, 2332, 2594, 2633, 2659, 2688, 2690, 2691, 3029, 3143, 3165, 3214, 3434, 3467, 3468, 3503, 3880, 3899, 3903, 3905, 3931, 4618, 4282, 4388, 3769]

**Comment by NilsVollmer** [comment]
@Twiek bitte checken, ob das so passt.
