### ISSUE TITLE
'Translated by Google' Hinweis im Header auf der deutschen Seite rausnehmen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1225]
Nur anzeigen, wenn auch wirklich was übersetzt wurde.

**Comment by MichiBecker** [comment]
wie aufwendig wäre es, das "translated by google" nur anzuzeigen, wenn der flag "translatedbygoogle" gesetzt ist? Und dann nicht oben in der Headleiste, sondern auf Angebotsseite rechtsbündig über der Description Box? Das wäre die "most realistic" Lösung. Und wir hätten das Google Logo wie gewünscht aus unserem Header raus.
