### ISSUE TITLE
Richtige Icon Modifier auf Offer#show

### ISSUE THREAD

**Issue by marcus-herrmann** [clarat-org/clarat#123]
Aktuell nur Dummies.

**Comment by Twiek** [comment]
Asche auf mein Haupt, habe vergessen das anzusprechen... Haben uns jetzt nämlich erstmal entschieden, erstmal gar keine Icons anzuzeigen da sie mehr für Verwirrung gesorgt als Nutzen gestiftet haben.

**Comment by marcus-herrmann** [comment]
Kein Problem. Die Icons, die du zuletzt entfernt hast, waren allerdings auch nur Dummies und v.a. immer die gleichen. Kein Wunder also, dass das verwirrt hat. Aktuelle Implementierung gibt jetzt das tatsächliche Main Tag Icon aus.

Kanns aber im Slim-Template auskommentieren - so wird es nicht gerendert, ist aber sofort bei Bedarf verfügbar.

**Comment by Twiek** [comment]
Ja, gerne auskommentieren.

**Comment by marcus-herrmann** [comment]
Done: 6eb9c7c3e86f3785f1fcde9fee9abeb75fd223d9 (master)
