### ISSUE TITLE
Heavy User Popup wird nicht richtig angezeigt

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1230]
Das Heavy User Popup wird vor einer tendenziell leeren Seite angezeigt.

![bildschirmfoto 2017-07-17 um 11 54 28](https://user-images.githubusercontent.com/432388/28263408-eb862b5a-6ae6-11e7-9012-31f347b3118e.png)

Hier die Anzeige, wenn ich das Popup wegklicke:

![bildschirmfoto 2017-07-17 um 11 56 31](https://user-images.githubusercontent.com/432388/28263431-01b17754-6ae7-11e7-9088-96441bb33c39.png)

Zwei Änderungswünsche:

Must have: 
- [ ] Nach wegklicken komme ich zu der Seite zu der ich eigentlich wollte.

Nice to have:
- [ ] Das Popup soll direkt über der Seite angezeigt werden die ich ansteuere (im konkreten Fall also www.clarat.org).

**Comment by mokus80** [comment]
https://github.com/clarat-org/clarat/pull/1233/files

**Comment by MichiBecker** [comment]
@mokus80  können im Zuge dieser Änderung auch die Anzeigekriterien geändert werden?

Das Popup sollte JEDEM Nutzer angezeigt werden (weil die Response Rate so miserabel ist)

Vielleicht nach 10 Sekunden auf der Suchergebnisseite? was meint ihr? @Twiek ?

**Comment by MichiBecker** [comment]
Falls das noch eine zu hohe Hürde ist, können wir nochmal nachjustieren auf "egal auf welcher Seite nach 10 Sekunden"

**Comment by MichiBecker** [comment]
nochmal.... JEDEM Nutzer anzeigen nach 5 Sekunden auf der Angebotsseite. Dann hat er einen Use Case von clarat durchlaufen und kann alle Fragen beantworten. Zum Beispiel auch "Hast du gefunden, wonach du gesucht hast"
