### ISSUE TITLE
Pflichtfelder im neuen Backend als solche kennzeichnen 

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1235]
Gerne mit einem '*' hinter dem Namen des Feldes.

**Comment by KonstantinKo** [comment]
Implementationshinweise:

Die Information ob ein Feld Pflicht ist oder nicht hat das "Frackend" schon. In der validation() Methode von FormObjects. Die Information da heraus zu bekommen ist nicht ganz einfach.
Schneller Pseudocode:

```es6
const instance = new OrgaCreateFormObject()
const validationTester = new RequiredValidationTester()
instance.validation.bind(validationTester)()
class RequiredValidationTester {
  required(attribute) {
    const filledTester = {}
    filledTester.prototype.filled = function() {
      this.pushRequireCalledAttributes attribute
    }
    return filledTester
  }
  pushReq... {...}
  get req... {...}
}
validationTester.requiredCalledAttributes // => ['name', 'comment']
```

Bitte bei der Gelegenheit auch mal schauen, ob du rausfindest, warum die `required('website').filled()` validation gerade noch nichts Vernünftiges macht.
