### ISSUE TITLE
'Slug'-Name aktualisiert sich nicht nach Namensänderung

### ISSUE THREAD

**Issue by JensBaumgarten** [clarat-org/clarat#124]
Mit dem Speichern eines Angebots wird der 'Slug'-Name automatisch generiert. Dieser wird jedoch nicht neu generiert, wenn der Name des Angebots nach dem Speichern nochmal geändert wird.

Beispiel:
1. Eingabe des Angebotnamens "Schulpsychologische Beratung"
2. Speichern des Angebots generiert den Slug-Namen 'schulpsychologische-beratung'
3. Änderung des Angebotsnamens in "Schulpsychologische Beratung Kreuzberg"
4. Erneutes Speichern

Ergebnis: Der Slugname müsste nun lauten: 'schulpsychologische-beratung-kreuzberg'. Es bleibt momentan aber bei: 'schulpsychologische-beratung'.

**Comment by Twiek** [comment]
Solange wir nicht 'live' sind scheint eine mehrfache Änderung der URL unproblematisch. Vorschläge wie man das handeln könnte wenn die Seite potentiell extern verlinkt ist? Einen automatisierten 301 redirect zu integrieren klingt nach overkill, oder?

**Comment by KonstantinKo** [comment]
Das System war auch so wie es jetzt ist konzipiert. URLs sollten sich eigentlich nicht mehr ändern. Der Titel sollte im Optimalfall gut überlegt sein und wenn man tatsächlich mal den Slug ändern möchte, dann kann man das ja manuell im Editier-Bereich machen (sollte aber wegen externer Verlinkung gut überlegt sein).
Hmm das mit 301 redirects ist tatsache schwierig. Bei FM haben wir mal was eingebaut was sowas kann, aber ich bin mir nicht sicher ob das mit heroku geht (man muss das in Bereichen abgreifen, die noch vor der Rails App liegen). EIn automatisches System ist dabei auch aufwändiger als ein manuelles (also in ner Datei redirects eintragen, ins repo einchecken und deployen)
Wenn das gewünscht ist dann mach das besser als eigenes Issue auf

**Comment by Twiek** [comment]
Werde es für die Zukunft so kommunizieren. Eventuell könnte man vor dem Livegang aber noch mal alle URLs/slugs neu generieren, da sich aktuell noch verhältnismäßig viel ändert und wir ja keine externe Verlinkung kaputt machen. Lass uns drüber sprechen.

**Comment by KonstantinKo** [comment]
Neu generiern vor Livegang ist kein Problem. Ich verschieb das hier mal ins Backlog und wir holen es im März wieder raus.

**Comment by KonstantinKo** [comment]
Slugs wurden zum Livegang aktualisiert
