### ISSUE TITLE
Event Tracking GA

### ISSUE THREAD

**Issue by MichiBecker** [clarat-org/clarat#1246]
Checken, warum keine Daten in GA ankommen für:

- automated translation
- glossar Tracker

und vielleicht ergibt sich ja auch was zu unserem immer noch bestehenden

NOT SET Problem?

**Comment by allthegoldt** [comment]
automated translation haben wir geklärt - hier geht es vor allem um den Bug-Fix für den Glossar-Hover-Tracker

**Comment by Twiek** [comment]
@MichiBecker Ist da jetzt noch was offen und wenn ja, was (Issue verlinken)? Ansonsten bitte schließen.
