### ISSUE TITLE
Um-Assign Übersetzungsangebote von Übersetzern zu System

### ISSUE THREAD

**Issue by BlahBlub90** [clarat-org/clarat#1248]
Orga ID 379 934 19 64 24 59 87 161 227 246 280 609 611 655 665 720 784 794 822 843 862 904 915 958 1054 1156 1216 1231 1250 9 13 37 41 88 93 111 112 127 133 134 138 168 178 194 283 492 555 567 604 610 635 645 659 666 693 736 741 743 765 820 826 898 931 939 964 978 1056 1082 1119 1120 1132 1189 1217 1249 1251 1260 1344

Hi Konstantin,

kannst du wie besprochen alle Übersetzungsangebote, die an diesen kranken Orgas liegen, mir zuweisen und somit aus der To-Do Liste von Nahla nehmen? Die Übersetzungsangebote, die durch Google Translation vorgenommen werden, sind natürlich nicht relevant. 

Danke
Tian

**Comment by KonstantinKo** [comment]
- Änderung besprochen: Angebotsübersetzungen (nur fa, ar, en) werden dem System zugewiesen. Nach Bearbeitung der Angebote sollten diese automatisch wieder bei den Übersetzern landen.

- Zuweisungen per Konsole erledigt!

**Comment by BlahBlub90** [comment]
Danke!
