### ISSUE TITLE
Zu großer Abstand in mobiler Ansicht

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#125]
Auf der Suchergebnisseite zwischen Paginaton und Schlagwortfilter.
![bildschirmfoto 2015-01-28 um 12 57 35](https://cloud.githubusercontent.com/assets/432388/5937236/6225fdf0-a6ed-11e4-87e5-6953474ca3f7.png)

**Comment by marcus-herrmann** [comment]
Alles klar, Ursache bekannt, wird gefixt mit #107

**Comment by marcus-herrmann** [comment]
Korrigiert mit: f12d49201959f3fdd7c71ee63833852f94d067dc
