### ISSUE TITLE
Bug Chrome Eingabefelder WAS WO "blockiert" (nur staging?)

### ISSUE THREAD

**Issue by MichiBecker** [clarat-org/clarat#1251]
Staging auf Chrome
alle Cookies gelöscht quasi "Jungfräulicher" Besucher

Ich will den Cursor ins WAS Feld setzen... nichts passiert
Das gleiche beim WO Feld
Nur wenn ich die Kategorie anklicke, wird der "Standort festlegen" Ablauf gestartet.
Kann nur über Kategorie Suche abschicken.

Hab es abgefilmt (Quick Time mov) könnt ihr euch bei mir ansehen

@allthegoldt bei dir war es auch? Specify if necessary :)

**Comment by mokus80** [comment]
Kann das Ticket geschlossen werden?
