### ISSUE TITLE
Export Notizen zu den Angeboten aller kranken Orgas

### ISSUE THREAD

**Issue by BlahBlub90** [clarat-org/clarat#1254]
Beim Aktualisieren kranker Orgas möchten wir vorschlagen, dass die Researcher alle bestehenden Angebote löschen und neu anlegen. Allerdings möchten wir dabei sicherstellen, dass die wichtigsten Notizen zu den Angeboten gelesen werden (e.g. Anbieter Feedback & co.) 

Könntet ihr für folgende Orgas alle Notizen (auf Angebots- und Orgaebene) exportieren mit der jeweiligen Angebot und Orga ID, zu der die eine oder andere Notiz gehört? Wenn ihr das direkt in Excel exportieren könnt, wäre es super. Ansonsten nehme ich auch alle erdenklichen Formate. :) 

Danke!
Tian 

Wenn ihr das bis Dienstag Nachmittag schafft, wäre das super!

Liste der Orgas: 

Orga ID
--
379
934
19
64
24
59
87
161
227
246
280
609
611
655
665
720
784
794
822
843
862
904
915
958
1054
1156
1216
1231
1250
9
13
37
41
88
93
111
112
127
133
134
138
168
178
194
283
492
555
567
604
610
635
645
659
666
693
736
741
743
765
820
826
898
931
939
964
978
1056
1082
1119
1120
1132
1189
1217
1249
1251
1260
1344

**Comment by Twiek** [comment]
Muster (https://docs.google.com/spreadsheets/d/1J4CwK4kI7ahIovD5BbM0CyazMYjpzmaViJKSoy8bYSY/edit?ts=59886d88#gid=0)

**Comment by Twiek** [comment]
@mokus80 Kannst Du das bitte mal checken (Muster kann im Zweifelsfall von Tian selbst befüllt werden). Im Idealfall bis morgen (Dienstag) Mittag.
