### ISSUE TITLE
Datenfeld 'Synonyms': variable Größe nötig

### ISSUE THREAD

**Issue by JensBaumgarten** [clarat-org/clarat#126]
Es wäre hilfreich, wenn sich das Datenfeld 'Synonyms' im Backend per Maus größer ziehen ließe. Analog zum Datenfeld 'Description' unter 'Angebot'.

Ziel: Bei der Bearbeitung der Synonyme ist es wichtig, dass man alle Einträge sieht ohne scrollen zu müssen.

Researcher: Sophie

**Comment by Twiek** [comment]
In Kombination mit #120 würde es eventuell Sinn machen statt 'string' gleich auf 'text' umzusteigen und dann die maximal Zeichenzahl auf 400 zu erhöhen, oder?
