### ISSUE TITLE
Bug: nested create von Division(s) (innerhalb einer Orga) klappt nicht

### ISSUE THREAD

**Issue by NilsVollmer** [clarat-org/clarat#1267]
Betrifft sowohl nested als auch standalone create. 403 forbidden error.

**Comment by NilsVollmer** [comment]
Update: Divisionen (nicht-nested) zu erstellen klappt jetzt wieder. Es fehlten die Env-Variablen für die automatischen Zuweisungen.

Der Nested-Create einer Division (innerhalb einer Orga) wirft noch einen 500er Server Fehler.

**Comment by NilsVollmer** [comment]
Update: Bug jetzt lokal reproduziert nach rform update. Der Fehler kommt also vermutlich aus einer der letzten Neuerungen in rform.

**Comment by NilsVollmer** [comment]
Bin gerade ein wenig Lost bzw. habe keine Zeit mehr (muss noch die grüne Liste importieren).

Deshalb darfst du dich am Montag darum herumärgern, @KonstantinKo ;)

Da der Bug gerade nur Screening betrifft und die einen Workaround haben (Division nachträglich in dem standalone Formular erstellen), eilt es auch nicht sehr.

**Comment by NilsVollmer** [comment]
@KonstantinKo ich habe mal ein paar Bugfixes auf dem Branch commited und ein rudimentäres Weiterreichen der Assignment.Create.Errors ist auch drin - not yet working.

**Comment by KonstantinKo** [comment]
So viel ärgern war da gar nicht benötigt ;)
hab das error parsing auch refactored und es sollte funktionieren.
Hab es als fix gleich merged und deployed, ohne PR
