### ISSUE TITLE
Mobiler Filterbutton in der Desktopansicht sichtbar

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#127]
![bildschirmfoto 2015-01-28 um 18 13 38](https://cloud.githubusercontent.com/assets/432388/5942705/7d9c418a-a719-11e4-9786-dfd0f4133d2f.png)

Bitte entfernen.

**Comment by marcus-herrmann** [comment]
Entfernt mit c6da86729258b332266fe20b1d182c9bd1ec526d (master)
