### ISSUE TITLE
1 click Button bei Fake Door 

### ISSUE THREAD

**Issue by MichiBecker** [clarat-org/clarat#1272]
Hallo Damjan,

bitte den Button bei Fake Door Popup so einstellen, dass man nur einmal Abschicken kann und im Besten Falle eine "Vielen Dank" Info einblenden.

Merci

**Comment by allthegoldt** [comment]
https://www.localeapp.com/projects/9072/translations/6078560 Übersetzungen nötig für die Erfolgsmeldung (die sowohl für Location als auch für More Information gleich sein soll).
