### ISSUE TITLE
"Leichen" Splitbase 

### ISSUE THREAD

**Issue by BlahBlub90** [clarat-org/clarat#1273]
Liebes IT Team,

ich habe folgende Splitbases entdeckt, welche auf dem ersten Blick anscheinend "Leichen" im Backend sind. Ich habe ein paar Stichproben gemacht und bis auf SB 2824 haben diese Splitbases auch keine Angebote. 

Könntet ihr über Konsole prüfen: 
- Hängen an diesen SB Angebote? 
- Zu welcher Division bzw. welcher Orga gehören sie? 

Wenn sie wirklich Leichen sind, dann wäre ich dafür, dass wir sie löschen. 

Das eilt jetzt nicht. Aber vielleicht geht das auch schnell. 

Danke!
Tian 

48
57
60
62
67
71
84
85
86
93
100
102
106
108
115
116
117
118
119
120
127
128
131
152
155
156
159
190
191
192
194
195
198
199
223
226
232
239
244
245
258
259
262
269
284
291
303
307
309
310
311
318
343
348
357
363
367
368
369
372
393
395
404
426
427
435
439
443
444
463
467
479
483
494
496
498
522
526
538
540
542
546
550
558
568
570
574
579
591
595
608
616
633
649
655
662
670
671
672
683
692
693
694
696
699
702
706
718
723
724
725
726
731
732
744
745
762
773
776
780
787
788
792
796
797
799
802
805
815
819
827
869
870
881
889
894
897
899
913
916
935
936
937
939
942
953
954
956
958
962
965
972
984
987
994
996
1014
1020
1029
1034
1042
1054
1059
1090
1091
1098
1101
1108
1110
1113
1118
1119
1133
1189
1190
1218
1240
1252
1263
1267
1273
1280
1283
1284
1286
1287
1290
1291
1297
1300
1301
1302
1303
1306
1308
1309
1317
1318
1319
1320
1322
1327
1328
1329
1333
1334
1338
1339
1341
1343
1346
1355
1360
1384
1386
1392
1396
1399
1422
1435
1439
1442
1455
1456
1457
1461
1462
1470
1473
1489
1496
1497
1510
1529
1531
1532
1537
1546
1547
1554
1557
1561
1598
1603
1629
1636
1646
1647
1648
1653
1655
1657
1675
1677
1681
1686
1688
1732
1737
1744
1754
1763
1764
1769
1771
1783
1788
1819
1822
1826
1827
1833
1838
1845
1854
1858
1861
1866
1878
1895
1896
1897
1902
1912
1915
1916
1957
1990
1996
1999
2000
2038
2039
2062
2069
2070
2071
2073
2075
2077
2078
2086
2087
2088
2089
2113
2116
2134
2142
2145
2159
2181
2188
2200
2205
2206
2208
2219
2221
2232
2237
2240
2251
2255
2272
2277
2279
2282
2283
2286
2288
2291
2296
2308
2309
2310
2332
2337
2340
2350
2354
2355
2375
2378
2382
2387
2389
2424
2429
2442
2446
2451
2484
2489
2505
2517
2524
2527
2530
2535
2546
2550
2560
2580
2584
2585
2586
2591
2595
2599
2600
2608
2620
2624
2630
2651
2652
2653
2655
2667
2675
2693
2704
2710
2745
2779
2785
2790
2792
2793
2797
2820
2822
2824
2826
2828
2840
2882
2887
2890
2892
2895
2896
2898
2900
2901
2910
2911
2913
2926
2928
2930
2969
2974
2988
3005
3014
3016
3018
3057
3059
3060
3061
3062
3073
3099
3104
3111
3113
3116
3132
3136
3154
3156
3172
3211
3219
3223
3225
3226
3245
3247
3261
3263
3266
3269
3271
3280
3288
3303
3305
3314
3319
3342
3344
3346
3347
3348
3349
3350
3363
3371
3395
3403
3411
3412
3423
3431
3454
3462
3470
3495
3496
3497
3502
3506
3508
3513
3519
3567
3596
3608
3665
3676
3688
3696
3703
3704
3705
3708
3709
3711
3712
3714
3715
3740
3741
3747
3772
3773
3779
3780
3791
3818
3827
3832
3851
3869
3870
3871
3874
3876
3888
3928
3946
3959
3961
3983
3986
3987
3990
4000
4004
4019
4027
4046
4056
4087
4089
4096
4111
4116
4120
4132
4134
4135
4136
4137
4138
4140
4141
4146
4153
4170
4191
4192
4238
4240
4251
4263
4265
4266
4267
4268
4309
4351
4389
4462
4469
4474
4487
4604
4605
4658
4688
4706
4716
4739
4757
4760
4762
4763
4776
4781
4795
4820
4824
4856
4860
4899
4916
4950
4964
4969
4999
5060
5094
5108
5116
5185
5237
5247
5253
5270
5299
5344
5351
5354
5364
5366
5389
5419
5464
5540
5549
5571
5583
5605
5607
5613
5633
5878

**Comment by mokus80** [comment]
Hier zunächst eine Übersicht über die SpitBases mit zugehörigen Orgas, Divisions und Angeboten: https://gist.github.com/mokus80/cc5b62ae0d35621f4dcfeb872fbd4c9a
