### ISSUE TITLE
Export zu SB

### ISSUE THREAD

**Issue by BlahBlub90** [clarat-org/clarat#1276]
Liebe Nicole,

kannst du für mich noch folgende 3 Exports ziehen? 

1) SB ID - Section ID 
2) SB ID - unique P-Kats der dazugehörigen Angebote. 
3) SB ID - unique Tags der dazugehörigen Angebote 

Für die 2) & 3) will ich am Ende jeweils eine Tabelle bauen, wo ich in Spalte 1 die sB ID habe und in Spalte 2 alle P-Kats bzw. alle Tags, hintereinander gereiht habe. Beispiele: Spalte 1 = 5827, Spalte 2 = Schule, Sorgen im Alltag, Geldsorgen, Freizeit, Hebammen. (Und wenn Freizeit an mehreren Angeboten hängt, dann brauche ich das nur 1x ausgegeben.) 

Besten Dank.
Tian

**Comment by mokus80** [comment]
1. https://gist.github.com/mokus80/5d90b4fbf2e8404aa022378987effdb7
SB-ID, Section-Offer, Section-Orgas, Section-Divisions

2. https://gist.github.com/mokus80/281ddc1b7cbd93010dd7a73ad47e9ef9

3. https://gist.github.com/mokus80/8b6ccde309ae51ccffe25538499a304f

**Comment by BlahBlub90** [comment]
Liebe Nicole, 
kannst du bei 2 & 3 die Ergebnisse pro SB auch alphabetisch sortieren lassen? Danke!

Tian

**Comment by BlahBlub90** [comment]
Danke. Ich brauche erstmal nichts mehr. Das mit der Alphabetisierung löse ich über Excel. 

Merci.
