### ISSUE TITLE
Angbeote ohne SB 

### ISSUE THREAD

**Issue by BlahBlub90** [clarat-org/clarat#1277]
Liebes IT Team,

uns sind 2 Angebote (2503, 2367) aufgefallen, die keine SB haben. Beide haben noch die Version 3 und sind auf internal_feedback gesetzt. 

Dann gibt es noch weitere 4 Angebote, welche keine SB haben. (3000, 3061, 2947, 3001) Sie wurden vor langer Zeit von Astrid angelegt und auch completed.  Aber ich erkenne auf den ersten Blick nicht, zu welcher Orga diese Angebote gehören sollen. 

Da man so nicht mehr herausfinden kann, für welche Orga diese Angebote angelegt wurden, könnt ihr sie einfach löschen? 

Danke

**Comment by Twiek** [comment]
@BlahBlub90: Wenn es nur darum geht die Angebote zu löschen würde ich Dich bitten es selber zu machen. Das geht im Backend vermutlich schneller als über die Konsole.

**Comment by BlahBlub90** [comment]
Jo. Machen wir.
