### ISSUE TITLE
Liste der "kranken" Orgas - 

### ISSUE THREAD

**Issue by BlahBlub90** [clarat-org/clarat#1278]
Liebes IT Team,

wie ihr wisst, versuchen wir gerade durch eine gezielte Aktualisierung die Monster Orgas, die durch Split entstanden sind, zu "heilen". Damit ich währenddessen und hinterher tracken kann, welchen Fortschritt wir da machen, wäre es super, wenn ihr mir helfen könnt, folgende Informationen zu ziehen. 

https://docs.google.com/spreadsheets/d/1Xdso3YdKFyJ8heG9yUpJ8j4hLDnKIWAuFuLnF0GA5gU/edit#gid=0

Danke!
Tian

**Comment by mokus80** [comment]
https://gist.github.com/mokus80/e06de1a5d775afda4207c1ee71061291

Die Status der Angebote in der Reihenfolge:

[:initialized, :completed, :approval_process, :approved, :checkup_process, :disapproved, :edit, :paused, :expired, :internal_feedback, :external_feedback, :organization_deactivated, :under_construction, :seasonal_pending, :website_unreachable]
