### ISSUE TITLE
Slug mit kryptischer Zahlenfolge

### ISSUE THREAD

**Issue by JensBaumgarten** [clarat-org/clarat#128]
Bei diesem Angebot: http://clarat.herokuapp.com/admin/offer/1197/edit

wurde folgender Slug generiert: 

sozialberatung-fuer-frauen-und-maedchen-f79c2359-1550-4557-8d19-e57cdf1df7e2

Fehler?

Researcher: Suse

**Comment by Twiek** [comment]
Why is that? Dachte im Zweifelsfall wird die PLZ der Location drangehängt?

**Comment by KonstantinKo** [comment]
Richtig, PLZ wird drangehängt aber wenn die auch gleich sind, wird automatisch eine UUID drangehängt damit man sich sicher sein kann, dass der string unique ist. Als ich das eingebaut hab, hatten wir aber gesagt, dass das nicht passieren sollte. (der selbe name in der selben PLZ)

Wenn das jetzt doch passiert, müssen wir uns überlegen, was dann der einzigartige string sein soll den wir noch anhängen

**Comment by Twiek** [comment]
Gleiche PLZ, aber andere Straße. Könnte man hier eventuell eine fortlaufende Nummer nehmen (also mit '_1' anfangen)?

**Comment by KonstantinKo** [comment]
So war das früher mal, aber die Funktion wurde aus dem gem rausgenommen für mehr Stabilität. Hat was mit race conditions zu tun. (Was, wenn zwei Leute gleichzeitig sowas anlegen? Wer ist dann 1 und wer 2?)

**Comment by Twiek** [comment]
Und einfach die ID des Angebots?

**Comment by KonstantinKo** [comment]
Der slug wird generiert, bevor das Angebot gespeichert wird. Es ist also noch keine Datenbank ID vorhanden. Könnte man höchstens in einem zweiten Schritt machen und den researchern sagen, dass sie eine eventuell aufgetretene UUID gegen unsere ID ersetzen sollen.
