### ISSUE TITLE
Designfehler in der mobilen Ansicht

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1281]
Ok streng genommen kein Fehler, aber schön ist anders...

![screenshot_2017-08-16-16-21-40](https://user-images.githubusercontent.com/432388/29510991-fbf44656-865d-11e7-9c9b-fcdbfcf0f496.png)

Sollten beide gleichgroß sein.

**Comment by mokus80** [comment]
@Twiek : Kann geschlossen werden, oder?
