### ISSUE TITLE
Leere Übersetzungen anzeigen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1282]
Wenn bei den Übersetzungen im neuen Backend Felder leer sind (vorübergehend gelöscht) sollten sie trotzdem angezeigt werden (halt als leer).

![img_0262](https://user-images.githubusercontent.com/432388/29514690-b740d32e-8669-11e7-94c5-6bc19c4b95f5.JPG)

**Comment by NilsVollmer** [comment]
Ist eher ein Bug: eigentlich sollte es schon so funktionieren, dass er die Übersetzung anzeigt wenn es eine deutsche Source gibt.

**Comment by NilsVollmer** [comment]
Als Hotfix direkt auf master umgesetzt und aufgespielt.
