### ISSUE TITLE
Preview für Orgas

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1284]
Organisationen im neuen Backend sollten eine bewusste (nicht versehentliche ;-) Previewfunktion bekommen.

**Comment by NilsVollmer** [comment]
Erweiterung: da diese Funktion am innerhalb der edit-View am meisten Sinn macht (ich editiere etwas und möchte mir dann die Preview im Frontend anschauen), sollten wir das wie folgt umsetzen: jedes Modell zeigt in jeder Ansicht eine Tab-Reiter-View, in der man zw. allen vorgesehenen Aktionen (z.B. Show, New, Edit, Export, Preview) switchen kann. Die gerade selektierte Option wird selektiert angezeigt. Die meisten dieser Aktionen springen zu der entsprechenden Route aber bei der Preview-Funktion macht es Sinn, den Link in einem neuen Tab zu öffnen.

Diese View brauchen wir sowieso (Ich möchte z.B. zw. show und edit hin- und herspringen ohne die URL ändern zu müssen oder zurück über das Dashboard gehen zu müssen) und sie deckt dann mit minimalen Änderungen auch diesen Fall mit ab.

**Comment by NilsVollmer** [comment]
Soweit umgesetzt, einzige Anpassung: Abwärtskompatibilität war nicht möglich (zumindest nicht wenn der show-reload-bug raus soll) und deshalb wurde die Funktion aus dem alten Backend entfernt. Offer-Preview läuft noch über das alte Backend.
