### ISSUE TITLE
Objekte (erstmal Organisationen) dem Systemuser zuweisen können

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1285]
Wenn ich z.B. eine kleine Änderung an einer Organisation vornehmen möchte (z.B. Typo) will ich mir diese zuweisen können und danach direkt wieder dem Systemuser zuweisen können. Daher braucht es einen 'Zuweisung schließen' Button.

**Comment by NilsVollmer** [comment]
Duplicate of #1274
