### ISSUE TITLE
Usability in der mobilen Suche

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#129]
Die vorgeschlagenen Ergebnisse in der Autovervollständigung machen es schwer den Ort anzupassen.

![bildschirmfoto 2015-02-02 um 14 29 43](https://cloud.githubusercontent.com/assets/432388/6001264/0bf30f8c-aae8-11e4-8a24-c860311aca75.png)

**Comment by Twiek** [comment]
Bitte Vorschlag erarbeiten (für Startseite und Suchergebnisseite). Denke es muss darauf hinauslaufen, dass die vorgeschlagenen Ergebnisse unter dem Feld der Ortssuche angezeigt werden (Vgl. Yelp).

**Comment by marcus-herrmann** [comment]
In Bezug auf die Startseite allein: Bevor ich die typeaheads zu Finde und Wo unterhalb der Input-Gruppe platziere, würde ich gerne folgende Variante vorschlagen: f725b61a566b51f391f66390ccf1c3810ab588e3 - hier wird das Location-Input nicht mehr von der Offer-Vorschlagsliste überdeckt, sondern drückt es nach unten. Wenn das grundsätzlich gefallen sollte, würde ich auch das zweite Typeahead zur Location entsprechend umbauen wollen, damit es dann den Such-Button nach unten drückt.

Für die Nicht-Startseiten (es ist ja nicht nur die Suchergebnisseite, die diesen Header hat) stimme ich dir zu, da erscheint der Yelp-Ansatz sinnvoll.

**Comment by Twiek** [comment]
Good call. So machen wir es.

**Comment by marcus-herrmann** [comment]
> Wenn das grundsätzlich gefallen sollte, würde ich auch das zweite Typeahead zur Location entsprechend umbauen wollen, damit es dann den Such-Button nach unten drückt.

Situation ist hier gerade, wie berichtet, dass der Container mit den Suchvorschlägen für Orte nicht direkt unter dem Suchfeld ("Wo") ist und damit eine Höhe erzeugen kann, die den Button Suchen entsprechend nach unten verschiebt, bzw. den ganzen gelben Container ("Distributor"-Modul) verlängert (wie bei der Vorschlagsliste zu "Finde).

Vielmehr ist dieser Container an einer ganz anderen Stelle im DOM (vor dem schließenden Body-Tag), wird dann absolut positioniert und [Google hat auch kein Interesse, das wieder zu ändern](https://groups.google.com/forum/#!topic/google-maps-js-api-v3/ibIknTkPTho). Werde hier wohl etwas länger dran sein.

**Comment by Twiek** [comment]
Eventuell erstmal nicht zu viel Zeit investieren. Im Gegensatz zur 'Finde-Box' kann man ja einen Ort aus den Suchvorschlägen anklicken, ohne dass man auf einer neuen Seite landet, d.h. sobald man einen Ort ausgewählt hat ist der Suchbutton ja wieder zu sehen.

**Comment by marcus-herrmann** [comment]
Roger. Breche erstmal ab. google.maps.places.Autocomplete ist logikseitig gut dokumentiert (Suchergebnisse selbst), aber gestaltungsseitig mal gar nicht und das Standardstyling sehr biased.

**Comment by marcus-herrmann** [comment]
Feature steht nun folgendermaßen bereit:

* auf der Startseite
    * schiebt das Typeahead zum Finde-Input den Location-Input nach unten
    * vergrößert vorerst das Typeahead zur Location den gelben Container nicht (Grund siehe oben)
* auf nicht-Startseiten
   * führt ein Klick in den Suchinput dazu, dass sich der Location-Input zeigt, und sich beide Inputs auf die maximal vertretbare Breite aufspannen

**Comment by Twiek** [comment]
Bei mir verschwindet das 'Wo' aus dem Location-Input auf der Startseite sobald es im Finde-Input mit dem Typeahead losgeht.

![bildschirmfoto 2015-02-27 um 16 21 28](https://cloud.githubusercontent.com/assets/432388/6415104/ff163ae6-be9c-11e4-9d7d-2ed5ff6f8297.png)

**Comment by marcus-herrmann** [comment]
Fix hierzu in Branch/PR ergänzt.
