### ISSUE TITLE
Usability Verbessern Suchergebnisseite Mobile

### ISSUE THREAD

**Issue by MichiBecker** [clarat-org/clarat#1291]
Auf der Suchergebnisseite vermittelt der Drop Down Pfeil, über den die Adresse eingeblendet werden kann, dass das die einzige Klickoption ist. Dadurch kann es passieren, dass Nutzer nicht raffen, dass man auf die Headline klicken kann (kein hover Effekt bei Mobile) und dann erst ALLE Infos zum Angebot bekommt.

hier mein Vorschlag (geht eventuell noch etwas schöner):
- Drop-Down Pfeil weg, Adressinfos gibt es erst auf der Angebotsseite
- Pfeil nach rechts oben in den Headline Balken, damit man erkennt, dass es dort noch weiter geht

![bildschirmfoto 2017-08-22 um 13 40 56](https://user-images.githubusercontent.com/20815293/29564087-9e8c7d56-8740-11e7-9107-6b9d6d3dd570.png)

**Comment by marcus-herrmann** [comment]
Würde das hier vorschlagen:

![localhost-3000-family-angebote-utf8 e2 9c 93 search_form 5bquery 5d search_form 5bsearch_location 5d alexanderplatz 2c berlin 2c deutschland search_form 5bgenerated_geolocation 5d 52 520007 2c13 404954 search_form 5bcategory 5d searc 1](https://user-images.githubusercontent.com/505181/29862402-bfff82b2-8d6c-11e7-937f-38e0926b5dbc.png)

Hier wäre - bei Gefallen - der Branch dazu: https://github.com/clarat-org/clarat/tree/feature/1291-improve-search-result-item-ux

**Comment by MichiBecker** [comment]
@marcus-herrmann I like. Was meint @Twiek dazu? Finde es ist eine UX-light Lösung par Excellence 👯‍♂️

**Comment by marcus-herrmann** [comment]
Ist im Rahmen von #1309 umgesetzt worden, kann vermutlich zu.
