### ISSUE TITLE
Angebote ins Backend 2.0

### ISSUE THREAD

**Issue by KonstantinKo** [clarat-org/clarat#1295]
Vorerst funktionsgleich zum alten Backend

**Comment by KonstantinKo** [comment]
@Twiek 
Überlegung: Wir würden gern am expiring Prozess etwas verändern.
Idee 1: expires_at wird immer beim Speichern auf (aktueller Tag + 1 Jahr) verändert => verhindert, dass lange herumliegende Angebote fast schon expired sind wenn sie approved werden
Idee 2: Wir schmeißen expiration einfach mal raus. Hat doch gerade eh keine praktische Auswirkung mehr. expired state tut effektiv nichts, Angebote sind trotzdem im Frontend. Wenn wir einfach mal herausfinden wollen, welche Angebote seit > einem Jahr nicht mehr bearbeitet werden, bekommen wir das auch über scopes hin.

@NilsVollmer Ergänzungen?

**Comment by Twiek** [comment]
Unter Vorbehalt sind die folgenden Änderungen zum alten Backend vorzunehmen:

Nicht im neuen Backend anzeigen, aber in derDatenbank behalten:
- All inclusive
- Old next steps

Wieder anzeigen":
- Target Audience Filter

Umzug zur Split-Base:
- Code word
- Solution Category

Komplett raus (auch aus der Datenbank):
- Expired_at

Bestätige noch mal, wenn das so final abgesegnet ist, daher zumindest noch nicht auf Production deployen.

**Comment by KonstantinKo** [comment]
Deploy TODO:
expires-at zu ends-at übertragen, wo ein starts-at vorhanden ist. Ansonsten auf nil setzen.
