### ISSUE TITLE
Required (Ortssuche) wird durch Schlagwortfilter nicht ausgelöst

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#130]
Wenn ich auf der Startseite auf z.B. 'Gesundheit' klicke komme ich ohne einen Ort angegeben zu haben auf eine Seite mit Suchergebnissen. Klicke ich dort auf ein weiteres Tag erscheint der freundliche Hinweis 'Leider konnten wir den von dir eingegeben Standort nicht finden'.

Sehe hier u.a. die folgenden Möglichkeiten damit umzugehen:

1. Wenn man auf der Startseite direkt auf eine Kategorie/Tag klickt wird man genötigt einen Ort anzugeben (gleicher Hinweis wie wenn man auf die Lupe klickt).

2. Wie 1. nur der Hinweis erscheint in einem Popup (noch expliziter und schlechter zu übersehen.

3. Man kommt zwar auf die Suchergebnissseite wird dort aber darauf hingewiesen doch bitte einen Ort anzugeben (z.B. durch ein Leiste über dem Header).

4. Wenn manuell nichts ausgefüllt wird, wird automatisch Berlin eingetragen, der User aber darüber informiert (z.B. analog zu 3.).

Dazu eine Meinung oder weitere Vorschläge?

**Comment by marcus-herrmann** [comment]
Ich tendiere für 4., bevor dann Berlin eingetragen würde, wird ja ohnehin über die Geolocation API versucht werden, der Standort zu ermitteln, korrekt?

**Comment by Twiek** [comment]
Agree. Bitte umsetzen.

**Comment by marcus-herrmann** [comment]
Könnte folgendes machen, ist aber eventuell nicht rein frontendseitig zu lösen: Klick-Event auf Startseite abfangen, checken, ob Location befüllt, ggf. befüllen, absenden. Für dieses Szenario bräuchte ich aber vom Backend aus noch eine Flash-Message dann auf der Result Page (etwa: "Du hattest keinen Ort angegeben, deswegen (ver)suchen wir's in Berlin")

**Comment by Twiek** [comment]
@KonstantinKo: Kannst Du hier unterstützen?

**Comment by Twiek** [comment]
Die Nachricht mit der Klasse '.Flash-message--alert' statt '.Flash-message--notice' versehen (oranger Hintergrund).

Außerdem wird dieses Feature bei mir immer aktiviert, d.h. auch wenn ich auf der Startseite etwas eingebe (z.B. Dortmund) erscheint die Nachricht und es wird nur in Berlin gesucht. Zusätzliche sollte für den Fall das Berlin eingesetzt wird dies auch auf der Suchergebnisseite im entsprechenden Suchfeld stehen.

**Comment by KonstantinKo** [comment]
Ist behoben, am besten mal mit mir zusammen ansehen.

Zu "Zusätzliche sollte für den Fall das Berlin eingesetzt wird dies auch auf der Suchergebnisseite im entsprechenden Suchfeld stehen.": Man beachte, dass 'Mein Standort' das trotzdem noch überschreibt, weil man ja Erlaubnis gegeben hat, dass der Eigene Standort automatisch zur Suche verwendet werden darf
