### ISSUE TITLE
Divionssuche innerhalb von SplitBases im alten Backend funktioniert (fast) nicht.

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1300]
Wenn ich im alten Backend einer Splitbase versuche eine Division hinzuzufügen kann ich diese nur anhand der ID suchen, nicht anhand des Namens (siehe Screenshot).

![bildschirmfoto 2017-08-29 um 10 25 14](https://user-images.githubusercontent.com/432388/29811640-87bcb7a8-8ca4-11e7-8ca5-54ed28979cda.png)

**Comment by NilsVollmer** [comment]
Als Hotfix direkt auf master umgesetzt & deployed.
