### ISSUE TITLE
Startseiten Redesign

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1309]
Details siehe Google-Doc 'Briefing neue Startseiten'.

Platzhaltertexte in den Textboxen ca. 200 Zeichen lang.

**Comment by marcus-herrmann** [comment]
Erste Skizze (wird nach und nach verbessert): https://sketch.cloud/s/nRxQp/all/page-1/desktop-hd

**Comment by marcus-herrmann** [comment]
Auswirkungen/Einzeltodos, die sich aus der obigen Skizze ergeben

[ ] Abrundungen raus
[ ] Header/"Bannerzeile" seitenweit ändern
[ ] Suchfeld seitenweit auf die volle Containerbreite ziehen
[ ] Farbe Beige verbleibt wahrscheinlich exklusiv in Angebots- und Orga-Kontext auf Offer Index und Offer show
[ ] Mit Headeranpassung: Footeranpassung
[ ] **mobile, resposive, fluide Layoutlösungen für diesen Screen nötig**
[ ] Umbau des Suchfeldes (bräuchte dafür Support aus dem Backend-Team!)
[ ] Falls Vimeo-Embed: Programmatisches Starten des Videos nach "weichem Sprung" nach unten

**Comment by MichiBecker** [comment]
@marcus-herrmann ich hab keine permission für die Sketch Cloud. Muss ich mir da nen Login holen?

**Comment by NilsVollmer** [comment]
PR im Backend mit den benötigten Änderungen (residency_status an Algolia schicken) ist fertig. 

TODO nach em Deploy:
```console
offer_ids = TargetAudienceFiltersOffer.where.not(residency_status: nil).pluck(:offer_id)
Offer.where(id: offer_ids).order(:id).map do |o|
   o.index!
   puts 'Done with Offer#' + o.id.to_s
end
```

**Comment by marcus-herrmann** [comment]
@Twiek @NilsVollmer Mir ist noch eine kleine Unschönheit mobil aufgefallen (betrifft nicht-offer-index und nicht-startseiten). **Hotfix dazu liegt auf master bereit**

**Comment by NilsVollmer** [comment]
@Twiek Ich weiß jetzt nicht genau, was marcus da behoben hat aber es wird dann jetzt gleich deployed da es auf master ist ;)
