### ISSUE TITLE
Popup bei Klick auf Kartenmarkierung

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#131]
Wenn ich auf einen Marker der Karte klicke geht ein Popup auf mit weiteren Informationen zum entsprechenden Angebot (Name des Angebots -> gleichzeitig Link zum Angebot, Name der Organisation -> tendenziell fett und die Adresse). Sobald ich irgendwohin außerhalb des Popups klicke verschwindet es wieder.

![bildschirmfoto 2015-02-05 um 17 34 52](https://cloud.githubusercontent.com/assets/432388/6064351/ad3ad862-ad5d-11e4-9815-71f952b1eb79.png)

Herausforderung: Das Popup nach Klick auf den Marker immer sichtbar sein, d.h. wenn der Marker am oberen Bildschirmrand ist, dann muss das Popup entweder 'nach unten' aufgehen, oder die Karte muss sich so bewegen, dass der Marker nicht mehr am oberen Rand ist (weitere Vorschläge willkommen).

**Comment by marcus-herrmann** [comment]
Problem hier ist bei meiner lokalen Entwicklung, dass die Faker Seeds keine Geodaten haben, auf offers#index also keine Kartenausgabe mit Markern erzeugen- damit kann ich nicht direkt experimentieren. Kann mir aber solange die Google Maps API anschauen, auch gerade was die verlässliche Sichtbarkeit der Bubble angeht.

**Comment by Twiek** [comment]
@KonstantinKo : Hast Du hier einen Tipp?

**Comment by KonstantinKo** [comment]
Bei mir generieren die fakes auch welche mit geodaten (zufällig, manchmal ja manchmal nein). Führ doch das fake script noch 2-3 mal aus, und schau auch auf den hinteren Seiten der Suchergebnisse (da die Ergebnisse ohne Geodaten ja imer zuerst kommen)

**Comment by marcus-herrmann** [comment]
Alles klar, danke. Die Statistik war bis eben nicht auf meiner Seite, habe zuletzt keine Geodaten bekommen und vermutete, dass das so fest in den Faker Seeds war.

**Comment by Twiek** [comment]
Karte wir auch auf Staging mit echten Daten nicht angezeigt (weder in der Suchübersicht noch in der Angebotseinzelansicht).

**Comment by marcus-herrmann** [comment]
Alles jQuery-basierte ist auf dem aktuellen Staging-Stand nicht mehr verfügbar, darunter auch die Karte. Von meiner Seite aus gabs keine bewusste Änderung der JS-Struktur (innerhalb eines Modules ja, aber nicht im großen Ganzen).

**Comment by Twiek** [comment]
@KonstantinKo Kannst Du dann da noch mal reinschauen?

**Comment by Twiek** [comment]
@marcus-herrmann: Bei mir lokal klappt es. Bitte die Linkfarbe noch mal checken. Finde das blau mäßig passend (falls überhaupt Absicht).
![bildschirmfoto 2015-02-16 um 11 36 00](https://cloud.githubusercontent.com/assets/432388/6210436/1f459472-b5d0-11e4-9cdb-eb0577ab5ca0.png)

**Comment by KonstantinKo** [comment]
Funktioniert nach redeploy auch auf staging

**Comment by Twiek** [comment]
Und weiter jammern auf hohem Niveau...

Im Screenshot erscheint mit die 'Blase' unnötig weit. Wenn möglich früher abschließen lassen und eventuell schon früher zum Zeilenumbruch zwingen.

![bildschirmfoto 2015-02-16 um 11 50 25](https://cloud.githubusercontent.com/assets/432388/6210676/3d824c80-b5d2-11e4-91ee-7d3f830ab2d5.png)

**Comment by marcus-herrmann** [comment]
Siehe c0cccdb

**Comment by marcus-herrmann** [comment]
(Hatte keinen eigenen Branch, da Minifix, deswegen kein PR und gleich in Ready for Deploy)
