### ISSUE TITLE
Kategorien werden zu Tags

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1313]
Hierarchien etc. entfallen dabei ersatzlos. Ebenso die Icons.

Vorgehen:
1. Es werden automatisiert Tags mit den bisherigen Kategorien identische Tags angelegt.
2. Alle Angebote welche bisher eine Kategorie direkt zugewiesen bekommen habe, erhalten jetzt das entsprechende Tag (die Kategorien oberere Ebene die implizit auch vergeben wurden werden ignoriert).
3. Kategorien werden nicht mehr an Algolia geschickt.
3. Alle Kategorien werden gelöscht.
5. Gems entfernen

Weitere Details folgen.

**Comment by allthegoldt** [comment]
Category.all.each do |cat|
          unless Tag.where(name_de: cat.name_de).any?
            cat_att = cat.attributes.except('id', 'created_at', 'updated_at', 'icon', 'visible', 'sort_order', 'parent_id')
            t = Tag.create(cat_att)
            puts t
            t.offers = cat.offers
          end
        end

**Comment by allthegoldt** [comment]
"Alkohol" ist z.Z. der einzige Begriff, den es bei Kategorien und Tags gibt. Mann muss da dann manuell Tag.where(name_de: 'Alkohol').first.offers = Category.where(name_de: 'Alkohol').first.offers machen und entscheiden, ob die anderen Felder von Kategorien kopiert werden sollen oder nicht.

**Comment by allthegoldt** [comment]
Kategorien mit folgenden Namen gibt es mehr als einmal: ["Coming Out", "Essen", "Freizeit", "Obdachlosigkeit", "Existenzsorgen", "Erwachsenwerden", "Hilfen vom Staat", "Sozialhilfe", "Geldsorgen", "Familienrecht", "Hartz 4", "Wohnen", "Wohngeld", "Liebeskummer", "Behörden und Ämter", "persönliche Probleme", "Elterngeld", "Sexuelle Identität", "Aufenthaltsrecht", "Kindergeld", "Sorgen im Alltag", "Beziehungsprobleme"] Soll da anders vorgegangen werden (oder soll wahllos je eine dieser Kategorien zu Tags werden)?

**Comment by Twiek** [comment]
@allthegoldt Bei den Kategorien die es mehr als einmal gibt sollte das ausschließlich an der Welt liegen. Das Element fällt ja wie parent, sort_order... weg. Kannst Du mal checken ob die in den zu übertragenden Werten identisch sind (also parent... ignorieren) und noch mal eine Liste von denen erstellen, die sich unterscheiden?

**Comment by Twiek** [comment]
Bezüglich Alkohol 'einfach' den Tag Alkohol mit den Werten der Kategorie Alkohol (hat im Gegensatz zum Tag schon Keywords) überschreiben. Dann allen Angeboten die die Kategorie Alkohol haben und noch nicht den Tag Alkohol eben diesen Tag geben.

**Comment by NilsVollmer** [comment]
UPDATE: der Deploy-TODO ist durchgelaufen (Punkt 1. und 2. erledigt)!

**Comment by allthegoldt** [comment]
claradmin schickt als _tags jetzt die tags und keine Kategorien. Allerdings muss noch in base search angepasst werden (der category code). Müssen noch abwarten, bis Umzug zu Rails 5 funktioniert hatte... Erst dann kann Schritt 3. vollständig abgeschlossen und 4. angefangen werden.
