### ISSUE TITLE
'Testphase' Banderole 

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#132]
Bitte einen Entwurf für eine 'Testphase' Banderole. Wenn man drauf klickt geht ein Popup auf in dem etwas erklärender Text steht (Vgl. 'Nichts gefunden Box' bei den Suchergebnissen).

**Comment by marcus-herrmann** [comment]
In dieser Richtung?
![group](https://cloud.githubusercontent.com/assets/505181/6079311/f324a280-ae03-11e4-98a7-4805d6198088.png)

**Comment by Twiek** [comment]
Ja, bitte so umsetzen (+Popup mit Dummytext).

**Comment by marcus-herrmann** [comment]
PR gestellt: #164

**Comment by Twiek** [comment]
Bitte noch Popup ergänzen wenn man auf 'mehr erfahren' klickt. Wie im Screenshot nur ohne E-Mail und mit Lore Ipsum Text (ca. 600 Zeichen).

**Comment by marcus-herrmann** [comment]
Ich könnte an der Rails-Template-Logik vorbei ein Popup realisieren - bei einer "nativen" Lösung wie https://github.com/clarat-org/clarat/blob/develop/app/views/offers/show.html.slim#L39 bin ich auf backendseitige Unterstützung angewiesen.

**Comment by KonstantinKo** [comment]
Weiß nicht ganz, was du mit einer "nativen" Lösung meinst, aber da Basti wohl einfach nur ein simples Popup mit nem Text wollte, hab ich einfach mal ein solches modal eingebaut.

Basti, musst es jetzt nur noch mit Inhalt füllen.

**Comment by marcus-herrmann** [comment]
Das war mit "nativ" gemeint, insbesondere die Rails-Logik um "modal_for". Vielen Dank!

**Comment by Twiek** [comment]
Noch nen kleinen optischen Fix ergänzt (https://github.com/clarat-org/clarat/commit/1300f44de7beaee257962af9800549b98d2dd597).
