### ISSUE TITLE
Filter: bei enumerize Feldern nur die vorhandenen Optionen anbieten

### ISSUE THREAD

**Issue by NilsVollmer** [clarat-org/clarat#1320]
Einige Modelle haben enumerized Fields (z.B. mailings bei Offer oder legal-form bei Orga's) mit festen Optionen. Bei den Suchfiltern wird dem Nutzer aktuell ein Freitextfeld angeboten, in dem er die exakt korrekte Option eintippen muss. Stattdessen sollte es ein Dropdown mit den möglichen Optionen für dieses Feld sein.

**Comment by allthegoldt** [comment]
done in clarat-org/clarat#1319
Filter: Boolean filterbar & nutzerfreundlich

https://github.com/clarat-org/claradmin/pull/175
