### ISSUE TITLE
Neue E-Mail in Contact-People in Organisation im neuen Backend funktioniert nicht

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1322]
Wenn ich in /organizations/new auf contact-people hinzufügen klicke und dann dort auf E-Mail hinzufügen, dann passiert exakt gar nichts. Das sollte nicht sein.
![bildschirmfoto 2017-09-06 um 13 35 24](https://user-images.githubusercontent.com/432388/30109871-4576df8a-9308-11e7-82b6-e90aca561bee.png)

**Comment by NilsVollmer** [comment]
Direkt als Bugfix auf master umgesetzt & deployed.
