### ISSUE TITLE
Suche nach Webseiten verbessern

### ISSUE THREAD

**Issue by NilsVollmer** [clarat-org/clarat#1324]
Die Suche nach Webseiten in einem Create/Edit-Formular (z.B. Divisions) ist im Moment eher suboptimal: wenn man einen Link aus dem Browser kopiert, muss man das 'http(s)?://' entfernen, damit die Suche funktioniert. Ausserdem findet man 'https://www.google.de' nicht wenn man einfach nur 'google' eingibt (Grund: prefix search von pg_search).

Beides sollte im Idealfall funktionieren - evtl. müssen wir dafür etwas anderes als pg_search benutzen.

**Comment by Twiek** [comment]
Erstmal ca. 2 Stunden abchecken ob/wie das überhaupt gelöst werden könnte und dann noch mal schätzen.

**Comment by NilsVollmer** [comment]
Update: Lösung: anstatt pg_search können wir einen eigenen scope mit LIKE-Query für diese Modelle benutzen. Das funktioniert dann natürlich nur auf genau einem field (bei websites die url und bei email die address) dürfte dann aber von der usabilty her genau das sein, was wir haben wollen.

Man braucht also das 'http:' nicht mehr wegzunehmen und braucht auch nicht immer bei 'www.' der URL anzufangen.

**Comment by NilsVollmer** [comment]
Als Mini-Feature direkt auf develop umgesetzt
