### ISSUE TITLE
Gesamtzahl der aktuell gefundenen Daten über dem IndexTable anzeigen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1326]
Bei 'Diesem Team zugewiesene, offene Aufgaben: ' erwartet man eine Zahl, aber da ist keine...

![bildschirmfoto 2017-09-07 um 11 27 09](https://user-images.githubusercontent.com/432388/30156319-a55f6784-93bf-11e7-9e67-2915b7660131.png)

**Comment by NilsVollmer** [comment]
Erweitert: refactoring des RangeFilter codes in Index.

**Comment by NilsVollmer** [comment]
Update: ah wir haben gerade auch auf master einen infinite-loop reloading Bug, den ich im Zusammenhang mit diesem Issue gerade gefunden habe. Deshalb High Prio.

**Comment by NilsVollmer** [comment]
Update2: Bug & refactoring rausgezogen.
