### ISSUE TITLE
Neues Datenmodell 'theme'

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1327]
Name des Modells: 'theme'
Datenfelder:
name --> String
Beziehungen:
has_many organizations

Initial werden die folgenden erstellt (analog der aktuellen Hauptkategorien):
- 'Probleme in der Familie'
- 'Gesundheit und Krankheit'
- 'Lernen und Arbeiten'
- 'Sorgen im Alltag'
- 'Gewalt und Kriminalität'
- 'Notfall'
- 'Asyl und Recht'

Deploy ToDo:
Alle bestehenden Organisationen werden wenn möglich themes zugeordnet. Dabei werden alle den Organisationen zugeordneten Angebote durchgegangen und je nachdem in welchen Hauptkategoriebäumen den Angeboten Kategorien zugeordnet wurden, werden den Organisationen themes zugeordnet.

Nice to have: Im Backend heißen die themes 'Sujets'.

**Comment by allthegoldt** [comment]
Deploy todo: 

t = ['Probleme in der Familie',
'Gesundheit und Krankheit',
'Lernen und Arbeiten',
'Sorgen im Alltag',
'Gewalt und Kriminalität',
'Notfall',
'Asyl und Recht']

t.each do |to| Topic.create(name: to) end

Organization.all.each do |orga|
  o = orga.offers.map do |o|
     o.categories.map do |c|
       c.self_and_ancestors.where(parent_id:nil).pluck(:name_de)
     end
   end.flatten.uniq

  o.each do |cat|
    if Topic.where(name: cat).count > 0
      orga.topics << Topic.where(name: cat).first
    end
  end
end

**Comment by NilsVollmer** [comment]
Deploy TODO ist auf production durchgelaufen.
