### ISSUE TITLE
Refactor 'Standort nicht gefunden'

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#133]
Zum einen wird die h1 Überschrift in der mobilen Ansicht nicht richtig angezeigt, zum anderen sieht es insgesamt ziemlich meh aus. Bitte minimales Styling ergänzen.

![bildschirmfoto 2015-02-05 um 18 42 22](https://cloud.githubusercontent.com/assets/432388/6065605/f6c0d5c8-ad66-11e4-8c5d-b12df38c9737.png)

**Comment by marcus-herrmann** [comment]
Alles klar - `/app/views/offers/invalid_location.html.slim` fehlen die üblichen Wrapper-Klassen.

**Comment by marcus-herrmann** [comment]
Ergänzt mit 54d8907400f95b63f52f6642e2dc0d56cbcf8190
