### ISSUE TITLE
Filter fürs Frontend vorbereiten

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1337]
Im Frontend sollen die Filter demnächst in offer_index direkt angezeigt werden (kein weiterer Klick notwendig). In dem Rahmen wird es andere Filter als bisher geben (die dann dort zur Verfügung und an Algolia geschickt werden müssen).

Konkret Family (alles soll als dropdown dargestellt werden):
- für wen
- Geschlecht
- Sprache

Konkret Refugees (alles soll als dropdown dargestellt werden):
- für wen
- Geschlecht
- Sprache
- Aufenthaltsstatus (residency status)

**Comment by NilsVollmer** [comment]
#1309

**Comment by NilsVollmer** [comment]
Ist fertig und auf #1309 commited

**Comment by NilsVollmer** [comment]
PR im Backend mit den benötigten Änderungen (residency_status an Algolia schicken) ist fertig. 

TODO nach em Deploy:
```console
offer_ids = TargetAudienceFiltersOffer.where.not(residency_status: nil).pluck(:offer_id)
Offer.where(id: offer_ids).order(:id).map do |o|
   o.index!
   puts 'Done with Offer#' + o.id.to_s
end
```

**Comment by NilsVollmer** [comment]
Die technische Funktionen sind soweit fertig. Pending: waiting for Frontend #1309

**Comment by NilsVollmer** [comment]
Update: Deploy TODO ist durchgelaufen
