### ISSUE TITLE
Übersetzungsverlinkung vom alten ins neue Backend

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1339]
Wenn ich im alten Backend ein Angebot anschaue (z.B. /admin/offer/25430) und dort auf die Übersetzungslinks klicke (siehe Screenshot), dann komme ich z.B. hier hin /offer_translations/177098/edit und da sieht man dann exakt überhaupt nichts. Das Problem ist, dass im Link zwischen 'offer' und 'translations' ein Unterstrich eingefügt ist (_), es sollte aber ein 'normaler' Strich sein (-), denn der Link /offer-translations/177098/edit klappt.

![bildschirmfoto 2017-09-11 um 10 59 32](https://user-images.githubusercontent.com/432388/30266635-539228e6-96e0-11e7-8221-e126deea240f.png)

**Comment by NilsVollmer** [comment]
Als Fix direkt auf master umgesetzt & deployed.
