### ISSUE TITLE
Aus Tags werden Kategorien

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#134]
ToDos (no need to do this in the presented order):

- [x] Rename tags to categories
- [ ] Each category can have 0 or 1 parent_id but nor more than 10 categories must have the same parent_id
- [x] The attribute 'main' is no longer needed
- [ ] If category 'a' is added to an offer, its parent category is also added
- [ ] If category 'a' is removed from an offer, its parent category is also removed unless it still has other categories with the same parent category
- [x] Show category facet count in search results

**Comment by KonstantinKo** [comment]
@Twiek Soll es ein Limit geben, wie viele Kategorien ein Angebot haben kann?
Ich frage weil ich Punkt 2 falsch gelesen habe und jetzt eine custom validierung dafür geschrieben hab, obwohl es ja um was ganz anderes ging ... Also falls so ein limit gewünscht ist brauch ich das wenigstens nicht wegwerfen

**Comment by Twiek** [comment]
@KonstantinKo: Nein, vorerst ist kein hartes Limit vorgesehen, d.h. ein Angebot kann theoretisch sehr, sehr vielen Kategorien zugeordnet sein. Mag sich vielleicht aber noch ändern.
