### ISSUE TITLE
Validierung: Divisions einer Split-Base müssen alle die gleiche Welt haben

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1340]
Wenn ich eine Split Base mit einer Division verknüpfe muss geprüft werden, ob dieser Split-Base schon eine andere Division zugeordnet wurde welche eine andere section hat. Dies darf nicht der Fall sein. Alle Divisions die mit einer Split-Base verknüpft sind müssen die gleiche Welt haben.

**Comment by allthegoldt** [comment]
Deprecated and can be closed.
