### ISSUE TITLE
Weltenauswahl nur noch in der Division ermöglichen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1352]
Die Welt soll künftig nur noch in der Division ausgewählt werden können. Allen anderen Objekten in der Kette (Orgas, SplitBases, Offers) bekommen nur noch indirekt durch den Bezug zu ihrer/ihren Divisions eine Welt. Dabei dürfen die Objekte SplitBase und Offers auch indirekt immer nur einer Welt zugeordnet werden (Divisions einer Welt). Wenn ich wissen will in welcher Welt eine SplitBase oder ein Angebot angesiedelt ist, dann erfahre ich das nur über die Division. Für den Backenduser sollte das aber dennoch in allen Objekten selber angezeigt werden (zur Info, verändert werden kann da natürlich nichts).

Vorher: Prüfen ob bzw. wie viele Split-Bases dadurch zu Zwischenwelt-Split-Bases würden.

**Comment by allthegoldt** [comment]
ist umgesetzt worden

**Comment by allthegoldt** [comment]
in 1451
