### ISSUE TITLE
Statistiken im neuen Backend - Angebote werden nicht gezählt

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1359]

**Comment by NilsVollmer** [comment]
Input von mir: passiert(e) im alten Backend in rails_admin_change_state.rb und da ich weder in der create noch in der update operation der Angebote etwas entsprechendes gefunden habe, wurde es wohl vergessen.

**Comment by KonstantinKo** [comment]
Als hotfix direkt auf master & deployed
