### ISSUE TITLE
Kategorien in den Suchergebnissen anzeigen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#137]
Siehe auch Mail und #134 .

**Comment by marcus-herrmann** [comment]
Hier mal eine mögliche vertikale Variante („Kategorie-Baum“): 
![results_vertical](https://cloud.githubusercontent.com/assets/505181/6171491/4d5ec0f6-b2db-11e4-9a47-6bb844e1b5dd.png)

**Comment by marcus-herrmann** [comment]
...und horizontal. Beides Zwischenstände.
![results_horizontal](https://cloud.githubusercontent.com/assets/505181/6173344/756f1aee-b2e7-11e4-879f-505d4d702c39.png)

**Comment by Twiek** [comment]
Klare Präferenz für die vertikale Ausrichtung, wobei ich hier die nicht ausgewählten Oberkategorien (also hier z.B. 'Lernen', 'Sucht', 'Autismus') ausblenden und immer nur die ausgewählten Oberkategorien anzeigen würde. Außerdem nicht die Kategorie oberster Ebene (im Beispiel 'Gesundheit') nicht (so stark) hervorheben, wenn schon weitere Unterkategorien ausgewählt wurden. Fokus immer auf die unterste ausgewählte Ebene.

**Comment by marcus-herrmann** [comment]
Überarbeitet: Schriftgröße erhöht, Einrückung der ersten Ebene überdacht, dafür folgende Einrückungen verschärft, aktiven Filter hervorgehoben:

![results_with_categories_vertically](https://cloud.githubusercontent.com/assets/505181/6264068/435d37fa-b820-11e4-9497-c1fa22be953e.png)

**Comment by marcus-herrmann** [comment]
Plus Variation des "aktiven Pfades zum Filter":

![results_with_categories_vertically_variation](https://cloud.githubusercontent.com/assets/505181/6264141/012de68a-b821-11e4-84c1-981bca501e9d.png)

**Comment by marcus-herrmann** [comment]
Hier Szenario Freitextsuche. Szenario Kategoriewahl und Weiteres dann morgen
#### 
![suchszenario 1 freitext schritt 2]
(https://cloud.githubusercontent.com/assets/505181/6370061/a106de62-bcec-11e4-8c84-1829221c9a07.png)
#### 
![suchszenario 1 freitext schritt 6](https://cloud.githubusercontent.com/assets/505181/6370064/a6c0144a-bcec-11e4-9970-9601e6e9c0eb.png)
#### 
![suchszenario 1 freitext schritt 4](https://cloud.githubusercontent.com/assets/505181/6370069/acb1e086-bcec-11e4-8f18-d83d91823680.png)

**Comment by marcus-herrmann** [comment]
![schritt 1 - kategorieklick](https://cloud.githubusercontent.com/assets/505181/6389346/9c3428c4-bda3-11e4-869e-ff40c8a076b0.png)
####
![schritt 2 - kategorieklick](https://cloud.githubusercontent.com/assets/505181/6389349/a47e53ce-bda3-11e4-9503-81c2fb8ea424.png)

**Comment by Twiek** [comment]
TBD: Was genau wird als Ort in den Klammern angezeigt. Nur der Name der Stadt, oder genau was man eingegeben hat, also z.B. 'Französische Straße 47, 10117 Berlin, Deutschland'?

**Comment by marcus-herrmann** [comment]
Vorschlag: PLZ + Ort

**Comment by KonstantinKo** [comment]
Woher soll aber die PLZ kommen, wenn nur ein Ort eingegeben wurde? Oder irgendetwas ganz anderes?

**Comment by marcus-herrmann** [comment]
Dachte da tatsächlich an Geokoordinaten (fals denn vorhanden), aber du hast recht, wäre unverhältnismäßig.

**Comment by Twiek** [comment]
@marcus-herrmann: Kannst Du mal einen Entwurf für einen Edge case machen bei dem man sich in der 4 Unterkategorie befindet und die Wortkombination 'Nachhilfe für unbegleitete Migranten' sucht. Gehr mir darum, wo man in dem Fall bei der Beschreibung der Suche (Breadcrumbs etc.) was abschneidet bzw. eine neue Zeile einfügt.

**Comment by KonstantinKo** [comment]
Ok also ein bisschen display code ist jetzt vorhanden und es kann angefangen werden, zu stylen.
![screenshot-localhost 3000 2015-03-02 15-12-01](https://cloud.githubusercontent.com/assets/779660/6442282/eb3f14ee-c0ee-11e4-9c74-37e7b735a67b.png)

Ein paar Dinge:

1. In den Screenshots ist es uneinheitlich, ob nun die Anzahl der aktuell auf dieser Seite angezeigten Angebote mit aufgelistet werden soll oder nicht. Ich bin jetzt einfach mal davon ausgegangen, dass das nicht der Fall ist.
2. Was soll passieren, wenn auf das X geklickt wird?
3. Im letzten Screenshot sieht man eine mir neue Funktion, dass wohl die Suche sich selbst mit weniger spezifischen Parametern neu starten soll, wenn nichts gefunden wurde. Wenn das tatsächlich eine Anforderung ist, dann bitte als gesondertes Issue aufmachen.

**Comment by marcus-herrmann** [comment]
@Twiek : Ich finde, dass das Breadcrumbmodul die Möglichkeit haben muss, sich vertikal auszubreiten, und die Ergebnisliste nach unten zu verschieben.

![edge case - freitextsuche](https://cloud.githubusercontent.com/assets/505181/6502387/52723b6a-c323-11e4-83df-8481274c9074.png)

**Comment by marcus-herrmann** [comment]
@KonstantinKo 
zu 1.: Verstehe das so: Sobald eine Paginierung erzeugt wird, ist es `X von Y Angebote in Foo`, im Falle von so wenig Suchergebnissen, dass eine Paginierung nicht nötig, ist nur `Y Angebote in Foo`. Richtig verstanden, @Twiek ?

zu 2., aus Google Doc Suchszenarien:
> ...dahinter ein kleines ‘x’ anzeigen. Dies wird allerdings nur angezeigt, wenn ich neben der Freitextsuche auch mindestens 1 Kategorie ausgewählt habe. Wenn ich das klicke wird die Freitextsuchanfrage gelöscht und ich befinde mich wieder in der reinen Kategoriesuche.

zu 3.: @Twiek , Issue nötig, oder Reopen/Ergänzung #134 ?

**Comment by marcus-herrmann** [comment]
@KonstantinKo : 819c8ab798fdd6150cd550d11951b615303174c3 beinhaltet eine grundsätzliche Implementierung des Category Tree Menu Klickverhaltens. Ich bräuchte:

* Eine Ajax-Response der Suchergebnisse allein, nicht wie jetzt, der kompletten Suchergebnisseite
* Im Sinne einer besseren Wartbarkeit: eine grobe Indikation der Category-Nesting-Levels, wobei First Level Listitem und Not First Level Listitem schon reicht (wenn das drin ist, bitte Issue wieder mir zuweisen, dann folgt entsprechendes Refactoring von `module/_categories.scss` und `category_tree.coffee`.

**Comment by KonstantinKo** [comment]
@marcus-herrmann Ist erledigt.

**Comment by KonstantinKo** [comment]
Note2self:
X zum Suchwort-Reset muss noch eingebaut werden, Lösung für Zahlenanzeige neben Kategorien muss gefunden werden

Wenn Issue von dir aus fertig Marcus, bitte nochmal mir zuweisen.

**Comment by marcus-herrmann** [comment]
Die Überarbeitung des clickHandlers ist nun fertig, wir können uns ab jetzt auf die Breadcrumbs (Reset) und die Zahlenanzeige konzentrieren.

**Comment by KonstantinKo** [comment]
ist erledigt und auf develop merged (da viel mit der suche passiert werden sonst merge konflikte zu groß)

**Comment by Twiek** [comment]
@marcus-herrmann : Bitte den 'Alle Kategorien' Link stylen.
