### ISSUE TITLE
History ergänzen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1376]
Auch Angeboten und Organisationen im neuen Backend eine History spendieren. Relevante Spalten:
- Datum/Zeit
- Nutzer
- Action (also 'update', 'create')

Was genau geändert wurde sollte, falls für Menschen lesbar möglich ist gerne ergänzen.

**Comment by Twiek** [comment]
Schön wäre zu sehen, wenn ein User einen state-change initiiert hat (approved hat etc.).

**Comment by KonstantinKo** [comment]
Funktionalität hergestellt. Liegt für Styling bei Marcus
