### ISSUE TITLE
Nach Duplkation (?) werden vorausgefüllte Felder als leer betrachtet

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1379]
Wenn ich Angebot duplizieren wird auch die target-audience-filters-offers dupliziert. Wenn ich dann aber speichern will und, dann wird behauptet, das age_from Feld sei nicht ausgefüllt. Ist es aber (mit 0)!

![screenshot 2017-10-05 at 13 54 37](https://user-images.githubusercontent.com/432388/31230476-6fda26c2-a9e4-11e7-9956-263995d3ed54.png)

**Comment by KonstantinKo** [comment]
fixed & deployed

**Comment by NilsVollmer** [comment]
@Twiek Please check if working

**Comment by KonstantinKo** [comment]
(das eigentliche Problem war übrigens, dass die Zahl 0 als nicht vorhanden angesehen wurde)
