### ISSUE TITLE
Previewansicht wird nicht aktualisiert

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1380]
Bei diesem Angebot ist seit letzter Woche das erste Wort der Description 'Wird':
/offers/11361/edit

Im Preview-Modus (/family/preview/angebote/telefonberatung-fuer-eltern-von-opfern-von-cybermobbing) aber noch immer 'Wir'.

Worker kaputt?

**Comment by NilsVollmer** [comment]
Scheint ein generelleres Problem mit allen Translations zu sein, deshalb High Prio

**Comment by NilsVollmer** [comment]
Als hotfix direkt auf master umgesetzt & deployed.
