### ISSUE TITLE
Export funktioniert nicht (Contact People)

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1384]
Versuche einen Export der contact people vorzunehmen (Filter: ID, first_name, last_name + E-Mail ID und Adresse).

Im Browser gibt es einen Serverfehler und in den Logs folgendes:

![bildschirmfoto 2017-10-10 um 11 36 16](https://user-images.githubusercontent.com/432388/31379752-801b5dfc-adaf-11e7-8211-b0197090b3ad.png)

**Comment by NilsVollmer** [comment]
@KonstantinKo habe noch nichts auf develop oder master gefunden.

**Comment by NilsVollmer** [comment]
Ist jetzt deployed
