### ISSUE TITLE
SplitBases mit langen Titeln können im Angebot nicht bearbeitet werden

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1387]
Die entsprechenden Buttons/Links sind überhaupt nicht zu sehen:

![bildschirmfoto 2017-10-10 um 12 33 58](https://user-images.githubusercontent.com/432388/31382282-6b54ec82-adb7-11e7-8a92-7fa5d52be990.png)

vs.

![bildschirmfoto 2017-10-10 um 12 33 47](https://user-images.githubusercontent.com/432388/31382290-70c3e9f2-adb7-11e7-93c8-6e7cd7ff187d.png)

**Comment by NilsVollmer** [comment]
@Twiek Obacht/Update: da das Label der Splitbase jetzt u.a. das Label aller zugeordneten Divisions enthält (damit man nach dem Organamen suchen kann), tritt dieses ab sofort vermutlich häufiger auf und wir müssen ggf. die Prio hochsetzen und/oder uns nochmal genauer überlegen, welche Infos wir in den labels von Division & Splitbase wirklich brauchen (kürzen?).
