### ISSUE TITLE
Trait-Filter wird doppelt vergeben

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1391]
In dem Angebote 25838 wird der Trait-Filter 'anonym' doppelt vergeben, d.h. wenn man ihn nur einmal auswählt und dann speichert erscheint er im Backend wir im Frontend doppelt. Daraus ergeben sich 2 Wünsche:

- [ ] Validierung, dass ein Trait-Filter immer nur einmal mit einem Angebote verknüpft werden kann
- [ ] Bugfix, dass er nicht doppelt vergeben wird.

**Comment by NilsVollmer** [comment]
Eine Validierung würde ich dafür nicht bauen - wenn wir so anfangen müsste wir für alle verknüpften Modelle eine Validierung bauen, die sicherstellt, dass Objekte nicht doppelt miteinander verknüpft werden.

Nachdem der Bug behoben ist, ist es für den normalen Nutzer (Konsole ist natürlich etwas anderes) nicht mehr möglich eine doppelte Verknüpfung zwischen zwei Objekten herzustellen.

**Comment by KonstantinKo** [comment]
Aaaalso, auch vorher wenn man erst "anonym" rausgenommen, gespeichert, und es dann wieder reingepackt hat kam es nur einmal. Ich habe jetzt alle Dopplungen gelöscht. Kann den Rest des Fehlers gerade nicht reproduzieren. Am besten nochmal warten, ob der Fehler noch ienmal gemeldet wird.
