### ISSUE TITLE
Openings 'winterfest' machen (Zeitverschiebung ignorieren)

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1399]
Vermutlich Sommer & Winterzeit: wenn ich eine neue Opening anlege, hat sie im Backend den korrekten Anzeigenamen aber im Frontend ist diese aktuell um eine Stunde (nach hinten) verschoben bzw. in der Datenbank auch wenn man sich die Zeitwerte anschaut.

Betrifft vermutlich auch den Update eines vorhandenen Openings im neuen Backend (habe ich jetzt nicht ausprobiert).

**Comment by KonstantinKo** [comment]
bereits deployed

**Comment by KonstantinKo** [comment]
![](https://imgs.xkcd.com/comics/supervillain_plan_2x.png)

**Comment by KonstantinKo** [comment]
Es gab noch weitere Probleme mit den Öffnungszeiten und deren Zeitzonen-Gewusel. Zum Beispiel beim Filtern fiz dafür ist nun auch deployed
