### ISSUE TITLE
Lokale Online-/Telefonberatung

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#140]
Lokale Online-/Telefonberatung grenzen sich insofern von deutschlandweiten Angeboten ab, als dass sie nur ortsgebundene Hilfe vermitteln, also z.B. bei Fragen zu Frauenhäuser in Berlin helfen. Man kann zwar auch aus München anrufen, wird aber tendenziell enttäuscht. Ziel ist es die Angebote nur dann in den Suchergebnissen anzeigen zu lassen, wenn man sich im abgedeckten Gebiet befindet.

Lösungsansatz:
Angebot wird unter 'encounter' als  'local_independent' (Arbeitstitel) erfasst. In diesem Fall muss eine Adresse angegeben werden (die für den Nutzer aber nicht sichtbar ist). Anhand der Adresse wir die zugehörige Stadt ermittelt, von dieser der Mittelpunkt laut Google ermittelt (after_save?) und unserem Suchservice als relevante Adresse übermittelt. Sie in dem Rahmen auch #152.

**Comment by KonstantinKo** [comment]
Ich würde dieses Issue zur Bearbeitung von https://docs.google.com/a/clarat.org/document/d/1nGDGsZQvMh-xmGenJ-rPkUgS1Emk4ByUnKKv9Cb7vng/edit nehmen - zumindest für den Teil der lokalen Hotlines
