### ISSUE TITLE
Translationprobleme!?

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1405]
Das Angebot 3612 hat im Backend keine opening_specifications mehr. Im Frontend schon und zumindest in den Translations auch:

![bildschirmfoto 2017-10-16 um 12 34 06](https://user-images.githubusercontent.com/432388/31607847-59dbce9c-b26e-11e7-9e4c-1f684ecf5384.png)

Das sollte deutlich schneller gehen.

**Comment by NilsVollmer** [comment]
War ein Bug von einem Bugfix der letzten Woche: leere Strings haben keine neuen Übersetzungen generiert und das führt genau in dem Szenario, dass vorher eine Übersetzung da war, die überschrieben werden soll, zu dem fehlerhaften Verhalten.

Direkt auf master umgesetzt & deployed und die Übersetzungen der fehlerhaften Angebote auf production generiert.
