### ISSUE TITLE
'Ruf an' auffindbar machen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1408]
Damit man ihn einem Offer zuordnen kann.

**Comment by NilsVollmer** [comment]
Problem ist: da dieser spezielle NextStep so kurz ist und der Text 'ruf an' auch in etlichen anderen NextSteps enthalten ist, kann man ihn gerade nicht finden: diese pg_search-Suche nach 'ruf an' ergibt 112 Ergebnisse und der gesuchte NextStep ist leider nicht in den ersten 30 Ergebnissen, die geladen werden. Das wäre grundsätzlich noch kein Problem weil man einfach die Suche weiter einschränken müsste aber das geht bei diesem kurzen NextStep ja nicht - deshalb ist es gerade schlicht nicht möglichen, diesen NextStep zu finden.

Die Lösung: das pg_search_ranking so anzupassen, dass es kurze Texte für NextSteps höher ranked als Lange.

**Comment by NilsVollmer** [comment]
Als Hotfix direkt auf master umgesetzt & deployed.
