### ISSUE TITLE
Bei standortunabhängigen Angeboten keine Organamen in Ergebnisliste

### ISSUE THREAD

**Issue by JensBaumgarten** [clarat-org/clarat#141]
Bei standortunabhängigen Angeboten (z.B. Beratungshotlines) werden im Frontend in der Ergebnisliste die Namen der Organisation nicht angezeigt.

**Comment by Twiek** [comment]
Fixed with https://github.com/clarat-org/clarat/commit/eccc1c4dc50fbcec3e5729a8dcf95b29f9f4d25c
