### ISSUE TITLE
Preview geht nicht

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1411]
Angebote im Zustand initialized fehlt der Slug.

**Comment by NilsVollmer** [comment]
Update: es scheint nichts mit Create/Update zu tun zu haben sondern mit dem state: sobald man ein Angebot completed, bekommt es einen slug.

**Comment by NilsVollmer** [comment]
Deploy Todo:

```rails
Offer.where(slug:nil).map do |o|
   o.update_column :slug, o.send(:set_slug)
end
```

**Comment by NilsVollmer** [comment]
Als Bugfix direkt auf master umgesetzt & deployed.
