### ISSUE TITLE
Individuelle 301 Redirects für alte Blogartikel

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1420]
Konkret geht es um diese:

http://blog.clarat.org/2017/07/17/borderline/
http://blog.clarat.org/2017/06/14/arbeiten-in-deutschland/
http://blog.clarat.org/2017/06/23/kindergeld/
http://blog.clarat.org/2017/06/15/praktikum/
http://blog.clarat.org/2017/06/23/elterngeld/
http://blog.clarat.org/2017/06/23/kindergeld/
http://blog.clarat.org/2017/06/23/kindergeld/
http://blog.clarat.org/2017/06/15/cybermobbing/
http://blog.clarat.org/2017/06/14/arbeiten-in-deutschland/
http://blog.clarat.org/2017/07/25/onlinespiele-sucht/
http://blog.clarat.org/2017/06/14/arbeiten-in-deutschland/
http://blog.clarat.org/2017/07/25/onlinespiele-sucht/
http://blog.clarat.org/2017/06/14/arbeiten-in-deutschland/
http://blog.clarat.org/2017/06/15/cybermobbing/
http://blog.clarat.org/2017/07/17/borderline/

Auf die entsprechenden Seiten in clarat+ verlinken.

**Comment by marcus-herrmann** [comment]
Eingerichtet. Allerdings: obwohl Borderline so definiert ist, wie die anderen auch (siehe Auszug), funktioniert es nicht, und ich verstehe absolut nicht, warum:

```
Redirect 301 /2017/07/17/borderline/ https://plus.clarat.org/wissen/borderline/
Redirect 301 /2017/06/14/arbeiten-in-deutschland/ https://plus.clarat.org/wissen/arbeiten-in-deutschland/
Redirect 301 /2017/06/23/kindergeld/ https://plus.clarat.org/wissen/kindergeld/
Redirect 301 /2017/06/15/praktikum/ https://plus.clarat.org/wissen/praktikum/
Redirect 301 /2017/06/23/elterngeld/ https://plus.clarat.org/wissen/elterngeld/
...
```

**Comment by Twiek** [comment]
Also bei mir funktioniert da noch gar nichts. Z.B. leitet http://blog.clarat.org/2017/06/23/kindergeld/ noch immer auf https://plus.clarat.org/wissen/ weiter, nicht auf https://plus.clarat.org/wissen/kindergeld/.

**Comment by marcus-herrmann** [comment]
Letzten Donnerstag gingen alle URLs, ausser /borderline/. Nun geht keine einzige mehr - ich kontaktiere morgen bei Euch mal Wolfssohn

**Comment by marcus-herrmann** [comment]
Hatten wir ja geklärt. Kann, denke ich, zu
