### ISSUE TITLE
Codeword back to Angebot

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1421]
Perspektivisch soll die Splitbase abgeschafft werden, aber schon vorher das Codeword zurück ins Angebot gehen. Im Detail:

- [x] Codeword wieder als Datenbankfeld einrichten
- [x] Bei allen Angeboten deren Splitbase ein Codeword hat dieses übernehmen
- [x] Bei allen anderen der altes Codeword reaktivieren
- [x] Frontend wieder mit Codeword auf Angebotsebene verknüpfen
- (Codeword auf Splitbase-Ebene löschen) => können wir vor der Übertragung der Daten nicht machen und da die SplitBase in absehbarer Zeit ja eh verschwinden soll, machen wir es einfach dann und löschen die ganze Tabelle.

**Comment by NilsVollmer** [comment]
Deploy TODO: 
``` ruby
# overwrite offer-code_word with split_base-code_word (if present)
SplitBase.where.not(code_word: [nil, '']).find_each do |sb|
   sb.offers.update_all code_word: sb.code_word
end
```

**Comment by NilsVollmer** [comment]
Update: effektiv vom rails 5 upgrade im Frontend geblockt - ich kann aufgrund von version conflicts kein bundle update clarat_base durchführen um die eine entfernte delegate Zeile rauszukriegen :(

**Comment by NilsVollmer** [comment]
Deployed & deploy TODO ist durchgelaufen.
