### ISSUE TITLE
Orgas dem Systemuser zuweisen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1425]
Alle Orgas die als pending_reason foreign haben oder in deren comment das Wort 'ausland auftaucht UND die aktuell im Screening-Pool liegen (und chillen), sollen dem Systemuser zugewiesen werden.

**Comment by mokus80** [comment]
Per Konsolentask wurden alle Orgas mit pending_reason: 'foreign' dem System zugewiesen und der Orga-state auf 'internal_feedback' gesetzt.
