### ISSUE TITLE
Charitable Häkchen sieht nicht wie ein Häkchen aus

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1427]
Im Bearbeitungsmodus.

![bildschirmfoto 2017-10-23 um 16 05 32](https://user-images.githubusercontent.com/432388/31893514-0882a89c-b80c-11e7-945f-d98a870dba40.png)

**Comment by KonstantinKo** [comment]
Quick-Fix ist online: `-webkit-appearance: none` in `bootstrap-customizations/forms.scss` rausgenommen.

@marcus-herrmann Bitte nochmal beim checkbox styling rein schauen

**Comment by marcus-herrmann** [comment]
Präzisierung des Fix ist auf master
