### ISSUE TITLE
Crawler Fälle führen zu Zuweisungen, statt zu Asana Tasks

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1437]
Mit gleichem Kommentar eine Zuweisung im Screeningpool erstellen. Ab dann keine neuen Tasks ins Asana Projekt 'Crawler'.

**Comment by mokus80** [comment]
https://github.com/clarat-org/clarat_base/pull/138

https://github.com/clarat-org/claradmin/pull/201
