### ISSUE TITLE
SplitBase abschaffen!

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1443]
Was passiert mit den Datenfeldern/Verknüpfungen?

title --> fällt weg
clarat-addition --> fällt weg
comment --> fällt weg
Verknüpfung mit Division --> wird vom Angebot übernommen
solution-category --> wandert zum Angebot. Wenn die solution-category noch eine solution_category_id hat, dann ist diese maßgeblich für die Solution Category welche das Angebot bekommt. Wenn diese nicht vorhanden/nil ist, dann wird die der SplitBase genutzt, wenn es da auch nichts gibt, dann bleibt es leer.

**Comment by NilsVollmer** [comment]
Deploy TODO:

```ruby
Offer.find_each do |o|
  # grab solution_category_id from split_base if offer does not have one
  if !o.solution_category && o.split_base
    o.update_columns solution_category_id: o.split_base.solution_category_id
  end
  # establish new connection (Offer<->Divisions)
  if o.split_base_id
    o.divisions = Division.where(id: SplitBaseDivision.where(split_base_id: o.split_base_id).pluck(:division_id))
  end
end
```

**Comment by NilsVollmer** [comment]
@Twiek Bitte auf 'ready for deploy' schieben, sobald die Researcher ihr OK geben.

**Comment by NilsVollmer** [comment]
Ist deployed & die Daten sind übertragen.
