### ISSUE TITLE
Google-Translate Logo wird falsch angezeigt

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1445]
Und macht die gesamte Seite kaputt:

![bildschirmfoto 2017-11-07 um 15 11 01](https://user-images.githubusercontent.com/432388/32497786-f836151e-c3cd-11e7-83d9-087597a94fff.png)

Scheint nur Angebote zu betreffen die noch nicht übersetzt sind.

**Comment by NilsVollmer** [comment]
Hotfix ist deployed.

@marcus-herrmann Bitte kurz prüfen, ob der Fix so okay ist.

**Comment by marcus-herrmann** [comment]
Passt
