### ISSUE TITLE
Section raus aus den Offers

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1451]
Gibt es dann nur noch in den Divisions.

Einen Wechsel der Section der Division darf dann über das Backend nicht mehr möglich sein.

**Comment by mokus80** [comment]
@allthegoldt Deploy auf Staging führt nach dem Merge auf develop zu folgenden Fehler: 

 ERROR in ./app/bundles/GenericForm/forms/DivisionFormObject.js
remote:        Module build failed: SyntaxError: Unexpected token, expected { (84:2)
remote:        82 |   merge({}, variablenName)
remote:        83 |
remote:        > 84 |   static get submodelConfig() {
remote:        |   ^
remote:        85 |     return merge(
remote:        86 |       { section: { relationship: 'oneToOne' } },
remote:        87 |       DivisionUpdateFormObject.submodelConfig
remote:        @ ./app/bundles/GenericForm/lib/formObjectSelect.js 12:26-64

Bitte noch mal lokal testen und anpassen.

**Comment by allthegoldt** [comment]
behoben, da hat sich eine Zeile Testcode zufällig reingeschlichen
