### ISSUE TITLE
Kontrast der Filter verstärken

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1453]
Gelb auf gelbem Grund wird leicht übersehen...

![bildschirmfoto 2017-11-15 um 10 47 20](https://user-images.githubusercontent.com/432388/32829438-66688380-c9f2-11e7-9d48-6b303d7b50fa.png)

**Comment by marcus-herrmann** [comment]
Alternative siehe unten. Bei Gefallen hier: https://github.com/clarat-org/clarat/commit/d963d2a28d24477e6259f043accb15068f873607

<img width="1252" alt="bildschirmfoto 2017-11-16 um 09 33 40" src="https://user-images.githubusercontent.com/505181/32881663-3e44fc74-cab2-11e7-8020-99a5c3a5d666.png">
