### ISSUE TITLE
Farsi Suchfeld Bug

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1459]
Siehe Screenshot:

![bildschirmfoto 2017-11-16 um 13 40 18](https://user-images.githubusercontent.com/432388/32892698-6aae1ee2-cad7-11e7-9051-01d86f2dea46.png)

**Comment by marcus-herrmann** [comment]
Korrektur hier: https://github.com/clarat-org/clarat/tree/fix/1459-fixing-farsi
