### ISSUE TITLE
Facebook-Verification für clarat+

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1460]
Geht darum: https://allfacebook.de/features/webseite-verifizieren-link-vorschau-bearbeiten

Es gibt 2 Möglichkeiten.

1. DNS-TXT-Aufzeichnung
![bildschirmfoto 2017-11-16 um 14 10 09](https://user-images.githubusercontent.com/432388/32892874-ee34a5ec-cad7-11e7-8d40-a29b3cf9cde3.png)

Für copy/paste: facebook-domain-verification=rv8c09a8wvz7goq4qdw1uhggqxnp43

2. HTML-Datei Upload
![bildschirmfoto 2017-11-16 um 14 11 17](https://user-images.githubusercontent.com/432388/32892927-17ac2d32-cad8-11e7-9a30-ee7081f9fbe7.png)

Für copy/paste: http://plus.clarat.org/rv8c09a8wvz7goq4qdw1uhggqxnp43.html

HTML-File kommt per E-Mail

**Comment by marcus-herrmann** [comment]
Datei ist an gewünschter Stelle (Möglichkeit 2)
