### ISSUE TITLE
Webseite mit Sonderzeichen in der URL macht das Preview kaputt

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#1474]
ES geht um das Angebot mit der ID 27497 und der Webseite mit der ID: 10988 und dem Preview /family/preview/angebote/betreutes-wohnen-13189

Die Konsole sagt dazu Folgendes:

![bildschirmfoto 2017-11-27 um 12 10 00](https://user-images.githubusercontent.com/432388/33263941-f36e288e-d36b-11e7-9afc-885a5cd5f12e.png)

**Comment by NilsVollmer** [comment]
Für diesen Fehler habe ich gerade bei Google auch ein paar Webseiten gefunden und direkt die url überschrieben. Der Fix ist relativ einfach: für unseren eigenen Crawler haben wir im Backend im website-Modell schon eine Methode ascii_url - die sollten wir in clarat_base verlagern und dann im Frontend diese Methode aufrufen. Somit müssen die Researcher bei der Eingabe nicht darauf achten und im Frontend sollte der Fehler nicht mehr auftreten.
