### ISSUE TITLE
Benachrichtigungsfeld wird falsch und überhaupt angezeigt

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#148]
Bisher nur auf Staging in der Angebotseinzelansicht.

![bildschirmfoto 2015-02-13 um 10 36 03](https://cloud.githubusercontent.com/assets/432388/6185230/3dee9614-b36c-11e4-8266-20b75603aa47.png)

**Comment by marcus-herrmann** [comment]
Siehe Kommentar zu #131, jQuery fehlt aktuell global, deswegen auch Auswirkung bei Modal.

**Comment by marcus-herrmann** [comment]
Schaut bei mir auf Live wieder gut aus; Weiteres morgen persönlich.
![bildschirmfoto 2015-02-18 um 10 06 03](https://cloud.githubusercontent.com/assets/505181/6244595/c5e94ef0-b755-11e4-9690-cbbe5c9e836e.png)

**Comment by marcus-herrmann** [comment]
Lokal, Staging ebenfalls wieder in Ordnung.
