### ISSUE TITLE
Begrenzung der Suchergebnisse auf einen Umkreis von 50 KM

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#152]
Künftig sollen nur noch Angebote in den Suchergebnissen auftauchen die sich um Umkreis von 50 KM um die angegebene Adresse befinden oder unter 'encounter' als 'independent' markiert wurden.

**Comment by KonstantinKo** [comment]
Wartet auf Ausspezifizierung durch getrennte Suchindexe für independent und lokalgebundene Angebote

**Comment by Twiek** [comment]
Siehe Suchdokument.
