### ISSUE TITLE
Neues Datenfeld 'expiring date'

### ISSUE THREAD

**Issue by JensBaumgarten** [clarat-org/clarat#154]
Bei Angeboten, die nur eine kurze Laufzeit haben (z.B. Kältehilfe), sollte der Researcher die Möglichkeit haben, das Datum des Projektendes im Backend eintragen zu können. 

An diesem Datum soll eine automatische Mail an eine noch zu bestimmende Mailadresse gehen, sodass die 'fälligen' Angebote entfernt oder geupdated werden können.

Das eingetragene Datum wird im Frontend nicht abgebildet.

**Comment by KonstantinKo** [comment]
Dann bitte noch die "noch zu bestimmende Mailadresse" bestimmen.

Und was soll in der Email stehen?

**Comment by JensBaumgarten** [comment]
Unser QSA-Team ist mit der Sache beauftragt. Sobald die Lösung steht, leite ich sie weiter.
