### ISSUE TITLE
Gelbe Haare auf gelben Grund

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#159]
Sieht blöd aus... Zu sehen bei den Suchergebnissen oder in der Angebotseinzelansicht.

![bildschirmfoto 2015-02-18 um 10 09 58](https://cloud.githubusercontent.com/assets/432388/6244642/612430ec-b756-11e4-94d5-880ab3887424.png)

**Comment by marcus-herrmann** [comment]
Eventuell Nebenwirkung von Commit cdd4e53 - schaue mir das morgen an.

**Comment by Twiek** [comment]
Ja, das ist es. Insofern bitte refactorn.

**Comment by marcus-herrmann** [comment]
Gelöst mit f8d55633294e07df712594f1004d0b1f32181401

**Comment by marcus-herrmann** [comment]
Hatte keinen eigenen Branch, da Minifix, deswegen kein PR und gleich in Ready for Deploy)
