### ISSUE TITLE
Telefonnummern richtig formatieren

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#163]
Ergebnis soll wie folgt aussehen: 030 36 56 55 8, also Vorwahl inkl. 0 und danach in Zweierblöcken.

Kann man das aus den bisherigen Nummern automatisiert erstellen (Herausforderung u.a. erkennen welcher Teil die Vorwahl ist) oder müssen die Researcher diese noch einmal neu eingeben?

**Comment by KonstantinKo** [comment]
Neu eingeben würde ich ausschließen. Wir formatieren das code-seitig.

**Comment by KonstantinKo** [comment]
Funktioniert grundsätzlich. Probleme gibt es nur, sobal wir nicht-dreistellige Vorwahlen haben. Mir fällt nach dem aktuellen Schema keine Möglichkeit ein, code-seitig zu erkennen, wo die Vorwahl aufhört und der Rest beginnt. Ideen?

**Comment by Twiek** [comment]
Da nicht leicht zu erkennen ist was Vorwahl ist und was nicht bitte getrennt erfassen (inkl. getrennter Aufnahme durch die Researcher). Einmal 'area_code_1' und 'local_number_1' und dann 'area_code_2' und 'local_number_2'.

**Comment by Twiek** [comment]
Bitte mit #112 verknüpfen.

**Comment by KonstantinKo** [comment]
Falls etwas fehlt, bitte genauer das Problem beschreiben. PR ist gestellt.
