### ISSUE TITLE
Auch Kategoriesuche erfordert Ortseingabe

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#165]
Wenn ich auf der Startseite ohne einen Ort anzugeben auf eines der Kategorieicons klicke geht ein Popup auf in dem ich nach dem wo gefragt werde. Überschrift: 'Wo möchtest Du suchen?". Darunter dann das Suchfeld mit dem Lupebutton.

Wenn ich vorher schon in das Ortssuchfeld auf der Startseite (das 'Wo' Feld) einen Ort eingegeben habe und dann auf ein Icon klick wird diese Ortsangabe berücksichtigt und ist dan auch im Suchfeld auf der folgenden Suchergebnisseite zu sehen.

**Comment by KonstantinKo** [comment]
Verbunden mit #130.
(jegliche Linkklicks sind keine Formular-Absendungen und lösen keine Frontend-Validierungen aus)

**Comment by KonstantinKo** [comment]
Schau dir mal die aktuelle Lösung durch #130 an, vielleicht reicht das ja auch schon für's erste.
