### ISSUE TITLE
Keywords einführen.

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#175]

**Comment by Twiek** [comment]
Jedes Angebot kann 0 - X Keywords haben. Keywords haben einen Namen und Synonyme (analog dem ursprünglichen Tags). Beides wird in unserer internen Suche berücksichtigt, sonst aber nicht verwendet.

**Comment by Twiek** [comment]
Bitte checken: https://github.com/clarat-org/clarat/tree/175_keywords. 
Dabei auch folgende Fragen beachten:
- Wenn man im Adminbereich ein Angebot anlegt/bearbeitet und in dem Rahmen ein neues Keyword erstellen will, dann wir einem trotzdem die Möglichkeit angeboten eine offer_id einzugeben. Das scheint mir fehleranfällig. Kann man das vermeiden?
![bildschirmfoto 2015-03-04 um 18 35 17](https://cloud.githubusercontent.com/assets/432388/6489255/4596b01e-c29d-11e4-80ac-84f1b283e666.png)

- Passen die Änderungen was die Suche angeht (keyword_string, category_string)?

**Comment by KonstantinKo** [comment]
Kommentar siehe https://github.com/clarat-org/clarat/commit/7b0e8bffa9f9a2777d3b809eb27d58e9c3062305

**Comment by Twiek** [comment]
Ok, habe es jetzt noch mal überarbeitet, bitte erneut checken. Das im Screenshot (s.o.) beschriebene Problem konnte ich allerdings nicht beheben. Hatte die Dokumentation (https://github.com/sferik/rails_admin/wiki/Associations-basics) so verstanden, dass es mit inverse_of funktionieren sollte. Tut es aber nicht. Any ideas?

**Comment by KonstantinKo** [comment]
Das ist jetzt soweit ich das sehe kein Problem mehr, da es anders als im Screenshot nun eine Auswahlliste ist, bei der auch schon das richtige Angebot vorausgewählt ist. Selbst als ich es abgewählt habe, hat es noch das richtige getan, als ich dann gespeichert hab.
