### ISSUE TITLE
Filter integrieren

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#177]
Aktueller Stand welche Filter es geben soll (Namen werden noch mal überarbeitet):
![clarat_filter](https://cloud.githubusercontent.com/assets/432388/6416063/905c7db6-bea3-11e4-819b-4d39c86d1233.png)

- [x] Möglichkeit die entsprechenden Daten bei der Erstellung/Bearbeitung eines Angebotes einzugeben. In allen Bereichen ist eine Mehrfachauswahl möglich.
- [ ] Anzeige im Frontend im Rahmen einer 'Profisuche' die ergänzend zu sonstigen Suchlogik die Möglichkeit bietet die Ergebnisse entsprechend zu filtern.

**Comment by Twiek** [comment]
@KonstantinKo: Bitte den bisherigen Ansatz (keine zusätzlichen models) prüfen und mit mir besprechen.

**Comment by Twiek** [comment]
Update Filter:

![clarat_filter 2](https://cloud.githubusercontent.com/assets/432388/6505619/3d576932-c344-11e4-9320-97815abc90d3.png)

**Comment by KonstantinKo** [comment]
Punkt 2 *"Anzeige im Frontend im Rahmen einer 'Profisuche' die ergänzend zu sonstigen Suchlogik die Möglichkeit bietet die Ergebnisse entsprechend zu filtern."* wird mit #187 bearbeitet. Bestandteil dieses Issues ist nur die Eingabe im Backend.

**Comment by KonstantinKo** [comment]
Backend Eingabe möglich und wird validiert (bei approval, da assoziiertes model).

Hinweis: Plural von baby ist babies
