### ISSUE TITLE
Redesign Ansprechpartner, Träger, Adresse.

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#178]
In der Angebotseinzelansicht wird es künftig ein oder auch mehrere Ansprechpartner mit potentiell eigenen Telefonnummern, E-Mails etc. geben (siehe #112). In dem Rahmen wird es die bisherige 'Wo kannst du dich melden' (contact-section) Partial so nicht mehr geben. Die Ansprechpartnerinformationen sollen hingegen mit dem 'Wer bietet diese Hilfe an?' (organization_section) und dem 'Wo' (location_section) optisch stärker verknüpft werden um den inhaltlichen Zusammenhang stärker zu betonen. Hier bitte einen Vorschlag machen und wie angedeutet berücksichtigen, dass es mehrere Ansprechpartner geben kann (Zahl variiert tendenziell von Angebot zu Angebot).

**Comment by marcus-herrmann** [comment]
![offer_show_neu](https://cloud.githubusercontent.com/assets/505181/6508911/fc82132c-c35b-11e4-8976-b55ba13abc73.png)

Bei der mobilen Ansicht dieses *Wer bietet diese Hilfe an* Blocks müssten wir mit Akkordeons arbeiten.

**Comment by Twiek** [comment]
@marcus-herrmann : gab hier eventuell ein Missverständnis. Es wird max. 1 Adresse pro Angebot geben, aber eventuell mehrere Ansprechpartner (nicht zwangsweise alle mit Namen, wenn wir nix außer einer info@ E-Mail haben, dann wird daraus ein namensloser Ansprechpartner. Darüber hinaus gibt es potentiell mehrere Träger des Angebots, aber die werden nur namentlich erwähnt und verlinkt, deren Adresse taucht nicht auf, nur die Adresse des Standortes des Angebotes (Standort ≠ Organistaion/Träger).

**Comment by marcus-herrmann** [comment]
Ich hoffe richtig verstanden (auch unter Sichtung von https://github.com/clarat-org/clarat/blob/feature/112-contact-person/app/views/offers/show/_contact_section.html.slim):

![ap_neu](https://cloud.githubusercontent.com/assets/505181/6618117/5321dac8-c8c0-11e4-9b47-d7a386bc59b1.png)

**Comment by Twiek** [comment]
Ich finde es noch nicht ganz ideal. Würde Namen der Anbieter (in 99% der Fälle nur einer) näher an die Adresse rücken/kombinieren, da es potentiell ja Teil dieser ist (Name der Organisation könnte am Klingelschild stehen).

Ansonsten wirken die Webseiten gerade wie weitere Ansprechpartner (einfach weitere Bulletpoints, sind es aber nicht. Inzwischen werden URLs auch verkürzt angezeigt, d.h. alles hinter der TLD ist nicht mehr zu sehen (also aus 'http://www.exit-deutschland.de/Startseite/Islamismus-/-Ultranationalismus/HAYAT/Beratungsstelle-HAYAT-K381.htm' wird 'www.exit-deutschland.de').

Auch scheint mir gerade das 'Wann kannst du dich melden?' näher mit der Karte verknüpft, als die eigentliche Adresse (zugegeben nicht ganz einfach zu lösen ohne die Karte ganz anders anzuzeigen).

**Comment by marcus-herrmann** [comment]
Wie besprochen:

![offer_show_150319](https://cloud.githubusercontent.com/assets/505181/6728047/0aefd996-ce27-11e4-84b2-caaaedd45264.png)

**Comment by marcus-herrmann** [comment]
@Twiek : Hier deine Skizze von letzter Woche übertragen. Bei der erwartbaren Höhe der Öffnungszeiten und fester Höhe der Karten (aber unklaren Höhe der Anbieter und Ansprechpartner) würde ich den Social Media Container noch mit in die Hauptspalte nehmen:

![offer_show_20150402](https://cloud.githubusercontent.com/assets/505181/6959886/b704bc96-d91d-11e4-9999-429245e10d4a.png)

**Comment by marcus-herrmann** [comment]
Umsetzung beginnen oder #222 / anderes abwarten?

**Comment by marcus-herrmann** [comment]
Note to self: Anbieter ÜBER Adresse nach links.

**Comment by marcus-herrmann** [comment]
PR gestellt
