### ISSUE TITLE
Schreibweise von Telefonnummern

### ISSUE THREAD

**Issue by JensBaumgarten** [clarat-org/clarat#179]
Die Schreibweise der Telefonnummern im Kontaktfeld richtet sich nach folgenden Regeln:

1. Die Vorwahl erscheint im Block
2. Zwischen Vorwahl und Hauptnummer gibt es ein Freizeichen
3. Die 'Hauptnummer' (Tel ohne Vorwahl) erscheint von links nach rechts in Zweierblöcken
4. Hat die Hauptnummer ein ungerade Zeichenanzahl, steht die letzte Zahl einzeln 

Beispiel: 02234 56 45 87 4

Von: Sprachteam

**Comment by KonstantinKo** [comment]
Wird mit #178 bearbeitet
