### ISSUE TITLE
Testphasenstörer bug bei verschiedenen Flash-Benachrichtigungen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#180]
Siehe Screenshots:

![bildschirmfoto 2015-03-02 um 17 39 57](https://cloud.githubusercontent.com/assets/432388/6445305/5685c284-c103-11e4-896d-f5c910d0ed5a.png)
![bildschirmfoto 2015-03-02 um 17 40 10](https://cloud.githubusercontent.com/assets/432388/6445307/584f4180-c103-11e4-9b37-00c5d047071f.png)

**Comment by marcus-herrmann** [comment]
Da fehlte nur ein left:0; als Hotfix direkt in develop ergänzt.
