### ISSUE TITLE
Filter designen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#187]
In der Suche soll es möglich sein die Ergebnisse zu Filter. In einem ersten Schritt soll die folgende Logik abgebildet werden:

![clarat_filter 2](https://cloud.githubusercontent.com/assets/432388/6506199/7c96a432-c349-11e4-835b-7bd20787aa22.png)

Die Filter sollen auf dem Desktop per default zu sehen sein (tendenziell über den Suchergebnissen), in der mobilen Version nicht. In beiden Fällen braucht es einen Button zum ein-/aufklappen ('Erweiterte Suche').

Insbesondere bei der Sprache ist zu erwarten, dass es mit der Zeit sehr viele Auswahlmöglichkeiten geben wird. Hier bitte Lösungsvorschläge mit Dropdown und Popup machen.

**Comment by marcus-herrmann** [comment]
Zwischenstand für @KonstantinKo 

![profisuche_wip](https://cloud.githubusercontent.com/assets/505181/6510700/e819ba5a-c367-11e4-9009-cf48af1511a3.png)

**Comment by Twiek** [comment]
Jefällt mir. Bitte testweise noch mal eine Version mit dem zusätzlichen Filter 'Jetzt geöffnet' einbauen (Tendenziell unter 'Sprache').

**Comment by marcus-herrmann** [comment]
![profisuche](https://cloud.githubusercontent.com/assets/505181/6613996/afecc5a0-c894-11e4-92cb-bd0d67a52f2b.png)
![profisuche ausgeklappt](https://cloud.githubusercontent.com/assets/505181/6613997/aff00756-c894-11e4-8997-9dbc9afdcae8.png)

Note to self: Mobile fehlt noch

**Comment by Twiek** [comment]
Bitte auch noch mal eine Ansicht dafür, wenn die Filter zugeklappt sind. Auch um zu testen inwiefern man doch das zum default machen kann. In dem Szenario bräuchte es dann aber definitiv noch einen Hinweis in der Nähe der Pfeile (z.B. 'Erweiterte Suche', oder 'Filter anzeigen').

**Comment by marcus-herrmann** [comment]
(Nachgereicht: mobile)

![filter mobile offener 2](https://cloud.githubusercontent.com/assets/505181/6728122/a98c1826-ce27-11e4-9679-8f43bc64e321.png)
![filter mobile offener](https://cloud.githubusercontent.com/assets/505181/6728124/a98de30e-ce27-11e4-80e2-01a54c731fa7.png)
![filter mobile geschlossen](https://cloud.githubusercontent.com/assets/505181/6728123/a98d4444-ce27-11e4-927f-0d71c02e3113.png)

**Comment by marcus-herrmann** [comment]
Filter eingeklappt Desktop (+ Update Filter ausgeklappt):

![profisuche ausgeklappt 2](https://cloud.githubusercontent.com/assets/505181/6731967/1265cf60-ce49-11e4-9168-aeaa23956464.png)
![profisuche mit getrennten suchergebnissen - update](https://cloud.githubusercontent.com/assets/505181/6731968/1265f5e4-ce49-11e4-965b-31b731e4f957.png)

**Comment by Twiek** [comment]
@marcus-herrmann: Beim Altersfilter wird 'junge Erwachsene' ersatzlos gestrichen.

**Comment by KonstantinKo** [comment]
Bitte nochmal develop pullen wenn du daran weiterarbeitest @marcus-herrmann 
Das erweiterte Suchformular existiert jetzt, ohne styling

**Comment by marcus-herrmann** [comment]
Seit #137 gibt es ja ein Ajax Load Event, um die Suchergebnisse anzuzeigen. Nun benötigt die Filterliste auch etwas JavaScript, um eingeklappt zu starten. Das klappt auch beim ersten Seitenaufruf ohne Ajax, danach kann ich aber keinen Event Listener auf "nachdem der Ajax Load lief" setzen. Aktuell versuche ich ein custom event zu triggern, ohne Erfolg: a3ca3d34cacc20d1a2e85b7715f6fb5075036da0

Speziell in der Smartphone-Ansicht brauche ich aber JS, um dem sehr hohem Filter visuell Herr zu werden. Kannst du mir da weiterhelfen? Kann ich auf ein bestimmtes Event aus Rails, ähnlich page:load hören?

**Comment by KonstantinKo** [comment]
@marcus-herrmann Geht es um das ajax_replaced event? Weil das wird bei mir problemlos etriggert und abgefangen.

Test war:
```
$(document).on 'ajax_replaced', ->
  alert 'here'
```
in ein coffee file geschrieben, In Suchergebnissen auf eine Kategorie geklickt, das alert kam.

**Comment by marcus-herrmann** [comment]
ajax_replaced war das custom event, das ich getriggert und gelistened habe, genau. funktionierte bei mir allerdings nicht. schaue da am donnerstag aber noch mal rein.

**Comment by marcus-herrmann** [comment]
Mit dem alert-Beispiel gehts inzwischen auch, insofern liegt's nicht am Event, sondern der filterExpand() function. Bin dran.

**Comment by marcus-herrmann** [comment]
PR gestellt

**Comment by marcus-herrmann** [comment]
Note to self:
* Fix: Falscher Filter-Collapse, nicht in Ausgangshöhe
* Fix: sessionStorage-Kollision wenn mehrere Tabs offen
* Änderung: Mobil: Kategorien raus, Filter-Switch an die Stelle des "Kategorie"-Links in blauer Bordüre

**Comment by marcus-herrmann** [comment]
@Twiek Kannst du eventuell noch mal pullen bis 178d1ee und checken, ob der Fehler noch auftaucht, wenn du zwei Tabs mit clarat offen hast, und dann ein Filter-Collapse ("Weniger Filter anzeigen") danach nicht mehr funktioniert? Konnte es weder vor dem PR noch jetzt reproduzieren
