### ISSUE TITLE
Blog Einschätzung

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#188]
Es soll einen clarat Blog geben. Sehr simpel (ähnlich https://stripe.com/blog + Kommentarfunktion). Macht es Sinn hierfür Wordpress aufzusetzen, oder gibt es ausreichend gute Railslösungen?

**Comment by KonstantinKo** [comment]
Gehe ich richtig in der Annahme, dass der Blog von denselben Menschen bedient werden soll wie http://www.benckiser-stiftung.org/blog/ ? Dann könnte man ja einfach dieselbe Plattform wie dort auch schon nehmen.

Es gibt auch gute rails blogs, aber im Zweifelsfall kann man da auch Wordpress nehmen, wenn schon klar ist, dass es simpel bleibt und keine Anpassungen benötigt werden.

**Comment by Twiek** [comment]
Goog point, werde das klären.
