### ISSUE TITLE
Cookie-Warning

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#192]
Vgl. Huffington Post:

![bildschirmfoto 2015-03-06 um 12 17 24](https://cloud.githubusercontent.com/assets/432388/6524523/d1587584-c3fa-11e4-96ab-37780c8bed31.png)

Wobei ich es aufgrund des Beta-Banners tendenziell besser fände, wenn es ganz unten angezeigt würde.

Mit folgendem Text:

„Diese Webseite verwendet Cookies, die es uns ermöglichen, Ihre Aktivtäten auf dieser Webseite zu speichern. Diese Informationen sind notwendig um das Angebot auf unserer Webseite für unsere Besucher stetig verbessern zu können. Nähere Informationen, insbesondere was Cookies sind und wie Sie der Verwendung widersprechen oder diese abstellen können, erhalten Sie hier (Link zu /datenschutzerklaerung). Wenn Sie diese Webseite nutzen, erklären Sie damit Ihre Einwilligung zum Setzen aller auf dieser Webseite verwandten Cookies.“

Das ganze noch mit einem Kreuzchen zum wegklicken versehen und frühestens 3 Monate später erneut anzeigen (Vgl. #191).

**Comment by KonstantinKo** [comment]
Was macht das Kreuzchen zum Wegklicken? Dasselbe wie wenn man auf 'ich stimme zu' klickt?

**Comment by Twiek** [comment]
Gibt kein 'ich stimme zu'.

Ansonsten den Hinweis gerne unten anzeigen.

**Comment by KonstantinKo** [comment]
Bitte stylen

**Comment by marcus-herrmann** [comment]
Basic styling drin, Font Size halbwegs ausgemittelt zwischen Textlänge und Wichtigkeit des Hinweises. Komplette Komponente wird aber spätestens in Smartphoneansicht kritisch (obwohl dort Font-Size nochmals kleiner).

**Comment by Twiek** [comment]
Bitte in
