### ISSUE TITLE
Removing 'encounter' from offers

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#193]

**Comment by KonstantinKo** [comment]
@Twiek Du hast Tests für encounter_value rausgeschmissen, die Funktion ansich aber noch drin gelassen. Das gibt unter Garantie Probleme mit der Test Coverage.

Es ist natürlich die Frage, was damit passieren soll. Wenn man jetzt einfach die Funktion entfernt, funktioniert das indexing nicht mehr, weil wir den Wert ja für die Sortierung in der Suche benötigen. Früher oder später muss die Suche ja eh angepasst werden, aber bis dahin würd' ich den Test wieder reinnehmen. Außerdem muss in die Funktion auch noch ein 'else' rein, weil wir ja nichtsmehr davon ausgehen können, dass encounter auch gefüllt ist.

2. In test/factories/offers.rb Zeile 44 setzt du location auf nil, und danach passiert was falls location nicht nil ist. Pack Zeile 46 doch noch mit in die if-Schleife davor

**Comment by Twiek** [comment]
@KonstantinKo Bitte übernehmen sie (Vgl. 'Suche' Dokument).
