### ISSUE TITLE
Keine Angebote gefunden Screen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#196]
Sollte man über die Freitextsuche keinerlei Ergebnisse finden (z.B. wenn man nach ';jdkslfnasdfn;lknasdfkl;nasd as;dlffa' sucht), so sollte nicht einfach eine leere Seite mit einer leeren Karte erscheinen, sondern ein Screen analog zu diesem:

![bildschirmfoto 2015-03-09 um 14 58 59](https://cloud.githubusercontent.com/assets/432388/6556325/fcad9506-c66c-11e4-97ed-5495e83da3d2.png)

Dabei folgenden Text verwenden:

Überschrift:
"Leider konnten wir zu dem Suchbegriff 'sadfsfasd' keine Angebote finden"

Text:
Bitte versuche es mit einem anderen Suchbegriff oder suche über die Kategorien.

**Comment by jjungle** [comment]
Der Text müsste vorerst gekürzt werden:

"Bitte versuche es mit einem anderen Suchbegriff."

Sonst ist er irreführend, klickt man links in die Kategorien wird der Suchbegriff nicht gelöscht und man findet ebenfalls nichts zu 'sadfsfasd'

**Comment by Twiek** [comment]
Und FAQs verlinken

**Comment by NilsVollmer** [comment]
@Twiek @jjungle  Die Map ist mit Issue #463 raus.

Vorschlag für den Text inkl. FAQ-Link:
"Bitte versuche es mit einem anderen Suchbegriff. Zu den häufig gestellten Fragen kommst du hier(LINK)"

oder:

"Es konnten leider keine Angebote gefunden werden. Manche Hilfsangebote sind nicht bei clarat. Warum das so ist kannst du hier(LINK) nachlesen.

**Comment by NilsVollmer** [comment]
@Twiek So in etwa vom Wording & Verhalten?

**Comment by NilsVollmer** [comment]
Waiting for FAQ branch (Deep Link)
