### ISSUE TITLE
Minimalistisches clarat Wordpress Theme entwerfen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#201]
Mit Kommentarfunktion, aber ansonsten ohne Schnickschnack (z.B. auch keine Seitenleiste).

Inspirationen z.B. https://medium.com/ (die Artikel, nicht der Stream), https://stripe.com/blog (nur nicht ganz so blass) oder https://signalvnoise.com/.

Vor Beginn gerne noch mal Rücksprache halten.

**Comment by marcus-herrmann** [comment]
Aus den Vorbildern ergibt sich folgendes:

* Textlasting, einspaltig
* Ein großer Strom an Artikeln, keine Teaser, sondern Volldarstellung der Artikel auch auf Listingseiten (Artikelindex)
* Viel Weißraum

Fragen:

* Sind neben den Artikeln Inhaltsseiten geplant (außer Impressum)?
* Kommentare WordPress-nativ oder beispielsweise Disqus?
* Erstmal Entwurfsphase in Grafikprogramm oder gleich designing in the browser?
* Schon Texte vorhanden? Ansonsten nehme ich Blindtexte

**Comment by marcus-herrmann** [comment]
Vorschlag technische Grundlage: https://roots.io/bedrock/intro/

Mit u.a.
* Dependency management with Composer
* Automated deployments with Capistrano
* Better folder structure
* Easy WordPress configuration with environment specific files
* Environment variables with Dotenv

**Comment by marcus-herrmann** [comment]
Idee Maskottchen: Wie in den folgenden Screenshots visualisiert, oder Clara an einer (schönen, alten, roten?) Schreibmaschine.

Ansonsten im Folgenden WIP-Stände / eine erste Idee:

![viewport beispiel](https://cloud.githubusercontent.com/assets/505181/7301439/f996a40e-e9e2-11e4-837d-c6aa29dfe323.png)
![full view open menu](https://cloud.githubusercontent.com/assets/505181/7301440/f996dc26-e9e2-11e4-9a65-e79fdfecd39b.png)
![full view](https://cloud.githubusercontent.com/assets/505181/7301441/f99812f8-e9e2-11e4-9eb1-a3ecc8708b71.png)

**Comment by Twiek** [comment]
Bitte noch mal nen Screen entwerfen mit Fotos und/oder Grafiken (eventuell auch 2 Varianten). Vgl. https://medium.com/migration-issues/why-are-americans-leaving-75fe530ce49d.

**Comment by marcus-herrmann** [comment]
Thema Fotos/Grafiken: Geht es dir um Inline Images oder eher eine Titelbildfunktion? Wenn letzteres: Hier zwei mögliche Varianten, eins im Großfoto-medium.com-Stil, eines mit Zeichnung/Magazin-Charakter (entlehnt aus alistapart.com, da kommt auch die Zeichnung für die Skizze her):

![blog_bild2](https://cloud.githubusercontent.com/assets/505181/7417449/684f9eb8-ef66-11e4-8e56-a39db351dcaa.png)
![blog_bild1](https://cloud.githubusercontent.com/assets/505181/7417450/685036c0-ef66-11e4-865f-dc84768a3046.png)

**Comment by marcus-herrmann** [comment]
(MOBILE generisch) Auch dies nur Skizze, keine Reinzeichnung:

![blog_mobile_draft](https://cloud.githubusercontent.com/assets/505181/7418635/994216be-ef6f-11e4-8179-696dd4b9b1dd.png)

**Comment by Twiek** [comment]
Bitte noch mal eine Version in der unter dem Artikel weitere Artikel angeteasert werden (Vgl. https://medium.com/dan-sanchez/miyazaki-s-beautiful-antiwar-dreams-44951be1be11) und eine mit Kommentaren.

Dabei bitte keine Fotos/Bilder über dem Text nutzen, wenn dann im Text.

**Comment by marcus-herrmann** [comment]
Hier HTML-Prototypen, ohne Navigationsfunktion und responsives Verhalten (Tabs würden mobil aber Akkordeons werden)

* http://clarat-blog.aufbau-server.de/overview.php - Startseite, Archivseite, Artikellisting
* http://clarat-blog.aufbau-server.de/single.php - Einzelartikelseite, Comments, Teaser auf weitere Artikel

**Comment by marcus-herrmann** [comment]
fyi: Clara T. mit Megafon ist nur eine schnelle Skizze meinerseits, ggf. muss hier noch eine richtige Illustration angefordert werden.

**Comment by Twiek** [comment]
Bitte folgende Dinge testen/umsetzen:

- Blog Schriftzug Variationen
- Verzicht auf fetten/gesonderten Teasertext (in der Übersicht einfach die ersten X Worte/Zeichen anzeigen)
- Artikel in der Übersicht komplett (ausgeschrieben) anzeigen.
- Farbe und Schriftart des Datums anpassen (mehr am Text orientieren) und das Datum eventuell nach unten (in der Artikeleinzelansicht)
- Auf Uhrzeit im Datum (Übersicht) verzichten
- Kategorien in der Artikeleinzelansicht anzeigen (dezent/unten)
- Ein Beispiel für Suchergebnisse erstellen (und/oder für die Übersicht nach ausgewählten Kategorien)

**Comment by marcus-herrmann** [comment]
Kleines Update der Vorschauen:

http://clarat-blog.aufbau-server.de/overview.php
http://clarat-blog.aufbau-server.de/single.php

Parallel läuft die WP-Theme-Erstellung, weiteres dann morgen.
