### ISSUE TITLE
'mehr erfahren' Text blitzt auf

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#205]
Wenn ich auf der Startseite die Lupe (Suche) klicke und auf die Suchergebnisseite klicke, so blitzt dort ganz kurz am oberen Rand der Text auf der im 'mehr erfahren' (Beta Banner) Modal steht, allerdings ander formatiert. Das sollte nicht sein.

Leider zu Schnell für Screenshots, aber sowohl in Chrome als auch in FF reproduzierbar (OSX Yosemite).

**Comment by marcus-herrmann** [comment]
Alles klar, kann es reproduzieren.

**Comment by marcus-herrmann** [comment]
Als hotfix auf develop.
