### ISSUE TITLE
'Alle Kategorien' Kategorie!?

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#209]
Wenn ich als User angefangen habe in die Kategoriensuche einzutauchen (egal ob in Kombination mit der Freitextsuche oder nicht), komme ich schwer wieder raus, d.h. ich muss erst wieder auf die Startseite um mich von allen Kategorien zu 'befreien'.

Hier sollte es einen leichteren Ausweg geben. Konkrete Ideen:

* Über den Hauptkategorien auf der Suchergebnisseite noch einen Link/Button 'Alle Kategorien' anzeigen. 
* Den Breadcrumbs das Wort 'Startseite' voranstellen (Vgl. Zalando)

Weitere Ideen willkommen.

**Comment by marcus-herrmann** [comment]
Nachdem die Breadcrumbzeile unberechenbar voll werden kann, sehe ich das eher über den Kategorien (wird so wie gestaltet sprachlich redundant; finde ich aber verkraftbar):

![alle-kategorien](https://cloud.githubusercontent.com/assets/505181/6730440/ee97d576-ce3c-11e4-92e5-488ccddf4214.png)

**Comment by Twiek** [comment]
I like. @KonstantinKo bitte übernehmen sie!

**Comment by marcus-herrmann** [comment]
Styling via commit e6ef65af0ed8fb546364f053eb5ea10910939120 - stelle aber PR zusammen mit den restlichen Punkten aus #137
