### ISSUE TITLE
Getrennte Suchergebnisse

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#210]
Technisch scheint es unvermeidlich, dass wir die Suchergebnisse zweiteilen müssen. Zum einen 'vor Ort' Angebote und zum anderen 'virtuelle' Angebote (also Hotlines, Chatberatung... ).

Aktuell angedacht ist, dass standardmäßig nur 'vor Ort' Angebote angezeigt werden. Lediglich ein einziges 'virtuelles' Angebot wird ganz oben über den anderen angezeigt und ist in irgendeiner Form optisch abgehoben + verfügt über einen Button/Link 'Weitere Hotlines anzeigen' (Wording vorläufig). Wenn ich darauf klicke komme ich auf eine Suchergebnisseite auf der zu den zuvor festgelegten Suchkriterien ausschließlich 'virtuelle' Angebote zu finden sind. Tendenziell sind hier dann bestimmte Filter vorausgefüllt (aktuell noch work in progress).

Besonderheiten:
* Wenn man bei den 'virtuellen' Suchergebnissen ist wird keine Karte angezeigt und es wir natürlich auch kein einzelner virtuelles Angebote hervorgehoben.

**Comment by marcus-herrmann** [comment]
Vorschlag für optische Abgrenzung virtueller Angebote. Im blauen Container kann "E-Mail", "Chat", "Telefonisch" (oder Hotline) stehen:

![profisuche mit getrennten suchergebnissen](https://cloud.githubusercontent.com/assets/505181/6729169/f9a74e5e-ce2f-11e4-9ee9-a5ce8d496144.png)

**Comment by marcus-herrmann** [comment]
![profisuche mit getrennten suchergebnissen - nur virtuell](https://cloud.githubusercontent.com/assets/505181/6729511/5384654e-ce33-11e4-85bb-0b7d554c2560.png)

**Comment by marcus-herrmann** [comment]
Notes to self:

* mobil
* Tausch: (Anbieter) (Form) statt (Form) (Anbieter)

**Comment by marcus-herrmann** [comment]
Tausch der Positionen von Anbieter und Kontaktaufnahmeart (wirkt m.M.n. zu unruhig):

![profisuche mit getrennten suchergebnissen - form nach anbieter](https://cloud.githubusercontent.com/assets/505181/6730846/4c5bea1e-ce40-11e4-87df-600fd0ff6f31.png)

Ruhiger würde es werden, stünde die Kontaktaufnahmeart ganz rechts - aber dann wären die Angebote nicht mehr so schnell von Angeboten mit Anlaufstelle unterscheidbar:

![profisuche mit getrennten suchergebnissen - form ganz rechts nur virtuell](https://cloud.githubusercontent.com/assets/505181/6730859/741d9048-ce40-11e4-8878-74d140681932.png)

![profisuche mit getrennten suchergebnissen - form ganz rechts](https://cloud.githubusercontent.com/assets/505181/6730858/741be414-ce40-11e4-9173-872d1858b470.png)

**Comment by marcus-herrmann** [comment]
Variante mit Kontaktaufnahmeart statt Adresse der Anlaufstelle, und vergleichbar (unauffällig) formatiert:

![profisuche mit getrennten suchergebnissen 2](https://cloud.githubusercontent.com/assets/505181/6731390/f8019c16-ce44-11e4-9a34-ab9438d2b01e.png)
![profisuche mit getrennten suchergebnissen](https://cloud.githubusercontent.com/assets/505181/6731389/f80181ea-ce44-11e4-9012-98c0d1bee193.png)

**Comment by marcus-herrmann** [comment]
Mobile Variante. Wie erwähnt würde ich hier vorschlagen, den Organisationsnamen ggf. abschneiden zu lassen (frontendseitig, CSS):

![mobile getrennte suchergebnisse](https://cloud.githubusercontent.com/assets/505181/6731626/6a9322a8-ce46-11e4-9e14-13a22f4133f7.png)

**Comment by marcus-herrmann** [comment]
Bräuchte hier für den View eine Ausgabe, ob "Telefonisch" oder "Online" zum Formatieren.

**Comment by marcus-herrmann** [comment]
Note to self: Zwischenüberschriften stylen

**Comment by KonstantinKo** [comment]
Gibt jetzt ein span im _single_search_result mit der Info. Es kann doch nur eine der Optionen haben.

**Comment by marcus-herrmann** [comment]
@Twiek Bevor ich einen PR stelle noch eine Frage hierzu: https://github.com/clarat-org/clarat/blob/c0eeeae65ee4fd628b322a59303b7b9db053ded5/app/views/offers/index/_single_search_result.html.slim - kann die Adresse einheitlich aus dem View entfernt werden, sobald es ein online/telefonisches Angebot ist? Online/Telefon + "Überall dort..." Ausgabe wäre redundant und gerade im kleinsten Breakpoint schmerzhaft.

**Comment by Twiek** [comment]
@marcus-herrmann: Ja, kann gemacht werden. Lass uns das morgen direkt zusammen umsetzen.

**Comment by marcus-herrmann** [comment]
Gemeint ist Donnerstag?

**Comment by Twiek** [comment]
Ja, morgen im Sinne von übermorgen... ;-)

**Comment by marcus-herrmann** [comment]
Comment mit Nachfrage entfernt, PR gestellt. Wenn unklar/anders zu lösen, gerne declinen.
