### ISSUE TITLE
WYSIWYG Editor integrieren

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#212]
Für Angebote (description und next steps). Es sollen Verlinkungen und Bullet Points möglich sein. Alles andere wenn möglich gar nicht erst als Möglichkeit anbieten. 

Erster Versuch findet sich hier: https://github.com/clarat-org/clarat/tree/wysihtml5

Bei dieser gibt aktuell noch mindestens 2 Probleme:

1. Der character count funktioniert erst nachdem man den 'Speichern' Button drückt und er zählt auch alle HTML-Tags mit, auch wenn man diese gar nicht sieht. Besser wäre auch hier ein 'Livecounter' und im Idealfall einer, der nur die Zeichen zählt, die auch der User sieht, selbst wenn die Validation sich auf sämtliche Zeichen bezieht (in einer perfekten Welt würde sie sich auch nur auf die 'sichtbaren' Zeichen beziehen). In dem Rahmen die validierte Zeichenzahl auf 600 hochsetzen.

2. Wenn man einen Link setzt und danach den Link (im Editor) doppelt anklickt geht das Fenster (modal) noch mal auf. Wenn man dann auf 'cancel' klickt wird der Bildschirm schwarz. Problem wird scheinbar auch hier diskutiert: https://github.com/jhollingworth/bootstrap-wysihtml5/issues/77 (Lösung scheint aber nicht zu klappen oder wurde von mir falsch eingebaut).

Bei Bedarf gerne auch auf eine anderes Gem/Lösung setzen und den Ansatz verwerfen.

**Comment by KonstantinKo** [comment]
Vorschlag war, mit Markdown zu arbaiten

**Comment by KonstantinKo** [comment]
Markdown it is
