### ISSUE TITLE
Schreibweise von Faxnummern

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#217]
Die Schreibweise von Faxnummern bitte wie in #179 anpassen.
Derzeit werden die Faxnummern noch in Zweierblocks dargestellt.
![screenshot 2015-03-23 at 12 56 41 - display 1](https://cloud.githubusercontent.com/assets/11425826/6779463/73e2185a-d15c-11e4-9bf1-4d542055205a.png)

**Comment by jjungle** [comment]
Sehe grad noch das da ein Doppelpunkt nach "Fax:" zuviel ist.

**Comment by KonstantinKo** [comment]
Wird mit #178 bearbeitet.
