### ISSUE TITLE
Öffnungszeiten zusammenfassen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#222]
Wenn ein Angebot verschiedene Öffnungszeiten an einem Tag hat (Beispiel siehe Screenshot), dann wird es schnell relativ unübersichtlich. Kann man das irgendwie optisch sinnvoll zusammenfassen?

![bildschirmfoto 2015-03-26 um 10 44 20](https://cloud.githubusercontent.com/assets/432388/6843644/361843b4-d3a5-11e4-9360-7f92a2c8e9e3.png)

**Comment by marcus-herrmann** [comment]
Siehe #178. Bräuchte aber entsprechend zusammenfassende Backend-Ausgabe, semantisch macht eine Tabelle Sinn.

![](https://cloud.githubusercontent.com/assets/505181/6959886/b704bc96-d91d-11e4-9999-429245e10d4a.png)

**Comment by Twiek** [comment]
@KonstantinKo Relevant: http://xkcd.com/1513/

**Comment by KonstantinKo** [comment]
Sehr passend :)

Dieses ganze opening_hash klingt mir nach einem value object, in dem könnte man dann auch sowas wie `.keys.grep(day).last.equal? day` als Methode verpacken.

Ich kann ja mal einen Gegenvorschlag vorbereiten.

**Comment by KonstantinKo** [comment]
@Twiek kannst dir ja mal meine Lösung von 1371be5 ansehen
@marcus-herrmann bitte Tabellenstyling anpassen

**Comment by marcus-herrmann** [comment]
Angepasst.
