### ISSUE TITLE
Safari Location bug

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#230]
Wenn ich in Safari gefragt werde ob er meinen aktuellen Standort verwenden darf, wird die Frage so oft wiederholt, bis ich angebe, dass er sich das für einen Tag merken darf. Kann man das irgendwie vermeiden (in Chrome und FF passiert das nicht).

![bildschirmfoto 2015-03-31 um 17 59 06](https://cloud.githubusercontent.com/assets/432388/6923108/17b76948-d7d0-11e4-95a0-82f20da18e41.png)

**Comment by KonstantinKo** [comment]
Auf feature/230-geolocation-rework liegt eine Erneuerung des Standort-Abfrage-Konzepts hinterlegt und gerade auf staging deployed. Bitte mal nachsehen ob das so von der Funktionalität iin Ordnung ist. Wenn ja an Marcus zum styling

**Comment by Twiek** [comment]
Bitte Styling anpassen.
