### ISSUE TITLE
New Relic integrieren

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#231]
Vorerst den 'Stark' Plan (https://addons.heroku.com/newrelic?utm_campaign=category&utm_medium=dashboard&utm_source=addons#stark).

Wichtig: Alle personenbezogenen Daten anonymisieren.

**Comment by KonstantinKo** [comment]
Hab bisher noch keine personenbezogenen Daten sehen können und zumindest in unserem gem was Daten an New Relic schickt, ist auch eingestellt, dass Datenbank-queries nur obfuscated übergeben werden. Weiter privacy Einstellungen hab ich noch nicht gefunden.

**Comment by Twiek** [comment]
Ist es das gleiche was hier beschrieben wird: https://docs.newrelic.com/docs/apm/transactions/transaction-traces/security-options-transaction-traces#obfuscation?

**Comment by KonstantinKo** [comment]
@Twiek Ja
