### ISSUE TITLE
Erklärpopups

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#236]
Bitte Lösungsvorschläge für folgende Anforderung erstellen:

Bestimmte Worte in der offer.description sollen als Link angezeigt werden und wenn man darauf klickt erscheint ein Text der dieses Wort erklärt. Entweder als Popup oder als Hover Effekt (muss aber auch mobil funktionieren, siehe z.B. hier: http://stackoverflow.com/questions/22559756/changing-hover-to-touch-click-for-mobile-devices).

Wichtig ist dabei eine automatisierte Möglichkeit entsprechende Link nachträglich zu erstellen, also wenn Wort 'X' oder 'Y' in der description auftaucht, dann daraus einen Link zu Popup 'Z' generieren.

**Comment by Twiek** [comment]
Bitte auch für die Beschreibung der Organisationen ergänzen.

Wie löscht man die Links in offer.description, wenn die Definition gelöscht wird?

**Comment by Twiek** [comment]
@marcus-herrmann Hier bitte das Styling anpassen (u.a. größere Schrift, gerade in der mobilen Ansicht + die Worte nicht kursiv, sondern unterstrichen anzeigen -> wie ein Link).

![bildschirmfoto 2015-04-17 um 16 32 49](https://cloud.githubusercontent.com/assets/432388/7204077/b793bd16-e51f-11e4-8b73-e834533b8608.png)
![bildschirmfoto 2015-04-17 um 16 33 38](https://cloud.githubusercontent.com/assets/432388/7204076/b7932680-e51f-11e4-800d-5d4e18ec25c4.png)

**Comment by marcus-herrmann** [comment]
Grundsätzliches Styling via 427046d1ed80e8502b29c8142ac19da110ced878

Auf meinem System positioniert das qTip2-JS allerdings teils im Offset, siehe Screenshot. @Twiek Bei Dir scheinbar nicht? Einstellungssache im Gem?

![bildschirmfoto 2015-04-23 um 13 09 38](https://cloud.githubusercontent.com/assets/505181/7295862/4a1948f6-e9ba-11e4-8686-47cd20eb0bc2.png)

**Comment by KonstantinKo** [comment]
@marcus-herrmann Bastis screenshot war vom develop branch. Ich hatte das Positioning dort geändert, ohne es nochmal in den feature branch zu mergen. Habe dies jetzt getan.

**Comment by marcus-herrmann** [comment]
:+1:

**Comment by marcus-herrmann** [comment]
PR stellen?

**Comment by Twiek** [comment]
Ja.

**Comment by marcus-herrmann** [comment]
https://github.com/clarat-org/clarat/pull/256
