### ISSUE TITLE
Performance messen und erhöhen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#245]
Siehe auch #238 und #231.

Weitere Hinweise lass sich auch E-Mail oder https://developers.google.com/speed/pagespeed/insights/?url=developer.clarat.org

**Comment by Twiek** [comment]
Ziel ist es sowohl 'Mobil' als auch auf dem 'Desktop' auf einen Wert von mind. 90/100 zu kommen.

**Comment by KonstantinKo** [comment]
PageSpeed Insights scheint mir ausgeschöpft, den Rest den er dort noch findet kann ich nicht direkt beeinflussen und er behauptet application.css würde dinge über dem fold blockieren aber es ist schon ganz unten. Einzig die Klickflächen-Größe im Mobile Bereich könnte man noch ändern.

DareBoost hat hauptsächlich dasselbe gesagt und beschwert sich noch über ein paar Kleinigkeiten, die ich nebensächlich finde.

Größte Baustelle nach NewRelic ist noch immer der Offers#index view. Ich werde als nächstes mal angehen, diesen asynchron arbeiten zu lassen (ähnlich wie bei 1deg)
