### ISSUE TITLE
'Akute Krisen' nennenswert hervor- abheben

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#252]
Auf der Startseite und der Suchergebnisseite.

Einfach orange umranden reicht nicht.

![unterstutzungsangebote fur kinder jugendliche und familien clarat](https://cloud.githubusercontent.com/assets/432388/7204122/14c6292e-e520-11e4-9ca2-fd407da0ed0a.png)

**Comment by marcus-herrmann** [comment]
Nachdem Orange auf Gelb ohnehin problematisch wäre - ist Farbinvertierung des Piktogramms eine Option?

![akute krisen hervorgehoben](https://cloud.githubusercontent.com/assets/505181/7293110/e440599c-e9a1-11e4-94ef-268013cd3269.png)

**Comment by Twiek** [comment]
Ja, bitte einmal im eigenen Branch umsetzen.

**Comment by marcus-herrmann** [comment]
Branch: `/feature/252-emphasis-on-crisis-picto`: https://github.com/clarat-org/clarat/tree/feature/252-emphasis-on-crisis-picto
