### ISSUE TITLE
Anlegen neuer Audience Filter

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#253]
Die Age Filter "Eltern" und "Großeltern" müssten in die "Audience Filter" wandern.
Hierzu müssen neue Identifier erstellt werden.

**Comment by Twiek** [comment]
Siehe https://github.com/clarat-org/clarat/commit/4984e6c60d97badd0074861701f581f04a4827f1

**Comment by KonstantinKo** [comment]
Man muss wahrscheinlich dann auch noch Übersetzungen anpassen, sobald das erweiterte Suchformular merged ist. Und natürlich die Daten auf production ändern nach deploy.

**Comment by jjungle** [comment]
Im Backend ist das Feature noch nicht umgesetzt.
