### ISSUE TITLE
Angebotstrennung in der Übersicht überarbeiten

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#257]
Habe bei der aktuellen, einfachen Textlosung die Sorge, dass man es komplett ausblendet...

![clarat](https://cloud.githubusercontent.com/assets/432388/7319643/3aad7f44-ea97-11e4-8410-6d8a1595e627.png)

**Comment by marcus-herrmann** [comment]
In Zusammenhang mit der Idee einer Erweiterung der Farbpalette (aus der Idee einer Ausweichfarbe für die "Flag" wurde eine Farbkodierung für nicht-lokale Angebote). Bin mir nicht 100% sicher, ob das die Nicht-vor-Ort-Angebote nicht *zu* sehr hervorhebt, will es aber mal zur Diskussion stellen.

![bildschirmfoto 2015-04-30 um 13 07 35](https://cloud.githubusercontent.com/assets/505181/7411642/42df7436-ef3a-11e4-9a28-06ff809b68ff.png)
