### ISSUE TITLE
Mobile Ansicht optimieren

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#258]
Wenn ich die Startseite mobil betrachte und dort auf eines der Kategorieicons klickt, blitzt die Filteransicht ganz kurz auf bevor sie wieder verschwindet. Das sollte nicht sein (getestet auf einem LG G3, aber auch in Chrome auf dem Desktop gut zu simulieren).

**Comment by marcus-herrmann** [comment]
JavaScript sorgt hier für das Einklappen, und das kickt erst relativ spät, CSS ist schneller. Absicht hier: Die Seite soll auch ohne JS benutzbar sein (progressive enhancement). Wenn die "geringe Höhe" fest im CSS wäre, und die Filterbox nur durch JS auf die "echte", nutzbare Höhe zu bringen wäre, wäre das eine Unbenutzbarkeit an dieser Stelle ohne JS. 

Lässt sich recht einfach umdrehen. Seite ist aber bisher top ohne JS benutzbar, und das wäre der erste kleine "Bruch". Konzeptionelle Frage.

**Comment by Twiek** [comment]
Welche mobilen Browser haben denn kein JS?

**Comment by Twiek** [comment]
Bitte dennoch optimieren aber mit einem Kommentar (im Code) versehen, falls es doch mehr Puristen gibt als vermutet.

**Comment by marcus-herrmann** [comment]
Done / als Hotfix auf develop
