### ISSUE TITLE
Zeilenumbruch auf mobiler Suchergebnissseite nicht optimal

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#259]
Siehe Screenshot (sollte einheitlich direkt untereinander anfangen):

![clarat](https://cloud.githubusercontent.com/assets/432388/7319850/d51f829c-ea98-11e4-96e3-155286273784.png)

**Comment by marcus-herrmann** [comment]
Fix auf eigenem Fix branch: https://github.com/clarat-org/clarat/tree/fix/259-fix-result-listing-mobile

**Comment by Twiek** [comment]
Habe es versehentlich selber gefixt (Issue übersehen): https://github.com/clarat-org/clarat/commit/2b52ad92b189d06659acf1bfb09c07574ec35c1e

Bitte noch einmal drüber schauen und dann die beste Lösung implementieren.

**Comment by marcus-herrmann** [comment]
Ohne einen Modifier auf `.Listing-results__offerinfo`, siehe oben (das wäre für den kompletten Container in beige [beinhaltet er ein virtuelles Offer, oder nicht]), ist deine Variante die beste/pragmatischste. Mein Featurebranch zu #259 kann entsprechend gelöscht werden

**Comment by Twiek** [comment]
Ok, bitte löschen,

**Comment by marcus-herrmann** [comment]
Done.
