### ISSUE TITLE
Tracken nach welchen Orten die User suchen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#262]
Um Muster und Verbesserungspotential zu erkennen.

**Comment by KonstantinKo** [comment]
TODO:
- check another day if the analytics data were correct
- reenable opt-out

**Comment by KonstantinKo** [comment]
Erledigt. Umgesetzt mit Google Analytics

![screenshot-www google com 2015-06-17 15-14-01](https://cloud.githubusercontent.com/assets/779660/8207776/04088b36-1504-11e5-9a98-7b2622ce6ba2.png)
![screenshot-www google com 2015-06-17 15-15-59](https://cloud.githubusercontent.com/assets/779660/8207778/05dd51b2-1504-11e5-8cac-3e4979199b4a.png)
