### ISSUE TITLE
FOUC durch Einbindung des CSS ganzen unten im Body

### ISSUE THREAD

**Issue by marcus-herrmann** [clarat-org/clarat#263]
FOUC = Flash of unstyled content

Mit ~11kb ist die main CSS akzeptabel klein, wird aber dennoch erst extrem spät geladen (da nicht im `<head>`), und das führt zu einer kurzen völlig unformatierten Ausgabe der Seite (bisher nur in Blink-basierten Browsern + Safari feststellen können, am besten sichtbar bei Suche von Start aus)

**Comment by Twiek** [comment]
Auf die Gefahr hin, dass wir im Speed-Test wieder den ein oder anderen Punkt verlieren bitte wieder weiter oben einbinden (zumindest auf offer.index), denn die Lösung scheint mir aus Usersicht noch problematisch (merkbarer) als minimaler Geschwindigkeitsverlust.

**Comment by marcus-herrmann** [comment]
Kompromiss bzw. Kotau vor Google Page Speed Insights: CSS komplett im Head inlinen.

**Comment by KonstantinKo** [comment]
CSS was ich momentan auf production ausgerendert bekomme 50kb + 21kb groß und dauert zum laden 165ms + 64ms = 279ms.
