### ISSUE TITLE
Margin nach und vor Bulletpoints vergrößern

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#265]
Der Abstand zu Zeilen vor und nach Bulletpoints muss etwas vergrößert werden.
(Weniger als eine Zeile).

**Comment by jjungle** [comment]
![bulletpoints](https://cloud.githubusercontent.com/assets/11425826/7412813/9e201e52-ef46-11e4-8256-548e70f5d52b.jpg)

**Comment by marcus-herrmann** [comment]
Auf develop
