### ISSUE TITLE
Sortierung der Uhrzeiten

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#268]
Bei mehreren Uhrzeiten/Sprechzeiten pro Tag, sollten diese von früh nach spät sortiert werden.
Momentan werden diese anscheinend nach Zeitpunkt der Eingabe sortiert. (Siehe Screenshot)

**Comment by jjungle** [comment]
![screenshot 2015-05-05 at 10 12 13](https://cloud.githubusercontent.com/assets/11425826/7469197/fd32559a-f310-11e4-8767-c4d1ed12712e.png)

**Comment by Twiek** [comment]
Beispiel: http://developer.clarat.org/angebote/beratung-fuer-eltern-bei-sorgen-und-problemen

**Comment by Twiek** [comment]
Durch https://github.com/clarat-org/clarat/commit/af0f5b45d20dcb468b9bc742f1eae8042f2c277a gelöst.
