### ISSUE TITLE
Preview-Mode für Angebote

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#270]
Als Researcher möchte ich ein 'Web-Preview' des Angebots sehen können bevor es approved ist.

**Comment by KonstantinKo** [comment]
Man kann einfach auf das Auge neben einem Angebot oder einer Organisation klicken und man wird auf die Einzelansichtsseite geleitet. Wenn man als admin eingeloggt ist kann man sie jetzt auch im nicht bestätigten Zustand ansehen.
