### ISSUE TITLE
config/locales refactoring

### ISSUE THREAD

**Issue by KonstantinKo** [clarat-org/clarat#272]
Ich hab für ein anderes Projekt einen style guide entwickelt, mit dem die Platzierung und Nutzung von Übersetzungsstrings einheitliche und nachvollziehbar ist. Den würde ich auch gerne bei uns anwenden. Dafür müssen viele locales umgezogen werden.

**Comment by Twiek** [comment]
Gibt es den Styleguide auch in schriftlicher Form? Wenn ja, dann her damit.

**Comment by KonstantinKo** [comment]
Hab ich hinzugefügt. Siehe https://github.com/clarat-org/clarat/tree/develop/config/locales
