### ISSUE TITLE
Such-Refactoring zu JS

### ISSUE THREAD

**Issue by KonstantinKo** [clarat-org/clarat#273]
Für #245 ist bereits die Suchergebnisseite asynchroner geworden und nutzt nun immer ajax anfragen. Für weitere Performance-Verbesserungen sollte die Suchausführung komplett auf JS umgezogen werden, da man so die request Zeit an den clarat Server sparen kann. Sehr low prio bis Performance der Suchergebnisse wieder über Richtwerten liegt.

**Comment by Twiek** [comment]
Krass!

Gibt aber scheinbar noch Fehler. So wird bei mir in der Suchergebnisliste weder Name noch Adresse angezeigt:

![bildschirmfoto 2015-07-15 um 10 44 23](https://cloud.githubusercontent.com/assets/432388/8694365/b2dec9c8-2ade-11e5-8d6e-66facff8993a.png)

Habe es dann auch noch mal auf staging gepushed, da sieht es genauso aus. Musst mir bei Gelegenheit dann auch noch mal zeigen wo/wie ich das debugge.

**Comment by KonstantinKo** [comment]
1. branch wechseln
2. datenbank löschen und wieder aufsetzen
3. rake db:fake (sollte automatisch reindexen)
4. rake cache:clear
5. server neustarten
5.5 wenns noch nicht klappt: rails s -> Offer.clear_index!; Offer.reindex

Wenns dann noch nicht klappt, mir nochmal zuweisen ;)

**Comment by KonstantinKo** [comment]
Achso und debugging in assets/javascripts/search (Ist ne js "Micro-App" die in unserer läuft. Hab schon ein bisschen was in README und Kommentare geschrieben aber das werd ich noch ausbauen. Allgemein hab ich mir vorgenommen, die Konzepte dort mal zu einem Mini-JS-Framework auszubauen)
