### ISSUE TITLE
HQ verpflichtend für Organisationen

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#275]
Organisationen sollen künftig zwingend ein Headquarter zugewiesen haben.

**Comment by jjungle** [comment]
![orga](https://cloud.githubusercontent.com/assets/11425826/7535990/841e9614-f58b-11e4-9ade-b0e38709204b.PNG)

**Comment by jjungle** [comment]
Bitte zusätzliche Bedingung einbauen: Jede Orga muss 1 HQ besitzen, darf jedoch gleichzeitig nicht mehr als 1 HQ besitzen.

**Comment by Twiek** [comment]
See also https://github.com/clarat-org/clarat/commit/2cbe2c10c89e0d87291ad9bdfca4129c7467fcf8.
