### ISSUE TITLE
Suchergebnisseite springt und placeholder wechseln 'live'

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#277]
Wenn ich auf der Suchergebnisseite nach ganz unten scrolle, dort z.B. das unterste Ergebnis anlicke, dann den Backbutton benutze kommte ich zwar zuerst direkt wider dorthin wo ich herkam (Suchergebnisseite ganz unten), nach ca. 2 Sekunden springe ich aber nach oben und sehe wie die placeholder im Suchfeld durchwechseln.

**Comment by KonstantinKo** [comment]
läuft sowieso auch anders mit ajax suche (#245), bitte schauen ob immernoch ein problem. konnte es selbst nicht nachvollziehen.
