### ISSUE TITLE
Inkonsistente Ergebnisse bei der Kategoriensuche

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#280]
Ich klicke auf der Startseite auf z.B. 'Familie'. Auf der Suchergebnisseite (http://developer.clarat.org/angebote?search_form%5Bcategories%5D=Familie&search_form%5Bquery%5D&search_form%5Bsearch_location%5D=Berlin%2C%20Deutschland&search_form%5Bgenerated_geolocation%5D=52.5200066%2C13.404954) erscheinen dann (Stand 13.5.) 224 Vor Ort Angebote:

![bildschirmfoto 2015-05-13 um 12 05 44](https://cloud.githubusercontent.com/assets/432388/7608299/6f9145bc-f968-11e4-8afc-b33f8a9697dc.png)

In der Seitenleiste stehen unter Familie aber 170 Angebote. Klicke ich dort noch mal auf die Kategorie Familie erscheinen dann auch nur 170 Vor Ort Angebote. 

![bildschirmfoto 2015-05-13 um 12 06 40](https://cloud.githubusercontent.com/assets/432388/7608339/cdc39144-f968-11e4-8570-7fbea1550752.png)

Erwartung ist, dass ein Klick auf 'Familie' auf der Startseite direkt zu den 170 Angeboten führt.

**Comment by KonstantinKo** [comment]
ändert sich sowieso mit #245
