### ISSUE TITLE
Ausschluß falscher Suchergebnisse

### ISSUE THREAD

**Issue by JulianJung** [clarat-org/clarat#282]
In manchen Angeboten wird bspw. erwähnt das Drogen dort verboten sind. Sucht ein User jetzt nach Drogen so landet er unter Umständen bei diesem Angebot.

Vornehmlich wird dieses Problem bei Drogenbezogenen Suchbegriffen auftreten.

**Comment by Twiek** [comment]
Kannst Du hier mal 1-2 konkrete Beispiel verlinken.

**Comment by Twiek** [comment]
Alternativ das Issue löschen.

**Comment by JulianJung** [comment]
http://www.clarat.org/family/angebote/betreuung-in-einer-eigenen-wohnung-fuer-jugendliche-ab-15-jahren

http://www.clarat.org/family/angebote/betreute-wohngruppe-bei-krisen-in-der-familie-fuer-selbststaendigere-maedchen-10555

Allerdings kam das Problem am 13. May 2015 auf und man findet immer noch sehr wenige Fälle in denen das der Fall ist. Sehe hier momentan keinen Handlungsbedarf mehr.
