### ISSUE TITLE
Beta-Banner and fixed Suchfeld on mobile

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#285]
Der Beta-Banner soll auch auf Mobilgeräten angezeigt werden (Vgl. https://github.com/clarat-org/clarat/commit/567295e23403c26d4852e3e42852208cf4810e24), allerdings nicht mitscrollen. Dies führt aktuell dazu, dass über der Suchleiste eine Lücke ergibt sobald man scrollt:

![bildschirmfoto 2015-05-15 um 11 51 51](https://cloud.githubusercontent.com/assets/432388/7650674/163421aa-faf9-11e4-90ea-ff3507adae85.png)

Diese sollte verschwinden.

**Comment by Twiek** [comment]
@KonstantinKo: Falls mit nennenswertem Rechercheaufwand verbunden bitte an Marcus delegieren.

**Comment by KonstantinKo** [comment]
Ich glaube da kann marcus tatsächlich schneller helfen.

**Comment by marcus-herrmann** [comment]
Hotfix in db6a3fa

**Comment by Twiek** [comment]
Sorry, unklar ausgedrückt. Der Beta-Banner soll verschwinden, sobald man scrollt, nur die Suchleiste bleibt fix

**Comment by marcus-herrmann** [comment]
Korrektur hierzu findest du in https://github.com/clarat-org/clarat/commit/5fd5c281cbeec493e1c33175dd69d89b5f1679ab / eigenem Fix-Branch fix/285-sticky-search-while-banner-scrolls

**Comment by Twiek** [comment]
Funktioniert nach merge nicht mehr. Bitte noch mal checken und insbesondere die mobile about page berücksichtigen.

**Comment by marcus-herrmann** [comment]
Note to self: Berücksichtigen, sobald #420 in develop gemergt ist

**Comment by marcus-herrmann** [comment]
Der Fix-Branch war extrem veraltet (Juni), ein merge des aktuellen develop-branches darein wäre abenteuerlich. Deswegen habe ich einen neuen branch erstellt (https://github.com/clarat-org/clarat/tree/fix/285-NEW-sticky-search-while-banner-scrolls) und die Essenz des Fix quasi manuell cherry picked (manuell: weil Refactoring in ActiveScript nötig wurde).

PR incoming

**Comment by NilsVollmer** [comment]
Zwei Dinge dazu: bei schmalen Devices, auf denen der Beta Banner aufgrund der Textlänge ein Zweizeiler wird (z.B. iPhone5) wird nicht die tatsächliche Höhe des Banners beachtet und so kommt es beim scrollen zu einem optischen Sprung der Suchleiste. Das ist aber mehr eine Kleinigkeiten.

Schlimmer finde ich die Uneinheitlichkeit bei den erweiterten Suchoptionen: der Button scrollt mit der Suchleiste mit aber die Optionen (wenn ausgeklappt) bleiben oben hängen. Man sollte wohl beides mitscrollen lassen, was aber bei ausgeklappten Suchoptionen zu sehr viel verlorenem vertical Space führen würde, oder auch den Button nicht mitscrollen lassen.

**Comment by marcus-herrmann** [comment]
Noch mal neu gebaut für #569 / `feature/family-refugees`
