### ISSUE TITLE
Lokale Onlineangebotssuche hängt

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#287]
Wenn ich lokal suche und dann den Filter "Telefon- und Onlineberatungen" setze lädt die Seite ohne jemals Ergebnisse anzuzeigen:

![bildschirmfoto 2015-05-15 um 16 36 31](https://cloud.githubusercontent.com/assets/432388/7655106/bf8da01e-fb21-11e4-8422-8028f633d673.png)

**Comment by KonstantinKo** [comment]
Tritt bei mir nicht auf, weder lokal noch auf staging/production. Bitte mehr Info, wie der Fehler gefunden werden kann.

Falls es lokal auftritt, bitte auch die Fehlermeldung der AJAX-Anfrage mit posten. Ist nun leicht sichtbar in der JS console.
