### ISSUE TITLE
Karte zurück in den Suchergebnissen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#289]
Bitte Vorschlag machen wo diese angezeigt werden könnte (tendenziell unter den Kategorien), vor allem aber wie man diese vergrößern kann (wird die Liste dann z.B. nach unten 'geschoben')?

**Comment by marcus-herrmann** [comment]
Idee:

Nachdem eine vergrößerte Karte nur schwer nachvollziehbar ins bestehende Layout integriert werden kann (anders als bei z.B. http://www.yelp.de/search?find_desc=&find_loc=Berlin&ns=1), kommt sie in ein großes Overlay. Die Vergrößerung erreicht man aus der Zwischenüberschrift der Vor Ort Angebote (denn nur die können auf einer Karte ausgegeben werden), oder aber durch einen Button unter der kleinen Karte in der Sidebar (bewusst redundant)

![fake_map_on_offersindex](https://cloud.githubusercontent.com/assets/505181/7855989/f62a22ce-0525-11e5-877b-0f3d7e80671f.png)

![fake_big_map_on_offersindex](https://cloud.githubusercontent.com/assets/505181/7855967/ce752aa8-0525-11e5-8f05-045bc5efbd99.png)

**Comment by marcus-herrmann** [comment]
Frontend soweit bereit, habe aber keine Markerdaten, will ungetestet noch keinen PR stellen

**Comment by Twiek** [comment]
Funktioniert in der Tat noch nicht (siehe hier: http://clarat-staging.herokuapp.com/angebote?utf8=%E2%9C%93&search_form%5Bquery%5D=&search_form%5Bsearch_location%5D=Berlin%2C+Deutschland&search_form%5Bgenerated_geolocation%5D=52.5200066%2C13.404954&search_form%5Bcategory%5D=).

**Comment by marcus-herrmann** [comment]
Das liegt aber daran, dass noch keine Marker aus dem Backend kommen, deswegen ist das Issue bei Konstantin

**Comment by KonstantinKo** [comment]
So, Markerdaten werden jetzt wieder ausgegeben. Das Ganze ist aber noch nicht ausreichend konzeptioniert:

Geokoordinaten werden natürlich erst mit den anderen Suchergebnisdaten, also innerhalb des nachgeschobenen AJAX-Requests, geholt und ändern sich auch mit jeder AJAX-Suchanfrage. Für die Ergebnisse dieser Suchanfrage hatten wir bisher immer einen abgetrennten Bereich, der der sich auch ausgraut und nachlädt. Nun ist die Map aber außerhalb dieses Bereichs.

Dadurch passieren unschöne Dinge : Es gibt eine Überschrift und einen Knopf in der Seitenleiste, die aber noch nichts tun bis die Suchanfrage fertig ist weil erst dann die Karte richtig gebaut werden kann. Interaktion mit den Suchergebnissen ist visuell ausgeschaltet während eine Suchanfrage läuft. Aber die Karte, die ja auch Teil der Suchergebnisse ist, ist davon nicht betroffen. Diese müsste also auch ausgegraut werden, bis die neuen Ergebnisse da sind. Auch muss darauf geachtet werden, was passiert, wenn jemand schnell genug die große Karte öffnet nachdem die neue AJAX-Suchanfrage in Auftrag gegeben wurde.

Ich habe zumindest eingerichtet, dass die Karte mit jedem abgeschlossenen Suchprozess neu initialisiert wird und damit auch neue Markerdaten angezeigt werden.

Der Zoom passt sich natürlich auch noch nicht von selbst an, aber das hat nichts mit dem oben genannten zu tun.

Weiteres TODO: Wenn mehrere Suchergebnisse an demselben Ort sind gab es vorher ein Popup mit Link auf eine spezielle Suche die nur diese Angebote angezeigt hat. Bin mir nicht sicher, ob das immer noch so funktioniert. Am Besten mir am Ende nochmal zuweisen.

**Comment by marcus-herrmann** [comment]
@Twiek , was meinst du dazu? (Können wir morgen besprechen)
