### ISSUE TITLE
Mehr/Weniger Filter anzeige buggy

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#294]
Nach Nutzung des Filters (z.B. Umstellung auf Onlineangebote) wird das Filterfeld wieder zusammengeklappt, allerdings wird der 'Aufklapptext' ('Weniger Filter anzeigen') nicht angepasst:

![bildschirmfoto 2015-05-21 um 11 38 01](https://cloud.githubusercontent.com/assets/432388/7745805/2ac32bf2-ffae-11e4-956c-3ff3129c1c35.png)

**Comment by marcus-herrmann** [comment]
PR gestellt: #303
