### ISSUE TITLE
Gleichzeitiges verlinken von PDF und Webseite nicht möglich

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#296]
Bildet man bei der Angebotsaufnahme eine Website (OWN) + PDF (OWN) ab, so wird nur eins davon angezeigt.

**Comment by Twiek** [comment]
Sollte das denn anders sein. Gibt es denn wirklich mehrere 'Startseiten' für ein Angebot, oder sollte man sich nicht für eine entscheiden. Tendiere hier eher max. 1 Website (own) zuzulassen.

**Comment by jjungle** [comment]
3 Gründe für mehrere "Startseiten":

1. Ein mobilier User hat so die Wahl zwischen PDF u. Website
2. Nähere Informationen über den Anbieter können besser über die Website eingeholt werden.
3. Aktualität: Eine flyerartige PDF wird vermutlich seltener aktualisiert als eine Website. Besonders in Hinsicht auf kurze Hinweise wie: Unser Büro ist jetzt im 10.Stock, wir bauen gerade um oder sonstiges.
