### ISSUE TITLE
Duplizieren von Angeboten anpassen

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#300]
Beim duplizieren von Angeboten soll alles außer Location, Contact people und Encounter dupliziert werden.

**Comment by Twiek** [comment]
Just to make sure: 

In Zukunft sollen encounter und location nicht mehr dupliziert werden (werden sie aktuell), dafür sollen name, organization, language_filter, audience_filter, age_filter, websites und keywords dupliziert werden, richtig?

**Comment by jjungle** [comment]
Korrekt.
+ Die alten Duplizierungen (Description,Next steps,Categories etc.) sollen natürlich auch beibehalten werden.

**Comment by KonstantinKo** [comment]
@jjungle Encounter hat keine Option für "nichts", es nicht zu duplizieren ist also schwer. Oder meinst du damit, dass alles beim duplizieren auf "Personal" gesetzt werden soll? Oder etwas anderes?

**Comment by KonstantinKo** [comment]
Auch muss man vorsichtig sein mit "alles duplizieren". Von bspw. completed und approved war ja keine Rede, heißt dass die auch mit übernommen werden würden. Kann mir nicht vorstellen, dass das so gewollt ist.
Ich hab jetzt mal was verändern. Am Besten anschauen und sehen, ob es so gemeint war.
