### ISSUE TITLE
Neue Encounter für Online Angebote

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#302]
Online Angebote werden künftig in Email-, Chat- und Forum-Angebote gesplitted.Hierzu müssen fürs Backend neue Encounter erstellt werden. Im Frontend müssten anschließend neue Fähnchen/Stamps erstellt werden.

**Comment by Twiek** [comment]
@jjungle: Was soll aus den Angeboten werden, die bisher den Encounter 'Online' haben? Wer geht die noch mal durch? Sollen die z.B. auf 'unapproved' gesetzt werden?

**Comment by jjungle** [comment]
Die bleiben approved. Ich gehe sie durch.

**Comment by Twiek** [comment]
Ok, also 'online' wird gestrichen und dafür gibt es dann 'email', 'chat' und 'forum'.

@Konstantin: Müssen wir die 'presence: true' validation deaktivieren bis Julian die neuen Encounter händisch vergeben hat?

**Comment by KonstantinKo** [comment]
@jjungle Neue Encounter sind jetzt online und können (sollten) durchgegangen werden. Ich schicke dir eine Liste per Email.

Solange nun noch Angebote ohne Encounter vorhanden sind, wird es Anzeige-Probleme mit den Fähnchen in der Suche geben.

Wenn alle durchgegangen sind bitte nochmal mir zuweisen. Dann gibts nen reindex, cache clear, und es sollte funktionieren.

**Comment by jjungle** [comment]
Sollte jetzt keine approved Angebote ohne Encouter mehr geben.
