### ISSUE TITLE
Selbst erstellte Angebote selbst approven

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#309]
Selbst erstellte Angebote sollen künftig auch selbst approved werden können.

**Comment by Twiek** [comment]
Mit Nicole besprochen? widerspricht ja dem 4 Augen Prinzip.

**Comment by jjungle** [comment]
War gewünscht und besprochen, ist aber für den neuen Approve-Prozess nicht mehr gewünscht.
