### ISSUE TITLE
Aufzeigen verwandter Angebote in der Angebotsansicht

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#311]
In einem Angebote kann ich 'verwandte' Angebote hinzufügen. Die Auswahlmöglichkeiten werden im Adminbereich wie folgt angezeigt: 'ID (Title)'.

In einem zweiten Schritt (Issue wird noch angelegt) werden Links auf diese verwandten Angebote im Angebot selbst angezeigt.

**Comment by KonstantinKo** [comment]
@jjungle Wichtige Frage: Gehen Angebotsverwandtschaften in beide Richtungen oder nur in eine?

Wenn Angebot A mit Angebot B verwandt ist, ist B dann auch im selben Maße mit A verwandt?

**Comment by KonstantinKo** [comment]
Hm, Bidirektionalität geht sowieso nicht so einfach.

Ich habe jetzt eine Verbindung geschrieben, sodass Offer mehrere andere related_offers haben kann. Das kann auch im Admin Interface gesetzt werden.
Bei dem verwandten Angebot tauchen dieses dann jedoch in einer Extra-Spalte auf, die ich jetzt mal "inverse related offers" genannt habe

Heißt A hat eine Liste von Angeboten, mit denen es verwandt/ähnlich ist. In dieser Liste ist B. Es hat auch eine Liste von Angeboten, mit die mit diesem verwandt sind. Dort ist B nicht drin.
Bei B ist in der ersten Liste nichts, in der zweiten ist A zu sehen.

Falls das Problematisch ist, mich nochmal ansprechen.

**Comment by jjungle** [comment]
vorerst on hold

**Comment by KonstantinKo** [comment]
I'll wait …
![tyrion-waiting](https://cloud.githubusercontent.com/assets/779660/9523003/2080dd0c-4cd8-11e5-9ed2-914eddcdc9c7.gif)

Beachte bitte, dass es immer mehr Anpassungen benötigt um den vorhandenen Code ins Projekt einzubinden, je länger wir warten. Irgendwann kann man dann auch gleich von vorne anfangen.
