### ISSUE TITLE
Adressdarstellung von Organisationen anpassen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#312]
Die Organisationsansicht soll so angepasst werden, dass die "Wo"-Box eine Art Briefkopf inkl. der zentralen Kontaktmöglichkeiten enthält. (Siehe Screenshot).

![841e9614-f58b-11e4-9ade-b0e38709204b](https://cloud.githubusercontent.com/assets/432388/8062238/f90e8ac2-0ece-11e5-82cc-28cc9e9033f4.png)

**Comment by jjungle** [comment]
Alle HQs mit approvten Orgas haben jetzt, sofern vorhanden, eine E-Mail und/oder Telefonnummer zugewiesen bekommen.

**Comment by NilsVollmer** [comment]
So in etwa? 

![image](https://cloud.githubusercontent.com/assets/1733220/9877123/31a61ccc-5bbb-11e5-8c0c-78f56c696b99.png)

**Comment by NilsVollmer** [comment]
@Twiek Habe meinen Ansatz mal mit dem branch adressdarstellung-orgas gepublished.
