### ISSUE TITLE
Anzeige von Angeboten die über Nacht laufen

### ISSUE THREAD

**Issue by JulianJung** [clarat-org/clarat#314]
Wenn Angebote über Nacht laufen und wir dies im Back-End so eintragen, sollte dies im Frontend wie im Screenshot angezeigt werden.

**Comment by jjungle** [comment]
![anzeige](https://cloud.githubusercontent.com/assets/11425826/8086565/591a52a8-0f96-11e5-9a3a-d8114e950125.JPG)

**Comment by Twiek** [comment]
Bin ich dagegen. Montag 22:00 - 10:00 Uhr sieht einfach falsch aus. Da brauchen wir meiner Meinung nach eine bessere Lösung. In dem Fall fände ich z.B. einen reinen Fokus auf die opening_specifications gut ('Die Notschlafstelle ist jeden Tag von 22:00 Uhr bis 10:00 Uhr des Folgetages geöffnet').

Eventuell wäre es dann sinnvoll die Zeiten zwar auch noch mal einzugeben, aber nicht anzuzeigen (per zu implementierenden Häkchen). Lass uns noch mal drüber sprechen.

**Comment by jjungle** [comment]
Habe es nochmal im Elfer-Rat besprochen. Da war die deutliche Mehrheit dafüres wie im Screenshot abzubilden. Vielleicht mit A/B Usertests ausprobieren? Die Anzahl der Angebote die über Nacht laufen ist ohnehin relativ gering.

**Comment by Twiek** [comment]
Kam jetzt seit nem Jahr nicht mehr auf. Zeit es zu löschen bis sich das ändert?

**Comment by JulianJung** [comment]
Ja!
