### ISSUE TITLE
Zahl hinter der Kategorie fehlerhaft

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#315]
Wenn ich auf der Startseite auf 'Akute Krise' klicke erscheinen 2 Ergebnisse (1 mal Vor-Ort, ein mal Online), aber in der Kategorieliste wird '(0)' angezeigt.
![bildschirmfoto 2015-06-11 um 12 22 11](https://cloud.githubusercontent.com/assets/432388/8104856/85546716-1034-11e5-9554-ccc736dbdf35.png)

**Comment by KonstantinKo** [comment]
Das Problem hat sich scheinbar mit einem reindex behoben.
