### ISSUE TITLE
Vor-Ort und Onlineangebote zusammenzählen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#316]
Die Zahl hinter den Kategorien sollte die Summe aus Vor-Ort und Onlineangeboten sein:

![bildschirmfoto 2015-06-11 um 13 24 00](https://cloud.githubusercontent.com/assets/432388/8105919/7e80e2da-103d-11e5-8ded-4c1e574fc24a.png)

**Comment by Twiek** [comment]
Insgesamt scheinen die Zahlen aktuell an verschiedenen Stellen nicht zu stimmen:

![bildschirmfoto 2015-06-18 um 15 10 58](https://cloud.githubusercontent.com/assets/432388/8232007/c2047c1c-15cc-11e5-8792-13c055ff266c.png)

**Comment by KonstantinKo** [comment]
@Twiek 
Dafür müssen wir dann aber noch eine fünfte Suchquery pro Suchanfrage schicken. Also, du willst ja nicht nur dass diese eine Zahl (die 262) richtig ist, sondern auch alle andereren in den Klammern. Um die zu bekommen machen wir ja nun schon eine vierte Query um allein die Zahl für Vor-Ort-Angebote zu bekommen. Wir wollen also auch noch eine für Telefon- und Onlineangebote um diese dann zusammenrechnen zu können, ja?

Mit der neuen Suche sollte das zwar von der Geschwindigkeit keine große Rolle mehr spielen aber meine Güte ... wie viele Queries und Komplexität kann und denn so eine Zahl wert sein?

**Comment by KonstantinKo** [comment]
Gute Nachrichten:
Wir müssen zwar 5 queries machen, aber 3 davon (die zwei um Kategorieanzahlen zu bekommen und die Abfrage, ob es Angebote in der Nähe gibt) müssen nur gemacht werden, wenn der gesuchte Ort sich verändert.

Ein Vorteil der neuen JS Suche, da wir ja nicht alles für jede Anfrage neu laden müssen sondern in memory behalten können.
