### ISSUE TITLE
Rework definitions

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#318]
Definition müssen überarbeitet werden um die folgenden Anforderungen zu erfüllen:

- [x] Deine Definition verfügt über mehrere Keys welche man kommagetrennt eingeben kann (z.B. 'Legasthenie, Legastheniker').

- [x] Taucht in der Description eines Angebots einer der Keys auf, so wird dieser mit der Explanation belegt (per Mouseover, wie gehabt). Sollten von einer Defintion allerdings mehrere Keys in einer Angebotsdescription auftauchen, so wird nur der erste Key beim ersten Auftreten mit einer Explanation belegt.

Beispiel: 'Ein Legastheniker hat Legasthenie'. Hier würde nur das Wort 'Legastheniker' mit einer Explanation belegt (für den User sichtbar), 'Legasthenie' allerdings nicht.

**Comment by Twiek** [comment]
Sicherstellen, dass eine Definition max. 1 mal pro Angebot angezeigt wird (also wenn das Wort Legasthenie 2 mal vorkommt wird es nur nach/beim ersten Auftauchen mit einer Definition ausgestattet).

**Comment by KonstantinKo** [comment]
done (auch wenn's mir nicht zugewiesen war)

**Comment by Twiek** [comment]
So, habe jetzt auch den zweiten Teil des Issues erledigt, aber es fühlt sich nicht gut an... Bitte einmal einen kritischen Blick auf https://github.com/clarat-org/clarat/compare/feature/318_rework_definitions werfen.
