### ISSUE TITLE
'Zuletzt aktualisiert' Hinweis auf die Angebotsseite

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#321]
Bitte einen tendenziell dezenten Verweis 'Zuletzt aktualisiert am 25. Mai 2014' auf die Angebotsseite integrieren (Screenshot/Design reicht, Logik kann ich übernehmen).

**Comment by marcus-herrmann** [comment]
![streetwork fur jugendliche am alexanderplatz clarat 2015-06-25 16-43-46](https://cloud.githubusercontent.com/assets/505181/8357383/f6b49bde-1b5a-11e5-84f3-6188df1e22cd.jpg)

Ich denke, so ein kleiner Timestamp genügt (Icon ist aus Font Aweseome, `<i class="fa fa-clock-o"></i>`)

**Comment by Twiek** [comment]
Bitte umplatzieren nach rechts unten (tendenziell in der Nähe zu 'Fehler gefunden')

**Comment by marcus-herrmann** [comment]
So?

![bildschirmfoto 2015-08-20 um 15 58 15](https://cloud.githubusercontent.com/assets/505181/9385098/b40dc79e-4754-11e5-9286-ff0902874427.jpg)

**Comment by Twiek** [comment]
Ja.

**Comment by Twiek** [comment]
Fast, würde es über 'Hast Du einen Fehler... ' platzieren.

**Comment by marcus-herrmann** [comment]
Ich baue es ohnehin gerade nicht (siehe oben "Screenshot/Design reicht, Logik kann ich übernehmen"). Platzierst du die Timestamp-Ausgabe im Template an dieser Stelle und ich gestalte sie dann wie hier vereinbart?
