### ISSUE TITLE
Googel-Translate Link in 'schön'

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#322]
Hier bitte Vorschläge machen und checken was möglich ist. Dabei folgende Wünsche berücksichtigen:

- [ ] Neben Deutsch (nur) noch die folgenden Sprachen anbieten: Englisch, Französisch, Arabisch, Türkisch, Polnisch, Russisch
- [ ] Statt mit Worten (z.B. 'Englisch') überall mit Fahnen arbeiten
- [ ] Möglichst prominente Platzierung (wenn wir eine Hauptnavigation hätten, dann da (Vgl. www.betterplace.org)
- [ ] Bei Klick auf das Dropdown erscheint ein Overlay mit einem kurzen Warnhinweis in verschiedenen Sprachen.

**Comment by marcus-herrmann** [comment]
Rechercheergebnisse in eigenem Feature-Branch: https://github.com/clarat-org/clarat/compare/feature/322-prettier-gt-widget

* Einschränkungen auf die Sprachen bereits gestern durch dich geschehen
* Hier wirds problematisch. Ich komme zwar [mit einem Trick](https://github.com/clarat-org/clarat/commit/edb7a50c5b2cf3f179bdf1176e83af77e49e1d3a#diff-60fa2aa78ab242c044301b0ffcff4596R56) via CSS in den iFrame mit der Sprachenauflistung (das Popup), aber das HTML darin verteilt keine Klassen/IDs, die darauf schließen lassen, welches span welche Sprache ist (sodass ich den Text verstecken und durch ein Flaggen-Hintergrundbild ersetzen kann). Bleibt mir nur das Zählen der klickbaren divs (siehe: https://github.com/clarat-org/clarat/commit/edb7a50c5b2cf3f179bdf1176e83af77e49e1d3a#diff-b67be160cff8be859abc7ba62767fa3dR21 , testweise einfach eingefärbt). Wenn man aber hier eine Sprache auswählt, z.B. Englisch, ändert sich - logischerweise - der Inhalt des Popups, und ein zählbasiertes Vorgehen funktioniert nicht mehr, Flaggen und Textlinks wären falsch zugeordnet (z.B. man klickt auf die türkische Flagge, und landet in einer polnischen Übersetzung). Die Sache erklärt sich schriftlich sehr schwer. **tldr: Das HTML des Popups mit den Sprachlinks gibt keine Eindeutige Flaggenzuordnung her. Da es von Google erzeugt wird, kann ich es nicht ändern.**
* Gestalterisch: Oben rechts im Body (wenn wir mit Flaggen hätten arbeiten können) absolut positioniert, egal ob mit oder ohne Meta-Banner
* Recherche hat kein JS-Event ergeben, auf dass ich "hören" kann (Moment des Wechsels von Deutsch in eine andere Sprache), um einen Warnhinweis zu erzeugen. Dann hätte ich aber mit unseren typischen JS-Modal (z.B. Betabanner, große Karte) gearbeitet. Aufdringlich, aber dann wäre die Botschaft ("maschinelle Übersetzung!") auch angekommen

**Comment by Twiek** [comment]
Ok, sieht schon nicht schlecht aus. Folgende Fragen/Bitten:

1. Gibt es ein JS Event bzw. eine Möglichkeit das man hören kann, wenn man auf den Link klickt oder auch nur mit der Maus drüber fährt (class="JS-tooltip" oder so)? Wenn ja, dann dort bitte den folgenden Text integrieren: "Hier kannst du dir clarat in andere Sprachen übersetzen lassen. Die Übersetzungen werden automatisch gemacht. In solchen Übersetzungen gibt es oft sprachliche Fehler. Es kann also sein, dass etwas komisch klingt. Schau dann lieber noch einmal in den deutschen Text."

2. Aktuell sieht der Link als würde er eher schlecht als recht zu Impressum und Co gehören. Könntest Du das bitte ändern und ihn gegenüber den anderen gerne hervorheben (oder anderweitig positionieren)?

**Comment by Twiek** [comment]
Just to make sure: Der Artikel hilft auch nicht weiter, oder: http://stackoverflow.com/questions/10486833/implementing-google-translate-with-custom-flag-icons

**Comment by marcus-herrmann** [comment]
@Twiek Besprechen wir am 22. persönlich wie hier der aktuelle Stand ist? Habe Issue wunschgemäß bis hierhin erstmal zurückgehalten

**Comment by marcus-herrmann** [comment]
@Twiek : Laut @NilsVollmer gibt es eine Verlagerung der Übersetzungen vom Front- ins Backend. Das macht dieses Ticket irrelevant, vermute ich?
