### ISSUE TITLE
Ajax-Preloader Offer Listing in IE9 defekt

### ISSUE THREAD

**Issue by marcus-herrmann** [clarat-org/clarat#323]
![bildschirmfoto 2015-06-17 um 10 14 06](https://cloud.githubusercontent.com/assets/505181/8202383/b358a7d6-14d9-11e5-901f-b237086c6bc1.png)

IE9 bleibt in diesem Zustand stecken, Result Listing damit so gut wie nicht nutzbar. <s>In welchem Commit wurde das eingebaut (muss irgendwann im Mai gewesen sein)?</s>

**Comment by marcus-herrmann** [comment]
IE9 kann kein history.pushState: http://caniuse.com/#search=pushstate, daran scheitert es.

Lässt sich Ajax.coffee an dieser Stelle refaktorieren?

**Comment by KonstantinKo** [comment]
Bitte Bugs immer direkt in die TODO Pipeline schieben.

**Comment by KonstantinKo** [comment]
So, die 1-Character-Lösung war jetzt erstmal, einfach history push auszuschalten, wenn die Funktionion halt nicht vorhanden ist. Probier das mal bitte aus, da es IE9 für mac nicht gibt kann ich das nicht wirklich testen. Du benutzt parallels, oder?

Nun ist halt die Frage ob das so reicht. Der Back-Button funktioniert dann natürlich für IE9 nicht wirklich... ist sicherlich eine Philosophiefrage wie viel wir veralteten Technologien wirklich gerecht weren müssen. History.js ist schon wieder ein Batzen Code, außerdem war es die Hölle als ich das letzte mal versucht habe das mit Turbolinks zu vereinen.

**Comment by marcus-herrmann** [comment]
Ja, Parallels und ja, klappt, hab dank. Ich wäre, was alte Browser angeht, eh dafür, so etwas wie http://browser-update.org/ einzubinden
