### ISSUE TITLE
Refactor #325

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#326]
https://github.com/clarat-org/clarat/pull/325

Neben Code-Feinheiten u.a. checken inwiefern es eine Möglichkeit gibt den teilweise zu vielen Platz unter den Texten zu umgehen ohne dass das 'System' (Grid?) kaputt geht (weniger Team-Mitglieder in einer Reihe angezeigt werden als sollen):

![bildschirmfoto 2015-06-18 um 11 25 59](https://cloud.githubusercontent.com/assets/432388/8228146/e031f0e0-15ac-11e5-9d33-569f108d0ce9.png)

vs.

![bildschirmfoto 2015-06-18 um 11 27 26](https://cloud.githubusercontent.com/assets/432388/8228166/0c25c186-15ad-11e5-97e1-1a210c72a027.png)

**Comment by marcus-herrmann** [comment]
Anbei auf dem dezidierten Featurebranch zu #325 ein Versuch, dem Floating Herr zu werden - in manchen Breiten sind die Container etwas größer als sie sein müssen, aber nicht mehr so extrem wie im Screenshot (da der Branch recht alt war, hoffe ich bei dem Merge von develop in ihn keine Änderungen an den SCSS-Dateien durch euch überschrieben zu haben - gesonderter/teils manueller Merge Commit).

**Comment by Twiek** [comment]
Just to make sure: Was meinst Du mit 'Anbei'? Gibt es hier noch irgendwas das nicht in develop gemerged wurde?

**Comment by marcus-herrmann** [comment]
Feature Branch redesign about Page müsste das sein. Glaube ich nicht in develop, bin aber gerade nur am Smartphone und kann nicht checken
