### ISSUE TITLE
Blog: Menü braucht einen anderen Z-Wert!?

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#328]
![bildschirmfoto 2015-06-19 um 13 25 24](https://cloud.githubusercontent.com/assets/432388/8252486/beab29fc-1686-11e5-8e28-a0f21a516dc2.png)

**Comment by marcus-herrmann** [comment]
Als hotfix auf master und äh... deployed

**Comment by Twiek** [comment]
Bei mir funktioniert es nach wie vor nicht, oder habe ich deployed falsch verstanden?

![bildschirmfoto 2015-06-19 um 15 51 23](https://cloud.githubusercontent.com/assets/432388/8254732/1d3ff4de-169b-11e5-87d8-68d6e5022ac8.png)

**Comment by marcus-herrmann** [comment]
Ich hatte meinen Fix eingespielt, er funktionierte auch. Vermute stark, dass wir unsere Änderungen gegenseitig überschrieben haben. Traue mich deswegen nicht, ihn wieder einzuspielen, da ansonsten deine Änderungen weg wären. Klären wir am Donnerstag.
