### ISSUE TITLE
Responsive Schriftgröße

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#330]
Habe gerade die Schriftgröße im Blog etwas reduziert (auf 1em -> nicht meine Idee...). Eventuell bin ich dabei übers Ziel hinausgeschossen, eventuell ist folgender Wunsch aber auch davon unabhängig:

In der mobilen Ansicht wirkt die Schrift in der Artikeleinzelansicht sehr klein. Hier bitte doch wieder etwas größer werden (nur für mobile Ansicht, nicht für Desktop):

![bildschirmfoto 2015-06-19 um 15 53 08](https://cloud.githubusercontent.com/assets/432388/8254785/8a9042be-169b-11e5-8a54-2fef8bcef678.png)

**Comment by marcus-herrmann** [comment]
Mal geändert, deployed. Passt es so bereits?

**Comment by Twiek** [comment]
Nope. Überschriften tendenziell zu groß, eigentlicher Text tendenziell zu klein. Überschriften sollten wenn möglich auf max. 2 Zeilen Platz finden.

Screenshot vom Nexus 5, sieht aber z.B. auf dem LG G3, Samsung Galaxy S4 genauso aus:

<img width="186" alt="bildschirmfoto 2015-07-03 um 11 00 51" src="https://cloud.githubusercontent.com/assets/432388/8496116/016e47f0-2173-11e5-9d6e-57d7a79743d0.png">

Bitte in der nächsten Runde gleich nen Screenshot anhängen.

**Comment by marcus-herrmann** [comment]
<img width="409" alt="bildschirmfoto 2015-10-13 um 10 38 43" src="https://cloud.githubusercontent.com/assets/505181/10449854/99da430e-7196-11e5-8f7d-7222312b2a74.png">

<img width="419" alt="bildschirmfoto 2015-10-13 um 10 39 27" src="https://cloud.githubusercontent.com/assets/505181/10449873/b740c2ba-7196-11e5-90b9-47924019a43e.png">

Screenshots von Live, Änderungen also deployed
