### ISSUE TITLE
Definitions verbessern

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#332]
Mir ist gerade aufgefallen, dass in den Descriptions nicht immer die erste Version eines Begriffs glossiert ist, sondern, wenn mehrere Versionen im Text vorkommen, diejenige, die an vorangehender Stelle in meiner Key-Liste steht. In dem Beispiel hier nicht "Betreuten Wohnen", sondern "Betreute Wohnen":

![screenshot 2015-06-19 at 15 42 29](https://cloud.githubusercontent.com/assets/432388/8255098/d6ecf4a2-169d-11e5-9e95-6a65ec6d9f2b.png)

**Comment by KonstantinKo** [comment]
Das ist doch das gewünschte Verhalten? Wenn "Baum, Bäume, Baumhaus" als keys gegeben ist und ein Text "Baum" enthält, dann werden die restlichen nicht mehr angeschaut. Wenn es nicht "Baum" enthält, aber "Bäume", dann wird "Baumhaus" nicht mehr angesehen.

Siehe auch Tests in https://github.com/clarat-org/clarat/blob/develop/test/models/definition_test.rb bei "Infuse, dort wird das verhalten eigentlich gut dargestellt. Wenn das nicht ist, was gewünscht wurde, dann gib mir doch am besten einen passenden Test.

**Comment by Twiek** [comment]
Wir sind fast da...

Im konkreten Beispiel (http://www.clarat.org/angebote/betreutes-wohnen-fuer-jugendliche) kommt in der description die definition mit der ID 14 mehrfach vor, u.a. mit den Keys 'Betreute Wohnen' und 'Betreuten Wohnen'. Richtig ist, dass im Frontend nur ein Key der Definition mit einem Mouseover belegt wird, allerdings soll es genau der Key sein, der als erstes im Text (description) auftauch, nicht der Key, der als erstes in der Definition auftaucht. Im konkreten Fall also 'Betreuten Wohnen' und nicht 'Betreute Wohnen'.

**Comment by KonstantinKo** [comment]
Argh, [you are tearing me apart Basti!](https://youtu.be/Plz-bhcHryc?t=3s)

Dann müssen wir ja doch alle keys durchgehen und dann im Nachhinein noch wieder irgendwie die unerwünschten definitions entfernen... Ein besserer Weg dafür fällt mir nicht ein.
Wär trotzdem schön gewesen, du passt mir den Test an wie du ihn haben willst. Dann gäb's wenigstens keine Missverständnisse mehr.

**Comment by Twiek** [comment]
Siehe auch #318
