### ISSUE TITLE
Ältere / Neuere Beiträge nicht richtig ausgerichtet

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#335]
![unnamed](https://cloud.githubusercontent.com/assets/432388/8285440/a9dd5e6c-1903-11e5-95f1-9fab17c3f41f.png)

+ Ältere nach rechts (weiterblättern ist doch immer rechts und nicht links).

**Comment by marcus-herrmann** [comment]
Deployed/geändert
