### ISSUE TITLE
Darstellungsfehler about us page IE11 & Firefox 38

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#338]
Bei Anzeige der about us page in IE11 & Firefox 38.x.x stehen einzelne Personen alleine in einer Zeile.  Getestet unter verschiedenen Auflösungen.
![unbenannt](https://cloud.githubusercontent.com/assets/11425826/8303635/9937dae6-199f-11e5-8d01-c48c0fa22ba7.JPG)

**Comment by Twiek** [comment]
Notdürftig gefixt, führt aber zu teilweise sehr, sehr viel Platz unter den Beschreibungstexten der einzelnen Personen:

![uber uns clarat](https://cloud.githubusercontent.com/assets/432388/8450835/b4943bfa-1fde-11e5-9a9c-e311e1a6b437.png)

**Comment by marcus-herrmann** [comment]
Hier etwas abgeschwächt: https://github.com/clarat-org/clarat/tree/redesign-about-page

**Comment by Twiek** [comment]
Sehe keine Veränderungen (lag das am pull?). Könntest Du vielleicht noch mal ein vorher/nachher Screenshot anbringen?

**Comment by marcus-herrmann** [comment]
Unterschied sollte zu sehen sein, ggf. $ rake cache:clear.
