### ISSUE TITLE
Karte in den Suchergebnissen nach Zurück-Button nicht angezeigt

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#339]
Springt man von der Angebotsansicht via Zurück-Button zurück in die Übersicht der Suchergebnisse, wird die Karte nicht mehr angezeigt. Erst ein refresh schafft Abhilfe.
![zurueckbutton](https://cloud.githubusercontent.com/assets/11425826/8304057/246b5644-19a3-11e5-8442-6feebccef59f.JPG)

**Comment by KonstantinKo** [comment]
Sollte in neuer Suche kein Problem mehr darstellen. Da die Suche so schnell ist, pushe ich auch übrigens keinen neuen History State mehr für Veränderungen der Suche. Sonst müsste man sich zB durch jeden getippten Buchstaben zurück klicken.
