### ISSUE TITLE
Kontaktfanfragen senden führt zu 500 Fehler

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#341]
Beim Nutzen des Kontaktformulars auf der Startseite (http://www.clarat.org/kontakt/new) wird nach dem Absenden die Standardfehlermeldung ausgespuckt.

"Fehler
Leider ist ein Fehler aufgetreten. Wir werden versuchen ihn schnellstmöglich zu beheben. 
Bis dahin kommst Du hier zurück auf unsere Startseite."

**Comment by Twiek** [comment]
Scheint der gleiche Fehler zu sein wie #340. Werde aus den Logs nicht schlau. Auf staging und lokal gibt es zumindest keine Fehlermeldung (es kommt aber scheinbar auch keine Mail an). 

![bildschirmfoto 2015-06-23 um 17 05 28](https://cloud.githubusercontent.com/assets/432388/8309316/1b56b810-19ca-11e5-8656-1ef10febfd7c.png)

**Comment by KonstantinKo** [comment]
Vermutlich behoben (Sidekiq hatte nicht funktioniert da redis falsch konfiguriert)
