### ISSUE TITLE
Fehler bei Karten-Marker mit mehreren Angeboten

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#342]
Klickt man in der Kartenansicht auf Marker an denen es laut Anzeige mehrere Angebote gibt, wird einem teilweise kein Angebot angezeigt. (Außer das obligatorische Online & Telefon Angebot).

Bsp für nicht funktionierende Links.:
http://www.clarat.org/angebote?utf8=%E2%9C%93&search_form%5Bquery%5D&search_form%5Bsearch_location%5D=Frankfurter%2BAllee%2C%2BBerlin%2C%2BDeutschland&search_form%5Bgenerated_geolocation%5D=52.50992%2C13.47015&search_form%5Bcategory%5D&search_form%5Bexact_location%5D=t

http://www.clarat.org/angebote?utf8=%E2%9C%93&search_form%5Bquery%5D&search_form%5Bsearch_location%5D=Berlin&search_form%5Bgenerated_geolocation%5D=52.5298651%2C13.3864428&search_form%5Bcategory%5D&search_form%5Bexact_location%5D=t

**Comment by jjungle** [comment]
![11](https://cloud.githubusercontent.com/assets/11425826/8306899/c69c8eb6-19bb-11e5-9a11-2506fae91867.jpg)
![unbenannt](https://cloud.githubusercontent.com/assets/11425826/8306906/cd3c7542-19bb-11e5-9bd8-54b05db58600.JPG)

**Comment by Twiek** [comment]
Ist das noch immer der Fall. Die Links führen zwar auch für mich zu einer leeren Karte, aber wenn ich den kompletten Weg versuche nachzuvollziehen klappt es. Im Zweifelsfall bitte noch mal ein Livedemo des Fehlers.

**Comment by Twiek** [comment]
Bitte noch mal aktuelle Beispiele verlinken oder wenn es keine gibt das Issue schließen.

**Comment by jjungle** [comment]
Bei mehreren Angeboten an einem Standort wird jetzt anscheinend einfach nur noch ein Angebot an diesem Standort angezeigt.
![asdf](https://cloud.githubusercontent.com/assets/11425826/9935634/1b1c68be-5d58-11e5-9bc7-63972b1bf019.JPG)
![asdf2](https://cloud.githubusercontent.com/assets/11425826/9935635/1b274a9a-5d58-11e5-83b3-f578327a9ee1.JPG)

**Comment by NilsVollmer** [comment]
Fehler ist behoben aber die Umsetzung mit einer neuen, eingeschränkten Suche finde ich aus Usability Sicht suboptimal.. Ich mache mir mal Gedanken über Alternativen

**Comment by NilsVollmer** [comment]
Julia & Janina zum Wording gefragt, warte auf Antwort

![image](https://cloud.githubusercontent.com/assets/1733220/10140284/09e80b04-6607-11e5-9984-9731a0d09977.png)

![image](https://cloud.githubusercontent.com/assets/1733220/10140241/dca68558-6606-11e5-9121-993d04beb7a7.png)

**Comment by NilsVollmer** [comment]
Janinas Wording-Input bei eingeschränkter Suche:
2 Angebote in der Nähe (X) (ADRESSE) für den Suchbegriff: "jugendliche"

**Comment by NilsVollmer** [comment]
Muss an Dreifaltigkeit angepasst werden.

**Comment by NilsVollmer** [comment]
Waiting for Advanced Search

**Comment by NilsVollmer** [comment]
Klappt soweit, ist aber in /modules umgesetzt. Sollte man wohl lieber überarbeiten.

**Comment by NilsVollmer** [comment]
Warte auf #511 und das darin umgesetzte refactoring des gmaps code.

**Comment by NilsVollmer** [comment]
cheery-picked changes and merged with #677 for PR

**Comment by NilsVollmer** [comment]
Zusammen mit Anpassungen in #677 umgesetzt!
