### ISSUE TITLE
Verlinkung von Blog auf Plattform verbessern

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#346]
Aktueller Workaround geht nicht klar:

![bildschirmfoto 2015-06-25 um 10 44 20](https://cloud.githubusercontent.com/assets/432388/8350595/3a8e3c22-1b27-11e5-8a26-d21d31adf960.png)

**Comment by marcus-herrmann** [comment]
Grafisch finde ich das gar nicht so schlecht (eventuell Clarat-Abrundungs-Style nutzen). Du meinst vermutlich vor allem technisch (ist das ein Plugin)?

**Comment by marcus-herrmann** [comment]
Deployed - Plugin deaktiviert.
