### ISSUE TITLE
Kontaktperson komplett überarbeiten

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#348]
Reihenfolge wichtig!

- [x] Neue Felder im Backend einrichten
- [x] Händisch alle Daten anpassen
- [x] Neue Anzeige im Frontend (nur noch die neuen Datenfelder werden genutzt)
- [x] Namensfeld im Backend löschen

Backend:
Name wird aufgeteilt/ergänzt um/in folgende Felder:
- Vorname (string)
- Nachname (string)
- Akademischer Titel (string -> limited to 'Dr.' und 'Prof. Dr.')
- Geschlecht (string -> limited to 'Mann' und 'Frau')
- Funktion (string -> z.B. 'Geschäftsführer)
- Zuständigkeit (string -> z.B. 'Übernimmt alle Anfragen von Menschen deren Nachname mit den Buchstaben a -z anfangen'')
- Zentral-Name (string -> z.B. 'Zentrale')

**Comment by Twiek** [comment]
Der erste Teil wurde durch https://github.com/clarat-org/clarat/commit/d4c1a3c9822df88ec42feb10cc38aa772c6c52f1, https://github.com/clarat-org/clarat/commit/67f17f8ee3e3ec76e0a6539ce0ce0bd9fbe9cb8c und https://github.com/clarat-org/clarat/commit/8cbf20aab10bc0f8f6eb50b0c257572caed57294 umgesetzt.

**Comment by jjungle** [comment]
Die alten Datenfelder wurden händisch in die neuen Felder übertragen.

**Comment by Twiek** [comment]
@jjungle Bitte fürs Frontend die must haves aufschreiben die zur Not auch hässlich umgesetzt werden müssen.

**Comment by jjungle** [comment]
'Ansprechpartner:' soll nicht weiter angezeigt werden
'Responsibility' soll wenn ausgefüllt, immer mit Break unter Name oder Operational Name angezeigt werden.

Alt:
![contacts-alt](https://cloud.githubusercontent.com/assets/11425826/10100913/5049a842-6395-11e5-8699-5df150a3ca4f.JPG)

Neu:
![contacts-neu](https://cloud.githubusercontent.com/assets/11425826/10100916/574e0840-6395-11e5-9b90-10d3c8bf33e7.JPG)

**Comment by NilsVollmer** [comment]
Frontend entsprechend angepasst, Löschen der Daten nach Absprache mit Konstantin
