### ISSUE TITLE
Links ohne www führen auf die Startseite

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#349]
http://www.clarat.org/angebote/beratung-fuer-maedchen-bei-sexueller-gewalt-10178

und

http://clarat.org/angebote/beratung-fuer-maedchen-bei-sexueller-gewalt-10178

sollten beide zum entsprechenden Angebote und nicht zur Startseite führen.

**Comment by jjungle** [comment]
Kann man bei Apache-Servern über eine .htaccess mit folgendem Inhalt lösen :

RewriteEngine On

RewriteCond %{HTTP_HOST} ^clarat.org
RewriteRule (.*) http://www.clarat.org/$1 [R=301,L]

**Comment by KonstantinKo** [comment]
Wir haben keinen Apache. Per Email bei Andreas angefragt.

**Comment by jjungle** [comment]
http://itsupportnewcastle.org.uk/301-redirect-all-non-www-to-www-using-rack-rewrite/

**Comment by Twiek** [comment]
Hat sich das geklärt, oder soll ich noch mal nachhaken?

**Comment by KonstantinKo** [comment]
Hat sich geklär. Ich leite dir auch immer solche Emails zwischen Andreas und mir weiter.
