### ISSUE TITLE
Expired Offer E-Mail-Benachrichtigungen werden nicht verschickt

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#351]
Siehe E-Mail von Andrea vom 22 Jun 2015 15:09:00 CEST.

**Comment by KonstantinKo** [comment]
Schwer zu sagen, ob's fixed ist oder nicht... Manuell testen ist schwierig und Test Suite behauptet seit jeher, die Mails müssten verschickt werden.

**Comment by Twiek** [comment]
Scheint jetzt zu klappen.
