### ISSUE TITLE
Neue Flüstertüten Clara für den Blog

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#352]
Bitte austauschen mit der per Mail versendeten Datei (Frontansicht).
![clara1](https://cloud.githubusercontent.com/assets/432388/8376662/e9232c24-1c09-11e5-8e78-5252020d3232.png)

**Comment by marcus-herrmann** [comment]
Zugangsdaten zum Blog scheinen sich geändert zu haben, sodass ich nicht einspielen konnte. Bitte https://github.com/clarat-org/clarat-blog-theme/commit/3588f2f0b9b6108aee3d493791f846f259c96279 auschecken, SCSS kompilieren, main.css und svg-Datei hochladen
