### ISSUE TITLE
Google-Translate Navbar nicht repsonsive

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#354]
Wenn man mobile die Google-Translate-Funktion nutzt kann man die 'Navbar' nicht wegklicken, da das 'x' nicht zu sehen ist und man da auch nicht hinscollen kann:

![img_3188](https://cloud.githubusercontent.com/assets/432388/8377794/afc2d05a-1c14-11e5-8194-3d3c567d91a1.jpg)

vs.

![bildschirmfoto 2015-06-26 um 15 05 12](https://cloud.githubusercontent.com/assets/432388/8377812/caeef872-1c14-11e5-80b8-76aab12d56f5.png)

**Comment by marcus-herrmann** [comment]
Problem hier: Das ist ein externer iFrame von Google, und es fällt mir schwer, da CSS zu injizieren. Den Code aus https://github.com/clarat-org/clarat/commit/edb7a50c5b2cf3f179bdf1176e83af77e49e1d3a#diff-60fa2aa78ab242c044301b0ffcff4596R54 kann ich leider nur bedingt nutzen, da ich das JS-Event kennen muss, bei dem die Navbar auftaucht (im Gegensatz zum verlinkten Ansatz, da ist es das Initialisieren des kompletten Übersetzungsmodus - die Navbar taucht aber erst später auf)
