### ISSUE TITLE
Mehrfach Abbonierung des Newsletters

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#355]
Teilweise passiert es, dass man sich trotz einfachem Klick mehrfach für den Newsletter anmeldet.
Der Fehler tritt sporadisch auf und ist bisher nicht reproduzierbar.
Getestet via Android - Chrome , Desktop - Chrome u. Firefox
![screenshot](https://cloud.githubusercontent.com/assets/11425826/8378279/79d62876-1c18-11e5-92cd-41cac72b5866.JPG)

**Comment by KonstantinKo** [comment]
siehe #370 (Fehler mit einfachem klick nicht reproduzierbar aber mehrfach klick ausgeschlossen)
