### ISSUE TITLE
Navbar für Tablets fixen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#356]
![bildschirmfoto 2015-06-26 um 15 34 23](https://cloud.githubusercontent.com/assets/432388/8378336/eb619926-1c18-11e5-9a27-5c23f5c44666.png)

Mehr an der Version für Smartphones orientieren und weniger Platz verschwenden.

**Comment by marcus-herrmann** [comment]
Verwandt mit #354 - nicht zu stylen, da extern

**Comment by Twiek** [comment]
Ok, unklar ausgedrückt. Auf dem SMartphone erscheinen Logo und Suche nebeneinander und nehmen dadurch nicht den halben Bildschrim ein. Hier auch schon für einen früheren Breakpoint eine ähnliche oder die gleiche Lösung nutzen. Da sollte nichts extern sein, oder?

<img width="424" alt="bildschirmfoto 2015-07-03 um 11 23 09" src="https://cloud.githubusercontent.com/assets/432388/8496515/0dfdc2a4-2176-11e5-8633-9cb672970eef.png">

**Comment by marcus-herrmann** [comment]
Sorry, Missverständnis auf meiner Seite. Natürlich nicht extern (war da wohl im Gedanken beim Google Translate Ticket)

**Comment by marcus-herrmann** [comment]
Variante zur Sichtung durch Euch [auf eigenem Featurebranch](https://github.com/clarat-org/clarat/tree/feature/356-tablet-navbar-enhancements). Stelle PR, sobald grünes Licht.
