### ISSUE TITLE
Backupchecker einrichten

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#358]
Details siehe Mail.

**Comment by KonstantinKo** [comment]
Low & Mid Prio?

**Comment by KonstantinKo** [comment]
Angefordert, wartet auf Rückmeldung, wahrscheinlich erst nach 03.07.2015

**Comment by Twiek** [comment]
Rückmeldung erhalten? Wenn nein bitte erneut anfordern und mich in Kopie setzen.

**Comment by KonstantinKo** [comment]
Siehe Email
