### ISSUE TITLE
qTip2 Tooltips optisch überarbeiten

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#359]
Die Mouseovers sollten besser von den eigentlichen Texten abgehoben werden.
Der Background sollte zum Beispiel nicht in der selben Farbe sein. Fontsize könnte ggf. auch etwas größer.

**Comment by marcus-herrmann** [comment]
Betrifft das Blog oder clarat.org? Siehe ausserdem Diskussion hier: https://github.com/clarat-org/clarat/issues/56

**Comment by jjungle** [comment]
Hatte mich etwas undeutlich ausgedrückt. Es geht um die qTip2 Tooltips aus #256

**Comment by marcus-herrmann** [comment]
Roger. Welche Prio hat das?

**Comment by marcus-herrmann** [comment]
<img width="463" alt="bildschirmfoto 2015-08-27 um 10 43 22" src="https://cloud.githubusercontent.com/assets/505181/9516374/8a951882-4ca8-11e5-9cd9-01541eed48ea.png">

Auscheckbar auf [eigenem Featurebranch](https://github.com/clarat-org/clarat/commits/feature/359-enhance-qtips)

**Comment by jjungle** [comment]
Für gut befunden!

**Comment by Twiek** [comment]
@jjungle Bitte immer erst schließen, nachdem es deployed wurde. In diesem Fall vermutlich am Montag.

**Comment by jjungle** [comment]
alles klar
