### ISSUE TITLE
Interne FAQ-Verlinkung teils fehlerhaft

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#362]
Die Interne FAQ-Verlinkung aus #360 funktioniert mit Firefox 38.05 nicht. Die verlinkte Antwort klappt nicht auf.

Mobil (Android - Chrome) klappt die Antwort auf aber ein Teil des Anfangs ist meist verdeckt und die Eingangsfrage ist ebenfalls nicht zu sehen. 

![screenshot_2015-06-30-11-15-03](https://cloud.githubusercontent.com/assets/11425826/8430123/6c5d28a2-1f2e-11e5-8353-e1f6baf57a37.png)

**Comment by Twiek** [comment]
@marcus-herrmann Mein Ziel war es, dass ich auf einen internen Link klicke, die Seite dann zur entsprechenden Seite scrollt und die entsprechende Frage aufklappt (ohne das aufklappen ist teilweise nur sehr schwer ersichtlich wo man eigentlich ist/sein sollte insbesondere bei Fragen die weit unten sind und zu denen man nicht direkt springen kann). Habe es erst mit normalen Ankerverlinkng probiert es aber nicht geschafft es mit dem Aufklappen der Fragen zu kombinieren. Es ging immer nur entweder oder (per preventDefault). Die aktuelle Lösung scheint allerdings nicht mir allen Browsern kompatibel zu sein (siehe Kommentar von Julian). Mobil muss man vermutlich nur noch etwas top-margin ergänzen.

**Comment by marcus-herrmann** [comment]
- event-Object for event.preventDefault() war nicht im Click Callback vrohanden, da war FF pedantischer als Chrome und brach die Funktion ab
- Offset, sobald Header Position Fixed (siehe Screenshot oben) ist drin.

Eigentlich Hotfix, dennoch PR gestellt

**Comment by marcus-herrmann** [comment]
PR durch, nun in Develop
