### ISSUE TITLE
Weitere Claras einbauen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#363]
Für FAQ, Über Uns und Kontakt (Vektorgrafiken folgen per Mail):

![clara_rubriken](https://cloud.githubusercontent.com/assets/432388/8451229/04daabb4-1fe2-11e5-8e4e-9646e39724eb.png)

**Comment by marcus-herrmann** [comment]
Auf eigenem Branch. https://github.com/clarat-org/clarat/tree/feature/363-adding-claras

Gestalterische Meinung: Über-uns-Illustration ist zu komplex/kleinteilig, FAQ-Illu in Ordnung (etwas breit), Kontakt auf den Punkt/großartig.
