### ISSUE TITLE
Anzeige der neuen 'contact person'-Felder

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#365]
Die neuen 'contact person' Felder 'gender' ‘First name’, 'Last name', 'operational name', 'responsibility', 'role'

werden im Frontend noch nicht angezeigt. Dies führt dazu das bei neu angelegten Kontakten nur die Nummern zu sehen sind.

**Comment by Twiek** [comment]
Zusammen mit #348 zu sehen.

**Comment by NilsVollmer** [comment]
Zusammen mit #348 bereits erledigt.

**Comment by Twiek** [comment]
@jjungle Bitte checken und wenn erfolgreich kommunizieren und schließen.
