### ISSUE TITLE
Suche nach einigen 'contact person' Feldern funktioniert nicht

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#367]
Im Backend muss es möglich sein nach folgenden 'contact person' - Feldern zu suchen:
- [x] 'Local number 1'
- [x] 'Local number 2'
- [ ] 'Local number 3' (Sobald es das Feld gibt)
- [ ] 'Email'
- [ ] 'Email 2' (Sobald es das Feld gibt)
- [x] 'Operational Name'

- [x] 'First name'
- [x] 'Last name'

**Comment by jjungle** [comment]
Nach 'First name' u. 'Last name' lässt sich jetzt bereits suchen, 'Local number1' u. 'Local number 2' fehlen noch.

**Comment by jjungle** [comment]
Da sich einige 'contact persons' nicht ohne weiteres wiederfinden lassen und dies zu Dubletten führen kann, entsprechend etwas höher priorisiert.

**Comment by KonstantinKo** [comment]
Issue ist ja doch schon etwas älter und geht von veralteten Annahmen aus. Eine Anfrage zu local_number_3 ist mir nicht bekannt, Emails wurden mittlerweile ausgelagert und sind deshalb nicht auf contact_person durchsuchbar. Der Rest wurde hinzugefügt (direkt auf develop).
