### ISSUE TITLE
Mehrfaches abschicken des Kontaktformulars

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#370]
Ähnlich wie in #355 kommt es vor, dass bei einfachem anklicken des Abschicken-Buttons im Kontaktformular das Abschicken mehrfach ausgeführt wird.

![unbenannt](https://cloud.githubusercontent.com/assets/11425826/8545104/75f217e2-24ab-11e5-9ad8-81953c9bc152.JPG)

**Comment by KonstantinKo** [comment]
"Bei einfachem anklicken des Abschicken-Buttons" konnte ich nicht nachvollziehen, aber ich habe jetzt dafür gesorgt, dass der Button (bei aktiviertem JS) auf keinen Fall mehrfach angeklickt werden kann.

**Comment by jjungle** [comment]
Ist der fix schon live? Gestern (30. Juli 2015, 19:41 Uhr) kam nochmal eine dreifach Mail übers Kontaktformular.

**Comment by KonstantinKo** [comment]
Nein ist noch nicht online. Kommt mit dem nächsten großen deploy
