### ISSUE TITLE
Anzeigeprobleme bei Fokus auf Telefon- und Onlineangebote

### ISSUE THREAD

**Issue by KonstantinKo** [clarat-org/clarat#372]
Etwas, das auch durch richtige Anzeige der Anzahlen nicht behoben wird:
![screenshot-localhost 3000 2015-07-08 15-45-31](https://cloud.githubusercontent.com/assets/779660/8571691/8e1137c6-2588-11e5-8ecc-b648a691713a.png)

Anzahl 3 wird mir angezeigt. Auch wenn 0 Telefonangebote + 3 lokale Angebote = 3 insgesamt. Aber es gibt keine Telefonangebote und wir zeigen keinen Teaser für lokale. Und überhaupt kommt man auch nicht mehr zu lokalen Angeboten zurück.

Das Konzept von dem Fokus auf Telefon- und Online-Angebote braucht noch etwas Ausarbeitung.

**Comment by Twiek** [comment]
Zurückbutton gibt es. Besteht darüber hinaus die Möglichkeit die Zahl neben den Kategorien in der Seitenleiste auf die der Telefonangebote zu reduzieren, wenn nur die Telefonangebote angezeigt werden bzw. generell die angelegten Filter auch dort berücksichtigen.

**Comment by KonstantinKo** [comment]
@Twiek aber wir haben doch extra eingebaut, dass immer die Anzahl aus beiden Suchindexen zusammengerechnet wird, auch wenn immer nur auf einer der Fokus liegt. Im Prinzip war es ja vorher so wie jetzt gewünscht.
