### ISSUE TITLE
Neue Checkbox um Angebote fürs Frontend "unsichtbar" zu machen

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#373]
Wir benötigen eine neue Checkbox um Angebote fürs Frontend Invisible zu schalten.

Grund hierfür sind Anrufe oder E-Mails in denen gewünscht wird, dass Angbote in dieser Form nicht sichtbar sein sollten etc. So können wir während der Überarbeitung oder Diskussion die Angebote vorerst "unsichtbar" schalten.
Die Angebote sollen aber nicht einfach unapproved geschaltet werden, da der Pool mit unapprovten Angeboten sonst unübersichtlich wird. Der normale rewrite+approval Prozess würde hierdurch gestört werden.

**Comment by KonstantinKo** [comment]
Ich würde vorschlagen, dass wir mal von den ganzen checkboxen wegkommen und auf eine state machine umsteigen. Offer durchlaufen eine Prozess. Der Zustand ändert sich von Eingabe -> Bereit für Approval -> Approved (-> deaktiviert, wie oben beschrieben)
Und falls es mal wieder eine rewrite phase oder sowas gibt braucht man auch nicht wieder einen Haufen Booleans in die Datenbank migrieren sondern kann einfach die Liste der Zustände erweitern.
