### ISSUE TITLE
Mediawiki macht Probleme

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#374]
![bildschirmfoto 2015-07-15 um 12 15 16](https://cloud.githubusercontent.com/assets/432388/8696272/2fc0b08a-2aeb-11e5-9647-3edd3192cc2c.png)

<img width="1272" alt="bildschirmfoto 2015-07-15 um 12 13 59" src="https://cloud.githubusercontent.com/assets/432388/8696274/31d37dbc-2aeb-11e5-9ad2-e91fbe081056.png">

What to do? Bitte sobald erste Erkenntnisse vorliegen mich ansprechen.

**Comment by Twiek** [comment]
Man musste wohl Heroku upgraden...

**Comment by KonstantinKo** [comment]
Wie mündlich besprochen: Ist PHP, nichts wo ich schnell was zu sagen kann. Habe bei Heroku erstmal keine one-click-caching Lösung gefunden und bezweifle auch, dass es sowas gibt.
