### ISSUE TITLE
Automatisierte E-Mailbenachrichtigungen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#379]
Erste Idee:

- [x] Emailadressen werden aus den Kontaktpersonen ausgelagert und diesen nur zugewiesen (wie Webseiten bei Angeboten).
- [x] Emails müssen immer einzigartig sein.
- [x] Eine Email merkt sich, ob bereits eine Willkommens-Mail an dieses abgeschickt wurde
- [x] Wird ein Angebot freigeschaltet, schauen wir, ob es eine Kontaktperson enthält, welche noch keine Willkommensmail bekommen hat.
  - [x] Wenn ja, bekommt diese eine.
  - [x] Wenn nein: (siehe unten) werden erstmal keine Emails verschickt.
  - [x] *Zusatz:* Am Anfang der Woche werden zusammenfassende Emails versandt, nicht direkt bei 
         approval.
- [x] In der Willkommensemail steht ganz unten: “PS: Dies ist eine einmalige Informationsemail für Sie. Falls Sie weiterhin informiert werden möchten, wenn Angebote auf clarat mit Ihnen als Kontaktperson aufgenommen werden, dann klicken Sie bitte hier(link). Wir werden Ihnen keine Werbung senden. Wenn Sie keine weiteren Emails von uns wünschen, brauchen Sie nichts weiter tun und wir werden Sie nicht noch einmal anschreiben.”
- [x] Wird auf den Link geklickt, merkt sich die Email, dass weitere updates gewünscht sind. Dann werden immer Emails verschickt, wenn ein neues Angebot dieser Person approved wird.
- [x] In jeder dieser weiteren Emails ist ein “Abmelden”-Link
- Eventuell kann man auch bei Angebotsveränderungen Info-Emails herausschicken. (An Leute, die sich für Emails angemeldet haben). [TBD, erstmal nicht]

**Comment by Twiek** [comment]
@jjungle: Bitte mal durchdenken und alle möglichen Fälle erfassen wenn man solche Mails einmal pro Woche verschickt (z.B. mehrere Angebote für eine E-Mail etc. -> im Endeffekt alles was in irgendeiner Form unterschiedliche E-Mailadressaten braucht oder wo nicht 100% klar wer/ob angeschrieben werden sollte).

**Comment by jjungle** [comment]
Mir fällt nur folgender Sonderfall ein:
info@irgendwas.de wird 2 (Hans, Kalle) persönlichen Kontakten zugewiesen + einem Büro. Die Kontakte haben jeweils unterschiedliche Angebote.
Eine Infomail geht raus in der alle Angebote gelisted sind.
Hans findet das toll und möchte weiterhin informiert werden, klickt deshalb. Kalle und Büro nicht, klicken deshalb nicht. Dem Büro wird die Woche darauf ein neues Angebot zugeordnet und es wird darüber per Mail informiert. Das Büro ärgert sich, klickt auf abmelden. Hans wundert sich das er nichts mehr bekommt.

Im Grunde aber eher ein externes Problem, dass beim teilen von info@ Mails entsteht.
Ansonsten finde ich die Überlegungen gut und sehe keine Probleme.

**Comment by KonstantinKo** [comment]
In diesem Fall wäre mein Geheim-Tipp an Hans & Co, dass sie sich in ihrem Emailprogramm Filter anlegen. So werden Emails, die nur ein Teilnehmer bekommen möchte, in einen speziellen Ordner gelegt. Aber ja, das ist nichts was wir direkt beeinflussen können.

**Comment by KonstantinKo** [comment]
Wurde zusammen mit Julian getestet. Der PR ist schon in develop merged damit ich darauf aufbauend weiterarbeiten kann. Bevor der develop branch aber das nächste mal auf production landet solltest du auch nochmal draufsehen, Basti.

Was außerdem nach dem nächsten deploy zu tun ist:
1. Alle Organisationen auf blocked setzen lassen, von denen die Researcher nicht wollen, dass sie angeschrieben werden (siehe #395)
2. Alle bereits angeschriebenen Emails (siehe Liste von Anne) auf aasm_state: "informed" setzen, damit sie nicht noch einmal angeschrieben werden.

Und dann eventuell nochmal den bereits angeschriebenen Parteien einen subscribe link zusenden?

**Comment by KonstantinKo** [comment]
Achja und Anpassung der Email-Texte und Titel nicht vergessen.

**Comment by jjungle** [comment]
An der Anpassung der E-Mail-Texte und Titel arbeitet das Comms-Team bereits.

**Comment by KonstantinKo** [comment]
@jjungle Ich bitte zu beachten, dass dieses Feature uns gerade ziemlich die deploys blockiert. Bevor das nicht fertig ist, können wir die ganzen neuen Features und kleinen Fixes nicht online bringen, die sich seit Wochen anstauen. (Da es ein sehr komplexes Feature mit vielen Abhängigkeiten war, hab ich darauf aufbauend andere Dinge weiterprogrammiert)

Es wäre also schön, wenn das Comms-Team sich das auch auf die High-Prio-Liste setzt.

**Comment by KonstantinKo** [comment]
Erste Infoemail
- Organisation ist vollständig => Benachrichtigungsfreigabe wird gegeben => Benachrichtigungen auf Kontaktebene, Inhalt Angebotsebene

Es gibt weitere approved Angebote (Kontakt subscribed)
- Pooling pro 14 Tage
- Nur wenn das erste mal approved

Neuer Kontakt mit neuem Angebot: 
- Email bekommen mit Pooling wenn Kontakt fertig (Hallo hier ist clarat)

Neuer Kontakt bei bestehendem Angebot:
- Nix

Evtl Große Orgas -> Grund warum noch nicht angeschrieben obwohl fertig

(Researcher könnten auch in Liste an Kontakte senden)

**Comment by KonstantinKo** [comment]
Entscheidung:
- [ ] Automatisierte Inform-Mailings für uninformed Emails, über checkbox in Orga, 14 Tage Intervall
- Keine Unterscheidung zwischen neuen Kontakten bei bestehenden und neuen Angeboten
- [ ] Automatisierte New-Approvals-Mailings für subscribed Emails, 14 Tage Intervall

**Comment by KonstantinKo** [comment]
Fertiggestellt und mit Basti getestet. Texte fehlen noch.

**Comment by Twiek** [comment]
Weiterer Featurewunsch: Wenn das 'emails enabled' Häckchen bei einer Organisation rausgenommen wird, dann gibt es auch keine weiteren E-Mail über neue Angebote, selbst wenn diesem Angebot ein Kontakt hinzugefügt wird der schon subscribed ist. Die Einstellung auf Orgaebene dominiert also die individuelle Einstellung des Kontakts.

**Comment by Twiek** [comment]
Bitte den 'irreversible' Hinweis im Orga-Adminbereich entfernen (stimmt ja technisch so nicht mehr).

**Comment by Twiek** [comment]
Neuer Text fürs Erstanschreiben findest Du hier: https://docs.google.com/document/d/1OG9uEA275FxusyJOn2iB8vBw4L6ocKf7cUDVq9tVOjk/edit#heading=h.jfaq5954bhtv

**Comment by Twiek** [comment]
Absender für alle E-Mails ist anne.schulze add clarat.org.

**Comment by Twiek** [comment]
E-Mails werden jeden 2. Dienstag um 10:00 Uhr versendet.

**Comment by KonstantinKo** [comment]
Anschreibentexte: OK kann ich machen, aber ich stimme den vorgenommenen Änderungen in der ersten Mail absolut nicht zu… Wenn ihr garantieren wollt, dass so gut wie niemand sich für weitere updates anmeldet dann versteckt den Link irgendwo unten im Fließtext der gern überflogen wird. Die zwei statistisch gesehen meistgelesenen Bereiche einer E-Mail sind
1.) Betreff
gefolgt von
2.) PS
Gut, dass wir dann wenigstens den Abmelden-Link so schön präsent gestalten… (smh)

Stichtagzeiten:
Beide Mailings zur gleichen Uhrzeit versenden könnte zu Problemen führen, deswegen werden jetzt gerade die SubscribedMailings um 6 Uhr und die UninformedMailings um 7 Uhr versandt (Um sicherzugehen, dass sich niemand sofort subscribed wenn er die email empfängt aber die subscription mailings noch nicht alle durchgelaufen sind.) Übrigens war der allgemein frühe Zeitpunkt auch deswegen gewählt, damit researcher nicht schon anfangen, Angebote zu approven während die worker laufen. Ein Zeitpunkt zu dem keiner mit dem System arbeitet wäre meiner Einschätzung nach wirklich klüger.

**Comment by KonstantinKo** [comment]
@Twiek weitere Anmerkungen zu den Mailing Texten:
1. zweites Mailing trägt den Titel "Ihr neues Angebot". Es kann aber auch sein, dass mehrere Angebote darin stehen. Vorschlag: "Ihre neuen Angebote". Es ist weniger seltsam, wenn andersrum dann doch nur eines darin steht.
2. selbes im Fließtext. Da ist dynamische Pluralisierung aber einfacher umzusetzen wie in den bisherigen Mailings.

**Comment by Twiek** [comment]
2. Anschreiben ist auch fertig und liegt im Google-Doc.
