### ISSUE TITLE
2 Wort synonyme direkt über Algolia abbilden

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#381]
Brauchen hierfür eine initiale Liste mit Synonymen in der folgenden Form:

["ny", "New York", "Big Apple"], ["burgerbrötchen", "pattie", "burger-pattie"]

Also jede zusammengehörige Gruppe von Synonymen in eckigen Klammern und durch Komma getrennt. Darin die einzelnen Synonyme in einfachen Anführungsstrichen und ebenfalls durch Komma getrennt. Details siehe auch hier: https://www.algolia.com/doc/rails#configure-synonyms.

Initial gerne in nem Google-Doc, spätere Ergänzungen dann direkt im Code (I will show you).

**Comment by Twiek** [comment]
Bei/nach der Vergabe der Keywords angehen.

**Comment by Twiek** [comment]
Ist das noch relevant? Wenn aus Deiner Sicht nicht, bitte schließen.

**Comment by JulianJung** [comment]
Sobald wir die Keywords angehen ja.

**Comment by Twiek** [comment]
Denke da braucht es kein eigenes Github-Issue für. Wird uns, wenn wir die Suche angehen mit Sicherheit wieder einfallen.
