### ISSUE TITLE
Neue Angebote erstellen nicht möglich

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#384]
Beim erstellen eines Angebots erhält man die Standardfehlermeldung "Fehler Leider ist ein Fehler aufgetreten. Wir werden versuchen ihn schnellstmöglich zu beheben. "

**Comment by KonstantinKo** [comment]
@jjungle sollte wieder klappen. Bitte checken.

**Comment by jjungle** [comment]
funktioniert!
