### ISSUE TITLE
Keine Map-Marker/Pömpel mit IE 11

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#385]
In IE11 werden keine Marker/Pömpel in den Maps angezeigt. Weder auf Angebotsebene noch auf Suchergebnisebene.

**Comment by Twiek** [comment]
Bitte Screenshot machen und dann Marcus zuweisen.

**Comment by jjungle** [comment]
![poempel](https://cloud.githubusercontent.com/assets/11425826/9935666/47929846-5d58-11e5-8986-e6b3e0d1f5b8.JPG)
![poempel2](https://cloud.githubusercontent.com/assets/11425826/9935667/479738f6-5d58-11e5-8de5-d1a3b1f2ffb9.JPG)

**Comment by marcus-herrmann** [comment]
Als Hotfix auf `develop` - IE11 bekommt ein PNG, da es keine SVGs als Marker Image mag, alle anderen Browser den SVG Marker

**Comment by Twiek** [comment]
@jjungle: Könntest Du das bitte checken (kein IE auf meinem Rechner ;-). Bei Problemen bezüglich Branch bitte Nils fragen.

**Comment by jjungle** [comment]
Kann ich leider nicht checken, lokal unter Windows geht bei mir nicht...nur Ubuntu.
Marcus hats aber via Parallels unter Windows 7 getestet....
