### ISSUE TITLE
Google Analytics in den Blog integrieren

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#387]

**Comment by Twiek** [comment]
Bitte folgendes Script verwenden:

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-59626864-2', 'auto');
  ga('set', 'anonymizeIp', true);
  ga('send', 'pageview');

</script>

**Comment by marcus-herrmann** [comment]
Nun im Repo und "deployed"

**Comment by Twiek** [comment]
Sorry, hatte das Snippet falsch formatiert. Bitte jetzt noch einmal integrieren (die XXX... ersetzen und das anonymizeIP hinzufügen):

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', 'UA-59626864-2', 'auto');
      ga('set', 'anonymizeIp', true);
      ga('send', 'pageview');
    </script>

**Comment by marcus-herrmann** [comment]
Sorry, im Footer ist es drin, hatte aber übersehen, dass ich damals schon einen Platzhalter weiter oben eingerichtet hatte (mit XXX). Nehme diesen asap raus, aber die Messung sollte unabhängig davon schon laufen.

Den Code konnte ich mir holen, in dem ich kurz in den Bearbeitungsmodus deines gestrigen Beitrags gegangen bin.

**Comment by marcus-herrmann** [comment]
Korrigiert. Ab jetzt gibt es nur noch eine GA, die gültige, mit Eurer ID.
