### ISSUE TITLE
Frontend Wording von 'Website (PDF)' auf 'Weitere Infos (PDF)' anpassen

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#394]
Der Kritik an Flyer wurde stattgegeben.

**Comment by KonstantinKo** [comment]
Braucht neuen Website host type: `document`. Sollte ab deploy-Zeitpunkt benutzt werden wenn PDF-Dokument eingetragen wird.

Folgenden Konsolenbefehl benutzen um Altdaten zu übertragen:
```
Website.pdf.update_all(host: 'document')
```
