### ISSUE TITLE
Ausschluss aus den automatisierten E-Mailbenachrichtigungen

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#395]
Es muss möglich sein Organisationen von den automatisierten E-Mailbenachrichtigungen #379 auszuschließen.
 
Alle E-Mails die mit einer solchen Organisation verknüpft sind dürfen dann nicht automatisch angeschrieben werden.

**Comment by KonstantinKo** [comment]
Neue Lösung: einfach `mailings_enabled` auf Organisation NICHT setzen.
