### ISSUE TITLE
Metadescription von Offer-Show-Seiten anpassen

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#396]
Damit die einzelnen Angebote in der Googlesuche ein besseres Snippet erhalten, sollten die ersten 154 Zeichen der offer.description automatisch auch im Meta-Description tag der einzelnen Seiten auftauchen.

**Comment by Twiek** [comment]
@jjungle Wenn gecheckt, dann bitte alle wirklich fertigen Issues closen.
