### ISSUE TITLE
Kommentarnotizen einführen

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#399]
Wie besprochen müsste ein neues Kommentarfeld her um Änderungen etc. besser von anderen Kommentaren zu trennen.

**Comment by KonstantinKo** [comment]
Als Admin möchte ich Meta-Informationen zu einem Angebot (evtl. auch Organisation+) hinzufügen können. Diese Metainformationen sollen nicht programmatisch verwendet werden und dienen nur zur reinen Information von mir und anderen Admins. Beispiele dafür sind
- Notizen zu Aufgaben (TODOs); meist um beim Angebotsbetreiber genauer nachzufragen
- Notizen was ich wann aus welchem Grund getan habe (mit Name)
- Notizen dazu, bei wem ich mich zu melden habe, falls dies von der eingetragenen Kontaktinformation abweicht.
- Notizen über Informationen die ich direkt vom Angebotsbetreiber bekommen habe
- Notizen dazu, warum ein Angebot in einem bestimmten Zustand (`state`) ist
Kerninformationen innerhalb dieser Notizen sollten strukturiert eingetragen und durchsuchbar/filterbar sein.

Als Admin will ich weiterhin einem Angebot Kontaktadressen zuweisen können, die nicht der wirkliche Angebotsbetreuer sind (z.B. Bürgertelefon oder ein Sekretariat in der Organisation). Diese [SPoC](https://de.wikipedia.org/wiki/Single_Point_of_Contact) sollen als solche markierbar sein und sollen weiterhin keine automatisierten Emails erhalten (und auch zukünftig nicht genause behandelt werden, wie tatsächliche Angebotsbetreuer)

**Comment by KonstantinKo** [comment]
Note:
- notable - id & type [offer, organization, …]
- author (id)
- created_at
- note_type [todo, history, hidden_contact, external_information]
- text [e.g. "Nachfragen: U18?", "Titel geändert und Angebot zu zweien aufgesplittet", "Nachfragen an Max Mustermann, m@m.com, 0123 4567890", "Kontaktperson Max teilte uns mit, dass Angebot nur im Winter stattfindet", "Angebot unapproved weil expired"]

Anzeige aller zugehörigen notes in RailsAdmin show & edit views:

(Beispiel)
----------------------------
*Julian* notierte am *01.01.2016* zum Thema *Aufgaben*:
Nachfragen: U18?
----------------------------
*Nicole* notierte am *02.01.2016* zum Thema *Aufgaben*:
Nachgefragt. Angebot ist U18 und kann bestehen bleiben.
----------------------------
*Nicole* notierte am *02.01.2016* zum Thema *History*:
Kontaktperson Max Mustermann aus Angebot entfernt und Bürgertelefon eingetragen, da dieser nicht direkt kontaktiert werden möchte.
----------------------------
*Nicole* notierte am *02.01.2016* zum Thema *Kontaktreferenz*:
Nachfragen zum Angebot an Max Mustermann unter 0123 4567890 oder m@m.de
----------------------------
*Server* notierte am *01.02.2016* zum Thema *History*:
Angebot unapproved weil expired.
----------------------------
*Julia* notierte am *05.02.2016* zum Thema *Externe Information*:
Bei Max Mustermann nachgefragt ob Angebot noch aktuell. Öffnungszeiten haben sich verändert: Nur noch jeden zweiten Montag. Diese Änderung befindet sich noch nicht auf deren Webseite.
----------------------------
*Julia* notierte am *05.02.2016* zum Thema *History*:
Angebot überprüft, expires_at und Öffnungszeiten aktualisiert, wieder approved.

**Comment by KonstantinKo** [comment]
![screenshot-localhost 3000 2015-08-14 22-12-38](https://cloud.githubusercontent.com/assets/779660/9283157/d34654aa-42d1-11e5-987d-5cb40c2fcfcc.png)

**Comment by KonstantinKo** [comment]
Zentrale Anlaufstellen extrahiert nach #404.
