### ISSUE TITLE
Einbinden der neuesten Claras in FAQ & Über uns & Contact

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#401]
Habe dir die Zip dazu per Mail geschickt.

**Comment by marcus-herrmann** [comment]
Contact dem Issue-Titel entsprechend nicht austauschen (obwohl in AI)?

**Comment by jjungle** [comment]
Hatte sich an der Contact-Clara etwas verändert? Habe da keinen Unterschied gesehen.

**Comment by marcus-herrmann** [comment]
Dito, sehe auch keinen. Getauschte Maskottchen FAQ und Über uns nun auf `develop`
