### ISSUE TITLE
definition Key bei mehr als einem Wort case sensitive

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#402]
Legt man einen definition Key mit mehr als einem Wort an so ist dieser case sensitive.

**Comment by jjungle** [comment]
Scheint noch nicht zu funktionieren:
Bsp:
definition Key:
'Sexuellen Identität'

http://www.clarat.org/angebote/beratung-bei-fragen-zum-coming-out-geschlecht-und-sexueller-identitaet

**Comment by Twiek** [comment]
@jjungle Kannst Du das bitte noch mal checken und das Issues wenn es klappt schließen?

**Comment by jjungle** [comment]
funktioniert.
