### ISSUE TITLE
Leerzeile in den Opening Specifications ermöglichen

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#403]
Es soll möglich sein eine Leerzeile in den Opening specifications zu erzeugen um Angaben besser voneinander zu trennen.

Momentan sieht es so aus:
![openingspecificationsalt](https://cloud.githubusercontent.com/assets/11425826/9271704/4afbf564-427c-11e5-9cad-b196b5b7cc84.JPG)

In Zukunft sollte es so möglich sein:
![openingspecifications](https://cloud.githubusercontent.com/assets/11425826/9271674/0939be04-427c-11e5-81a4-2c37851470f9.JPG)

**Comment by Twiek** [comment]
Markdown ermöglichen.

**Comment by NilsVollmer** [comment]
@jjungle Markdown unterstützt leider keine Leerzeilen durch simple Zeilenumbrüche. Egal, wie oft du Enter eingibt, wird immer nur genau ein Zeilenumbruch (keine Leerzeile) dabei herauskommen. 

Wenn ihr einen wirklichen Zeilenumbruch wollt, muss man auf simple html syntax zurückgreifen:
Zeile1
<br>Zeile2

erzeugt das gewünschte Ergebnis: Der Zeilenumbruch sorgt für eine neue Zeile und der <br>-tag erzeugt eine Leerzeile. Aktuelle auf http://staging.clarat.org/angebote/2794 zu sehen (sowohl in der description als auch in der opening_specification).

So gesehen gibt es am Code nichts zu ändern.

**Comment by jjungle** [comment]
Habs in die Anleitung zum Backend übernommen, Danke!
