### ISSUE TITLE
Statistiken updaten

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#406]
Bitte Susann und Sophie rausnehmen und Verena und Amina auch 'eine Farbe geben' (siehe Screenshot):

![bildschirmfoto 2015-08-17 um 11 37 10](https://cloud.githubusercontent.com/assets/432388/9302134/7a29e0da-44d4-11e5-914b-6e6d954917ae.png)

**Comment by KonstantinKo** [comment]
Susann und Sophie rausnehmen halte ich für keine gute Idee. Sie haben ja mal was gemacht wie man auch an den vorhandenen Linien sieht und historische Daten würden verfälscht werden, wenn wir sie nicht mehr einbeziehen. Es sollten auch aus diesem Grund keine User je wirklich gelöscht werden, wir können ihnen aber die Rechte wegnehmen.

**Comment by Twiek** [comment]
Ok, hat sich erledigt. Statistiken sollen grundlegend neu angefasst werden (#425). Falls von der bisherigen Lösung nichts übernommen wird kann diese danach gelöscht werden.
