### ISSUE TITLE
Weiterleitung aller Heroku Domains

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#408]
http://clarat.herokuapp.com/angebote/beratung-und-therapie-fuer-depressive-muetter-nach-der-geburt sollte immer googlefreundlich (301?) auf http://www.clarat.org/angebote/beratung-und-therapie-fuer-depressive-muetter-nach-der-geburt weiterleiten.

**Comment by Twiek** [comment]
Gleiches gilt fürs Wiki (z.B. http://clarat-wiki.herokuapp.com/index.php?title=Digitale_Mediathek).

**Comment by KonstantinKo** [comment]
Als hotfix auf master umgesetzt (mittels rack-rewrite)

**Comment by Twiek** [comment]
Bitte auch noch fürs Wiki umsetzen.  http://clarat-wiki.herokuapp.com/index.php?title=Digitale_Mediathek leitet noch nicht weiter auf wiki.clarat.org...

**Comment by KonstantinKo** [comment]
@Twiek Wiki ist nicht mein Bier. Bei Rails musste ich dafür doch nen rack rewrite einbauen. PHP hat ja wahrscheinlich Apache, kann denke ich mit .htaccess gelöst werden.

**Comment by jjungle** [comment]
Mittels .htaccess fürs wiki gelöst
