### ISSUE TITLE
Designbug in den Suchergebnissen (Safari)

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#409]
Tritt scheinbar nur bei Safari auf.

- Ich gebe auf der Startseite einen Suchbegriff ein (z.B. 'rauchen').
- Ich klicke auf das erste Suchergebnis.
- Ich klicke auf den Backbutton oder 'wische zurück'

Entweder verschwindet die Karte, oder die Optik spielt völlig verrückt und die gesamte Seitenleiste verschwindet:

<img width="812" alt="bildschirmfoto 2015-08-17 um 18 15 03" src="https://cloud.githubusercontent.com/assets/432388/9309783/2a1d5f08-450c-11e5-85ab-071fe8415792.png">
<img width="778" alt="bildschirmfoto 2015-08-17 um 18 14 35" src="https://cloud.githubusercontent.com/assets/432388/9309787/2d059df2-450c-11e5-8f75-e2db67289652.png">

Im Zweifelsfall sonst Marcus zuweisen.

**Comment by KonstantinKo** [comment]
Ich setz es mal auf PENDING: Kann gut sein, dass sich das erledigt hat, wenn wir wieder von develop deployen. Dann bitte einfach nochmal nachschauen, ob es immernoch auftritt.

**Comment by Twiek** [comment]
Bitte Suche nach Deploy prüfen und es gegebenenfalls mit rake cache:clear versuchen.

**Comment by KonstantinKo** [comment]
Bei mir aufm Safari geht's.
