### ISSUE TITLE
Offer State Machine

### ISSUE THREAD

**Issue by KonstantinKo** [clarat-org/clarat#411]
- [x] Implementieren
- [x] testen
- [x] Admin-Interface bauen

**Comment by KonstantinKo** [comment]
![screenshot-localhost 3000 2015-08-19 17-52-37](https://cloud.githubusercontent.com/assets/779660/9361357/5b369bf0-469b-11e5-8ce2-e9df2f6197ac.png)
(Alle Buttons & labels auf die Seite geholt; tatsächliche Ansicht wird nur verfügbare Buttons und aktuelles label beinhalten)

**Comment by Twiek** [comment]
Bitte folgendendermaßen umsetzen:

- Renewed außen vor lassen. Wird wirklich bald abgeschafft.
- Urzustand ist 'initialized' von dort kann ausschließlich in der Zustand 'Completed' gewechselt werden.
- Vom Zustand 'Completed' kann ausschließlich in den Zustand 'Approved' gewechselt werden.
- Vom Zustand 'Approved' kann in die folgenden Zustände gewechselt werden: 'Expired', 'Paused', 'Internal Feedback' und 'External Feedback' (mehr Zustände gibt es auch nicht). Von diesen Zustand kann in alle anderen Zustände außer 'Initialized' und 'Completed' kommen. Es kann also z.B. direkt von 'External Feedback' zu 'Paused' gewechselt werden.
- Den Wechsel von 'Completed' zu 'Approved' kann nicht dieselbe Person machen, die das Angebot ursprünglich mal angelegt hat. Alle anderen Wechsel zu 'Approved' schon.
- Wird ein Angebot automatisch auf 'Expired' gesetzt wird weiterhin eine E-Mail versendet.
- In der Angebotsübersicht (http://www.clarat.org/admin/offer) gibt es die Spalte 'Zustand'

Alles clarat?

**Comment by KonstantinKo** [comment]
Braucht noch Regeln für Datenbankmigrierung. Vorschlag:
```
Offer.where(approved: true).update_all aasm_state: :approved
Offer.where(approved: false, completed: true, unapproved_reason: 'N/A').update_all aasm_state: :completed
Offer.where(approved: false, completed: true, unapproved_reason: :not_approved).update_all aasm_state: :completed
Offer.where(approved: false, completed: true, unapproved_reason: :expired).update_all aasm_state: :expired
Offer.where(approved: false, completed: true, unapproved_reason: :paused).update_all aasm_state: :paused
Offer.where(approved: false, completed: true, unapproved_reason: :internal_review).update_all aasm_state: :internal_feedback
Offer.where(approved: false, completed: true, unapproved_reason: :external_feedback).update_all aasm_state: :external_feedback
```
@Twiek Richtig? Ist wichtig.

**Comment by Twiek** [comment]
Ja, richtig.

**Comment by Twiek** [comment]
Ein paar Änderungswünsche:

Bildschirmfoto 2015-08-28 um 11.53.42
<img width="1271" alt="bildschirmfoto 2015-08-28 um 11 40 26" src="https://cloud.githubusercontent.com/assets/432388/9543890/ce3198fc-4d7c-11e5-92ed-145a00d9c04c.png">
<img width="1236" alt="bildschirmfoto 2015-08-28 um 11 40 10" src="https://cloud.githubusercontent.com/assets/432388/9543892/d122feca-4d7c-11e5-87f7-237eabd748e9.png">

**Comment by KonstantinKo** [comment]
Glaube zwar schon, dass auch jeder gecheckt hätte, dass es sich bei dem Objekt um das Angebot handelt bei dem ich gerade auf nen Knopf geklickt habe, aber ich habs mal verändert. Ist jetzt halt der englische model-name. Fehlerbeschreibung gibt es auch aber nein, es ist nicht möglich da auch noch die entsprechenden Formularfelder rot zu färben.

Alles andere fixed.
