### ISSUE TITLE
Footer für den Blog

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#412]
Bitte für den Blog einen Footer erstellen bzw. einen anderen Vorschlag machen wie wir auf jeder Seite Links zu Impressum, Rechtliche Hinweise und Datenschutzhinweise unterbringen (verlinken dann auf die entsprechenden clarat Seiten und gehen in einem neuen Tab auf).

**Comment by marcus-herrmann** [comment]
Es gab ja mal einen Footer, den wir vor Going Live des Blogs rausgenommen haben. Macht hier eine Wiederbelebung Sinn, oder ist ein neuer Ansatz gewünscht?

<img width="971" alt="bildschirmfoto 2015-08-20 um 15 40 56" src="https://cloud.githubusercontent.com/assets/505181/9384614/fc19afb0-4751-11e5-9f4e-d74cbc165c36.png">

**Comment by Twiek** [comment]
Wenn kein großer Aufwand erstmal wieder reinpacken aber mit anderen Links versehen (s.o.).

**Comment by marcus-herrmann** [comment]
Ist nun "deployed" und mit den Links ausgestattet.
