### ISSUE TITLE
Neue FAQs einarbeiten

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#415]

**Comment by Twiek** [comment]
@jjungle: Jetzt sollte es zumindest keine Fehler mehr geben.

**Comment by Twiek** [comment]
@jjungle: Bitte Brandenburg aus den FAQs löschen. Da werden ja erstmal alle alten Angebote gelöscht.

**Comment by jjungle** [comment]
Ist erledigt. Die von Janina entdeckten Fehler wurden ebenfalls gefixt.
