### ISSUE TITLE
Alte Filter löschen (im Code UND in der Datenbank)

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#416]
Audiencefilter, Agefilter...

**Comment by Twiek** [comment]
@KonstantinKo Kannst Du hier die Datenbank noch mal checken ob da noch irgendwas nicht mehr benötigtes liegt?

**Comment by KonstantinKo** [comment]
Hab auf production mal direkt auf der Datenbank ne Anfrage auf alle Filters gesetzt und und nur LanguageFilter, SectionFilter und TargetAudienceFilter gefunden. Es scheint also alles richtig zu sein.
