### ISSUE TITLE
Grafischer Vorschlag für neue Filter

### ISSUE THREAD

**Issue by marcus-herrmann** [clarat-org/clarat#420]
![neuer filter geschlossen](https://cloud.githubusercontent.com/assets/505181/9520948/bf6f8a2e-4ccb-11e5-81e1-9a0a58dbac8b.png)
![neuer filter offen](https://cloud.githubusercontent.com/assets/505181/9520947/bf5594d4-4ccb-11e5-8122-2364178b8e2e.png)

**Comment by marcus-herrmann** [comment]
Update:

Ich versuche eine normale Button-Lösung zu vermeiden, um nicht mit den bestehenden Buttons (alle virtuellen Angebote, alle auf Karte..) zu konkurrieren.

Die Vierspaltigkeit wird garantiert hakelig, sobald der Inhaltscontainer kleiner wird. Aktuell dreizeilige Labels könnten dann vier- und fünfzeilig werden. Insofern ist der aktuelle Vorschlag zwar platzsparender, aber auch fragiler, als der "verschwenderische" (aber m.E.n. klarere) erste.

![neuer filter geschlossen2](https://cloud.githubusercontent.com/assets/505181/9522912/a1776350-4cd7-11e5-9d6b-ec324c726150.png)
![neuer filter offen2](https://cloud.githubusercontent.com/assets/505181/9522924/ae01c8c2-4cd7-11e5-9987-31b30296ec50.png)

**Comment by marcus-herrmann** [comment]
Update mit der gewünschten Reihenfolge von Julia (würde allerdings Sprache unter Alter platzieren, da ansonsten in diesem Breakpoint eine komische Rampe ensteht).

Diese Variante bietet, wie besprochen, aber ein paar technische Herausforderungen (im Frontend), wenn wir uns für sie entscheiden.

![neuer filter offen3](https://cloud.githubusercontent.com/assets/505181/9526016/4b96a558-4ce7-11e5-8627-6ec1739d4191.png)
![neuer filter geschlossen3](https://cloud.githubusercontent.com/assets/505181/9526015/4b95b21a-4ce7-11e5-9ec7-d013066f2ca2.png)

**Comment by marcus-herrmann** [comment]
![neuer filter offen3a](https://cloud.githubusercontent.com/assets/505181/9526898/2c60bec6-4cec-11e5-907f-b0941ce30cd1.png)

**Comment by Twiek** [comment]
Die letzten beiden Vorschläge finden wir alle gut. Die 'vollgelbe' letzte Variante erscheint aber etwas zu massiv, die 'reinbeige' wirkt irgendwie so als würde sie nicht wirklich zum darüber liegenden, gelben 'Suchkasten' gehören. Fallen Dir hier noch andere Varianten ein, z.B. nen Farbverlauf, nen Rand...

Der 'Weitere Suchoptionen' Link passt auf jeden Fall.

Ansonsten bitte noch 'beide Geschlechter' in 'egal' umbenennen.

**Comment by marcus-herrmann** [comment]
Hier ein Update. Wenn das in Ordnung ist, würde ich heute prüfen, wie ich diesen Vorschlag in HTML abbilden kann - auf den ersten Blick ist es ein Formular, was sich über 2 Container erstreckt (Header, Hauptcontentspalte)

![neuer filter offen_150903](https://cloud.githubusercontent.com/assets/505181/9656818/ae827210-523b-11e5-9110-f0a4dbf815db.png)

**Comment by Twiek** [comment]
@marcus-herrmann: Gefällt mir, diesen Vorschlag bitte weiterverfolgen.

@KonstantinKo: Das ist der letzte Stand.

**Comment by marcus-herrmann** [comment]
Hier - isoliert betrachtet - Scribbles, wie es non-desktop aussehen könnte (keine Reinzeichnungen)

![neue filter mobile offen](https://cloud.githubusercontent.com/assets/505181/9664201/a781ff26-5268-11e5-8e41-3e2c20125820.png)
![neue filter tablet offen](https://cloud.githubusercontent.com/assets/505181/9664202/a7879954-5268-11e5-94a5-5dd02b743db8.png)
![neue filter tablet geschlossen](https://cloud.githubusercontent.com/assets/505181/9664203/a78976f2-5268-11e5-9749-cc3a8a322b25.png)

**Comment by Twiek** [comment]
Bitte bei 'Hilfe für wen?' noch 'Für Schwangere' ergänzen.

**Comment by marcus-herrmann** [comment]
Das würde dann aktualisiert folgendermaßen aussehen (offene Filter jeweils visualisiert):

![neuer filter offen 150917](https://cloud.githubusercontent.com/assets/505181/9928920/c1ffefd6-5d29-11e5-846b-acf76b0b41b6.png)
![neuer filter offen tablet 150917](https://cloud.githubusercontent.com/assets/505181/9928921/c2002d98-5d29-11e5-9f07-fa4ac0d4b72e.png)

**Comment by marcus-herrmann** [comment]
Hier erstmal Desktop:

![neuer filter offen_2](https://cloud.githubusercontent.com/assets/505181/9931808/2785e210-5d3f-11e5-9d7c-dec7fab4e768.png)
![neuer filter offen_2a](https://cloud.githubusercontent.com/assets/505181/9931809/2787073a-5d3f-11e5-9059-cab5528fb876.png)

**Comment by marcus-herrmann** [comment]
Und non-desktop:

![neue filter tablet 2](https://cloud.githubusercontent.com/assets/505181/9932192/3755a830-5d42-11e5-9f32-75c176c00b40.png)
![neue filter tablet 1](https://cloud.githubusercontent.com/assets/505181/9932190/3752d2ae-5d42-11e5-9d3d-b9ac8da9fb9e.png)
![filter mobile offener 2](https://cloud.githubusercontent.com/assets/505181/9932191/375466d2-5d42-11e5-8c68-3e568b3b4e88.png)

**Comment by Twiek** [comment]
@marcus-herrmann: Sieht gut aus, bitte umsetzen (oder brauchst Du noch spezifisches Feedback?).
@KonstantinKo: Was das Wording beim Alter des Kindes angeht bitte folgendes verwenden: '< 1 Jahr', '1 Jahr', '2 Jahre' ... '17 Jahre'.

**Comment by Twiek** [comment]
Und bitte auch das 'für alle' bei 'Hilfe für wen?' in 'egal' umbenennen.

**Comment by NilsVollmer** [comment]
kleines Update vom Sprachteam: "für die ganze Familie" sollte besser "für Familien" heißen

**Comment by marcus-herrmann** [comment]
Das müsste ans Backend-Team, am besten des Form eines gesonderten Tickets, überwiesen werden, da die `target_audience`'s aus der Datenbank zu kommen scheinen.

**Comment by NilsVollmer** [comment]
@marcus-herrmann Jo, passt - ich hatte es hier auch eher als Notiz hingeschrieben, damit wir es nicht vergessen ;)

**Comment by Twiek** [comment]
Wenn man 'Vor Ort' Häkchen gesetzt ist bitte auch die einzelnen Wörter (Telefon, E-Mail...) 'ausgrauen' bzw. blasser darstellen. Ansonsten sieht es schick aus.

**Comment by Twiek** [comment]
@NilsVollmer: Bitte versuche mal die Verknüpfung mit Algolia hinzubekommen + das Wording beim Alters-Dropdown wie folgt zu ändern:

'< 1 Jahr'
'1 Jahr'
'2 Jahre'
...

**Comment by marcus-herrmann** [comment]
> Wenn man 'Vor Ort' Häkchen gesetzt ist bitte auch die einzelnen Wörter (Telefon, E-Mail...) 'ausgrauen' bzw. blasser darstellen. Ansonsten sieht es schick aus.

Drin.

**Comment by Twiek** [comment]
Und dann bitte auf Staging deployen...

**Comment by NilsVollmer** [comment]
Ist aktuell auf staging deployed. Sprache, für wen und Geschlecht funktionieren anscheinend schon gut.

Alter und encounter brauchen noch ein wenig Zuneigung

**Comment by NilsVollmer** [comment]
Alter klappt jetzt auch - bis auf 'Auf welchem Weg?' (encounter) schaut alles ganz gut aus.

**Comment by Twiek** [comment]
Please prepare for deploy (gerne vorher noch mal auf Staging testen)

**Comment by NilsVollmer** [comment]
merge branch: feature/420-adv-search-merge-sep

**Comment by NilsVollmer** [comment]
Die entsprechenden branches auf clarat_base und claradmin heißen adv-search

**Comment by KonstantinKo** [comment]
Habe noch encounter filtering umgesetzt. Bitte mal feature/420-adv-search-merge-sep anschauen, ob das dem gewünschten verhalten entspricht.

**Comment by Twiek** [comment]
@KonstantinKo: Sieht alles gut aus. Verbleibende Herausforderung ist jetzt scheinbar   'nur' noch da wieder develop reinzumergen (ne Menge Konflikte) damit u.a. auch die Kategorien wieder in der Seitenleiste auftauchen. Dann gerne baldmöglichst deployen.

**Comment by KonstantinKo** [comment]
Ist jetzt nach unseren mündlich besprochenen Anforderungen umgesetzt.
Nach deploy: reindex & cache clear
