### ISSUE TITLE
Möglichkeit für Standort - Name/Addition bei Telefon u. Onlineangeboten

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#421]
Bei manchen Telefon u. Onlineangeboten gehen wichtige Informationen zum Anbieter verloren die wir sonst über den Standor Name oder Addition abbilden.
Die Probleme treten vorrangig bei komplexereren Orgas wie Kliniken oder Ämtern auf.

Bsp.:

![hotline](https://cloud.githubusercontent.com/assets/11425826/9521737/df7a7400-4cd0-11e5-9102-1465cad561ac.JPG)

Müsste eigentlich um folgende Informationen ergänzt werden.
![hotline besser](https://cloud.githubusercontent.com/assets/11425826/9521738/e4ff2bdc-4cd0-11e5-8608-00dce47410ea.JPG)

**Comment by Twiek** [comment]
+ 'Wo gibt's die Hilfe' macht als Überschrift keinen Sinn bei virtuellen Angeboten.

**Comment by Twiek** [comment]
Wird erst umgesetzt, wenn sich noch mal jemand aktiv meldet.
