### ISSUE TITLE
Statistiken überarbeiten

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#425]
Folgendes soll zu Angeboten zu sehen sein:
- [x] Gesamtzahl der aktuell freigeschalteten (approved)
- [x] Gesamtzahl der aktuell existierenden (created)
- [x] Gesamtzahl bisher erstellten (created) (inkl. der gelöschten -> eher nice to have)

- [ ] Erstapproval pro Tag (gerne in einem Graph und gerne mit der Möglichkeit sich den kumulierten Wert und alternativ die Werte für jeden einzelnen User anzeigen zu lassen)
- [ ] Erstellt (created) pro Tag (gerne in einem Graph und gerne mit der Möglichkeit sich den kumulierten Wert und alternativ die Werte für jeden einzelnen User anzeigen zu lassen)

Folgendes soll zu Orgas zu sehen sein:
- [x] Gesamtzahl der aktuell freigeschalteten (approved)
- [x] Gesamtzahl der aktuell existierenden (created)
- [x] Gesamtzahl bisher erstellten (created) (inkl. der gelöschten -> eher nice to have)

Für beides:
- [x] Möglichkeit die Daten runterzuladen (z.B. als CSV). Wird vermutlich sehr selten genutzt, kann zur Not also auch per command line ausgeführt werden
- [x] Neben jeder Statistik sollte Platz für einen kleinen Erklärtext (< 200 Zeichen) sein. Auch als Mouseover denkbar.

Die Daten müssen definitiv nicht live generiert werden, aber einmal täglich (gerne nachts) wäre eine Aktualisierung gut.

**Comment by KonstantinKo** [comment]
Post Deploy:

```ruby
Date.parse('2014-09-19').upto(Date.current) do |date|
  created_offers = Offer.where("offers.created_at::date = ?", date)
  if created_offers.any?
    created_offers.select("DISTINCT(created_by)").each do |creator_offer|
      creator_id = creator_offer.created_by
      y_count = created_offers.where(created_by: creator_id).count
      Statistic.create! topic: :offer_created, user_id: creator_id,
                        x: date, y: y_count
    end
  end
  
  approved_offers = Offer.where("offers.approved_at::date = ?", date)
  if approved_offers.any?
    approved_offers.select("DISTINCT(approved_by)").each do |approver_offer|
      approver_id = approver_offer.approved_by
      y_count = approved_offers.where(approved_by: approver_id).count
      Statistic.create! topic: :offer_approved, user_id: approver_id,
                        x: date, y: y_count
    end
  end
  
  created_orgas = Organization.where("organizations.created_at::date = ?", date)
  if created_orgas.any?
    created_orgas.select("DISTINCT(created_by)").each do |creator_organization|
      creator_id = creator_organization.created_by
      y_count = created_orgas.where(created_by: creator_id).count
      Statistic.create! topic: :organization_created, user_id: creator_id,
                        x: date, y: y_count
    end
  end
  
  approved_orgas = Organization.where("organizations.approved_at::date = ?", date)
  if approved_orgas.any?
    approved_orgas.select("DISTINCT(approved_by)").each do |approver_orga|
      approver_id = approver_orga.approved_by
      y_count = approved_orgas.where(approved_by: approver_id).count
      Statistic.create! topic: :organization_approved, user_id: approver_id,
                        x: date, y: y_count
    end
  end
end
```

**Comment by KonstantinKo** [comment]
Brauche PR merged (und live deployed) um Blockspring-Integration bauen zu können.
Bitte #452 reviewen.

**Comment by Twiek** [comment]
Blockspring bitte testweise in einem Google-Sheet integrieren.

**Comment by KonstantinKo** [comment]
Blockspring funktionen online stellen!

**Comment by KonstantinKo** [comment]
Umgesetzt mit Blockspring Funktionen.

Es wird zwar nicht "Erstapproval" dargestellt, aber dafür ein langfristig korrekt bleibender wert von create und approve Aktionen.

Kumulativ gibt es noch nicht, kann man aber sicher auch mit standard Excel-Funktionen umsetzen.

Damit sollte das Issue erledigt sein, oder?

**Comment by KonstantinKo** [comment]
Blockspring funktionen gespeichert unter https://github.com/clarat-org/clarat-blockspring-functions
Api-Keys sind Secrets

**Comment by Twiek** [comment]
Bitte noch ergänzen bzw. aufzeigen wo zu finden/wie zu erstellen: Kumulierter Chart für die Gesamtzahlen + kummulierte Charts pro Researcher.

**Comment by KonstantinKo** [comment]
@Twiek http://www.extendoffice.com/documents/excel/1534-excel-cumulative-chart.html
Kann ich natürlich auch machen wenn nötig.

**Comment by Twiek** [comment]
Das ist veraltet und kann weg, oder?

**Comment by KonstantinKo** [comment]
Ja, ich glaube das blockspring konzept haben wir aufgegeben, oder? Man hätte natürlich daraus bessere und mehr Statistiken mit weniger Entwicklungszeit bekommen können, aber dann müsste sich halt jemand mit der Excel-Seite beschäftigen.
