### ISSUE TITLE
Bearbeiten/Speichern von Angeboten von unapproved Organization

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#433]
Es muss möglich sein Angebote die unapproved Organizations zugewiesen sind, nach Überarbeitung(also auch nach initialized Zustand) zu speichern.

**Comment by KonstantinKo** [comment]
Braucht Spezifikation: Es soll sicherlich nicht immer möglich sein, Angebote von unapproved Organisationen zu speichern. Sonst hätten wir die Validierung nie eingeführt.
Also, wann soll es noch möglich sein? "Auch nach initialized Zustand" … Also auch wenn das Angebot schon completed ist? Aber ein Angebot kann doch nicht komplett (sprich "Bereit zum approven") sein, wenn die zugehörige Organisation nicht auch bereit ist. Und schon gar nicht, wenn das Angebot approved ist?
Und was ist, wenn die Änderung die gespeichert werden soll eben gerade das Ändern des Zustandes ist?

@Twiek interessiert dich vielleicht auch.

**Comment by Twiek** [comment]
Man kann ein Angebot anlegen und updaten auch wenn die zugeordnete Organisation nicht approved ist. Dies ist in den Zuständen 'initialized' und 'completed' möglich. Wenn man das Angebote approven will so muss es einer Organisation zugeordnet sein die ebenfalls approved ist. Gleiches gilt für die potentiell darauf folgenden Zustände (expired, internal feedback... ). Auch wenn ein Angebot in einem dieser Zustände später noch einmal bearbeitet wird muss vor dem Speichern geprüft werden, ob die Organisation 'approved' ist.
Lediglich die Zustände 'completed

**Comment by KonstantinKo** [comment]
Direkt auf develop umgesetzt da hohe prio und ein weiteres feature (#439) hiervon abhängt. Bitte direkt dort reviewen.

**Comment by KonstantinKo** [comment]
> Gleiches gilt für die potentiell darauf folgenden Zustände (expired, internal feedback... ). Auch wenn ein Angebot in einem dieser Zustände später noch einmal bearbeitet wird muss vor dem Speichern geprüft werden, ob die Organisation 'approved' ist.

Dies wurde zwar umgesetzt, aber mit PR #453 (zu Issue #439) wieder entfernt:
Da Angebote deaktiviert werden sollen wenn die Organization deaktiviert (sprich nicht approved ist), darf diese Validierung dann nicht laufen.
Nach diesem PR greift die Validierung nur noch, wenn das angebot approved ist oder es werden soll.
