### ISSUE TITLE
Deaktivieren von Organisationen deaktiviert auch deren Angebote

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#439]
Wenn man den Zustand einer Organisation von 'approved' auf 'Deaktivieren (Internal Feedback)' oder auf 'Deaktivieren (External Feedback)' setzt, so werden auch alle der Organisation zugeordneten Angebote die bisher den Zustand 'approved' hatten auf 'Deaktivieren (Internal Feedback)' oder auf 'Deaktivieren (External Feedback)' gesetzt (die, die nicht approved waren bleiben wie sie sind).

Nice to have: In allen zugehörigen Angeboten deren Zustand geändert wurde wird eine Notiz mit dem neu anzulegendem Thema 'Organisation deaktiviert' und dem Inhalt 'Organisation wurde in den Zustand '[Hier der Zustand]' versetzt.

**Comment by KonstantinKo** [comment]
@Twiek

**Comment by Twiek** [comment]
History it is!

**Comment by KonstantinKo** [comment]
@Twiek Hier wäre übrigens bei den Notes eine größere Auswahl an Referenzpunkten gut gewesen, weil ich dann einfach die betreffende auslösende Organisation hätte verlinken können. Man wäre dann mit einem Klick gleich beim Auslöser. (Man bedenke: Angebote können mehrere Organisationen haben)

**Comment by KonstantinKo** [comment]
siehe Kommentar in #433

**Comment by Twiek** [comment]
Sorry, noch mal durchgesprochen und zu neuen Erkenntnissen/Anforderungen/Fragen gelangt:

Wäre es nicht möglich den Angeboten einen weiteren state namens 'organization unapproved' hinzuzufügen. In diesen wird das Angebot ausschließlich dann versetzt, wenn die Organisation unapproved wird. Eine gesonderte Notiz ist dann nicht mehr notwendig (bei dem selten Fall von mehreren Organisationen auf einem Angebot müssen sich die Researcher halt durchklicken). Wird eine Organisation approved werden alle Angebote die ihr zugeordnet sind, sich im state 'organization unapproved' befinden und ansonsten valide sind wieder auf 'approved' gesetzt. Manuell sollte man Angebote nicht direkt in den state 'organization unapproved' setzen können.
