### ISSUE TITLE
Reihenfolge in der RailsAdmin Sidebar anpassen

### ISSUE THREAD

**Issue by JulianJung** [clarat-org/clarat#440]
Die neue Reihenfolge soll so beginnen:
Organisationen
Standorte
Angebote
Kontaktpersonen
Emails

Rest gleichbleibend

**Comment by Twiek** [comment]
Und auch noch mal kritisch prüfen ob Sachen nicht ganz gelöscht werden können.

**Comment by Twiek** [comment]
Neues Backend, neues Glück...
