### ISSUE TITLE
Comments in die Notizen migrieren

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#441]
Die momentan gesetzten Comments sollen beim migrieren in die neuen Notizen das Thema Todo erhalten.

**Comment by Twiek** [comment]
Bitte entsprechend migrieren und dem Inhalt der so neu angelegten Notes ein 'Ehemaliges comment: ' voranstellen.

Danach die comments aus der Datenbank und dem Code entfernen.

**Comment by KonstantinKo** [comment]
Umgesetzt.
(Beispiel-Angebot ID 67)
