### ISSUE TITLE
Location Addition Feld auch in der Vorschau anzeigen

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#442]
Um bei der Standortauswahl bei Erstellung eines Angebots oder einer Organisation besser differenzieren zu können, sollte das Additionfeld ebenfalls in der Vorschau angezeigt werden.

![julian-clarat-2015-06-10-p6100181 1](https://cloud.githubusercontent.com/assets/11425826/9680872/4b462a38-52fa-11e5-991e-2994bc79ec81.jpg)

**Comment by KonstantinKo** [comment]
Umgesetzt auf clarat_base & claradmin

**Comment by KonstantinKo** [comment]
Deploy TODO:
```ruby
Location.find_each &:save
```
um `display_name`s neu zu generieren.
