### ISSUE TITLE
Hinzufügen von Kontakten in der Angebotserstellung - Verdeutlichen das keine E-Mail gefunden wurde

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#443]
Wenn man Kontakte via Angebotserstellung hinzufügen möchte ist es nicht 100% deutlich, dass eine Email nicht gefunden wurde. Da wir gewohnt sind eine E-Mail in diesem Feld via Copy & Paste einzufügen und auf Speichern zu klicken, kann man dies schnell übersehen und den Kontakt versehentlich ohne E-Mail anlegen.

![asdf](https://cloud.githubusercontent.com/assets/11425826/9681966/7aec672c-5302-11e5-92ef-90280d05a1d4.jpg)

**Comment by KonstantinKo** [comment]
In Absprache mit Basti: won't fix.

Ich packs mal in die Wishlist falls man das hier fürs RailsAdmin-rework behalten will. Wenn nicht, bitte einfach closen.
