### ISSUE TITLE
Wording anpassen - 404 & Error page

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#444]
Um Personen besser abzuholen die in Google auf ein clarat Angebot klicken dass wir bereits gelöscht haben, sollten wir die 404 page etwas im Wording anpassen.
Gleiches gilt für den fall das ein Angebot unapproved wurde aber in Google Suche zu finden ist:

Vorschlag für unapproved:

Dieses Angebot ist für kurze Zeit unsichtbar.

Bei diesem Angebot prüfen wir gerade, ob alle Infos stimmen. Deshalb ist es für kurze Zeit unsichtbar. Schreibe einfach in das Finde-Feld, welche Hilfe du suchst. Oder was dein Problem ist. clarat zeigt dir dann weitere Angebote in deiner Nähe.

Vorschlag für 404 aus dem Sprachteam:

Leider konnten wir diese Seite nicht finden.

Schreibe einfach in das Finde-Feld, welche Hilfe du suchst. Oder was dein Problem ist. clarat zeigt dir dann weitere Angebote in deiner Nähe. Oder gehe hier (LINK) auf die Startseite. Dort kannst du über die runden Bilder nach passender Hilfe suchen.

**Comment by Twiek** [comment]
@jjungle Hast Du für das 'Google-Problem' nen Link oder nen Beispiel zum testen?

Sind ansonsten die Texte mit den Sprachmädels abgestimmt? Tue mich z.B. mit 'Finde-Feld' etwas schwer. Denke Suchfeld ist hier weit geläufiger, oder?

**Comment by jjungle** [comment]
Die Texte stammen von Julia. Ich bin auch kein Freund vom 'Finde-Feld'. Es wurde in den FAQs allerdings auch öfters so genannt. 

Hier ist ein unapproved Angebot das noch in der Google Suche ist:
https://www.google.de/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=F%C3%BCr+Eltern+von+Roma-Kindern+Hilfe+bei+Problemen

Mehr davon hier: https://www.google.com/webmasters/tools/crawl-errors

Aktuelle 404er  auf Angebotsebene scheint es da aktuell nicht zu geben. Wird es aber ziemlich sicher immer mal wieder.

**Comment by Twiek** [comment]
@NilsVollmer Bitte mal checken, ob man User die über die Googlesuche zu einem Angebot kommen welches aktuell nicht approved ist gesondert abfangen kann (Linkbeispiel: https://www.google.de/url?sa=t&rct=j&q=&esrc=s&source=web&cd=2&cad=rja&uact=8&ved=0CDkQFjABahUKEwjSy825pfvHAhUHRBQKHa_PB0w&url=http%3A%2F%2Fwww.clarat.org%2Fangebote%2Fhilfe-bei-problemen-in-der-schule-fuer-eltern-und-lehrer-von-roma-kindern&usg=AFQjCNEG9-7_eQjwRAsN2-gstfKl6hWrxw).

Ansonsten bitte den 404 Text wie von Julian beschrieben ändern.

**Comment by NilsVollmer** [comment]
@Twiek Ich habe die 404 und 500er pages entsprechend angepasst. Da bei der 500er Page keine "Finde-Zeile" zu sehen ist, habe ich die Abschnitte im Text rausgenommen, da sind sonst nur verwirren würden. Man sollte aber schon noch einmal drüber nachdenken, ob es gut ist, dass die 500er Page jetzt immer den relativ spezifischen Text zeigt. Evtl. ist eine allgemeinere Formulierung sinnvoller, da man auch aus anderen Gründen auf der Page landen könnte.

![image](https://cloud.githubusercontent.com/assets/1733220/9905050/c0395928-5c82-11e5-9ced-579271eb7956.png)

![image](https://cloud.githubusercontent.com/assets/1733220/9905068/d7803db8-5c82-11e5-9b19-e16b06a3915d.png)

**Comment by Twiek** [comment]
@NilsVollmer : Ja, sorry, Missverständnis. Bitte den alten 500-Text benutzen. Neuer Text wäre nur relevant, wenn wir hier unterscheiden könnten.
