### ISSUE TITLE
Regelmäßig prüfen ob alle approved Organizations valid

### ISSUE THREAD

**Issue by JulianJung** [clarat-org/clarat#445]
Da es ein paar approved Organizations gab die durch Veränderung der Standorte nicht mehr valid waren, sollte man regelmäßig nachschauen ob dies öfters auftritt.

**Comment by Twiek** [comment]
Bzw. bei Änderungen von z.B. der location checken ein anderes Objekt (z.B. Organisation) invalide wird.

**Comment by Twiek** [comment]
Heute geprüft und alles gut.

**Comment by Twiek** [comment]
@jjungle: Die Organisationen mit den folgenden IDs sind approved, aber nicht valide:

58, 388, 203, 72, 269, 242, 9, 215, 30, 158, 113, 240

Bitte mal händisch überprüfen. Liegt zumindest teilweise an den Webseiten und dass die als Host nicht 'own' haben.

**Comment by jjungle** [comment]
Alle angepasst. Lag immer an Host-Type ≠ own

**Comment by Twiek** [comment]
Stand heute alles gut.

**Comment by Twiek** [comment]
Stand heute alles gut.

**Comment by Twiek** [comment]
Heute 3 Fälle gefunden (939, 243, 589) und an WPQ gegeben.

**Comment by Twiek** [comment]
Überlegen wie das perspektivisch richtig zu lösen ist. Z.B. Verknüpfung zwischen Orga und Standort in 2 Varianten aufteilen.
