### ISSUE TITLE
Expired Angebote sollen via Asana API  Tasks für QMA erzeugen

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#446]
Asana Project ID: 44856824806357
Der Taskname soll sich wie folgt zusammensetzen : 'Organization_Name'-'expires_at'-'offer_name'
Die Taskdescription sollte die Backend URL des Angebots beinhalten.

**Comment by KonstantinKo** [comment]
@jjungle "Organization_Name" -> Von welcher Organisation? Einfach irgendeine von den potentiell mehreren die so ein Angebot hat?

**Comment by KonstantinKo** [comment]
Ich kann auch wie bei der Suchergebnisanzeige "Kooperationsprojekt" hinschreiben wenn es mehrere gibt.

**Comment by KonstantinKo** [comment]
![screenshot-app asana com 2015-09-21 16-26-15](https://cloud.githubusercontent.com/assets/779660/9994437/764d1724-607d-11e5-8881-fcddf5ce5914.png)

**Comment by jjungle** [comment]
Wenn ein Angebot mehreren Organisationen zugeordnet ist, sollen an dieser Stelle alle Organisationen kommagetrennt aufgelistet werden. Dem QMA Team ist bewusst wie lang der Taskname dann werden könnte.
Wenn das nicht geht, reicht auch irgendeine dem Angebot zugewiesesene Organisation.

**Comment by Twiek** [comment]
@KonstantinKo, @jjungle: Nen Vorschlag wie man das sinnvoll testen kann, oder wollen wir es einfach 'live' ausprobieren? Worst case ist ja, dass zu viele, falsche oder keine Tickets erstellt werden und wir könnten wohl mit allem leben, richtig?

**Comment by jjungle** [comment]
@Twiek die ersten Angebote sind schon abgelaufen.
Alle Angebote die am 29.09 abgelaufen sind wurden auch in Asana erstellt.
https://app.asana.com/0/44856824806357/53405221832954
Angebote vom 26.09 fehlen jedoch. (IDs: 1653, 2228, 2291, 47, 1483[invalid])

Angebote vom 25.09, 23.09 u. 22.09 sind ebenfalls nicht in Asana zu sehen.

**Comment by KonstantinKo** [comment]
es wurde ja auch erst gestern (28.09.) deployed
