### ISSUE TITLE
Kontaktformular ohne angabe der Email ausgelöst.

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#450]
Ein User hat 5 Nachrichten über das Kontaktformular gesendet und dabei trotz Pflichtfeld keine Email angegeben (oder die angegebene Mail wurde nicht übermittelt).
Die Nachrichten sind zudem nicht in Freshdesk angekommen.

http://www.clarat.org/admin/contact/329
http://www.clarat.org/admin/contact/330
http://www.clarat.org/admin/contact/331
http://www.clarat.org/admin/contact/332
http://www.clarat.org/admin/contact/333

**Comment by KonstantinKo** [comment]
Email ist *kein* Pflichtfeld, wenn die Anfrage über ein "ich habe einen Fehler gefunden"-Formular kommt.

> "It's not a bug, it's a feature"

Außerdem tragen alle diese Kontaktanfragen verschiedene URLs, heißt der Nutzer muss die Nachricht auf jedem von diesen Angeboten in das Formular eingetragen und abgeschickt haben.

Warum die Nachricht in Freshdesk ankommen sollte, weiß ich nicht. Mir kam dazu bisher noch kein Feature-Task auf den Tisch. Bitte als neues Feature-Request an Basti geben.

(Wenn damit erledigt, bitte schließen.)
