### ISSUE TITLE
Die Kategorie 'Sucht' kann nicht hinzugefügt werden wenn schon bestimmte andere Kategorien vergeben wurden 

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#451]
Siehe z.B. hier: http://www.clarat.org/admin/offer/1977/edit (es wurde bereits die Kategorie 'Eltern mit Suchtproblemen' vergeben.

**Comment by KonstantinKo** [comment]
Hab nachgeschaut, ist definitiv rails_admin interna. Wenn du nicht willst, dass ich ein paar Tage damit verbringe, mich in rails_admin core einzuarbeiten, diesen Fehler nachzubauen, und bugfixes direkt an die zu submitten dann ist das ein "won't fix"
