### ISSUE TITLE
Verfügbare Sprachen in der Angebotseinzelansicht anzeigen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#455]
Einige Angebote sind in mehrere Sprachen verfügbar (z.B. Sozialberatung auf Türkisch). Bitte einen Vorschlag machen wo/wie das im Frontend angezeigt werden kann.

**Comment by marcus-herrmann** [comment]
Zunächst Desktop - ist das so gemeint, oder dezenter?

![offer-show-sprachen](https://cloud.githubusercontent.com/assets/505181/10454180/1a222754-71b3-11e5-8af8-63d905b093e7.png)

**Comment by NilsVollmer** [comment]
Ich wurde gerade von Lavinia und Franzi bzgl. des Themas angesprochen und dabei sind wir zu dem Ergebnis gekommen, dass die kleinen Flaggen unglücklich sind. Bei Deutsch, türkisch, englisch mag es noch relativ klar sein aber z.B. bei Arabisch wird es schwierig, genau eine passende Flagge zu finden.

Das ist wohl auch ein sensibles Thema unter den Geflüchteten, deshalb wäre es ohne die Flagge (so schick ich sie auch finde) wohl besser.

Davon unabhängig geht es um die unterstütze Sprachen bei dem konkreten Angebot (z.B. Sozialberatung auf türkisch) und nicht um die Sprache bei uns auf der Seite - das Wording mit 'X Version' ist also verwirrend. Das soll IMO auch nichts Auswählbares sondern einfach nur eine Information sein.

Vielleicht sollte man es eher als zusätzliches Element z.B. unter 'Wo erfährst du mehr im Netz?' machen: 'Welche Sprachen werden dort gesprochen?': Deutsch, Englisch, Türkisch.

**Comment by marcus-herrmann** [comment]
Verstehe. Hatte Bastis Formulierung oben irgendwie als "echtes Multilanguage" für Offers verstanden und deswegen in einer Navigation gedacht. Es ist also mehr eine Metainfo zum Offer.

**Comment by NilsVollmer** [comment]
Echt Mehrsprachigkeit steht eher noch auf der Mittelfristigen TODO-Liste ;)

Ich werde Basti aber gleich nochmal auf das Thema ansprechen.

**Comment by Twiek** [comment]
Sorry, hatte mich da nicht klar genug ausgedrückt, es geht in der Tat darum, dass lediglich das Angebot in mehreren Sprachen angeboten wird, man es also auch dann wahrnehmen kann, wenn man z.B. nur türkisch spricht. Es geht nicht darum, dass die clarat Webseite übersetzt wird. Insofern hat Nils recht und man müsste mal schauen, ob es dafür einen extra Kasten gibt, oder es an die bisherigen Informationen rangehängt wird wie z.B. eine dezentere Variante des 'What to do next' wie sie hier zu finden ist: https://www.1deg.org/opp/enroll-in-an-afterschool-sports-and-technology-program-for-girls-in-6-7th-grade.

**Comment by Twiek** [comment]
Ansonsten sehe ich die Flaggen (leider) auch kritisch und tendiere zu einer Lösung wie 'Hindi | हिन्दी', also erst den Namen der Sprache auf Deutsch und dann in der jeweiligen Landesschreibweise.

**Comment by Twiek** [comment]
Ok, das Issue wurde gerade noch mal um eine zusätzliche Herausforderung ergänzt: Es ist zu erwarten, dass es künftig mehrere Angebote geben wird die sich ausschließlich durch die Angebotene Sprache und andere Öffnungszeiten unterscheiden. Herausforderung ist nun die unterschiedlichen Sprachen bereits in der Suchergebnisseite anzuzeigen, auch mobil... Lass uns drüber sprechen.

**Comment by marcus-herrmann** [comment]
@Twiek Ist die Aussage noch aktuell - und besprechen wir es am 19.11.?

**Comment by Twiek** [comment]
@marcus-herrmann: Thema ist aktuell, aber lass es uns in diesem Issue beschränken. In der Angebotseinzelansicht folgende Bitten:

1. Einen Entwurf machen in dem es überhalb der Karte einen weitere, tendenziell grüne Box gibt in denen die verschiedenen Sprachen in denen das Angebot wahrgenommen werden kann, angezeigt werden. Bitte einmal nur mit 'Deutsch', einmal mit 'Deutsch, Arabisch | عربي, Russisch | НА РУССКОМ' und einmal mit 'Deutsch, Arabisch | عربي, Hindi | Hindi हिन्दी, Russisch | НА РУССКОМ, Türkisch | TÜRKÇE' sowie einem Link 'weitere Sprachen' + eine Ansicht bei der man diesen Link schon geklickt hat und diese Box nach unten ausfährt um weitere Sprachen anzuzeigen (in Beispiel noch 'Spanisch | MUNDO, Japanisch | 日本語'). Also bis auf Deutsch immer erst den Deutschen Namen der Sprach und dann durch eine Pipe (|) getrennt die native Schreibweise. Anzahl der direkt angezeigten Sprachen und inwiefern die Kommatrennung Sinn mach tbd.

2. Falls Dir eine ansprechendere Lösung einfällt, gerne kundtun.

Alles weitere (Suchergebnisseite etc.) in anderen Issues.

**Comment by marcus-herrmann** [comment]
Folgendes mal als visuelles Brainstorming und v.a. Frage, ob ich das Briefing richtig verstanden habe:

![offer show3](https://cloud.githubusercontent.com/assets/505181/11558733/a4608342-99b4-11e5-80a0-e1e2540c8c12.png)
![offer show2](https://cloud.githubusercontent.com/assets/505181/11558732/a45eb3dc-99b4-11e5-88f1-6378c8132a1b.png)
![offer show1](https://cloud.githubusercontent.com/assets/505181/11558734/a46219aa-99b4-11e5-986c-af59acf293b6.png)
![offer show0](https://cloud.githubusercontent.com/assets/505181/11558735/a46786f6-99b4-11e5-95d7-cf6f26873014.png)

(Newsletter-Button noch braun, bitte ignorieren)

**Comment by marcus-herrmann** [comment]
Korrigierte Fassungen, in dem ich die Pipe mal durch einen Doppelpunkt ersetzt habe. Das Pipe-Symbol hat naturgemäß eine seltsame Zeilenhöhe und macht den gesamten Bezeichner (der im Falle von Arabisch eine andere Grundlinie hat) **noch** unruhiger:

![offer show--1sprache](https://cloud.githubusercontent.com/assets/505181/11711872/cddc28fa-9f29-11e5-84ad-7d9d3939d691.png)
![offer show--3sprachen](https://cloud.githubusercontent.com/assets/505181/11711873/d0f1a01a-9f29-11e5-9a24-fcd428a2997a.png)
![offer show--5sprachen](https://cloud.githubusercontent.com/assets/505181/11711877/d65a2f4a-9f29-11e5-85f8-d50aa9f7a96d.png)
![offer show--7sprachen](https://cloud.githubusercontent.com/assets/505181/11711879/d8201c2c-9f29-11e5-8f43-622c7477c91f.png)

**Comment by marcus-herrmann** [comment]
![offer show--ohneicons](https://cloud.githubusercontent.com/assets/505181/11714568/67111b3c-9f3b-11e5-93ce-376365ed3f35.png)

**Comment by Twiek** [comment]
Thanks. Bitte die Version ohne die Sprechblasen und mit den Gedankenstrichen (last one) umsetzen.

**Comment by marcus-herrmann** [comment]
![offer show__1](https://cloud.githubusercontent.com/assets/505181/11871354/4c1662e4-a4cf-11e5-8b4d-109ecc66b9f1.png)
![offer show__3](https://cloud.githubusercontent.com/assets/505181/11871355/4c19059e-a4cf-11e5-9783-542cbf30b59b.png)
![offer show__5](https://cloud.githubusercontent.com/assets/505181/11871356/4c1a5e8a-a4cf-11e5-9a39-27a2ee68fa82.png)
![offer show__7](https://cloud.githubusercontent.com/assets/505181/11871357/4c1ad252-a4cf-11e5-95d5-681ae580f23c.png)

**Comment by marcus-herrmann** [comment]
PR gestellt, #625

**Comment by Twiek** [comment]
Bitte noch dafür sorgen, dass die aktuell ausgewählte Sprache (standardmäßig Deutsch) nicht zweimal angezeigt wird, also z.B. nie 'Deutsch - Deutsch' oder wenn man künftig ins Englische wechselt 'English - English' zu sehen ist. Stattdessen einfach nur 'Deutsch' bzw. 'English'.
