### ISSUE TITLE
Stop memory leakage in Heroku

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#456]
Fehler finden und eliminieren!

**Comment by Twiek** [comment]
Scheint sich hauptsächlich um diesen Fehler zu handeln: https://devcenter.heroku.com/articles/error-codes#r14-memory-quota-exceeded

**Comment by KonstantinKo** [comment]
Hab jetzt so einiges zu dem Thema gelesen. Dass eine App mit heroku's 512MB Speicher auskommt scheint zwar möglich, aber es ist nicht ungewöhnlich, dass es darüber hinaus schießt. Vor allem, wenn viele Objekte aus AR geholt werden müssen. ("If you have a 1G of data in the table, ActiveRecord representation of it will take 2G and, in some cases, more" -[Quelle](https://www.airpair.com/ruby-on-rails/performance)) Das ist bei uns im Backend stark der Fall, und was Rails Admin sich intern für AR-Objekte und Felder zieht, können wir nicht beeinflussen und optimieren. Es sei denn, ich soll Core-Entwickler bei Rails Admin werden.

Ruby braucht recht viel memory, da der verbrauch tendenziell bis zu einem gewissen Punkt leicht ansteigt. Der Punkt unterscheidet sich je nachdem was routine-mäßig instanziert wird (siehe oben). Das liegt an der Art und Weise wie der Garbage Collector funktioniert. Er fragmentiert:
![](http://collectiveidea.com/assets/54e54b90c0d6714a9e025aeb/malloc_memory_fragmentation.png)
([Quelle](http://collectiveidea.com/blog/archives/2015/02/19/optimizing-rails-for-memory-usage-part-2-tuning-the-gc/))
Das lässt sich nicht wirklich vermeiden, man kann nur probieren den GC öfter laufen zu lassen, damit mehr Platz frei wird. Keine Ahnung ob das auf heroku geht, aber ich kann's probieren.

Man sieht auch beim heroku profile: Im Allgemeinen steigt der Memory-Verbrauch nur langsam. Dann, sobald es die 500MB Schwelle erreicht schießt es natürlich in die Luft weil swap verwendet werden muss und das ist keine Dauerlösung.

> "The first rule of optimization is, “Don’t do it.” Of course, experienced developers still optimize from time to time because “don’t do it” is really shorthand for several warnings […] Do you know the root of the problem? If not, find it. Otherwise you will guess and probably guess wrong."
- [Quelle](http://collectiveidea.com/blog/archives/2015/02/19/optimizing-rails-for-memory-usage-part-1-before-you-optimize/)

Das ist wohl unser größtes Problem, wir haben nur sehr geringfügige Möglichkeiten, auf heroku zu profilen, und selbst mit guten Möglichkeiten ist es ein langwieriger und fitzeliger Prozess. Es gibt tools, gems, skripte etc. die einem helfen aber trotzdem.


Ich empfehle, was auch immer sonst getan wird, trotzdem ein upgrade auf 1GB memory pro web dyno. Wir haben nunmal eine erhöhte Last durch viele gleichzeitig arbeitende Researcher und RA optimieren ist schwer bis nicht möglich.
Wenn wir mal separate Instanzen für Frontend & Admin-Backend haben, können wir das evtl nochmal zurückschrauben.

Zusätzlich können wir noch andere Optimierungen probieren, je nachdem wie viel Zeiteinsatz meinerseits es euch wert ist.

Übrigens, bei Fairmondo hatten wir glaube ich mehrere 2GB RAM Maschinen und bei  Besucherinflux sind die trotzdem in die Knie gegangen. Das waren zwar massig mehr Leute als unsere Besucher zahlen, aber die haben alle nur Daten ausgelesen und wenig writes gemacht. Bei uns ist das anders und writes sind tendenziell teurer, vor allem bei unseren ganzen Validierungen.

**Comment by Twiek** [comment]
Was würdest Du genau empfehlen? Von einem Standard-1X dyno auf einen 2X upgraden? Auch für den worker dyno?

**Comment by KonstantinKo** [comment]
Genau, 2X für den Web-Dyno. Sobald wir mehr traffic haben sollten wir uns auch überlegen, ob wir nicht zwei davon haben sollten. Den worker können wir wahrscheinlich noch ziemlich lange auf 1 mal 1X lassen.
