### ISSUE TITLE
"Hast du einen Fehler entdeckt?" - Contact Form überarbeiten

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#458]
Wenn in dieser contact form keine E-Mail angegeben wird, muss der Sender ein anderer als post@clarat.org sein. Die E-Mails landen sonst nicht bei Freshdesk.

**Comment by Twiek** [comment]
@jjungle Welche E-Mail soll denn verwendet werden? Eine von den speziellen Asana-Mails?

**Comment by Twiek** [comment]
Als Absender E-Mail bitte 'fehler@clarat.org' nutzen. Diese Mail existiert aktuell allerdings nicht. Wenn das problematisch ist, bitte Rückmeldung, dann lege ich die an.

**Comment by KonstantinKo** [comment]
Was ist mit E-Mails über dieses Formular, bei denen doch eine optionale E-Mailadresse angegeben wurde?

Also, sollen alle Kontaktanfragen vom "Hast du einen Fehler entdeckt?"-Contact-Form an fehler@clarat.org gehen oder nur Kontaktanfragen von diesem Form ohne E-Mail-Adresse und der Rest weiterhin an post@…?

**Comment by jjungle** [comment]
Hier gibts ein Missverständnis:
Die Mails sollen nach wie vor immer an post@clarat.org geschickt werden.
Es soll sich lediglich folgendes ändern:

Wird keine optionale E-Mailadresse angegeben, soll die E-Mail TO: post@clarat.org FROM: fehler@clarat.org gesendet werden.

Wird eine optionale E-Mailadresse angegeben, soll die E-Mail TO: post@clarat.org
FROM: 'angegebene E-Mail'  gesendet werden.

**Comment by KonstantinKo** [comment]
Alles klar. Done. Liegt als Mini-Fix, direkt auf develop.
