### ISSUE TITLE
'history' und 'other' als mögliche Note-Topics entfernen.

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#459]
@jjungle: Bitte schreibe in das Issue, was mit den Notes passieren soll, denen aktuell das Topic 'other' zugeordnet ist (IDs dieser Notes: 15, 16, 18, 19). Dann das Issue Konstantin zuweisen.

**Comment by jjungle** [comment]
15, 16, 18, 19 können ignoriert werden.

**Comment by KonstantinKo** [comment]
Nein, können sie nicht. Wenn das Topic entfernt wird, muss ein anderes dafür eingesetzt werden.

**Comment by jjungle** [comment]
Sorry, mit ignorieren meinte ich löschen. Sollte eigentlich letzte Woche bereits händisch erledigt werden.

**Comment by KonstantinKo** [comment]
Konflikt mit #439 -> History wird benötigt. Was ist dort der Ersatz? Warum überhaupt die Löschung?

**Comment by Twiek** [comment]
History sollte künftig nicht mehr benötigt werden (siehe letztes Kommentar zu #439.

Grund für Löschung ist, dass es nicht benötigt wird und unnötige Auswahlmöglichkeiten verwirren.

**Comment by KonstantinKo** [comment]
Auf claradmin & clarat_base umgesetzt.
