### ISSUE TITLE
Karte und Kartenbutton ausblenden, wenn keine Ergebnisse gefunden wurden

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#463]
![bildschirmfoto 2015-09-16 um 10 16 23](https://cloud.githubusercontent.com/assets/432388/9899758/55e9c79a-5c5c-11e5-9422-e17dd6b1be35.png)

**Comment by NilsVollmer** [comment]
Ich nutze die Gelegenheit und arbeite mich in die Search Logik ein ;)

**Comment by NilsVollmer** [comment]
Sollte soweit klappen - bitte überprüfen ;)
