### ISSUE TITLE
'Auf großer Karte anzeigen' Button weg

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#466]
<img width="1253" alt="bildschirmfoto 2015-09-17 um 14 51 06" src="https://cloud.githubusercontent.com/assets/432388/9933543/cbba7d30-5d4b-11e5-906b-0c6974426be2.png">

**Comment by NilsVollmer** [comment]
Hab's im branch 463-hide-map-and-button eingebaut weil es inhaltlich dazu gehört.

**Comment by Twiek** [comment]
Klappt bei mir lokal aber irritierender Weise nicht auf staging. Please check.

**Comment by NilsVollmer** [comment]
Nach einigem Cache-gefrickel sollte es jetzt klappen ;)
