### ISSUE TITLE
Aufgeklapptes Suchfeld überlagert Suchergebnissüberschrift (mobile)

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#470]
Siehe Screenshots:
![bildschirmfoto 2015-09-22 um 14 32 17](https://cloud.githubusercontent.com/assets/432388/10018420/dba631fa-6136-11e5-8b18-2490b54f95fb.png)
![bildschirmfoto 2015-09-22 um 14 32 27](https://cloud.githubusercontent.com/assets/432388/10018424/e20ed182-6136-11e5-885c-197bdbdcad25.png)

**Comment by marcus-herrmann** [comment]
Bewusst damals so gebaut. Gewünsches Verhalten, dass es den Content nach unten schiebt statt überlagert?

**Comment by Twiek** [comment]
Sorry, soll jetzt doch so umgesetzt werden, dass es den Content nach unten schiebt.

**Comment by marcus-herrmann** [comment]
Zusammen mit #420 gelöst und entsprechend auf dem Featurebranch https://github.com/clarat-org/clarat/tree/feature/420-advanced-search
