### ISSUE TITLE
HTML-Vorschau bei Angebots- u. Orgaerstellung abschaffen

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#471]
Description html
Next steps html

Bei der Erstellung und Anzeige von Orgas und Offers im Backend nicht mehr benötigt.

![asdf](https://cloud.githubusercontent.com/assets/11425826/10100511/9aaf4e8a-6392-11e5-9c85-9a97c8a0e8f2.JPG)
![asdf2](https://cloud.githubusercontent.com/assets/11425826/10100510/9aad73e4-6392-11e5-966e-d2189318ca25.JPG)

**Comment by NilsVollmer** [comment]
Felder in Branch feature/471... ausgeblendet und Pull Request erstellt
