### ISSUE TITLE
Auch bei einer Suche in Brandenburg darauf hinweisen, dass wir dort noch nicht tätig sind

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#473]
Vorerst bei jeder Suche außerhalb Berlins darauf verweisen, dass wir hier noch nicht tätig sind. Alte Angebote aus Brandenburg werden erstmal gelöscht. Textanpassung ist schon umgesetzt.

![bildschirmfoto 2015-09-25 um 17 26 01](https://cloud.githubusercontent.com/assets/432388/10104548/8b1e81b2-63aa-11e5-94d8-5f9c49612652.png)

**Comment by NilsVollmer** [comment]
@Twiek  Das modale Fenster hängt an einer Suche, die an der angegebenen Location (im Fall oben: Dortmund) mit einem Radius von 25 km nach Angeboten sucht. Wenn keine Angebote gefunden wurden, wird das entsprechende Fenster angezeigt. Am Rande von Brandenburg, nahe an Berlin wird man also trotzdem Angebote in Berlin finden, was ich aber auch in Ordnung finde weil die dann ja auch relativ nah und gut zu erreichen sind.

Insofern müsste es eigentlich schon funktionieren, wenn man in Gebieten sucht, in denen keine Angebote in der Nähe sind. Wenn ich als Ort "brandenburg" auf staging eingeben, geht das Fenster auch auf (noch mit altem Text). Das trotzdem Angebote gefunden wurden, liegt daran, dass die tatsächliche Suche im Moment mit einem Radius von 50 km arbeitet und die beiden Suchen dementsprechend nicht ganz im Sync sind.
