### ISSUE TITLE
Anzahl der Angebote pro Kategorie stimmt nicht

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#476]
Siehe z.B. bei 'ein Kind zur Adoption freigeben':

<img width="1276" alt="bildschirmfoto 2015-09-22 um 16 31 51" src="https://cloud.githubusercontent.com/assets/432388/10138410/9eb9b2cc-65fe-11e5-8866-be9e1520c170.png">

**Comment by NilsVollmer** [comment]
@Twiek , @KonstantinKo  Das Problem scheint mehrere Schichten zu haben. Es scheint an der Suche zu liegen - die Facet-Dictionaries decken sich mit der Anzeige im Frontend. Ich habe es mir auf production und staging angeschaut.

Erstens scheint meistens die Navigationsleiste Dinge zu verschweigen. Es steht da also eine falsche (zu geringe) Zahl. Oft ist das dann 0 obwohl ein paar Ergebnisse vorhanden sind oder eine zu geringe Zahl (8 links aber 10 Ergebnisse rechts). Bis jetzt habe ich den Fehler immer nur im Zusammenhang mit den Personel(facet) Suche gesehen - die Remote Suche scheint soweit in Sync mit der MainSearch zu sein. 

Zum Beispiel Basti's Screenshot oder der hier:
![image](https://cloud.githubusercontent.com/assets/1733220/10165074/8b134854-66bd-11e5-8497-63dc3ebba83c.png)


Zweitens habe ich auch folgendes beobachtet (sowie auf frisch indiziertem staging aber auch auf production):
![image](https://cloud.githubusercontent.com/assets/1733220/10164769/b7e7613c-66bb-11e5-8066-5cc3438c9d6b.png)

Das ist natürlich bitter: während beim ersten Fall links nur ein paar Ergebnisse in der Summe fehlen, wird im zweiten Fall eine Ergebnisanzahl angezeigt aber man kann nicht auf die Ergebnisse zugreifen.

Category.find(525).offers.approved.count auf der staging console ergibt 36, die Navileiste scheint also korrekter zu sein.. Also gibt es in der MainSearch anscheinend auch noch Probleme
