### ISSUE TITLE
Skater Clara macht Probleme

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#482]
Skater Clara verdeckt Buttons:

**Bei höheren Seitenzahlen in den Suchergebnissen:**

![skater clara macht probleme](https://cloud.githubusercontent.com/assets/11425826/10219122/7b984174-683c-11e5-90c0-36e34e43219f.JPG)

**Comment by Twiek** [comment]
Durch die verschiedenen Sprachen gibt es an verschiedener Stelle Probleme (z.B. auch im Suchfeld). Das können wir nicht alles für alle Sprachen optimieren, auch da sich Übersetzungen mit der Zeit (hoffentlich) ändern (GO CANADA... )

**Comment by jjungle** [comment]
Das Problem "Bei höheren Seitenzahlen in den Suchergebnissen:" besteht allerdings auch in der unübersetzten Variante.

**Comment by Twiek** [comment]
@marcus-herrmann: Any ideas? U.a. hier zu beobachten: http://www.clarat.org/family/angebote?search_form%5Bpage%5D=10.

**Comment by marcus-herrmann** [comment]
@Twiek: lässt sich hotfixen mit etwas mehr Innenabstand (Headspace, im wahrsten Sinne des Wortes) für den Footercontainer, der Skaterclara umgibt.

**Comment by Twiek** [comment]
@marcus-herrmann: Na dann los.

**Comment by marcus-herrmann** [comment]
Als Hotfix auf develop
