### ISSUE TITLE
clarat refugees - Backend Version 1

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#484]
- [x] Filter mit dem Angebote entweder 'family', 'refugees' oder 'family and refugees' zugewiesen werden könne. Alle bestehenden Angebote bekommen nachträglich 'family' zugewiesen. Pflichtfeld.

- [x] Die age_to Validierung (<= 17) greift nur für 'family' und 'family and refugees' Angebote. Falls nicht umsetzbar dies Validierung vorerst deaktivieren.

**Comment by KonstantinKo** [comment]
Deploy TODO:
```ruby
TargetAudienceFilter.find_by_identifier('family').update_columns(name: 'Kernfamilie', identifier: 'nuclear_family')
family = SectionFilter.create!(name: 'Family', identifier: 'family')
SectionFilter.create!(name: 'Refugees', identifier: 'refugees')
Offer.find_each { |offer| offer.section_filters << family }
```

**Comment by KonstantinKo** [comment]
Ist auf clarat_base & claradmin umgesetzt.

**Comment by Twiek** [comment]
Vor Deploy auf Production auf jeden Fall noch #486 und #487 umsetzen.

**Comment by Twiek** [comment]
https://github.com/clarat-org/clarat/issues/471 scheint nicht mitgekommen zu sein. @jjungle: Bitte auch noch mal mithelfen und checken was eventuell beim Umzug durchgerutscht ist bzw. was nicht mehr funktioniert/fehlt.

**Comment by KonstantinKo** [comment]
#471 nochmal reimplementiert.

**Comment by jjungle** [comment]
Von den letzten Issues scheint sonst alles mitgekommen zu sein.
Was mir noch aufgefallen ist:
Age to & Age from sollten erstmal auch für clarat-r verpflichtend sein.
Mit Chrome bekomme ich keine Fehlermeldungen wenn ich verpflichtende Dropdowns nicht auswähle. Mit Firefox wird zumindest "Bitte wählen sie einen Eintrag in der Liste" angezeigt.

**Comment by KonstantinKo** [comment]
@jjungle 

> Age to & Age from sollten erstmal auch für clarat-r verpflichtend sein.

Bist du dir da 100% sicher? Das war nämlich **extra** eine Anforderung (siehe zweiter Stichpunkt im ursprünglichen Kommentar) auf das ich auch nochmal gesondert hingewiesen wurde.

**Comment by jjungle** [comment]
Hatte mit Nicole darüber gesprochen, wäre durchaus sinnvoll auch bei 'clarat-r' Altersgrenzen mit festzuhalten. Die extra Anforderung besagt ja nur das die '<= 17' logik bei 'clarat-f' und 'clarat-f&r' Angeboten greifen soll, nicht aber bei 'clarat-r only' Angeboten. Das Altersangaben für 'clarat-r only' Angebote gar nicht mehr verpflichtend sind steht da ja nicht.

**Comment by NilsVollmer** [comment]
Mir ist gerade noch aufgefallen, dass trotz der Validation und der entsprechenden Fehlermeldung ein Angebot ohne section_filters gespeichert werden kann. (Auf Staging gibt es auch schon ein paar Angebote ohne clarat-welt)

**Comment by KonstantinKo** [comment]
@NilsVollmer Ich bekomme es nicht hin, auf staging ohne section_filters ein Angebot zu speichern. Bitte mal Klickweg aufschreiben damit ich's nachvollziehen kann.

**Comment by NilsVollmer** [comment]
@KonstantinKo Vermutlich klappt es nur beim editieren - bei den Kategorien klappt es beim erstellen auch nicht aber beim editieren schon. Also einfach ein vorhandenes Angebot editieren, dann bei den Welten "alle löschen" klicken und speichern. Dann kommt zwar die Fehlermeldung aber es wird anscheinend trotzdem gespeichert (sieht man z.B. in der Übersicht)

**Comment by KonstantinKo** [comment]
@jjungle 

> Age to & Age from sollten erstmal auch für clarat-r verpflichtend sein.
> […]
> Die extra Anforderung besagt ja nur das die '<= 17' logik bei 'clarat-f' und 'clarat-f&r' Angeboten greifen soll, nicht aber bei 'clarat-r only' Angeboten

OK ich dachte da sollen alle Validierungen raus. Trotzdem ist die Anforderung auch dann ungenau, daher muss ich nochmal nachhaken:

Es steht oben nur die Validierung bei `age_to` <= 17 soll raus. So eine gibt es gar nicht. Es gibt nur eine `age_to` <= 1**8**. Es gibt auch eine `age_from` <= 17. Ich gehe davon aus, dass beide raussollen, richtig? Ich gehe erstmal davon aus und habe das so umgesetz.

Es gibt auch eine Validierung, die besagt, dass `age_from` kleiner als `age_to` sein muss. Die hab ich dann auch für refugees wieder reingenommen.

--------------

> Mit Chrome bekomme ich keine Fehlermeldungen wenn ich verpflichtende Dropdowns nicht auswähle. 

Ist ein bekannter Bug für den es ohne ein eigenes Backend keine praktikable Lösung gibt und hat nichts mit refugees zu tun (gibts auch gerade auf production). Weiterhin *wont-fix*

--------------

@NilsVollmer 

> Also einfach ein vorhandenes Angebot editieren, dann bei den Welten "alle löschen" klicken und speichern. Dann kommt zwar die Fehlermeldung aber es wird anscheinend trotzdem gespeichert

Da hast du einen Bug gefunden, der für alle verpflichtenden Filter gilt und auch auf production existiert. Manchmal scheint es wohl ganz gut zu sein, auch einfach bestehende Dinge mal wieder gründlich zu testen.
Aber da es nichts mit refugees zu tun hat pack ich den bug in ein anderes Issue. Scheinbar scheinen Leute ja bisher auch klug genug gewesen zu sein, nicht einfach im Nachhinein wieder Filter zu löschen.

-------------------

Damit ist dies Issue von meiner Seite aus wieder "done".

**Comment by NilsVollmer** [comment]
@jjungle Ich habe auf staging den aktuellen branch mit den clarat-Welten für Kategorien gepushed. Das bitte auch direkt testen.
