### ISSUE TITLE
Broken Script-Links (bei Google Translate) fixen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#485]
Wenn man die Seite per Google-Translate übersetzt, dann lassen sich die Kategorielinks nicht klicken (bei den Oberkategorien scheint es zu gehen, wenn man nicht direkt auf das Wort klickt).

**Comment by NilsVollmer** [comment]
direkt als unschöner hotfix auf develop umgesetzt

**Comment by jjungle** [comment]
Betrifft auch die unteren Seitenzahlen in den Suchergebnissen.

**Comment by NilsVollmer** [comment]
Auch problematisch: Kategorie-Anzahl verschwindet mit translate manchmal

Screen:
![image](https://cloud.githubusercontent.com/assets/1733220/10760229/c715351a-7cbb-11e5-8706-0ee6f767d718.png)

**Comment by NilsVollmer** [comment]
Translate zerstört auch einige Links: 
vorher: 
![image](https://cloud.githubusercontent.com/assets/1733220/10760625/ba0867a0-7cbd-11e5-86a7-2702d1008841.png)

nachher:
![image](https://cloud.githubusercontent.com/assets/1733220/10760667/efc9ccd0-7cbd-11e5-93ad-564228eb5113.png)

**Comment by NilsVollmer** [comment]
Die Links sollten damit wieder funktionieren. Der fehlende Count bei den Kategorielinks ist ein wenig tricky. Ich konnte es so eingrenzen, dass es anscheinend eine Art Race-Condition ist, die nur manchmal beim Page Reload auftritt. Dann wird der Search-Presenter neu erstellt und bevor die Suchergebnisse da sind, rendert der ein paar Dinge vor - u.A. auch die Kategorielinks nur mit ihrem Namen, also ohne Count dahinter. Vermutlich läuft dann GoogleTranslate los und übersetzt das. Da die Übersetzung aber immer ein paar Sekunden dauert, kommt es manchmal vor, dass die Suchergebnisse da sind, bevor GoogleTranslate die Inhalte ausgetauscht hat. In dem Fall kriegt GoogleTranslate nichts von den aktualisierten Counts der Suchergebnisse mit (bzw. die neue Übersetzung wird verworfen weil noch eine pending ist) und übersetzt kurz danach den Ausgangswert, der nunmal nur die Namen darstellt.

Wenn GoogleTranslate schneller als die Suchergebnisse ist, klappt es wie gewollt: es werden erst die Namen übersetzt, dann kommen die Ergebnisse und hängen die Counts hinten dran und Translate übersetzt diese erneut, was dann das gewünschte Ergebnis produziert. 

Um das zu fixen, müssten wir entweder GoogleTranslate zu einer neuen Übersetzung zwingen können oder sehr viel an der Generierung unserer Page ändern..

**Comment by NilsVollmer** [comment]
Auf Staging deployed & PullRequest erstellt.

**Comment by NilsVollmer** [comment]
@KonstantinKo https://en.wikipedia.org/wiki/Google_Translate#Translation_methodology

**Comment by Twiek** [comment]
@jjungle Bitte kommunizieren und dann schließen.
