### ISSUE TITLE
In App Vorschau von Angeboten

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#486]
Als Reseacher will ich aus dem Backend direkt zu einer Frontendvorschau einzelner Angebote oder Organisationen gelangen können, egal ob diese 'approved' sind oder sich in einem anderen Status befinden.

**Comment by KonstantinKo** [comment]
umgesetzt auf claradmin

**Comment by Twiek** [comment]
Sollten das sicherheitshalber direkt nach dem Deploy noch mal checken. Auf Staging nur schwer zu testen, da man da ja immer nen Passwort braucht um irgendwas zu sehen.
