### ISSUE TITLE
Weltenfilter für Kategorien

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#487]
Auch Kategorien brauchen analog zu den Angeboten einen 'Weltenfilter'. Siehe auch 'Lila-Kategoriebaum'.

**Comment by Twiek** [comment]
Bitte direkt mit dem Kategorien-Team klären, inwiefern alle bisherigen Kategorien automatisch der 'family-Welt' zugeordnet werden können.

**Comment by NilsVollmer** [comment]
Auf entsprechenden Branches auf clarat_base & claradmin umgesetzt

**Comment by NilsVollmer** [comment]
zum TODO siehe #492

**Comment by KonstantinKo** [comment]
Der Fehler ist, wie in 484 gesagt, separat und sollte refugee Issues nicht beeinflussen.

**Comment by NilsVollmer** [comment]
Deploy TODO:

family = SectionFilter.find_by name: 'Family'
Category.find_each { |category| category.section_filters << family}
