### ISSUE TITLE
Auf clarat-family werden nur Kategorien der 'family-Welt' angezeigt

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#488]
Im Anschluss an https://github.com/clarat-org/clarat/issues/487 ist sicherzustellen, dass auch in der Übergangsphase bevor clarat-refugees live geht, im Frontend nur die Kategorien zu sehen sind, die zumindest auch der 'family-Welt' zugeordnet sind.

**Comment by NilsVollmer** [comment]
Basiert natürlich auf #487 und allem was damit zusammenhängt

**Comment by NilsVollmer** [comment]
Die eingeschränkte Suche scheint schonmal zu funktionieren.. Der Kategoriebaum ist eine eigene Baustelle ;)

**Comment by NilsVollmer** [comment]
Auf entsprechenden Branches von clarat_base & clarat umgesetzt und aktuell auf Staging deployed. Darf dann gerne ausprobiert werden ;)

**Comment by NilsVollmer** [comment]
Deploy TODO: Rails cache clear & Offers neu indizieren

**Comment by Twiek** [comment]
@KonstantinKo Bitte PullRequest checken. 'Inhaltlich' macht das was es soll.
