### ISSUE TITLE
verpflichtende Backend-Dropdowns geben bei Nichtausfüllen keine Fehlermeldung aus

### ISSUE THREAD

**Issue by JulianJung** [clarat-org/clarat#490]
In Chrome passiert nichts wenn man auf speichern klickt und ein verpflichtendes Dropdown nicht ausgefüllt hat. Firefox gibt zumindest bescheid das irgendeine Liste nicht ausgefüllt wurde.

Mit folgenden Dropdowns getestet:
Organizations => Legal form
Offer => Encounter
Offer => Note Topic
Location => Federal State
Contact Person=> Organization

**Comment by NilsVollmer** [comment]
Fehlermeldung: 
An invalid form control with name='location[federal_state_id]' is not focusable.

**Comment by NilsVollmer** [comment]
Zitat Konstantin: "Ist ein bekannter Bug für den es ohne ein eigenes Backend keine praktikable Lösung gibt und hat nichts mit refugees zu tun (gibts auch gerade auf production). Weiterhin wont-fix"

**Comment by jjungle** [comment]
Alles klar, dann per Newsticker dafür sensibilisieren alle Dropdowns bei Speicherproblemen zu checken.
