### ISSUE TITLE
expired, 'nicht personal' Angebote tauchen in den Suchergebnissen im Frontend auf

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#491]
offer show dennoch nur eingeloggt möglich.
Bsp.: Offer  ID 1971

**Comment by jjungle** [comment]
![image](https://cloud.githubusercontent.com/assets/11425826/10333803/a0fbde7c-6ce6-11e5-8f92-2b4c1380a938.png)

**Comment by NilsVollmer** [comment]
Tauchen fälschlicherweise bei den Suchergebnissen auf, sind dann aber nicht einsehbar (was ja auch korrekt ist).

**Comment by NilsVollmer** [comment]
Bei Algolia ist das Angebote noch im state 'approved', intern allerdings bereits auf 'expired'. Das Problem ist also ein fehlerhafter sync zwischen unserer DB und Algolia.

**Comment by NilsVollmer** [comment]
als hotfix direkt auf master umgesetzt und die bereits expired Angebote manuell neu indiziert. Somit sollte auf production jetzt wieder alles passen.

**Comment by jjungle** [comment]
http://www.clarat.org/admin/offer/1561
expired, aber dennoch im frontend

**Comment by NilsVollmer** [comment]
Bug gefunden und (hoffentlich) behoben. Direkt auf _base master umgesetzt aber auf production nicht mehr. Lohnt sich für die paar Tage nicht so richtig. Ich werde abends immer einen manuellen reindex bei den expired angeboten triggern, damit es auf production bis zum deploy zu keinen Inkonsistenzen kommt.

**Comment by NilsVollmer** [comment]
Und die Tests entsprechend angepasst ;)

**Comment by NilsVollmer** [comment]
@jjungle Bitte schauen, ob das Problem seit Dienstag noch aufgetreten ist. Alle Angebote, die seitdem expired sind (Asana task erstellt) sollten im Frontend mit der Suche nicht mehr auffindbar sein.
