### ISSUE TITLE
Pflichtfilter können gelöscht werden

### ISSUE THREAD

**Issue by KonstantinKo** [clarat-org/clarat#492]
Verpflichtende Filter können im admin backend nachträglich wieder herausgenommen werden. Beim Speichern gibt es dann zwar eine Fehlermeldung, aber die Änderung wird trotzdem übernommen.

(gefunden in #484)

**Comment by KonstantinKo** [comment]
Zwischenstand vorm Urlaub: 

Fix ist erstaunlich kniffelig. Hab mir gestern ein paar Stunden hierüber den Kopf zerbrochen. Schon der folgende Test schlägt fehl:

```ruby
offer = FactoryGirl.create :offer
offer.reload.section_filters.count.wont_equal 0 # so weit so gut
offer.section_filters = []
offer.reload.section_filters.count.wont_equal 0 # fail! dabei wurde noch kein #save aufgerufen. Passiert instant bei der Zuweisung.
```

Selbes tritt auch auf bei `offer.assign_attributes section_filters: []` und allen anderen dingen von denen ich dachte, sie würden die Änderungen nicht gleich speichern. Dasselbe wird auch intern bei rails_admin passieren: sie weisen die parameter aus dem Formular zu, wollen dann validieren, aber es ist bereits zu spät.

Problem ist vermutlich ein `autosave` auf der habtm Beziehung von Filtern und Angeboten. Aber auch `autosave: false` behebt das Problem nicht.

Meine Vermutung ist, dass wir die habtm durch eine `has_many :through` ersetzen müssen. Was dann passieren muss um diese Automatisierung abzustellen weiß ich auch noch nicht, aber ich glaube nicht, dass ein fix ohne das möglich ist.

Falls das also in meiner Abwesenheit schonmal jemand anfangen möchte (@NilsVollmer?), das wäre der Startpunkt.

**Comment by NilsVollmer** [comment]
Gerade bei einer anderen Sache gefunden. Nur Titel gelesen aber der passt soweit.
https://github.com/TylerRick/has_and_belongs_to_many_with_deferred_save

**Comment by Twiek** [comment]
Problem ist ja nach wie vor vorhanden (z.B. bei der Target_Audience). Ist es möglich das im aktuellen Backend zu fixen (mit ansatzweise überschaubarem Aufwand), oder sollten wir ein neues Ticket fürs neue Backend draus machen?

**Comment by KonstantinKo** [comment]
Also, `has_many :through` zeigt dasselbe Verhalten, ist also keine Alternative. Das gem was @NilsVollmer gefunden hat ist für Rails 2 und seit 6 Jahren nicht maintained. Die Rails Dokumentation sagt, man solle `collection.build()` benutzen, aber das bekommen wir rails_admin natürlich nicht so leicht verklickert.

Fazit: Praktisch nicht im aktuellen Backend behebbar.

**Comment by Twiek** [comment]
Ist zu erwarten, dass das im neuen Backend noch ein Problem ist? Wenn nein einfach schließen.

**Comment by KonstantinKo** [comment]
Nein, so ein Mist passiert uns mit Operations (wenn richtig eingesetzt) nicht mehr. Ein Hoch auf's Backend 2.0!
