### ISSUE TITLE
Definitions werden im Frontend nicht angezeigt

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#493]
Wenn ich eine Definition mit z.B. den Keys 'Weisung, Weisungen' anlege und im der Descriptions eines Angebots das Wort 'Weisungen' auftaucht, so wird die Definition auch nach mehrfachem Abspeicherns des Angebots nicht angezeigt.

**Comment by NilsVollmer** [comment]
Kleiner Bug in dem entsprechenden Code:
Ruby '''
occurence = string.downcase.index(key.downcase)
'''
durch 
Ruby '''
occurence = string.downcase.index(/\b(#{key.downcase})\b/i)
'''
austauschen. Mache ich dann später, wenn der Deploy auf die Dreifaltigkeit durch ist.

**Comment by NilsVollmer** [comment]
Fix inklusive entsprechendem Test direkt auf _base master umgesetzt

**Comment by jjungle** [comment]
Scheint noch nicht zu funktionieren?
http://www.clarat.org/angebote/beratung-fuer-straffaellige-jugendliche-von-14-bis-21-jahren-10589
