### ISSUE TITLE
Umbrella-Auswahl 'öffentliche Hand' lässt sich nicht speichern

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#494]
Wenn man in einer Organisation 'öffentliche Hand' als Umbrella auswählt, lässt sich die Orga nicht speichern. => Error 500

**Comment by NilsVollmer** [comment]
@jjungle Macht Sinn:
```ruby
    t.string   "umbrella",               limit: 8
```
```ruby
  enumerize :umbrella, in: %w(caritas diakonie awo dpw drk asb zwst dbs vdw bags
                              svdkd bkd church hospital public_authority other)
```
 Wie dringlich ist der fix? Reicht es mit dem deploy der Dreifaltigkeit (spätestens Anfang nächster Woche) ?

**Comment by Twiek** [comment]
Ich behaupte jetzt einfach mal ja. Insofern schon mal auf develop umsetzen (das Limit entsprechend erhöhen).

**Comment by jjungle** [comment]
Ja, kann bis nächste Woche warten.

**Comment by NilsVollmer** [comment]
War lokal nicht reproduzierbar (save hat geklappt) aber auf staging besteht der Fehler auch - scheint also nur auf in zusammenspiel mit Heroku zu passieren. Deshalb direkt auf clarat_base master umgesetzt und auf staging getestet.

**Comment by NilsVollmer** [comment]
Da man das alte 'public_authority' ja nicht speichern konnte gibt es auch kein deploy todo
