### ISSUE TITLE
Notizen auch auf Organisationsebene ermöglichen

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#497]
Notes sollten auch auf Organisationsebene verfügbar sein.
Die Themen-Auswahlmöglichkeiten sollten hier  'To Do' und 'External Info'  sein.

**Comment by NilsVollmer** [comment]
Nach Absprache mit Julian ohne Einschränkung der Auswahlmöglichkeiten.

**Comment by NilsVollmer** [comment]
Als Einzeiler direkt auf develop umgesetzt.
