### ISSUE TITLE
Notizen in der Angebotsansicht - Sortierung anpassen

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#499]
Es wäre hilfreicher Notizen in der Angebotsansicht direkt am Anfang aufzuzeigen.

**momentaner Stand:**

![image](https://cloud.githubusercontent.com/assets/11425826/10480250/6cc4e5ee-7269-11e5-903c-42dd78ee5d0b.png)

**Wunsch:**

![image](https://cloud.githubusercontent.com/assets/11425826/10480268/9062861e-7269-11e5-8d09-860acdbe781b.png)

**Comment by NilsVollmer** [comment]
Auf claradmin im Sammelbranch 'minor-features' umgesetzt
