### ISSUE TITLE
Favicon fürs Backend

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#500]
Zum Bekämpfen der Tab Wust wurde ein Favicon fürs Backend gewünscht.

Vorschlag war diese Wolke:
![image](https://cloud.githubusercontent.com/assets/11425826/10481056/80b50e8a-726e-11e5-80c2-ff673e5efe77.png)

**Comment by NilsVollmer** [comment]
Die Wolke ist sehr klein und unscheinbar - wie wäre es mit einem grünen Zahnrad?
![image](https://cloud.githubusercontent.com/assets/1733220/10540243/a5990244-7406-11e5-9640-864d947d94b6.png)

**Comment by jjungle** [comment]
Gerne nochmal mit dem clarat 'c' oder 'a' probieren
