### ISSUE TITLE
Google Translate selektiv deaktivieren

### ISSUE THREAD

**Issue by NilsVollmer** [clarat-org/clarat#501]
Die Researcher würden die Übersetzungen von Google gerne selektiv deaktivieren können. Damit sollen dann z.B. Eigennamen von Organisationen unangetastet bleiben oder auch nativ übersetzte Texte im Original behalten werden.

TODO: noch abklären, in welchen Texten das funktionieren soll.

Denkbar ist ein eigenes kleines Markup z.B. wie der Markdown renderer also wenn z.B. aus der description die description_html generiert wird.

Die Organisation __Organame__ bietet... => The organization Organame offers...

**Comment by Twiek** [comment]
Bitte noch mal alle Bereiche sammeln die nicht übersetzt werden sollen. Als 'nice to have' unter Umsetzungsvorbehalt auch gerne getrennt auflisten wo im Text einzelne Bereiche nicht übersetzt werden sollen (z.B. Organame in der Description).

**Comment by jjungle** [comment]
Nahezu alles in diesem div (offers-show)

<div class="adr">
also die span classes:
offer-location-name
extended-address
street-address
postal-code
locality
Listing-organizations__list

"Ein Angebot von:" sollte jedoch übersetzt werden.

(organizations-show)
Ebenfalls im div <div class="adr">

die span classes:
street-address
postal-code
locality

Sowie die class page-detail__title


Bei den Kontaktpersonen sollte wenn dann, lediglich "Telefon" übersetzt werden.
