### ISSUE TITLE
Offer to Categories validations

### ISSUE THREAD

**Issue by NilsVollmer** [clarat-org/clarat#502]
Beim speichern eines Angebots soll validiert werden, ob die Welten des Angebots mit denen der ausgewählten Kategorien übereinstimmen.

**Comment by NilsVollmer** [comment]
Auf clarat_base master umgesetzt und auf staging deployed. Beim speichern/erstellen eines Angebots werden die Welten-Filter mit denen der zugeordneten Kategorien validiert und entsprechend Fehler geworfen, wenn eine Angebots-Welt nicht in einer Kategorie enthalten ist.

@jjungle Gerne testen ;)

**Comment by jjungle** [comment]
Funktioniert.
