### ISSUE TITLE
Suchanfragen dauerhaft speichern

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#503]
Aktuell können wir über Algolia nur die Suchanfragen der letzten 2 Wochen auswerten. Künftig wollen wir auch auf historische Daten zurückgreifen.

Dafür bitte alle 14 Tage einen Export der Suchanfragen der letzten 14 Tage durchführen (Details zur API finden sich hier: https://www.algolia.com/doc/rest#analytics-api).

Kernbestandteil sollen die einzelnen Suchstrings sein, wie oft diese gesucht wurden. zusätzlich die 'Average Hits' und die 'Average Hits without Typos' (Wording etc. siehe auch Algolia Backend).

Dabei folgende 'nice to haves' berücksichtigen:

- [ ] Characters/Search
- [ ] Words/Search
- [ ] Results/Search

Vgl.:

<img width="1177" alt="bildschirmfoto 2015-10-15 um 12 27 22" src="https://cloud.githubusercontent.com/assets/432388/10511229/1f4a53ba-7338-11e5-93e2-62507a04916c.png">

- [ ] Der Name des Dokuments sollte den genauen Zeitraum beinhalten (z.B. clarat Suchanfragen 01.10.2015 - 14.10.2015).
- [x] Das Format sollte es ermöglichen direkt in Google-Drive geöffnet und ausgewertet zu werden.
- [x] Neben den einzelnen Dokument sollte es ein kumuliertes geben in welchem immer nur die neusten Daten ergänzt werden und bei dem gleiche Suchbegriffe automatisch summiert werden.

Grundlegende Fragen gerne erstmal mündlich klären.

**Comment by NilsVollmer** [comment]
Kann ich mir gerne anschauen. Ist natürlich akut durch die Eingaben des Teams verfälscht - nicht so wie bei Analytics was wir ja per plugin blocken.

**Comment by KonstantinKo** [comment]
Characters/Search, Words/Search und Results/Search bekomm ich aus der API nicht leicht raus, müsste man bei starkem Interesse evtl. selbst ausrechnen aus den Suchdaten die man bekommt.
Ansonsten kannst du dir aber auch mal die Sachen anschauen, die man sonst noch so von der API bekommt. Z.B. Suchanfragen mit 0 (oder geringen) Ergebnissen, Häufigste IPs, etc. Vielleicht ist davon ja was interessant. Sind dann aber neue Issues, da dafür getrennte Anfragen laufen müssen.

**Comment by KonstantinKo** [comment]
Aaalso das ist jetzt so gelöst (großteils mündliche Absprache):

Es gibt ein Dokument in unserem clarat Google Drive im Ordner IT namens "Suchstatistiken". Dieses enthält ein Google Script, welches ich weiter unten reinkopieren werde.

Das Script läuft von Google automatisiert jeden Sonntag um 23:55 Uhr und aktualisiert die Tabelle mit den 100 häufigsten Suchanfragen seit Montag 0:00 Uhr. Average Hits (mit & ohne Typos) werden dort in den einzelnen Spalten ersetzt, der Count wird immer oben drauf gerechnet.

(Achtung: Counts könnten evtl. leicht falsche kumulierte Anzahlen anzeigen, weil ja nur von den 100 beliebtesten die Anzahlen geholt und draufgerechnet werden)

Testen ist bei der ganzen Sache etwas schwierig. Am besten man schaut immer mal am Montag morgen was sich getan hat und vergleicht es mit einer manuellen Kopie des Dokuments von der vorhergehenden Woche.

```js
// Automated function: Runs once at the end of the week. Will update the sheet with the latest search statistics data.
function onTick(e) {
  // Request stats for last week from Algolia
  
  //- get start and end timestamp
  var today = new Date();
  var lastMonday = new Date(today.setDate(today.getDate() - today.getDay() + 1));
  var endOfWeek = new Date(today.setDate(lastMonday.getDate() + 6));
  var startAt = lastMonday.setHours(0,0,0,0) / 1000;
  var endAt = endOfWeek.setHours(23,59,59,999) / 1000;
  
  //- send API request
  var headers = {
    'X-Algolia-API-Key': '...',
    'X-Algolia-Application-Id': '...'
  };
  var options = {
    'method': 'get',
    'headers': headers
  };
  var url = 'https://analytics.algolia.com/1/searches/Offer_production_personal/popular?startAt=' + startAt + '&endAt=' + endAt
  var response = UrlFetchApp.fetch(url, options);
  //Logger.log(response);
  var json = response.getContentText();
  var data = JSON.parse(json);
  var newData = data.topSearches;
  //Logger.log(data.topSearches);

  // Display the data in the sheet
  
  //- Get existing historical data from the sheet
  var sheet = SpreadsheetApp.getActiveSpreadsheet().getSheets()[0];
  var historicalData = sheet.getDataRange().getValues();
  for (var i = 1; i < historicalData.length; i++) {
    Logger.log('A: ' + historicalData[i][0]);
    Logger.log('B: ' + historicalData[i][1]);
  }
  
  //- Merge the existing data with the new: count is cumulatively added, the rest is replaced with new data
  for (var i = 0; i < newData.length; i++) { /// for every new piece of data...
    var newColumn = newData[i];
    var queryAlreadyExists = false;

    for (var j = 1; j < historicalData.length; j++) { /// search every pice of old data...
      var oldColumn = historicalData[j];
 
      if (oldColumn[0] == newColumn.query) { /// if the query of the new piece is found, merge it
        queryAlreadyExists = true;
        oldColumn[1] = newColumn.avgHitCount;
        oldColumn[2] = newColumn.avgHitCountWithoutTypos;
        oldColumn[3] = oldColumn[3] + newColumn.count;
        break;
      }
    }
    
    if (!queryAlreadyExists) { /// if the query of the new piece was not found, append it
      historicalData.push([newColumn.query, newColumn.avgHitCount, newColumn.avgHitCountWithoutTypos, newColumn.count])
    }
  }
  
  //- Clear the existing sheet
  sheet.clear();
  
  //- Write the new data array as a table in the now empty sheet
  sheet.appendRow(['Query', 'Average Hits', '...without Typos', 'Count']);
  for (var i = 1; i < historicalData.length; i++) {
    sheet.appendRow(historicalData[i]);
  }
  sheet.autoResizeColumn(1);
  sheet.autoResizeColumn(2);
  sheet.autoResizeColumn(3);
  sheet.autoResizeColumn(4);
}
```

**Comment by Twiek** [comment]
Bei mir ist die Tabelle leider leer. Bitte noch mal checken.

**Comment by KonstantinKo** [comment]
Lösung war, den angefragten Suchindex auf `Offer_production_personal_de` zu stellen, also mit neuer locale-Endung. Wenn das ganze auch mit anderen Sprachen funktionieren soll, ist das ein neue Feature Wunsch (bitte dieses Issue referenzieren)
