### ISSUE TITLE
Keine Refugee-Only Hauptkategorien auf der Landing Page

### ISSUE THREAD

**Issue by NilsVollmer** [clarat-org/clarat#506]
Hauptkategorien, die Refugee-Only sind, dürfen (vorerst) nicht im Frontend der Landing Page auftauchen. Am besten direkt per World selektieren (aktuell hardcoded 'family', später dann wechselbar).

**Comment by NilsVollmer** [comment]
Könnte man für den Übergang hotfixen, indem man den Kategorien kein icon zuweist - aber in wenigen Wochen muss das ja sowieso funktionieren.

**Comment by KonstantinKo** [comment]
@Twiek das hier geht dann erst mal wieder zurück an dich bis es eine Entscheidung gibt, mehr zu tun als nur zu hotfixen

**Comment by NilsVollmer** [comment]
Direkt als commit feature/family-refugees umgesetzt.
