### ISSUE TITLE
Duplizieren von Angeboten anpassen

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#509]
Beim Duplizieren von Angeboten sollte folgendes wenn ausgefüllt mit dupliziert werden:

'Clarat-Welten'
'Name'
'Description'
'Next Steps'
'Legal information'
'Contact people'
'Encounter'
'Location'
'Area'
'Organizations'
'Categories'
'Language filters'
'Target gender'
'Target audience filters'
'Age from'
'Age to'
'Openings'
'Opening specification'
'Websites'
'Keywords'

Nicht dupliziert werden sollten:
'Comment'
'Notes'
'Creator' des Ursprungangebots (Hier sollte der Creator des Duplikats einfach derjenige werden der gerade dupliziert)

'Expires at'  - Hier sollte, wie in der normalen Angebotserstellung, einfach Duplizierdatum + 1 Jahr gelten

'Renewed'
'Zustand'

**Comment by NilsVollmer** [comment]
Auf https://github.com/clarat-org/clarat_base/commit/94d70790a6f11bb2914d70b4033de8b182710788 umgesetzt. Claradmin Update in #499 enthalten. https://github.com/clarat-org/claradmin/commit/f16c31b44d101c4fd39a8e7d87f0506c67bbcdb8

**Comment by jjungle** [comment]
Funktioniert.
