### ISSUE TITLE
Kategorien und Karte scrollen auf der Suchergebnisseite immer mit

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#510]
D.h. sie verschwinden nicht wenn an runterscrollt (siehe Screenshot):

![bildschirmfoto 2015-10-21 um 17 23 48](https://cloud.githubusercontent.com/assets/432388/10641236/a2aeb590-7818-11e5-846d-7332d927ccea.png)

Nur für Desktop.

**Comment by marcus-herrmann** [comment]
Funktion wurde im Februar entfernt. Wird refaktoriert wieder eingebaut

**Comment by marcus-herrmann** [comment]
Hier erstmal zur Betrachtung: https://github.com/clarat-org/clarat/tree/fix/510-return-of-sticky-sidebar

HTML von offers#index hatte sich seit Februar verändert, darum hat das etwas länger gedauert.

**Comment by Twiek** [comment]
Also bei mir lokal klappts es noch nicht so wirklich...

<img width="1279" alt="bildschirmfoto 2015-11-06 um 11 40 42" src="https://cloud.githubusercontent.com/assets/432388/10995182/4f092f50-847b-11e5-8c34-d9b4a5f52e99.png">

**Comment by marcus-herrmann** [comment]
Habe die Schwellenwerte erhöht, ab dem die "Stickyness" aktiviert wird. Zudem der abgebildeten Situation (sehr wenige Angebote in der Hauptspalte), geringe Viewporthöhe.

Ausserdem develop in den fix branch gemergt. Hoffe, die merge conflicts in eurem Sinne gelöst zu haben. Wenn ja, kann ich jederzeit einen PR in develop stellen

**Comment by Twiek** [comment]
Bei mir sieht es lokal noch immer so aus:

<img width="754" alt="bildschirmfoto 2015-11-18 um 10 28 07" src="https://cloud.githubusercontent.com/assets/432388/11237280/23e6d2a6-8ddf-11e5-8d96-01f56fc7c0f2.png">

Bitte noch mal checken und mich dann ansprechen.

**Comment by marcus-herrmann** [comment]
So eine Kollision zwischen Sidebar und Footer habe ich letzten Donnerstag via JS ausgeschlossen, sieht mir nach einen noch nicht geclearten Cache aus.

Aber danke für den Hinweis mit den Merge-Resten (<<<<<HEAD). Habe ich gerade durch einen weiteren Commit auf dem Branch entfernt, bitte auschecken, und cache:clear

**Comment by Twiek** [comment]
Cache gecleart und es sieht tatsächlich anders aus, aber leider nicht besser (man muss einmal runter und dann wieder hochscrollen). Sowohl in Chrome als auch in FF:

![bildschirmfoto 2015-11-18 um 12 02 59](https://cloud.githubusercontent.com/assets/432388/11239470/863bf442-8dec-11e5-9b55-fa518e0e63ee.png)

**Comment by marcus-herrmann** [comment]
Bitte nochmal pullen, siehe letzter Eintrag von mir. Sehe in deinem Screenshot noch das "<<<<< HEAD"-Fragment

**Comment by Twiek** [comment]
Ja, warum auch die Kommentare bis zum Ende lesen... Sorry dafür.

Jetzt klappts, bitte Pull-Request stellen.

**Comment by NilsVollmer** [comment]
Sehr verrückt: ich habe das heute vor dem merge auf Staging getestet und nach einem cache.clear hat es funktioniert und ich habe es gemerged. 

Jetzt habe ich es gerade auf production deployed (und auch in den aktuellen master gezogen) und den cache gecleared aber es funktioniert einfach nicht. Stattdessen klappe die adv. search dann nicht mehr auf.

Habe jetzt aus Zeitmangel bei heroku einen rollback gemacht und werde mir das dann morgen auf dem aktuellen master anschauen..

**Comment by NilsVollmer** [comment]
Ich habe den PR-merge jetzt reverted und nochmal auf dem 510er branch nachgeschaut - da ist irgendwie einiges im Frontend kaputt gegangen. Folgendes ist mir aufgefallen:

- die Adv. Search klappt nicht mehr auf
- die mitscrollende Sidebar funktioniert nicht
- das mobile layout (mindestens auf dem iPhone5, vermutlich S) ist total kaputt

@marcus-herrmann Lass uns morgen mal gucken, wo, warum und was da kaputt gegangen ist.. ich hatte das auch gestern lokal getestet und da hat es noch funktioniert.. stehe gerade ein wenig auf dem Schlauch und wir haben auch noch einen High Prio Bug, der Vorrang hat.

**Comment by marcus-herrmann** [comment]
Vereinbarungsgemäß nochmal auf Basis eines neueren Develop-Standes rekonstruiert, hier: https://github.com/clarat-org/clarat/tree/fix/510-sticky-sidebar-new-approach

(Wäre PR-geeignet)

**Comment by NilsVollmer** [comment]
Jetzt klappt es grundsätzlich und die Fehler sind auch draußen. Es passiert aber noch etwas komisches wenn man unten ankommt: dann bounced die linke Leiste ein gutes Stück nach oben. Ist jetzt nicht mega kritisch aber es fällt schon auf, finde ich. 

Da im Moment aber andere Dinge eine höhere Prio haben, schlage ich vor, dass wir am kommenden Donnerstag mit @Twiek zusammen entscheiden, wie viel Zeit in dieses Feature noch fließen soll.

**Comment by marcus-herrmann** [comment]
Das ist gewünschtes Verhalten und soll bei niedrigen Viewports oder kurzen/niedrigen Suchergebnislisten die Kollision mit dem Footer auf jeden Fall vermeiden

**Comment by NilsVollmer** [comment]
Dann bitte den entsprechenden PR erstellen und das Ticket @Twiek zum Review zuweisen.
