### ISSUE TITLE
Karte vergrößern in der Angebotseinzelansicht

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#511]
Egal wohin ich auf der Karte klicke (auch auf den Pöpel), geht eine große Karte mit genau diesem Pöpel genau in der Mitte auf (Vgl. ‚Karte vergrößern‘ auf der Suchergebnisseite). Es gibt keinen gesonderten Hinweis auf diese Funktion.

![bildschirmfoto 2015-10-21 um 17 26 58](https://cloud.githubusercontent.com/assets/432388/10641455/99f86198-7819-11e5-9849-292da5614a98.png)

**Comment by marcus-herrmann** [comment]
In welchem Browser tritt das auf?

Live oder Staging oder development-Stand?

**Comment by NilsVollmer** [comment]
Ich glaube da ist eher ein gewünschtes Feature als ein Bug-Report. Ist allerdings eher wie letzteres formuliert ;)

**Comment by marcus-herrmann** [comment]
UX/UI-Vorschlag: Anstelle der komplett klickbaren Karte analog zu "Offer#index" ein Button unter ihr, der die Big Map öffnet. Denn es könnte etwas irritieren, wenn man die Google Map Controls in der kleinen Karte nicht wie gewohnt bedienen kann.

**Comment by NilsVollmer** [comment]
Ich denke, dass die GUI-Elemete schon wie gewohnt klickbar bleiben sollen und nur wenn man die Karte darunter klickt, soll die große Karte angezeigt werden.

Die Drag-Controls auf der Map sollten natürlich weiterhin funktionieren.

**Comment by Twiek** [comment]
Tue mich nach weiterer Überlegung mit einem weiteren Button schwer, sehe aber auch, dass man nicht GUI-Elemente anzeigen sollte die dann nicht funktionieren. Kann man denn alternativ die GUI-Elemente in der kleinen Karte ausblenden / nicht anzeigen?

**Comment by marcus-herrmann** [comment]
Laut Dokumentation ja: https://developers.google.com/maps/documentation/javascript/examples/control-options

Das für die Kartenerzeugung zuständige JS ist aktuell ein deprecated module in `javascripts/modules/gmaps` - wenn ich die Datei richtig verstehe ist sie sowohl für die Karte auf offer#show und die Karte auf offer#index zuständig.

Im Zuge eines Refactors könnte man den Karten unterschiedliche Konfigurationen mitgeben: `mapTypeControl: false, zoomControl: false` für offer#show und `true`für offer#index. Soll ich das angehen?

**Comment by KonstantinKo** [comment]
TODO für mich:
- GMaps code refactoren
- control switch einbauen  ( @Twiek Ich nehme an die Lösung ohne Controls soll genommen werden? )
- an Marcus zurückgeben

**Comment by KonstantinKo** [comment]
OK also refactoring ist soweit durch dass damit weitergearbeitet werden kann. (branch `feature/511-mapclick-enlarges-map`)

Ich habe zum Test die UI controls wie vorgeschlagen ausgebaut. Das hat aber natürlich auch zur Folge, dass sie in der vergrößerten Ansicht auch nicht da sind, da es ja dieselbe map ist die wir da anzeigen.
Die Controls in der Fußzeile (Datenschutzinformationen etc.) können nicht ausgeschaltet werden.

Im Vorbild yelp wird das ganz anders gemacht, mithilfe von static maps (https://developers.google.com/maps/documentation/static-maps/).

Was interessant ist: Da ich im Moment die Kartenvergrößerung auf mousedown im map-container aufrufe, kann ein Nutzer in der kleinen Map anfangen die Karte zur Seite zu ziehen und dieser Befehl wird mit in die große Map übernommen. Selbes würde auch mit dem Ziehen vom StreetView-Männchen klappen, nicht aber mit einzelnen Klicks auf andere Bedienelemente (da diese unter der Maus wegspringen bevor mouseup ausgelöst wird)

Außerdem: Es erscheint mir nicht zielführend, für dieselbe Funktionialität zwei verschiedene Nutzerintefaces zu haben: index & show haben Kartenansichten die man vergrößern kann. Beim einen geht das über Knopfdruck, beim anderen durch Klick auf die Karte. Man könnte es doch genausogut vereinheitlichen - und wenn kein Button auf die show Seiten kommen soll, dann lass uns doch auch die Karte in der Suchansicht per Klick darauf vergrößern. (Den Button könnte man auch trotzdem noch da lassen. Ist zur Zeit auf dem branch so umgesetzt)

**Comment by Twiek** [comment]
Bitte Code bei Bedarf aktualisieren, jedoch ein unterschiedliches Verhalten für die Suchergebnisansicht und die Angebotseinzelansicht umsetzen. Bei den Suchergebnissen muss auf den 'Karte vergrößern' Button geklickt werden. Ein Klick in die Karte hat keine entsprechende Funktion. In der Angebotseinzelansicht führt jeder Klick in der Karte zu einer Vergrößerung (wie aktuell in 511 umgesetzt).

**Comment by NilsVollmer** [comment]
Ich kann mich @KonstantinKo da nur anschließen: zwei verschiedene Interaktionsmöglichkeiten für ein quasi gleiches UI-Element (einziger Unterschied ist die Anzahl der Marker) sind eher verwirrend als sinnvoll. Ganz davon abgesehen, dass es wahrscheinlich zu Spagetti-Code führen würde.

Das Problem an der aktuellen Umsetzung ist, dass die Karte durch den Instant OnClick nicht mehr gut zu benutzen (Klick auf Marker oder Mouse-Down für Map-Drag maximiert sofort die Karte, was mich ziemlich irritiert). Man könnte also die Maximierung erst bei einem Klick (MouseUp and Down) und nur auf der Karte (nicht auf den Markern oder den InfoBoxen) ausführen.

**Comment by Twiek** [comment]
Aktuell liegt ein Fehler vor, d.h. in der Einzelansicht wird die Karte nicht vergrößert, in der Suchergebnisansicht schon. Sollte aber genau umgekehrt sein.

Auf der Angebotseinzelansicht dann die Höhe des Containers von 300px auf 150px reduzieren und alle GUI-Elemente (außer Nutzungsbedingungen etc.) rausnehmen (bei den Suchergebnissen gerne anzeigen). Dann ist es für den User auch klarer, dass es unterschiedliche Arten von Karten sind und diese auch unterschiedlich funktionieren können.

**Comment by KonstantinKo** [comment]
OK habs auf develop fixed

**Comment by Twiek** [comment]
Bitte noch die Karte in der Angebotseinzelansicht verkleinern (150px).

**Comment by KonstantinKo** [comment]
OK done

**Comment by Twiek** [comment]
Top, danke.
