### ISSUE TITLE
Backbutton simulieren (bei der Pagination)

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#513]
Wenn ich z.B. von der Startseite auf die Suchergebnisseite komme und dort in der Pagination auf 'Seite 2' klicke und dann den Backbutton des Browsers nutze, komme ich zurück auf die Startseite und nicht auf 'Seite 1' meiner Suchergebnisse, dies sollte aber der Fall sein.

**Comment by KonstantinKo** [comment]
Sorry, hab vergessen einen branch hierfür anzulegen. Ist jetzt schon auf develop commited. Ist aber auch nur ein commit, Code-Unterschied kann also auch direkt dort reviewed werden.

**Comment by Twiek** [comment]
@KonstantinKo Ist das schon deplyed? Klappt bei mir nicht.

**Comment by KonstantinKo** [comment]
Ahh. Erinnerst du dich, wie ich vorhin gesagt hab, ich hab was gelöscht um den Safaribug zu beheben aber war mir eigentlich sicher dass das wichtig war? Hierfür war's.

**Comment by KonstantinKo** [comment]
Jetzt klappt's auch auf production

**Comment by NilsVollmer** [comment]
Hat einen kleinen Fehler produziert, der mit #543 gefixt wurde
