### ISSUE TITLE
Ausgefahrene, erweiterte Suche wenn ich per Backbutton zurück zu gefilterten Suchergebnissen komme

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#514]
Wenn ich bei einer Suche die Filter nutze, dann auf ein einzelnes Angebot klicke und dann den Backbutton nutze bleiben die zuvor gestzten Filter aktiviert, allerdings sind die erweiterten Suchoptionen nicht 'ausgeklappt'. Dies sollte der Fall sein.

**Comment by Twiek** [comment]
Funktioniert bei mir weder lokal noch auf Staging.

**Comment by KonstantinKo** [comment]
Funktioniert ja woohoool
