### ISSUE TITLE
Im Translator Drop-Down auch 'Deutsch' anzeigen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#516]
Im Translator Drop-Down die Auswahlmöglichkeit 'Deutsch' anzeigen. Im Idealfall nur, wenn aktuell eine andere Sprache ausgewählt ist. Funktion bei Auswahl die gleiche als wenn man oben auf 'Original anzeigen' klickt.

![bildschirmfoto 2015-10-21 um 18 08 05](https://cloud.githubusercontent.com/assets/432388/10642644/fcf71870-781e-11e5-8253-be00609a0296.png)

![bildschirmfoto 2015-10-21 um 18 09 51](https://cloud.githubusercontent.com/assets/432388/10642638/f9b6ee38-781e-11e5-8133-bccae4556e20.png)

**Comment by marcus-herrmann** [comment]
@Twiek : Laut @NilsVollmer gibt es eine Verlagerung der Übersetzungen vom Front- ins Backend. Das macht dieses Ticket irrelevant, vermute ich?
