### ISSUE TITLE
Prepare CSS for clarat seperation

### ISSUE THREAD

**Issue by marcus-herrmann** [clarat-org/clarat#519]

**Comment by KonstantinKo** [comment]
Auf `feature/family-refugees` wurde damit weitergearbeitet. Geh gern dazu über, auch auf dem branch weitere Arbeiten zur Separierung vorzunehmen.

**Comment by marcus-herrmann** [comment]
Tinos Design auf `feature/family-refugees` grundsätzlich umgesetzt, aktueller Develop reingemergt, cache clear, gecheckt, gepusht. PR?

**Comment by marcus-herrmann** [comment]
Icons nun auch drin
