### ISSUE TITLE
Asana Tasks benötigen die neue Backend URL

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#522]
In den Asana Tasks zu expired Angeboten #446 
muss künftig die alte Backend URL mit der neuen ersetzt werden.

**Comment by NilsVollmer** [comment]
Direkt als Hotfix mit #521angepasst.

**Comment by Twiek** [comment]
@jjungle Bitte checken und wenn es klappt das Issue schließen.

**Comment by jjungle** [comment]
Klappt leider noch nicht.
Bsp.: https://app.asana.com/0/44856824806357/61856427326694

**Comment by NilsVollmer** [comment]
Narf, sorry - hatte nur den ContactMailer erwischt und das eigentlich Wichtige (Asana) übersehen :/

Sollte jetzt korrekt funktionieren.

**Comment by Twiek** [comment]
@jjungle Funktioniert das jetzt? Wenn ja, bitte kommunizieren und das Issue schließen.

**Comment by jjungle** [comment]
Funktioniert.
