### ISSUE TITLE
Worker von clarat_base nach claradmin

### ISSUE THREAD

**Issue by KonstantinKo** [clarat-org/clarat#524]
inkl. Templates von clarat

Wurde im Zuge des clarat_base refactorings aus Zeitgründen übersprungen. Muss nachgereicht werden.

**Comment by NilsVollmer** [comment]
Siehe auch #521

**Comment by NilsVollmer** [comment]
Könnte ich mir vornehmen.

**Comment by KonstantinKo** [comment]
Kannst du machen wenn du möchtest

**Comment by NilsVollmer** [comment]
in allen drei Repos auf dem branch: refactor/524-workers-to-claradmin umgesetzt.

Deploy TODO: Env-Variablen für Mailchimp in claradmin setzen & Worker auf clarat de- und auf claradmin aktivieren

**Comment by NilsVollmer** [comment]
Merged und aktuell auf Staging deployed.
