### ISSUE TITLE
Sprachenfilter im Frontend updaten

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#527]
Nach LanguageFilter.name sortieren.

**Comment by NilsVollmer** [comment]
per Konsole sortiertert: 
150 326 568 639 amh ara aze ben bos bul deu ell eng fas fra hin hrv hun ita kur lav lit mkd pol por rom ron rus spa sqi srp tam tha tur urd vie wol

Die Zahlen müsste man wohl händisch korrekt platzieren ;)

**Comment by KonstantinKo** [comment]
Es sollte wohl nicht nach dem kürzel sortiert werden, sondern nach dem deutschen übersetzten Namen. Da kommt Griechisch dann nicht nach Deutsch.
Davon abgesehen wollte Basti sowieso gleich absprechen, welche Filter jetzt außerhalb der alphabetischen Reihe woanders platziert werden sollen (da man es ja sowieso händisch durchgehen muss)
