### ISSUE TITLE
Mouseover täuscht Link vor (Filter)

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#528]
Leider kann ich gerade keinen Screenshot machen, sollte aber leicht zu reproduzieren sein.

Wenn die Filter ausgeklappt sind und man z.B. bei 'Hilfe für wen?' den Cursor rechts neben z.B. die Worte 'für Eltern' zieht, so ändert er seinen Status und suggeriert einem, dass man klicken kann. Kann man aber nicht. Daher sollte der Cursor das einem auch nicht suggerieren oder man sollte halt doch klicken können.

**Comment by marcus-herrmann** [comment]
Mouseover-Fläche war viel zu groß eingestellt, jetzt haben wirklich nur die Labels ein "Hand"-Icon, gemäß u.a. http://webcode-blog.org/ein-simpler-usability-trick.

Als Hotfix auf develop
