### ISSUE TITLE
'virtuell' Filter und die Zahl hinter den Kategorien synchronisieren nicht richtig

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#529]
Im Screenshot lässt die Zahl hinter der ausgewählten Kategorie auf 47 Angebote hoffen, es wird aber nur ein einziges angezeigt. Insofern scheint die Zahl immer auch die 'vor Ort' Angebote mitzuzählen.

**Comment by KonstantinKo** [comment]
@Twiek Das hatten wir doch schonmal. Ist alles wie gewünscht. Es war doch vorher so, dass immer nur die Anzahl des aktuell ausgewählten contact_type angezeigt wurden, aber dann kam Issue #316 daher und es wurden extra queries eingebaut damit wir zusammenrechnen können.

**Comment by NilsVollmer** [comment]
Dann halte ich mir erst einmal raus, bis es eine Entscheidung gibt. ;)

**Comment by Twiek** [comment]
Ja, macht aber im Rahmen der erweiterten Suchoptionen noch weniger Sinn die Zahl nicht zu reduzieren, wenn nur die virtuellen oder nur die vor Ort Angebote angezeigt werden (wurde mir auch als Fehler aus dem Researchteam gemeldet).

Insofern sähe das komplette Wunschszenario wie folgt aus:

- vor Ort Angebote mit virtuellem Teaser: Die Zahl hinter den Kategorien entspricht der Gesamtzahl (virtuelle + vor Ort)

- nur virtuelle Angebote: Die Zahl hinter den Kategorien entspricht nur der Zahl der virtuellen Angebote (egal ob man hier über das Filtermenü hinkommt, oder über den Button 'Weitere Angebote' -> den werde ich übrigens gleich umbenennen in vorerst 'weitere virtuelle Angebote').
