### ISSUE TITLE
Angebote im Backend nach 'clarat-Welt' filtern

### ISSUE THREAD

**Issue by NilsVollmer** [clarat-org/clarat#532]
Die Researcher hätten im Backend bei den Angeboten gerne einen Filter für die clarat-Welt um sich dann z.B. alle approved Angebote, die 'Refugees' zugeordnet sind, anzeigen zu lassen.

**Comment by NilsVollmer** [comment]
Ist mit RailsAdmin wohl nicht so einfach, deshalb back to wishlist. Ich werde den Researchern dann erst einmal wöchentlich die Zahlen schicken, die sie haben wollen.

**Comment by jjungle** [comment]
Eine Sortierung nach clarat-Welt wäre als Workaround auch erstmal möglich.

**Comment by NilsVollmer** [comment]
Mein Stand ist, dass es mit der aktuellen habtm Verknüpfung nicht funktionieren kann. Möglicherweise klappt es mit has_many through.. dafür müssten wir die Assoziation zwischen offers und filters ändern und alle vorhandenen Daten migrieren.  Habe dazu das hier gefunden: http://craiccomputing.blogspot.de/2013/06/migrating-from-rails-habtm-to-hasmany.html
Würde das lieber in Zusammenarbeit mit @KonstantinKo angehen bzw. erst einmal abklären, ob diese Änderung das Problem überhaupt lösen würde.

**Comment by KonstantinKo** [comment]
Auch mit nem has_many through kann ich mir nicht so recht vorstellen, wie das mit Rails Admin funktionieren soll. Ich würde sagen wir packen das auf die Feature Liste für's eigene Admin-Backend.

**Comment by NilsVollmer** [comment]
Aber wäre das dann nicht analog zu dem, was wir zwischen Offers und Organizations machen? Da klappt das filtern nach Orga-Name auf Offer-Ebene ja auch (durch die Änderungen, die in http://blog.endpoint.com/2013/07/hasmany-filter-in-railsadmin.html). Der Unterschied wäre noch, dass es Filter und konkrete Filter (language_filters, section_filters etc.) gibt aber sollte es nicht dennoch funktionieren, dass man dann in RailsAdmin config bei section_filter searchable :name nimmt und dann im Backend bei den Angeboten Filters => Clarat-Welten => 'Family' eingibt und dann nur die entsprechenden Angebote bekommt?

**Comment by NilsVollmer** [comment]
Nach einem Tag try-and-error und Rücksprache mit @KonstantinKo erstmal wont-fix mit aktuellem Backend. 

Das umgebaute Model (offers <-> filters als has_many through anstatt habtm) ist in clarat-org/clarat_base auf dem branch feature/has-many-filters umgesetzt.
