### ISSUE TITLE
Bei fortgeschrittener Pagination (z.B. '20') führen Filter zur Anzeige von 0 Suchergebnissen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#533]
Da man dann noch immer auf Seite 20 ist, es dafür aber nicht genug Angebote gibt. Insofern sollte jeder Einsatz von Filtern dazu führen, dass man wieder auf Seite 1 kommt.

**Comment by KonstantinKo** [comment]
Sorry, hab eben erst gesehen dass es hierfür ein Issue gibt. Fix dafür ist schon auf develop.

**Comment by Twiek** [comment]
@jjungle Bei Bedarf kommunizieren.
