### ISSUE TITLE
Organization Show - Angebote wie in den Suchergebnissen anzeigen

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#536]
Die Liste der Angebote auf den Organisationseinzelseiten von der Optik bitte analog zu den Suchergebnissen anzeigen:

<img width="842" alt="bildschirmfoto 2016-03-11 um 15 20 49" src="https://cloud.githubusercontent.com/assets/432388/13704571/df4fc7f2-e79c-11e5-9453-2d9316644a74.png">

Sortierung weiterhin alphabetisch.

Eventuell auf das umschließende Kästchen ('Welche Hilfe bietet diese Organisation?') verzichten.

**Comment by marcus-herrmann** [comment]
Note to self:
[ ] Designvorschlag
[ ] Refugees-List, Family-List
[ ] Links (in LTR) Stamp, rechts Adresse

**Comment by marcus-herrmann** [comment]
Pull request gestellt.
