### ISSUE TITLE
Website Host Type für Orgas auf 'Own' begrenzen

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#537]
Fügt man einer Orga eine Website zu, wird im Frontend nur die Host Auswahl 'Own' angezeigt. Deshalb sollte im Backend auch lediglich 'Own' auswählbar sein.

**Comment by NilsVollmer** [comment]
@jjungle Das sollte nicht so sein und wäre dann ein Bug. Ich habe mir gerade stichprobenartig ein paar Angebote angeschaut, die eine 'Own'-Website und mindestens noch eine andere zugewiesen haben und habe keine gefunden, bei der im Frontend dann nur die 'Own'-Website auftaucht.

Hast du ein konkretes Angebot, bei dem die Anzeige falsch ist?! Vom Code her ist es nur so, dass wenn mehrere Website-Typen einem Angebot zugeordnet sind (z.B. 2x Facebook-Links) nur die erste der Websites im Frontend als Link auftaucht.

**Comment by jjungle** [comment]
Es ging hier um Orgas nicht um Offers. Da kann man zwar Facebook etc. auswählen, angezeigt wird aber lediglich die Websites mit 'Own'-Auswahl.

Bsp.:
http://claradmin.herokuapp.com/admin/organization/58

Zum P.S: Nicht schlecht, die ersten Orgas geben anscheinend ihre eigenen Webseiten auf :+1: clarat reicht ihnen anscheinend völlig

**Comment by NilsVollmer** [comment]
Stimmt, bei den Orga's wird die erste Website angezeigt, die 'own' ist. Dann schaue ich mir die Begrenzung der Auswahl auf 'own' im Backend mal an.

Zum P.S.: Ich glaube eher, dass Verlinkungen auf unsere Page unabsichtlich/aus Versehen oder zum Testen so eingetragen wurde ;)

**Comment by NilsVollmer** [comment]
@jjungle:
Update: eine Begrenzung des Drop-Down-Feldes auf 'own' ist nicht so einfach. Eine website ist eine website (mit all ihren Host-Typen) und der kann man nicht ohne weiteres beibringen, sich anders zu verhalten wenn sie einer Orga zugeordnet wird bzw. wenn sie aus einer Orga heraus erstellt wird. 

Schnell umzusetzen wäre allerdings eine validation inkl. Fehlermeldung. Man könnte also not-own-websites auswählen aber beim Speichern gibt es dann einen entsprechenden Fehler für jede not-own-website, z.B.
Webseite ... ist nicht Host 'own'
...
Alternativ natürlich nur eine Fehlermeldung für alle, dann müsste man aber händisch gucken, welche der Webseiten das Problem verursachen.

**Comment by jjungle** [comment]
Denke die Validation inkl.Fehlermeldung reicht dann. Ich weise in der Anleitung zum Backend auch nochmal explizit darauf hin.

**Comment by NilsVollmer** [comment]
PR auf _base erstellt, clarat & claradmin sind soweit fertig und es müssen nur noch die Gemfiles angepasst bundle update durchgeführt werden.

**Comment by NilsVollmer** [comment]
Ist bereits merged & deployed.
