### ISSUE TITLE
Disable Automailings

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#539]
Hier müssen dringend die Texte geändert werden. Bis dahin bitte erstmal keine weiteren Automailings rausschicken ('Ihr Angebot auf clarat... '). Allerdings aufgeschoben, nicht aufgehoben. Sobald wir es wieder aktivieren sollen alle benachrichtigt werden.

**Comment by KonstantinKo** [comment]
Ah, hierfür gab's auch ein Issue. Hab's in der Wishlist nicht gesehen. Wurde erledigt mit Commit 13c26d55d576293e3a50fbcd5afe4dcd6948f73f auf clarat-org/clarat_base
