### ISSUE TITLE
Neue URL-Struktur vorbereiten

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#540]
In Vorereitung auf die Aufteilung von clarat-Family und clarat-Refugees.

Startseite und statische Seiten: www.clarat.org/family/ bzw. www.clarat.org/refugees/ oder www.clarat.org/family/impressum.

Suchergebnisse und einzelne Angebote: www.clarat.org/family/angebote (hier werden nur Angebote aus der Family-Welt angezeigt) oder z.B. www.clarat.org/refugees/angebote/streetwork-fuer-jugendliche-am-alexanderplatz.

Organisationsseiten: www.clarat.org/family/organisationen/bezirksamt-charlottenburg ('organisationen', nicht 'organizations' wie bisher).

Wichtig:

1. Alle bisherigen URLs googlefreundlich umleiten (301 redirect).
2. Allen Seiten die textlich doppelt auftauchen (statische Seiten, gemischte Angebote und gemischte Organisationen) die Refugees-Seite per canonical URL aus Google-Sicht zum Default machen (https://support.google.com/webmasters/answer/139066?hl=de).

**Comment by Twiek** [comment]
Woher weiß eine Organisation in welcher Welt sie ist?

- Immer wenn ein Angebot approved ist und einer bzw. mehreren Organisationen zugeordnet wird übernimmt die Organisation die Welt(en) dieses Angebots (falls nicht schon gemacht). 
- Immer wenn ein Angebot approved wird übernehmen deren Organisationen die Welt(en) dieses Angebots (falls nicht schon gemacht). 
- Immer wenn einem Angebot eine weitere Welt hinzugefügt wird (oder eine entfernt wird) übernehmen deren Organisationen die Welt(en) dieses Angebots (falls nicht schon gemacht). Falls es sich um eine Entfernung handelt müssen auch alle anderen Angebote der Organisation geprüft werden um zu entscheiden, ob auch die Organisation diese Welt 'verlieren' kann.
- Immer wenn eine Organisation unapproved oder gelöscht wird werden bei allen seinen Organisationen auch alle anderen Angebote geprüft um zu entscheiden, ob auch die Organisation diese Welt 'verlieren' kann.

**Comment by KonstantinKo** [comment]
Branch hierfür ist `feature/family-refugees`. Würde vorschlagen, dass wir diesen Branch für alle sub-issues zum Split verwenden (sofern praktikabel)

**Comment by Twiek** [comment]
Auf Staging schwer zu testen, da alle Angebote in beiden Welten angezeigt werden und wenn man z.B. auf der Suchergebnisseite der Family-Welt ist und auf ein Angebot klickt, man in die Refugees Welt springt...

**Comment by KonstantinKo** [comment]
Ein cache clear später funktioniert es wie es soll.

**Comment by NilsVollmer** [comment]
Habe gerade noch ein wenig die Funktionalitäten geprüft und Folgendes ist mir noch aufgefallen:

- Subscribe und Kontakt funktioniert noch nicht
- wenn man auf einer Sub-Page die Section wechselt, kommt man nicht zu der jeweiligen Version der Sub-Page, die es aber durchaus gibt (z.B. /family/ueber-uns => /refugees/ueber-uns ), sondern zu /section/angebote. Solange da keine unterschiedlichen Inhalte vorhanden sind, sollte das aber kein großes Problem sein.

**Comment by NilsVollmer** [comment]
Update: das subscribe und contact nicht funktioniert, hat nichts mit fam/ref zu tun sondern vermutlich mit der Dreifaltigkeit. Ist auch gerade auf production der Fall.. habe dementsprechend ein Bug Ticket erstellt.

**Comment by KonstantinKo** [comment]
> wenn man auf einer Sub-Page die Section wechselt, kommt man nicht zu der jeweiligen Version der Sub-Page, die es aber durchaus gibt (z.B. /family/ueber-uns => /refugees/ueber-uns ), sondern zu /section/angebote. Solange da keine unterschiedlichen Inhalte vorhanden sind, sollte das aber kein großes Problem sein.

**Comment by NilsVollmer** [comment]
Da das hier ja quasi das Ticket von Refugees ist, schreibe ich es mal hier rein - ggf. ein eigenes Ticket daraus machen.

Julia hat mich darauf hingewiesen, dass das WebTranslator Gadget die Openings z.T. kaputt macht. Da die Übersetzung ja erst später fertig werden wird, brauchen wir ihrer Meinung nach für den Übergang eine Lösung für das Gadget. Probleme sind:
- in seltenen Fällen wird der Tag falsch übersetzt, es steht z.B. 2x Wednesday obwohl im Original Dienstag und Mittwoch steht.
- Mit Uhrzeiten kommt er nicht immer klar. Problematisch sind wohl vor allem Zahlen, bei denen nicht eindeutig ist, ob es am/pm oder 24h Format ist, also z.B. macht er aus 9:00 Uhr - 12:00 Uhr gerne mal 9 clock - 0 clock. Von der Übersetzung Uhr => clock mal ganz abgesehen ;)

Wenn wir das für den Übergang noch beheben wollen, bräuchten wir da entsprechende Lösungsansätze.. auch über ein notranslate-Tag um den ganzen Bereich sollte man da nachdenken, weil vor allem das zweite Problem ohne die wirkliche Übersetzung zu lösen sein könnte.

**Comment by KonstantinKo** [comment]
obiges mit @NilsVollmer besprochen: maximal quickfix mit notranslate, native Übersetzungen sollten das recht bald fixen.


*DEPLOY TODO*:
Kategorien icons anpassen

**Comment by Twiek** [comment]
Fixen wir dann direkt mit der Datenbankgestützten Übersetzung. Bis dahin müssen wir mit den Fehlern leben.
