### ISSUE TITLE
Suche 'lädt sich tot' (Safari only)

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#542]
Wenn man aktuell Develop auf staging testet und auf der Startseite den Suchbutton klickt, wird die Suchergebnisseite nicht richtig geladen bzw. macht den Eindruck, als würde sie ständig versuchen sich zu refreshen ohne jemals auch nur ein Ergebnis anzuzeigen. In Chrome oder Firefox lässt sich der Fehler nicht reproduzieren.

**Comment by KonstantinKo** [comment]
auf develop hotfixed
