### ISSUE TITLE
Suchwörter in den Titeln highlighten

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#545]
Auf der Suchergebnisseite sollten die Suchwörter in den Angebotstiteln gehighlightet werden.

**Comment by NilsVollmer** [comment]
Auf staging deployed - bitte Funktionalität checken.

**Comment by Twiek** [comment]
Funktioniert, aber die Farbe macht mich fertig... ;-)

Bitte mal mit dem dunklen braun versuchen oder reiner 'Hervorhebung' falls das mit der weißen Schrift irgendwie sinnvoll zu machen ist.

**Comment by Twiek** [comment]
Lokal sieht es bei mir aktuell so aus:

<img width="754" alt="bildschirmfoto 2015-11-18 um 10 28 07" src="https://cloud.githubusercontent.com/assets/432388/11237280/23e6d2a6-8ddf-11e5-8d96-01f56fc7c0f2.png">

Bitte noch mal checken.

**Comment by NilsVollmer** [comment]
Die Farbe war nur als Test gedacht und ist als Variable in in den stylesheets gesetzt, kann also beliebig angepasst werden.

**Comment by marcus-herrmann** [comment]
Verständnisfrage: Warum funktioniert das auf Staging/Develop bei mir nicht (grafisch, wie HTML)?

<img width="509" alt="bildschirmfoto 2015-12-03 um 12 46 15" src="https://cloud.githubusercontent.com/assets/505181/11559813/fac13e46-99bb-11e5-9a2b-47135b5d2a7b.png">

**Comment by KonstantinKo** [comment]
Es sieht nicht so aus, als ob es hierfür schon einen PR gab.

**Comment by marcus-herrmann** [comment]
Achso, ist noch auf eigenem Feature Branch. Das "auf Staging deployed" oben hatte mich irritiert.

**Comment by marcus-herrmann** [comment]
Vorschlag: 

<img width="213" alt="bildschirmfoto 2015-12-03 um 13 50 23" src="https://cloud.githubusercontent.com/assets/505181/11561060/f34bc218-99c4-11e5-9b6e-7d82aceb5ced.png">

(Zu finden auf o.g. Branch)

**Comment by Twiek** [comment]
Gefällt, ist aber leider veraltet. Bitte auf den Family/Refugee-Stand bringen, Farben noch mal testen und dann gegebenenfalls nen Pullrequest stellen.

**Comment by marcus-herrmann** [comment]
Styling liegt bereit. Seit einem Merge des aktuellen develop geht aber das Feature nicht mehr (die spans werden nicht mehr erzeugt).

**Comment by NilsVollmer** [comment]
Funktionalität ist wiederhergestellt und kann reviewed werden. 

@Twiek Sprich mich zu dem Verhalten gerne nochmal an.

**Comment by Twiek** [comment]
Feature hat leider doch nicht überzeugt. Daher bitte löschen.
