### ISSUE TITLE
HTML-Code zum Ausschluss des Google-Translators benötigt zu viele Zeichen

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#546]
Der Code benötigt 35 Zeichen, dadurch haben wir nur noch 415 für die eigentliche Description.

**Comment by jjungle** [comment]
Es betrifft vorrangig Codewörter/Projektnamen/Organamen in Descriptions. 
Wir schreiben diese immer via Markdown im Fettdruck. Könnte Fettgedrucktem in Description automatisch die 'notranslate' class zuweisen?

**Comment by NilsVollmer** [comment]
Nach Absprache mit Julia ist dieses Ticket erst einmal on-hold, weil die technische Umsetzung zwar möglich ist, aber leider in sehr vielen Fällen den Satzbau zerschießt. 

Mit der von @KonstantinKo vorgeschlagenen Überarbeitung der Übersetzung sollte ein entsprechendes Feature allerdings umsetzbar sein.

**Comment by NilsVollmer** [comment]
Hat sich durch die Mehrsprachigkeit & code_word erledigt.
