### ISSUE TITLE
Verlinkte URLs in Angeboten regelmäßig prüfen

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#547]
Die in Angeboten verlinkten URLs sollten regemäßig überprüft werden.
Sobald beim überprüfen ein 404 oder anderer Error auftritt, sollten die mit der Website verlinkten Angebote in den Zustand 'Expired' wechseln.

**Comment by NilsVollmer** [comment]
@jjungle Der zustand expired ist eigentlich schon extra für ausgelaufene Angebote da.. Vielleicht lieber 'internal_review' inkl. entsprechendem Asana-Task, dass nur die Webseite geprüft werden muss?

**Comment by jjungle** [comment]
Asana Task bitte nach der alten Syntax erstellen, aber dem Tasknamen ein 'URL unreachable' voranstellen.

**Comment by NilsVollmer** [comment]
@jjungle Und alles andere (Organamen, expires_at datum, offer-name) so lassen? 

Das Datum könnt eher verwirren weil das ja noch nicht überschritten sein wird.

**Comment by jjungle** [comment]
Ist so gewünscht. 'URL unreachable' vorangestellt soll reichen, hatte bei QMA nachgehakt.

**Comment by NilsVollmer** [comment]
@KonstantinKo Ich habe einen entsprechenden Worker inkl. Tests geschrieben, der die Website per http-get anspricht, bei den nicht erreichbaren Webseiten die Angebote expired und ein asana task erstellt.

Allerdings brauchen wir HTTP-GET's jeweils ein paar Sekunden und bei über 1000 zu überprüfenden Seiten dauert das schon eine Weile.. Falls es eine maximale Laufzeit für Worker gibt, könnte das problematisch werden. Ansonsten habe ich den Worker auf Sonntag, 23 Uhr gesetzt. Man könnte ich noch überlegen, den seltener laufen zu lassen.

Oder eine schnellere Alternative zum HTTP-GET finden..

**Comment by KonstantinKo** [comment]
Sonntag 23 Uhr halte ich für keine gute Idee, da das ein beliebter Zeitpunkt für Aufgaben ist, die wirklich die vergangene Woche zusammenfassen sollen. Bei diesen tests macht es ja keinen Unterschied. Also lieber einen anderen Zeitpunkt wählen.

Dass das ne Weile dauern wird ist richtig. Und tendenziell sollten wir natürlich auch damit rechnen, dass wir in Zukunft mal eine sehr viel höhere Anzahl von angeboten haben werden und uns auch dann nicht die Server zusammenbrechen sollen.

Grundsätzlich bei solchen heavy workern: Aufgabenmenge gering halten. Es gibt einen Spawner, der 1000+ neue Worker in die Auftragsliste setzt und jeder von diesen kleinen Workern überprüft genau eine Webseite. Achte drauf, dass du auch wirklich einen harten Timeout einbaust.

Dafür würde ich eine neue queue in sidekiq anlegen. So können wir diese dann auch späterhin zu bestimmten Uhrzeiten pausieren, wo wir unsere Rechenleistung lieber für Endkunden bereithalten.

**Comment by NilsVollmer** [comment]
Deploy TODO: prüfen, ob das sidekiq setup mit der heavy_load queue funktioniert

**Comment by KonstantinKo** [comment]
Bitte den bestehenden Worker zu einem Spawner machen, der für jede gefundene Webseite einen eigenen Mini-Worker instanziert, der wiederum die HTTP requests handhabt.
Auch sollte in dem erstellten Task die offending webseite erwähnt werden.

**Comment by NilsVollmer** [comment]
Änderungen umgesetzt, PR ist ja noch offen: https://github.com/clarat-org/claradmin/pull/10
