### ISSUE TITLE
Konsistentes Mouseover

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#56]
Wenn man bei den Suchergebnissen über einen Link zum Angebot fährt, so wird der Name braun. Wenn mann aber auch einen Marker in der Map fährt, dann wird der Hintergrund des Angebotsnamens orange. Würde hier nicht mehr Konsistenz Sinnn machen (immer orange)?

**Comment by marcus-herrmann** [comment]
Vorschlag zur Konsistenz:

Links, die eine "eigene" Farbfläche haben, nicht Links in einem Fließtext sind (Ergebnislisting, Paginierung) bekommen on hover `text-decoration: underline`. Links im Fließtext sind per se unterstrichen, um sie von Mengentext zu unterscheiden.

Siehe: 19baffba5a0c80af522767effe2c3895ec5a01a8
