### ISSUE TITLE
Suchoptionen bei Refugees/Family kaputt

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#562]
Wenn ich auf 'Suchoptionen' klicke passiert nichts. Der Link der mir beim Mouseover angezeigt wird deutet das auch schon an (http://staging.clarat.org/family/angebote# vs. http://www.clarat.org/angebote?utf8=%E2%9C%93&search_form%5Bquery%5D=&search_form%5Bsearch_location%5D=Berlin%2C+Deutschland&search_form%5Bgenerated_geolocation%5D=52.52000659999999%2C13.404954&search_form%5Bcategory%5D=&search_form%5Bexact_location%5D=false&search_form%5Bcontact_type%5D=personal&search_form%5Bencounters%5D=hotline%2Cemail%2Cchat%2Cforum%2Conline-course&search_form%5Bage%5D=&search_form%5Btarget_audience%5D=&search_form%5Bexclusive_gender%5D=&search_form%5Blanguage%5D=&search_form%5Bsection%5D=family#).

**Comment by NilsVollmer** [comment]
nach einem cache clear funktioniert es auf Staging wieder wie es sollte.
