### ISSUE TITLE
404 & 500 Fehlerseiten entwerfen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#57]
404: Bitte Suchfeld integrieren und den folgenden Text (+ Footer):
"Leider konnten wir diese Seite nicht finden. Versuche es doch bitte mal mit der Suchfunktion."

500: Folgender Text (mit entsprechender Verlinkung):
"Leider ist ein Fehler aufgetreten. Wir werden versuchen ihn schnellstmöglich zu beheben. Bis dahin kommst Du hier zurück auf unsere Startseite"

Wenn es sich als sehr aufwendig herausstellt sämtlichen Code direkt in die jeweiligen Dateien zu packen (public/404.html), dann noch mal Rücksprache halten.

**Comment by marcus-herrmann** [comment]
Kann ich irgendwie einen 404er aus der App heraus erzeugen? http://localhost:3000/foo erzeugt bei mir einen Routing Error, aber keinen 404 im Sinne von Rückgriff auf `public/404.html`

**Comment by Twiek** [comment]
Hilft Dir das: http://localhost:3000/404.html ?

Am 2. Februar 2015 um 11:21 schrieb Marcus Herrmann <
notifications@github.com>:

> Kann ich irgendwie einen 404er aus der App heraus erzeugen?
> http://localhost:3000/foo erzeugt bei mir einen Routing Error, aber
> keinen 404 im Sinne von Rückgriff auf public/404.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/clarat-org/clarat/issues/57#issuecomment-72433786>.
>



-- 
Sebastian Schwiecker

Telefon: +49 30 55 57 96 01 1

Clarat
Projekt der Benckiser Stiftung Zukunft
Französische Straße 47
D-10117 Berlin
schwiecker@clarat.org
www.clarat.org

**Comment by marcus-herrmann** [comment]
Gibt es hier auf GH Facepalm-Emojis?

Ja, hilft natürlich. Danke

**Comment by marcus-herrmann** [comment]
Gegenvorschlag zur 404-Idee: Da ich das generische Folgeseitentemplate verwenden möchte (Suche im Header), wäre ein weiteres Suchfeld im Body redundant (s.o.). Würde daher das Wording leicht anpassen: "…Suche oben".
![bildschirmfoto 2015-02-02 um 11 44 28](https://cloud.githubusercontent.com/assets/505181/5999327/107a130a-aad1-11e4-9f49-ad1c41fe7345.png)

**Comment by Twiek** [comment]
Passt.

**Comment by marcus-herrmann** [comment]
Vorschläge in 9a0f37342362138e689b09d413023933d624d914 (im eigenen Branch).

Anstelle von CSS inline traversiere ich allerdings in die wirkliche, aktuelle Datei `	<link  href="/assets/application.css" media="all" rel="stylesheet"/>` und hole mir die Styles von da. Gleiches gilt für die JavaScripts - hier sind es alles noch Einzelaufrufe der einzelnen Module. Sobald JS fertig ist, könnte ich das noch mal zu einer Datei zusammenfassen (so wie Rails es auf production ja auch automatisch tut).

**Comment by Twiek** [comment]
Ok, passt erstmal.

**Comment by marcus-herrmann** [comment]
Nun im master.

**Comment by KonstantinKo** [comment]
Beachte bitte, dass bei einem 500er Fehler eine hohe Chance besteht, dass kein asset ausgeliefert wird. Heißt alles mit nem src attribut sieht evtl. ebenfalls kaputt aus. So eine Seite muss eigentlich als eigenständige HTML Datei funktionieren.
Ich habe aber auch bei ner schnellen Suche was mit digest links und precompilation gefunden, womit man evtl ein bisschen was automatisieren kann ...
http://icelab.com.au/articles/precompiled-rails-static-404-and-500-pages/

**Comment by marcus-herrmann** [comment]
Von Assets unabhängige, noch weiter reduzierte 500er ergänzt mit 5efb18fe4c1bfcf1374681cef730da15bb49fd8a

**Comment by Twiek** [comment]
Funktioniert noch nicht für http://developer.clarat.org/afsdgdfsdsfgsdf
