### ISSUE TITLE
Suchergebnisseite: Verbindung Karte und Liste

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#570]
Wenn ich mit dem Cursor über eine Suchergebnis in der Liste hover sollte der entsprechende Pömpel in der Karte anfangen zu springen. 

Wenn ich mit dem Cursor über einen Pömpel auf der Karte fahre sollten sie entsprechenden Suchergebnisse in der Liste gehighlighted werden.

Frage: Was, wenn die Suchergebnisse nicht zu sehen sind? Falls es eine einfach Möglichkeit gibt dann an die entsprechende Stelle zu scrollen, gerne so umsetzen, aber eher nice-to-have als must-have.

**Comment by marcus-herrmann** [comment]
Stylingvorschlag: umfärben der betreffenden Angebotszeile bzw. des entsprechenden Markers in orange auf feature/570-map-result-connection

**Comment by NilsVollmer** [comment]
Reminder: Funktionalität passt aktuell, muss aber in Zusammenhang mit #342 möglicherweise angepasst werden.

**Comment by NilsVollmer** [comment]
Auf dem aktuellen develop funktioniert der orangene Highlight-Marker nicht und es wird der default google-marker angezeigt.

**Comment by marcus-herrmann** [comment]
Hatte ich auf den Feature Branch dazu auch sehr lange und sehr hartnäckig. Rails s + rake cache:clear mehrmals half dann irgendwann. Scheint extremst gecached zu werden.

**Comment by NilsVollmer** [comment]
Okay ich schau's mir nochmal an und refactore es ein wenig, sodass der IE11 auch damit klarkommt - der scheint svg's ja nicht zu mögen.
