### ISSUE TITLE
Sidekiq Worker finden Einträge in der Datenbank nicht

### ISSUE THREAD

**Issue by NilsVollmer** [clarat-org/clarat#571]
Da die Jobs für die Kontaktanfragen (und manchmal auch die der Subscription) aktuell gerne mal die entsprechenden Datenbank-Einträge nicht finden, soll bei deren Tod (nach 25 fehlgeschlagenen Versuchen) eine automatisierte interne Mail verschickt werden.

In diesem Zusammenhang macht es wohl auch Sinn, den Retry-Count für diese Jobs herunterzusetzen. 25 Versuche sind erst nach 21 Tagen erreicht und so lange sollten wir nicht darauf warten.

**Comment by NilsVollmer** [comment]
Lieber noch einen Schritt zurück und das Problem beheben anstatt das mit den Mailings umzusetzen.

**Comment by NilsVollmer** [comment]
Update: Auf Staging & Production arbeitet Sidekiq tatsächlich auf den gleichen Datensätzen: auf Staging war die contact-ID bei 350, auf production durch Tests schon auf 356 und auf staging konnte ich manuell den contact-Mailer-Worker mit ID 356 aufrufen (ist durchgelaufen). 

Also arbeiteten beide Environments aktuell auf den production-Daten. Deshalb waren bei sidekiq auch zwei worker aktiv - deshalb habe ich den auf staging erst einmal wieder deaktiviert, weil die beiden sowieso das gleiche getan haben.

**Comment by NilsVollmer** [comment]
Sidekiq ist auf staging und production jetzt voneinander getrennt. Evtl. ist der Fehler dadurch behoben - ich teste das heute noch ein wenig.

**Comment by NilsVollmer** [comment]
Update: habe gerade nochmal direkt nacheinander ein paar Kontaktanfragen verschickt und die gingen allesamt direkt durch (erster oder zweiter Versuch). Scheint also aktuell nicht mehr so problematisch zu sein, dass wir da im code aktiv werden müssten.

**Comment by NilsVollmer** [comment]
Problem scheint nicht mehr aufzutreten.

**Comment by Twiek** [comment]
@NilsVollmer Denkst Du, wir können das Issue schließen? Wenn ja, go ahead!

**Comment by NilsVollmer** [comment]
Habe seitdem nichts problematisches bei Sidekiq gesehen, also close.
