### ISSUE TITLE
Organisationsadressen teilweise nicht anzeigen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#572]
Bei privaten Initiativen wie z.B. Workeer oder Frauenhäusern soll/kann die Adresse der Organisation nicht angezeigt werden (z.B. auch weil es sich nur um ein Postfach handelt).

Hierfür innerhalb der Locations einen Flag/Booelan 'Adresse anzeigen' einführen. Ist dieser gesetzt wird die Adresse und die Karte im Frontend nicht angezeigt (inkl . Addition).

Sollte auch keine Webseite angezeigt werden, so wird das gesamte Kästchen nicht angezeigt.

@jjungle: Bitte mit dem Sprachteam eine andere Überschrift ausdenken und hier reinkommentieren. Anforderung ist, dass das Kästchen auch ohne Adresse nur mit der Webseite Sinn macht und perspektivisch auch nur mit einer Telefonnummer.

**Comment by NilsVollmer** [comment]
> Hierfür innerhalb der Locations einen Flag/Booelan 'Adresse anzeigen' einführen. Ist dieser gesetzt wird die Adresse und die Karte im Frontend nicht angezeigt (inkl . Addition).

Dann soll der Flag wohl eher 'Adresse nicht anzeigen' oder 'Adresse verstecken' heißen.

**Comment by NilsVollmer** [comment]
@jjungle Ist technisch soweit fertig und ich brauche dann noch das neue Wording ;)

**Comment by jjungle** [comment]
Das Sprachteam hat gesprochen: "Wo findest du die Organisation?"

**Comment by NilsVollmer** [comment]
Alles klar, passt so gerade eben da rein ;)

**Comment by NilsVollmer** [comment]
Ist soweit fertig und kann wohl noch am Montag gemerged werden.
