### ISSUE TITLE
Neue Benachrichtigungsmails

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#573]
Künftig soll es mehr verschiedene Benachrichtigungsmails geben. Zum einen wird hier auch clarat Refugees berücksichtigt, zum anderen die Möglichkeit, dass bereits in der Willkommensmail auf deutlich mehr als 5 Angebote hingewiesen wird und diese daher in 2 Teile gesplittet werden soll (eine Erstbenachrichtigung und eine die direkt nach dem subscriben verschickt wird, also die 'Warteschlange' überspringt).

Ganz grob wird die Logik hier skizziert:

![bildschirmfoto 2015-11-27 um 18 22 52](https://cloud.githubusercontent.com/assets/432388/11446234/43037908-9534-11e5-9688-04878bf1bb15.png)

Weitere Details siehe Mail von Lisa.

**Comment by NilsVollmer** [comment]
Habe gestern mit @KonstantinKo darüber gesprochen und wir waren beide der Meinung, dass diese Restmasse-Mail nicht direkt 'best-practice' für Usability ist und deshalb werde ich das heute im Gespräch mit Lisi & Lisi nochmal challengen.

Unsere Idee ist, stattdessen eine neue Seite zu erstellen, auf der jederzeit die aktuelle Liste aller Angebote, mit der eine Kontaktperson verknüpft ist, einsehbar ist. Den Link zu dieser Page können wir dann direkt in der ersten Mail mit verschicken & zusätzlich dahin weiterleiten, wenn man sich für die Subscription anmeldet. 
Das hätte folgende Vorteile:
- weniger emails (die erste bekommen sie ja schon ohne Anfrage)
- keine neue, schlecht zu debuggende Email erstellen (Page ist viel besser zu testen)
- Die Page ist immer aktuell, man kann also jederzeit wieder (bookmarken) dort nachschauen, was es für aktuelle Angebote für diese Person gibt
- Man kann sie sich auch anschauen, ohne sich anzumelden (vllt. wollen das viele nicht und dann erfahren sie nie etwas von den restlichen Angeboten auf clarat)

Ich erinnere mich daran mit @Twiek schonmal im Treppenhaus etwas ähnliches besprochen zu haben und da wurde google Indizierung als Nachteil angesprochen - war genau wäre da das Problem?

**Comment by KonstantinKo** [comment]
+ wir triggern weniger spambots weil wir nicht gleich 2 EMails mit dutzenden von externen Links verschicken. (Man könnte sich sogar überlegen, ob man die regulären mailings für subscribed Emails nicht auch begrenzt und immer auf diese Seite verlinkt)

Google Indizierung ist kein Problem wenn wir die Seite einfach auf noindex stellen.

**Comment by Twiek** [comment]
Ok, dann sollte die Seite aber auf jeden Fall auf noindex gestellt werden, eine URL die man sich nicht herleiten kann und keine Informationen enthalten die nicht auch anderweitig öffentlich sind. Sollte aber alles kein Problem sein.

Wenn ok für Lisa und Co. habt Ihr mein Go.

**Comment by NilsVollmer** [comment]
Heute noch mit Lisa besprochen: da es ja vorkommen kann, dass einer Kontaktperson Angebote von family und refugees zugeordnet sind, müssen wir uns noch überlegen, wie wir damit verfahren.

Man könnte die Angebote auf einer Seite anzeigen und dann vertikal voneinander trennen (zuerst die eine section und dann die andere - ggf. auch ein Kasten pro Section).

Alternativ zeigt man auf einer Seite nur die Angebote der jeweiligen section, was dann bedeutet, dass wir in diesem Fall zwei URLs brauchen: clarat.org/de/family/... und analog für refugees. In der Anschreiben-Mail ist diese Trennung auch vorgesehen, also wäre es kein nennenswerter Zusatzaufwand, dort die beiden Links sinnvoll unterzubringen (wenn es zwei werden).

**Comment by NilsVollmer** [comment]
Update: die von uns präferierte Variante wäre der zweite Ansatz, also eine eindeutige Trennung nach sections. auf .../family/ObskureURL findet man dann die family-Angebote und die refugee-Angebote entsprechend auf .../refugees/ObskureURL . In der Mail werden die Angebote auch getrennt aufgelistet und dann unter der Auflistung jeweils die neue(n) Seite(n) verlinkt.

@KonstantinKo wird sich um die neue Seite kümmern und ich passe die Mailings an die neue Logik an.

**Comment by KonstantinKo** [comment]
OK die Seite ist grundlegend fertig. Muss wahrscheinlich noch styled werden und es braucht noch einen finalen Erklärungstext (@Twiek).
So obskur ist die URL nicht, nutzt die ID einer Email. Die kann man sich ja auch nicht einfach so herleiten wenn man sie nicht kennt.

**Comment by NilsVollmer** [comment]
Update: warte aktuell auf Researcher Input zu ein paar letzten Wordings. Sobald das da ist, kann ich auf claradmin den PR erstellen.

**Comment by Twiek** [comment]
Hier der Text:


Deine clarat Family Angebote für <E-Mail-Adresse>

Hier siehst du auf einen Blick alle deine Angebote bei clarat. Deine Angebote sind Angebote, bei denen wir deine E-Mail-Adresse als Kontaktadresse gefunden haben.
Diese Seite ist immer aktuell. Du kannst sie in deinen Favoriten speichern und so immer auf einen Blick zu sehen, welche Angebote von dir gerade auf clarat zu finden sind.
Wenn du weiterhin auch per E-Mail informiert werden möchtest, wenn neue Angebote von dir bei clarat online sind, nutze den Link am Ende der E-Mail, die du von uns bekommen hast.


--> Deine clarat Refugees Angebote

**Comment by KonstantinKo** [comment]
@marcus-herrmann Es steht noch das Styling der Email-Übersichtsseite aus.

**Comment by marcus-herrmann** [comment]
![emailubersicht](https://cloud.githubusercontent.com/assets/505181/12166878/3743566e-b529-11e5-874f-aaf609beb766.png)

So umsetzen?

**Comment by NilsVollmer** [comment]
Passt von meiner Warte aus. Mobile würde dann erst die Überschrift, dann die Infobox inkl. Button und darunter die Angebotsliste kommen? Oder nach der Überschrift die Angebotsliste und darunter Info-Box inkl. Button?

**Comment by marcus-herrmann** [comment]
Umgesetzt und auf Branch. Mobile erst Listing, dann Infobox, lässt sich aber ändern

**Comment by NilsVollmer** [comment]
Ich habe die Ansicht noch ein wenig überarbeitet und zwar wird die Anzahl der Angebote in der jeweils anderen Welt in dem Button mit angezeigt und wenn es keine gibt (was fast immer der Fall ist) wird der Button nicht angezeigt um eine bad user experience zu vermeiden (Klick auf Button => Leider keine Angebote).

Aktuell haben auf staging genau acht Emails Angebote aus beiden Welten zugeordnet: 73, 229, 344, 613, 321, 600, 368, 950. Also z.B. http://staging.clarat.org/family/emails/73/angebote. An diesen Beispielen kann man die Funktionalität des Button sehen - bei allen anderen ist er einfach nicht da.

**Comment by NilsVollmer** [comment]
Input von Lisa: 
- clarat family & clarat refugees in HTML Variante bold
- unter der Mail das Logo/die Logos einbinden (family, refugees)

**Comment by NilsVollmer** [comment]
Update:
- [ ] "Ihre Angebote bei clarat family sind" => "Ihre Angebote bei **clarat family** sind" und analog für refugees
- [ ] "In Ihrer persönlichen  (LINK) Übersicht (LINK) haben Sie alle Ihre Angebote bei clarat XY im Blick."
- [ ] Logo und PS tauschen (PS wieder ganz am Ende)
