### ISSUE TITLE
Cookie Warnung verdeckt Freshdesk-Chat

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#576]
![image](https://cloud.githubusercontent.com/assets/11425826/11537482/7c044b00-991d-11e5-9e03-fae3e3dfe905.png)

![image](https://cloud.githubusercontent.com/assets/11425826/11537534/baa1dfc6-991d-11e5-9ec8-740332427976.png)

**Comment by NilsVollmer** [comment]
Am besten wäre es wohl, wenn die chat-box bei vorhandenem Cookie-Banner um die entsprechende Höhe nach oben versetzt wird (und beim Entfernen natürlich wieder nach unten).

**Comment by marcus-herrmann** [comment]
Das CookieWarning-CoffeeScript erzeugt eine body-Klasse, wenn es aktiv ist. Diese nimmt den von dir vorgeschlagenen Offset in diesem Szenario vor. Fix-Branch: https://github.com/clarat-org/clarat/tree/fix/576-cookiewarning-vs-chat (sehr klein, fast ein Hotfix)

**Comment by NilsVollmer** [comment]
Das nach oben schieben klappt gut aber wenn man die Leiste entfernt, wird der Chat nicht entsprechend nach unten verschoben und dann sieht es so aus:

![image](https://cloud.githubusercontent.com/assets/1733220/11591155/e9f99790-9a95-11e5-9aac-eb5b3950cdf8.png)

**Comment by marcus-herrmann** [comment]
Hotfix auf den Branch zu 576: Schließen der Cookie Warning nimmt auch offset wieder raus - Chat dann wieder unten "befestigt"

**Comment by NilsVollmer** [comment]
Top, funktioniert super! Gerne PR auf develop daraus machen.
