### ISSUE TITLE
Erweitete Suchoptionen in der refugee-Welt anpassen

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#577]
In der refugee Welt sollten folgende erweiterte Suchoptionen nicht angezeigt werden:
"Hilfe für wen?"
"Alter des Kindes?"

Falls nicht möglich einfach die Erweiterten Suchoptionen erstmal ausblenden, bis Marcus wieder on board ist.

**Comment by NilsVollmer** [comment]
Wenn man die Felder einfach weglässt sieht es ein wenig ausgedünnt aus:

![image](https://cloud.githubusercontent.com/assets/1733220/11586515/e58ba3b4-9a73-11e5-8c3e-0ced38089d18.png)

So umsetzen?

**Comment by NilsVollmer** [comment]
Hab's per display:none auf entsprechendem Branch umgesetzt. Wenn optisch so gewünscht, mache ich einen PR draus.

**Comment by NilsVollmer** [comment]
In develop gemerged und neu auf staging deployed.
