### ISSUE TITLE
preview URL fehlerhaft/unvollständig

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#578]
Wenn man aus claradmin-staging heraus ein Angebot in der Frontend preview anschauen will, fehlt der clarat-welt Zusatz in der URL. Führt deshalb zu 404

Bsp. URL nach "anzeigen in app" klick aus claradmin:
http://staging.clarat.org/preview/angebote/hilfe-fuer-arabische-fluechtlinge-bei-antraegen

Wenn man die clarat-Welt händisch ergänzt, klappts.
http://staging.clarat.org/refugees/preview/angebote/hilfe-fuer-arabische-fluechtlinge-bei-antraegen

**Comment by NilsVollmer** [comment]
Es gab noch einen Bug, der mit #582 behoben wurde.
