### ISSUE TITLE
'Categories ist nicht gültig'

### ISSUE THREAD

**Issue by NilsVollmer** [clarat-org/clarat#583]
Wenn man ein neues Angebot erstellt, kommt es manchmal zu einem komischen Fehler 'Categories ist nicht gültig'. Das Beispiel war ein F&R Angebot, dass direkt bei der Erstellung der Kategorie Diskriminierung (F&R) zugeordnet werden soll. Auf den ersten Blick konnte ich nicht ermitteln, woher diese Fehlerausgabe kommt (der Text und auch die Bausteine kommen nicht in den locales vor bzw. sind ohne Bezug zu der Problematik).

Wenn man das Angebot mit einer anderen Kategorie oder ganz ohne Kategorie speichert und danach Diskriminierung hinzufügt, funktioniert es auf einmal. Es scheint also ein Problem von new/create zu sein - beim update klappt es dann. Deshalb auch erst einmal geringe Priorität.

Wahrscheinlich Rails admin intern und damit won't fix.

**Comment by KonstantinKo** [comment]
Kategorien waren tatsächlich nicht gültig. Im Direktkontakt mit Research gefixt.
