### ISSUE TITLE
Unterschiedliche code coverage und LOC beim testen (travis vs local)

### ISSUE THREAD

**Issue by NilsVollmer** [clarat-org/clarat#591]
Seit dem Upgrade auf Rails 4.2 (vgl. #76 ) haben wir in claradmin (und auch clarat) lokal und in den travis builds eine uneinheitliche code coverage. Lokal passt alles und die coverage ist bei 100% (aktuell 244/244) und in dem travis build werden ersten viel mehr Zeilen erkannt (358) und zweitens treffen wir deutlich weniger Zeilen (128), was dann zu einer coverage von gerade mal 35,75% (128/358) führt.

**Comment by NilsVollmer** [comment]
Update: durch das Ausführen der Befehle, die auch bei travis ausgeführt werden: 

Mit ```bundle exec rake db:migrate test:all```kommen wir lokal dann auf eine identische coverage. 
```rake db:migrate test```genügt auch schon - es scheint also an dem vorgeschaltetem Migrieren zu liegen.

**Comment by NilsVollmer** [comment]
Update2: Habe mir mal die betroffenen Files angeschaut: er hat keine neuen Dateien gefunden, die vorher nicht berücksichtigt wurden, sondern nur Dateien auf 0% gesetzt, die er vorher als 100% geflagged hatte. 

Da in den Dateien die relevanten Lines auch nicht mehr korrekt erkannt werden, führt es zu dem Anstieg der LOC insgesamt und zum Sinken der getroffenen Lines.

Interessant ist nach wie vor, dass dies anscheinend nur beim vorgeschalteten db:migrate passiert.

**Comment by NilsVollmer** [comment]
Update3: ich habe jetzt einige Dinge wieder zurück geändert (vor allem den eager_load und die neue new syntax) weil es manchmal zu dem komischen Verhalten kam, dass u.a. Leerzeilen und Kommentare bei der coverage nicht ignoriert wurden.

Ansonsten habe ich auf dem branch fix/test-suite-coverage ein paar fehlende Tests hinzugefügt (hat komischerweise zu keiner Veränderung des Verhaltens geführt) und den travis-command entsprechend angepasst. Damit ist es jetzt durchgelaufen (https://travis-ci.org/clarat-org/claradmin/builds/96981758).

Für application_controller, application_helper und rails_admin_state_extensions könnte man evtl. noch tests formulieren - da habe ich mich schwer getan.

**Comment by NilsVollmer** [comment]
Ich schaue mal, ob ich clarat auch noch auf 4.2 bekomme.

**Comment by NilsVollmer** [comment]
aktueller Stand auf clarat: Ich bin vermutlich an dem gleichen Punkt wie @KonstantinKo gestern: alle Tests scheitern weil die Tabelle 'areas' angeblich nicht gefunden werden kann. Habe das Zeug dennoch mal auf fix/test-suite-coverage gepushed damit man das nicht noch einmal machen muss.

**Comment by KonstantinKo** [comment]
Letzteres doppelt sich mit #76.
Coverage fix war ja soweit erfolgreich.
