### ISSUE TITLE
Kategorien auch in der mobile-Version anzeigen

### ISSUE THREAD

**Issue by JulianJung** [clarat-org/clarat#593]
Der Kategorienbaum sollte auch in der mobile Version sichtbar sein.

**Comment by NilsVollmer** [comment]
Also auf meinem Smartphone ist der Kategoriebaum ganz unten (unter der Angebotsliste) sichtbar. Geht es darum, ihn prominenter zu positionieren bzw. anders darzustellen oder ist er auf einigen Geräten tatsächlich nicht sichtbar?

**Comment by Twiek** [comment]
@jjungle : Bei mir auch. Soll er anders angezeigt werden, oder ist das Issue einfach alt.

**Comment by jjungle** [comment]
@Twiek habe in Asana nachgeguckt: Wir haben dazu am 10.12 gesprochen, und dabei anscheinend beide nicht bemerkt das der Kategorienbaum ganz unten auftaucht.
Wäre also vermutlich nicht schlecht ihn etwas prominenter zu platzieren. Oder gab es den Kategoriebaum da mobil noch nicht?

**Comment by NilsVollmer** [comment]
Am mobilen Design haben sich nur Kleinigkeiten geändert also wird es den Baum schon damals gegeben haben. 

Was die prominentere Platzierung angeht ist das nicht ganz einfach.. wenn er über den Angeboten steht, muss man immer sehr weit scrollen um zu den Angeboten zu kommen. Oder man packt ihn default hidden darüber (also wie die Suchoptionen) aber dann ist er nur nach einem zusätzlichen Klick sichtbar.

**Comment by Twiek** [comment]
Abwarten bis neue Suchergebnisseite (inkl. Stamps) online ist.

**Comment by Twiek** [comment]
Ideen: Komplettes Overlay aller Suchoptionen inkl. Kategorien. Eventuell leicht transparent damit man sieht, dass ich im Hintergrund was ändert.
