### ISSUE TITLE
Sidebar legt sich über den Footer

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#595]
Wenn man einige Kategorien in der Sidebar aufklappt, legt sich die Sidebar über den Footer. Tritt meist dann auf, wenn die Liste der Suchergebnisse kürzer ist als die Sidebar.
Falls mit #510 behoben, einfach schließen.

![image](https://cloud.githubusercontent.com/assets/11425826/11838959/9c407718-a3ea-11e5-817c-b604018fff8e.png)

**Comment by NilsVollmer** [comment]
Julian ist gerade auf einen weiteren Bug mit der Sidebar gestoßen: bei gewissen Fensterbreiten legt diese sich erst über den Content:

![image](https://cloud.githubusercontent.com/assets/1733220/12119173/6b3ef5c8-b3ca-11e5-9fa4-51ad1794d707.png)

und wenn man das Fenster dann schmaler zieht landet sie unter dem Content und bleibt da auch wenn man das Fenster anschließend wieder breiter zieht:

![image](https://cloud.githubusercontent.com/assets/1733220/12119215/a6624e52-b3ca-11e5-98bd-3f7dc61a3420.png)

Bei Bedarf gerne ein eigenes Ticket daraus machen.

**Comment by marcus-herrmann** [comment]
Hotfix dazu auf develop

**Comment by NilsVollmer** [comment]
Beim xl-layout besteht immer noch der Fehler, dass die sidebar unten hängen bleibt wenn man das Browserfenster verschmälert und anschließend wieder breiter zieht.

Aber da das auch ein nicht so häufiges Nutzerverhalten sein dürfte, hat der ursprüngliche Bug, dass die sidebar den footer überlagert, definitiv die höhere Priorität.

**Comment by marcus-herrmann** [comment]
PR gestellt, #618
