### ISSUE TITLE
Suche via PLZ fehlerhaft

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#597]
Wenn man bspw. 10969 in das 'Wo-Feld' eingibt und dann nicht den Autovervollständigungsvorschlag von Google auswählt, sondern direkt mit Enter bestätigt (oder wahlweise auf die Lupe klickt) werden keine Angebote gefunden, nichteinmal standortunabhängige Angebote.

**Bsp.: PLZ 10969**
![image](https://cloud.githubusercontent.com/assets/11425826/11842308/27b6ed1e-a403-11e5-8ee7-26417ebdf22b.png)

**Mit der PLZ 12355 funktioniert es hingegen bspw. schon.**

![image](https://cloud.githubusercontent.com/assets/11425826/11842348/65188eec-a403-11e5-8cd4-e562f5f07663.png)

**Comment by NilsVollmer** [comment]
Das hatten wir doch kurz vor dem Refugee-Launch schon. Ist ein bisschen Glücksspiel weil in dem Fall tatsächlich nur diese Zahl an GoogleGeocode geschickt wird und dann auch mal was ganz falsch dabei herum kommen kann. Siehe Beispiel aus dem Browser - das da jetzt Berlin der erste Hit ist liegt wohl an Zusatzinformationen, GoogleMaps sich zieht.

![image](https://cloud.githubusercontent.com/assets/1733220/11842710/a986dd16-a405-11e5-971e-705f7fbae696.png)

Manchmal wird Berlin der erste Treffer sein und dann klappt es aber manchmal eben nicht und wir suchen z.B. in Amerika, wo wir natürlich keine Angebote haben.

Das das Ganze bei dem DropDown-Vorschlägen funktioniert liegt vermutlich daran, dass wir da noch Zusatzinformationen mitschicken (z.B. in Deutschland).

**Comment by Twiek** [comment]
Kann es aktuell nicht mehr reproduzieren. Wenn es wieder gemeldet wird und ein echtes Problem darstellt nehmen wir uns dem erneut an.
