### ISSUE TITLE
Umsetzung von Tinos Designs zum Sprach-Switch-"Banner"

### ISSUE THREAD

**Issue by marcus-herrmann** [clarat-org/clarat#601]

**Comment by marcus-herrmann** [comment]
Achtung: Auf feature-Branch zu **554**!

**Comment by Twiek** [comment]
Das Dropdown funktioniert bei mir noch nicht (mobile) und wenn ich auf irgendeine Sprache außer Englisch klicke erscheint nicht das 'Warndreieck'.

**Comment by KonstantinKo** [comment]
Bitte auch daran denken, den Dummy-Sprachswitch im Footer (die Flaggen) wieder zu entfernen, wenn das hier funktioniert.

**Comment by marcus-herrmann** [comment]
@Twiek

> Das Dropdown funktioniert bei mir noch nicht (mobile) 

Konnte ich auf einem anderen Rechner reproduzieren, war aber mit `rake cache:clear` zu lösen. Warndreieck schaue ich mir an

**Comment by marcus-herrmann** [comment]
@Twiek Warndreiecke nun sprachweit (ausser de)
@KonstantinKo ist entfernt

Wenn alle Labels in allen Sprachen vorliegen, geht es weiter mit #602 - Textlängenfinetuning bei bestimmten Labels/Buttons

**Comment by marcus-herrmann** [comment]
@KonstantinKo @NilsVollmer Kann - rein funktionell - auf staging ausprobiert werden

**Comment by KonstantinKo** [comment]
> Translation results
> Your application may display, in response to a user’s action, translation results obtained from the Google Translate API. Whenever you display such information, you must include attribution to Google which links to http://translate.google.com.

-https://cloud.google.com/translate/v2/attribution

Wir müssen das "translated by Google" leider noch verlinken.

**Comment by KonstantinKo** [comment]
nvm war es wohl schon

**Comment by marcus-herrmann** [comment]
Ich habe jetzt gerade für den Bruchteil einer Sekunde überlegt, was "nvm" jetzt schon wieder für ein Packagemanager ist ;)
