### ISSUE TITLE
Beim Aufklappen der virtuellen Angebote verschwindet die Sidebar komplett

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#603]
Der Kategoriebaum sollte jedoch auch hier zu sehen sein.

![image](https://cloud.githubusercontent.com/assets/11425826/11867662/dcebac2e-a4b2-11e5-85f7-6fe9f7d7d177.png)

**Comment by NilsVollmer** [comment]
Sollte zusammen mit #596 bereits gefixed sein und muss nur noch deployed werden.

**Comment by NilsVollmer** [comment]
Ist deployed und somit behoben.
