### ISSUE TITLE
Verstecken der Adresse auf Angebotsebene

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#605]
Hier bei gibt es zwei verschiedene Use-Cases:

- Die Adresse ist uns bekannt, sie soll aber nicht im Frontend angezeigt werden.
- Die (genaue) Adresse ist uns nicht bekannt, wir legen eine Fake-Adresse an, diese sollte ebenfalls nicht im Frontend angezeigt werden. Gleichzeitig sollte sie aber auch als Fake-Adresse markiert sein.

**Comment by Twiek** [comment]
@Julian: Kannst Du mal ein paar Beispiele für unbekannte Adressen liefern? Wenn wir keine Adresse haben können wir den Leuten ja auch nicht sagen wo sie hin sollen. Wo kriegen die User die Adressen her?

**Comment by jjungle** [comment]
@Twiek 
Zum Thema unbekannte Adressen betrifft es vor allem die Area-Problematikfälle. Angebote die an Orten ohne konkrete Adresse stattfinden: Bsp.: Alexanderplatz. Cafe XY Ecke Strasse X & Y; Streetwork in Nord-Neukölln, Selbsthilfegruppe im Prenzlauerberg => Nach der Adresse soll man telefonisch fragen.

Zu Frage 2:
Mir sind da keine Fälle bekannt. Würde auch etwas unlogisch sein. Aber selbst wenn, könnte man hier zwei Standorte anlegen.
