### ISSUE TITLE
Anlegen von Adressen außerhalb Deutschlands

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#606]
Wie besprochen:
Hierzu fehlt die Möglichkeit ein Land anzugeben, sowie ein variableres Zip Feld.

Betrifft momentan nur ca. 3-5 Standorte..

**Comment by Twiek** [comment]
Als weiteres Bundesland bitte 'Ausland' (abroad) hinzufügen.

**Comment by NilsVollmer** [comment]
PR auf _base erstellt, nach review & merge dann einfach mir für bundle update auf claradmin zuweisen.
