### ISSUE TITLE
Getrennte Suchvorschläge bei Family und Refugees

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#608]
Bei Refugees machen die aktuellen Suchvorschläge wie z.B. 'Nachhilfe' oder 'rauchen' nicht so viel Sinn. Hier bitte die folgenden nehmen:

- Staatsbürgerschaft
- Deutschkurs
- Anerkennung
- Kriegstrauma
- Asylverfahren
- Gesundheitsversorgung
- Behörden
- Aufenthaltsrecht

**Comment by NilsVollmer** [comment]
@KonstantinKo War ein deprecated module - ich hab's als presenter zu einem ActiveScript übernommen und den section switch implementiert. Bitte noch über das Script gucken, ob das so okay ist - Funktionalität passt.

**Comment by KonstantinKo** [comment]
@Twiek es wiederholen sich aber zur Zeit die Begriffe recht häufig da es gar nicht mal so viele davon gibt. Bei Family haben wir die doppelt Menge an Beispielen.

**Comment by NilsVollmer** [comment]
Kann gemerged werden
