### ISSUE TITLE
Erklär-Pop-Ups

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#609]
Einmal um den 'Weltenswitch' (Family/Refugees) auf der Startseite zu erklären. Einmal um auf die 'Suchoptionen' hinzuweisen.

Sollten per 'x' wegklickbar sein und dann auch die nächsten 3 Monate nicht mehr auftauchen (per Cookie). Texte folgen.

![bildschirmfoto 2015-12-18 um 12 58 14](https://cloud.githubusercontent.com/assets/432388/11896605/43635828-a588-11e5-8d1d-bb6df7d2be6a.png)
![bildschirmfoto 2015-12-18 um 12 52 25](https://cloud.githubusercontent.com/assets/432388/11896606/4365bd2a-a588-11e5-8615-9520ec82c5b7.png)

**Comment by marcus-herrmann** [comment]
Funktionelle Demo nun auf eigenem Featurebranch `feature/609-descriptive-tooltips`. Warte auf fertige Texte, dann geht es bestimmt noch mal an's Styling

**Comment by Twiek** [comment]
Warte noch auf den Text. Bis dahin bitte diesen verwenden:

"Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet."

Außerdem schon mal mit offensiveren/auffälligeren Farben testen und einem kompletten Ausgrauen des Hintergrundes. Gerne von allen Varianten einen Screenshot machen und hier einstellen.

**Comment by Twiek** [comment]
Ok, richtige Texte sind gerade reingekommen:

Für die Filter: "Willst du deine Suche genauer machen? Dann klicke hier. Es öffnet sich eine Box mit Auswahl-Möglichkeiten."

Für den Welten-Switch: 
"Wenn du hier klickst, kommst du zu clarat-family. In clarat-family kannst du nach Hilfe für Kinder, Jugendliche und Familien suchen."

und

"Wenn du hier klickst, kommst du zu clarat-refugees. In clarat-refugees kannst du nach Hilfe für Flüchtlinge suchen."

Da kürzer als erwartet muss die Aufmerksamkeit anderweitig darauf gelenkt werden (z.B. mit besagtem Ausgrauen).

**Comment by marcus-herrmann** [comment]
Hier mal beispielhaft am welcome tooltip der Welt-Navi:

<img width="1403" alt="bildschirmfoto 2016-02-04 um 14 15 48" src="https://cloud.githubusercontent.com/assets/505181/12815947/de2d598a-cb49-11e5-8c81-f6984a081809.png">
<img width="1395" alt="bildschirmfoto 2016-02-04 um 14 14 32" src="https://cloud.githubusercontent.com/assets/505181/12815948/de2d7dfc-cb49-11e5-94ef-6893d0fb3059.png">
<img width="1395" alt="bildschirmfoto 2016-02-04 um 14 13 25" src="https://cloud.githubusercontent.com/assets/505181/12815946/de2c6d90-cb49-11e5-8029-a585f6a992d6.png">

**Comment by marcus-herrmann** [comment]
Oder ist das zu agressiv?

Ich baue derweil die Logik, die die Welten erkennt und die jeweilig andere mit Beschreibungstooltip versorgt (so wie oben - man ist auf Refugees und bekommt den Hinweis zu family.

**Comment by Twiek** [comment]
Die unterste Version (ausgegrauter Hintergrund und gräuliche Sprachblase finde ich am besten. Dazu aber noch ein paar Wünsche:

1. Bitte den Pfeil auf den jeweiligen Reiter deutlich größer.
2. Bitte das Wort hier durch 'Family' bzw. 'Refugees' auswechseln.

Ansonsten die Fragen inwiefern auch ein Klick irgendwo auf die ausgegraute Fläche dazu führt, dass der Hinweis verschwindet (sollte so sein) und ob Du Dich auch um Cookies kümmerst damit mir der Hinweis erst nach 90 Tagen wieder angezeigt wird?

**Comment by marcus-herrmann** [comment]
Die Cookie-Logik ist bereits drin (auskommentiert für die Demo). Klick on overlay kann ihn verschinden lassen, wird eingebaut.

Du meinst Family und Refugees mit großem Anfangsbuchstaben im Tooltiptext?

**Comment by marcus-herrmann** [comment]
@Twiek Update: <img width="1419" alt="bildschirmfoto 2016-02-04 um 15 00 16" src="https://cloud.githubusercontent.com/assets/505181/12817030/156ade9e-cb50-11e5-98ad-69fa15fab6c5.png">

**Comment by marcus-herrmann** [comment]
<img width="1141" alt="bildschirmfoto 2016-02-04 um 16 00 21" src="https://cloud.githubusercontent.com/assets/505181/12818762/6e065ab2-cb58-11e5-83fb-da45bbf966a9.png">

**Comment by marcus-herrmann** [comment]
Es ist erstmal so wie in den Screenshots im Feature-Branch. Die Cookie Detection ist da, aber auskommentiert, siehe: https://github.com/clarat-org/clarat/blob/feature/609-descriptive-tooltips/app/assets/javascripts/welcome_tooltips/presenter.coffee#L64 ff

Was ich nächste Woche noch tun muss (da mal wieder eine Slim-Edge-Case-Situation): Konstantin fragen, wie ich die "konditionellen" Welt-Tooltips exakt umsetze

**Comment by marcus-herrmann** [comment]
Feature-Branch ist mit Welt-Unterscheidung ergänzt. Cookie Detection nach wie vor auskommentiert (Zeile 130 in o.g. Datei).

**Comment by marcus-herrmann** [comment]
Note to self wegen https://github.com/clarat-org/clarat/pull/674#issuecomment-182959865:

Entsprechendes Element clonen, den Clone im Dom nach dem Overlay platzieren, ebenfalls position fixed, dann höherer z-Index?

**Comment by marcus-herrmann** [comment]
So umgesetzt auf Feature-Branch. Grafisch folgendermaßen:

![clarat 2016-02-18 10-47-47](https://cloud.githubusercontent.com/assets/505181/13139582/8b247838-d62d-11e5-89f3-313a18ede5b0.jpg)
![unterstutzungsangebote fur fluchtlinge clarat 2016-02-18 10-47-31](https://cloud.githubusercontent.com/assets/505181/13139580/8b2281c2-d62d-11e5-8bee-a1aec0d08c1e.jpg)
![unterstutzungsangebote fur kinder jugendliche und familien clarat 2016-02-18 10-46-58](https://cloud.githubusercontent.com/assets/505181/13139581/8b22a58a-d62d-11e5-8414-e3fab2fbd880.jpg)

**Comment by marcus-herrmann** [comment]
Wie immer gilt: Zu Demonstrationszwecken ist die Cookie-Funktion ausgestellt. Bevor ich den PR stelle, wird sie wieder aktiviert.

**Comment by Twiek** [comment]
Sprich mich noch mal drauf an. Würde gerne die folgenden Punkte diskutieren:

- Gibt es verschiedene Cookies für die Verweise auf die Welten und auf die Suchoptionen? Sollte es. Cookies sollten 90 Tage gespeichert werden.

- Kann man auf der Suchergebnisseite auch den Verweis auf die Welten anbringen, allerdings nur, wenn man ihn nicht schon anderweitig gesehen hat? Ansonsten nur den Verweis auf die Suchoptionen.

- Kann den Verweis auf die Welten auch auf allen anderen Seiten anzeigen (Angebotseinzelansicht, FAQs... ).

**Comment by marcus-herrmann** [comment]
@Twiek Da haben wir uns gestern zwar nicht drüber unterhalten, aber ich würde mich um folgenden Teil deiner Nachricht kümmern:

> Kann den Verweis auf die Welten auch auf allen anderen Seiten anzeigen (Angebotseinzelansicht, FAQs... ).

**Comment by marcus-herrmann** [comment]
Die Business-Logik war relativ einfach umzusetzen, das Schwierige war das Styling, vor allem responsiv, vor allem auf offer index, wenn beide Tooltips angezeigt werden sollen

**Comment by Twiek** [comment]
Scheint noch Probleme in der mobilen Version zu geben:
![bildschirmfoto 2016-03-15 um 13 00 18](https://cloud.githubusercontent.com/assets/432388/13777102/49ab1c3c-eaae-11e5-9f43-e6342f482f5d.png)

In der Angebotseinzelansicht gibt es die erweiterten Suchoptionen ja gar nicht.

**Comment by marcus-herrmann** [comment]
Featurebranch aktualisiert. Bitte pullen/noch mal auschecken
