### ISSUE TITLE
Neuer Encounter für Portale/Listen/Websites

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#611]
Für Remote-Angebote wie Listen,Portale und Websites brauchen wir einen neuen Encounter.
Falls kein Konflikt mit den derzeitigen 'Websites' ensteht gerne einfach 'Website' nennen.
Ansonsten ginge auch 'List' oder 'Portal'

**Comment by NilsVollmer** [comment]
'Website' finde ich ein wenig zu allgemein gehalten und könnte zu Missverständnissen führen. Zum Beispiel haben wir ja die encounter 'forum' und 'online-course', die ja auch Webseiten sind. Also lieber genauer benennen, sprich 'Liste' und 'Portal'. Wenn es nur ein neuer Encounter sein soll, müsste man sich über ein Wording Gedanken machen, das zutreffend und nicht missverständlich mit bereits vorhandenen Encountern ist

**Comment by NilsVollmer** [comment]
Den neuen Encounter 'portal' baue ich dann im Backend schonmal ein (noch nicht deployen). Für die Änderungen im Frontend muss noch ein Wording für diesen Encounter gefunden und entschieden werden, ob die Encounter-Stamps der Remote-Angebote in der Übersicht der Suchergebnisse noch relevant sind.

**Comment by NilsVollmer** [comment]
Die Umsetzung ist eher eine Kleinigkeit und es würde dann jetzt nur noch ein Frontend-Wording für den neuen encounter fehlen. Intern (im Backend) heißt er 'portal'.

**Comment by jjungle** [comment]
We have a winner "Adressliste" ist das Frontend-Wording.
