### ISSUE TITLE
Formatierungsänderungen in den Suchwortvorschlägen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#615]
Hinter dem eigentlichen Vorschlag das ',' und die '...' weglassen, also statt 'z.B. wohnen, ...' immer nur ein Wortvorschlag und dann 'z.B. wohnen'

![bildschirmfoto 2016-01-06 um 18 27 05](https://cloud.githubusercontent.com/assets/432388/12149308/520c1368-b4a3-11e5-954a-112f93576ac8.png)

**Comment by NilsVollmer** [comment]
War eine absolute Kleinigkeit, deshalb ohne PR direkt auf develop umgesetzt
