### ISSUE TITLE
Der 'Expires at'-Vorschlag sollte immer genau 1 Jahr in der Zukunft liegen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#617]
Aktuell scheint es < 1 Jahr zu sein. Z.B. heute (7.1.) wird mir der 24.12.2016 vorgeschlagen. Ist allerdings nicht immer bei allen nachvollziehbar. Manchmal scheint es zu klappen.

**Comment by NilsVollmer** [comment]
Ich konnte das auch nach mehrfachem Ausprobieren nicht reproduzieren: wenn man ein neues Angebot anlegt wird das expired_at genau ein Jahr in die Zukunft initialisiert.

Das gilt allerdings nur für neu erstellte Angebote! Wenn ein Angebot dupliziert wird, wird das Datum des Ursprungsangebot genommen. Das wurde im Zuge der besseren Duplicate Methode extra so programmiert weil es das gewünschte Verhalten sein sollte.

Also bitte nochmal Rücksprache halten, wann das auftritt und ob es nicht ein duplicate war.

**Comment by jjungle** [comment]
Kanns ebenfalls nicht reproduzieren. Falls es nochmal bei jemandem auftritt, gebe ich sofort bescheid.
