### ISSUE TITLE
Neuen Sprachfilter 'Kikuyu' anlegen

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#619]
Name: 'Kikuyu'
Identifier: 'kik'

**Comment by NilsVollmer** [comment]
![image](https://cloud.githubusercontent.com/assets/1733220/12198672/8ea143b4-b612-11e5-9c30-6e0a0ef7e28c.png)

**Comment by NilsVollmer** [comment]
Deploy TODO: LanguageFilter anlegen

**Comment by NilsVollmer** [comment]
Erledigt und im gleichen Atemzug auch alle fehlenden Sprach-Identifier zu dem enum hinzugefügt.
