### ISSUE TITLE
Standort Invisible Funktion auf Angebote ausdehnen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#620]
Künftig sollen Standorte die auf invisible gesetzt sind auch nicht mehr im Rahmen von Angeboten angezeigt werden, also weder in der Suchergebnisliste (Pömpel auf der Karte bzw. Adresse in der Liste) noch im Angebot selber (Karte und Adresse nicht anzeigen).

Vor-Ort-Angebote bleiben aber Vor-Ort-Angebote und im Backen muss den Angeboten auch weiterhin ein Standort zugewiesen werden.

Hintergrund: Frauenhäuser, Exit etc.

**Comment by NilsVollmer** [comment]
Auf der Angebotsleiste führt das Verstecken der location dazu, dass die 'where'-section ein wenig missverständlich ist: 

![image](https://cloud.githubusercontent.com/assets/1733220/12264455/49e964a4-b937-11e5-893c-f3e098130bbd.png)

Vielleicht sollte man in dem Fall einen kurzen Text dort einblenden, der den Grund erklärt ("Leider ist die Adresse nicht öffentlich einsehbar".to_simple_language)? Sonst könnte das als ein Fehler aussehen. Alternativ könnte man die Überschrift der Box in dem Fall anpassen.

**Comment by NilsVollmer** [comment]
Input von @jjungle ergibt noch eine dritte Option: einfach das 'Ein Angebot von:' weglassen. Dann sieht es so aus, wie auch bei den Remote-Angeboten.

**Comment by NilsVollmer** [comment]
@Twiek @jjungle Ich bin der Meinung, dass wir noch einmal darüber nachdenken sollten, anstatt der Adresse einen erklärenden Text einzubinden, damit es nicht nach einem Fehler aussieht / klarer wird, warum man die Adresse da jetzt nicht sieht.

![image](https://cloud.githubusercontent.com/assets/1733220/12290168/7f1b175e-b9e0-11e5-8faf-c1c17da397f9.png)

**Comment by Twiek** [comment]
Da Design eh gerade überarbeitet wird würde ich das jetzt direkt so umsetzen und im neuen darauf achten.

**Comment by Twiek** [comment]
Hier im Admin-Bereich bitte noch den Satz 'Obacht: nur dann entfernen, wenn die Adresse auf der Orga-Seite versteckt werden soll!' in 'Obacht: nur dann entfernen, wenn die Adresse auf der Orga- UND auf der Angebotsseite versteckt werden soll!' ändern.

**Comment by NilsVollmer** [comment]
Anpassungen direkt auf Develop umgesetzt
