### ISSUE TITLE
Kontaktpersonen in Angeboten unsichtbar machen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#621]
Auf Angebotsebene soll es ein flag geben der dazu führt, dass die zugeordneten Kontaktpersonen im Frontend nicht angezeigt werden. Ausnahme sind Kontaktpersonen mit dem flag 'SPoC', diese werden immer angezeigt.

Arbeitstitel: 'hide contact persons'

**Comment by NilsVollmer** [comment]
@Twiek @jjungle Direkt mit entsprechender Validierung, die nicht zulässt, dass SPoC's versteckt werden? Dann kann es nicht zu verwirrenden Eingaben (ich habe doch verstecken geklickt, warum wird der trotzdem angezeigt?) kommen.

**Comment by Twiek** [comment]
Ja.

**Comment by NilsVollmer** [comment]
Nach Rücksprache mit @Twiek und der Klärung des Missverständnisses gibt es jetzt doch keine Validierung.

**Comment by Twiek** [comment]
Wenn überhaupt keine Kontaktperson bei einem Angebote angezeigt wird, sollte die gesamte Box 'Wo kannst du dich melden?' nicht angezeigt werden.

**Comment by NilsVollmer** [comment]
Anpassungen direkt auf Develop umgesetzt
