### ISSUE TITLE
Kontaktpersonen aus den Notizen holen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#622]
Nach Deploy von https://github.com/clarat-org/clarat/issues/621 sollen alle Kontaktpersonen die in einem Angebot im Rahmen einer Notiz verlinkt werden direkt diesem Angebote zugeordnet werden, aber nur dann, wenn diesem Angebote aktuell nur Kontaktpersonen mit dem flag 'SPoC' zugeordnet wären. Diese Angebote sollen dann auch der hide contact persons flag gesetzt werden, der alle Kontaktpersonen im Frontend unsichtbar macht (außer die bei denen 'SPoC' gesetzt ist).

@jjungle: Bitte noch mal checken, ob dadurch nicht doch falsche Kontaktpersonen an die Angebote geheftet werden können und wenn nein, dann an Nils übergeben.

**Comment by jjungle** [comment]
@Twiek 
Insgesamt wurden ja nur 11 Kontaktpersonen über Notizen verknüpft. 10 davon gehen interessanterweise auf meine Kappe. Die übrige Notiz war keinem Angebot zugeordnet, konnte gelöscht werden.
Bei den 10 Angeboten würde es passen. Lohnt sich das denn dann überhaupt noch automatisch?

**Comment by NilsVollmer** [comment]
Ist das hier noch relevant oder soll es einfach manuell angepasst werden?

**Comment by jjungle** [comment]
Sobald fertig bei #657 Pending entfernen und kommentieren.

**Comment by jjungle** [comment]
Alles erledigt.
