### ISSUE TITLE
Neue Webseitenhosts

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#624]
Folgende 'Hosts' sollen hinzukommen (Übersetzung fürs Frontend in Klammern):

- online-consulting (Onlineberatung)
- chat (Chat)
- forum (Forum)
- online-course (Online-Kurs)
- application-form (Anmeldeformular)
- contact-form (Kontaktformular)

**Comment by NilsVollmer** [comment]
@Twiek Wichtig: jedes Wording-Update führt natürlich dazu, dass wir die neuen Dinge irgendwie übersetzt kriegen müssen. Je öfter sich die Dateien aktuell ändern und out of sync mit dem translations-branch sind, desto unschöner wird es.
