### ISSUE TITLE
Änderungen in Sprachdateien ändern

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#626]
Spätestens wenn ein Issue gemerged wird hier alle .yml Dateien aufführen die sich geändert haben.

Vor nem Merge noch einmal überprüfen.

**Comment by marcus-herrmann** [comment]
Für #455:
In offers/de.yml neue Nodes "current_and_original_locale", "speaking", "lang_list_toggle",

Für #609:
In shareds/de.yml neue Node "tooltips"

**Comment by NilsVollmer** [comment]
#624 neue Website-Hosts Übersetzungen in views/offers/de.yml

**Comment by NilsVollmer** [comment]
Direkt auf develop/master als fix für #455: weitere Sprachen in offers/de.yml unter current_and_original_locale hinzugefügt

**Comment by KonstantinKo** [comment]
Weiterhin im Zusammenhang mit #455: (commit 9263766d74b59c39550f51cb375f90d8075bf0a1)
locales/de.yml übersetzungen in den JS-Bereich verschoben

**Comment by NilsVollmer** [comment]
In #631, neuer Text vor dem code_word in view/offers/de.yml in der neuen partial node next_steps.

**Comment by KonstantinKo** [comment]
für #642 (commit c084016 )
locales/views/pages/de.yml -> home.title

**Comment by Twiek** [comment]
'Irreguläres Zählen' checken (ein Apfel, zwei Äpfel... vs. eins Apfel, zwei Äpfel... --> wie sieht es da bei anderen Sprachen aus?

**Comment by Twiek** [comment]
#654 und #652 .

**Comment by NilsVollmer** [comment]
In #608 => Suchvorschläge nach Welten getrennt und neue Keys für refugees hinzugefügt.

**Comment by NilsVollmer** [comment]
Für #659 : /cells/frequently_asked_questions/[locale].yml => alle FAQ Texte hierhin ausgelagert

Direkt auf develop:
- /views/pages/[locale].yml => neue sub-nodes (de, en) in .home.title und not_found.link_text
- /gems/routes/[locale].yml => neue Übersetzungen (de, en) für routes hinzugefügt

**Comment by KonstantinKo** [comment]
Durch Marcus mit PR #671

locales/*.yml

Punkte headlines & option_any

**Comment by NilsVollmer** [comment]
Wichtig: in locales/views/offers/*.yml habe ich die doppelten Sprach-Notes entfernt und in die .shared note ausgelagert. Das muss dann bei allen kommenden Sprachen auch angepasst werden!

**Comment by NilsVollmer** [comment]
Direkt auf Develop für Mehrsprachigkeit: in den Tickets #342 und #680 zusammen (im PR f+r #680): neue & veränderte nodes in locales/[de, en].yml für mehrere Angebote an einer Adresse.

**Comment by NilsVollmer** [comment]
Für #688:
- neue locale nodes in locales/[de, en].yml: js.search.pagination mit drei subnodes

**Comment by clarat-researcher** [comment]
Test?
