### ISSUE TITLE
Chat asynchron nachladen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#628]
Da mit Freshdeskprobleme nicht unsere Probleme werden.

**Comment by KonstantinKo** [comment]
@jjungle Hierfür bräuchte ich mal bitte Zugriff auf Freshdesk. Komm am Besten einfach mal vorbei wenn du Zeit hast.

**Comment by KonstantinKo** [comment]
OK ist als hotfix auf master umgesetzt und auch schon deployed. Ist aber schwierig zu testen, ob es jetzt auch eine Verbesserung gebracht hat
