### ISSUE TITLE
Plätze anzeigen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#629]
Ziel: Ich möchte als Adresse lediglich 'Leopoldplatz' eingeben (als 'Street' oder 'Addition') ohne eine eigentliche Straße oder eine Nummer angebe zu müssen und im Frontend sehe ich einen 'Pömpel' auf dem Leopoldplatz (oder Alexanderplatz).

**Comment by Twiek** [comment]
Oder anders ausgedrückt: Bei 'Street' die Validierung, dass eine Zahl angegeben werden muss löschen.

**Comment by NilsVollmer** [comment]
@Twiek  Die Validierung der Zahlen ist jetzt optional.

Obacht: es besteht keine Garantie, dass von Google passende GeoLocations zurückkommen. Streng genommen gibt es die mit Zahlen natürlich auch nicht aber je mehr Informationen wir wegnehmen, desto wahrscheinlicher werden falsche GeoLocations.
