### ISSUE TITLE
Code-Wort

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#631]
In den 'Next-Steps' soll unter den Fließtext (getrennt durch eine Leerzeile) folgender Satz stehen: 'Wonach musst Du fragen oder auf der Webseite suchen?' (wird dann manuell übersetzt). Dahinter soll ein Wort bzw. kurzer Text (String mit 140-Zeichen Begrenzung') den man im Backend eingibt (code_word). Das Code-Wort wird nie übersetzt (weder automatisiert noch manuell). Das Code-Wort ist ein Pflichtfeld.

**Comment by NilsVollmer** [comment]
- [ ] Backend: neues Feld in offers: code_word (string, verpflichtend, max. 140 Zeichen)
- [ ] Frontend: Anzeige des neues Feldes

Fragen:
- Soll das im Backend vor dem Frontend umgesetzt werden, damit die Researcher es schonmal eingeben können?
- Die nachträgliche Einführung eines Pflichtfeldes führt dazu, dass alle Angebote dann nicht valide sind. Führt das nicht zu Problemen? 
- Da es ja eine Übergangsphase (viele Angebote ohne code_word) geben wird: wenn nicht vorhanden dann die komplette "Extension" nicht anzeigen?

Man könnte wahrscheinlich default einen leeren String eintragen.. das würde dann, solange es keine empty validierung gibt, das invalid-Problem lösen. Den leeren String könnte man dann auch einfach im Frontend abfragen und entsprechen den kompletten Block unter den next steps nicht anzeigen.

Man sollte auch potentielle Probleme mit dem translations-Branch, in dem ja die Umgestaltung der next_steps hängt, beachten.

**Comment by NilsVollmer** [comment]
So wie ich mir es gedacht habe, klappt es leider nicht. Mit der presence: true Validierung wird leider nicht nur nil sondern auch leere Strings überprüft ('' oder ' '). 

Deshalb kann das neue Feld kein Pflichtfeld sein weil damit alle Angebote invalid wären. Nach Rücksprache mit Julia & Julian haben wir entschieden, dass das Feld optional wird.

Eine automatisierte Verarbeitung wäre z.T. möglich (code_word aus der description ziehen) aber nicht sinnvoll weil auch die Description dann überarbeitet werden muss (code_word dort raus und in das neue Feld rein).
