### ISSUE TITLE
7 Hauptkategorien bei Refugees

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#633]
Bei Refugees soll es künftig eine weitere Hauptkategorie geben ('Familie' kommt hinzu). Icon wie bei Family, aber dann insgesamt 7 Kategorien die nebeneinander auf der Startseite angezeigt werden müssen.

**Comment by marcus-herrmann** [comment]
Warte jetzt auf die Reihenfolge der Icons. CSS-technisch kann das Layout aber jetzt bereits im Refugees-Bereich mit 7 Icons "umgehen".

**Comment by NilsVollmer** [comment]
Gewünschte Reihenfolge: 'Familie' bei Refugees zwischen 'Leben in Deutschland' und 'Gewalt' einordnen

**Comment by marcus-herrmann** [comment]
Ist umgesetzt auf Featurebranch: https://github.com/clarat-org/clarat/tree/feature/633-new-icon-for-refugees
