### ISSUE TITLE
Zielgruppenstamps Refugees

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#634]
Künftig sollen in den Suchergebnissen und auch auf den Angebotsseiten selber 'Zielgruppenstamps' zu sehen sein. Im Designentwurf das 'für Kinder und Jugendliche (12 - 16 Jahre)'.

<img width="735" alt="bildschirmfoto 2016-01-18 um 15 38 04" src="https://cloud.githubusercontent.com/assets/432388/12394028/a892a328-bdf9-11e5-8c4c-f523fc87126d.png">

Diese werden auf unterschiedliche Weise zusammengebaut. Bei den Refugees wie folgt.

Es kann auf Angebotsebene eine (nur eine) der folgenden Zielgruppen ausgewählt werden:

- Flüchtlinge 
- geflüchtete Kinder 
- geflüchtete Jugendliche 
- geflüchtete Kinder und Jugendliche 
- unbegleitete minderjährige Flüchtlinge 
- unbegleitete junge Flüchtlinge 
- geflüchtete Familien
- Flüchtlinge vor dem Asylantrag
- Flüchtlinge im Asylverfahren
- Flüchtlinge mit Abschiebebescheid
- Flüchtlinge mit Duldung 
- Flüchtlinge mit Aufenthaltserlaubnis

Bis auf die Zielgruppe kann für das Frontend noch eine Altersangabe in Klammern folgen. Zusammen mit dem in jedem Fall davorgeschobenen Wort 'für' würde es dann  z.B. so aussehen 'für Flüchtlinge mit Duldung (12 - 35 Jahre)' oder so 'für Flüchtlinge mit Duldung (ab 14 Jahre)', oder so 'für Flüchtlinge mit Duldung (bis 22 Jahre)' bzw. wenn es keine Altersangaben gibt oder das age_invisible Flag gesetzt wurde so 'für Flüchtlinge mit Duldung'.

Was genau in den Klammern steht ergibt sich durch die Altersangaben wie folgt.

Refugees:
age_from befüllt ('3') && age_to befüllt ('8') => '3 - 8 Jahre'
age_from leer && age_to befüllt ('15') => 'bis 15 Jahre'
age_from befüllt ('3') && age_to leer => 'ab 3 Jahre'
age_from leer && age_to leer => ''
Zusätzlich soll ein einen age_invisible Flag geben. Ist dieser gesetzt wird das Alter im Frontend nicht angezeigt, egal was sonst eingetragen wurde. Weitere Besonderheit ist, dass hinter der Zielgruppe 'geflüchtete Familien' nie eine Klammer mit Altersangaben erscheint.

Family (gibt dazu noch ein gesondertes Issues, hier erstmal nur für den Hinterkopf):
Sonderfall wenn 'age_to' > 17, dann wird es behandelt, als wäre das Feld leer. Beispiel:
age_from befüllt ('3') && age_to befüllt ('25') => 'ab 3 Jahre'

**Comment by NilsVollmer** [comment]
Also müssen folgende Dinge umgesetzt werden:
- [ ] age_visible flag in offers
- [ ] neue/eigene Zielgruppen für Refugees im Backend und entsprechende Übersetzungen im Frontend (erstmal de, den Rest aber so bauen, dass es keine Probleme mit den bevorstehenden translations gibt)
- [ ] Umsetzung von Methoden für die Ausgabe des neuen Stamps (finale Frontend-Umsetzung dann von @marcus-herrmann )

Fragen:
- Soll das age_invisible flag nur bei refugees setzbar sein (in family via Validierung verhinden) und kann es auch, wie bisher immer, ein age_visible mit default true sein?
- Soll in dem Fall, dass weder age_to noch age_from gesetzt sind, wirklich ein leerer String in Klammern dahinter stehen "()"? Sollen die Klammern in diesem Fall nicht auch verschwinden oder, was ich besser fände, ein erklärendes Wording z.B. "(jedes Alter)" da rein? Könnte mit dem Platz allerdings problematisch werden.

**Comment by NilsVollmer** [comment]
TODO: abklären, wann das neue age_visible flag automatisiert gesetzt werden soll, weil es default false ist

**Comment by NilsVollmer** [comment]
Deploy TODO:

Schritt 1: allen vorhandenen TargetAudienceFiltern als section_filter family zuweisen:
```console
fam = SectionFilter.find_by identifier: 'family'
TargetAudienceFilter.create name: 'Alle', identifier: 'everyone', type: 'TargetAudienceFilter'
TargetAudienceFilter.update_all section_filter_id: fam.id
```

Schritt 2: neue TargetAudienceFilter anlegen
```console
ref = SectionFilter.find_by identifier: 'refugees'
new_filters = [ ['refugees','Flüchtlinge'], ['refugees_children','geflüchtete Kinder'],['refugees_adolescents', 'geflüchtete Jugendliche'],['refugees_children_and_adolescents', 'geflüchtete Kinder und Jugendliche'], ['refugees_umf', 'unbegleitete minderjährige Flüchtlinge'],['refugees_ujf','unbegleitete junge Flüchtlinge'], ['refugees_families', 'geflüchtete Familien'], ['refugees_pre_asylum_procedure', 'Flüchtlinge vor dem Asylantrag'], ['refugees_asylum_procedure','Flüchtlinge im Asylverfahren'], ['refugees_deportation_decision', 'Flüchtlinge mit Abschiebebescheid'],['refugees_toleration_decision', 'Flüchtlinge mit Duldung'] , ['refugees_residence_permit','Flüchtlinge mit Aufenthaltserlaubnis']]
new_filters.each do | item |
TargetAudienceFilter.create name: item.last, identifier: item.first, type: 'TargetAudienceFilter', section_filter_id: ref.id
end
```
