### ISSUE TITLE
Stamps fürs Frontend generieren

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#643]
Gemäß Tabelle in der clarat Bibel.

**Comment by Twiek** [comment]
Folgende Regeln gibt es für Zwischenwelt-Angebote, wie zum Beispiel den Berliner Krisendienst:
Der Researcher legt das Angebot an und wählt in dem Falle beide Welten aus: family & refugees
Der Researcher schreibt das Angebot wie gewohnt (Sprache bekommt auch ein Update zu der Zwischenwelt)
Der Researcher wählt Kategorien aus - es müssen F+R Kategorien sein! Wenn nicht bereits als F+R markiert, dann vorher Anfrage an TKKG.
Der Researcher wählt gemäß der family-Logik die target audience/gender aus. Diese sollten dann auch als Stamp generiert werden und sind bei dem Angebot sichtbar. Der Flüchtlingsbezug ist hier nicht relevant, auch wenn die Angebote bei refugees sichtbar sind.
Der Researcher wählt die Altersgrenzen der refugees Welt und setzt bei allen Angeboten das Alter auf invisible.

**Comment by NilsVollmer** [comment]
Ich kralle mir das mal für die Generierung des stamps. Dann kann sich Marcus anschließend um das Frontend kümmern.

**Comment by Twiek** [comment]
Frontend gemäß dem angehängten Design von Tino umsetzen.

[desktop_1680_searchresults_V9.pdf](https://github.com/clarat-org/clarat/files/134602/desktop_1680_searchresults_V9.pdf)

**Comment by NilsVollmer** [comment]
Deploy TODO: 
```
family_section = SectionFilter.find_by name: "Family"
TargetAudienceFilter.create name: 'Schwangere mit Kind', identifier: 'family_pregnant_with_child', section_filter_id: family_section.id
["Kinder", "Eltern", "Familie", "Bekannte", "Schwangere", "Alle"].each_with_index do |name, index|
ta = TargetAudienceFilter.find_by name: name
next unless ta
ta.identifier = TargetAudienceFilter::FAMILY_IDENTIFIER[index]
ta.save
end
```

**Comment by NilsVollmer** [comment]
@Twiek aktueller Stand inkl. den deploy TODOs auf staging deployed.

**Comment by NilsVollmer** [comment]
Nach Rücksprache mit @KonstantinKo wird die Logik doch von clarat nach clarat_base verlagert, um sie nicht im Frontend dupliziert (CoffeeScript & Ruby) vorhalten zu müssen. Das wäre mit der Anzeige des Stamps im Offer.show (sehr baldiges Feature) nötig geworden.

**Comment by Twiek** [comment]
@NilsVollmer Würde die Weltkugel gerne mit einem Mouseover versehen. Für wie aufwendig (auch performancetechnisch) hältst Du es dort nicht nur etwas allgemeines einzustellen (z.B. 'Dieses Angebot kannst du in verschiedenen Sprachen wahrnehmen'), sondern direkt die dem Angebot zugeordneten Sprachen anzuzeigen, also z.B. 'Dieses Angebot kannst du in Deutsch, Spanisch und Türkisch wahrnehmen'?

**Comment by NilsVollmer** [comment]
Auslagerung der Logik in clarat_base inkl. Tests ist soweit fertig und der aktuelle develop/master Stand ist gemerged. So gesehen ist die Funktionalität von meiner Seite aus Fertig.

**Comment by NilsVollmer** [comment]
@Twiek Die language_filters schicken wir ja schon an Algolia also wäre es kein großer Akt, einen mouse_over Text bereitzustellen. Muss dann natürlich entsprechend lokalisiert werden. Ich setze das testweise mal um.

**Comment by NilsVollmer** [comment]
@Twiek Ich hab's mal anstatt des stamps ausrendern lassen:

![image](https://cloud.githubusercontent.com/assets/1733220/13292331/9bfdbadc-db1b-11e5-8d01-d445f411ca6e.png)

**Comment by Twiek** [comment]
Ok, dann bitte umsetzen... ;-)

**Comment by NilsVollmer** [comment]
Aktueller Stand auf Staging deployed also gerne anschauen.

**Comment by Twiek** [comment]
Bitte noch mal mit aktuellen Daten auf Staging deployen und bei allen Angeboten < Version 4 (siehe Elefantenrunde) keinen Stamp generieren.

**Comment by NilsVollmer** [comment]
@Twiek Ist zusammen mit dem 5-Ebenen Kategoriebaum auf Staging deployed.

**Comment by NilsVollmer** [comment]
TODO: Backend-locales auslagern & anschließen localeapp Projekt für clarat_base öffnen. Im Optimalfall stehen da dann nur noch die stamp entries drin.
