### ISSUE TITLE
Neue Sprachfilter anlegen

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#644]
Bitte folgende Sprachfilter neu anlegen:
Hebräisch
Tschechisch
Slowakisch
Koreanisch
Finnisch
Kreolisch
Montenegrinisch
Suaheli
Balinesisch

**Comment by NilsVollmer** [comment]
Mit folgenden Anpassungen aufgenommen:
- für kreolisch gibt es 4-5 Möglichkeiten. Ich habe nach Absprache mit Bettina Kreolisch-Englisch und Kreolisch-Französisch aufgenommen. Falls noch Kreolisch-Portugiesisch oder Haiti-Kreolisch benötigt wird, bitte neu melden.
- Montenegrinisch gibt es im ISO 639-2 nicht.. Wikipedia spuckt dazu serbisch (haben wir schon) oder serbokroatisch (laut Lavinia politisch unkorrekt) aus. Deshalb vorerst rausgelassen.
- Suaheli ist Swahili oder auch Kisuaheli => haben wir schon drin

**Comment by jjungle** [comment]
Folgende konnte ich schon in Erfahrung bringen, der Rest steht noch aus:
- [ ] Balinesisch
ISO 639-2: 'ban'
Eigenbezeichnung: 'Basa Bali'

- [ ] Tschechisch
ISO 639-2: 'cze'
Eigenbezeichnung: 'čeština'

- [ ] Hebräisch
ISO 639-2: 'heb'
Eigenbezeichnung: 'עברית'

- [ ] Koreanisch
ISO 639-2: 'kor'
한국말 (Südkorea)

조선말 (Nordkorea)

- [ ] Finnisch
ISO 639-2:  'fin'
Eigenbezeichnung: 'suomi'

- [ ] Slowakisch
ISO 639-2: 'slo'
Eigenbezeichnung: 'slovenský jazyk'

**Comment by NilsVollmer** [comment]
Ich würde dann lieber auf die restlichen warten und alle auf einmal anlagen ;-)

**Comment by jjungle** [comment]
Genug gewartet :+1:

**Comment by NilsVollmer** [comment]
Code ist fertig, nach dem Deploy müssen sie im Backend noch angelegt werden.

**Comment by Twiek** [comment]
Nach Deploy bitte an Julian verweisen der die Filter dann im Backend anlegt
