### ISSUE TITLE
Trenner in dem Suchoptionen Sprachauswahl-Dropdown 

### ISSUE THREAD

**Issue by JulianJung** [clarat-org/clarat#645]
Nach den "Top-Sprachen" sollte ein Trenner eingefügt werden, um klar zumachen das von hier ab an anders sortiert wird.

**Comment by Twiek** [comment]
Also bevor die Reihenfolge alphabetisch wird (aktuell vor 'Albanisch').

**Comment by marcus-herrmann** [comment]
Wie besprochen: Da Selects Betriebssystem-Sache und damit nicht ohne Komplettersetzung (jQuery UI) zu stylen, käme nur http://stackoverflow.com/questions/899148/html-select-option-separator in Frage, `<option disabled>-------</option>`. So eine Trenner-Option ist aber nicht ohne große backendseitige Umbauten machbar, laut @KonstantinKo und @NilsVollmer

**Comment by Twiek** [comment]
In dem Fall dann doch nur streng alphabetisch, alles andere ist zu verwirrend (https://github.com/clarat-org/clarat/pull/892).
