### ISSUE TITLE
In der jeweiligen Welt nur die dazugehörigen Zielgruppenfilter anzeigen

### ISSUE THREAD

**Issue by NilsVollmer** [clarat-org/clarat#649]
Aktuell werden alle aus dem Array gezogen und (in family) angezeigt. Als Hotfix werden nur die ersten fünf (die ursprünglichen Family-Zielgruppen) genommen.

Es sollen in der jeweiligen Welt nur die dazugehörigen Zielgruppenfilter in der erweiterten Suche zur Auswahl stehen. Für Refugees muss das Element dann noch im CSS wieder eingeblendet werden.

**Comment by NilsVollmer** [comment]
Aktuell auf Staging deployed. Design-Anpassungen sind nötig weil die wordings der refugees-Zielgruppen dezent lang sein (werden als Zweizeiler dargestellt).

**Comment by Twiek** [comment]
Bitte einmal checken ob man nur für den Filter die Anzahl der Zielgruppen reduzieren/zusammenfassen kann.

**Comment by Twiek** [comment]
@JulianJung Wenn sich das erledigt hat bitte schließen. Ansonsten das Problem bitte noch mal genauer erklären (gerne mit Link und/oder Screenshot).

**Comment by JulianJung** [comment]
Die Zielgruppen wurden ja nun komplett abgeändert in clarat-ref. Somit nicht mehr relevant, oder?
