### ISSUE TITLE
Safaribug

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#65]
Zumindst konnte ich bisher nur in safari nachvollziehen.

Ich gehe auf developer.clarat.org und suche etwas (z.B. 'drogen'). Wenn ich dann auf der Suchergebnisseite auf das Clarat-Logo klicke komme ich wieder auf die Startseite. Hier ist dann aber das Design zerschossen (Kategorie-Icons) und ich kann auch nicht mehr in das Suchfeld klicken.

![bildschirmfoto 2014-12-11 um 17 54 24](https://cloud.githubusercontent.com/assets/432388/5397988/1234020a-815f-11e4-8d58-077b33086db5.png)

**Comment by marcus-herrmann** [comment]
Inzwischen Theorie: 

`/app/views/offers/shared/_search_form.html.slim` bzw. Formtastic rendert List items (je für Input Offers, Location und den Absende-Button), das ganze ist aber nur von einem DIV und nicht etwa einer UL umgeben. Eine Möglichkeit ist, dass dies Twitter-Typeahead irritiert. Komme morgen auf Euch zu, um Formtastic ggf. hier saubere Semantik rendern zu lassen.

Wenn das nicht hilft, versuche ich über die Twitter Typeahead-API zu gehen: https://github.com/twitter/typeahead.js/blob/master/doc/jquery_typeahead.md (explizites Destroy, dann noch mal initiieren).
