### ISSUE TITLE
Remove 'Hidden contact" aus Notizen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#657]
Vorher noch mal checken wie viele es gibt. Auf #622 warten.

**Comment by jjungle** [comment]
#622 ist fertig.

'Referenzpunkt' samt Auswahlmöglichkeit kann auch gleich mit entfernt werden.
Wurde ausschließlich für die Hidden Contacts genutzt.

**Comment by NilsVollmer** [comment]
Hidden_contact Notes gibt es tatsächlich aktuell keine. Den identifier rauszunehmen ist also kein Problem.

Zu dem Refenrenzpunkt: eine Note kann von einer anderen Note oder einer Kontaktperson referenziert werden. Sollen diese Beziehungen wirklich gelöscht werden? Klingt nach einer durchaus sinnvollen Sache, die wir auch im Backend 2.0 wahrscheinlich wieder brauchen werden...

**Comment by NilsVollmer** [comment]
Im Gespräch geklärt: enum hidden_contact und Referenz zu KontaktPersonen rausnehmen. Referenzen von Notes untereinander können bleiben.
