### ISSUE TITLE
Kontaktpersonen Organisationen zuordnen (und Feld ergänzen)

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#658]
Kontaktpersonen sollen auch Organisationen zu geordnet werden können (Analog Angeboten).

Kontaktpersonen sollen ein zusätzliches Feld erhalten mit den folgenden Auswahlmöglichkeiten:

- 'Chef' (umgangssprachlich, da es bei einer gGmbH der 'Geschäftsführer', bei einer AG der 'Vorstand' etc. ist und wir hier nicht unnötig kleinteilig werden wollen)
- 'Öffentlichkeitsarbeit'
- 'Sekretariat'
- 'Sonstige'

**Comment by NilsVollmer** [comment]
Organisationen haben schon ContactPeople - die konnte man im Backend nur nicht auswählen.

Deshalb auf _base nur das neue Feld position hinzugefügt.

**Comment by NilsVollmer** [comment]
Der PR für die Änderungen in claradmin folgt dann nach dem _base PR merge.

**Comment by NilsVollmer** [comment]
PR aktualisiert, 'superior' anstatt 'chef'

**Comment by NilsVollmer** [comment]
PR auf claradmin erstellt.
