### ISSUE TITLE
Neue FAQs

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#659]
Inhalte gemäß Google-Doc (Stand 1.2.).

Bisherigen Slim-Code gerne sehr kritisch prüfen und gegebenenfalls komplett neu aufsetzen. Dabei insbesondere berücksichtigen, dass die FAQs händisch übersetzt werden.

**Comment by NilsVollmer** [comment]
Icons in den FAQ werden dann, wie besprochen, später nachgeliefert.
