### ISSUE TITLE
Responsive optimieren

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#66]
Siehe Screenshots:

![bildschirmfoto 2014-12-15 um 12 43 55](https://cloud.githubusercontent.com/assets/432388/5436021/ebc08994-8461-11e4-9ee3-8c4ac55f1f4e.png)
![bildschirmfoto 2014-12-15 um 12 44 12](https://cloud.githubusercontent.com/assets/432388/5436023/ebc39a80-8461-11e4-8f0b-3d825f743e2c.png)
![bildschirmfoto 2014-12-15 um 12 44 35](https://cloud.githubusercontent.com/assets/432388/5436022/ebc0e8ee-8461-11e4-8700-de2b3a37a5a5.png)

**Comment by marcus-herrmann** [comment]
Hier aufgeführte Fehldarstellungen/abgebildete Screenshots sind gefixt. Da andere Tickets sich noch mal grundsätzlich mit der Result-Darstellung befassen und intensives Realgeräte-Testing noch aussteht, schließe ich hier und kommentiere in den genannten anderen Tickets, bzw. erstelle neue (pro Setup/Device).
