### ISSUE TITLE
Pagination in mobiler Ansicht ohne Funktion

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#666]
Die pagination ist mobil nicht klickbar.

**Comment by NilsVollmer** [comment]
Nachforschung hat ergeben: die Links sind wohl nicht kaputt aber um S-Layout legt sich der Kategorie-Container über die Pagination-Leiste. Sollte für @marcus-herrmann keine große Sache sein, also bitte möglichst zeitnah beheben, damit man auf mobile die Angebote wieder durchsuchen kann.

**Comment by marcus-herrmann** [comment]
Ich bekomme develop gerade nicht zum Laufen, habe aber "blind" einen Hotfix auf develop gepusht. Bitte prüfen und ggf. Hinweis geben. Bis Donnerstag!

**Comment by NilsVollmer** [comment]
Habe den fix auf master cherry-picked und auf staging getestet => funktioniert :)

Geht jetzt auf production live damit er nicht auf den translations branch warten muss.

**Comment by NilsVollmer** [comment]
Live und working.
