### ISSUE TITLE
Icons in die FAQs einbauen

### ISSUE THREAD

**Issue by NilsVollmer** [clarat-org/clarat#669]
Im Anschluss an #659 sollen bei den Fragen 'Zu welchen Themen finde ich bei clarat XY Hilfe?' sollen die entsprechenden Kategorie-Icons eingebaut werden.

**Comment by NilsVollmer** [comment]
Die li classes sind wie besprochen eingebaut - der Rest dürfte CSS für @marcus-herrmann sein.

**Comment by marcus-herrmann** [comment]
PR gestellt
