### ISSUE TITLE
Mini-Info-Grafik "translated by Google"

### ISSUE THREAD

**Issue by KonstantinKo** [clarat-org/clarat#670]
Wir bräuchten bitte eine Grafik, die Wiedererkennungswert zum "translated by Google"-Header-Bildchen hat, aber in etwa die Größe vom Warndreieck hat. Etwas breiter wird es schon dürfen. Der Wunsch war, dass es weniger nach einem Warnhinweis/Fehler auf der Seite aussieht und mehr nach einem "FYI".

Dann ersetz das Warndreieck bitte durch diese Grafik. Du findest den code dafür in `app/helpers/translation_helper.rb #automation_warning`.

Bei der Gelegenheit könntest du auch nochmal auf das CSS schauen. Ich habe da das Problem nicht gut gelöst bekommen, dass auf bestimmten Breiten der Warnhinweis auf eine neue Zeile floated.

**Comment by marcus-herrmann** [comment]
Skizze (Farbigkeit und Reinzeichnung würde bei Gefallen folgen)
@Twiek : Deine Meinung bräuchte ich noch


![group](https://cloud.githubusercontent.com/assets/505181/12975649/b938a5de-d0bd-11e5-9c5b-eb5deefa1143.png)

**Comment by marcus-herrmann** [comment]
@KonstantinKo Warum die Zuweisung? #673 ist der PR hierzu (oder geht es um die failenden Tests?)
