### ISSUE TITLE
Asana API-Keys updaten

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#672]
Siehe https://asana.com/guide/help/api/api?utm_source=Asana&utm_medium=email&utm_campaign=6763840_API%20Key_2.10.16&utm_content=learn%20more&dm_i=1L9Q,40Z0G,KPZIKW,EK5KO,1#gl-api-key

**Comment by KonstantinKo** [comment]
Soweit ich das sehen kann benutzen wir den Asana API-Key gar nicht sondern nur Personal Access Tokens
