### ISSUE TITLE
Mobiles Offer show: main-container hat zu großen Abstand nach oben

### ISSUE THREAD

**Issue by marcus-herrmann** [clarat-org/clarat#675]
Siehe Screen

<img width="379" alt="bildschirmfoto 2016-02-11 um 17 53 32" src="https://cloud.githubusercontent.com/assets/505181/12983205/86a68778-d0e8-11e5-8199-317d9ecec13c.png">

**Comment by Twiek** [comment]
In dem Rahmen auch mit einer kleiner Schriftgröße des Angebotstitels experimentieren (z.B. 24px) und einen Vorschlag machen.

**Comment by marcus-herrmann** [comment]
Auf eigenem Fix-Branch: https://github.com/clarat-org/clarat/compare/fix/675-mobile-main-container, trotz Hotfix-Charakter dieses Issues. 24px abgebildet:

![doloremque quisquam rerum nostrum vero clarat 2016-02-18 11-23-42](https://cloud.githubusercontent.com/assets/505181/13140400/2d916e9c-d632-11e5-8c3c-e7b044ddb18a.jpg)
