### ISSUE TITLE
Codewort verpflichtend machen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#678]
Im Backend

**Comment by NilsVollmer** [comment]
@Twiek Wir wollten noch kurz mit @KonstantinKo quatschen, ob es damit Probleme gibt, weil viele Angebote dann invalid sind.

**Comment by Twiek** [comment]
@NilsVollmer: Sollte an die Version Codewort gehängt werden. Bitte in dem Rahmen checken wie viele dieser Logic-Version an invalide sind. Liste der IDs dann an Julian der sich um zügige Nachbearbeitung kümmert.

**Comment by NilsVollmer** [comment]
Im Gespräch mit @KonstantinKo waren wir beide der Meinung, dass wir solche Features auf das Backend 2.0 verlagern wollen.

Es scheint ja auch so gut zu klappen: von den 809 Angeboten in der CodeWord-Version haben gerade mal 21 keines zugewiesen. Sortierte IDs: 2080, 2097, 2151, 5881, 6086, 6110, 6406, 6452, 6502, 6504, 6506, 6527, 6546, 6547, 6562, 6688, 6692, 6776, 6818, 7208, 7210

**Comment by Twiek** [comment]
Ok, lass uns damit warten.
