### ISSUE TITLE
Ein Angebot, Zwei Welten

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#679]
Es soll möglich sein, dass ein und  dasselbe Angebot künftig in beiden Welten angezeigt wird.

Dafür müssen beide Welten ausgewählt sein. In diesem Fall muss sich die Validierung bei den Kategorien darauf beschränken, dass dem Angebot mindestens eine R bzw. F/R Kategorie und mindestens eine F bzw. F/R Kategorie zugeordnet ist.

In den jeweiligen Suchergebnissen muss ein anderer Zielgruppenstamp angezeigt werden. Einmal der Refugee-Stamp und einmal der zusammengesetzte Family Stamp.

**Comment by KonstantinKo** [comment]
@NilsVollmer Bitte _base PR reviewen und mir dieses Issue wieder zuweisen

**Comment by KonstantinKo** [comment]
@Twiek PR auf claradmin
