### ISSUE TITLE
Versionierung

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#683]
Angebote sollen (aktuell) eine von 5 Versionsnummern tragen (zukünftig wird es eventuell weitere geben):

- 1 (Erklärung: Vor Sprache, Name: Rewrite)
- 2 (Erklärung: Nach Sprache und vor Split, Name: Sprache)
- 3 (Erklärung: Nach Split und vor TKKG, Name: Split)
- 4 (Erklärung: Nach TKKG und vor Codewort, Name: TKKG)
- 5 (Erklärung: Nach Codewort, Name: Codewort)

Wird ein Angebot neu erstellt (initialized) erhält es keine Versionsnummer.

Die Versionsnummer kann zum einen händisch vergeben werden, zum anderen wird sie aber auch automatisch vergeben. Folgende Events triggern eine solche Vergabe:

- Wechselt ein Angebot in den Zustand 'completed' oder 'approved' (egal woher) so wird diesem Angebot automatisch die neuste Versionsnummer zugeschrieben (vorerst '5').

Initial sollen (fast) alle Angebote nachträglich Versionsnummern erhalten. Hierbei bitte gemäß E-Mail vorgehen.

**Comment by KonstantinKo** [comment]
Abfrage für "Offer IDs von Offers, die vor Tag X completed wurden", bei der ich mir ~ 70% sicher bin, dass sie das tut, was ich von ihr erwate:
```ruby
Offer.joins(:versions).where('offers.aasm_state = ?', 'completed').where("versions.object_changes LIKE ? OR versions.object_changes LIKE ?", "%aasm_state:\n- initialized\n- completed\n%", "%completed:\n- false\n- true%").where('versions.created_at < ?', Date.new(2016,01,27)).ids.uniq
```

@NilsVollmer bitte auch nochmal drüber schauen

**Comment by KonstantinKo** [comment]
@Twiek: OK ich habe jetzt alle alten Angebote nach den Vorgaben im GoogleDokument mit Versionsnummern versehen.

**Comment by KonstantinKo** [comment]
PR auf claradmin
