### ISSUE TITLE
Codewort in Algolia aufnehmen

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#684]
Die Codewörter tauchen zwar in den Next Steps auf, werden allerdings nicht, wie die Next Steps, für die Suche berücksichtigt.

**Comment by NilsVollmer** [comment]
PR auf _base gestellt, auf claradmin ist es danach nur noch ein bundle update.

Macht definitiv Sinn, dass noch zusammen mit der Mehrsprachigkeit zu deployen, da wir ansonsten wieder alle Angebote neu indizieren müssen.
