### ISSUE TITLE
Fremdsprachige Angebote auch in der Sitemap aufnehmen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#686]

**Comment by KonstantinKo** [comment]
Sitemaps haben seit dem Welten-Split gar nicht mehr funktioniert. Der commit ist somit auch gleich ein Bugfix gewesen.

Daher direkt auf develop umgesetzt.

**Comment by Twiek** [comment]
Bin gerade doof das zu testen. Geht das lokal überhaupt?

**Comment by KonstantinKo** [comment]
Mit `rake sitemap:generate` kann man sich auch ne Sitemap okal generieren lassen.

**Comment by Twiek** [comment]
@KonstantinKo Brauchts dann eigentlich auch ein Deploy-To-Do?
