### ISSUE TITLE
Neue family Target Audience

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#687]
Wir brauchen eine neue Target Audience namens 'Schwangere mit Kind' 
folgender Stamp sollte sich daraus ergeben:
für Schwangere mit Kind (Alter wenn visible)

**Comment by NilsVollmer** [comment]
Umsetzung in #643 enthalten - Depoy TODOs beachten!

**Comment by NilsVollmer** [comment]
Update: pending weil es auf neue Entscheidungen wartet.

**Comment by NilsVollmer** [comment]
Zusammengefasst in #716 , deshalb kann das hier geschlossen werden.
