### ISSUE TITLE
'.' vs. '>' in den Kategorien

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#689]
Auf der Suchergebnisseite erscheint vor einigen Kategorien ein '>' obwohl es keine sichtbaren Unterkategorien dazu gibt (invisible). In diesen Fällen sollte dort auch ein '.' angezeigt werden. Bezüglich dieser Anzeige dürfen nur die für den Nutzer sichtbaren Kategorien berücksichtigt werden.

**Comment by NilsVollmer** [comment]
TODO: current_section beachten!

**Comment by NilsVollmer** [comment]
Erledigt und PR aktualisiert.
