### ISSUE TITLE
Bug: Skript-Fehler im Backend

### ISSUE THREAD

**Issue by NilsVollmer** [clarat-org/clarat#694]
Bei der Angebotserstellung gibt es gerade einen Skriptfehler: 'Uncaught TypeError: Cannot read property '1' of null', der wohl durch die folgende Zeile in der next_steps_offers_area Methode hervorgerufen wird:

```offer_id = /^.*\/offer\/(\d+)\/edit.*$/.exec(location.href)[1] ````

Das Ziehen der Offer_id aus der URL klappt so nur beim editieren von Angeboten, aber nicht beim Erstellen, da die URL da einfach nur '/offer/new' ist. Die Angebots-ID muss in diesem Fall anders gezogen werden. 

Anscheinend führt dieser Fehler dazu, dass sich die modalen Views innerhalb eines neuen Angebots beim Speichern nicht schließen. Es sieht dann wie ein Fehler aus und man kann auch mehrfach Speichern und somit Dubletten erzeugen.

**Comment by KonstantinKo** [comment]
hotfixed & production deployed

**Comment by NilsVollmer** [comment]
Super, klappt wieder!
