### ISSUE TITLE
Next-Step-Baustein mit Link

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#695]
'Melde dich bei deinem [Berliner Jugendamt] und frage nach, wie du diese Hilfe bekommen kannst.'

'Contact your [youth welfare office in Berlin] and find out how you can obtain this help.'

Der Link führt jeweils hier hin:
https://service.berlin.de/jugendaemter/

**Comment by NilsVollmer** [comment]
Auf production & staging angelegt und auf Letzterem getestet.
