### ISSUE TITLE
Next Step Bausteine ebenfalls duplizieren

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#698]
Inkl. Reihenfolge.
Außerdem soll das Codewort auch mitdupliziert werden.

**Comment by jjungle** [comment]
Hatte dazu schon ein Ticket (#696).
Das 'Code word' sollten beim duplizieren von Angeboten ebenfalls dupliziert werden.

**Comment by KonstantinKo** [comment]
Das Codewort wird doch mitdupliziert!?

**Comment by KonstantinKo** [comment]
Next steps duplizieren war ein Einzeiler. Dass die Reihenfolge mitkommt funktioniert scheinbar auch so. Auch wenn ich nicht wirklich weiß, wie das funktioniert.

Njaa, ist auf claradmin direkt auf develop
