### ISSUE TITLE
Neuer State: 'Doze'

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#699]
Gedacht für Angebote bei denen wir nicht an genug Infos kommen um sie fertigzustellen, die wir aber für Analysen dennoch im Backend haben wollen.

Man kann ausschließlich von 'initialized' in 'doze' wechseln und von 'doze' ausschließlich in 'completed'.

**Comment by NilsVollmer** [comment]
PR auf _base, Änderungen auf in claradmin im Anschluss.

**Comment by Twiek** [comment]
Ok, habe gemerged.

**Comment by NilsVollmer** [comment]
PR auf claradmin. Der Button-Text ist 'Schlafen legen' und der state wird als 'dozing' angezeigt. Beides kann, falls anders gewünscht, einfach in der entsprechenden locale geändert werden.
