### ISSUE TITLE
Mandrill ist doof

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#705]
Weil sie ihren Service nennenswert umbauen und nicht mehr kostenlos anbieten (bei Heroku sind sie dann auch raus, wobei mir noch nicht ganz klar ist, ob das auch für Mailchimp gilt).

Hintergrund:
http://blog.mandrill.com/important-changes-to-mandrill.html
http://blog.mailchimp.com/important-changes-to-mandrill/

D.h. wir müssten ein wenig umbauen und künftig mindestens 20US$ im Monat bezahlen. Kein Beinbruch, aber Anlass sich auch über Alternativen Gedanken zu machen. Da bieten sich natürlich die Heroku-Add-Ons an (https://elements.heroku.com/addons#email-sms).

Habe bisher gutes über SendGrid (https://elements.heroku.com/addons/sendgrid) und Mailgun (https://elements.heroku.com/addons/mailgun) gehört die auch beide für unsere Bedürfnisse erstmal kostenlos wären.

Bitte mal checken und auch den Migrationsaufwand für die verschiedenen Lösungen prüfen und eine Empfehlung aussprechen.

**Comment by KonstantinKo** [comment]
Auf clarat durch sendgrit ersetzt.  Auf claradmin muss noch. Braucht privacy Anpassungen.

**Comment by KonstantinKo** [comment]
Ist ersetzt auf den entsprechenden branches in clarat & claradmin. Noch keine PRs erstellt, da ja noch die privacy policy angepasst werden muss

**Comment by Twiek** [comment]
Warte auf Rückmeldung von Anne.
