### ISSUE TITLE
Zielgruppenstamp in der Angebotseinzelansicht

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#706]
Gemäß Design von Tino.

![zielgruppe_v1](https://cloud.githubusercontent.com/assets/432388/13322228/bb3ff03c-dbd3-11e5-83c8-758066a9cffb.png)

**Comment by marcus-herrmann** [comment]
Auf eigenem Feature-Branch, https://github.com/clarat-org/clarat/tree/feature/706-stamp-in-offer-show
