### ISSUE TITLE
Locationfelder 'Local number' & 'Email' löschen

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#708]
Die Locationfelder 'Local number' & 'Email' werden nicht mehr benötigt, die bisher aufgenommenen Datensätze können ebenfalls ersatzlos gelöscht werden.

**Comment by NilsVollmer** [comment]
Nochmal um Sicher zu gehen: von den 1607 Locations haben gerade...
- 569 eine local_number und
- 518 eine email

Die sollen tatsächlich alle gelöscht und jegliche Anzeige (falls vorhanden) im Frontend entfernt werden??

Wenn ja: es gibt auch noch das Feld 'area_code', dass anscheinend zur local_number dazugehört (Vorwahl '030'). Ist das dann Kunst oder kann das auch weg?

**Comment by jjungle** [comment]
Ja, tatsächlich. Habe 3-4 mal nachgefragt ob man sich wirklich sicher sei.
Im Frontend sind die Daten nie angekommen.
'area code' gehört zur 'local_number' und kann ebenfalls weg.

**Comment by NilsVollmer** [comment]
PR auf _base, der Rest ist vorbereitet und kommt dann nach merge direkt hinterher.
