### ISSUE TITLE
Next Step Übersetzungen automatisiert hinzufügen.

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#710]
Siehe E-Mail.

**Comment by KonstantinKo** [comment]
Nils sitzt schon dran

**Comment by NilsVollmer** [comment]
Okay, ist auf production (und staging) erledigt. In der Tabelle habe ich die fehlenden Übersetzungen gekennzeichnet ('??'), damit man sie schnell findet. Wenn die Übersetzungen dafür nachkommen, einfach an mich weiterleiten (Deutscher Ausgangstext + einzelne Übersetzung).

Ansonsten fehlt Türkisch komplett und vollständig war die Liste auch nicht: 176 Einträge aber auf Production haben wir aktuell 231.

**Comment by NilsVollmer** [comment]
Ich close das hier, da es ein inhaltlich ähnliches, neues Ticket gibt #838
