### ISSUE TITLE
Target Audience Anpassung ..mit Kind/Baby

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#716]
2nd part of Stamp => neutral Gender einführen um 'mit Kind/Baby' Zusatz zu erzeugen. Wäre für die Eingabelogik intuitiver. ?!
Rückwirkende Anpassungen automatisch möglich.

Bei folgenden Target Audiences sollte der 'mit Kind' Zusatz in Zukunft zu einem 'mit Baby' Zusatz werden, sobald 'age from=0' und 'age to=1'

| Im Backend vergeben:                                             | Im Frontend-Stamp angezeigt:  |
|------------------------------------------------------------------|-------------------------|
| Kernfamilie + Gender. 1st pt. o. S. - Female + Age from/to = 0/1 | Mütter mit Baby         |
| Kernfamilie + Gender. 1st pt. o. S. - Male + Age from/to = 0/1   | Väter mit Baby          |
| Schwangere mit Kind + Age from/to = 0/1                          | Schwangere mit Baby (fragwürdig da nur sehr kurze Zeit + Missverständlich => Baby im Bauch oder schon da?)    |
| werdende Väter + Age from/to = 0/1                                                     | werdende Väter mit Baby (warten  bis es Angebote hierfür gibt?) |

| Im Backend vergeben:    | Im Frontend-Stamp angezeigt:  |
|-------------------------|-------------------------|
|      'Schwangere mit Kind'     | für Schwangere mit Kind (Alter wenn visible)          |

| Im Backend vergeben:    | Im Frontend-Stamp angezeigt:  |
|-------------------------|-------------------------|
| werdende Väter          | werdende Väter (Alter wenn visible)          |
| werdende Väter mit Kind | werdende Väter mit Kind (Alter wenn visible) [Vorschlag random 2nd Gender wählen => widerspricht der Logik aller anderen Stamps, hier generieren wir das Kind immer automatisch ] |

#687 
#701

**Comment by jjungle** [comment]
| Backendvergabe alt                                                                                          | Backendvergabe neu                                                                             | Frontend-stamp alt                                       | Frontend-Stamp neu                                           |
|-------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------|----------------------------------------------------------|--------------------------------------------------------------|
| Kernfamilie + g. 2nd part of stamp - female/male + Alter (wenn visible)                                     | -                                                                                              | für Familien mit Mädchen/Jungs                           | -                                                            |
| Kernfamilie + g. 1st p.o.s female/male + g. 2nd part of stamp - female/male + Alter (wenn visible)          | -                                                                                              | für Mütter/Väter mit Töchtern/Söhnen(Alter wenn visible) | Für Mütter/Väter und ihre Töchter/Söhne (Alter wenn visible) |
| Kernfamilie + g. 1st p.o.s female/male + Alter (wenn visible)                                               | Kernfamilie + g. 1st p.o.s female/male + g. 2nd part of stamp - neutral + Alter (wenn visible) | für Mütter/Väter mit Kind (Alter wenn visible)           | für Mütter/Väter und ihre Kinder (Alter wenn visible)        |
| Kernfamilie + Alter visible                                                                                 | Kernfamilie + g. 2nd part of stamp - neutral + Alter (wenn visible)                            | für Familien und ihre Kinder (Alter wenn visible)        | für Familien mit Kindern(Alter wenn visible)                 |
| für Schwangere + Alter (wenn visible)                                                                       | werdende Eltern + g. 1st p.o.s female + Alter (wenn visible)                                   | für Schwangere (Alter wenn visible)                      | -                                                            |
| -                                                                                                           | werdende Eltern + g. 1st p.o.s male + Alter (wenn visible)                                     | -                                                        | für werdende Väter (Alter wenn visible)                      |
| -                                                                                                           | werdende Eltern + g. 1st p.o.s female + g. 2nd p.o.s neutral + Alter (wenn visible)            | -                                                        | für Schwangere mit Kindern (Alter wenn visible)              |
| -                                                                                                           | werdende Eltern + g. 1st p.o.s male +  g. 2nd p.o.s neutral + Alter (wenn visible)             | -                                                        | für werdende Väter mit Kindern (Alter wenn visible)          |
| -                                                                                                           | werdende Eltern + Alter (wenn visible)                                                         | -                                                        | für werdende Eltern (Alter wenn visible)                     |
|                                                                                                             | werdende Eltern + g. 2nd p.o.s. neutral + Alter (wenn visible)                                 | -                                                        | für werdende Eltern mit Kindern (Alter wenn visible)         |
| Eltern + gender 1st part of stamp male/female + gender 2nd part of stamp male/female + Alter (wenn visible) | -                                                                                              | für Väter/Mütter von Söhnen/Töchtern                     | -                                                            |
| Eltern + gender 1st part of stamp - male/female + Alter (wenn visible)                                      | Eltern + g. 1st p.o.s male/female + g. 2nd p.o.s neutral + Alter (wenn visible)                | für Väter/Mütter (Alter des Kindes: Alter wenn visible)  | -                                                            |
| Eltern + Alter (wenn visible)                                                                               | Eltern + g. 2nd p.o.s neutral + Alter wenn (visible)                                           | für Eltern (Alter des Kindes: Alter wenn visible)        | -                                                            |
| -                                                                                                           | Kernfamilie + g. 1st p. o. s. - Male + g. 2nd. p.o.s. neutral - Age from/to = 0/1              | -                                                        | Väter mit Baby                                               |
| -                                                                                                           | Kernfamilie + g. 1st p. o. s. - Female + g. 2nd p.o.s. neutral - Age from/to = 0/1             | -                                                        | Mütter mit Baby                                              |

**Comment by NilsVollmer** [comment]
Pending, weil alle Stamps nochmal aus Konsistenz überprüft werden sollen. Bitte weist mir das Ticket im Anschluss wieder zu.

**Comment by jjungle** [comment]
https://docs.google.com/document/d/1-jmxo8BfbpwW02cU6GfEIeSyHb6wo3nQbifIIsLi9Vw/edit

Bitte Anhand dieses Docs umsetzen.

**Comment by NilsVollmer** [comment]
Änderungen nach deploy:
- Kernfamilie + 1st poS gesetzt => 2nd poS 'neutral zuweisen
- Kernfamilie + age_visible => 2nd poS 'neutral zuweisen
- Eltern + 1st poS gesetzt => 2nd poS 'neutral zuweisen
- Eltern + age_visible => 2nd poS 'neutral zuweisen
- Schwangere => werdende Eltern + 1st poS 'female' zuweisen, Schwangere entfernen

@jjungle Bitte bestätigen, dass die korrekt & vollständig sind.

**Comment by jjungle** [comment]
Passt alles so. Du kannst es wie vorhin besprochen umsetzen.
In dem Doc habe ich es auch aktualisiert.

**Comment by NilsVollmer** [comment]
Deploy TODO:
```
    pregnant_ta = TargetAudienceFilter.find_by(identifier: 'family_pregnant_woman')
    parents_to_be_ta = TargetAudienceFilter.create(identifier: 'family_parents_to_be', name: 'werdende Eltern')

    Offer.find_each do |offer|
      ta_identifiers = offer.target_audience_filters.pluck(:identifier)
      changed = false

      # TODO: mit Julian abklären
      if offer.gender_second_part_of_stamp.blank?
        if ta_identifiers.include?('family_nuclear_family') && (!offer.gender_first_part_of_stamp.blank? || offer.age_visible)
          offer.update_columns gender_second_part_of_stamp: 'neutral'
          changed = true
        end

        if ta_identifiers.include?('family_parents') && offer.age_visible
          offer.update_columns gender_second_part_of_stamp: 'neutral'
          changed = true
        end
      end

      if ta_identifiers.include?('family_pregnant_woman')
        # remove old TA from offer
        offer.target_audience_filters.delete(pregnant_ta)
        # add new TA and gender_first_part_of_stamp to achieve same result
        offer.target_audience_filters << parents_to_be_ta
        offer.update_columns gender_first_part_of_stamp: 'female'
        changed = true
      end

      offer.index if changed
    end

    # remove old pregnant_women TargetAudienceFilter
    pregnant_ta.delete!
```

**Comment by NilsVollmer** [comment]
Es gab Kommunikationsprobleme bei dem Feature, deshalb pending bis das alles geklärt ist. Evtl. müssen wir noch Konsolenbefehle ausführen.

**Comment by NilsVollmer** [comment]
Die offenen Fragen bei Sprache sind anscheinend geklärt und ich habe den Deploy-TODO gerade nochmal überprüft, also nachgeschaut, ob noch Dinge in der alten Vergabe-Logik existieren und die in die Neue überführt. Insofern ist das jetzt erledigt.
