### ISSUE TITLE
Automatische Mailings - Kontakte auf Orga Ebene

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#717]
Kontakte auf Orga-Ebene sollen immer dann die automatische "Orga"-Mailings bekommen, wenn folgendes erfüllt ist:
- Mailing Enabled Checkbox der Orga aktiv
- Orga hat weniger als 10 Standorte
- mind. 1 approved Angebot
- Orga muss approved sein

Es werden alle vorhandenen Orga-Kontakte dieser Orga angeschrieben.
 
Das ganze geschieht einmalig und zeitgleich mit den normalen Mailings an die Angebotsowner (gleicher Turnus). Es gibt keinerlei Follow-Up anschreiben auf dieser Ebene.

**Comment by jjungle** [comment]
Ergänzung:
Wenn eine E-Mail sowohl "Angebotsowner" als auch "Orga-Kontakt" ist, so soll sie dennoch beide Mailings erhalten.

**Comment by jjungle** [comment]
Dieser Punkt soll nun doch manuell von den Researchern beachtet werden:
- Orga hat weniger als 10 Standorte

**Comment by NilsVollmer** [comment]
Im Gespräch beschlossen:
- alle vorhandenen Orga-Kontakte werden angeschrieben
- jeder Orga-Kontakt wird nur dann angeschrieben, wenn er noch nie eine Mail bekommen hat (Orga oder OfferMail) => jeder Orga-Kontakt maximal 1x

**Comment by NilsVollmer** [comment]
Update: nach Rücksprache mit Janina sollen die < 10 Standorte für die Orga-Mail jetzt doch im Code abgefragt werden. Hintergrund: mailings_enabled wird auch für große Orgas nach manuellem Kontakt auf true gesetzt damit die Offer-Mails rausgehen. Die Geschäftsführer sollen in diesem Fall aber keine Orga-Mail bekommen weil sie ja bereits vorab manuell kontaktiert wurden.
