### ISSUE TITLE
ContactPerson.responsibility auch von Google übersetzen lassen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#719]
Einmalig nachträglich für alle + dann künftig immer wenn eine ContactPerson gespeichert wird und sich das 'responsibility' Feld geändert hat.

**Comment by allthegoldt** [comment]
Soll die Conact Person assignable sein?

**Comment by Twiek** [comment]
Nope, es soll einfach von Google übersetzt werden ohne die Möglichkeit das manuell nachzubearbeiten.

**Comment by Twiek** [comment]
Basti checkt wie viele Kontaktpersonen das bisher überhaupt betrifft und wie gut Google diese übersetzt.

**Comment by Twiek** [comment]
Betrifft aktuell 152 und Google übersetzt relativ gut (nicht perfekt). Denke wir sollten das machen.

**Comment by allthegoldt** [comment]
Bitte zuerst clarat base pull request bearbeiten und bitte entschuldige dort die vielen Commits!

**Comment by NilsVollmer** [comment]
@allthegoldt  Der _base PR sieht soweit gut aus aber im claradmin PR gibt es noch ein paar Dinge zu tun. Siehe Review.

**Comment by NilsVollmer** [comment]
Deploy TODO: bei allen ContactPersons 1x manuell die Übersetzung triggern.
