### ISSUE TITLE
Anpassung der Openings - Erstes 'Uhr' fällt weg

### ISSUE THREAD

**Issue by JulianJung** [clarat-org/clarat#720]
In den Opening Specifications geben wir bei Angabe der Uhrzeiten (dem Translator zuliebe) nur hinter der letzten Uhrzeit ein 'Uhr' an. In den Openings sollte dies ebenfalls angepasst werden.
![image](https://cloud.githubusercontent.com/assets/11425826/13527146/48584e30-e20d-11e5-86f5-1da2d3efd688.png)

**Comment by NilsVollmer** [comment]
@jjungle @Twiek Obacht: das macht nur in der 24h Notation Sinn - bei am/pm braucht man zwingend hinter beiden Zahlen das Kürzel damit es eindeutig ist. 

Die Openings schicken wir nicht an Google, sind also auch kein Problem - da haben wir die vollen Kontrolle darüber, was angezeigt wird.

Das manuelle Eintragen von Uhrzeiten in den opening_specs ist sehr fehleranfällig sobald es über den Translator geht.. der macht dann 9:00 - 16:00 clock daraus.. Wenn ihr sowas öfter braucht, sollten wir uns eher über ein entsprechendes DB-Feld (appointment_openings) für die Terminabsprache machen. Dann wird es auch vernünftig übersetzt.

**Comment by Twiek** [comment]
Dann spricht aber nichts dagegen es zumindest für die Openings zu machen (nicht die Specifications), oder? Wenn ja, go ahead!
