### ISSUE TITLE
Umsortieren der 'Wer bietet diese Hilfe an'- Box

### ISSUE THREAD

**Issue by JulianJung** [clarat-org/clarat#722]
Nach der Frage: "Wer bietet diese Hilfe an?" sollte zunächst der Organame erscheinen. Das "ein Angebot von" könnte dann weg.
Erst dann die Karte und darunter weiterhin die Adresse.
Bsp.:
![bildschirmfoto 2016-03-04 um 15 24 40](https://cloud.githubusercontent.com/assets/11425826/13529569/4080fc74-e21d-11e5-92a5-fe5bae83376a.png)

**Comment by Twiek** [comment]
Problema es: In den Suchergebnissen soll der Standortname künftig gegenüber dem Organamen priorisiert werden. Daher sollte auch in der Angebotseinzelansicht die Orga weiter unten aufgeführt werden (wie gehabt). Insofern 'nur' eine sprachliche Herausforderung. Statt 'Ein Angebot von:' eher 'Trägerorganisation' oder etwas ähnliches.

**Comment by JulianJung** [comment]
Da lieber die "Wer bietet diese Hilfe an?" Frage in eine "Wo Frage" geändert werden soll, kann das hier eigentlich zu.
