### ISSUE TITLE
Definitions regelmäßig neu generieren (auf Deutsch)

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#723]
Wenn eine neue Definition angelegt wurde sollten in regelmäßigen Abstand alle Angebote gescannt werden ob hier die Definition in der Description hinzugefügt werden muss (z.B. 1 mal pro Woche). Wenn möglich soll vermieden werden, dass der Text danach erneut an Google geschickt und übersetzt wird.

Es geht hier ausschließlich um die deutsche Version.

**Comment by KonstantinKo** [comment]
PR auf claradmin
