### ISSUE TITLE
Pfeil im aktiven Reiter

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#726]
Aktuell wird immer im inaktiven Reiter ein Pfeil angezeigt. Sollte umgekehrt sein (auf der Startseite und insgesamt im Header).

<img width="472" alt="bildschirmfoto 2016-03-08 um 12 24 25" src="https://cloud.githubusercontent.com/assets/432388/13600398/d3126e20-e528-11e5-8f84-f9a6aea3f23e.png">

Bei ausgeprägter anderweitiger Meinung bitte kurze Rücksprache.

**Comment by marcus-herrmann** [comment]
Entspricht Design: http://siteproduction.de/clarat/clarat_V5_Family/
Kann ich ändern.

**Comment by marcus-herrmann** [comment]
Als Hotfix auf develop

**Comment by Twiek** [comment]
Klappt bei mir nicht. Sieht aus wie vorher. Bitte noch mal checken.

**Comment by marcus-herrmann** [comment]
Klappt bei mir auf develop nach wie vor (Commit 39805c6f7fa11650eae3e189c5e4e10aa650d889). Cache clear?
