### ISSUE TITLE
Standortname statt Organame in den Suchergebnissen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#729]
In den Suchergebnissen statt des Organamens standardmäßig den Namen des Standortes anzeigen. Im Beispiel also statt 'ZDK Gesellschaft Demokratische Kultur gGmbH' einfach 'EXIT-Deutschland' anzeigen.

<img width="851" alt="bildschirmfoto 2016-03-10 um 11 32 47" src="https://cloud.githubusercontent.com/assets/432388/13666961/80f2690a-e6b4-11e5-9e0d-3a86196dc760.png">

<img width="350" alt="bildschirmfoto 2016-03-10 um 11 33 08" src="https://cloud.githubusercontent.com/assets/432388/13666965/83bdb0c2-e6b4-11e5-8b41-e559eecb9263.png">

Wenn kein Standortname vorhanden ist dann als Fallback doch wieder den Namen der Organisation anzeigen.

In der Angebotseinzelansicht ändert sich nichts.

Der Standortname soll dann auch in der Suche berücksichtigt werden.

**Comment by Twiek** [comment]
Und den Standortname dann auch in der Suche berücksichtigen (Prio direkt über dem Organisationsnamen).

**Comment by Twiek** [comment]
@JulianJung Kannst Du hier bitte noch mal eintragen auf was wir warten und wie der aktuelle Stand ist?

**Comment by JulianJung** [comment]
Wir warten nach wie vor auf das voranschreiten der Aktualisierungswochen, damit in den Suchergebnissen nichts völlig verqueres wie 'Büro-Nord' etc. steht.
Sobald abgeschlossen, würde ich hier bescheid geben.

**Comment by Twiek** [comment]
@JulianJung Wie ist hier der Stand?

**Comment by JulianJung** [comment]
Habe Jens bescheid gegeben. Er meldet sich sobald das ganze umgeschaltet werden kann.

**Comment by NilsVollmer** [comment]
Deploy TODO: Angebote mit location neu Indizieren (wahrscheinlich machen wir einen kompletten Index-Update weil andere Issues den auch brauchen)
