### ISSUE TITLE
Anfrage über Kontaktformular nicht in Freshdesk erschienen

### ISSUE THREAD

**Issue by JulianJung** [clarat-org/clarat#732]
Kontaktformular-Anfrag 373 ist nicht in Freshdesk angekommen. Bitte kurz nachforschen ob bei der Weiterleitung irgendwelche Probleme auftraten.

**Comment by NilsVollmer** [comment]
Ich konnte nichts finden.. der Prozess ist an sich auch sehr simpel: der ContactObserver triggert eine delayed mail an uns selbst, die wiederrum von freshdesk aus dem GMail-Account 'gezogen' wird.

Das Problem scheint beim rausschicken der Mail zu passieren: auch beim manuellen Aufruf des Observer-Codes mit der entsprechenden ID kommt die Mail nicht im Gmail-Konto an. Es gibt aber keine Fehlermeldung oder ähnliches.. an der  Mail ist mir auch nichts aufgefallen (url, message).

Ich bin ein wenig out of ideas - vllt. fällt @KonstantinKo ja noch was ein/auf.

**Comment by NilsVollmer** [comment]
Sollte mit #811 behoben sein.
