### ISSUE TITLE
Löschen von Kategorien nicht möglich

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#733]

**Comment by Twiek** [comment]
Konkretes Beispiel ist die Kategorie 562.

Fehler in den Logs sieht wie folgt aus:

<img width="1279" alt="bildschirmfoto 2016-03-11 um 18 54 20" src="https://cloud.githubusercontent.com/assets/432388/13710610/b44a6da0-e7ba-11e5-80d2-5ef505754ca0.png">

Wenn man versucht die Kategorie in der Konsole zu löschen sieht es ähnlich aus:

<img width="989" alt="bildschirmfoto 2016-03-11 um 18 55 08" src="https://cloud.githubusercontent.com/assets/432388/13710636/cf354dc4-e7ba-11e5-9063-03ba85fc04a0.png">

Eigentlich haben wir den Table ja in https://github.com/clarat-org/clarat_base/blob/master/db/migrate/20160229141529_change_translation_of_categories.rb gedropped. Keine Ahnung warum der jetzt noch Ärger macht. Hat das vielleicht mit https://github.com/clarat-org/clarat_base/blob/master/app/models/concerns/translation.rb zutun?

**Comment by NilsVollmer** [comment]
Fix direkt commited & deployed.
