### ISSUE TITLE
Analyse / Zahlen aus dem Backend

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#734]
Für Anne:

"# aller Angebote, 
die im Januar, Februar, und März (gerne jeder Monat einzeln, ich addiere dann, was ich brauche)
completed bzw. approved wurden "

Bitte Einschätzung wie (un)genau die Ergebnisse sind.

**Comment by NilsVollmer** [comment]
Nicht uninteressant, diese Zahlen.. Januar nice.. Einbruch im Februar.. März sieht wieder besser aus (erst zwei Wochen um und davon war eine auch noch Aufräumwoche)

;Januar;Februar;Maerz
Family completed;860;510;180
Refugees completed;157;127;91
Family approved;829;445;158
Refugees approved;128;57;46

Ist CSV-formatiert.. Anne will die Zahlen bestimmt in Excel haben.

Zur Genauigkeit: das ist die Anzahl der Angebote in der jeweiligen Welt, die in dem jeweiligen Zeitraum einen State-Change gemacht haben. Wenn ein Angebot z.B.: approved wurde, aber dann wieder aus irgendwelche Gründen, einen State-Change gemacht hat,  wird das nicht beachtet. Bei approved könnte man das sogar machen (nur die, die jetzt auch noch approved sind) aber bei completed geht das z.B. nicht, weil sie mittlerweile ja approved sein könnten - das wäre aber natürlich okay.

Wenn die approved-Abfrage ausgeführt werden soll, sag einfach Bescheid - ist keine große Sache.

**Comment by NilsVollmer** [comment]
Siehe Mail.
