### ISSUE TITLE
Organisationsliste bei Kooperationsangeboten

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#735]
In der Angebotseinzelansicht. Z.B. hier: http://www.clarat.org/refugees/preview/angebote/unv-einblick-in-ein-geisteswissenschaften-studium-an-einer-universitaet-fuer-fluechtlinge-mit-hochschulabschluss. Eventuell alphabetisch sortieren und klarer trennen (Leerzeile, Bullets... ).

**Comment by Twiek** [comment]
@marcus-herrmann Kannst Du hier mal testen ob Spiegelstriche/Bullet Points hier funktionieren?

**Comment by marcus-herrmann** [comment]
<img width="361" alt="bildschirmfoto 2016-08-11 um 15 25 37" src="https://cloud.githubusercontent.com/assets/505181/17589963/ef379024-5fd7-11e6-9f70-cdbe42e3877d.png">

Bei Gefallen gibt es einen Featurebranch zu 735

**Comment by Twiek** [comment]
Go for it.

**Comment by marcus-herrmann** [comment]
Pull request hierzugestellt - #895
