### ISSUE TITLE
Neuer Ankerlink in den FAQs

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#736]
Wenn ich erfolglos suche kriege ich einen Verweis auf die FAQ:

<img width="855" alt="bildschirmfoto 2016-03-14 um 12 19 09" src="https://cloud.githubusercontent.com/assets/432388/13742919/0dead9d2-e9df-11e5-9dda-82d160c48df4.png">

Dieser verlinkt allerdings nicht auf die Überschrift 'Hast du Fragen zu deiner Suche?', sondern direkt auf die erste Frage. Sollte auf die Überschrift verlinken. Den Anker der ersten Frage ('who_finds_help') aber nicht verändern, da der noch an anderer Stelle benutzt wird, sondern einen neuen Anker ergänzen.

**Comment by NilsVollmer** [comment]
Als mini-feature direkt auf develop umgesetzt.
