### ISSUE TITLE
Automatisierte Übersetzungen von Kategorien und Next Steps 

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#737]
Bitte prüfen ob folgende Lösung praktisch machbar ist.

Ich speichere eine Kategorie oder einen Next-Step-Baustein ab, wobei der deutsche und der englische Name Pflichtfelder sind. Über die Unbabel API (https://unbabel.com/products/) oder Gengo API (https://gengo.com/de/developers/) werden die fehlenden Sprachen ergänzt und dann direkt bei uns gespeichert ohne dass wir noch weiter aktiv werden müssen.

**Comment by KonstantinKo** [comment]
Also bei beiden services gibt es die Sprachen die wir brauchen nicht vom Deutschen aus. Man müsste eine Stille-Post-Übersetzung über Englisch machen, oder aber wir müssen die Researcher dazu auffordern, die next steps und Kategorienamen in Englisch einzugeben wovon aus dann übersetzt werden könnte.
Persisch gibt es gar nicht.
Ansonsten eine automatisierte API-Anbindung gibt es, ja. Könnte man über worker laufen lassen.

Weitere Idee, wie wir evtl. localeapp auch für Kategorien und Next Steps nutzen können:
Wir schreiben einen rake-task, der automatisch alle vorhandenen Kategorien und NextSteps durchgeht und bei localeapp anfragt. Da angefragte Keys die nicht existieren ja von localeapp gleich angelegt werden, kommen die keys also gleich in localeapp an. 
Vorteil: einheitliche Eingabemaske, mit unseren Übersetzern die vom Deutschen aus übersetzen.
Nachteile: Man müsste dann auch die deutschen Übersetzungen manuell in localeapp eintragen. Die keys können ja slugs von der deutschen Version sein, sodass man nur noch abtippen muss aber gemacht werden muss es wohl. Außerdem ginge dieser rake task wohl nur auf staging, man müsste sich also immer die Datenbank wieder von production auf staging kopieren und dann den task laufen lassen, um localeapp zu updaten sobald es wieder einen neuen Satz Kategorien/Next Steps gibt. Ist auch was manuelles.

@NilsVollmer Hast du noch Ideen?

**Comment by NilsVollmer** [comment]
Ich würde die API Lösung bevorzugen, weil es für uns alle am wenigsten laufende Arbeit (nachdem es programmiert ist) bedeutet. Voraussetzung ist natürlich, dass wir eine API finden, die alle unsere Sprachen abdeckt und von den Researchern würden wir dann die deutsche & englische Eingabe verlangen. Letztere wird dann als Quelle an die API geschickt.

**Comment by Twiek** [comment]
Habe mit Lavinia gesprochen und Englisch können wir inhouse abbilden und die Übersetzungen darauf basieren lassen (würde Englisch entsprechend zum Pflichtfeld der Übersetzer machen). 

Insofern klingt für mich die API-Lösung auch attraktiver, was aber ein Dealbreaker werden könnte wären künftige Sprachen (Farsi wird ja schon aktiv diskutiert). Werde da noch mal auf ne finale Aussage drängen und mich dann noch mal melden.

**Comment by Twiek** [comment]
Weitere Alternative wäre die Next-Steps Übersetzungen wieder aus der Datenbank zu holen (Vgl. Sprachfilter). Dann müssten aber für alle neuen Kategorien etc. Identifier angelegt werden.

**Comment by Twiek** [comment]
Da wir jetzt mehr und mehr auf manuelle Übersetzungen setzen schließe ich das erstmal.
