### ISSUE TITLE
Auswahl mehrere Lösungskategorien ermöglichen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#738]
Also tendenziell eine has_and-belongs_to_many Beziehung draus machen.

**Comment by NilsVollmer** [comment]
@KonstantinKo bitte drüberschauen/anpassen.

**Comment by KonstantinKo** [comment]
Bedarf Rücksprache

**Comment by Twiek** [comment]
@KonstantinKo Kannst Du hier kurz notieren was noch besprochen werden muss.

**Comment by Twiek** [comment]
@KonstantinKo Still waiting for an answer? ;-)

**Comment by Twiek** [comment]
Wenn es noch mal aufkommt schauen wir uns das noch mal an.
