### ISSUE TITLE
Newsticker Backup

### ISSUE THREAD

**Issue by NilsVollmer** [clarat-org/clarat#741]
@jjungle würde gerade die Daten des Newstickers regelmäßig als Backup speichern. Ein SQL-Dump scheint da möglich zu sein. Könnte man ja an der gleichen Stelle speichern wie die clarat und wiki Backups?

**Comment by jjungle** [comment]
@Twiek eine pragmatische Lösung wäre auch der Backup nach GoogleDrive. Es gibt Plugins die das in einem anpassbaren Turnus übernehmen (SQL-Dump + Files).

**Comment by Twiek** [comment]
Dann go ahead.

**Comment by Twiek** [comment]
@JulianJung Wie schauts hier aus?

**Comment by JulianJung** [comment]
Wird wöchentlich in Google Drive gedumpt.
