### ISSUE TITLE
Validierung der Kategorienvergabe nach clarat-Welt verschärfen

### ISSUE THREAD

**Issue by jjungle** [clarat-org/clarat#743]
Momentan ist es möglich einem family Angebot eine refugee Kategorie zuzuordnen, sofern diesem Angebot mind. eine family Kategorie zugeordnet ist. 
Gewünschte Validierung:
Angebote der family-Welt sollten ausschließlich f oder f+r Kategorien besitzen dürfen
Angebote der refugee-Welt sollten ausschließlich r oder f+r Kategorien besitzen dürfen
Angebote beider Welten können f,r und f+r Kategorien besitzen.

**Comment by NilsVollmer** [comment]
PR auf clarat_base gestellt. Auf claradmin müssen dann noch die Fehlermeldungen & Tests entsprechend angepasst werden.

**Comment by KonstantinKo** [comment]
Mündlich besprochen: Validierung passt noch nicht ganz, zweite wird benötigt
