### ISSUE TITLE
Leeres 'Wo' Feld führt zu Fehler

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#752]
Beobachtetes Verhalten: Ich bin auf der Startseite, gebe nichts in das 'Was' Feld ein und leere das 'Wo' Feld. Dann klicke ich auf ein Kategorie-Icon. Dann komme ich auf eine Seite wie diese: http://www.clarat.org/family/angebote?utf8=%E2%9C%93&search_form%5Bquery%5D=&search_form%5Bsearch_location%5D=&search_form%5Bgenerated_geolocation%5D=53.07929619999999%2C8.8016937&search_form%5Bcategory%5D=&search_form%5Bexact_location%5D=false&search_form%5Bcontact_type%5D=personal&search_form%5Bencounters%5D=hotline%2Cemail%2Cchat%2Cforum%2Conline-course%2Cportal&search_form%5Bage%5D=&search_form%5Btarget_audience%5D=&search_form%5Bexclusive_gender%5D=&search_form%5Blanguage%5D=&search_form%5Bsection%5D=family. Dort steht 'Leider konnten wir den von dir eingegeben Standort nicht finden' obwohl jetzt im 'Wo' Feld die letzte Stadt steht die dort eingegeben wurde (bevor ich das Feld geleert habe). Wenn ich jetzt noch mal auf den Suchbutton klicke wird dieser Ort berücksichtig.

Gewünschtes Verhalten: Ich leere das Suchfeld und klicke eine Kategorie: HTML5-Validierung (das Feld muss ausgefüllt werden --> aber auf das duzen achten). Wenn der Browser damit nicht klar kommt dann wie gehabt die zuletzt genutzte Stadt verwenden, allerdings diese dann nicht nur dem User anzeigen, sondern auch direkt verwenden, so dass man nicht auf einer 'Standort nicht gefunden' Seite endet. Wenn das mit dem duzen zu sehr Frickelei wird diesen Teil des Issues ignorieren.

**Comment by KonstantinKo** [comment]
Fix nach mündlicher Besprechung war, dass wir ein leeres Suchfeld als "Berlin" ansehen. Wurde als hotfix bereits deployed.
