### ISSUE TITLE
Restliche Sprachen deploy-fertig machen

### ISSUE THREAD

**Issue by KonstantinKo** [clarat-org/clarat#753]

**Comment by KonstantinKo** [comment]
Branch feature/753-languages ist für dich vorbereitet.

Da wir es am Donnerstag auch online bringen wollen, bitte wieder mit erhöhter Prio dies angehen. Ich hab schon gesehen, dass es im Französischen da Probleme auf der Startseite im "Wie funktioniert clarat"-Bereich gibt wegen der zweizeiligen Überschrift. Außerdem siehe http://www.clarat.org/pl/family -> Sorgen im Alltag.

Arabisch bleibt weiterhin spannend und hat die niedrigste Prio von den neuen Sprachen.

**Comment by marcus-herrmann** [comment]
Hi @KonstantinKo 

Habe gerade #753 ausgecheckt, finde da als Sprachen aber nur Deu und Eng vor. Pl sehe ich auf Production und kann es somit "halbblind" fixen, aber für Französisch brauche ich vermutlich einen initializer? Wäre super wenn du mir den Code per Mail schicken könntest. Rake Cache Clear natürlich gemacht.

**Comment by marcus-herrmann** [comment]
Besteht eine Chance, die Hauptkategorien-Bezeichner in den verschiedenen Sprachen in die Seeds/Fakes aufzunehmen? Gerade die überraschen ja manchmal mit ungewöhnlichen Textlängen.

**Comment by KonstantinKo** [comment]
@marcus-herrmann Ja können wir machen, setz mich später gleich mal dran

**Comment by marcus-herrmann** [comment]
Super. Ich arbeite derweil "drumherum" und committe kleinteilig, sodass ihr auf jeden Fall den ganzen Tag "was zum Deployen" habt.

**Comment by KonstantinKo** [comment]
OK die updated seeds sind pushed

**Comment by marcus-herrmann** [comment]
@KonstantinKo  Merci. Bisher keine bösen Überraschungen. Wir haben aber ein Encoding-Problem im Title-Tag des Französischen. Dachte, das über utf-8 im Dokument über dem Title zu lösen, aber eventuell kommt das so falsch aus den Sprachdateien: `Listes d&#39;aide pour les enfants, les ados et les familles | clarat`. Das `&#39;` ist zwar typografisch richtig (ein echter Apostroph), aber das eigentlich falsche Hochkomma `'` sollte uns vor dem Fehler bewahren.

**Comment by KonstantinKo** [comment]
Ja unsere französische Übersetzerin hat diese echten Apostrophe tatsächlich überall verwendet. Ist das auch an anderen Stellen ein Problem?

**Comment by marcus-herrmann** [comment]
Nein, nicht entdeckt. Es gibt weitere Apostrophen in freier Wildbahn, aber keine Probleme. Könnte das die Lösung sein: http://stackoverflow.com/questions/13052484/passing-string-with-apostrophe-to-helper-method-doesnt-display-correctly ?

**Comment by marcus-herrmann** [comment]
Uiii! Ja, der Tipp aus SO klappt! :facepunch:  Darf ich das committen (Änderung von application_helper.rb)?

**Comment by marcus-herrmann** [comment]
Kann man demnach schließen?

**Comment by KonstantinKo** [comment]
Basti schließt das dann
