### ISSUE TITLE
Follow-Up-Mail vereinheitlichen & emails/offers anpassen

### ISSUE THREAD

**Issue by NilsVollmer** [clarat-org/clarat#755]
Vereinheitlichung gemäß Word-Dokument.
- [x] Wordings vereinheitlichen

Auf der Übersichtsseite:
- [x] updated_at Datum anzeigen & Liste danach sortieren (neuste zuerst)
- [x] Anzeige hübsch machen
- [x] Beschreibung minimal dafür anpassen. (von localeapp - einfach mich darauf ansprechen)

**Comment by NilsVollmer** [comment]
Backend-Anpassungen sind fertig, Ticket geht für's Frontend an @marcus-herrmann .

**Comment by marcus-herrmann** [comment]
@Twiek @NilsVollmer Bin ein großer Fan von Minimalismus, deswegen folgender Vorschlag:

![clarat 2016-04-14 10-43-14](https://cloud.githubusercontent.com/assets/505181/14522203/c77b1720-022d-11e6-9afb-6dbb746d7710.jpg)

Der wäre auch gleich ready for Commit. Wenn man es weitertreiben und dem Backend etwas Arbeit erzeugen will, kann man auch über eine abnehmende Farbintensität, je länger das Update her ist, reden.

**Comment by Twiek** [comment]
Statt 'Update' bitte 'Zuletzt geändert'. Ansonsten schick.

**Comment by marcus-herrmann** [comment]
PR gestellt. Aktueller Text in localeapp ist noch der Lange, aber der Container ist auf Textlänge von Bastis Wunschtext vorbereitet @NilsVollmer

**Comment by Twiek** [comment]
Let me know when it's ready.

**Comment by marcus-herrmann** [comment]
PR gestellt, #764
