### ISSUE TITLE
Update auf Rails 4.2

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#76]
http://weblog.rubyonrails.org/2014/12/19/Rails-4-2-final/

**Comment by Twiek** [comment]
Ok, keine Hektik (ist bewusst 'Low Prio'). Können das ja einfach einmal im Monat checken.

**Comment by KonstantinKo** [comment]
Update auf clarat_base und claradmin geschehen. Auf clarat geht aus mir unerfindlichen Gründen die test suite kaputt - er löscht scheinbar die migrierte Datenbank und kann dann fixtures nicht mehr laden. Sehr seltsam. Issue ist also weiterhin nicht komplett fixed.

**Comment by Twiek** [comment]
Wie schauts hier eigentlich aus? Inzwischn ist Rails 5.0 ja schon offiziell...
