### ISSUE TITLE
"Rich Off-Canvas" für Offer Index mit Filtern und Kategorien

### ISSUE THREAD

**Issue by marcus-herrmann** [clarat-org/clarat#767]
Note to self, ungefähr so:

![iphone 6 plus](https://cloud.githubusercontent.com/assets/505181/14716620/1071733c-07ee-11e6-8432-9c9924a712c9.png)

**Comment by marcus-herrmann** [comment]
Zunächst Prototyp

**Comment by marcus-herrmann** [comment]
@Twiek Für KW24ff: Feature ist umgesetzt, wir sollten aber noch mal über das genaue Label des Schließen-Button reden. Dieser muss ja

a) unfallfrei übersetzbar sein
b) durch die Nennung der aktuell zusammengefilterten Offers auch eine Indikatorfunktion haben. Aktuell ist das: {n} Suchergebnisse anzeigen. Alternativ: Zurück zu {n} Suchergebnissen ?

**Comment by marcus-herrmann** [comment]
Branch: https://github.com/clarat-org/clarat/tree/feature/767-off-canvas-experiments

**Comment by marcus-herrmann** [comment]
Note to self:

* Swipe = close
* Z-Index des Close Buttons

**Comment by marcus-herrmann** [comment]
Kommt mit Commit b2c6ca036834b1eb20528f0a69bcb0ab458d405e

**Comment by marcus-herrmann** [comment]
Es bleibt noch die "XX Suchergebniss(e) anzeigen"-Problematik. Das JS ergänzt die Zahl gerade am Anfang des Strings, aber es gibt bestimmt auch andere Satzbauszenarien in anderen Sprachen

**Comment by Twiek** [comment]
Bitte checken, ob wir es mit Zahl zumindest in Deutsch und Englisch deployen können. Wenn ja, umsetzen und Deploy vorbereiten. Dann direkt ein weiteres Issue für die anderen Sprachen erstellen.

**Comment by marcus-herrmann** [comment]
Die Formulierung "XX Suchergebniss(e) anzeigen" ist natürlich nur ein Vorschlag. Letztendlich geht auch so etwas wie: "Zurück zu den Suchergebnissen: XX", das in allen Sprachen so funktionieren sollte, vielleicht nicht so elegant ist. Muss man abwägen.

**Comment by Twiek** [comment]
Finde das mit der Zahl schon recht hilfreich. Wer nicht sieht, dass sich unter dem Layer was ändert kriegt es so noch mal aufgezeigt. Denke das mit den anderen Sprachen werden wir schon hinkriegen.

**Comment by NilsVollmer** [comment]
Text wird inklusive Variable von localapp gezogen. Aktuell nur de und en (für alle restlichen Sprachen en als Fallback). Die fehlenden Sprachen sollten dann so schnell wie möglich ergänzt werden.

**Comment by Twiek** [comment]
In der Desktop-Variante funktionieren 'Suchoptionen einblenden' nicht. Ein Klick bewirkt nichts.

**Comment by marcus-herrmann** [comment]
Hast du einen Branch-Stand ausgecheckt, in dem der Commit bcb3ec9862e7e83079d43678bd25dd3177a26beb drin ist? Dort ist die Korrektur drin

**Comment by Twiek** [comment]
Never underestimate the power of 'Rails.cache.clear'...

It's working!
