### ISSUE TITLE
404 Fehler wegen u.a. falscher Routen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#768]
Wenn man z.B. auf der französischen Seite aufs Impressum klickt.

Viele, viele weitere Fehler siehe hier: https://www.google.com/webmasters/tools/crawl-errors?hl=de&siteUrl=http://www.clarat.org/#t2=1.

**Comment by Twiek** [comment]
@KonstantinKo: Bitte auch mal das Webmastertool checken und dann die Sitemaps prüfen. Viele der falschen Links die dort als 404 gebrandmarkt sind, sind in unserer Sitemap längst aktualisiert. Müssen/können wir Google noch besser anpingen, wenn sich die Sitemap geändert hat, bzw. irgendwie explizit über nicht mehr aktuelle Links informieren?

**Comment by NilsVollmer** [comment]
Die fehlerhaften Routen sollten jetzt (hoffentlich) alle soweit passen. Das ist auch als Hotfix bereits deployed. 

Bzgl. der sitemap gerne nochmal gucken.

**Comment by KonstantinKo** [comment]
@Twiek Es ist nicht wirklich automatisiert möglich, bei Google das Nichtvorhandensein einer Seite anzupingen. Normalerweise infernen die das schon aus derem Index wenn sie ein paar mal da nichts gefunden haben. Ansonsten manuell: https://www.google.com/webmasters/tools/removals

Sitemaps werden pro Tag einmal generiert, die aktuelle hab ich auch mal Stichprobenartig geprüft und es hat funktioniert.

Habe noch einen section_forward fix auf develop committed.
