### ISSUE TITLE
Einrückung von Kategorien noch nicht optimal (arabisch)

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#771]
Müssten Dreiecke und Punkte nicht eigentlich rechts neben den Kategorien stehen?

![bildschirmfoto 2016-04-15 um 15 50 49](https://cloud.githubusercontent.com/assets/432388/14563382/f24beb7e-0321-11e6-90a5-abaf49e7b43f.png)

**Comment by marcus-herrmann** [comment]
Als Hotfix auf develop
