### ISSUE TITLE
Locations und Contact People können in Organisationen nicht direkt entfernt werden

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#776]
Der entsprechende Pfeil ist nicht zu sehen.

![bildschirmfoto 2016-04-20 um 10 53 01](https://cloud.githubusercontent.com/assets/432388/14668790/3e17707e-06e6-11e6-807e-2dae7db056f8.png)

Bug oder Feature

**Comment by KonstantinKo** [comment]
Auf master hotfixed und deployed.

**Comment by KonstantinKo** [comment]
… uuund wieder reverted. Location & ContactPerson müssen einer ORga zugewiesen sein. Das auf null setzen schmeißt Fehler.
