### ISSUE TITLE
Export für Production anpassen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#778]
Folgender Wunsch für die Backend 2.0 Exportfunktion auf Prodcution:

Wenn ich mich über die neue Anmeldeseite anmelde, dann werde ich danach automatisch ins alte Backend weitergeleitet. Dort sehe ich, tendenziell im Header, einen Link mit dem Namen 'Backend 2.0 (Beta)'. 

Hintergrund ist, dass sich die Researcher in 99%+ der Fälle (noch) nicht für das neue Backend interessieren.

**Comment by NilsVollmer** [comment]
Ich war mal so frei, mich diesem Ticket anzunehmen. Die links sind entsprechend angepasst und nach dem sign_in wird entweder zur 'return_to' url (z.B. Tab über Nach offen gelassen und re-auth benötigt) oder zu '/admin' weitergeleitet.
