### ISSUE TITLE
Arabisch in der mobilen Ansicht nicht sichtbar ohne zu scrollen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#783]
Wenn ich mit dem handy (richtig, nicht simuliert) auf ein konkretes Angebote gehe und dann die Seite in Arabisch anzeigen möchte, sehe ich einen leeren, weißen Bildschirm. Erst wenn ich ganz nach rechts scrolle kommen wieder Inhalte.

**Comment by marcus-herrmann** [comment]
Könntest du mir genauere Infos geben? Konkretes Angebot (oder passiert das bei allen?), Browser, Gerät? Habe mein Android-Testgerät im Büro, kann es aber unter iOS auf verschiedenen Angebotseinzelseiten nicht reproduzieren

**Comment by marcus-herrmann** [comment]
Sehr sehr seltsamer Bug, der mit der Google API zu tun hat (Stichwort: "BESbewy"). Als Hotfix auf Develop
