### ISSUE TITLE
Adresse zurück in die Kontaktpersonen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#784]
Wichtig für 'Brief-Angebote'. Bitte folgende Felder für Kontaktpersonen ergänzen:

- Straße/Postfach (string)
- Postleitzah/Ort (string)

Bitte im Adminberiech folgenden Infotext hinzufügen: "Ausschließlich bei Angeboten mit dem Encounter 'Brief' verwenden."

**Comment by NilsVollmer** [comment]
Zu erledigen wäre dann noch die Anzeige im Frontend.
