### ISSUE TITLE
Auflistung der Angebote in der Orgaansicht anpassen

### ISSUE THREAD

**Issue by JulianJung** [clarat-org/clarat#786]
Die Zusammengehörigkeit von Titel und Stamps sollte wiederhergestellt werden. 

![bildschirmfoto 2016-04-28 um 19 28 31](https://cloud.githubusercontent.com/assets/11425826/14895151/8136c462-0d77-11e6-8c4e-b0d0a2fb71fe.png)

**Comment by Twiek** [comment]
@marcus-herrmann Problema es: Das 'für Jugendliche' und 'Beratung bei Bedrohung... 'stehen recht weit auseinander und es ist nicht völlig klar, dass die zusammengehören. Bitte hier mal einen Vorschlag machen wie das deutlicher wird.

**Comment by marcus-herrmann** [comment]
@Twiek Im Sinne von: Mit den Spaltenbreiten etwas herumspielen (siehe Bild) oder mehr in Richtung "Zuordnungsdreieck" wie auf Offer Show bei den Ansprechpartnern?

<img width="1280" alt="bildschirmfoto 2016-08-11 um 15 08 48" src="https://cloud.githubusercontent.com/assets/505181/17589565/c7e909b4-5fd5-11e6-8b5a-480b3721557a.png">

**Comment by JulianJung** [comment]
Spricht etwas dagegen diese Ansicht an die Angebotsoptik in den Suchergebnissen anzupassen?
Finde den Angebotstitel über der Adresse etwas verwirrend, auch da hier in der anderen Ansicht der Organame steht. Wäre das nicht Einheitlich hilfreicher? Der Titel ist schließlich das wichtigste Element eines Angebots. Das wird finde ich besonders mobil nochmal deutlich:
![image](https://cloud.githubusercontent.com/assets/11425826/17593735/2dfb0688-5fe7-11e6-8833-69c82335daf5.png)

**Comment by Twiek** [comment]
Ja, lass hier das Design von den Suchergebnissen kopieren. Die Orgainfo ist dann zwar doppelt, aber was solls (+bald wird statt dem Namen der Orga ohnehin öfter der Name des Standortes angezeigt, dann hat sich das auch zum großen Teil erledigt).

**Comment by marcus-herrmann** [comment]
Achtung @NilsVollmer - Basti hat gerade diesen Featurebranch auf Staging deployed, damit ich hier mit realeren Daten prüfen konnte

**Comment by marcus-herrmann** [comment]
Note to self: Blocker sind hier aktuell das Fehlen halbwegs realistischer Fake-Daten und -Verwandtschaften
