### ISSUE TITLE
Genderfilter im Frontend bezieht sich auf Gender 1st part of Stamp Angaben

### ISSUE THREAD

**Issue by JulianJung** [clarat-org/clarat#788]
Wie besprochen.
Zutreffend für beide Welten: family, refugees.

**Comment by Twiek** [comment]
@JulianJung Ist das nicht schon so? Kannst Du hier mal ein Beispiel posten (gerne auch Staging) auf dem das anders ist?

**Comment by JulianJung** [comment]
Kann sein das es mittlerweile so ist. War damals wohl nicht der Fall. Hab auf Anhieb jetzt auch nichts Gegenteiliges auf Staging finden können.
Kann meines Achtens also zu.

**Comment by MichiBecker** [comment]
hallo halli,

heute wieder aufgefallen: Kann noch nicht zu.

Der Filter im Frontende "Geschlecht" bezieht sich immer noch auf das Feld "Excluisve gender".

Dieses Feld gibt es im Backend garnicht mehr. öhöm., öhöm,-......

**Comment by Twiek** [comment]
@OmarAlsabbagh Bitte check das mal. Die Filter werden hier definiert: https://github.com/clarat-org/clarat/blob/develop/app/views/offers/index/_filters.json.jbuilder. Gerne auch mit @MichiBecker besprechen um das inhaltlich noch besser zu verstehen.

**Comment by OmarAlsabbagh** [comment]
@Twiek kannst du mir Bitte als Contributor machen damit ich Branches pushen könnte,
dann muss auch Änderung im Algolia gemacht werden, das mache ich gemeinsam mit Nicole ( ich selber habe keine Zugang im Algolia)

**Comment by mokus80** [comment]
1. @MichiBecker hat alle Angebote die exclusive_gender gesetzt hatten, aber gender_first_part_of_stamp nicht, durchschaut und bei Bedarf upgedatet.

2. Nach Merge des Pull Request auf Staging: 'bundle update clarat_base' auf Clarat UND Claradmin.

3. Alle Angebote mit mit gender_first_part_of_stamp (ca. 3000) müssen in Algolia neu indiziert werden. Dazu Deploy TO DO (kann aber auch schon vorher ausgeführt werden: 

Offer.where.not(gender_first_part_of_stamp: nil).each do |offer|
  offer.index!
end

4. Translations für boys_only und girls_only können gelöscht werden.
