### ISSUE TITLE
Titel der Expired-Angebote in Asana anpassen

### ISSUE THREAD

**Issue by JulianJung** [clarat-org/clarat#789]
Das QM Team wünscht eine andere Titelgenese der durch ablaufende Angebote  automatisch erzeugten Asana Tasks.

"Name der Orga(s)" - "Expired-at Datum" - "clarat-Welt"- "Angebotstitel"

wenn möglich bei der Welt ggf. einfach nur: "ref" für refugees oder "fam" für family

**Comment by Twiek** [comment]
Nach Deploy mit QM/Screening checken ob es klappt.
