### ISSUE TITLE
Favicon entwerfen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#79]
If not your cup of tea, let me know.

Related: https://github.com/clarat-org/clarat/issues/80

**Comment by marcus-herrmann** [comment]
Wir könnten für Favicon und weitere, verwandte Zwecke (Webpage Icons in all ihren Varianten) den Kartenmarker verwenden (Sorry, Prio-Herabstufung zu spät gesehen, Idee schon eine Woche alt).

![favico-vorschlag](https://cloud.githubusercontent.com/assets/505181/5891515/017702fa-a49b-11e4-9270-79f68af3db3f.jpg)

**Comment by Twiek** [comment]
Gefällt mir. Sollte ja mit hoffentlich minimalem Aufwand verbunden sein und bis auf weiteres ausreichen.
