### ISSUE TITLE
Hinweis ins Impressum

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#792]
Im Impressum soll ein Popup mit dem folgenden Text erscheinen: "clarat ist eine Suchmaschine. clarat sagt dir, wo du Hilfe bekommst. Zum Beispiel, wo du einen Experten findest, der dir bei deinem Problem hilft. clarat selber kann dir nur beim Suchen helfen.".

Optisch soll es sich an dem orientieren was angezeigt wird, wenn man an einem Standort sucht in dem wir noch keine Angebote hinterlegt haben.

<img width="744" alt="bildschirmfoto 2016-05-27 um 13 15 18" src="https://cloud.githubusercontent.com/assets/432388/15606527/28e80698-240d-11e6-8005-0e87aec364f6.png">

**Comment by Twiek** [comment]
Gerne mit 3-Monats-Cookie versehen. Wer warum auch immer öfter einen Blick in unser Impressum werfen will muss das nicht jedes mal sehen.

**Comment by NilsVollmer** [comment]
Update: Nach Rücksprache mit den entsprechenden Experten-Teams haben wir uns doch gegen die Popup-Lösung entschieden!

Stattdessen soll über dem Impressum (also direkt über der Überschrift 'Impressum') eine Info-Box mit dem entsprechenden Text angezeigt werden, die immer da ist und auch nicht weggeklickt werden kann. 

@marcus-herrmann am besten quick-and-dirty ein paar Möglichkeiten entwerfen - gerne pragmatisch mit wenig Aufwand, sodass das heute noch deployed werden kann.

**Comment by marcus-herrmann** [comment]
Like this? Bei Gefallen liegt es auf https://github.com/clarat-org/clarat/tree/feature/792-imprint-hint für die weitere Bearbeitung bereit

![screencapture-localhost-3000-refugees-impressum-1464860311274](https://cloud.githubusercontent.com/assets/505181/15740819/f9c7f63a-28b6-11e6-8b30-1ae3538586b9.png)
![screencapture-localhost-3000-refugees-impressum-1464860294305](https://cloud.githubusercontent.com/assets/505181/15740818/f9c6bf90-28b6-11e6-835d-ad4d9a09e2ec.png)

**Comment by NilsVollmer** [comment]
Yep, das nehmen wir so, danke.
