### ISSUE TITLE
Crawling-Fehler (Google) beheben

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#797]
Siehe E-Mail. Las dazu am besten aber auch noch mal sprechen.

**Comment by NilsVollmer** [comment]
Wie besprochen: die wenigen Fehler, die noch im Code waren, sollten auf develop behoben sein und was die alten Informationen von Google angeht, können wir nur wohl abwarten, bis der Crawler das hinbekommt.

**Comment by Twiek** [comment]
Es ist besser, aber nicht gut: https://www.google.com/webmasters/tools/crawl-errors?hl=de&siteUrl=http%3A%2F%2Fwww.clarat.org%2F&pli=1#t2=1. Versuche Eleonore mit einzubeziehen.

**Comment by NilsVollmer** [comment]
Umbenannt um Verwechslung mit unserem Crawler zu vermeiden.

**Comment by Twiek** [comment]
Bitte noch mal checken was es mit den aktuellen Fehlern auf sich hat: https://www.google.com/webmasters/tools/crawl-errors?hl=de&siteUrl=https://www.clarat.org/.

**Comment by NilsVollmer** [comment]
Ohje.. anscheinend wurde die fr-offer-route einfach so geändert und keiner hat es mitbekommen. Deshalb mal high prio

**Comment by NilsVollmer** [comment]
Update: habe 1-2 Fehler in den übersetzen Routen gefunden und als Hotfix deployed. Alle aktuell gefundenen 404-Fehler bei Google habe ich als erledigt markiert.

Pending: jetzt heißt es abwarten und später checken, ob Google damit klarkommt.

**Comment by NilsVollmer** [comment]
Da es ein neues Issue gibt mache ich das hier mal zu.
