### ISSUE TITLE
Webpage Icon erstellen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#80]
Related: https://github.com/clarat-org/clarat/issues/79

Siehe auch:
https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html

Sollte dann vermutlich auch für Android funktionieren (obwohl glaube ich offiziell eine andere Syntax verwendet wird), aber sicherheitshalber noch mal testen.

**Comment by marcus-herrmann** [comment]
Webpage Icons auf "konzeptioneller Basis" des Favicons (= Map marker)  erstellt und mit c1415a3d7ca02ff675bdcdd135d70a7faeb2daca im Master
