### ISSUE TITLE
Telefonnummer-Spacing

### ISSUE THREAD

**Issue by KonstantinKo** [clarat-org/clarat#800]
Telefonnummern gehen im arabischen Layout kaputt. Sie schreiben Zahlen genauso wie wir, aber in der Anzeige von Telefonnummern werden die einzelnen Blöcke in verkehrter Reihenfolge angezeigt (030 123 45 67 => 67 45 123 030). Das liegt daran, weil wir Leerzeichen zum Spacing verwenden.

Bitte darum die Zahlenblöcke in Telefonnummern mittels `span`s ohne Leerzeichen voneinander trennen und diese dann per CSS lesbarer anzeigen.

**Comment by marcus-herrmann** [comment]
Als Hotfix auf develop. Für die Nachwelt:

```
    unicode-bidi: embed;
```

**Comment by KonstantinKo** [comment]
Mir wäre ein spacing per `span` auch aus dem Grund lieber gewesen, dass man damit Telefonnummern beim rauskopieren nicht noch manuell ihrer Leerzeichen berauben muss. Das hat mich seit längerem schon gestört.
Muss nicht unbedingt jetzt sein, aber lass es uns im Hinterkopf behalten, dass das eh mal gemacht werden muss.
