### ISSUE TITLE
Angebotstranslations nur anfordern, wenn sich die entsprechenden Felder ändern

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#803]
Nur dann von Google Übersetzungen anfordern, wenn etwas im entsprechenden Feld (title, description) geändert wurde. Im Idealfall dann auch nur für das Feld, in dem die Änderung stattgefunden hat.

**Comment by NilsVollmer** [comment]
Ist relativ tricky, genau das Verhalten zu erzeugen, dass wir haben wollen.. Da der Observer after_save durchläuft bringt die _changed? Methode nichts und wenn der callback before_save durchlaufen soll, muss man einige andere Dinge verhindern (z.B. Anfordern von translations beim löschen)

Des Weiteren muss man aufpassen, dass die Übersetzungen zwar nur für die geänderten Felder angefordert werden aber trotzdem für alle Felder (unabhängig von Änderungen darin) wenn der state sich ändert (einzelne Änderung, die dann aber alle Übersetzungen triggern muss).

Ich commite einfach mal den aktuellen (nicht-funktionierenden) Stand.

**Comment by NilsVollmer** [comment]
Den ersten Commit ignorieren - ging aus Versehen direkt auf master und ist schon wieder reverted.

Der zweite ist der feature-branch.

**Comment by KonstantinKo** [comment]
Wegen after_save changes:
Idee 1: Ich glaube eventuell funktionieren die dirty `_changed?` helper in `after_update`. `after_create` muss ja sowieso immer generiert werden.
Idee 2: Auf offers benutzen wir doch papertrail. Kann man da eventuell heraus bekommen, ob in der letzten Änderung relevante Felder verändert wurden?

**Comment by NilsVollmer** [comment]
Okay dann schaue ich mir after_update nochmal an. 

Die Idee mit den Versionen hatte ich auch schon.. sollte klappen, wäre dann aber wohl eine string-suche, die man dann auch in anderen Feldern triggern könnte. Aber solange die einzige Konsequenz eine angeforderte Übersetzung von Google ist, sehe ich da kein Problem.

**Comment by KonstantinKo** [comment]
PR auf clarat_base.

- Nur für offer umgesetzt, nicht für orga oder andere
- Achtung: Neuer reinitialize state change für doze. Dieser braucht noch tests und Übersetzungen!
- Lustige factory-Änderungen. Ich hoffe der randomly failing test tritt nicht nochmal auf.
