### ISSUE TITLE
"Zeige Lokale Angebote"-Button legt sich über Text

### ISSUE THREAD

**Issue by JulianJung** [clarat-org/clarat#809]
![image](https://cloud.githubusercontent.com/assets/11425826/15548144/4e7c4890-22a7-11e6-9fed-e741a1b621f5.png)

**Comment by NilsVollmer** [comment]
Ähnliches hatten wir in anderen Sprachen (Russisch?) ja auch schon.. der Fix sollte entsprechend straight-forward sein.

**Comment by marcus-herrmann** [comment]
Als Hotfix auf Develop

**Comment by NilsVollmer** [comment]
Leider auf develop auch nach cache:clear & neustart immer noch der Fall:

![image](https://cloud.githubusercontent.com/assets/1733220/15744131/76d6b108-28ca-11e6-80e4-83c6662ee0ae.png)

**Comment by marcus-herrmann** [comment]
<img width="729" alt="bildschirmfoto 2016-06-02 um 14 03 56" src="https://cloud.githubusercontent.com/assets/505181/15744205/e4a9029e-28ca-11e6-9707-26141cd5a3a6.png">

Ebenfalls aktueller Develop und cache:clear. Habe deinen Browsercache im Verdacht. In anderem Browser/privatem Tab?

**Comment by marcus-herrmann** [comment]
Nevermind, Missverständnis wegen Breakpoint! Update folgt

**Comment by marcus-herrmann** [comment]
Update: b12af8b7741383e307a9a2d06ae49e2be854bc93
