### ISSUE TITLE
Split-Base vorbereiten

### ISSUE THREAD

**Issue by JulianJung** [clarat-org/clarat#810]
Wir bräuchten bis Dienstag (2.06) eine auf Staging funktionierende Split-Base um sie einigen Personen zum Testen vorzustellen.
Das bisherige Base-Offer müsste dafür um folgende Punkte ergänzt werden:

- [x] Titel [Anbieterwording (kann unter Umständen recht lang werden)]
- [x] Clarat Zusatz/Identifier (auszufüllen bei überschneidenen Anbieterwordings)
- [x] Kommentarfeld => Notes gehen natürlich auch
- [x] Man muss der Split-Base eine Orga zugewiesen werden (Pflichtfeld)
- [x] Man muss der Split-Base eine Solution Category zugewiesen werden (Pflichtfeld)
- [x] Beim Auswählen der Split-Base in den Angeboten sollte folgendes zu sehen sein → Organame → L-Kategorie → Titel (diese Kombination ist der Displayname, dieser muss unique sein)
- [x] Es brauch eine neue Version (aufgrund der Validierungen). Nummer 8, Codename: 'Splitbase'

- [ ] Die Split-Base braucht ein Boolean → Angebote nur für eine bestimmte  Zielgruppe =>  Muss noch mit den Patinnen besprochen werden

**Comment by KonstantinKo** [comment]
Deploy TODO: Version anlegen

**Comment by NilsVollmer** [comment]
Update: 'Silent' Version ist aufgespielt. Unsichtbar für die Researcher im Backend und solange wir die neue Logik-Version nicht anlegen, wird ja auch nichts validiert.

Da es bei der praktischen Nutzung der SpitBase anscheinend noch Probleme gibt, und wir diese 'Unsicherheitsangebote' gerne nachträglich herausfiltern wollen, haben wir uns auf folgendes geeinigt:
- es wird zwei neue Versionen (7 für alle neuen Regeln abzüglich der SplitBase, name TBD und 8 für Split Base ) geben
- der Regelfall sollte natürlich alles sein: der Researcher aktualisiert alles und Version 8 ist aktiv
- Ausnahme sollte sein: Researcher ist sich bzgl. SplitBase unsicher => er aktualisiert alles andere und setzt die Version aktiv auf Version 7
