### ISSUE TITLE
Seeds fixen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#814]
Scheint Probleme mit Gengo zu geben (die wollen uns wohl nicht an ihre Sandbox lassen?).

**Comment by NilsVollmer** [comment]
Bei mir klappt es jetzt wieder - @Twiek gerne noch ausprobieren.

**Comment by Twiek** [comment]
Bei mir klappts schon wieder nicht. Bin bei claradmin auf develop und egal ob ich es mit rake db:drop oder rake db:hardreset versuche kommt beim Versuch zu seeden folgender Fehler:

![bildschirmfoto 2016-06-24 um 17 36 49](https://cloud.githubusercontent.com/assets/432388/16342416/4d382736-3a32-11e6-9b46-45ab30756b73.png)

**Comment by KonstantinKo** [comment]
Hatte sich erledigt oder?
