### ISSUE TITLE
Mehrsprachigkeit - Manuelle Übersetzungen von Angeboten

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#815]
Es soll 1-2 Monate getestet werden, ob es Sinn macht Title und Description von Angeboten manuell übersetzen zu lassen. Vorerst soll sich der Test auf Arabisch und Russisch beschränken. Es ergeben sich die folgenden Anforderungen:

- [x] Titel und Description können für die russische und arabische Sprache direkt über das Backend nachträglich manuell angepasst werden.
- [x] Es muss im Backend neben/unter Title und Description ersichtlich sein, wer für die letzte Änderung verantwortlich war (Mensch oder Maschine).
- [x] Man kann Angebote danach sortieren oder filtern ob die russischen oder arabischen Übersetzungen von Menschen bzw. Maschinen übersetzt wurden. Tendenziell über die Exportfunktion.
- [x] Descriptions und Titel die einmal von einem Menschen angefasst wurden, werden nie wieder von Google überschrieben, auch wenn z.B. die deutsche Description manuell geändert wird. In einem solchen Fall kriegt das Angebot aber einen 'Flag' (z.B. 'Russische Übersetzung möglicherweise veraltet') nach der auch sortiert oder gefiltert werden kann (s.o.).

**Comment by KonstantinKo** [comment]
Ist inklusive Backend 2.0-Lösung reviewfertig. Die erste schöne custom 2.0 Lösung! Endlich haben wir mal ein Beispiel von einer funktion die so mit rails_admin nicht möglich gewesen wäre.

**Comment by NilsVollmer** [comment]
Can't wait to review!

**Comment by Twiek** [comment]
Sieht schick aus. 2 Extrawünsche hätte ich aber noch:
- [ ] 'Neuet Teil' funktioniert nicht (vermutlich absichtlich). In dem Fall diesen Button/Link nicht anzeigen
- [ ] Zumindest für die Testphase wäre es wünschenswert, wenn ausschließlich die ar und ru Translations angezeigt würden

**Comment by KonstantinKo** [comment]
Done

**Comment by NilsVollmer** [comment]
Was mir noch aufgefallen ist: beim deutschen Text kann man mit Markdown arbeiten und bei den Translations arbeitet man geparstem HTML-Code. Und rechts daneben als Source steht aber der ursprüngliche Markdown-Code. Das könnte zu Verwirrungen führen bzw. man müsste den Leuten, die damit arbeiten, mindestens erklären, dass sie so den HTML-Code beibehalten müssen.

Alternativ könnte man für menschlichen Translations den Markdown-Renderer aktivieren - das wäre dann einheitlich und weniger verwirrend. Die Tatsache, dass der ursprüngliche Text von GT dann trotzdem noch voller HTML ist, können wir nicht wirklich ändern.

**Comment by NilsVollmer** [comment]
Eine Sache noch: kann es sein, dass der zweite Teil des vierten Punktes (Flag, dass sich bei einer Menschenhand-Übersetzung der Source-Text geändert hat) nicht da ist, oder bin ich gerade einfach nur blind?

Ansonsten schaut es gut aus! :)

**Comment by KonstantinKo** [comment]
> bei der deutschen description kann man mit Markdown arbeiten und bei den Translations arbeitet man geparstem HTML-Code
Bei den Übersetzungen zumindest kommen wir nicht von HTML weg (Man bedenke: Auch Deutsch ist eine Übersetzung, halt von Markdown in HTML). Was man sich aber überlegen könnte ist auf der rechten Seite die deutscheÜbersetzung anzuzeigen und nicht den unübersetzten Text. Dann ist die Frage, ob man HTML escapen sollte.

> kann es sein, dass der zweite Teil des vierten Punktes (Flag, dass sich bei einer Menschenhand-Übersetzung der Source-Text geändert hat) nicht da ist
Das ist im PR auf clarat_base. Der "Flag" ist einfach, dass die source GoogleTranslate ist oder nicht (`#automated?`)

**Comment by NilsVollmer** [comment]
Aber das gibt doch nur an, dass die Übersetzung von Menschenhand ist. Den zweite Teil von Punkt vier habe ich so verstanden: bei einer Menschenhand-Übersetzung bei der nachträglich die source geändert wird, wird diese Menschenhand-Übersetzung als 'veraltet' oder 'to be reviewed' geflagged. 

Denn es ist ja schon richtig, dass wir diesen Fall bei der Menschenhand-Übersetzung nicht abdecken: GT wird bei jeder Änderung automatisch aktualisiert aber die Menschenhand-Übersetzung bleibt wie sie ist und deshalb sollten die Übersetzungen, bei denen dann nachträglich die Source geändert wurde, sichtbar sein (sortier- und/oder filterbar für den User). 

Das wäre ja über einen Vergleich der updated_at Felder der de-translation mit denen der manually-translated-translations möglich.

**Comment by Twiek** [comment]
Bezüglich HTML wäre ich auch dafür dies dann überall anzuzeigen, also auch bei der deutschen Übersetzung. Denke das wäre dann auch für die Researcher nachvollziehbarer.

**Comment by Twiek** [comment]
Bezüglich der Source wäre die Anforderung in der Tat nach OfferTranslation zu sortieren die möglicherweise veraltet sind. Eventuell braucht es hier dann noch eine weitere source ('researcher (old)')?

**Comment by NilsVollmer** [comment]
Ist definitiv bereits deployed.

**Comment by NilsVollmer** [comment]
@Twiek Ist das Ticket Kunst oder kann das weg?
