### ISSUE TITLE
Location-Name-Feld soll Anzeige des Organamen in den Suchergebnissen überschreiben

### ISSUE THREAD

**Issue by JulianJung** [clarat-org/clarat#816]
...wenn ausgefüllt.
Zusätzlich soll der Location-Name auch mit in die Suche aufgenommen werden.

Erst umsetzen wenn die Aktualisierungswochen abgeschlossen sind. Ich gebe dann hier bescheid.

**Comment by Twiek** [comment]
Überschneidung mit #729 ? Kann eines davon gelöscht werden?

**Comment by JulianJung** [comment]
Ja das hier kann zu.
