### ISSUE TITLE
Target Audience family_acquaintances umbenennen

### ISSUE THREAD

**Issue by KonstantinKo** [clarat-org/clarat#819]
(Da Julian gerade krank und Basti im Urlaub ist, ging die Anfrage ausnahmsweise über mich Auftraggeberin: Elisa)
Target Audience "für Bekannte und Verwandte" soll umbenannt werden in "für Angehörige"

family_acquaintances dementsprechend wohl family_relatives

Alle bestehenden Daten, die family_acquaintances zugehören sollen somit auch family_relatives weiterhin zugehören.

"Gern bis Montag"

**Comment by NilsVollmer** [comment]
Aus Zeitgründen für morgen dann nur 'name' umbenennen und den Anzeigenamen im Frontend.

Deploy TODO:
```console
TargetAudienceFilter.find_by(identifier: 'family_acquaintances').update_columns(name: 'Angehörige')
```

**Comment by Twiek** [comment]
@NilsVollmer Wie schaut es hier aus? Können/müssen wir irgendwo aktiv werden?

**Comment by NilsVollmer** [comment]
@Twiek Soweit ich den AsanaTask richtig im Kopf habe, warten wir da noch auf eine fehlende Übersetzung des neuen wordings. Erst wenn die da ist kann ich final aktiv werden.

Sind sie aktiv? Ja, final aktiv!

**Comment by NilsVollmer** [comment]
Wird zusammen mit #941 deployed werden.

Deploy TODO:
```ruby
TargetAudienceFilter.find_by(name: 'für Angehörige').update_columns identifier: 'family_relatives'
```

**Comment by NilsVollmer** [comment]
Zusammen mit #941 umgesetzt.
