### ISSUE TITLE
Ortssuche optimieren

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#82]
Im Feld für die Ortssuche gibt es folgende Herausforderungen:

1. Der Text, der im Vorfeld im Kästchen steht (z.B. 'Mein Standort') verschwindet nicht, wenn man in das Feld klickt und anfängt zu tippen, sondern muss manuell gelöscht werden (z.B. liest man wenn man in das Feld klickt und dann auf den Buchstaben 'n' klickt folgendes 'nMein Standort'. Mir wäre nur 'n' deutlich lieber.

2. Das Suchfeld und die Autovervollständigungsbox die aufgeht sobald man tippt sind nicht ganz gleich groß, sollten sie aber.

![bildschirmfoto 2014-12-24 um 17 12 14](https://cloud.githubusercontent.com/assets/432388/5549708/1ee40a28-8b90-11e4-9665-8f6a3e157610.png)

In beiden Fällen darauf achten Google nicht in die Quere zu kommen (im Zweifelsfall Rücksprache halten).

**Comment by marcus-herrmann** [comment]
Zweiter Punkt implementiert/gefixt mit 6e3f9398800de7a311adeade6b2487cf27036cd7

**Comment by marcus-herrmann** [comment]
Erster Punkt: Ist das durch den Einsatz der Geolocation-Auflösung seitdem noch relevant? Anstelle von "Mein Standort" bekomme ich aktuell "Berlin". Für den Fall dass ich in Berlin genauer suchen will, z.B. Prenzlauer Berg ist es nicht unpraktisch, dass "Berlin" schon vorausgefüllt ist (ich weiß, eine Suche nach "Prenzlauer Berg" allein genügt). Oder ist ein Feature für eine automatische Löschung des automatischen Ergebnisses noch wichtig, weil eventuell die Lokalisierung zu grob (bin z.B. in Potsdam, bekomme aber "Berlin", das ich dann löschen müsste)?

**Comment by Twiek** [comment]
Hat sich erledigt, funktioniert jetzt alles wie es soll, d.h. selbst wenn man den Platzhalter sieht verschwindet er sobald man anfängt zu tippen
