### ISSUE TITLE
'Mehr im Netz' - Farbe ändern

### ISSUE THREAD

**Issue by NilsVollmer** [clarat-org/clarat#821]
Die sehr dezente, graue Farbe bitte in ein auffälligeres grün geändert werden. 

Fraglich ist eigentlich nur noch, ob man das grün von der Headlines der right-side Boxen oder ein Anderes nimmt. Können wir uns am nächsten Donnerstag am besten live anschauen.

**Comment by marcus-herrmann** [comment]
Das etalblierte Grün (das zum Beispiel auch als Hintergrundfarbe für die Überschrift von "In welcher Sprache hilft man dir?" zum Einsatz kommt)?

![bildschirmfoto 2016-06-03 um 14 39 43](https://cloud.githubusercontent.com/assets/505181/15778831/06cd8c2c-2999-11e6-887d-13cfa7372f85.png)

**Comment by marcus-herrmann** [comment]
![screencapture-localhost-3000-refugees-angebote-accusamus-autem-ratione-1465460347295](https://cloud.githubusercontent.com/assets/505181/15923841/6d0452f6-2e2f-11e6-843a-cf77ece17a6f.png)
![screencapture-localhost-3000-refugees-angebote-accusamus-autem-ratione-1465460384401](https://cloud.githubusercontent.com/assets/505181/15923842/6d2da7b4-2e2f-11e6-8efc-c6b8dba65971.png)
![screencapture-localhost-3000-refugees-angebote-accusamus-autem-ratione-1465460615196](https://cloud.githubusercontent.com/assets/505181/15923843/6d2ded78-2e2f-11e6-9079-3ebc5c5c4737.png)

**Comment by Twiek** [comment]
Ok, habe es jetzt mal ganz dreist selber umgesetzt...
