### ISSUE TITLE
Eine Suche in Köln, zeigt auch Angebote aus Düsseldorf

### ISSUE THREAD

**Issue by JulianJung** [clarat-org/clarat#824]
...trotz über 25km Radius.

![image](https://cloud.githubusercontent.com/assets/11425826/15865113/cbd58ebe-2cd9-11e6-8d16-b0c647425807.png)

**Comment by NilsVollmer** [comment]
Hmm anscheinend suchen wir mit einem 50km Radius.. Nach Absprache auf 25km runtergeschraubt.
