### ISSUE TITLE
Firefox-Design-Bug

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#83]
Siehe Screenshot (Mac OSX 10.9.5):

![bildschirmfoto 2014-12-24 um 17 13 56](https://cloud.githubusercontent.com/assets/432388/5549720/83294516-8b90-11e4-8a0f-5e0fab199cb5.png)

**Comment by Twiek** [comment]
Inzwischen auch unter Windows gesehen (auch FF).

**Comment by Twiek** [comment]
Nun auch in Chrome beobachtet (Mac).

![bildschirmfoto 2015-01-23 um 11 01 21](https://cloud.githubusercontent.com/assets/432388/5872744/3922aa04-a2ef-11e4-87ad-098455de2cbb.png)

**Comment by marcus-herrmann** [comment]
Aktives Twitter Typeahead macht das Ensemble aus Inputs genau 2px zu breit (darum auch kleiner Sprung in falschen Zustand), browserübergreifend per max-width zu lösen, folgt am Montag als allererstes.
