### ISSUE TITLE
Split-Base - Erweiterung der Orgaauswahl

### ISSUE THREAD

**Issue by JulianJung** [clarat-org/clarat#832]
Es muss möglich sein einer Split-Base mehr als eine Orga zuzuweisen (für Kooperationsangebote).

**Comment by NilsVollmer** [comment]
Dann zusammen mit der Validierung 'Jedes zugeordnete Angebot muss die gleichen Orgas wie die SplitBase haben?'

**Comment by JulianJung** [comment]
Ja, stimmt!

**Comment by NilsVollmer** [comment]
Die Herausforderung dabei ist die uniqueness-validation: aktuell läuft die einfach über die ID der Orga, die ja direkt ein Feld des Models ist. Sobald es mehrere Orgas sein sollen, muss die Validierung über die Verknüpfungstabelle und die (sortieren?) IDs der Orgas laufen.

**Comment by KonstantinKo** [comment]
Müssen wir die Organisation dann überhaupt noch auf dem Angebot speichern? Wenn Angebote immer die selbe Organisation wie deren SplitBase haben soll dann reicht es doch wenn man sie da auswählt und wir die Beziehung über SplitBase als Verbindungsmodell herstellen, oder?

Dann spart man sich die Validierung und eine potenzielle Fehlerquelle. Außerdem ein weiterer Schritt Richtung SplitBase 2.0

**Comment by NilsVollmer** [comment]
Ja, ich bin stark dafür. Das sollte den Researchern auch gefallen weil die sich schon wundern, warum sie die Orga und die solution_category doppelt auswählen müssen. Bei Letzterer gibt es aber anscheinend ein paar Ausnahmen die das bedingen. 

@JulianJung was meinst du? Coole Idee oder gibt es bei den Orgas auch wieder Ausnahmen?

Interessant ist dann aber natürlich wieder die Übergangsphase: aktuell haben die meisten Angebote ja noch keine SplitBase also können wir die Verknüpfung Orga <-> Angebot noch nicht entfernen und müssen eine Zeit lang parallel fahren. Geht das denn? Also sowohl has_many :organizations, through: :organization_offers als auch has_many :organizations, through: :split_base ?

**Comment by KonstantinKo** [comment]
Das mit den solution_category Unstimmigkeiten haben wir aber glaube ich auch aufgeschrieben und wird vom Spliteam bei den Neuüberlegungen mitgedacht. Hoffe ich.

> Geht das denn? Also sowohl has_many :organizations, through: :organization_offers als auch has_many :organizations, through: :split_base ?

Nein das geht leider nicht und du hast rest, das ist in der Tat ein Problem… Wahrscheinlich müssen wir dann eine zweite Verbindung wie `has_many :organization_connections, through: :split_base` herstellen und die benutzen.

**Comment by JulianJung** [comment]
Die solution_category Unstimmigkeiten denken wir bei der Split-Base Weiterentwicklung mit. Darüber die Orgaauswahl komplett auf die Split-Base zu verschieben haben wir schon gesprochen, klang für uns absolut sinnvoll. Müsste man dann allerdings noch im Backend-PB etc. absegnen oder war das generell für die Split-Base 2.0 gedacht?

**Comment by KonstantinKo** [comment]
Man kann den Übergang graduell machen, aber du hast recht. Erstmal absegnen lassen.

**Comment by Twiek** [comment]
Und die Abteilungen nicht vergessen... ;-)

**Comment by Twiek** [comment]
In #945 reingezogen.
