### ISSUE TITLE
SplitBase: ID in den display_name damit man danach suchen kann

### ISSUE THREAD

**Issue by NilsVollmer** [clarat-org/clarat#833]
Funktioniert aktuell nur für eigene (title, addition) und nicht für verknüpfte Felder (orga.name & solution_category.name).

**Comment by NilsVollmer** [comment]
Interessanterweise funktioniert der Fix lokal aber auf staging nicht..

Ich habe nochmal in unsere Daten geschaut und bei Locations hatten wir anscheinend schon einmal diesen Fall, dass es komplexer display_name generiert wurde, der komplett durchsuchbar sein sollte. Da speichern wir diesen Namen dann mit dezenter Redundanz nochmal zusätzlich als Field und somit ist er natürlich durchsuchbar.

**Comment by Twiek** [comment]
@JulianJung Wie wichtig schätzt Du dieses Feature ein. Lohnt es sich hier ein bisschen unsauberen Code zu produzieren?

**Comment by JulianJung** [comment]
Mit steigender Split-Base Zahl und somit steigender Wahrscheinlichkeit auf gleiche Split-Base Titles, wird es immer wichtiger, dass man auch nach Organamen mit durchsuchen kann.  Wenn man 15-20 Split-Base Titles namens "Beratung" findet und sich jedes mal die passende Orga raussuchen muss wird es doch sehr umständlich. Kann sein das da noch 1-2-3 Monate ruhe ist, kann aber auch sein das solche Fälle relativ bald auftreten.

**Comment by NilsVollmer** [comment]
Da es früher oder später zum Problem werden wird, können wir es dann auch direkt jetzt so machen, finde ich. Wenn man 'Beratung' eingibt kriegt man jetzt schon einen ziemlich unübersichtlichen Haufen. Des Weiteren sieht es so aus, als würde die DropDown-Box auch nicht beliebig hoch werden - es könnte also irgendwann dazu kommen, dass man seine SplitBase nicht findet (weil sie nicht mehr gelistet wird) obwohl man nach dem kompletten Titel gesucht hat.

Deshalb in Absprache mit @JulianJung gerade darauf geeinigt, dass wir stattdessen die ID als erstes bei dem display_name voranstellen. So kann man die SplitBases auch in Zukunft definitiv eindeutig finden und falls das von der Usability als lästig empfunden wird, können wir später immer noch den kompletten display_name redundant speichern.
