### ISSUE TITLE
Zielgruppenstamp in den Suchindex aufnehmen 

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#834]
Wenn wir es schon so prominent in den Suchergebnissen anzeigen, dann sollte es auch in der Freitextsuche berücksichtigt werden.

**Comment by NilsVollmer** [comment]
Deploy TODO **nach cache:clear**!!:

```console
Offer.clear_index!
Offer.reindex
```

**Comment by NilsVollmer** [comment]
PR auf clarat_base erstellt. Änderungen auf clarat sind implementiert und warten nur auf den _base merge.

**Comment by NilsVollmer** [comment]
Im Newsfeed kommuniziert
