### ISSUE TITLE
Bei Sprachwechsel springt der Suchstandort automatisch auf Berlin

### ISSUE THREAD

**Issue by JulianJung** [clarat-org/clarat#835]
Wenn ich Angebote in Köln, Düsseldorf oder sonstwo ≠ Berlin. suche, dann die Sprache wechsele, springt der Suchstandort auf Berlin, angezeigt wird aber immernoch der vorher eingegebene Suchstandort. Gleiches passiert auch bei einem Weltenwechsel.

![image](https://cloud.githubusercontent.com/assets/11425826/16078320/826ec0e4-32fe-11e6-818c-389f66474d18.png)

**Comment by marcus-herrmann** [comment]
Mit @NilsVollmer besprochen braucht es einen verlässlichen, am besten backend-befeuerten Standardwert, also eine Lokalisierung via IP, siehe #825

**Comment by NilsVollmer** [comment]
Das geht auch ohne Location, denke ich. Das gewünscht Verhalten ist ja nur, dass der vorher eingegebene Ort korrekt 'mitgenommen' wird. Es soll also auch bei Welt und/oder Sprachenwechsel an diesem Ort gesucht werden.

**Comment by NilsVollmer** [comment]
Nach kurzer Rücksprache mit Konstantin: da das was wir behalten wollen (z.B. Suchort Düsseldorf) ja noch in der SearchForm steht, wäre die Aufgabe, es von dort wieder in die URL (und damit in die Suche) zu kriegen. 

Da Frontend schiebe ich es mal Marcus zu - bei Unklarheit gerne nachfragen.

**Comment by NilsVollmer** [comment]
Fix auf master umgesetzt und deployed.
