### ISSUE TITLE
Gedanken zur neuen Startseiten- und Suchergebisseitenstrategie

### ISSUE THREAD

**Issue by marcus-herrmann** [clarat-org/clarat#836]
- Vorschaltseite mit Tunnelfunktion
- Bereichsstartseiten
- Illustrationen zurückfahren
- Welten-Navi zurückfahren

**Comment by marcus-herrmann** [comment]
Variante "Evolution" (Desktop, Maximalausprägung)

![neue_startseite_evolution](https://cloud.githubusercontent.com/assets/505181/16121984/a6ddba88-33e5-11e6-80f7-c961e4569fbb.png)

**Comment by marcus-herrmann** [comment]
Variante "Evolution II" (Desktop, "Revolution" passt ja nicht wirklich)

![evoevo](https://cloud.githubusercontent.com/assets/505181/16122885/3307f714-33e9-11e6-8e9a-c10e2707645a.png)

**Comment by marcus-herrmann** [comment]
Jetzt, wo alles kompakter ist, fällt die Farbkollision Sprach-Leiste-Blau und Refugee-Welt-Blau noch mal deutlich auf.

**Comment by marcus-herrmann** [comment]
"Evolution I", weitere Ausprägungen/skizzenhaft:
![tablet-ish](https://cloud.githubusercontent.com/assets/505181/16301872/3a8319ec-3948-11e6-9ef9-7d40b8ce5f12.png)

![smartphone](https://cloud.githubusercontent.com/assets/505181/16301883/502779c8-3948-11e6-9874-b77325fc0341.png)

**Comment by marcus-herrmann** [comment]
Hier habt ihr vermutlich nächste Woche Neuigkeiten für mich?

**Comment by marcus-herrmann** [comment]
Notes:

* Start: Claim raus, nur Pitch
* Start: Algolia und Zahnrad raus
* Start: Erwe. Suchergebnisse

* Offer index: Änderung, erst Breadcrumb, dann Virtual-Lokal-Switch
* Breadcrumb: Overflow via Mehrzeilig vs. Overflow via Ellipsis

**Comment by marcus-herrmann** [comment]
Startseite:

![desktop v3-3 refugees 1440](https://cloud.githubusercontent.com/assets/505181/17778045/084f1cae-6563-11e6-9756-25bb334c7c0d.png)

**Comment by marcus-herrmann** [comment]
Offer index mit Text-Overflow Ellipsis (also "…")

![desktop 1440 v1-1-2 familiy copy](https://cloud.githubusercontent.com/assets/505181/17780261/0d50f7f6-656b-11e6-8da3-4355b19691d8.png)

**Comment by Twiek** [comment]
Bitte Umsetzung gemäß https://cloud.githubusercontent.com/assets/505181/17780261/0d50f7f6-656b-11e6-8da3-4355b19691d8.png beginnen. Am lebenden Herzen wird es dann finale Entscheidung bezüglich der Algolia-Platzierung geben und bezüglich des Weltenlinks im Header. Hier erstmal auf der Family-Seite mit 'zu Refugees' experimentieren.

**Comment by marcus-herrmann** [comment]
* Festgefahren bei der Select-Situation
* Remote Offers brauchen genaugenommen keine Sortierung nach "In deiner Nähe"

**Comment by marcus-herrmann** [comment]
Auf Featurebranch zu diesem Ticket

**Comment by marcus-herrmann** [comment]
Update Startseite:

![desktop v3-3 refugees 1440](https://cloud.githubusercontent.com/assets/505181/18712893/bf95e024-8010-11e6-8876-4fdea54ca3b0.png)

**Comment by marcus-herrmann** [comment]
Variationen:

![desktop v3-3 refugees 1440 - 2](https://cloud.githubusercontent.com/assets/505181/18713335/3784572c-8012-11e6-81ef-bdbcd17d3222.png)
![desktop v3-3 refugees 1440 - 1](https://cloud.githubusercontent.com/assets/505181/18713334/37844d04-8012-11e6-8569-6886bc09edf9.png)

**Comment by MichiBecker** [comment]
Hi @marcus-herrmann , es geht nur um den Link oben zu family oder?

Ich würde den Pfeil gerne analog zum "mehr Sprachen" Pfeil haben und den so drehen, dass die Spitze nach links zeigt, nicht wie in den Screens nach rechts. Das drück mMn mehr das zu(rück) aus bzw. das "ich gehe aus der refugees Welt raus"

Außerdem würde ich Schrift und Schriftgröße ebenfalls analog zu einem "normalen" Link machen und nicht die Schrift vom Logo benutzen. Schriftfarbe in Weltfarbe der Welt find ich als Wiedererkennung gut.

anyone any thoughts too?

**Comment by Twiek** [comment]
@marcus-herrmann Bitte den Vorschlag von Michi im Header ausprobieren.
Ansonsten muss das 'Einfach Hilfe finden' doch prominent auftauchen. Hier mal bitte mal basierend auf Deinem letzten Vorschlag ausprobieren, ob man es nicht doch oben rechts im Bild über/statt den Wolken (weiß auf blauem Grund) auftauchen lassen kann. 

Das 'Unterstützungsangebote... auch noch mal mit etwas kleinerer Schrift (analog zu 'Wie funktioniert clarat') ausprobieren und testen ob man es komplett/nur vor dem gelben Hintergrund über den Suchboxen anzeigen lassen kann (bitte testweise/zusätzlich auch einmal nur als Schrift ohne blauen Kasten dahinter).

**Comment by marcus-herrmann** [comment]
![desktop v3-3 refugees 1440 - 3](https://cloud.githubusercontent.com/assets/505181/18813224/1f8963e0-82f3-11e6-8e5c-e7857ca3952d.png)

Stimme zu zu "< zu clarat family".

Die anderen gewünschten Änderungen gehen in eine falsche, grafisch deutlich unruhigere Richtung, finde ich (vorausgesetzt, ich habe das richtig verstanden). Es ist schwierig, Dinge aneinander auszurichten/gemeinsame Fluchten zu finden, um es harmonischer zu machen. 

Verständnisfrage: Warum sollte die weltübergreifende Clarat-Logline (Einfach Hilfe finden) mit blau in Richtung Refugees farbcodiert werden (bzw. je in Welt-Farbe)? Deswegen hier im Vorschlag erstmal gelb.

**Comment by marcus-herrmann** [comment]
Das ist irgendwie ein Mehrzweckticket <s>am Ostbahnhof</s> geworden. Schlage vor:

* Dieses Ticket befasst sich "nur noch" mit dem Umbau von Offer Index
* Die reduzierte Weltenstartseite: #931
* Der Umbau des mobilen Headers auf nicht-Startseiten: #930

**Comment by marcus-herrmann** [comment]
Wie vor 14 Tagen besprochen Zuweisung an @KonstantinKo für Übernahme/Bereitstellung der select-Funktionalität ("Beste Treffer"/"in der Nähe")

**Comment by marcus-herrmann** [comment]
![desktop v3-3 refugees 1440 - 1 1](https://cloud.githubusercontent.com/assets/505181/18949666/b071c2d4-863c-11e6-8c45-93bd1caac039.png)
![desktop v3-3 refugees 1440 - 1](https://cloud.githubusercontent.com/assets/505181/18949667/b071d184-863c-11e6-800b-8b59eba2bae7.png)
![desktop v3-3 refugees 1440 - 3](https://cloud.githubusercontent.com/assets/505181/18949668/b072f4ba-863c-11e6-9067-17e5b3eb0c33.png)
![desktop v3-3 refugees 1440 - 1 3](https://cloud.githubusercontent.com/assets/505181/18949669/b07625cc-863c-11e6-8483-700abfc07cc3.png)
![desktop v3-3 refugees 1440 - 1 2](https://cloud.githubusercontent.com/assets/505181/18949670/b0769a5c-863c-11e6-98b0-a4bb42b05e31.png)

**Comment by KonstantinKo** [comment]
Funktionalität von `sort_order` und `contact_type` switch existieren, braucht styling

Achtung, es gibt durch Umstellung des type-switch-systems nun ein paar Redundanzen in der Search-Komponente, für die ich keine Zeit mehr habe.

**Comment by KonstantinKo** [comment]
Achja, da sind noch ein paar `console.log`s übrig geblieben, die bitte noch rausschmeißen

**Comment by marcus-herrmann** [comment]
Note to self: 836 und 930 zusammengeführt in #931

**Comment by marcus-herrmann** [comment]
Kann demnach zu, sobald #931 komplett

**Comment by marcus-herrmann** [comment]
Mit dem stattgefunden Deploy von #931 hinfällig
