### ISSUE TITLE
Alte fehlende Übersetzungen von Gengo anfordern

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#838]
Es fehlen bei vielen alten Next Steps noch Übersetzungen. Diese bitte anfordern und direkt in die Datenbank schreiben lassen. Dabei lediglich die Next Steps berücksichtigen die nicht ohnehin schon bei Gengo liegen sollten, als erstellt wurden bevor wir Gengo aktiviert haben.

Bitte auch checken, ob es auch Kategorien gibt auf die das zutrifft.

**Comment by NilsVollmer** [comment]
Ich schaue mir gerade erstmal die aktuellen Übersetzungen an, also nachdem wir gengo aktiviert haben und da gibt es definitiv einen Bug: einige Übersetzungen fehlen bei uns in der DB, sind aber approved in gengo drin. Prüfe deshalb erst einmal unseren Prozess, der die Übersetzungen zieht und abspeichert.

**Comment by NilsVollmer** [comment]
Update: wir fragen nur die approved Übersetzungen der letzten 25 Stunden ab (täglich) und dachten, dass der Timestamp ein approved_at ist. Tatsächlich ist das aber nur die submitted time, also wann der Job erstellt wurde. Wenn dann die Übersetzungen nicht bis zur nächsten Abfrage da sind, ziehen wir uns die Übersetzung deshalb nicht mehr.

Ohne die Zeiteinschränkungen würden wir aber jeder Tag ALLE Übersetzungen ziehen und in die Datenbank schieben - unabhängig davon, ob sie schon da ist. Das erzeugt viel Worker- und Database-Load. **Streng genommen müssten bei den Kategorien sogar noch alle zugeordneten Angebote in der Sprache neu indiziert werden.**

Man könnte die Übersetzung ziehen und dann nur speichern wenn sie unterschiedlich zum aktuellen Wert ist aber der Worker-Load wäre dennoch relativ hoch..

**Comment by NilsVollmer** [comment]
Deploy TODO:

- WICHTIG: zuerst alle bereits vorhandenen Translations von gengo ziehen & speichern (manuell in der Konsole oder den überarbeiteten Worker #842 triggern), da wir sonst einiges doppelt Übersetzen werden (teuer!!)

Anschließend dann:

``` console
    # TODO: vorher unbedingt (!!!!) alle bereits vorhandenen Übersetzungen 
    # ziehen & speichern sonst werden wir unnötig doppelt übersetzen lassen!!!
    connection = Gengo::API.new(
      public_key: Rails.application.secrets.gengo['public_key'],
      private_key: Rails.application.secrets.gengo['private_key']
    )
    jobs = []
    translatable_locales = I18n.available_locales - [:de, :en]
    # NextSteps
    sql_string = translatable_locales.map { |locale| "text_#{locale} IS null" }.join(' OR ')
    NextStep.where(sql_string).each do |next_step|
      translatable_locales.each do |locale|
        next if next_step.send("text_#{locale}") # skip existing translations
        jobs << {
          tier: 'standard', type: 'text', max_chars: 255, auto_approve: 1,
          comment: 'It\'s for a web app to help refugees in Germany to find'\
                   ' help. Please use very simple / easy to understand'\
                   ' language.',
          purpose: 'Web content. Describing help for refugees in Germany',
          tone:    'Friendly, Informal',
          lc_src: 'en', lc_tgt: locale.to_s,
          body_src: next_step.text_en,
          slug: "NextStep:#{next_step.id}:text_#{locale}"
        }
      end
    end
    # categories
    sql_string = translatable_locales.map { |locale| "name_#{locale} IS null" }.join(' OR ')
    Category.where(sql_string).each do |category|
      translatable_locales.each do |locale|
        next if category.send("name_#{locale}") # skip existing translations
        jobs << {
          tier: 'standard', type: 'text', max_chars: 255, auto_approve: 1,
          comment: 'It\'s for a web app to help refugees in Germany to find'\
                   ' help. Please use very simple / easy to understand'\
                   ' language.',
          purpose: 'Web content. Describing help for refugees in Germany',
          tone:    'Friendly, Informal',
          lc_src: 'en', lc_tgt: locale.to_s,
          body_src: category.name_en,
          slug: "Category:#{category.id}:name_#{locale}"
        }
      end
    end
    connection.postTranslationJobs(jobs: jobs)
```

**Comment by NilsVollmer** [comment]
Erledigt: alle alten Übersetzungen sind gezogen und somit sind (aktuell) alle NextSteps und Kategorien übersetzt.
