### ISSUE TITLE
Target Audience Stamp entfernen

### ISSUE THREAD

**Issue by JulianJung** [clarat-org/clarat#839]
Es sollte künftig nicht mehr möglich sein durch folgende Kombination folgenden Target Audience Stamp zu erzeugen:

Kernfamilie + 2nd Part of Stamp neutral = für Familien und ihre Kinder
angezeigt stattdessen                              = für Familien

es sollte lediglich möglich sein diesen Target Audience Stamp in Kombination mit einem visible Age abzubilden:

Kernfamilie + 2nd Part of Stamp neutral + Age visible (10-15) = für Familien und ihre Kinder (10-15 Jahre)

**Comment by NilsVollmer** [comment]
Als mini-Feature direkt auf _base master und claradmin develop umgesetzt.
