### ISSUE TITLE
Ein Angebot, mehrere Organisationen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#84]
Es gibt Angebote die von mehreren Organisationen betrieben werden (siehe z.B. hier: https://www.schwulenberatungberlin.de/projekte/queer-leben/).

Dies wollen wir künftig auch abbilden können. Dafür müssen die folgenden Punkte abgedeckt werden:

- Relations in den Models
- Mehrere Anbieter im offer/show view
- Tests aktualisieren/ergänzen
-...

**Comment by KonstantinKo** [comment]
Braucht noch styling in der frontend Ansicht
(Bsp: http://clarat.herokuapp.com/angebote/beratung-fuer-homosexuelle-bisexuelle-transexuelle-und-intergeschlechtliche )

**Comment by Twiek** [comment]
@marcus-herrmann: Bitte sprich darauf an bevor Du loslegst.

**Comment by marcus-herrmann** [comment]
Mit @KonstantinKo kurz besprochen - analog zu Orga-hasMany-Offer-Styling?

**Comment by Twiek** [comment]
@marcus-herrmann: Ja, aber auch #108 berücksichtigen. Sehe grundsätzlich 2 Losungsmöglichkeiten:

1. Die Organisationen werden theoretisch alle angezeigt, praktisch wird aber irgendwann abgebrochen, also z.B. 'Caritas, Diakonie, Deutscher Tiersc... ' (z.B. nach 80 oder max. 100 Zeichen).

2. Wenn es mehrere Organisationen sind erscheint überhaupt kein Organisationsname, sondern nur 'Kooperationsprojekt'.

Ne Meinung dazu?

**Comment by marcus-herrmann** [comment]
Tendiere zu zwei, nicht dass die abgeschnittenen Strings irgendwann 'Deutsche T.., Bundesver.., Deutsche F...' lauten. Das hätte dann null Aussage. Da wäre "Kooperationsprojekt" im Result Listing stringenter. Die einzelnen Entitäten lassen sich ja gerne in Offer#show aufführen, da ist Platz.

**Comment by Twiek** [comment]
Ok, dann lass es erstmal so probieren.
