### ISSUE TITLE
SSL einführen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#840]
Brauchen wir für automatische Standorterkennung in Chrome, besserem Ranking bei Google...

Bitte erstmal nur verschiedenen Möglichkeiten checken (z.B. https://elements.heroku.com/addons/ssl, https://letsencrypt.org/... ) und einen Vorschlag machen was die aus Deiner Sicht beste Lösung wäre (inkl. Angaben zu Aufwand und Kosten).

**Comment by KonstantinKo** [comment]
Ohne es genau zu verstehen glaube ich, dass das von dir verlinkte SSL Addon ein vorhandenes Zertifikat benötigt (welches man sich separat kaufen muss). Es gibt noch https://elements.heroku.com/addons/expeditedssl - hier glaube ich ist das Zertifikat mit dabei, kann aber teuer werden je nachdem ob man wildcard (mit subdomains) haben möchte oder nicht.

Auf jeden Fall müssen wir aufpassen, da wir mit Einführung von SSL auch nur noch auf SSL assets verlinken dürfen (Bilder, externe JS Dateien, externes CSS, etc.).

Im Zweifelsfall sollte man aber mal nen Server-Administrator fragen, die kennen sich weit besser mit dem Thema aus. Auch, ob das mit letsencrypt ne Variante für uns ist.

**Comment by Twiek** [comment]
@KonstantinKo Hilft uns das https://substrakt.com/heroku-ssl-me-weve-come-a-long-way/ (inkl. Hacker News Diskussion: https://news.ycombinator.com/item?id=12136414 ?

**Comment by marcus-herrmann** [comment]
Mangels Testszenario kann ich das natürlich nicht überprüfen, aber die Lage gestaltet sich wohl so:

1. Man benötigt das Add On "SSL Endpoint" auf Heroku (20 $/Monat)
2. Man installiert sich Certbot (von LetsEncrypt) auf einem Mac (via Homebrew)
3. Start Certbot, Angabe der Domain, zu der man ein Cert braucht
4. Generierung Datei
5. Diese Datei muss auf den Server deployed werden und sie erwartet eine spezielle Route, insofern muss die in der App angelegt werden
6. Ansteuern der URL
7. Aktivieren des Endpoint AddOns auf Heroku
8. `$ sudo heroku certs:update /etc/letsencrypt/live/clarat.org/fullchain.pem /etc/letsencrypt/live/clarat.org/privkey.pem`

Certs von Lets Encrypt sind aktuell nur 90 Tage gültig. Dann

9. Renew: `$ sudo certbot renew --agree-tos` und weiter mit Schritt 5.

Quelle: http://collectiveidea.com/blog/archives/2016/01/12/lets-encrypt-with-a-rails-app-on-heroku/

Obendrauf kommen natürlich noch Anpassungen im Frontend, sodass wir keine Mixed Content Warnings (also ungesunde Mischungen aus http und https - looking at you, third party scripts) erzeugen.

Dann wiederum stehen uns neben den bekannten Vorteilen von SSL wieder ein paar Schmankerl (GeoLocation via JS in Chrome, Offline-Möglichkeiten in bestimmten Browsern, ...) zur Verfügung.

**Comment by Twiek** [comment]
Please try SSL FastTrack (https://app.sslfasttrack.com/home/prerequisites). Erstmal auf Staging.

**Comment by KonstantinKo** [comment]
Wartet auf Bestätigungs-Email an mail@clarat.org

**Comment by Twiek** [comment]
Inzwischen kam ne Rückmeldung von SSL FastTrack.

**Comment by KonstantinKo** [comment]
Auf staging done

**Comment by KonstantinKo** [comment]
Go für production?

**Comment by marcus-herrmann** [comment]
Kann von meiner Seite aus auf Production losgelassen werden - auf Staging waren keine Mixed Content Warnings ausfindig zu machen.

**Comment by KonstantinKo** [comment]
Wartet auf Wolffsohn IT.
Braucht dann noch `config.force_ssl = true` in production.rb
