### ISSUE TITLE
Umbrella bei Organisationen: Mehrfach-Selection & verpflichtend

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#841]
Und allen die bisher nichts ausgewählt haben 'Sonstige' zuweisen. Die entsprechenden IDs sind schon an die Researcher kommuniziert.

**Comment by NilsVollmer** [comment]
Braucht Rücksprache bzgl. 'None' Option.

**Comment by Twiek** [comment]
Neue Anforderungen (yeah):

Mehrfachauswahl zulassen!

Ansonsten soll 'Sonstiges' die 'None' Option sein.

Beide Anforderungen wurden ausgiebig gechallenged....

**Comment by NilsVollmer** [comment]
Also muss aus dem Enum eine Zuordnung werden - praktischerweise dann eine Extension des Filtermodels.. UmbrellaFilter z.B... Da es eh ein neues Model geben muss, können wir die Gelegenheit nutzen, dem Ding einen passenderen Namen zu spendieren ;-)

**Comment by Twiek** [comment]
Name soll Umbrella bleiben.

**Comment by NilsVollmer** [comment]
Ich habe den Namen im Backend frech pluralisiert weil man ja mehrere auswählen kann.

**Comment by NilsVollmer** [comment]
PR aus _base gestellt, die restlichen beiden kommen dann hinterher sobald der reviewed & merged ist.

**Comment by KonstantinKo** [comment]
@NilsVollmer in Zukunft bitte keine einfachen `has_and_belongs_to_many` mehr erstellen, sondern gleich `has_many :through`. Selbst wenn man das Verbindungsmodell *noch* nicht braucht
