### ISSUE TITLE
Bug: Gengo Translations werden nicht immer gezogen

### ISSUE THREAD

**Issue by NilsVollmer** [clarat-org/clarat#842]
Gefunden in #838 

Update: wir fragen nur die approved Übersetzungen der letzten 25 Stunden ab (täglich) und dachten, dass der Timestamp ein approved_at ist. Tatsächlich ist das aber nur die submitted time, also wann der Job erstellt wurde. Wenn dann die Übersetzungen nicht bis zur nächsten Abfrage da sind, ziehen wir uns die Übersetzung deshalb nicht mehr.

Ohne die Zeiteinschränkungen würden wir aber jeder Tag ALLE Übersetzungen ziehen und in die Datenbank schieben - unabhängig davon, ob sie schon da ist. Das erzeugt viel Worker- und Database-Load. **Streng genommen müssten bei den Kategorien sogar noch alle zugeordneten Angebote in der Sprache neu indiziert werden.**

Man könnte die Übersetzung ziehen und dann nur speichern wenn sie unterschiedlich zum aktuellen Wert ist aber der Worker-Load wäre dennoch relativ hoch.

**Comment by NilsVollmer** [comment]
Deploy TODO:  das neue created_at der NextSteps füllen (Stichtag seitdem wir gengo benutzen)
``` console
NextStep.update_all(created_at: Date.new(2016,5,26))
```
Ausserdem muss #838 schnellstmöglich erledigt werden weil wir sonst noch sehr alte Kategorien ohne Übersetzungen haben und uns dadurch immer alles von gengo ziehen. Erst wenn die alten Kategorien abgearbeitet sind, kann die neue Logik vernünftig greifen und die Menge, die von gengo gezogen wird, ordentlich verringern.

**Comment by NilsVollmer** [comment]
Ich habe den reindex der Kategorie-Angebote jetzt erstmal raus gelassen, weil wir da IMO ein wenig aufpassen müssen:  eigentlich müsste man alle Angebote der jeweiligen Kategorie und alle aller Kind-Kategorien (die haben nämlich auch immer den Kategorienamen mit drin) neu indizieren. Und das aktuell in allen Sprachen, solange wir das noch nicht optimiert haben und da uns gerade viele Kategorien fehlen würden diese ganzen reindex-Operations auch potentiell mehrfach für mehrere Kategorien geschehen (durch die Kind-Zuordnung).

Deshalb habe ich es raus gelassen und wir sollten dann lieber sobald die Übersetzungen da sind (passiert ja meistens innerhalb von Tagen) einen manuellen Reindex über alle Angebote laufen lassen.
Parallel dazu können wir dann versuchen, die Index-Operation pro locale zu ermöglichen damit wir hier und auch bei den GT-Translations nicht immer unnötig indizieren.

**Comment by NilsVollmer** [comment]
Update: der Bug ist gefixed aber dabei sind andere Ungereimtheiten aufgekommen, sodass das Ziehen der GengoTranslations noch einmal grundsätzlich überarbeitet werden sollte.

Es sollten beim Anfordern der Translations die Job-IDs gespeichert in optionalen Feldern gespeichert werden. Sobald die Übersetzung gezogen wurde, soll das ID-Feld wieder auf nil gesetzt werden. So können wir dann nur für die pending Jobs (die mit einer ID) nachfragen, ob sie schon fertig übersetzt sind. Damit fragen wir dann so wenig wie möglich an und speichern auch nur das Notwendige.

**Comment by KonstantinKo** [comment]
Braucht noch reindex

**Comment by NilsVollmer** [comment]
Im Newsfeed kommuniziert
