### ISSUE TITLE
Kategorien ohne approved Angebote nicht anzeigen

### ISSUE THREAD

**Issue by JulianJung** [clarat-org/clarat#844]
Kategorien ohne approved Angebote sollen nicht im Frontend angezeigt werden .
Das manuelle entfernen des visible Hakens kommt dazu nicht in Frage, da wir hiermit Kategorien langfristig nicht im Frontend anzeigen wollen, um wichtigere Kategorien nicht aus dem Fokus zu nehmen und die Kategorienmap zu entschlacken.
Die Rückmeldungen der Researcher "ich habe die Angebote jetzt approved, du kannst die Kategorie fürs Frontend freischalten" sind als Alternative zu Ressourcenhungrig.

**Comment by NilsVollmer** [comment]
PR auf clarat gestellt - ist das Feature wirklich so trivial oder übersehe ich etwas?

**Comment by KonstantinKo** [comment]
Hab's abgeändert, bitte nochmal drüberschauen. Von mir aus kann merged werden.

**Comment by NilsVollmer** [comment]
Sieht gut und elegant aus - ich merge dann mal.

**Comment by NilsVollmer** [comment]
Im Newsfeed kommuniziert
