### ISSUE TITLE
Kategorien für Sendgrid

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#847]
Ich möchte über Sendgrid Infos zu den Öffnungs- und Klickraten für externe Mails bekommen. Aktuell sind die Statistiken durch unsere internen Mails weitgehend unbrauchbar.

Mögliche Lösung wäre es hier über die Kategorisierung zu gehen: https://sendgrid.com/docs/API_Reference/SMTP_API/categories.html.

**Comment by NilsVollmer** [comment]
Zusätzlicher Wunsch: family & refugees taggen.

**Comment by Twiek** [comment]
Bei Fragen gerne auch direkt an Eleonore wenden.

**Comment by allthegoldt** [comment]
Ich habe bei Sendgrid nachgefragt, was mit unserem Free-Plan möglich ist (ich habe ggf. passende Einstellung für Marketing-Listings gefunden, was wir nicht haben). Kategorien kann man für Refugees & Family benutzen. Ich warte Klärung von Sendgrid und weitere Spezifizierung von Eleonore ab.

**Comment by allthegoldt** [comment]
Eleonore meint, dass das Ticket von Laura ist. Ich warte mit dem Ticket, bis ich mit ihr gesprochen habe.
