### ISSUE TITLE
'To Do'- Note Topics in 'Internal Info' umbenennen

### ISSUE THREAD

**Issue by JulianJung** [clarat-org/clarat#850]
Siehe Titel.
Das dann alte (705) 'To Do' Notes aufeinmal 'Internal Info' als Topic haben ist bekannt.

**Comment by Twiek** [comment]
In clarat_base geändert (https://github.com/clarat-org/clarat_base/commit/f3b9dd7e90a0f32557ec5854c824bec048a68645). Nach dem Deploy noch über die Konsole alle Note updaten.

**Comment by NilsVollmer** [comment]
Deployed und TODO erledigt.
