### ISSUE TITLE
Neue Participant Structure: Target Audience and others with same problem

### ISSUE THREAD

**Issue by JulianJung** [clarat-org/clarat#851]
Bitte oben genannte 'Participant Structure'-Auswahlmöglichkeit anlegen.
Name kann gerne gekürzt werden falls euch etwas einfällt.
Ziel ist es Stuhlkreisangebote die ausschließlich für eine bestimmte Zielgruppe vorgesehen sind markieren zu können.

**Comment by NilsVollmer** [comment]
Als mini-Feature direkt auf _base master umgesetzt. Braucht dann noch einen bundle_update auf claradmin, den ich jetzt nicht gemacht habe weil dabei noch andere Dinge (GengoOrder) mitgekommen wären.

**Comment by NilsVollmer** [comment]
@Twiek Ist jetzt auf develop in claradmin, sollte also bis zum nächsten deploy kommuniziert werden.
