### ISSUE TITLE
Implementierung "Portalseite" (Vorschaltseite Startseite)

### ISSUE THREAD

**Issue by marcus-herrmann** [clarat-org/clarat#852]

**Comment by marcus-herrmann** [comment]
Vorschlag Überarbeitung der Illustrationen:

<img width="1058" alt="bildschirmfoto 2016-06-30 um 17 22 43" src="https://cloud.githubusercontent.com/assets/505181/16493844/51d015ec-3ee7-11e6-99b9-5bcaeb88357c.png">

**Comment by Twiek** [comment]
Looks good. Please proceed.

**Comment by marcus-herrmann** [comment]
Stand gemäß Tinos Design von Ende Juni nun auf Featurebranch #852

**Comment by marcus-herrmann** [comment]
@Twiek : Bräuchte noch Title
@Twiek oder @KonstantinKo : a[href='#'] müsste noch durch echte Routes ersetzt werden

**Comment by Twiek** [comment]
@marcus-herrmann Vorläufiger Title: 'Unterstützungsangebote für Kinder, Jugendliche, Familien und Flüchtlinge'
@KonstantinKo Bitte um die Routes kümmern.

**Comment by KonstantinKo** [comment]
Routes eingefügt. Es fehlen noch ein paar Übersetzungen und dann soll ja auch noch was am Header-Styling auf den restlichen Seiten verändert werden.
