### ISSUE TITLE
Mobile Suchergebnisse werden im Arabischen nicht richtig angezeigt

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#853]
Siehe Screenshot:

![bildschirmfoto 2016-06-30 um 11 56 07](https://cloud.githubusercontent.com/assets/432388/16484542/00ed1cec-3eba-11e6-86a5-a50c12c266ab.png)

**Comment by marcus-herrmann** [comment]
Als Hotfix auf develop
