### ISSUE TITLE
Kriege claradmin lokal nicht zum Laufen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#856]
<img width="1276" alt="bildschirmfoto 2016-07-01 um 18 55 29" src="https://cloud.githubusercontent.com/assets/432388/16528473/7d2a5640-3fbd-11e6-8db4-6e08900db091.png">

**Comment by KonstantinKo** [comment]
@Twiek Achja, der neue Befehl lautet `npm run rails-server`. Braucht dann ein paar Sekunden nach Serverstart  bis das vendor-bundle generiert wurde.

**Comment by Twiek** [comment]
Thanks. Leider gibt es nun ein weiteres Problem (bei Nils sieht es ähnlich aus).

![bildschirmfoto 2016-07-04 um 09 51 07](https://cloud.githubusercontent.com/assets/432388/16554106/09622a8c-41cd-11e6-9457-c41b672e5f99.png)

**Comment by KonstantinKo** [comment]
`npm install` oder kurz `npm i`
Ist das Frontend-pendant zu `bundle install`

**Comment by NilsVollmer** [comment]
Ich habe das Problem leider nach wie vor:

```console
elevens-MacBook-Air:claradmin nilsvollmer$ npm run rails-server

> claradmin@1.1.1 rails-server /Users/nilsvollmer/Developing/claradmin
> echo 'visit http://localhost:3000/hello_world' && foreman start -f Procfile.dev

visit http://localhost:3000/hello_world
sh: foreman: command not found

npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "rails-server"
npm ERR! node v4.1.1
npm ERR! npm  v2.14.4
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! claradmin@1.1.1 rails-server: `echo 'visit http://localhost:3000/hello_world' && foreman start -f Procfile.dev`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the claradmin@1.1.1 rails-server script 'echo 'visit http://localhost:3000/hello_world' && foreman start -f Procfile.dev'.
npm ERR! This is most likely a problem with the claradmin package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     echo 'visit http://localhost:3000/hello_world' && foreman start -f Procfile.dev
npm ERR! You can get their info via:
npm ERR!     npm owner ls claradmin
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/nilsvollmer/Developing/claradmin/npm-debug.log
```

npm install ist durchgelaufen und macht beim erneuten Versuch auch nicht mehr viel. Beim Start des Server via neuen Commands kommt der Fehler.

Wenn ich mit 'rails s' den Server starte, gibt es den anderen Fehler, der übrigens auf dem aktuellen develop auch bei den Tests auftritt (vgl. https://travis-ci.org/clarat-org/claradmin/builds/142214126). Vermutlich muss da der rake-task angepasst werden?!

**Comment by NilsVollmer** [comment]
Okay nach gem install foreman funktioniert es.
