### ISSUE TITLE
clarat Frontend Suche - Scrolling Bug

### ISSUE THREAD

**Issue by KonstantinKo** [clarat-org/clarat#857]
Getestet in Chrome.

Versucht man auf der Suche ganz herunter zu scrollen, scheint zuviel Platz nach unten zu sein und man springt automatisch wieder zum eigentlichen Seitenende. Stört die Seitennutzung nicht, sieht aber kaputt aus.

![claratbug2](https://cloud.githubusercontent.com/assets/779660/16560801/d9c8a2a0-41f5-11e6-8b5a-8991f99c4b16.gif)
(Beim gif gebe ich nur den scroll-Impuls nach unten, nach oben springt es automatisch. Es zittert in der Realität mehr als die FPS hier wiedergeben können)

**Comment by marcus-herrmann** [comment]
Vor meinem Urlaub habe ich das in Chrome nachvollziehen können/ebenfalls gesehen (während FF problemlos war, meine ich). Heute war es genau umgekehrt: Ich habe es in verschiedenen Chromium-Versionen nicht reproduzieren können (eventuell Auto-Update?), dafür aber im FF 47.0.1. - wie auch immer: Mit https://github.com/clarat-org/clarat/tree/fix/857-scrolling-sticky sollte das abgestellt sein; ich hoffe das kannst du wiederum reproduzieren ;) @KonstantinKo

**Comment by Twiek** [comment]
Wenn ich 'mit Schwung' nach unten scrolle (Suchergebnisseite), dann 'vibriert' die Grafik sobald ich unten angekommen bin. Schaut auch nicht gut aus.

**Comment by KonstantinKo** [comment]
Genau um den Fehler geht's

**Comment by Twiek** [comment]
Ok, dann gerne mal Marcus Lösungsvorschlag checken.

**Comment by marcus-herrmann** [comment]
Hier an einem anderen Rechner habe ich den Effekt live auch in Chrome 51 noch, _während die Seite noch lädt_ . Danach nicht mehr.

**Comment by KonstantinKo** [comment]
Jau fix klappt bei mir
