### ISSUE TITLE
Geolocation Möglichkeiten checken

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#858]
Da Berlin als default zusehends keinen Sinn mehr macht sollten wir nach Möglichkeiten suchen wie wir den Ort der suchenden Person anderweitig voraussagen könne. Mögliche Lösungen sollten insbesondere folgende Kriterien erfüllen:
- Hohe Trefferquote (wenn ich in Berlin bin sollte clarat mir keine Ergebnisse in Hamburg anzeigen)
- Möglichkeit die Lösung mit dem deutschen Datenschutz ein Einklang zu bringen
- Überschaubarer Aufwand (initial und ongoing)

**Comment by Twiek** [comment]
Habe mal bei Wheelmap nachgefragt.

**Comment by Twiek** [comment]
Bitte versuchen es mit Algolia zu probieren (https://www.algolia.com/doc/guides/geo-search/geo-search-overview#filter-and-sort-around-a-location) und auch zu prüfen, ob/wie wir aus den erratenen Geolocation-Daten wieder einen für Menschen aussagekräftigen Ortsnamen bekommen der dem User auch wieder angezeigt wird (damit er schneller merkt, falls wir seinen Standort falsch eingeschätzt haben).

**Comment by NilsVollmer** [comment]
@Twiek Ich hab's mal maximal unschön ge-prototyped.. Ist auf staging deployed. Der verwendete Suchort von Algolia wird zum Testen sowohl in den Page-Title als auch in das Suchfeld eingetragen (aber nicht in den 'Leider keine Angebote.. (ORT) gefunden'-Text).
