### ISSUE TITLE
Klicks auf externe Links erfassen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#862]
Momentan können wir nicht nachvollziehen, ob User auf die ausgehenden Links klicken. Funktioniert theoretisch wie folgt: https://support.google.com/analytics/answer/1136920?hl=de

**Comment by Twiek** [comment]
@NilsVollmer Da bist Du mit Eleonore sowieso schon dran, oder?

**Comment by NilsVollmer** [comment]
Klingt sehr ähnlich, kann also zusammengelegt werden.

**Comment by NilsVollmer** [comment]
Bzw. das hier kann einfach zu - durch die Referenz finden wir die Info's bei Bedarf ja wieder. Closed because of duplicate

**Comment by NilsVollmer** [comment]
Re-Open: es geht hier doch um was anderes. Hier geht es um das Erfassen von Links innerhalb unserer Webseite, die woanders (auf andere Pages) hin führen. Bei dem anderen Ticket geht es um utm-Tracking der Links aus unseren Mails, die auf unsere Seite führen. Also hier outbound-Traffic-Tracking bzw. UserFlow messen und in dem anderen Ticket inbound-Traffic-Tracking

**Comment by marcus-herrmann** [comment]
Vorbereitet auf Featurebranch: https://github.com/clarat-org/clarat/tree/feature/862-ext-link-click-tracking

**Comment by marcus-herrmann** [comment]
Erweitert/verbessert/refactoriert unter Leitung von Konstantin:

https://github.com/clarat-org/clarat/tree/feature/862-ext-link-click-tracking

**Comment by Twiek** [comment]
https://github.com/clarat-org/clarat/pull/886 scheint noch Probleme zu machen.

**Comment by NilsVollmer** [comment]
Behoben.
