### ISSUE TITLE
Falscher Facebook-Teaser

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#863]
Wenn ich versuche http://www.clarat.org/family auf Facebook zu posten, dann erscheint dort der Teaser-Text von Refugees. Das sollte nicht sein...

![bildschirmfoto 2016-07-07 um 12 32 06](https://cloud.githubusercontent.com/assets/432388/16650544/028f9d6a-443f-11e6-8daa-c6ecc826cd16.png)

**Comment by NilsVollmer** [comment]
Schickes facebook-bild ;)

**Comment by NilsVollmer** [comment]
Der untere Text ist in beiden Welten identisch - nur der Title wird offensichtlich nicht korrekt für die section angezeigt.

**Comment by NilsVollmer** [comment]
Anscheinend wird bei dem Facebook-crawler, der da durchläuft, die section nicht gesetzt und dann gibt es den Fallback auf refugees. Habe dazu gerade nicht viel mehr Ideen - @KonstantinKo fällt bestimmt eher was dazu ein.

**Comment by KonstantinKo** [comment]
https://developers.facebook.com/docs/sharing/webmasters

Eventuell ist `og:description` das was wir brauchen. Man kann überlegen ob man dann die anderen tags auch irgendwie befüllen möchte.

**Comment by NilsVollmer** [comment]
Als mini-feature direkt auf clarat develop umgesetzt - Tag steht im HTML.

**Comment by Twiek** [comment]
@NilsVollmer Kann man erst testen wenn es live ist, oder?

**Comment by NilsVollmer** [comment]
@Twiek im HTML steht halt der korrekte Inhalt drin. Ob der Crawler das dann tatsächlich korrekt verarbeitet, können wir tatsächlich erst live testen. Facebook bietet zwar einen direkten Check an aber auf Staging haben wir ja HTTP-Auth vorgeschaltet und damit kommt der wahrscheinlich nicht klar.

Da es nichts schlechter machen kann und es in der Doku so steht, dass der crawler den Inhalt verarbeitet, würde ich es einfach darauf ankommen lassen und live ausprobieren.

**Comment by Twiek** [comment]
Ja, raus damit. Hänge dann noch ein 'Deploy-ToDo' ran, damit wir nicht vergessen zu checken, ob es auch in der Realität klappt.

**Comment by Twiek** [comment]
Bei mir klappt leider noch immer nicht...

**Comment by NilsVollmer** [comment]
Update: der og:title ist korrekt gesetzt aber das Problem ist die canonical-URL: Der FB-Crawler behandelt die immer als redirect dem er folgt und deshalb steht da dann der refugees-Text. Mir fällt gerade keine Lösung ein und das Problem hat sich ja potentiell bald mit der Landing-Page und der Abschaffung der default-Welt erledigt.
