### ISSUE TITLE
Suchoptionen mobil noch deutlicher 

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#866]
Eventuell testen 'Filter' und 'Kategorien' direkt namentlich erwähnen/verlinken (statt 'Suchoptionen'). Zusätzlich testen ob man auch die Karte direkt verlinken kann (Vgl. Yelp).

**Comment by marcus-herrmann** [comment]
Zum Thema "deutlicher":

![bildschirmfoto 2016-08-04 um 10 16 01](https://cloud.githubusercontent.com/assets/505181/17395136/231ed7ae-5a2d-11e6-87b6-d7a11cf472d8.png)

Das ist in den Entwicklertools des Browsers verändert und noch nicht persistiert (die einzige Möglichkeit dafür wäre ja in der Localeapp, und das würde sofort live gehen). Da der Button nun mehr Text hat und je nach Breite oder Übersetzungslänge zweizeilig werden kann, ist der Button erstmal nur auf dem Featurebranch zu 866 dynamisch hoch: https://github.com/clarat-org/clarat/tree/feature/866-better-search-option-label-mobile

**Comment by marcus-herrmann** [comment]
Verständnisfrage zur Karte: dachtest du da an eine Sprungmarke nach unten zur Karte (z.B. durch einen Button, der in der Nähe des "Suchoptionen"-Buttons ist) oder etwas "krasseres"?

**Comment by Twiek** [comment]
Sprich mich bitte bei nächster Gelegenheit dazu an.

**Comment by Twiek** [comment]
Mir ist übrigens gerade aufgefallen, dass wenn ich die Suchoptionen 'wegwische' (nicht auf das 'x' klicke) dann unter der Suchleiste 'Suchoptionen ausblenden', nicht 'Suchoptionen einblenden' steht. Frage mich wozu dort jemals 'Suchoptionen ausblenden' steht, da man das doch ohnehin nie lesen oder klicken kann wenn es Sinn macht, oder?

Ansonsten auch gerne bei Anzeige der Suchoptionen den Headerlink 'XYZ Suchergebnisse anzeige' unterstreichen.

**Comment by marcus-herrmann** [comment]
Der Bugfix zum falschen Label nach "Wegswipen" und die Unterstreichung hier: https://github.com/clarat-org/clarat/tree/fix/866-offcanvas-fixes

**Comment by marcus-herrmann** [comment]
Funktionalität ist vorbereitet, Frage nach genauem Design noch offen. In etwa so? @Twiek 

![better_offcanvas_trigger](https://cloud.githubusercontent.com/assets/505181/17968180/a274c3de-6acb-11e6-8a0a-0360e7cbbf44.png)

**Comment by Twiek** [comment]
Finde ich gut. Denke deployen sollten wir das aber erst in Kombination mit https://github.com/clarat-org/clarat/issues/836. 

Ansonsten wurde gerade noch mal die alte Entscheidung gechallengt, dass in der mobilen Ansicht das 'Wo' Feld erst zu sehen ist, wenn man vorher in das 'Was' Feld klickt. Scheint für z.B. Yelp zu funktionieren, aber macht das auch für uns Sinn? Kann man irgendwie anders darauf verweisen, dass man auch seinen Standort ändern kann?

**Comment by marcus-herrmann** [comment]
Ich nehme an, das hier ist seit dem Meeting heute erstmal on hold?
