### ISSUE TITLE
States 1.5

### ISSUE THREAD

**Issue by NilsVollmer** [clarat-org/clarat#867]
TODO:
- [x] neue States & Transitions (Offers and Orgas)
- [x] Entscheidung bzgl. orga_deactivated & damit verknüpften Automatisierungen abwarten & entsprechend implementieren
- [x] Orga-Transitions: all_done -> checkup & approved -> checkup
- [x] all_done mit approved 'gleichsetzen'
- [x] after_enter: approved => alle nicht-saisonalen Angebote setzen expires_at auf jetzt + 1 Jahr
- [x] Bearbeitung von Angeboten (und Orgas?) nur in speziellen States erlauben? (Forms nicht rendern) => muss durch R-JF, warte auf finale Entscheidung (Yes! nur in initialized, checkup_process & approval_process und auch für Orgas)
- [x] Kompromiss: da man in completed nicht mehr bearbeiten soll, muss das Angebot/die Orga wieder zum bearbeiten freigeschaltet werden dürfen. Umgesetzt als ein Event, das automatisch entweder zurück zu initialized (neues Angebot/Orga) oder zu checkup_process (war schonmal approved) wechselt. 
- [x] Neu: kein checkup_process auf Orga-Ebene (produziert im Moment mehr Probleme mit den Prozessen der Researcher als er löst)
- [x] Angebote, die von Orgas deaktiviert wurden: Logik minimal anpassen (bleiben in ihrem Deaktivierungsstate, wenn approve nicht klappt)
- [x] State-Changes zu bestimmten states (checkup & approval process + x?) von invaliden Angeboten ermöglichen
- [x] completed_by & _at
- [x] State-Transition-Buttons auch über den Forms anzeigen (convenience)
- [x] Tests, Tests, Tests
(...)

**Automatisierte Logik für saisonale Angebote (+ new optional field, workers and asana task)**
- [x] starts_at Feld & dadurch werden Angebote zu saisonalen Angeboten
- [x] bei ablaufen: paused anstatt expire für saisonale Angebote
- [x] automatische transition: bei approve: saisonale Angebote vor ihrem TimeFrame werden seasonal_pending
- [x] täglicher worker, der 1. seasonal_pending Angebote prüft und entsprechend freischaltet und 2. paused-Angebote auf ihr start-date prüft und einmalig 30 Tage davor ein Asana-Task (Projekt 'Querschläger') erstellt
- [x] Asana Projekt ID
- [x] Tests, Tests, Tests

**Automatisierte mailings_enabled Logik (+ change field to enum)**
- [x] neues Feld, entsprechende migration & altes Feld löschen
- [x] bisherige Logik auf neues Feld umschreiben
- [x] orga done => mailings Logik greift (Definition: große Orga fehlt noch) und bei großen Orgas wird einmalig ein Asana-Task an Comms (Projekt-ID??) geschickt
- [x] Asana Projekt-ID
- [x] große Orga definition (waiting for comms) einbauen
- [x] Tests

vor dem Deploy:
- [x] mit Comms abklären, ob und wenn ja, wie wir absichtlich deaktivierte Orgas in 'force_disabled' übertragen können.
Update dazu: Comms hat Orga-Liste und erstellt vorab für die Kandidaten eine extra Notiz mit 'force disabled'. Nach deploy können diese Orgas dann maschinell gefunden und mailings auf force_disabled gesetzt werden.

**Comment by NilsVollmer** [comment]
Klären:
- [ ] unnötige transitions entfernen? 
- [ ] different_actor guard doppelt oder in den neuen State auslagern?

**Comment by NilsVollmer** [comment]
Soweit fertig, warte noch auf ein paar externe Entscheidungen.

**Comment by NilsVollmer** [comment]
Deploy TODO:
```console
Organization.approved.where(mailings: 'enabled').map(&:mark_as_done!)
```

**Comment by NilsVollmer** [comment]
So, PR's sind raus. Auf claradmin muss vor dem merge noch das Gemfile auf _base master (nach dem PR merge dort) zurückgebogen werden.

Außerdem kann es noch sein, dass sich die 'große_orga'-Logik (mailings-only) noch minimal ändert aber der komplette Rest kann und sollte unabhängig davon reviewed werden, da es zeitlich sonst knapp werden könnte.

**Comment by KonstantinKo** [comment]
Reviewed & Merged. Ist natürlich ne ganze Menge, was das Zusammenspiel der ganzen Dinge angeht vertrau ich dir uns deinen Tests ;)
Gibt sicherlich eine refactor-bare Bereiche für's Backend 2.0. Wenn erstmal die Validierungen aus dem Model verschwinden kann man viele update_column durch events ersetzen.
