### ISSUE TITLE
Codeword im Frontend umbenennen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#868]
Statt "Wonach musst du fragen oder auf der Webseite suchen?" künftig bitte "So heißt die Hilfe beim Anbieter:"

**Comment by JulianJung** [comment]
Laut Asanaverlauf kann das ganze zudem ans Ende der Description wandern. Die Next-Steps hatten wir ja mal als weniger sinnvoll für diesen Satz/Hinweis befunden.
https://app.asana.com/0/49099656685110/112142567461949

**Comment by NilsVollmer** [comment]
@Twiek / @JulianJung Bei allen Sprach-Änderungen in localeapp brauchen wir ja immer wieder die Übersetzungen oder zumindest einen englischen Fallback. Es wäre super, wenn ihr das vorzeitig schon erwähnen würden, damit das dann erst nicht auffällt wenn sich jemand das Ticket vornimmt. Damit verzögern wir die Bearbeitungszeit nur unnötig und es könnte ja easy vorher oder parallel ablaufen.

**Comment by Twiek** [comment]
Habe den deutschen Text jetzt in Localeapp geändert. Die Verschiebung nehmen wir in Angriff sobald die Zukunft des Codewortes final geklärt ist.
