### ISSUE TITLE
Mobile Share Buttons ala Techcrunch, Huffington Post etc.

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#87]
Inkl. What's App.

![bildschirmfoto 2015-01-05 um 18 52 49](https://cloud.githubusercontent.com/assets/432388/5617188/3918b7b0-950c-11e4-8156-c3a517897aeb.png)

**Comment by tordans** [comment]
Hast du ein gutes Skript gefunden für whatsapp @Twiek ? Ich habe ein inoffiziellen in meinen Bookmarks, das wollte ich mal ausprobieren. 
T

**Comment by Twiek** [comment]
@tordans Warten wie bei Google-Ananlytics noch auf die grundsätzliche Freigabe vom Anwalt, sollte aber hoffentlich nächste Woche kommen. Da wir noch kein Skript etc. haben, freue ich mich über jeden Tipp.

**Comment by tordans** [comment]
Habe nochmal geschaut.
http://whatsapp-sharing.com/ scheint der goto-place zu sein.
Laut http://rechtsanwalt-schwenke.de/whatsapp-marketing-recht-teil1-whatsapp-sharing-button/ ist das rechtlich auch alles OK da kein externes iFrame (wie bei Facebook und Co). Aber ich denke, wir werden es so bauen, dass wir das Script nicht verwenden sondern einfach selbst einen Button machen da wir dann auch ganz normal GA Event Tracking drauf packen können.

**Comment by Twiek** [comment]
Thanks.

**Comment by tordans** [comment]
PS: Wenn Ihr Tracking für den Button haben wollt, schau mal unter https://github.com/kriskbx/whatsapp-sharing/issues/26

**Comment by Twiek** [comment]
Vorerst Beschränkung auf offer.show in der mobilen Ansicht.

Folgende Services: Facebook, Twitter, WhatsApp, E-Mail (geht das eigentlich auch mit sms).

**Comment by Twiek** [comment]
Vor Umsetzung bitte http://www.heise.de/ct/ausgabe/2014-26-Social-Media-Buttons-datenschutzkonform-nutzen-2463330.html lesen und Rücksprache mit mir halten.

**Comment by KonstantinKo** [comment]
Shariff buttons sind eingebaut im offers#show. SMS bieten die nicht an.
Braucht noch styling und Beschränkung auf Mobilansicht. @marcus-herrmann würdest du das übernehmen?

**Comment by marcus-herrmann** [comment]
Note to self:

* Desktop: Platzierung bleibt unten, WhatsApp ausgeblendet
* Mobile: "Floater", der nach einem Scrollweg erscheint, "Share"/"Teilen"-Label, möglichst keine aggressive Logo-Galerie

**Comment by marcus-herrmann** [comment]
Update note to self:
* Desktop Lasche

**Comment by marcus-herrmann** [comment]
Gestaltungsvorschlag [in eigenem Branch](https://github.com/clarat-org/clarat/tree/feature/87-mobile-share-buttons)

**Comment by Twiek** [comment]
Aktuelle Screenshots:

![bildschirmfoto 2015-07-15 um 11 50 50](https://cloud.githubusercontent.com/assets/432388/8695810/e1255064-2ae7-11e5-8b58-45d248a3c0d2.png)
![bildschirmfoto 2015-07-15 um 11 50 36](https://cloud.githubusercontent.com/assets/432388/8695807/e122b962-2ae7-11e5-8581-a7e25bf8579f.png)
![bildschirmfoto 2015-07-15 um 11 49 45](https://cloud.githubusercontent.com/assets/432388/8695809/e125492a-2ae7-11e5-9d16-5a0bdae5dc12.png)
![bildschirmfoto 2015-07-15 um 11 48 45](https://cloud.githubusercontent.com/assets/432388/8695808/e122e478-2ae7-11e5-969b-a8dc300d5238.png)

**Comment by marcus-herrmann** [comment]
Korrekt. So ist der Vorschlag.

**Comment by Twiek** [comment]
Reihenfolge ändern (Desktop: Mail, Facebook, Twitter; Mobile: Mail, WhatsApp, Facebook, Twitter) + noch mal checken ob/wie man sms integrieren kann.
