### ISSUE TITLE
Produktivitäts-Statistiken: Burn-Up Chart

### ISSUE THREAD

**Issue by KonstantinKo** [clarat-org/clarat#870]
Teil 1 der Produktivitätsstatistiken: Teamleiter möchten Ziele für Teams festlegen und Meilensteine ableiten können. Dafür bauen wir Burn-Up Charts. Das genaue Konzept liegt bei Konstantin auf Papier.

Erledigt:
- [x] Ziel anlegen: Formular und speichern
- [x] Charts pro angelegtem Ziel anzeigen
- [x] Produktivitäts-Tracking
- [x] Tracking-Linie anzeigen
- [x] Ressourcen/Durchschnittszeiten Tracking
- [x] Projektionslinie errechnen und anzeigen
- [x] Nutzer: Angabe von aktuellem Team
- [x] Nutzer: Angabe von IST-Stunden, Vergleich in Tabelle zu SOLL-Stunden
- [x] Anzeigebeschränkung, je nach Nutzerrechten

Hohe Prio:
- [x] Sortierung der Nutzer in Ressourcenplanung alphabetisch
- [x] Kommentarfeld für Abweichungen vom Ist-W&A (Freitext)
- [x] UserTeams anlegen, bearbeiten[, löschen?]

Niedrigere Prio:
- [ ] Genauere Ziele anlegen: Ausgangs-Zustand angeben können (von state x in state y)
- [ ] Nutzer für Ressourcenplanung deaktivieren können
- [ ] Ziele editieren, wenn es bereits laufende Daten gibt
- [ ] Absence-Convenience
- [ ] Div. Features in Ziel-Anzeige ("was wäre wenn" Daten-Änderung)
- [ ] Anzeige von Statistiken pro Nutzer, nicht nur pro Team

**Comment by KonstantinKo** [comment]
Deploy TODO:
```
Statistic.find_each do |stat|
  model, value = stat.topic.split('_')
  stat.model = model.titleize
  stat.field_end_value = value
  stat.field_name = 'aasm_state'
end
```

**Comment by NilsVollmer** [comment]
Update: Alles bis hierhin ist jetzt deployed & deploy TODOs sind durchgeführt!

**Comment by NilsVollmer** [comment]
Update: Batch 2 deployed

**Comment by Twiek** [comment]
Hier noch mal die neuen Anforderungen:

* Es müssen Ziele für einzelne Personen erstellt werden können (ob explizit oder über 1 Personen Teams ist egal)
* Diese Ziele (Soll und Ist) sind für diese Person selber und aller ihr übergeordneten Personen einsehbar (Vgl. Baustruktur).
![bildschirmfoto 2017-02-02 um 16 02 35](https://cloud.githubusercontent.com/assets/432388/22554759/9a2533c0-e961-11e6-9450-7540521de137.png)
* Aggregierte Ziele (Teams) können nur Personen angehören die in der Struktur unterhalb des Erstellers angesiedelt sind. Alle Ziele (Teams) sind neben dem Ersteller ebenfalls für alle Personen einsehbar, die in der Struktur über ihm angesiedelt sind.
* Neben dem Graphen sind alle Zahlen auch in einer optisch gerne sehr einfach gestalteten Tabelle (Vgl. Statistiken) einzusehen (in Wochen unterteilt).
* Neben den genannten Zielen gibt es auch noch aggregierte Ziele für alle Family und getrennt davon alle Regugees Angebote. Falls es einfacher ist kann hier auch nur der Ist-Zustand in einer Tabelle angezeigt werden. Diese aggregierten Zahlen sind generell für alle Mitarbeiter einsehbar.

**Comment by Twiek** [comment]
@KonstantinKo Habe gerade noch mal eine wichtige 'Detailänderung' vorgenommen (Kommentar überarbeitet). Geht darum, dass Ziele (Soll/Ist) nicht mehr generell von allen in der Struktur über dem Ersteller angesiedelten Personen einsehbar sind, sondern immer nur von der Person direkt über dem Ersteller. Der/die Chefin kann also individuelle Ziele auf unterster Ebene nicht sehen. Lass dazu später noch mal sprechen.

**Comment by Twiek** [comment]
Neues Issues erstellen und auf dieses verweisen (aber es schließen).

**Comment by Twiek** [comment]
Aktuelles Schaubild: https://docs.google.com/drawings/d/1l2DUm1T0jVVbFIk9icGwOoimoax6yk7-LHpxMn-TguA/edit

Ok, hier die neusten To-dos:

- [ ] Die states 'doze' und 'under_construction_pre' fallen weg. Alle Angebote die dort bisher sind werden in den state 'paused' versetzt. Vor deploy eine Liste mit den IDs dieser Angebote erstellen und mir per E-Mail schicken.
- [ ] Wechsel von 'completed' zu 'initialized' unmöglich mache (one way street).
- [ ] Neuen state 're-edit' erstellen. In diesem kann das Angebot bearbeitet werden. Man kann von 'completed' und 'disapprove' hinwechseln. Von 're-edit' kann man ausschließlich zu 'completed' wechseln.
- [ ] Es werden auf individueller Ebene 'Completed-Punkte' für den Wechsel von 'initialized' oder 'checkup_process' zu 'completed' vergeben. Für den Wechsel von 're-edit' zu 'completed' werden keine Punkte vergeben.
- [ ] Es werden auf individueller Ebene 'Approved-Punkte' für den Wechsel von 'approval_process' oder 'checkup_process' zu 'approved' oder 'seasonal_pending'
- [ ] Die Punkte werden nur vergeben, wenn ich die entsprechenden Button klicke und ich Teil eines bestimmten Teams meines Teams (z.B. zählt, wenn ich es in meiner Rolle des Teams 'Sprache' mache, aber nicht, wenn ich es in meiner Rolle des Teams 'Querschläger' mache nicht).
- [ ] Jeder Backenduser sieht in seinem Dashboard (oder einer speziellen Seite) seine absoluten Zahlen für das Jahr. Also z.B. 'Approved: 87, Completed: 113').
- [ ] Jeder Backenduser sieht in seinem Dashboard (oder einer speziellen Seite) zusätzlich seine Zahlen pro Woche (Tabellenansicht) für das Jahr (später kann er zwischen verschiedenen Jahren hin und her wechseln).
- [ ] Backenduser mit speziellen Rechten können Ziele für 'Completed-Punkte' und für 'Approved-Punkte für alle User anlegen.
- [ ]  Jeder Backenduser sieht in seinem Dashboard (oder einer speziellen Seite) einen Graphen in dem er zwei lineare Ziellinien für 'Approved-Punkte' und 'Completed-Punkte' hat. Dazu kommen dann Linien welchen den realen Fortschritt aufzeigen.
- [ ] Backenduser mit speziellen Rechten können Ziele für 'Completed-Punkte' und für 'Approved-Punkte für alle Teams anlegen.
- [ ] Es werden jedem Backenduser auf einer gesonderten Seite die Zahlen und Ziele für das Team angezeigt in dem er gerade unterwegs ist.
- [ ] Backenduser mit bestimmten Rechten können für für jeden dieser User gesondert ausgewählte Teams auch die Zahlen und Ziele aller anderen Mitglieder dieses Teams einsehen.

**Comment by Twiek** [comment]
Habe jetzt die verbleibenden Anforderungen in #1064 und #1065 ausgelagert.
