### ISSUE TITLE
Subscribe Link in Orga-Mail

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#872]
In den Orga-Mail soll auch eine Möglichkeit zum subscriben eingefügt werden. Mit folgendem Text: "PS Gerne informieren wir Sie, wenn mehr Ihrer Angebote online sind. Klicken Sie einfach hier (Subscribe-Link). Ansonsten erhalten sie keine Mails mehr von uns."

**Comment by Twiek** [comment]
Danach gibt es dann vierteljährige Follow-Up-Mails mit folgendem Inhalt: https://docs.google.com/document/d/1b4a-U05fD_m3UKDdglvwxqMyoSyD-P09WDuZVEmpWmI/edit#heading=h.4yn8kbvv7o9z.

Hier gilt: wenn Orga-Owner = Angebotsowner, dann wird nur der Angebotsowner informiert (im normalen wöchentlichen Anschreiben-Turnus).

**Comment by NilsVollmer** [comment]
Braucht noch Rücksprache (siehe Asana Task)

**Comment by NilsVollmer** [comment]
Update: ich habe gerade zusammen im Gespräch mit Laura beschlossen, dass die Follow-Up Mechanik Mails für Orga-Kontakt zwar vorbereitet (Link in Anschreiben & ab dann merken, für welche Angebote die Leute angeschrieben wurden) aber die Logik und das neue Anschreiben selbst erst später umgesetzt wird.

Gründe: 
1. die Anschreiben sollen bald eh nochmal alle überarbeitet werden und
2. können sich die bereits bestehenden Kontakte nicht nachträglich subscriben, also würde von den FollowUps nur zukünftige Mails profitieren und damit würden die erste FollowUps frühestens in 90+x Tagen verschickt. Bis dahin sollten die Überarbeitungen von Punkt 1. durchgeführt sein bzw. es gibt dann halt erst Orga-Follow-Ups wenn diese Überarbeitungen implementiert sind
