### ISSUE TITLE
utm-Tagging der Links in den Orgamailings

### ISSUE THREAD

**Issue by JulianJung** [clarat-org/clarat#873]
Um die Trafficquelle separat behandeln zu können bräuchten die Links in den Orgamailings ein utm-Tagging.
Die campaign soll "orga-mailing" heißen.
Falls man zwischen den verschiedenen Anschreiben unterscheiden kann bitte nochmal kurz bescheid geben.

**Comment by NilsVollmer** [comment]
Bitte priorisieren und sobald Eleonore sich in Asana wieder gemeldet hat, updaten.

**Comment by NilsVollmer** [comment]
Yep, ich habe das andere Ticket geschlossen. Das hier hat die aktuelleren Infos.

**Comment by NilsVollmer** [comment]
Wir wünschen uns die Parameter folgendermaßen: 

Medium=E-Mail
Source=Sendgrid
Campaign=Welt_Empfängertyp_Angebotsanzahl_Mailtyp

Ausgeschrieben natürlich viel zu lang, daher abgekürzt nach folgendem Schema:

**Welt**
R	(refugees)
F	(family)
FR	(Mix-Orga (Zwischenwelt oder beide))

**Empfängertyp**	
AO	(Angebotsowner)
GF	(Geschäftsführer)

**Angebotsanzahl**
E	(Eins)
EP	(Eins Plus)
FP	(Fünf Plus)

**Mailtyp**
OB	(Onboarding)
FU	(Follow Up)

**Comment by NilsVollmer** [comment]
Update: ist größtenteils fertig - wir (Laura, Eleonore & ich) müssen nur noch entscheiden, ob und wenn ja wie wir die utm-tags auch in der text-Version der Mail einbauen wollen, in der sieht ziemlich unschön aussehen.
