### ISSUE TITLE
Bug: ContactPersons werden doppelt zugeordnet.

### ISSUE THREAD

**Issue by NilsVollmer** [clarat-org/clarat#875]
Sehr einfach zu produzieren: bei einem Angebot per modaler View eine neue Kontaktperson hinzufügen (KontaktPerson speichern schließt das modale Fenster und die Kontaktperson ist korrekt mit dem Angebot verknüpft) und dann Speichern & Bearbeiten klicken. Die Kontaktperson ist dann doppelt mit dem Angebot verknüpft, es existiert also ein Duplikat in der Verknüpfungstabelle. 

Betrifft potentiell alle has_many through oder has_and_belongs_to_many associations. Allerdings scheint er nur bei der Erstellung eines verknüpften Modells aufzutreten - wenn eine bestehende Kontaktperson im modalen Fenster bearbeitet (und gespeichert) wird und man dann beim Angebot auf 'Speichern und bearbeiten' klickt, tritt der Bug nicht auf.

Vermutung: beim create wird die Erstellung des Verknüpfungseintrags irgendwo gecached und beim  'speichern & bearbeiten' wird sie dann nochmal erstellt?! 

UPDATE: der Umfang scheint sich noch in Grenzen zu halten: aktuell gibt es auf production 14 Fälle, bei denen es mehr als einmal den gleichen ContactPeopleOffer-Eintrag gibt.

UPDATE2: habe versucht einen Test dafür zu schreiben aber ich befürchte, dass wir die modalen Fenster nicht wirklich testen können.

@Twiek Was meinst du zu der Prio? Es scheint ja doch nicht so oft vorzukommen aber wenn dann ist es schon ungünstig weil es auch direkt falsch im Frontend auftaucht.
@KonstantinKo Ich bin gerade ein wenig out of Ideas - fällt dir etwas ein oder eher won't fix?

**Comment by KonstantinKo** [comment]
Hmm das ist scheinbar ein bug in rails_admin, nicht bei uns. Daher auch tendenziell nicht von uns fixbar. Vielleicht kann man eine uniqueness validierung schreiben, die solche duplikate verhindert? Dann würde es wahrscheinlich komische Fehler geben, aber immerhin taucht die Dopplung nicht mehr auf.
Ansonsten fällt mir dazu leider auch nicht viel mehr ein

**Comment by NilsVollmer** [comment]
Ja die Idee mit der uniqueness hatte ich auch schon, dachte mir aber auch, dass es dann Fehler geben könnte.. Könnte man ja mal ausprobieren. Ansonsten sieht es in der Tat sehr intern aus und ein wirklicher fix würde einiges an Zeit in Anspruch nehmen.
@Twiek What do you think??

**Comment by NilsVollmer** [comment]
Update: war gerade kurz vor dem Deploy aber dann schlug die TestSuite beim Erstellen eines neuen Angebots fehl. Nach längerem Suchen (manuellem Ausprobieren) war klar, dass die Validierungen bei neuen Einträgen wohl Probleme macht. Vermutlich weil da so ein rails_admin hack die Verknüpfungstabelle erstmal mit ID nil befüllt (Angebot existiert ja noch nicht, hat ergo noch keine ID) und dann später die richtige ID einträgt. Das Vorgehen macht natürlich sowohl mit presence:true als auch mit uniqueness Probleme.

Gott sei Dank scheint das Entfernen der offers-Zuordnung bei den Kontaktpersonen (was ja eh schon in dem Fix mit drin war) alleine den Bug auch schon zu beheben (lokal getestet). Ich habe mir nochmal von den Team-Leads versichern lassen, dass dieser Weg der Zuordnung nicht genutzt wird und werde das dann jetzt deployen.

**Comment by NilsVollmer** [comment]
Update 2: Als Bugfix aufgespielt, auf Production nochmal getestet (:D) => funktioniert und anschließend die 14 Angebote <-> ContactPeople mit Mehrfachverknüpfungen auf jeweils eine reduziert (Duplikate gelöscht). Somit erledigt :)
