### ISSUE TITLE
Teams

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#877]
Im Rahmen von Zuweisungen werden 'Teams' benötigt. Ein 'Team' ist als Verteiler zu verstehen und verfügt über die folgenden Eigenschaften:
- Ein Team hat einen Namen (string)
- Einem Team ist immer mindestens 1 User zugewiesen

**Comment by NilsVollmer** [comment]
Input aus Backend Meeting:
- Team-Verwaltung muss an Rollen & Rechte geknüpft sein

Related: User können wählen, im welchem Team (Bsp. Jens als Partner von Tandem XY oder als Randland) sie gerade im Backend aktiv sind. Daraus kann sich dann z.B. auch die Default-Auswahl für #879 ergeben.

Ansonsten hat @KonstantinKo schon viel auf dem aktuellen Statistik-Branch für dieses Ticket fertig, sodass man darauf aufbauen sollte. Das genaue Vorgehen sollten wir dann am Montag besprechen.

**Comment by NilsVollmer** [comment]
Das Modell existiert schon: UserTeams
