### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#879]
Tasks haben die folgenden Eigenschaften/Datenfelder:
- Freitext/Kommentare (text)
- Verantwortlicher (Verknüpfung mit Researcher oder Team)
- Status ('offen' oder 'erledigt')
- Beteiligte (ursprünglicher Verfasser + alle die jemals Verantwortlicher waren)

Die Beteiligten werden automatisch erstellt. Es ist für jeden möglich Beteiligte zu entfernen, es ist aber nicht möglich Beteiligte hinzuzufügen (nur indirekt indem man eine Person zum Verantwortlichen macht). Alle anderen Felder sind Pflichtfelder.

Auf ein Task kann beliebig oft von jeder Person kommentiert werden (text). Es ist sowohl für den initialen Freitext als auch für jedes Kommentar/Antwort erkenntlich wer diesen verfasst hat. Hierbei kann der Verfasser wählen ob er als Einzelperson oder als Teil eines Team antwortet, also z.B. 'Peter' oder 'Peter - Randland'. Default ist die Einzelperson, kann aber per Dropdown geändert werden. Es stehen nur die Teams zur Auswahl den man zugeordnet wurde (Grund: Es gibt sonst keine Möglichkeit indirekt herauszufinden wer eigentlich für die Organisation/Abteilung zuständig ist).

Es gibt 2 verschiedene Arten von Tasks:
1.  Meta-Tasks
   Diese Tasks sind einen kompletten Objekt (z.B. Angebot) zugeordnet. Pro Objekt kann es immer nur ein 'offenes' Meta-Task geben. Wird ein Meta-Taks zugewiesen so muss auch das gesamte Objekt der gleichen Person zugewiesen werden. Es gibt jedoch 2 Ausnahmen: Organisationen und Abteilungen. Hier kann das Meta-Task einer anderen Person/Team zugewiesen werden als die Organisation/Abteilung selber.

![bildschirmfoto 2016-08-08 um 14 02 51](https://cloud.githubusercontent.com/assets/432388/17479151/0789acf2-5d71-11e6-943b-7daecfa757fe.png)
1. Datenfeld-Tasks
   Diese Tasks sind einzelnen Datenfeldern eines Objektes zugewiesen, also z.B. der Description eines Angebots. Jedes Datenfeld kann maximal ein 'offenes' Datenfeld-Task zugewiesen sein.  

![bildschirmfoto 2016-08-08 um 14 20 45](https://cloud.githubusercontent.com/assets/432388/17479542/5d80a73a-5d73-11e6-965e-203585bc95cf.png)

**Comment by NilsVollmer** [comment]
Input aus Backend Meeting:
- Brauchen wir Beteiligte?
- Wenn ja, dann müssen diese Task anders angezeigt werden (nicht auf gleicher Wichtigkeitsebene wie Zuweisungen)

**Comment by Twiek** [comment]
Läuft jetzt #878.
