### ISSUE TITLE
'Automated Translations!' für Datenschutzhinweise etc. anders anzeigen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#881]
http://www.clarat.org/refugees/datenschutzhinweise
http://www.clarat.org/refugees/rechtliche-hinweise und
http://www.clarat.org/refugees/impressum werden nicht übersetzt. Daher sollte hier im Header neben dem Warndreieck auch nicht z.B. 'Automated translations!' stehen, sondern die Übersetzung von 'Rechtstexte kannst du bei uns nur auf Deutsch lesen.'. Bitte entsprechend einrichten (Übersetzungen fordern wir dann über Localeapp an).

**Comment by NilsVollmer** [comment]
Da eher frontend-only ist @marcus-herrmann besser dafür geeignet.

**Comment by Twiek** [comment]
Schaue mir auch das Wording noch einmal an. Es sind ja eigentlich keine 'Gesetzestexte' im engeren Sinn.

**Comment by KonstantinKo** [comment]
String-Ersetzung erfolgt

**Comment by marcus-herrmann** [comment]
Erledigt durch Konstantin auf: https://github.com/clarat-org/clarat/tree/feature/881-german-content-warning
