### ISSUE TITLE
Invisible locations werden auf der Orga-Übersichtsseite angezeigt

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#882]
Invisible locations werden auf der Orga-Übersichtsseite angezeigt.
siehe hier: http://www.clarat.org/refugees/organisationen/start-with-a-friend-e-v
Obwohl Location invisible: http://claradmin.herokuapp.com/admin/location/2321.

Gilt somit auch für Angebote deren Location wir sehr bewusst nicht öffentlich machen wollen.

**Comment by NilsVollmer** [comment]
Fix deployed.
