### ISSUE TITLE
'Mehr Sprachen zeigen' klickbarer aussehen lassen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#884]
Interner Link: https://app.asana.com/0/48434740552087/167627385418580

Ne Idee wie man den 'Mehr Sprachen zeigen' Balken eher aussehen lassen kann wie ein Link? Eventuell doch keinen Balken? Gab dazu kritische Anmerkungen und umso länger ich drüber nachdenke umso kritischer sehe ich das.

![screenshot 2016-08-15 at 17 33 16](https://cloud.githubusercontent.com/assets/432388/17737468/8959fade-648d-11e6-83b4-9eaacf067166.png)

Falls Du das für unproblematisch hältst (bisher gibts nur Anekdoten zum Thema), let me know as well.

**Comment by marcus-herrmann** [comment]
Würde ein Pfeil nach unten (als Aufklappaufforderung) bzw. ein Pfeil nach oben (als Einklappaufforderung), bzw. Plus und Minus schon Abhilfe schaffen oder soll es noch mal deutlich anders gedacht werden?

**Comment by Twiek** [comment]
Denke das sollte ausreichen. Please show me.

**Comment by marcus-herrmann** [comment]
Hier erstmal die Pfeile:

<img width="387" alt="bildschirmfoto 2016-08-25 um 10 47 11" src="https://cloud.githubusercontent.com/assets/505181/17962543/b90ccda4-6ab1-11e6-96ec-b34a036324c2.png">
<img width="375" alt="bildschirmfoto 2016-08-25 um 10 47 20" src="https://cloud.githubusercontent.com/assets/505181/17962544/b91595d8-6ab1-11e6-8533-80e98fa959e5.png">

Hier auch auscheckbar: https://github.com/clarat-org/clarat/tree/feature/884-make-more-languages-great-again

**Comment by MichiBecker** [comment]
Hallo Markus,

Julian und ich haben gerade im IT Meeting die Pfeile auf uns wirken lassen :)

Die sind uns zu kleinteilig und es ist irgendwie ungewohnt, dass die auf beiden Seiten des Balkens sind.

Unser Vorschlag: Kannst du ausprobieren, einen breiteren Pfeil (Dreieck) mittig unter "Mehr Sprachen anzeigen" zu packen?

Danke

**Comment by marcus-herrmann** [comment]
> Unser Vorschlag: Kannst du ausprobieren, einen breiteren Pfeil (Dreieck) mittig unter "Mehr Sprachen anzeigen" zu packen?

Verständnisfrage: "Mittig unter" im Sinne von, dass dann der Button deutlich höher wird (Zeile 1: Text, Zeile 2: Button-Dreieck)?

**Comment by MichiBecker** [comment]
ja.

Wir hatten bisher noch keinen "Balken/Button" unten oder? Dann wäre die Höhe ja auch noch "flexibel".

Aber du kannst auch eine Alternative machen mit Pfeil nur rechts und dann schauen wir was besser aussieht?

**Comment by marcus-herrmann** [comment]
<img width="397" alt="bildschirmfoto 2016-09-01 um 14 52 07" src="https://cloud.githubusercontent.com/assets/505181/18168004/e11146f2-7053-11e6-9b31-00925ce0e3cf.png">

**Comment by MichiBecker** [comment]
schade, ich dachte das sieht besser aus ;)

http://cameronbourke.github.io/react-cardstack/

Ich glaube, es sieht besser aus, wenn man den Pfeil am Text andockt wie im Beispiel und dann den ganzen Text inkl. Pfeil mittig ausrichtet. 

Was meinst du?

**Comment by marcus-herrmann** [comment]
Sieht auf jeden Fall besser aus:

<img width="477" alt="bildschirmfoto 2016-09-21 um 16 31 57" src="https://cloud.githubusercontent.com/assets/505181/18715264/f668e0f8-8018-11e6-8237-18966a9ef080.png">

**Comment by MichiBecker** [comment]
gefällt mir! nehmen wir so @Twiek ?

**Comment by Twiek** [comment]
Yo!

**Comment by marcus-herrmann** [comment]
Code merged, Ticket kann zu
