### ISSUE TITLE
'Statistics' Link im Header des neuen Backend herausnehmen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#885]
Zugriff dann nur noch über direkten Link. Perspektivisch sollen nur ausgewählte User Zugriff auf die Statistiken haben. Vorerst Anne, Nicole und die IT.

**Comment by NilsVollmer** [comment]
Als Hotfix direkt auf master umgesetzt & deployed. Für die Umsetzung mit Nutzerrollen dann am besten ein neues Issue erstellen bzw. die Anforderung zu einem related Issue (Statistiken?) hinzufügen.
