### ISSUE TITLE
'Mehr' Link in den Autovervollständigungssuchergebnissen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#89]
Unter den Suchergebnissen im Rahmen der Autovervollständigung (siehe Screenshot) den abgetrennten Link/Text "Alle Suchergebnisse für 'droge'" anzeigen. 'droge' ist dabei identisch mit dem was man aktuell eingetippt hat und in einfachen Anführungsstrichen und kursiv. Klickt man darauf, so passiert das Gleiche als würde man in dem Moment Return drücken

![bildschirmfoto 2015-01-07 um 17 48 33](https://cloud.githubusercontent.com/assets/432388/5649418/ef76145a-9695-11e4-8920-56e2eed12673.png)

**Comment by Twiek** [comment]
@KonstantinKo: Kriegt man hier mit überschaubarem Aufwand auch die Anzahl der Suchergebnisse rein? In dem Fall dann bitte den Text ändern in "'Alle X Ergebnisse für 'xxx'".

**Comment by marcus-herrmann** [comment]
Frage ging nicht an mich, aber ich fürchte das wäre noch ein Ajax-Call mehr, und noch mehr gefühlte Latenz.

**Comment by Twiek** [comment]
Kann man die Latenz irgendwie objektiv messen?

**Comment by marcus-herrmann** [comment]
Nicht dass ich wüsste, müssten wir erstmal ausprobieren. Erstmal Bauchgefühl.

**Comment by KonstantinKo** [comment]
Geht auch ohne zweite Anfrage. Keine zusätzliche Latenz.
