### ISSUE TITLE
Farsi integrieren

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#890]
- [x] Möglichkeit einrichten im Backend schon mit den Übersetzungen zu beginnen (Localeapp, Kategorien... s.u.) im Frontend aber noch nichts anzuzeigen.
- [x] Bei Localeapp Farsi ('fa = Persian') hinzufügen
- [x] Headerleiste anpassen. Neue Reihenfolge: Deutsch, Englisch, Arabisch, Farsi, Türkisch, Polnisch, Russisch, Französisch
- [x] Farsi bei Kategorien und Next-Steps nicht von Gengo sondern manuell übersetzen lassen (analog zu Deutsch und Englisch)
- [x] Farsi bei den Offer- und Organization-Translations hinzufügen (inkl. Verlinkung aus dem alten Backend)

**Comment by NilsVollmer** [comment]
TODO für Freitag (Bewerbungsgespräche am Montag): 

- [ ] Farsi im Backend auf staging deployen

**Comment by NilsVollmer** [comment]
Deploy-TODO:
``` console
    OfferTranslation.pluck(:offer_id).uniq.each do |id|
      TranslationGenerationWorker.perform_async(:fa, 'Offer', id, :all)
    end

    OrganizationTranslation.pluck(:organization_id).uniq.each do |id|
      TranslationGenerationWorker.perform_async(:fa, 'Organization', id, :all)
    end
```

**Comment by NilsVollmer** [comment]
Für den Test auf Staging (im Kontext der Bewerbungsgespräche) ist alles umgesetzt und aufgespielt. Die restlichen Kleinigkeiten folgen dann später.

**Comment by NilsVollmer** [comment]
Update: Backend deployed
