### ISSUE TITLE
Target=_blank Links öffnen im neuen und im ursprünglichen Tab

### ISSUE THREAD

**Issue by NilsVollmer** [clarat-org/clarat#899]
Sie sollen sich natürlich nur im neuen Tab öffnen und den ursprungs-Tab nicht verändert.

**Comment by NilsVollmer** [comment]
Fix auf master umgesetzt und deployed.

@marcus-herrmann : welchen Grund gab es für den hitCallback bzw. wurde durch den Fix etwas anderes kaputt gemacht?

**Comment by marcus-herrmann** [comment]
Antwort auf beide Fragen: #862

Code ist so, inkl. hitCallback von Google übernommen: https://support.google.com/analytics/answer/1136920?hl=de

**Comment by marcus-herrmann** [comment]
Fix müsste folgendermaßen sein:

```
'hitCallback': ->
   newTab = window.open url, '_blank'
   newTab.focus()
   return
```

**Comment by NilsVollmer** [comment]
Aber würde das nicht 1. jeden Link auf unserer Seite zu einem new-tab-Link machen? und 2. Dann nicht sogar zwei neues Tabs für target=_blank-Links öffnen?

Ist es denn ohne den hitCallback überhaupt ein Problem? Das Browser-Verhalten ist so zumindest korrekt.. es kann nur sein, dass der GA-Code jetzt nicht funktioniert. Ist das so?

**Comment by marcus-herrmann** [comment]
Nur die externen, aber mit dem 2x hast du wahrscheinlich recht. 

Ob das GA-Custom-Event-Empfangen klappt kann ich nicht ohne GA-Zugang beurteilen. Laut Doku ist der Callback aber optional: https://developers.google.com/analytics/devguides/collection/analyticsjs/field-reference#hitCallback

**Comment by NilsVollmer** [comment]
@marcus-herrmann Da ich morgen nicht da bin, bitte kurz mit Konstantin besprechen, ob der aktuelle Hotfix (Callback entfernt) Probleme machen könnte.

**Comment by marcus-herrmann** [comment]
Auch seit dem Hotfix laufen noch Ergebnisse zu "Outbound"-Events in Google Analytics ein, und das Callback ist optional, insofern problemlos.
