### ISSUE TITLE
Staging Konzept umsetzen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#90]

**Comment by Twiek** [comment]
Weiterer Server von Anne genehmigt.

**Comment by KonstantinKo** [comment]
Production-DB ist gerade auf staging gespiegelt. Um das wieder zu aktualisieren, folgenden Befehl eingeben:
`heroku pgbackups:transfer HEROKU_POSTGRESQL_GREEN clarat-staging::HEROKU_POSTGRESQL_COPPER --app clarat`
