### ISSUE TITLE
301-Redirect für geänderte Routen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#902]
Damit Google endlich damit klar kommt, dass unter der alten URL (insbesondere französische) nichts mehr zu finden ist.

**Comment by NilsVollmer** [comment]
@KonstantinKo ich bin da gerade ein wenig lost, wie wir es (mit dem route_translator) hinkriegen, für nur eine Sprache (Französisch) einen redirect von einer alten zu der aktuellen Routen-Übersetzung zu schalten.

**Comment by KonstantinKo** [comment]
Ich fürchte das bekommen wir mit route translator nicht gut/sauber hin. Es wird einen Eintrag in route.rb mit dem alten französischen namespace geben müssen der dann auf eine forward action verweist. Hoffentlich reicht es wenn wir den temporär reinnehmen bis google es rafft, dass die Seiten an einem neuen Ort sind.
