### ISSUE TITLE
Timeout auf 4 Stunden erhöhen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#904]
Anfrage von den Researchern die damit scheinbar trotz 120 Minuten nen Problem mit haben. Wenn es außer den für unseren Usecase weniger relevanten Security-Issues keine Bedenken gibt bitte auch 240 Minuten erhöhen.

**Comment by KonstantinKo** [comment]
Einzeiler; direkt auf develop (3c844bf)
