### ISSUE TITLE
Crawler erweitern 

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#905]
Auch Seiten die zwar theoretisch erreichbar sind, aber bei denen im Browser nur ein Warnhinweis kommt (z.B. Sicherheitszertifikat abgelaufen) sollten behandelt werden als gebe es einen Serverfehler (bei der roten Karte geht das Angebot offline). Für den User ist das ja tendenziell noch verstörender als wenn die Seite gar nicht aufgerufen werden kann.

<img width="1279" alt="bildschirmfoto 2016-09-07 um 17 09 29" src="https://cloud.githubusercontent.com/assets/432388/18317339/12af253e-751e-11e6-8c83-0c619dbae96b.png">

**Comment by NilsVollmer** [comment]
Es gibt immer nur einen generellen SSL-Error. Im Einzelfall kann es sein, dass die Seite trotzdem erreichbar ist (nicht wie bei dem Screenshot oben). Wir fangen erst einmal alles ab und gucken dann, ob es da problematische Fälle gibt.
