### ISSUE TITLE
Zu viele locales?

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#909]
Sind hier versehentlich zu viele Locales entstanden?

![bildschirmfoto 2016-09-08 um 15 25 11](https://cloud.githubusercontent.com/assets/432388/18350958/8c10645a-75d8-11e6-9f2e-c2732aa4f461.png)

Bei Bedarf mit @marcus-herrmann Rücksprache halten

**Comment by Twiek** [comment]
@marcus-herrmann Sprich bitte mal Nils drauf an.

**Comment by NilsVollmer** [comment]
Update: die unnötigen Einträge sind gelöscht.
