### ISSUE TITLE
Angebotsnamen und Organisationsnamen in title tag aufnehmen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#91]

**Comment by Twiek** [comment]
@KonstantinKo: Bitte checken https://github.com/clarat-org/clarat/commit/06277dec063e0da5f7b4928b2c9f67946f85483a ob das aus Deiner Sicht passt.

**Comment by KonstantinKo** [comment]
@Twiek Ist gut soweit, nur i18n könnte besser sein. Aber dafür müssen wir uns wohl ohnehin mal Zeit nehmen und die ganzen Strings lokalisieren.
