### ISSUE TITLE
Translation Pending State

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#912]
Wenn ein Researcher künftig ein Refugees Angebot 'freischaltet' soll es nicht automatisch für Externe sichtbar sein. Es wechselt in den State 'translation_pending'. Sobald alle manuell möglichen OfferTranslations bearbeitet wurden wechselt das Angebot automatisch in den Status 'approved' und ist auch für externe User sichtbar.

**Comment by NilsVollmer** [comment]
Pending: noch einmal mit Sprache diskutieren.

**Comment by NilsVollmer** [comment]
@Twiek Wenn die aktuell besprochene Übergangslösung von Sprache abgenickt wurde, kann dieses Ticket hier wohl zu. Einen State auf Offer-Ebene soll es ja nicht geben und für die finale Umsetzung mit Zuweisungen sollten wir ein neues Ticket aufmachen.
