### ISSUE TITLE
Über Uns Texte updaten

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#914]
Siehe https://docs.google.com/document/d/133EjHttAjvINU7umaKu_wPp3cYvo2TfgXy449vPvO_w/edit

**Comment by NilsVollmer** [comment]
Soweit fertig es fehlt nur noch das ausgewählte Bild von Jacinta (angeschrieben) und die Texte müssen dann irgendwann noch in die anderen Sprachen übersetzt werden.

**Comment by NilsVollmer** [comment]
Ist soweit fertig aber die Übersetzungen für die ganzen Texte fehlen natürlich noch. Wenn wir es so schon aufspielen möchten, sollten wir zumindest Englisch fix nachziehen (haben wir jetzt ja inhouse). Ist also bis auf localeapp-Übersetzungen und anschließendem Localeapp-pull fertig.
