### ISSUE TITLE
Definition von 'Großen Orgas' erweitern (für die automatisierten Anschreiben)

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#916]
Wenn folgende Worte im Orga-Titel sind soll es automatisch eine große Orga sein: Deutschland, Bund, Deutscher, Bundes, international, internationale,  Arbeitsgemeinschaft, Verband, Verbund.

**Comment by NilsVollmer** [comment]
Als mini-feature direkt auf develop umgesetzt.
