### ISSUE TITLE
Laden der Suchergebnisseite ist langsam

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#918]
Wenn man erstmal drauf ist geht es schnell, aber erstmalig dauert es (oder beim Reload). Please investigate!

**Comment by NilsVollmer** [comment]
Marcus und ich haben da schon mal ein wenig investigated und haben akut den chat unter Verdacht, der relativ lange (mehrere Sekunden) hohe Auslastungen produziert und da er selbst in Javascript läuft, anscheinend unser JavaScript der Suche ausbremst. Auf allen anderen Seiten macht er das auch, bremst aber unsere Seite nicht aus. Als wir ihn testweise rausgenommen hatten, lief es auch direkt deutlich schneller.

Am besten sollte der Chat auf der Suchergebnis-Seite erst geladen werden, wenn unser Such-Script fertig ist.

**Comment by Twiek** [comment]
Relevant: https://developers.google.com/speed/pagespeed/insights/?hl=de&url=clarat.org&tab=mobile

Mobile 63/100 "Behebung erforderlich"
Desktop 84/100 "Behebung empfohlen"

**Comment by Twiek** [comment]
Ist inzwischen wirklich fast unerträglich langsam und kommt auch schon als Bugreport an. Insofern dringend optimieren und gerne auch den Chat so lange rausschmeißen bis wir ihn so einbauen können, dass er uns nicht derartig bremst.

**Comment by KonstantinKo** [comment]
OK habe das Laden des Chats verzögert und zusätzlich das Kateogrie-JSON cachen lassen. Ist auch schon als hotfix deployed. Scheint für mich auch schneller zu gehen.
PS: Der obige pagespeed Link überprüft gar nicht die Suchergebnisseite. Das wäre [der hier](https://developers.google.com/speed/pagespeed/insights/?hl=de&url=https%3A%2F%2Fwww.clarat.org%2Frefugees%2Fangebote&tab=mobile).

**Comment by NilsVollmer** [comment]
Der böse Kategoriebaum.. aber die Geschwindigkeit ist jetzt echt awesome :)
