### ISSUE TITLE
Angebotsübersicht auf Orgaseiten teilweise kaputt

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#921]
<img width="932" alt="bildschirmfoto 2016-09-23 um 12 03 33" src="https://cloud.githubusercontent.com/assets/432388/18782263/dc63e72a-8185-11e6-909a-5394541e4947.png">

https://www.clarat.org/refugees/organisationen/freie-universitaet-berlin

Scheint daran zu liegen, dass es Online- oder Telefonangebote sind die keine Adresse haben. Könnte man die ohnehin getrennt mit eigener Überschrift ('Telefonberatungen und Onlineangebote') anzeigen?

**Comment by marcus-herrmann** [comment]
Damn. Fake-Daten waren zu unterkomplex, sodass mir das nicht aufgefallen ist. Auf dem Fix-Branch https://github.com/clarat-org/clarat/tree/fix/921-offer-listings-on-orga-enhanced liegt ein vermuteter erste Hilfe-Fix (wollte keinen Hotfix auf develop machen).

Für die Trennung nach encounter müsste m.E.n. der Controller angepasst werden - der loopt aktuell nur durch die Welten, aber darin nicht noch mal durch die Offer-Arten.

**Comment by Twiek** [comment]
Leider noch immer fehlerhaft:

![bildschirmfoto 2017-03-02 um 13 55 32](https://cloud.githubusercontent.com/assets/432388/23508059/cee762f8-ff47-11e6-94ff-3d44bb5e95d9.png)



https://staging.clarat.org/refugees/organisationen/freie-universitaet-berlin

**Comment by marcus-herrmann** [comment]
Keine Ahnung, was da auf Staging für ein alter Branch eingespielt ist (da ist sogar noch die alte Welt-Navigation). Auf Production tritt der Fehler nicht auf: https://www.clarat.org/refugees/organisationen/freie-universitaet-berlin

**Comment by Twiek** [comment]
Aber der branch wurde nie gemerged, oder? So oder so soll es mir ja recht sein, wenn sich das Problem in Wohlgefallen aufgelöst hat.

**Comment by marcus-herrmann** [comment]
Wenn Auflösung in Wohlgefallen, kann Ticket zu, oder?
