### ISSUE TITLE
Organisationen bei Kooperationsangeboten alphabetisch sortieren

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#922]
Z.B. hier: https://www.clarat.org/refugees/angebote/unv-einblick-in-ein-biowissenschaften-studium-an-einer-universitaet-fuer-fluechtlinge-mit-schulabschluss

<img width="344" alt="bildschirmfoto 2016-09-23 um 12 14 13" src="https://cloud.githubusercontent.com/assets/432388/18782534/45627c68-8187-11e6-9a7c-2ff258bf304e.png">

**Comment by marcus-herrmann** [comment]
@KonstantinKo reicht hier ein `.order('name ASC')` oder ist das wegen I18n komplexer (wie ja auch ein Stück weiter oben, wo es eine extra Controller-Methode zum alphabetisch ordnen gibt)?

**Comment by KonstantinKo** [comment]
Da Organamen nicht übersetzt werden hat auch einfach ein `order(:name)` gereicht
