### ISSUE TITLE
Neue Sprachen anlegen

### ISSUE THREAD

**Issue by MichiBecker** [clarat-org/clarat#926]
Bitte folgende 4 Sprachen anlegen:

Bambara
ISO 639-2: bam
Eigenbezeichnung: bamanankan 

Dioula
ISO 639-2: dyu
Eigenbezeichnung: julakan 

Slowenisch
ISO 639-2: slv
Eigenbezeichnung: slovenščina

Malinke
ISO 639-2:man
Eigenbezeichnung: Maninka

**Comment by NilsVollmer** [comment]
@MichiBecker Bitte jeweils noch die deutsche Bezeichnung hinzufügen ;)

**Comment by MichiBecker** [comment]
@NilsVollmer erledigt 💃
