### ISSUE TITLE
Interne Statistiken

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#93]
In einem Bereich der nur ausgewählten Admins zugänglich ist (kann hardgecodet werden, wird sich selten ändern).

Hier soll es eine Übersicht für jeden anderen Admin geben wie viele Angebote dieser im Zeitverlauf created und wie viele er approved hat. 

Falls möglich sollen hier bestimme Admin nicht angezeigt werden die ohnehin keine Angebote bearbeiten (kann auch hardgecodet werden).

**Comment by Twiek** [comment]
Die Researcher sollten zumindest die kumulierten Statistiken anschauen.

**Comment by KonstantinKo** [comment]
Letzter Zusatz nicht ausgeführt da im Moment zu hoher Aufwand. Falls doch gewünscht, bitte als neues Issue öffnen.
