### ISSUE TITLE
Umbau des Headers in mobiler Ansicht

### ISSUE THREAD

**Issue by marcus-herrmann** [clarat-org/clarat#930]
https://share.sketch.cloud/5bpp/p/search-results-mobile

**Comment by marcus-herrmann** [comment]
Note to self: german_content_warning muss ebenfalls in ein "qTip"

**Comment by marcus-herrmann** [comment]
Hi @NilsVollmer ,

wie letzte Woche besprochen - ich habe die locale-app-Begegnung maximal lange herausgezögert und erstmal mit festen deutschen Strings auf https://github.com/clarat-org/clarat/tree/feature/930-rebuilding-mobile-header gearbeitet.Mit dem Suchbegiff `TodoBeforePR` findest du die Stellen, die einerseits i18n, häufig aber auch echte Routes/link_to's und in einem Fall einge Logikabfrage brauchen.

Ich weiß jetzt nicht ganz genau, wann Konstantin wieder da ist, aber sobald du fertig bist, würde ich dich bitten dieses Ticket direkt ihm zuzuweisen.

@KonstantinKo - Situation ist folgende: Teil dieses Tickets ist das eigentlich trivial erscheinende "Umpositionieren" des sort_by-selects: Auf Desktop ist das in der Nähe der Listing-Results, und mobile halt im Off Canvas Container. Nun ist es so, und ich habe mich die letzten Stunden daran erfolglos festgebissen, dass bei der Interaktion mit dem Select es sich, sobald onchange event, selbst klont und noch mal unter dem Element, das "changed" wurde platziert, sodass mit jeder Interaktion ein neues Select "sort_by" im Off Canvas Container erscheint. Mein Script (handle_mobile_layout) kann das allerdings nicht sein, da ich das select nicht klone, sondern immer nur verschiebe. Und selbst wenn: Der Bug appended den Selekt-Klon immer wieder, ich benutze im Verschiebeprozess aber nur prepend. Bin ratlos.

Wenn diese 2 Probleme gelöst sind, ist dieses Feature allein immer noch nicht deploy-bereit, bitte wieder mir zuweisen. Ich muss das dann mit #836  und #931 zusammenführen, da sich Dinge überschneiden.

**Comment by KonstantinKo** [comment]
@NilsVollmer Bitte mir keine "In Progress" Tickets zuschieben, erst in TODO setzen.

**Comment by KonstantinKo** [comment]
Ist auf feature/836-new-offer-index funktionell umgesetzt

**Comment by marcus-herrmann** [comment]
Note to self: 836 und 930 zusammengeführt in #931

**Comment by marcus-herrmann** [comment]
Kann demnach zu, sobald #931 komplett

**Comment by marcus-herrmann** [comment]
Mit dem stattgefunden Deploy von #931 hinfällig
