### ISSUE TITLE
Generische Create & Edit Views

### ISSUE THREAD

**Issue by NilsVollmer** [clarat-org/clarat#935]
Im neuen Backend soll es jeweils einen generischen New und Create View geben, die für jedes Modell verwendet werden können. Alle vorhandenen Felder sollen füll- und speicherbar sein. 
- [ ] generic Create View
- [ ] generic Edit View

**Comment by Twiek** [comment]
Bitte noch mal checken was aktuell noch fehlt.

**Comment by Twiek** [comment]
Implizit Teil anderer Issues.
