### ISSUE TITLE
Statistik reloaded

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#94]
Die Statistik soll wahlweise für das laufende Kalenderjahr oder 'all time' angezeigt werden können (nice to have: 'die letzten 52 Wochen' als dritte Option).

**Comment by KonstantinKo** [comment]
bis jetzt nur all time

**Comment by Twiek** [comment]
Schaut gut aus. Falls möglich aber auch allen 'researchern' Zugang zu den kumulierten Statistiken geben.

**Comment by Twiek** [comment]
Ok, reicht vorerst. Gegen Ende des Jahres müssen wir uns das aber sicherlich noch mal anschauen (irgendwann wirds halt unübersichtlich).
