### ISSUE TITLE
Refugees target_audience erweitern

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#941]
Bitte die in folgender Tabelle benannten Target Audiences anlegen. Im Anschluss dann bitte wie im Tabellenblatt "rückwirkende Anpassungen" notiert, Angeboten mit den alten TAs die neuen TAs zuordnen. Die Target Audiences sollen zudem um folgende Aufenthaltsstatus ergänzt werden können (separate Abfrage) :
- vor dem Asylantrag
- im Asylverfahren
- mit Aufenthaltserlaubnis
- mit Duldung
- mit Abschiebebescheid

in der Anzeige des Target Audience Stamps sollen diese Aufenthaltsstatus jeweils ganz am Ende des Stamps erscheinen.
Bsp.:
für geflüchtete Mütter (18-27 Jahre) mit Duldung
für geflüchtete Eltern von Söhnen (6-12 Jahre) mit Aufenthaltserlaubnis
für geflüchtete werdende Eltern vor dem Asylantrag

https://docs.google.com/spreadsheets/d/1aHC2HqwOl2b41EHQN0MtSyERxfViAHaEpG719RyH8h0/

Komplettes Konzept: https://docs.google.com/document/d/1ddv3F1pHJwa_QVVZJRsVirNQ9fYJp5Y0IwbtIOFQ77k/edit#heading=h.12tok9m9203q

**Comment by JulianJung** [comment]
@Twiek habe dein Eingangscomment wie gewünscht kommentiert, es kann hier jetzt weitergehen.
Eine neue Version brauchen wir meines Achtens nicht, da sich die alten TAs komplett ersetzen lassen.

**Comment by Twiek** [comment]
Ok, go ahead. Fokus auf jeden Fall auf die Eingabe im Backend. Bei Unklarheiten einfach fragen (mich oder in Abwesenheit Elisa).

**Comment by NilsVollmer** [comment]
@Twiek / @JulianJung Für das Zusammensetzen des Stamps wenn ein Status vorhanden ist, müssen wir uns unbedingt noch Feedback von Sprache abholen, denn ich glaube nicht, dass dieses 'einfach hinten dran hängen' in allen Sprachen (vor allem Arabisch & Farsi) so funktioniert. Diesen Prozess bitte jetzt schonmal anstoßen damit wir da so schnell es geht eine Lösung finden können.

**Comment by NilsVollmer** [comment]
Update: Logik ist grundsätzlich fertig aber es gibt noch ein paar Dinge abzuklären - dafür schnappe ich mir morgen am besten den @JulianJung .

Ausserdem werden wir noch einige neue Übersetzungen in localeapp (aktuell 31 aber wahrscheinlich noch mehr) brauchen - dafür brauchen wir auch eine Lösung.

**Comment by NilsVollmer** [comment]
TODO
- [ ] Grundsätzliche Logik
- [ ] Tests
- [ ] Localeapp anpassen
- [ ] Localeapp aufräumen (alte Dinge löschen)
- [ ] Formatierung in anderen Sprachen abklären

**Comment by NilsVollmer** [comment]
@JulianJung Eine Herausforderung ist noch die Länge des Stamps.. ich habe hier mal beispielhaft einen eingefügt:

![image](https://cloud.githubusercontent.com/assets/1733220/22430145/69239bbe-e70d-11e6-881e-95b5c4d21856.png)

**Comment by Twiek** [comment]
Sieht wirklich nicht hübsch aus... Eventuell sollte man den Abstand zum Standort noch etwas erhöhen und den Zeilenabstand reduzieren. Könntest Du noch mal Screenshot posten indem Auch der Standort zweizeilig ist.

**Comment by NilsVollmer** [comment]
Here you go: 

![image](https://cloud.githubusercontent.com/assets/1733220/22457064/19320f08-e796-11e6-9c14-61a065c3acd7.png)

**Comment by MichiBecker** [comment]
aloha,

ginge es, einen gezwungenen Umbruch nach "...Flüchtling" zu machen? aber nur in bestimmten Fällen?

Und Zeilenabstand anpassen an den Zeilenabstand der Adresse.

Wenn das mit dem schöneren Umbruch nicht geht: ist da noch Luft, die Adresse weiter nach rechts zu schieben?

Ich such mal einen laaaaaangen Orga.-Titel

**Comment by NilsVollmer** [comment]
Also feste Zeilenumbrüche in Ausnahmefällen (:P) sind da nicht so zielführend, denke ich ;)

Da es vor allem ein Frontend Issue ist, besprechen wir das morgen mit @marcus-herrmann 

Aber such gerne einen lange Orga-Titel raus, damit wir morgen worst-case Daten haben.

**Comment by MichiBecker** [comment]
Hier ist ein 2-zeiliger Orga Name. Wenn wir da eh Platz haben für 2 Zeilen Orga-Name, könnte man auch das ganze mehr nach rechts schieben. Was meint ihr?

![screenshot 2017-02-01 at 12 23 41](https://cloud.githubusercontent.com/assets/20815293/22504992/4ebf3450-e879-11e6-9505-4a32cfb6d028.png)

**Comment by KonstantinKo** [comment]
Bedenke bitte, dass Designvorschläge auch auf allen möglichen Browser-Breiten funktionieren müssen, nicht nur auf dem aktuell benutzten Bildschirm. Was da zeizeilig ist, ist unter Umständen auch dreizeilig (und wird mit Verschiebung mehr oder weniger)

**Comment by MichiBecker** [comment]
Hier der lange Orga-Name auf iPad Hochformat.

![screenshot 2017-02-01 at 12 32 46](https://cloud.githubusercontent.com/assets/20815293/22505219/90f5ae84-e87a-11e6-8304-5854545af798.png)

**Comment by Twiek** [comment]
@marcus-herrmann Sprich mit da bitte morgen mal drauf an.

**Comment by marcus-herrmann** [comment]
Bezüglich Umbrüche: Es gibt "geschützte Leerzeichen", bzw. präziser "Non breaking spaces" als Sonderzeichen, die man in HTML einfügen und damit die Umbruchlogik etwas modifizieren kann.

Um die "Fussball spielen - Roma"-Situation zu vermeiden, könnte man den TA String folgendermaßen machen: 

```
für geflüchtete Kinder (8&nbsp;–14&nbsp;Jahren)
```

Ihr müsst entscheiden, ob das für die Übersetzer praktikabel ist. 

[Typographienerd]
Wenn ihr gerade dabei seid, bitte den <a href="https://de.wikipedia.org/wiki/Halbgeviertstrich#Bis-Strich">Halbgeviertstrich</a> für die X bis Y-Angabe nutzen ;)
[/Typographienerd]

**Comment by marcus-herrmann** [comment]
Ist jetzt auf dem Feature-Branch zu #941 entsprechend dem Bild oben umgesetzt

**Comment by NilsVollmer** [comment]
Staging-Screenshot mit überarbeitetem Stamp:

![image](https://cloud.githubusercontent.com/assets/1733220/22931854/7bef5ae8-f2c6-11e6-88bf-4624a11de939.png)
