### ISSUE TITLE
'Pausieren' Button nicht mehr anzeigen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#942]
Wechsel in der state 'paused' soll nur noch gemäß automatisierter Regeln für saisonale Angebote erfolgen, nicht mehr händisch.

**Comment by NilsVollmer** [comment]
Als mini-Feature auf develop umgesetzt. Obacht: wir haben durch die in develop vorhandenen (unfertigen) Zuweisungen einen indirekten Feature-Freeze.
