### ISSUE TITLE
Organisationen ins Backend

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#944]
Der Umzug der Organisationen ins neue Backend soll vollzogen werden. Ziel ist es auch, dass Screening dann nicht mehr in irgendwelchen Google-Docs arbeitet, sondern alles direkt im Backend aufnimmt.

Die folgenden Felder sollen dabei von Screening ausgefüllt werden (nur für die Reihenfolge/User Flow wichtig):
- Name der Organisation [string]*
- Webseite [has_one Verknüpfung]*
- Standort [has_many Verknüpfung]**
- Contact People [has_many Verknüpfung]**
- 'Nicht-Bearbeitungsgrund' (pending_reason?) (instabil, onhold, Ausland) [string]
- Notes [has_many Verknüpfung] -- oder einfach *Textfeld*
- Hohe Priorität [boolean]
- Divisions (vormals Abteilungen) [has_many Verknüpfung] {Pflichtfeld außer data}

Die folgenden Felder sollen dann von den Researchern ausgefüllt werden:
- Description [text]**
- Legal Form [string]**
- Charitable [boolean]
- Umbrella [has_and_belongs_to_many Verknüpfung]

Das folgende Feld soll wenn, dann von Comms ausgefüllt werden:

- Mailings [boolean] --> 'enabled' ist default, d.h. sobald alle Divisions 'done' sind wird das Mailing für die Orga versendet, es sei denn, es wurde vorher auf 'disabled' gesetzt.

      * Pflichtfeld um speichern zu können
      ** Pflichtfeld um approven zu können

Offene Fragen: 
- Kann man einen sinnvollen Dublettencheck einbauen? Einige Ideen:

--> Name identisch (wäre hier auch eine 98% Check möglich?)
--> Über Location (Name, Zip, Straße) gehen?
--> Über Webseite gehen?
--> All of the above (in Verknüpfung)?

+ "data" state! -> Wird nur aufgenommen, um sich in Erinnerung zu behalten, dass Orga ausland ist

**Comment by KonstantinKo** [comment]
Kooperationsorganisation[en]: Seriously? Orgas haben andere Orgas? Reicht da nicht umbrella? Haben wir doch vorher auch nicht aufgenommen.
Reichweite: Ist das nicht encounter? (personal/remote)?

Dublettencheck: Ja, über Levenshtein-Distanz kann man prozentual vergleichen. Dauert aber immer länger je mehr Organisationen wir haben.
Verknüpfung muss genauer definiert werden. (Müssen alle checks stimmen oder nur Teile davon)

**Comment by Twiek** [comment]
Kooperationsorganisationen sind raus. 
Abteilungen sollen nicht mehr Abteilungen heißen da hier zu viel Verwirrung entstehen kann, wenn die Orga selbst auch von Abteilungen spricht, diese aber ganz anders definiert wie wir. Neuer Name 'Unit' bzw. 'Units' (sowohl in deutscher als auch in englischer Sprache).

**Comment by Twiek** [comment]
Welt wird nicht explizit vergeben sondern indirekt aus den Units (Abteilungen) gezogen.

**Comment by KonstantinKo** [comment]
DEPLOY TODO:

- Ensure every organization has only one hyperlink (and thus website) before db:migrate

**Comment by Twiek** [comment]
Bitte die Verknüpfung mit allen Webseiten lösen die nicht den host 'own' haben (dürfte nur eine pro Organisation sei). Die anderen wenn, dann nur dann löschen, wenn keine andere Verknüpfung, z.b. zu einem Angebot besteht. Die URLs der getrennten Webseiten bitte in die Notizen der Organisationen packen.

**Comment by KonstantinKo** [comment]
TODO: Location zum initialen Pflichtfeld machen, ist nicht ganz trivial.
