### ISSUE TITLE
Divisions (ehemals Abteilungen) anlegen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#945]
Die folgenden Datenfelder sollten für Abteilungen zu bearbeiten sein:
- Name [string]*
- Organisation [has_one Verknüpfung]*
- Welt [has_one Verknüpfung]*
- Stadt [belongs_to]* (eins von beiden)
- Area [belongs_to]* (eins von beiden)
- Webseiten [has_many Verknüpfungen]
- Problemkategorien [has_many Verknüpfung]
- Lösungskategorien [has_many Verknüpfung]
- Notes [has_many Verknüpfung] -- oder einfach Textfeld
- Done [boolean]
- Size (small, medium, large) [string]

```
* = Pflichtfeld (vor dem Abspeichern)
```

Deploy Todo:
Im Rahmen des automatischen Anlegens von Divisions für bestehende Organisationen (max. 1 Family- + max. 1 Refugees-Division) soll die Größe wie folgt festgelegt werden:

small = 2 Angebote (ref/fam)
medium = < 10 Angebote (ref/fam)
large > 10 Angebote (ref/fam)

**Comment by KonstantinKo** [comment]
Welt: Sollte keine has_many Verknüpfung sein sonder 1-n. Da fanden ja schon lange Diskussionen statt.

**Comment by Twiek** [comment]
- Description fällt raus (Note und Zuweisungstext reicht).

**Comment by KonstantinKo** [comment]
Deploy TODO:

```ruby
Organization.find_each do |orga|
  orga.section_filters.each do |sf|
    orga.divisions.create(name: "default (#{sf.identifier})", section_filter: sf)
  end
end
```

**Comment by Twiek** [comment]
Habe gerade noch ein Feld ergänzt: 'Done' [boolean]. Hintergrund ist, dass Organisationen perspektivisch automatisch in den all-done state versetzt werden soll (löst das Versenden der Benachrichtigungs-Mails aus). Dies soll passieren, wenn alle Divisions fertig ('done') sind.

**Comment by Twiek** [comment]
Alternative wäre natürlich auch hier eine State-Machine anzudocken. Vor Umsetzung bitte noch mal diskutieren (auch das Screening-Team überlegt noch).

**Comment by Twiek** [comment]
Nope, keine States. 'Done' ist und bleibt nen boolean.

**Comment by Twiek** [comment]
- Featurewunsch: Abhänging von der ausgewählten Welt wird ein Vorschlag gemacht, wem die Division nach Erstellung zugewiesen wird. Default wäre das jeweilige Welten-Team (z.B. 'Team Family'). Dies kann jedoch manuell geändert und die Division auf einer Einzelperson zugewiesen werden.

**Comment by Twiek** [comment]
Size ist hinzugekommen.

**Comment by Twiek** [comment]
Note to self: Wie werden Kooperationsangebote angelegt. Haben die Split-Bases potentiell mehrere Divisions, die Divisions mehrere Orgas... ?

**Comment by Twiek** [comment]
Nachdem eine Division erstellt wurde wird direkt eine entsprechende Zuweisung für das 'Team family' oder das 'Team refugees' erstellt. Will Screening da noch mal ran, müssen sie es sich aktiv zurückholen.

**Comment by Twiek** [comment]
Feld 'Stadt' ergänzt.

**Comment by Twiek** [comment]
Feld 'Stadt' hinzugefügt.

**Comment by Twiek** [comment]
Zu klären: Werden die Angebote einer Orga gemäß section auch gleich den automatisch erstellten Divisions zugeordnet (und die direkte Veknüpfung Orga/Angebot gekappt?)?

**Comment by NilsVollmer** [comment]
Update nach Rücksprache mit Screening:
- Feld Area hinzugefügt (Stadt oder Area muss gesetzt sein)

Betrifft online-only Orga's (bzw. deren Divisions) und wir wollen nicht sowas wie Stadt 'Bundesweit' haben.

**Comment by Twiek** [comment]
Deploy-TODO ergänzt.
