### ISSUE TITLE
Safari-Fehler

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#95]
Wenn ich auf der Startseite auf ein Icon klicke (z.B. 'Akute Krise') und dann auf der darauf folgenden Suchergebnisseite wieder auf das Logo (oben links) um auf die Startseite zu kommen, dann ist dort das Design der Icons etwas zerschossen (siehe Screenshot). Scheint nur bei Safari auf dem Mac aufzutreten.

![bildschirmfoto 2015-01-14 um 16 38 37](https://cloud.githubusercontent.com/assets/432388/5741554/254c850c-9c0c-11e4-99e4-8c6cf0f68f6c.png)

**Comment by marcus-herrmann** [comment]
Entspricht das #65?

**Comment by Twiek** [comment]
Ja.
