### ISSUE TITLE
Darstellungsfehler

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#951]
Bei der Liste der Angebote: https://www.clarat.org/family/organisationen/gsj-gesellschaft-fuer-sport-und-jugendsozialarbeit

![image](https://cloud.githubusercontent.com/assets/432388/20003100/cb6436c6-a284-11e6-95a4-e17d0c798adf.png)

**Comment by marcus-herrmann** [comment]
Vermutlicher Fix (deswegen nicht als Hotfix committed) liegt auf https://github.com/clarat-org/clarat/tree/fix/951-offer-list-fix bereit, es wäre ideal, wenn dieser Branch mal kurz auf staging könnte (nach dem viel wichtigeren #931-Umbau natürlich)

**Comment by Twiek** [comment]
Habe es auf Staging deployed, aber da sieht es noch genauso aus... (https://staging.clarat.org/family/organisationen/gsj-gesellschaft-fuer-sport-und-jugendsozialarbeit).

**Comment by marcus-herrmann** [comment]
> Habe es auf Staging deployed, aber da sieht es noch genauso aus... (https://staging.clarat.org/family/organisationen/gsj-gesellschaft-fuer-sport-und-jugendsozialarbeit).

Immer noch kaputt, aber tatsächlich *anders* kaputt ;) Bin dran.

**Comment by marcus-herrmann** [comment]
Habe gerade einen neuen Commit gepusht, der das Problem entgültig lösen sollte. Auch hier macht ein kurzes Deploy auf staging Sinn

**Comment by NilsVollmer** [comment]
Jetzt wie gewünscht? 
https://www.clarat.org/family/organisationen/gsj-gesellschaft-fuer-sport-und-jugendsozialarbeit
