### ISSUE TITLE
Change state via console?

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#952]
Kann man den aasm_state eine Organisation (konkret: 838) von 'all_done' wieder auf 'approved' setzen und wenn ja wie und was muss man beachten?

**Comment by KonstantinKo** [comment]
Man kann es nur indirekt über internal_feedback, external_feedback, oder under_construction_post machen. Wenn ein neuer state_change dazu kommen soll, würde ich am liebsten auf Nils warten zum absprechen da er in der ganzen state Materie mehr drin steckt als ich

**Comment by KonstantinKo** [comment]
Feedback von Nils: State change einbauen ist wahrscheinlich kein Problem.

ABER: Wir haben diskutiert, ob die Aussage "Wir glauben, dass in diesem Moment alles fertig ist" (und es kann sich ja doch mal ändern wenn neue Städte hinzugenommen werden, es neue Randland entscheidungen gibt, etc.) nicht doch eher mit einem boolean abgedeckt werden sollte.

Das ganze System kann sich aber auch mit Abteilungen eh komplett ändern, da eventuell die "fertig" Information dorthin verschoben wird.

**Comment by Twiek** [comment]
Schauen ob/wie das mit Divisions etc. relevant ist.
