### ISSUE TITLE
Bug: family-Logo auf Landing Page wird im Firefox verzerrt

### ISSUE THREAD

**Issue by NilsVollmer** [clarat-org/clarat#957]
Es wird anscheinend breiter gezerrt als es ist:

![image](https://cloud.githubusercontent.com/assets/1733220/20394982/ad7af3b8-ace1-11e6-8478-5882afc3cc66.png)

Nur im Firefox beoachtet (in Chrome & Safari wird es wie gewünscht dargestellt)

**Comment by marcus-herrmann** [comment]
Taucht wo auf - Featurebranch 931, live?

**Comment by NilsVollmer** [comment]
Develop/Master/live aber das hast du anscheinend schon selbst gemerkt :)

**Comment by marcus-herrmann** [comment]
Als hotfix auf **develop**
