### ISSUE TITLE
neue Sprache anlegen – Aramäisch

### ISSUE THREAD

**Issue by MichiBecker** [clarat-org/clarat#958]
Aramäisch
ISO639-2 Code arc
ܠܶܫܳܢܳܐ ܐܳܪܳܡܳܝܳܐ

Danke

**Comment by NilsVollmer** [comment]
TODO: clarat_base in claradmin ziehen und nach dem deploy per konsole den Sprachfilter anlegen:
```ruby
LanguageFilter.create! identifier: 'arc', name: 'Aramäisch'
```
