### ISSUE TITLE
Statistik-Seite im Backend

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#961]
- Öffentlich für alle Backend-User
- Keine personenbezogenen Daten
- Müssen nicht live berechnet werden. Einmal pro Tag bzw. Nacht reicht

- [x] Anzahl der Orgas getrennt nach states und Welten, also z.B. 'State: completed | Refugees: 123 | Family: 12 | Gesamt: 135' 

- [x] Anzahl der Angebote getrennt nach states und Welten, also z.B. 'State: completed | Refugees: 123 | Family: 12 | Gesamt: 135'

- [x] Durchschnittliche Anzahl der Angebote pro Orga im 'all done' state getrennt Welten der Orga (states der Angebote ist egal), also z.B. 'State: all-done | Refugees: 3,51 | Family: 1,24 | Gesamt: 3,03'. Für die Welt nur die Angebote berücksichtigen die zumindest auch der Welt zugeordnet sind (Zwischenweltangebote zählen somit doppelt).

**Comment by Twiek** [comment]
Ist komplett deployed, oder?

**Comment by KonstantinKo** [comment]
Noch nicht komplett, nein. Gestern kamen noch ein paar fixes dazu.

**Comment by Twiek** [comment]
Leider noch mal ergänzende Featurewünsche. Folgendes soll ergänzt werden:

- [ ] Gesamtzahl über alle States ergänzen
- [ ] Sämtliche Seiten, also 'offer_overview', 'organizaton_overview' und 'ratio_overview' zusätzlich noch mal einzeln für die folgenden Städte anzeigen (ob auf eigener, verlinkten Unterseite oder im Rahmen eines Filters sei Dir überlassen): Berlin, Köln, München, Düsseldorf.

**Comment by NilsVollmer** [comment]
@Twiek Kann das hier zu?
