### ISSUE TITLE
SSL-Probleme ohne www.

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#962]
Wenn ich https://clarat.org/ aufrufe gibt es ne Warnung, dass es sich um keine sichere Verbindung handelt:

<img width="962" alt="bildschirmfoto 2016-11-24 um 10 19 02" src="https://cloud.githubusercontent.com/assets/432388/20592731/736c4ad4-b22f-11e6-957f-7dcd01c6146f.png">

**Comment by KonstantinKo** [comment]
Fixed by Kevin. All hail Kevin.
