### ISSUE TITLE
Target Audience Filter "Angehörige" + Alter des Kindes visible: Frontend Output anpassen

### ISSUE THREAD

**Issue by MichiBecker** [clarat-org/clarat#963]
Hallo zusammen,

analog zur Target Audience "Eltern" brauchen wir für "Angehörige" folgenden Output im Frontend, wenn das Alter des Kindes für dieses Angebot begrenzt ist und deshalb visible sein muss

für Bekannte und Verwandte (Alter des Kindes: x - x Jahre)

Bis jetzt steht da nur "Für Bekannte und Verwandte" auch wenn Age visible ist und Gender 2nd part of stamp gesetzt hat.

Versteht man das? Falls nicht, nachfragen :)

Merci

**Comment by NilsVollmer** [comment]
@Twiek Am besten direkt im Zusammenhang mit der Überarbeitung der Stamps für refugees zu erledigen. Die beiden Issue dann gerne mir zuweisen und (falls nötig) Prio aktualisieren.

**Comment by NilsVollmer** [comment]
Deploy TODO: reindex
``` ruby
TargetAudienceFilter.find_by(identifier: 'family_acquaintances').offers.where(gender_second_part_of_stamp: 'neutral').where(age_visible: true).map(&:index!)
```

**Comment by NilsVollmer** [comment]
@MichiBecker Just to be sure neu soll also Folgendes passieren:
ta = 'family_acquaintances' + gender_second_part_of_stamp == 'neutral' + age_visible == true => 'für Angehörige (Alter des Kindes: X - Y Jahre)'

Nur in dieser Kombination & sonst nicht. Korrekt?

**Comment by NilsVollmer** [comment]
Zusammen mit #941 umgesetzt.
