### ISSUE TITLE
FE-Optimierungen für Page Speed Insights 

### ISSUE THREAD

**Issue by marcus-herrmann** [clarat-org/clarat#965]

**Comment by marcus-herrmann** [comment]
Versuche Microoptimierung durch DNS prefetch und ein versetztes Laden der fontawesome.css: https://github.com/clarat-org/clarat/tree/feature/965-performance

**Comment by Twiek** [comment]
Nach Deploy schauen ob es was gebracht hat. Vorher:

![bildschirmfoto 2017-01-27 um 10 43 59](https://cloud.githubusercontent.com/assets/432388/22366555/9f104dae-e47d-11e6-8dcc-cd56aa6a31dc.png)

**Comment by Twiek** [comment]
Zumindest mal besser:
![bildschirmfoto 2017-01-27 um 17 26 23](https://cloud.githubusercontent.com/assets/432388/22378396/c68f5e32-e4b5-11e6-8693-d23ea1e42356.png)
