### ISSUE TITLE
Suchanfrage mit Alter des Kindes ausgewählt liefert 0 Ergebnisse

### ISSUE THREAD

**Issue by MichiBecker** [clarat-org/clarat#966]
Wenn ich in den Suchfiltern Alter des Kindes auswähle, wird nach abschicken der Suchabfrage (Klick auf Lupe) eine leere Suchergebnisseite angezeigt.

Live Update der Suchergebnisse funktioniert nach Filtereingabe, nur eben wenn man nochmal die Lupe drückt, wird nichts angezeigt - was ja durchaus passieren kann, falls man nicht checkt, dass sich die Suchergebnisse schon automatisch angepasst haben.

**Comment by MichiBecker** [comment]
Update: passiert nicht nur bei "Alter des Kindes" sondern auch bei anderen Filtern.

**Comment by NilsVollmer** [comment]
Wir hatten die Limits unseres Suchanbieters überschritten und deshalb dürfte die komplette Suche gestern kurzzeitig nicht funktioniert haben. Wir mussten ein paar staging indizes löschen und sind somit jetzt erst einmal wieder deutlich unter den Limits.

Basti hat Algolia zwecks einer längerfristigen Lösung angeschrieben.

**Comment by KonstantinKo** [comment]
Nope, glaube nicht dass der Fehler nur an Algolia liegt. Der JS Fehler `Cannot read property 'target' of undefined` könnte auch von woanders kommen. Lass mich liber mal nachschauen.

**Comment by KonstantinKo** [comment]
Hotfix auf master & deployed

**Comment by NilsVollmer** [comment]
Habe gerade noch auf production geschaut und der Fehler tritt nicht mehr auf.
