### ISSUE TITLE
neue Sprache

### ISSUE THREAD

**Issue by MichiBecker** [clarat-org/clarat#967]
Abchasisch
аҧсуа бызшәа
ISO 639-1: ab
ISO 639-2: abk
ISO 639-3: abk

Merci :)

**Comment by NilsVollmer** [comment]
DeployTodo:

´´´console
LanguageFilter.create!(identifier: 'fuf', name: 'Pular')
LanguageFilter.create!(identifier: 'abk', name: 'Abchasisch')
´´´
