### ISSUE TITLE
Mehrsprachigkeits-Warnhinweis verschärfen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#969]
Den Cookie bitte insofern verschärfen, dass er nur die aktuelle Session durchhält. Wenn ich 3 Stunden nach meinem letzten Besuch auf clarat mit dem gleichen Rechner und dem gleichen Browser auf die Seite gehe, dann sollte der Warnhinweis erneut erscheinen.

**Comment by marcus-herrmann** [comment]
Wie im Dezember besprochen: auf 2h lifetime gesetzt: https://github.com/clarat-org/clarat/tree/feature/969-cookie-expiry
