### ISSUE TITLE
Share bar in mobile

### ISSUE THREAD

**Issue by MichiBecker** [clarat-org/clarat#971]
Problem/Irritation: 

Wenn der Share bar neben den Next Steps angezeigt wird und dort auch noch steht "schreibe eine E-Mail..." wird der "per Mail teilen" Button fehlinterpretiert als "Hier kann ich ja gleich die Mail schreiben"

Schnellschuss Gedanke:
Vielleicht kann man den Share bar doch als horizontalen Balken unter der Headline oder unter der Description anzeigen.

Github angelegt, damit es nicht verloren geht.

![screenshot 2016-11-24 at 12 23 42](https://cloud.githubusercontent.com/assets/20815293/21193267/00842782-c22c-11e6-8589-86d9a2471b5b.png)

**Comment by Twiek** [comment]
Würde hier wenn dann für ein 'ganz klassisches' Design plädieren. Z.B. wie bei der Huffingtonpost:

![bildschirmfoto 2017-01-04 um 16 20 45](https://cloud.githubusercontent.com/assets/432388/21681452/90f48f58-d34f-11e6-9b4a-98f1a38399f0.png)

**Comment by MichiBecker** [comment]
find ich auch gut!

**Comment by marcus-herrmann** [comment]
Vorschlag: Browserbreite kleiner 750px:

<img width="378" alt="bildschirmfoto 2017-01-18 um 13 40 09" src="https://cloud.githubusercontent.com/assets/505181/22064426/d55d2130-dd83-11e6-8eb9-7e659e403446.png">

Wäre hier zu finden. Bei Gefallen erstelle ich nach Browsertesting einen PR: https://github.com/clarat-org/clarat/tree/feature/971-revamp-shariff-mobile

**Comment by marcus-herrmann** [comment]
<img width="371" alt="bildschirmfoto 2017-01-18 um 14 38 32" src="https://cloud.githubusercontent.com/assets/505181/22066133/d3ce2672-dd8b-11e6-807d-1eb021c86138.png">

Die Buttons könnten jetzt auf Desktop sowie auf mobile die "Kanal-Farben" bekommen (nicht erst on hover, wie bisher). Damit geht es ein bisschen mehr in Richtung HuffPo

**Comment by marcus-herrmann** [comment]
PR wird gleich gestellt, hier der umgesetzte Stand:

![localhost-3000-family-angebote-hilfe-fuer-opfer-von-gewalt iphone 6](https://cloud.githubusercontent.com/assets/505181/22328621/770093de-e3bd-11e6-80c5-a98fc83c7634.png)
<img width="1105" alt="bildschirmfoto 2017-01-26 um 11 35 49" src="https://cloud.githubusercontent.com/assets/505181/22328623/7701c240-e3bd-11e6-932e-0b4696a69136.png">
<img width="167" alt="bildschirmfoto 2017-01-26 um 11 35 59" src="https://cloud.githubusercontent.com/assets/505181/22328622/770182bc-e3bd-11e6-9da0-d72cb720c7c7.png">
