### ISSUE TITLE
Änderung Absender + Signatur Anschreiben Sendgrid

### ISSUE THREAD

**Issue by MichiBecker** [clarat-org/clarat#973]
Hallo,

bitte die Absenderadresse der Orga-Anschreiben von

schulze@clarat.org auf

**post@clarat.org** 

ändern und in der Signatur statt

Anne Schulze bitte

**clarat-Team**

Grund: Alle wollen immer mit einer gewissen Frau Schulze sprechen bei Rückfragen ;)

**Comment by Twiek** [comment]
@MichiBecker Müssen wir hier noch jemanden informieren und wenn ja, kannst Du das bitte übernehmen.

**Comment by MichiBecker** [comment]
Hi Basti, ich gebe Janina Heppner bescheid. Die Anfrage kam von Comms.
