### ISSUE TITLE
Update auf Rails 5.X

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#975]

**Comment by mokus80** [comment]
Base wurde reviewed und in develop gemergt, Vorsicht hier!

Claradmin wurde gestern getestet, Fehler, die es nicht auch auf Produktion gibt, wurden keine gefunden. Kann also auf Produktion.

Bei Clarat habe ich momentan noch das Problem, dass Javascript nicht compiliert wird. Lokal und auf in der Produktionsumgebung (heroku config:set RAILS_ENV=production --remote staging) funktioniert es. Außerdem muss Clarat noch getestet werden, da es hier nach Marcus' Änderungen viele Mergekonflikte gab.

**Comment by KonstantinKo** [comment]
Claradmin deployed
