### ISSUE TITLE
Bug: Kategorie-Vorschlag-Funktion für Angebote funktioniert nicht (und wirft Fehler)

### ISSUE THREAD

**Issue by NilsVollmer** [clarat-org/clarat#978]
Den Fehler habe ich jetzt schon oft in den Logs gesehen. Er scheint nicht direkt zu einem Problem zu führen aber wir wollen das Backend natürlich Fehlerfrei halten ;)

Bsp.:
``` console
» 10 Jan 2017 11:55:09.617 215 <190>1 2017-01-10T10:55:09.108718+00:00 app web.1 - - Started GET "/categories/Beratung%20bei%20Sorgen%20und%20Problemen.json" for 213.148.154.178 at 2017-01-10 10:55:09 +0000
» 10 Jan 2017 11:55:09.618 94 <190>1 2017-01-10T10:55:09.116240+00:00 app web.1 - -
» 10 Jan 2017 11:55:09.618 193 <190>1 2017-01-10T10:55:09.116242+00:00 app web.1 - - AbstractController::ActionNotFound (The action 'show' could not be found for CategoriesController):
» 10 Jan 2017 11:55:09.618 193 <190>1 2017-01-10T10:55:09.116243+00:00 app web.1 - - vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:132:in `process'
» 10 Jan 2017 11:55:09.618 189 <190>1 2017-01-10T10:55:09.116244+00:00 app web.1 - - vendor/bundle/ruby/2.3.0/gems/actionview-4.2.7.1/lib/action_view/rendering.rb:30:in `process'
» 10 Jan 2017 11:55:09.618 193 <190>1 2017-01-10T10:55:09.116244+00:00 app web.1 - - vendor/bundle/ruby/2.3.0/gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:196:in `dispatch'
(...)
```

**Comment by NilsVollmer** [comment]
Fun Fact: die Kategorie, die da angefragt wird ('Beratung bei Sorgen und Problemen') gibt es gar nicht.

**Comment by NilsVollmer** [comment]
Update: der Fehler tritt über den ganzen Tag verteilt relativ regelmäßig auf und anscheinend sind die Titel immer Angebotstitel (z.B. 'Beratung bei Sorgen und Problemen'), mit denen die show operation der Kategorien aufgerufen werden soll. Das klappt dann natürlich nicht.

Nächster Schritt wäre, die Vorkommnisse einzuschränken (z.B. nur bei neuen Angeboten?) um die möglichen Fehlerquellen einzuschränken.

Da der Fehler aber so oft auftritt, scheint er aber keine direkten Auswirkungen auf die Researcher zu haben.

**Comment by NilsVollmer** [comment]
Update2: okay Fehler gefunden: wir haben ja mal so eine Kategorie-Vorschlag-Funktion bei Angeboten eingebaut, die bei identischen Titel Kategorien vorschlägt. Das ist es offenbar, was nicht funktioniert. Der entsprechende Code im neuen (nicht-v1) Backend ist auskommentiert:

```ruby
  # # For admin backend: Provides a list of categories that offers with name X
  # # already belong to.
  # def index
  #   offer_categories = Offer.where(name: params[:offer_name])
  #                      .joins(:categories).pluck('DISTINCT(categories.name_de)')
  #
  #   respond_with offer_categories
  # end
```

**Comment by Twiek** [comment]
Rausschmeißen oder zumindest auskommentieren.

**Comment by NilsVollmer** [comment]
War dann doch mit relativ geringem Aufwand noch zu retten und funktioniert jetzt wieder.
