### ISSUE TITLE
Bing Webmaster Tools snippet integrieren

### ISSUE THREAD

**Issue by MichiBecker** [clarat-org/clarat#982]
Hallo zusammen,

analog zu Google Analytics möchte Eleonore auch für Bing ein Snippet bei clarat haben.

Bitte einplanen im nächsten Sprint...das wär so ne Mini Aufgabe für den Puffer :)

<meta name="msvalidate.01" content="2EF21E72D848CCA021AC432F95FA63EA" />

**Comment by allthegoldt** [comment]
Hallo Michi, würde ich gerne machen, aber dafür bräuchte ich den Code, den ich einfügen sollte. Bitte dem Ticket hinzufügen. Viele Grüße Damjan

**Comment by MichiBecker** [comment]
hoppla! Natürlich bekommst du den:

<meta name="msvalidate.01" content="2EF21E72D848CCA021AC432F95FA63EA" />

Muss in den <head> aber das weißt du eh...
