### ISSUE TITLE
Orga-Name im Frontend hat Probleme mit rtl-direction

### ISSUE THREAD

**Issue by NilsVollmer** [clarat-org/clarat#983]
Hassen & Nahla waren gerade bei mir und haben darauf hingewiesen:

![image](https://cloud.githubusercontent.com/assets/1733220/21929073/d154fc32-d98e-11e6-81ec-8f8fea608001.png)

Der zweite Punkt von e.V. rutscht vor den gesamten Text.. scheint ein komisches Verhalten der rtl-direction mit deutschem Text zu sein.

Möglicher Fix: da Orga-Namen ja immer auf deutsch bleiben & nicht übersetzt werden, könnte man für den Namen die direction wieder auf ltr und text-align:right einstellen (natürlich nur für arabisch & farsi). Damit würde es korrekt aussehen.

Aber vllt. fällt @marcus-herrmann ja eine bessere Lösung ein.

PS: nicht wundern: in der Description passiert das auch aber da haben die Übersetzer eine pragmatische Lösung für gefunden, die sie anwenden werden (Punkt VOR den Text produziert das gewünschte Aussehen). 

@Twiek : bitte priorisieren und zuweisen ;)

**Comment by marcus-herrmann** [comment]
Der Punkt wird als Satzbeendungspunkt/Satzzeichen verstanden, nicht als Bestandteil der Abkürzung "e.V.". @NilsVollmer s Vorschlag kann man anwenden, aber dann entsteht ein Mix, weil der Organame auch im "Was macht die Organisation"-Container vorkommt:

![bildschirmfoto 2017-01-18 um 12 03 09](https://cloud.githubusercontent.com/assets/505181/22061702/7e5d33fa-dd76-11e6-8dd9-dd6b81e49542.jpg)

**Comment by Twiek** [comment]
Die Orgaseite ist allerdings deutlich weniger wichtig als die Angebotsseite, d.h. dort können wir fehlertoleranter sein. Insofern bitte den Vorschlag von Nils umsetzen.
