### ISSUE TITLE
Hinweis, dass Datenschutz etc. nicht übersetzt wird

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#984]
Wir brauchen auf den folgenden Seiten customized Hinweise, dass sie nicht übersetzt werden (in allen Sprachen):

https://www.clarat.org/family/impressum
https://www.clarat.org/family/rechtliche-hinweise
https://www.clarat.org/family/datenschutzhinweise

Der Text 'Automated translations! On clarat, some of the texts in your language have been translated by Google Translate. These texts might sound a bit strange sometimes. Or the language might be a bit wrong.' soll ersetzt werden. Vorläufiger Platzhalter: 'Rechtstexte kannst du bei uns nur auf Deutsch lesen.'. Dieser Text sollte immer erscheinen, wenn ich in nicht deutscher Einstellung auf eine dieser Seiten gehe, egal ob ich vor 5 Minuten schon mal da war.

**Comment by marcus-herrmann** [comment]
Auf https://github.com/clarat-org/clarat/tree/feature/984-legal-text-notice zu sehen - da ist aktuell noch dein Textvorschlag hart im Template - letztendlich würde ich die Node in der Übersetzung dafür nutzen. Hätte ich das aber jetzt schon gemacht, wäre der neue Text via localeapp schon "live" gegangen.

**Comment by marcus-herrmann** [comment]
Missverständnis korrigiert, Branch aktualisiert.
