### ISSUE TITLE
Expired Angebote im Frontend anzeigen

### ISSUE THREAD

**Issue by Twiek** [clarat-org/clarat#986]
Angebote im state 'expired' sollen künftig weiterhin im Frontend sichtbar sein, d.h. für den Enduser sind sie nicht von Angeboten im state 'approved' zu unterscheiden. Sie sind über die clarat Suche, Link, Google auffind- und aufrufbar. Dies gilt auch rückwirkend für alle Angebote die sich aktuell in diesem Zustand befinden.

Für die Prozesse/Auswertungen im Backend soll sich hingegen nichts ändern. Es sollen weiterhin Asana Tasks erstellt werden, sie sollen in den Statistiken gesondert aufgeführt werden etc. Auch das Wordding bleibt gleich, da sonst Bibel, Manual etc. geändert werden müssten.

**Comment by NilsVollmer** [comment]
Relevant: wenn wir alle aktuell exired Angebote wieder anzeigen wollen, sprengen wir definitiv unseren Record Threshold bei Algolia.

**Comment by NilsVollmer** [comment]
https://developers.google.com/web/fundamentals/native-hardware/user-location/

**Comment by Twiek** [comment]
Hier noch mal die explizite Bestätigung, dass auch Angebote in der Version 'Sprache' sichtbar gemacht werden sollen (und natürlich in den Versionen darüber).

**Comment by NilsVollmer** [comment]
Okay dann muss ich definitiv den Ball an dich zurückspielen: wir können das dann nicht deployen, ohne vorher mit Algolia zusammen eine Lösung für den Threshold gefunden zu haben.

Mit ca. 2k mehr Angeboten * 7 Sprachen sprengen wir definitiv unseren Record-Count.

Code ist soweit fertig, kann aber nicht merged/deployed werden, bevor das gelöst ist.

**Comment by Twiek** [comment]
Ok, Algolia ist erledigt. Dann ist das potentiell ready für den nächsten Deploy, richtig?
