### ISSUE TITLE
Position Tooltip / Glossar-Popup in mobile Ansicht

### ISSUE THREAD

**Issue by MichiBecker** [clarat-org/clarat#987]
Hi Markus,

Basti hat mir folgenden Screenshot geschickt.
Da läuft irgendwas mit der Positionierung falsch.

![screenshot_2017-01-24-14-58-36](https://cloud.githubusercontent.com/assets/20815293/22262187/27c0f10e-e270-11e6-99d7-d5360328e914.png)

lg
Michi

**Comment by Twiek** [comment]
Scheint leider auch noch nicht behoben:

![bildschirmfoto 2017-03-02 um 14 03 15](https://cloud.githubusercontent.com/assets/432388/23508253/18cda8f6-ff51-11e6-9e1d-705844652fcc.png)

**Comment by marcus-herrmann** [comment]
Als Hotfix auf develop.

**Comment by NilsVollmer** [comment]
Ich bin gerade dabei, den deploy vorzubereiten. Kann das ohne Ausprobieren mit deployed werden?

**Comment by marcus-herrmann** [comment]
Ja. Commit besteht nur aus Config des Tooltip Plugins

**Comment by Twiek** [comment]
Denke das reicht erstmal, aber für den Hinterkopf sei gesagt, dass 100% der Fehler leider noch nicht behoben werden. Hier ein aktueller Screenshot von meinem LG G3 (Chrome auf Android):

![screenshot_2017-03-06-11-54-58](https://cloud.githubusercontent.com/assets/432388/23607194/32db3a68-0264-11e7-921b-e1102d956b87.png)

https://www.clarat.org/family/angebote/wohngruppe-fuer-queere-identitaeten (Klick auf SGB VIII am Ende der Beschreibung).
