### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by JaninaHeppner** [clarat-org/clarat#99]
Nächstes Mal dann mit Screenshot

**Comment by Twiek** [comment]
Ist das nicht das gleiche Issue wie #100? ;-)

**Comment by JaninaHeppner** [comment]
Hallo Basti,

sorry, ich war ein bisschen langsam mit der Antwort. Der clarat-Gruppe bei
github bin ich beigetreten und bei mite habe ich mich angemeldet und meine
Stunden eingetragen. Hat soweit alles funktioniert. Jetzt muss sich bloß
noch der workflow einstellen;)

Beste Grüße
Janina

2015-01-20 14:56 GMT+01:00 Sebastian Schwiecker <notifications@github.com>:
